{
  "abstract": [
    {
      "text": "A constant that indicates UPC-E symbology.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/UPCE-7qps5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "s:So18VNBarcodeSymbologya6VisionE4UPCEABvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UPCE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNBarcodeSymbology",
        "text": "VNBarcodeSymbology"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "iOS",
        "renamed": "upce",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "iPadOS",
        "renamed": "upce",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "renamed": "upce",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.13",
        "name": "macOS",
        "renamed": "upce",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "tvOS",
        "renamed": "upce",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "upce",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "UPCE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UPCE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNBarcodeSymbology",
              "text": "VNBarcodeSymbology"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology": {
      "abstract": [
        {
          "text": "The barcode symbologies that the framework detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeSymbology",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Aztec-6g0vi": {
      "abstract": [
        {
          "text": "A constant that indicates Aztec symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Aztec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Aztec-6g0vi",
      "kind": "symbol",
      "role": "symbol",
      "title": "Aztec",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/aztec-6g0vi"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code128-7spp7": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code128"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code128-7spp7",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code128",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code128-7spp7"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39-34358": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39-34358",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39-34358"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39Checksum-2jrn": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology with a checksum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39Checksum-2jrn",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39checksum-2jrn"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCII-m5wd": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39FullASCII"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCII-m5wd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39FullASCII",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullascii-m5wd"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCIIChecksum-5xnfs": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology with a checksum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code39FullASCIIChecksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCIIChecksum-5xnfs",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code39FullASCIIChecksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullasciichecksum-5xnfs"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93-67nn0": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code93"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93-67nn0",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code93",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93-67nn0"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93i-84cmv": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93i symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code93i"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93i-84cmv",
      "kind": "symbol",
      "role": "symbol",
      "title": "Code93i",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93i-84cmv"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/DataMatrix-2fgc9": {
      "abstract": [
        {
          "text": "A constant that indicates Data Matrix symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/DataMatrix-2fgc9",
      "kind": "symbol",
      "role": "symbol",
      "title": "DataMatrix",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/datamatrix-2fgc9"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN13-8ir8e": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-13 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAN13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN13-8ir8e",
      "kind": "symbol",
      "role": "symbol",
      "title": "EAN13",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean13-8ir8e"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN8-4rzbb": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-8 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAN8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN8-4rzbb",
      "kind": "symbol",
      "role": "symbol",
      "title": "EAN8",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean8-4rzbb"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5-1r8e7": {
      "abstract": [
        {
          "text": "A constant that indicates Interleaved 2 of 5 (ITF) symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "I2of5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5-1r8e7",
      "kind": "symbol",
      "role": "symbol",
      "title": "I2of5",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/i2of5-1r8e7"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5Checksum-832s5": {
      "abstract": [
        {
          "text": "A constant that indicates Interleaved 2 of 5 (ITF) symbology with a checksum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "I2of5Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5Checksum-832s5",
      "kind": "symbol",
      "role": "symbol",
      "title": "I2of5Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/i2of5checksum-832s5"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ITF14-1wp9s": {
      "abstract": [
        {
          "text": "A constant that indicates ITF-14 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITF14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ITF14-1wp9s",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITF14",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/itf14-1wp9s"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/PDF417-56ney": {
      "abstract": [
        {
          "text": "A constant that indicates PDF417 symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDF417"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/PDF417-56ney",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDF417",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/pdf417-56ney"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/UPCE-7qps5": {
      "abstract": [
        {
          "text": "A constant that indicates UPC-E symbology.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UPCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/UPCE-7qps5",
      "kind": "symbol",
      "role": "symbol",
      "title": "UPCE",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/upce-7qps5"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Aztec-6g0vi",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code128-7spp7",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39-34358",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39Checksum-2jrn",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCII-m5wd",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code39FullASCIIChecksum-5xnfs",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93-67nn0",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/Code93i-84cmv",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/DataMatrix-2fgc9",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN8-4rzbb",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/EAN13-8ir8e",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5-1r8e7",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/I2of5Checksum-832s5",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ITF14-1wp9s",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/PDF417-56ney"
      ],
      "title": "Deprecated Symbols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/title",
          "value": "VNBarcodeSymbology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnbarcodesymbology/upce-7qps5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
