{
  "abstract": [
    {
      "text": "The workout session has paused.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWorkoutSessionState@HKWorkoutSessionStatePaused",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "paused"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWorkoutSessionStatePaused"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKWorkoutSessionState.paused"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paused"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/pause()": {
      "abstract": [
        {
          "text": "Pauses the workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession/pause()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState": {
      "abstract": [
        {
          "text": "A workout session’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionState"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionState"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended": {
      "abstract": [
        {
          "text": "The workout session has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionStateEnded"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState.ended",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate/ended"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted": {
      "abstract": [
        {
          "text": "The workout session has not started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notStarted"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionStateNotStarted"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState.notStarted",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate/notstarted"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused": {
      "abstract": [
        {
          "text": "The workout session has paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionStatePaused"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState.paused",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate/paused"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared": {
      "abstract": [
        {
          "text": "The session is ready but not yet running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepared"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionStatePrepared"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState.prepared",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate/prepared"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running": {
      "abstract": [
        {
          "text": "The workout session is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionStateRunning"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState.running",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate/running"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped": {
      "abstract": [
        {
          "text": "The session has stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionStateStopped"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState.stopped",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate/stopped"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/pause()"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Session-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended"
      ],
      "title": "Session states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWorkoutSessionStatePaused"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStatePaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/pause()"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Session-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended"
              ],
              "title": "Session states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKWorkoutSessionStatePaused"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1stopped/title",
          "value": "HKWorkoutSessionStateStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStateStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1ended/title",
          "value": "HKWorkoutSessionStateEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStateEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1prepared/title",
          "value": "HKWorkoutSessionStatePrepared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1prepared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStatePrepared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1notStarted/title",
          "value": "HKWorkoutSessionStateNotStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1notStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStateNotStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1running/title",
          "value": "HKWorkoutSessionStateRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStateRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1paused/title",
          "value": "HKWorkoutSessionStatePaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1paused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionStatePaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/title",
          "value": "HKWorkoutSessionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkoutsessionstate/paused"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkoutsessionstate/paused"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
