{"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"modules":[{"name":"HealthKit"}],"platforms":[{"deprecated":false,"introducedAt":"17.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"17.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"17.0","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS"},{"deprecated":false,"introducedAt":"5.0","unavailable":false,"beta":false,"name":"watchOS"}],"externalID":"c:@E@HKWorkoutSessionState@HKWorkoutSessionStateStopped","title":"HKWorkoutSessionState.stopped","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStateStopped"}]},"kind":"symbol","variants":[{"paths":["/documentation/healthkit/hkworkoutsessionstate/stopped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkworkoutsessionstate/stopped"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"As soon as the session stops, the watch’s sensors return to normal, and it no longer generates workout data; however, the app can continue to run in the background, even after the user lowers their wrist.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can’t restart or reuse the workout session."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The session has stopped.","type":"text"}],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended"],"anchor":"Session-states","generated":true,"title":"Session states"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended":{"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended","title":"HKWorkoutSessionState.ended","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ended"}],"url":"/documentation/healthkit/hkworkoutsessionstate/ended","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStateEnded"}],"abstract":[{"text":"The workout session has ended.","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused":{"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused","title":"HKWorkoutSessionState.paused","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"}],"url":"/documentation/healthkit/hkworkoutsessionstate/paused","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStatePaused"}],"abstract":[{"text":"The workout session has paused.","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped":{"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/stopped","title":"HKWorkoutSessionState.stopped","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"url":"/documentation/healthkit/hkworkoutsessionstate/stopped","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStateStopped"}],"abstract":[{"text":"The session has stopped.","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared":{"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared","title":"HKWorkoutSessionState.prepared","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepared"}],"url":"/documentation/healthkit/hkworkoutsessionstate/prepared","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStatePrepared"}],"abstract":[{"text":"The session is ready but not yet running.","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState","title":"HKWorkoutSessionState","abstract":[{"text":"A workout session’s state.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HKWorkoutSessionState"}],"navigatorTitle":[{"text":"HKWorkoutSessionState","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/healthkit/hkworkoutsessionstate"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running":{"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running","url":"/documentation/healthkit/hkworkoutsessionstate/running","type":"topic","abstract":[{"type":"text","text":"The workout session is running."}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStateRunning"}],"kind":"symbol","title":"HKWorkoutSessionState.running","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"running"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted":{"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted","title":"HKWorkoutSessionState.notStarted","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notStarted"}],"url":"/documentation/healthkit/hkworkoutsessionstate/notstarted","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionStateNotStarted"}],"abstract":[{"text":"The workout session has not started.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"17.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"17.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"17.0","beta":false},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false},{"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"5.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"HKWorkoutSessionStateStopped","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"HKWorkoutSessionStateStopped","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/notStarted","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/prepared","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/running","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/paused","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState/ended"],"title":"Session states","anchor":"Session-states"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"HKWorkoutSessionStateStopped","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"HKWorkoutSessionStateEnded","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1ended/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSessionStateEnded"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1ended/fragments"},{"op":"replace","value":"HKWorkoutSessionStatePaused","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1paused/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSessionStatePaused"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1paused/fragments"},{"op":"replace","value":"HKWorkoutSessionStateStopped","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1stopped/title"},{"op":"replace","value":[{"text":"HKWorkoutSessionStateStopped","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1stopped/fragments"},{"op":"replace","value":"HKWorkoutSessionStatePrepared","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1prepared/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSessionStatePrepared"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1prepared/fragments"},{"op":"replace","value":"HKWorkoutSessionState","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/title"},{"op":"replace","value":[{"text":"HKWorkoutSessionState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/fragments"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/navigatorTitle","value":[{"text":"HKWorkoutSessionState","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1running/title","value":"HKWorkoutSessionStateRunning","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1running/fragments","value":[{"kind":"identifier","text":"HKWorkoutSessionStateRunning"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1notStarted/title","value":"HKWorkoutSessionStateNotStarted","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState~1notStarted/fragments","value":[{"kind":"identifier","text":"HKWorkoutSessionStateNotStarted"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}