{
  "abstract": [
    {
      "text": "A 7-bit control type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7Bit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDITransformControlType@kMIDIControlType_7Bit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "controlType_7Bit"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDIControlType_7Bit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDITransformControlType.controlType_7Bit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "controlType_7Bit"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType": {
      "abstract": [
        {
          "text": "A set of values that indicate how to interpret control numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDITransformControlType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDITransformControlType"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14Bit": {
      "abstract": [
        {
          "text": "A 14-bit control type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType_14Bit"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14Bit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIControlType_14Bit"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType.controlType_14Bit",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype/controltype_14bit"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitNRPN": {
      "abstract": [
        {
          "text": "A 14-bit Nonregistered Parameter Number (RPN).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType_14BitNRPN"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitNRPN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIControlType_14BitNRPN"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType.controlType_14BitNRPN",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype/controltype_14bitnrpn"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitRPN": {
      "abstract": [
        {
          "text": "A 14-bit Registered Parameter Number (RPN).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType_14BitRPN"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitRPN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIControlType_14BitRPN"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType.controlType_14BitRPN",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype/controltype_14bitrpn"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7Bit": {
      "abstract": [
        {
          "text": "A 7-bit control type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType_7Bit"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7Bit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIControlType_7Bit"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType.controlType_7Bit",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype/controltype_7bit"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitNRPN": {
      "abstract": [
        {
          "text": "A 7-bit Nonregistered Parameter Number (RPN).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType_7BitNRPN"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitNRPN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIControlType_7BitNRPN"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType.controlType_7BitNRPN",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype/controltype_7bitnrpn"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitRPN": {
      "abstract": [
        {
          "text": "A 7-bit Registered Parameter Number (RPN).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType_7BitRPN"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitRPN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIControlType_7BitRPN"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType.controlType_7BitRPN",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype/controltype_7bitrpn"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transform-Control-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14Bit",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitRPN",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitRPN",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitNRPN",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitNRPN"
      ],
      "title": "Transform Control Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDIControlType_7Bit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_7Bit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transform-Control-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14Bit",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitRPN",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitRPN",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_7BitNRPN",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType/controlType_14BitNRPN"
              ],
              "title": "Transform Control Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDIControlType_7Bit"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_14Bit/title",
          "value": "kMIDIControlType_14Bit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_14Bit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_14Bit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_7BitNRPN/title",
          "value": "kMIDIControlType_7BitNRPN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_7BitNRPN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_7BitNRPN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType/title",
          "value": "MIDITransformControlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_7Bit/title",
          "value": "kMIDIControlType_7Bit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_7Bit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_7Bit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_14BitRPN/title",
          "value": "kMIDIControlType_14BitRPN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_14BitRPN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_14BitRPN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_14BitNRPN/title",
          "value": "kMIDIControlType_14BitNRPN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_14BitNRPN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_14BitNRPN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_7BitRPN/title",
          "value": "kMIDIControlType_7BitRPN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType~1controlType_7BitRPN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIControlType_7BitRPN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/miditransformcontroltype/controltype_7bit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/miditransformcontroltype/controltype_7bit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
