{
  "abstract": [
    {
      "text": "A guide for positioning other elements with the content view image’s focused frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView/focusedFrameGuide"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVMediaItemContentView(py)focusedFrameGuide",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "focusedFrameGuide"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UILayoutGuide",
        "text": "UILayoutGuide"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "focusedFrameGuide"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "focusedFrameGuide"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "focusedFrameGuide"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UILayoutGuide",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UILayoutGuide",
              "text": "UILayoutGuide"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView": {
      "abstract": [
        {
          "text": "A view that represents media content, such as movies and TV shows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItemContentView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItemContentView"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItemContentView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmediaitemcontentview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView/focusedFrameGuide": {
      "abstract": [
        {
          "text": "A guide for positioning other elements with the content view image’s focused frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedFrameGuide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILayoutGuide",
          "text": "UILayoutGuide"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView/focusedFrameGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusedFrameGuide"
        }
      ],
      "role": "symbol",
      "title": "focusedFrameGuide",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmediaitemcontentview/focusedframeguide"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UILayoutGuide": {
      "abstract": [
        {
          "text": "A rectangular area that can interact with Auto Layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILayoutGuide"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UILayoutGuide",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILayoutGuide",
      "type": "topic",
      "url": "/documentation/UIKit/UILayoutGuide"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "focusedFrameGuide"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusedFrameGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UILayoutGuide",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UILayoutGuide",
                    "text": "UILayoutGuide"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "focusedFrameGuide"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView~1focusedFrameGuide/title",
          "value": "focusedFrameGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView~1focusedFrameGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusedFrameGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView/title",
          "value": "TVMediaItemContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UILayoutGuide/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UILayoutGuide"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvmediaitemcontentview/focusedframeguide"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvmediaitemcontentview/focusedframeguide"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
