{
  "abstract": [
    {
      "text": "Represents a local source.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKSourceType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/local"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKSourceType@EKSourceTypeLocal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "local"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKSourceTypeLocal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKSourceType.local"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "local"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType": {
      "abstract": [
        {
          "text": "The type of source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKSourceType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceType"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/birthdays": {
      "abstract": [
        {
          "text": "Represents a birthday source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdays"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/birthdays",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceTypeBirthdays"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType.birthdays",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype/birthdays"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/calDAV": {
      "abstract": [
        {
          "text": "Represents a CalDAV or iCloud source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calDAV"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/calDAV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceTypeCalDAV"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType.calDAV",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype/caldav"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/exchange": {
      "abstract": [
        {
          "text": "Represents an Exchange source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exchange"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/exchange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceTypeExchange"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType.exchange",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype/exchange"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/local": {
      "abstract": [
        {
          "text": "Represents a local source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "local"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/local",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceTypeLocal"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType.local",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype/local"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/mobileMe": {
      "abstract": [
        {
          "text": "Represents a MobileMe source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mobileMe"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/mobileMe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceTypeMobileMe"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType.mobileMe",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype/mobileme"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/subscribed": {
      "abstract": [
        {
          "text": "Represents a subscribed source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribed"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/subscribed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSourceTypeSubscribed"
        }
      ],
      "role": "symbol",
      "title": "EKSourceType.subscribed",
      "type": "topic",
      "url": "/documentation/eventkit/eksourcetype/subscribed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "EventKit-Source-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/exchange",
        "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/calDAV",
        "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/mobileMe",
        "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/subscribed",
        "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/birthdays"
      ],
      "title": "EventKit Source Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKSourceTypeLocal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKSourceType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "EventKit-Source-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/exchange",
                "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/calDAV",
                "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/mobileMe",
                "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/subscribed",
                "doc://com.apple.eventkit/documentation/EventKit/EKSourceType/birthdays"
              ],
              "title": "EventKit Source Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKSourceTypeLocal"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1exchange/title",
          "value": "EKSourceTypeExchange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1exchange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1subscribed/title",
          "value": "EKSourceTypeSubscribed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1subscribed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeSubscribed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType/title",
          "value": "EKSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1birthdays/title",
          "value": "EKSourceTypeBirthdays"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1birthdays/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeBirthdays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1local/title",
          "value": "EKSourceTypeLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1local/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1calDAV/title",
          "value": "EKSourceTypeCalDAV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1calDAV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeCalDAV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1mobileMe/title",
          "value": "EKSourceTypeMobileMe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSourceType~1mobileMe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSourceTypeMobileMe"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/eksourcetype/local"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/eksourcetype/local"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
