{
  "abstract": [
    {
      "text": "Specified authentication type is not supported.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/typeUnsupported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CFStreamErrorHTTPAuthentication@kCFStreamErrorHTTPAuthenticationTypeUnsupported",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "typeUnsupported"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CFStreamErrorHTTPAuthentication.typeUnsupported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "typeUnsupported"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication": {
      "abstract": [
        {
          "text": "Authentication error codes that may be returned when trying to apply authentication to a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFStreamErrorHTTPAuthentication"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFStreamErrorHTTPAuthentication"
        }
      ],
      "role": "symbol",
      "title": "CFStreamErrorHTTPAuthentication",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfstreamerrorhttpauthentication"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badPassword": {
      "abstract": [
        {
          "text": "Password is in a format that is not suitable for the request. Currently, passwords are decoded using ",
          "type": "text"
        },
        {
          "code": "kCFStringEncodingISOLatin1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badPassword"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorHTTPAuthenticationBadPassword"
        }
      ],
      "role": "symbol",
      "title": "CFStreamErrorHTTPAuthentication.badPassword",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfstreamerrorhttpauthentication/badpassword"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badUserName": {
      "abstract": [
        {
          "text": "User name is in a format that is not suitable for the request. Currently, user names are decoded using ",
          "type": "text"
        },
        {
          "code": "kCFStringEncodingISOLatin1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badUserName"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badUserName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorHTTPAuthenticationBadUserName"
        }
      ],
      "role": "symbol",
      "title": "CFStreamErrorHTTPAuthentication.badUserName",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfstreamerrorhttpauthentication/badusername"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/typeUnsupported": {
      "abstract": [
        {
          "text": "Specified authentication type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeUnsupported"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/typeUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "CFStreamErrorHTTPAuthentication.typeUnsupported",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfstreamerrorhttpauthentication/typeunsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badUserName",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badPassword"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badUserName",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamErrorHTTPAuthentication/badPassword"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication/title",
          "value": "CFStreamErrorHTTPAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFStreamErrorHTTPAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFStreamErrorHTTPAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication~1badPassword/title",
          "value": "kCFStreamErrorHTTPAuthenticationBadPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication~1badPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorHTTPAuthenticationBadPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication~1badUserName/title",
          "value": "kCFStreamErrorHTTPAuthenticationBadUserName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication~1badUserName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorHTTPAuthenticationBadUserName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication~1typeUnsupported/title",
          "value": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamErrorHTTPAuthentication~1typeUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorHTTPAuthenticationTypeUnsupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfstreamerrorhttpauthentication/typeunsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfstreamerrorhttpauthentication/typeunsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
