{"variants":[{"paths":["/documentation/appkit/nsparagraphstyle/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsparagraphstyle/default"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The default paragraph style."}],"metadata":{"platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.0","unavailable":false,"name":"macOS"}],"title":"default","externalID":"c:objc(cs)NSParagraphStyle(cpy)defaultParagraphStyle","navigatorTitle":[{"text":"defaultParagraphStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSParagraphStyle","text":"NSParagraphStyle","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Type Property","role":"symbol","modules":[{"name":"AppKit"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle","text":"NSParagraphStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSParagraphStyle"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default paragraph style has the following default values:"}]},{"header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Subattribute","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Alignment"}]}],[{"type":"paragraph","inlineContent":[{"code":"NSNaturalTextAlignment","type":"codeVoice"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tab stops"}]}],[{"type":"paragraph","inlineContent":[{"text":"12 left-aligned tabs, spaced by ","type":"text"},{"code":"28.0","type":"codeVoice"},{"text":" points","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Line break mode"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"NSLineBreakByWordWrapping"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"All others"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"0.0"}]}]]],"type":"table"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See individual method descriptions for explanations of each subattribute."}]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default":{"url":"/documentation/appkit/nsparagraphstyle/default","abstract":[{"type":"text","text":"The default paragraph style."}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSParagraphStyle","text":"NSParagraphStyle","kind":"typeIdentifier"}],"kind":"symbol","title":"default","navigatorTitle":[{"text":"defaultParagraphStyle","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSParagraphStyle"}],"url":"/documentation/appkit/nsparagraphstyle","identifier":"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle","abstract":[{"type":"text","text":"The paragraph or ruler attributes for an attributed string."}],"title":"NSParagraphStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSParagraphStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"10.0","name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Property","op":"replace","path":"/metadata/roleHeading"},{"value":"defaultParagraphStyle","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"defaultParagraphStyle","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSParagraphStyle","text":"NSParagraphStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"defaultParagraphStyle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace"},{"value":"defaultParagraphStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1default/title","op":"replace"},{"value":[{"text":"defaultParagraphStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1default/fragments","op":"replace"},{"value":"NSParagraphStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/title","op":"replace"},{"value":[{"text":"NSParagraphStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/fragments","op":"replace"},{"value":[{"text":"NSParagraphStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}