{
  "abstract": [
    {
      "text": "Constants that specify the type of tab stop.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSTextTabType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TextTabType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TextTabType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSParagraphStyle.TextTabType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TextTabType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following mappings define the conversions between text alignment in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and tab stop types that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defines:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Alignment",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Tab stop type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/left",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/right",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/rightTabStopType",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/center",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/centerTabStopType",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/justified",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/natural",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/rightTabStopType",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", depending on the user setting.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/right",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with a terminator",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/decimalTabStopType",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle": {
      "abstract": [
        {
          "text": "The paragraph or ruler attributes for an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType": {
      "abstract": [
        {
          "text": "Constants that specify the type of tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextTabType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextTabType"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.TextTabType",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/centerTabStopType": {
      "abstract": [
        {
          "text": "A center-aligned tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerTabStopType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/centerTabStopType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCenterTabStopType"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.TextTabType.centerTabStopType",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype/centertabstoptype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/decimalTabStopType": {
      "abstract": [
        {
          "text": "A tab stop that aligns columns of numbers to each number’s decimal point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decimalTabStopType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/decimalTabStopType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDecimalTabStopType"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.TextTabType.decimalTabStopType",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype/decimaltabstoptype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType": {
      "abstract": [
        {
          "text": "A left-aligned tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftTabStopType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLeftTabStopType"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.TextTabType.leftTabStopType",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype/lefttabstoptype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/rightTabStopType": {
      "abstract": [
        {
          "text": "A right-aligned tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightTabStopType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/rightTabStopType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRightTabStopType"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.TextTabType.rightTabStopType",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype/righttabstoptype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval": {
      "abstract": [
        {
          "text": "The documentwide default tab interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        }
      ],
      "role": "symbol",
      "title": "defaultTabInterval",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/defaulttabinterval"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops": {
      "abstract": [
        {
          "text": "The text tab objects that represent the paragraph’s tab stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStops"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTab",
          "text": "NSTextTab"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabStops"
        }
      ],
      "role": "symbol",
      "title": "tabStops",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/tabstops"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/center": {
      "abstract": [
        {
          "text": "Text is center-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment.center",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment/center"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/justified": {
      "abstract": [
        {
          "text": "Text is justified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "justified"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/justified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignmentJustified"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment.justified",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment/justified"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/left": {
      "abstract": [
        {
          "text": "Text is left-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignmentLeft"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment.left",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/natural": {
      "abstract": [
        {
          "text": "Text uses the default alignment for the current localization of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "natural"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/natural",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignmentNatural"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment.natural",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment/natural"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/right": {
      "abstract": [
        {
          "text": "Text is right-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignmentRight"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment.right",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTab": {
      "abstract": [
        {
          "text": "A tab in a paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTab"
        }
      ],
      "role": "symbol",
      "title": "NSTextTab",
      "type": "topic",
      "url": "/documentation/appkit/nstexttab"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-tab-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval"
      ],
      "title": "Accessing tab information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/rightTabStopType",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/centerTabStopType",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/decimalTabStopType"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextTabType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTabType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTabType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/leftTabStopType",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/rightTabStopType",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/centerTabStopType",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType/decimalTabStopType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-tab-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval"
              ],
              "title": "Accessing tab information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextTabType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1leftTabStopType/title",
          "value": "NSLeftTabStopType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1leftTabStopType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLeftTabStopType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1right/title",
          "value": "NSTextAlignmentRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignmentRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/title",
          "value": "NSTextTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType/title",
          "value": "NSTextTabType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTabType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTabType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tabStops/title",
          "value": "tabStops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tabStops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabStops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1defaultTabInterval/title",
          "value": "defaultTabInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1defaultTabInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultTabInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/title",
          "value": "NSParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1center/title",
          "value": "NSTextAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1rightTabStopType/title",
          "value": "NSRightTabStopType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1rightTabStopType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRightTabStopType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1natural/title",
          "value": "NSTextAlignmentNatural"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1natural/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignmentNatural"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1decimalTabStopType/title",
          "value": "NSDecimalTabStopType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1decimalTabStopType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDecimalTabStopType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1left/title",
          "value": "NSTextAlignmentLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignmentLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1centerTabStopType/title",
          "value": "NSCenterTabStopType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType~1centerTabStopType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCenterTabStopType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1justified/title",
          "value": "NSTextAlignmentJustified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1justified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignmentJustified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsparagraphstyle/texttabtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsparagraphstyle/texttabtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
