{
  "abstract": [
    {
      "text": "The number of voltage measurements associated with this sample.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/numberOfVoltageMeasurements"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKElectrocardiogram(py)numberOfVoltageMeasurements",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "numberOfVoltageMeasurements"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "numberOfVoltageMeasurements"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "numberOfVoltageMeasurements"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfVoltageMeasurements"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram": {
      "abstract": [
        {
          "text": "A sample for electrocardiogram data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKElectrocardiogram"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogram"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Lead": {
      "abstract": [
        {
          "text": "The lead used to record a voltage measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Lead"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Lead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Lead"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Lead",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/lead"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/VoltageMeasurement": {
      "abstract": [
        {
          "text": "The voltage for all leads at a single point in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VoltageMeasurement"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/VoltageMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VoltageMeasurement"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.VoltageMeasurement",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/voltagemeasurement"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/numberOfVoltageMeasurements": {
      "abstract": [
        {
          "text": "The number of voltage measurements associated with this sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfVoltageMeasurements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/numberOfVoltageMeasurements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfVoltageMeasurements"
        }
      ],
      "role": "symbol",
      "title": "numberOfVoltageMeasurements",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/numberofvoltagemeasurements"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/samplingFrequency": {
      "abstract": [
        {
          "text": "The frequency at which the Apple Watch sampled the voltage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "samplingFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/samplingFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplingFrequency"
        }
      ],
      "role": "symbol",
      "title": "samplingFrequency",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/samplingfrequency"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Voltage-Measurements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/samplingFrequency",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/VoltageMeasurement",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Lead"
      ],
      "title": "Accessing Voltage Measurements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "numberOfVoltageMeasurements"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfVoltageMeasurements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Voltage-Measurements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/samplingFrequency",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/VoltageMeasurement",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Lead"
              ],
              "title": "Accessing Voltage Measurements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "numberOfVoltageMeasurements"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Lead/title",
          "value": "HKElectrocardiogramLead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Lead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramLead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Lead/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramLead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1numberOfVoltageMeasurements/title",
          "value": "numberOfVoltageMeasurements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1numberOfVoltageMeasurements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfVoltageMeasurements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1samplingFrequency/title",
          "value": "samplingFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1samplingFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "samplingFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram/title",
          "value": "HKElectrocardiogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1VoltageMeasurement/title",
          "value": "HKElectrocardiogramVoltageMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1VoltageMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramVoltageMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1VoltageMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramVoltageMeasurement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkelectrocardiogram/numberofvoltagemeasurements"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkelectrocardiogram/numberofvoltagemeasurements"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
