{
  "abstract": [
    {
      "text": "An activation function that returns the softmax function of its input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionSoftmax"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSActivationFunction@BNNSActivationFunctionSoftmax",
    "fragments": [
      {
        "kind": "identifier",
        "text": "BNNSActivationFunctionSoftmax"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSActivationFunctionSoftmax"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "BNNSActivationFunctionSoftmax"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionSoftmax"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This constant defines an activation function that returns values using the following formula:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3401551",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The softmax function transforms a vector of real numbers into a vector of probabilities. Each probability in the result is in the range 0…1, and the sum of the probabilities is 1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to apply the softmax function to a vector that contains seven elements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let inputs: [Float] = [3, 5, 1, 6, 2, 1, 4]",
            "let count = inputs.count",
            "var outputs = [Float](repeating: 0,",
            "                      count: count)",
            "",
            "var inDescription = BNNSVectorDescriptor(size: count,",
            "                                         data_type: .float)",
            "var outDescription = BNNSVectorDescriptor(size: count,",
            "                                          data_type: .float)",
            "var activation = BNNSActivation(function: .softmax)",
            "var filterParameters = BNNSFilterParameters()",
            "",
            "let activationLayer = BNNSFilterCreateVectorActivationLayer(&inDescription,",
            "                                                            &outDescription,",
            "                                                            &activation,",
            "                                                            &filterParameters)",
            "",
            "BNNSFilterApply(activationLayer, inputs, &outputs)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On return, the softmax function calculates the following values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Inputs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Outputs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "3.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.031415492",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "5.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.23213086",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.004251625",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "6.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.63099706",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "2.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.011557114",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.004251625",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "4.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.08539616",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Changing the fourth element in ",
              "type": "text"
            },
            {
              "code": "inputs",
              "type": "codeVoice"
            },
            {
              "text": " to 10 increases its probability to almost 1.0:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Inputs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Outputs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "3.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.00090221845",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "5.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.0066665425",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.00012210199",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "10.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.98940265",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "2.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.00033190762",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.00012210199",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "4.0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "0.002452484",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction": {
      "abstract": [
        {
          "text": "Constants that describe activation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionClamp": {
      "abstract": [
        {
          "text": "An activation function that returns its input clamped to the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionClamp"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionClamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSActivationFunctionClamp",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/bnnsactivationfunctionclamp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionIntegerLinearSaturate": {
      "abstract": [
        {
          "text": "An activation function that returns an arithmetic shift, preserving sign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionIntegerLinearSaturate"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionIntegerLinearSaturate",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSActivationFunctionIntegerLinearSaturate",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/bnnsactivationfunctionintegerlinearsaturate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionSoftmax": {
      "abstract": [
        {
          "text": "An activation function that returns the softmax function of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionSoftmax"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionSoftmax",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSActivationFunctionSoftmax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/bnnsactivationfunctionsoftmax"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU": {
      "abstract": [
        {
          "text": "An activation function that evaluates the continuously differentiable exponential linear units (CELU) on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionCELU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionCELU"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionCELU",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctioncelu"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear": {
      "abstract": [
        {
          "text": "An activation function that returns its input clamped to beta when that is greater than or equal to zero, otherwise it returns its input multiplied by alpha clamped to beta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionClampedLeakyRectifiedLinear",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionclampedleakyrectifiedlinear"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU": {
      "abstract": [
        {
          "text": "An activation function that evaluates the exponential linear units (ELU) on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionELU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionELU"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionELU",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionelu"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionErf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionErf"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionErf",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionerf"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELU"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELU",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongelu"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation": {
      "abstract": [
        {
          "text": "An activation function that evaluates the Gaussian error linear units (GELU) approximation on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELUApproximation",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongeluapproximation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2": {
      "abstract": [
        {
          "text": "An activation function that provides a fast evaluation of the Gaussian error linear units (GELU) approximation on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation2"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELUApproximation2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongeluapproximation2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximationSigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximationSigmoid"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELUApproximationSigmoid",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongeluapproximationsigmoid"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel": {
      "abstract": [
        {
          "text": "An activation function that returns random numbers from the Gumbel distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbel"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGumbel",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongumbel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax": {
      "abstract": [
        {
          "text": "An activation function that returns random numbers from the Gumbel distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbelMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbelMax"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGumbelMax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongumbelmax"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink": {
      "abstract": [
        {
          "text": "An activation function that returns zero when the absolute input is less than alpha, otherwise it returns its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardShrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardShrink"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionHardShrink",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionhardshrink"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSigmoid": {
      "abstract": [
        {
          "text": "An activation function that returns the hard sigmoid function of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSigmoid"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionHardSigmoid",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionhardsigmoid"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSwish": {
      "abstract": [
        {
          "text": "An activation function that returns the hard swish function of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSwish"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSwish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSwish"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionHardSwish",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionhardswish"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3401551": {
      "alt": "General formula that describes mathematically the softmax activation function. s open bracket x sub i close bracket equals  the exponential of x sub i over summation from j equals one to n times the exponential of x sub j.",
      "identifier": "media-3401551",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ce7621b84d5ab53d3174d8b6b257582c/media-3401551@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Raw-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionClamp",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSigmoid",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSwish",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionIntegerLinearSaturate"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardShrink/title",
          "value": "BNNSActivationFunctionHardShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionHardShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionCELU/title",
          "value": "BNNSActivationFunctionCELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionCELU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionCELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSwish/title",
          "value": "BNNSActivationFunctionHardSwish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSwish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionHardSwish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionClampedLeakyRectifiedLinear/title",
          "value": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionClampedLeakyRectifiedLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionErf/title",
          "value": "BNNSActivationFunctionErf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionErf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionErf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation/title",
          "value": "BNNSActivationFunctionGELUApproximation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELUApproximation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbelMax/title",
          "value": "BNNSActivationFunctionGumbelMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbelMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGumbelMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation2/title",
          "value": "BNNSActivationFunctionGELUApproximation2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELUApproximation2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSigmoid/title",
          "value": "BNNSActivationFunctionHardSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionHardSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionELU/title",
          "value": "BNNSActivationFunctionELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionELU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunction/title",
          "value": "BNNSActivationFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELU/title",
          "value": "BNNSActivationFunctionGELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbel/title",
          "value": "BNNSActivationFunctionGumbel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGumbel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximationSigmoid/title",
          "value": "BNNSActivationFunctionGELUApproximationSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximationSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELUApproximationSigmoid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsactivationfunction/bnnsactivationfunctionsoftmax"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
