{
  "abstract": [
    {
      "text": "Codes that describe errors encountered during accessory discovery.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ASErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "AccessorySetupKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ASError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit": {
      "abstract": [
        {
          "text": "Enable privacy-preserving discovery and configuration of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AccessorySetupKit",
      "type": "topic",
      "url": "/documentation/accessorysetupkit"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError": {
      "abstract": [
        {
          "text": "An error encountered during accessory discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASError"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASError"
        }
      ],
      "role": "symbol",
      "title": "ASError",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code": {
      "abstract": [
        {
          "text": "Codes that describe errors encountered during accessory discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/equatable-implementations"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/rawrepresentable-implementations"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/activationFailed": {
      "abstract": [
        {
          "text": "Session activation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationFailed"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/activationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeActivationFailed"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.activationFailed",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/activationfailed"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/connectionFailed": {
      "abstract": [
        {
          "text": "The session was unable to establish a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/connectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.connectionFailed",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/connectionfailed"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/discoveryTimeout": {
      "abstract": [
        {
          "text": "Accessory discovery timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discoveryTimeout"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/discoveryTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeDiscoveryTimeout"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.discoveryTimeout",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/discoverytimeout"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/extensionNotFound": {
      "abstract": [
        {
          "text": "The framework couldn’t find the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionNotFound"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/extensionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeExtensionNotFound"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.extensionNotFound",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/extensionnotfound"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/init(rawvalue:)"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidRequest": {
      "abstract": [
        {
          "text": "The session received an invalid request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRequest"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeInvalidRequest"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.invalidRequest",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/invalidrequest"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidated": {
      "abstract": [
        {
          "text": "The session invalidated prior to completing the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidated"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeInvalidated"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.invalidated",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/invalidated"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerAlreadyActive": {
      "abstract": [
        {
          "text": "The picker received a show request when it was already active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerAlreadyActive"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerAlreadyActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodePickerAlreadyActive"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.pickerAlreadyActive",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/pickeralreadyactive"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerRestricted": {
      "abstract": [
        {
          "text": "The picker can’t be used because the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerRestricted"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodePickerRestricted"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.pickerRestricted",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/pickerrestricted"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/success": {
      "abstract": [
        {
          "text": "A code that represents a successful action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.success",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/success"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/unknown": {
      "abstract": [
        {
          "text": "An underlying failure with an unknown cause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.unknown",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/unknown"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userCancelled": {
      "abstract": [
        {
          "text": "The person using the app canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCancelled"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeUserCancelled"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.userCancelled",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/usercancelled"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userRestricted": {
      "abstract": [
        {
          "text": "The person using the app restricted access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userRestricted"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorCodeUserRestricted"
        }
      ],
      "role": "symbol",
      "title": "ASError.Code.userRestricted",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/code/userrestricted"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/errorDomain": {
      "abstract": [
        {
          "text": "The domain of the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserror/errordomain"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASErrorDomain": {
      "abstract": [
        {
          "text": "NSError domain for AccessorySetupKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ASErrorDomain",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/aserrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-error-code",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/init(rawValue:)"
      ],
      "title": "Creating an error code"
    },
    {
      "anchor": "Activation-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/activationFailed"
      ],
      "title": "Activation errors"
    },
    {
      "anchor": "Timeout-and-life-cycle-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/discoveryTimeout",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidated"
      ],
      "title": "Timeout and life cycle errors"
    },
    {
      "anchor": "Configuration-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/extensionNotFound",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userRestricted",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidRequest"
      ],
      "title": "Configuration errors"
    },
    {
      "anchor": "Picker-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerRestricted",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerAlreadyActive"
      ],
      "title": "Picker errors"
    },
    {
      "anchor": "Cancellation-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userCancelled"
      ],
      "title": "Cancellation errors"
    },
    {
      "anchor": "Communication-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/connectionFailed"
      ],
      "title": "Communication errors"
    },
    {
      "anchor": "Success-cases",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/success"
      ],
      "title": "Success cases"
    },
    {
      "anchor": "Unclassified-errors",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/unknown"
      ],
      "title": "Unclassified errors"
    },
    {
      "anchor": "Accessing-the-error-domain",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/errorDomain",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASErrorDomain"
      ],
      "title": "Accessing the error domain"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/Equatable-Implementations",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activation-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/activationFailed"
              ],
              "title": "Activation errors"
            },
            {
              "anchor": "Timeout-and-life-cycle-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/discoveryTimeout",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidated"
              ],
              "title": "Timeout and life cycle errors"
            },
            {
              "anchor": "Configuration-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/extensionNotFound",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userRestricted",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/invalidRequest"
              ],
              "title": "Configuration errors"
            },
            {
              "anchor": "Picker-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerRestricted",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/pickerAlreadyActive"
              ],
              "title": "Picker errors"
            },
            {
              "anchor": "Cancellation-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/userCancelled"
              ],
              "title": "Cancellation errors"
            },
            {
              "anchor": "Communication-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/connectionFailed"
              ],
              "title": "Communication errors"
            },
            {
              "anchor": "Success-cases",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/success"
              ],
              "title": "Success cases"
            },
            {
              "anchor": "Unclassified-errors",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASError/Code/unknown"
              ],
              "title": "Unclassified errors"
            },
            {
              "anchor": "Accessing-the-error-domain",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASErrorDomain"
              ],
              "title": "Accessing the error domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1activationFailed/title",
          "value": "ASErrorCodeActivationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1activationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeActivationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1userRestricted/title",
          "value": "ASErrorCodeUserRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1userRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeUserRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASErrorDomain/title",
          "value": "ASErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1userCancelled/title",
          "value": "ASErrorCodeUserCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1userCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeUserCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1pickerRestricted/title",
          "value": "ASErrorCodePickerRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1pickerRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodePickerRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1success/title",
          "value": "ASErrorCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code/title",
          "value": "ASErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1extensionNotFound/title",
          "value": "ASErrorCodeExtensionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1extensionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeExtensionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1pickerAlreadyActive/title",
          "value": "ASErrorCodePickerAlreadyActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1pickerAlreadyActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodePickerAlreadyActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1invalidRequest/title",
          "value": "ASErrorCodeInvalidRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1invalidRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeInvalidRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1invalidated/title",
          "value": "ASErrorCodeInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1invalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1discoveryTimeout/title",
          "value": "ASErrorCodeDiscoveryTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1discoveryTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeDiscoveryTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1unknown/title",
          "value": "ASErrorCodeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1connectionFailed/title",
          "value": "ASErrorCodeConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASError~1Code~1connectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASErrorCodeConnectionFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessorysetupkit/aserror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessorysetupkit/aserror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
