{
  "abstract": [
    {
      "text": "A state in which the framework downloads localization imagery.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARGeoTrackingStateReason@ARGeoTrackingStateReasonGeoDataNotLoaded",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "geoDataNotLoaded"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARGeoTrackingStatus.StateReason.geoDataNotLoaded"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "geoDataNotLoaded"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ARKit provides this reason in state ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum/localizing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the session is actively attempting to download localization imagery (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingConfiguration#Refine-the-Users-Position-with-Imagery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If this state persists for too long, it may indicate a network issue. If a reasonable amount of time elapses in this state reason, the app may consider requesting that the user check their internet connection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingConfiguration#Refine-the-Users-Position-with-Imagery": {
      "abstract": [],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingConfiguration#Refine-the-Users-Position-with-Imagery",
      "kind": "section",
      "title": "Refine the User’s Position with Imagery",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingconfiguration#Refine-the-Users-Position-with-Imagery"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus": {
      "abstract": [
        {
          "text": "The state, accuracy, and reason that are possible for geo-tracking’s current condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum/localizing": {
      "abstract": [
        {
          "text": "Geo tracking is attempting to localize against a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizing"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum/localizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateLocalizing"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.State.localizing",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/state-swift.enum/localizing"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum": {
      "abstract": [
        {
          "text": "The reasons for the app’s geotracking status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StateReason"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow": {
      "abstract": [
        {
          "text": "The position of the device is too low for geotracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePointedTooLow"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonDevicePointedTooLow"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.devicePointedTooLow",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/devicepointedtoolow"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded": {
      "abstract": [
        {
          "text": "A state in which the framework downloads localization imagery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geoDataNotLoaded"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.geoDataNotLoaded",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/geodatanotloaded"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions": {
      "abstract": [
        {
          "text": "The location requires user permission for geotracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needLocationPermissions"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonNeedLocationPermissions"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.needLocationPermissions",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/needlocationpermissions"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none": {
      "abstract": [
        {
          "text": "No issues reported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonNone"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.none",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/none"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation": {
      "abstract": [
        {
          "text": "The location doesn’t provide geotracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAvailableAtLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonNotAvailableAtLocation"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.notAvailableAtLocation",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/notavailableatlocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed": {
      "abstract": [
        {
          "text": "Localization imagery failed to match the view from the device’s camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualLocalizationFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonVisualLocalizationFailed"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.visualLocalizationFailed",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/visuallocalizationfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck": {
      "abstract": [
        {
          "text": "A state in which the framework performs a check for geotracking availability at the user’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitingForAvailabilityCheck"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonWaitingForAvailabilityCheck"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.waitingForAvailabilityCheck",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/waitingforavailabilitycheck"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation": {
      "abstract": [
        {
          "text": "A state in which the framework performs a check for the user’s GPS position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitingForLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonWaitingForLocation"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.waitingForLocation",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/waitingforlocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable": {
      "abstract": [
        {
          "text": "The position or motion of the device makes geotracking unstable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldTrackingUnstable"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonWorldTrackingUnstable"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.worldTrackingUnstable",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/worldtrackingunstable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Status-Reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck"
      ],
      "title": "Status Reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARGeoTrackingStateReasonGeoDataNotLoaded"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Status-Reasons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck"
              ],
              "title": "Status Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1none/title",
          "value": "ARGeoTrackingStateReasonNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1devicePointedTooLow/title",
          "value": "ARGeoTrackingStateReasonDevicePointedTooLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1devicePointedTooLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonDevicePointedTooLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1needLocationPermissions/title",
          "value": "ARGeoTrackingStateReasonNeedLocationPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1needLocationPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonNeedLocationPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1visualLocalizationFailed/title",
          "value": "ARGeoTrackingStateReasonVisualLocalizationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1visualLocalizationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonVisualLocalizationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1worldTrackingUnstable/title",
          "value": "ARGeoTrackingStateReasonWorldTrackingUnstable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1worldTrackingUnstable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonWorldTrackingUnstable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/title",
          "value": "ARGeoTrackingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/title",
          "value": "ARGeoTrackingStateReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1geoDataNotLoaded/title",
          "value": "ARGeoTrackingStateReasonGeoDataNotLoaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1geoDataNotLoaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1notAvailableAtLocation/title",
          "value": "ARGeoTrackingStateReasonNotAvailableAtLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1notAvailableAtLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonNotAvailableAtLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForAvailabilityCheck/title",
          "value": "ARGeoTrackingStateReasonWaitingForAvailabilityCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForAvailabilityCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonWaitingForAvailabilityCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForLocation/title",
          "value": "ARGeoTrackingStateReasonWaitingForLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonWaitingForLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum~1localizing/title",
          "value": "ARGeoTrackingStateLocalizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum~1localizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateLocalizing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/geodatanotloaded"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/geodatanotloaded"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
