{
  "abstract": [
    {
      "text": "An object that holds configuration options for a host view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.extensionkit/documentation/ExtensionKit",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ExtensionKit",
    "externalID": "s:So20EXHostViewControllerC12ExtensionKitE13ConfigurationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "modules": [
      {
        "name": "ExtensionKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "EXHostViewController.Configuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Configuration"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit": {
      "abstract": [
        {
          "text": "Create executable bundles to extend the functionality of other apps by presenting a user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ExtensionKit",
      "type": "topic",
      "url": "/documentation/extensionkit"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController": {
      "abstract": [
        {
          "text": "A view controller that hosts remote views provided by an extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EXHostViewController"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EXHostViewController"
        }
      ],
      "role": "symbol",
      "title": "EXHostViewController",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "An object that holds configuration options for a host view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "EXHostViewController.Configuration",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/configuration-swift.struct"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/appExtension": {
      "abstract": [
        {
          "text": "The app extension for this configuration object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:19ExtensionFoundation03AppA8IdentityV",
          "text": "AppExtensionIdentity"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/appExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "appExtension",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/configuration-swift.struct/appextension"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/init(appExtension:sceneID:)": {
      "abstract": [
        {
          "text": "Creates a new configuration object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "appExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:19ExtensionFoundation03AppA8IdentityV",
          "text": "AppExtensionIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sceneID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/init(appExtension:sceneID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(appExtension:sceneID:)",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/configuration-swift.struct/init(appextension:sceneid:)"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/sceneID": {
      "abstract": [
        {
          "text": "The unique identifier for this configuration object’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/sceneID",
      "kind": "symbol",
      "role": "symbol",
      "title": "sceneID",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/configuration-swift.struct/sceneid"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/configuration-swift.property": {
      "abstract": [
        {
          "text": "The view controller’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EXHostViewController",
          "text": "EXHostViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So20EXHostViewControllerC12ExtensionKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/configuration-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/configuration-swift.property"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/placeholderView": {
      "abstract": [
        {
          "text": "A view that’s used when the view controller has no content to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/placeholderView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderView"
        }
      ],
      "role": "symbol",
      "title": "placeholderView",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/placeholderview"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-View-Controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/configuration-swift.property",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/placeholderView"
      ],
      "title": "Configuring the View Controller"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Configuration-Object",
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/init(appExtension:sceneID:)"
      ],
      "title": "Creating a Configuration Object"
    },
    {
      "anchor": "Identifying-the-Extension",
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/appExtension",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/Configuration-swift.struct/sceneID"
      ],
      "title": "Identifying the Extension"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/title",
          "value": "EXHostViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController~1placeholderView/title",
          "value": "placeholderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController~1placeholderView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/extensionkit/exhostviewcontroller/configuration-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
