{
  "abstract": [
    {
      "text": "Enables support for parsing additional fragments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions/allowIncrementalFragmentParsing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEFormatReaderInstantiationOptions(py)allowIncrementalFragmentParsing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allowIncrementalFragmentParsing"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "allowIncrementalFragmentParsing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "allowIncrementalFragmentParsing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allowIncrementalFragmentParsing"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions": {
      "abstract": [
        {
          "text": "An object that contains options to pass to a format reader extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReaderInstantiationOptions"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderInstantiationOptions"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReaderInstantiationOptions",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderinstantiationoptions"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions/allowIncrementalFragmentParsing": {
      "abstract": [
        {
          "text": "Enables support for parsing additional fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowIncrementalFragmentParsing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions/allowIncrementalFragmentParsing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowIncrementalFragmentParsing"
        }
      ],
      "role": "symbol",
      "title": "allowIncrementalFragmentParsing",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderinstantiationoptions/allowincrementalfragmentparsing"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "allowIncrementalFragmentParsing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowIncrementalFragmentParsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowIncrementalFragmentParsing"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions/title",
          "value": "MEFormatReaderInstantiationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderInstantiationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderInstantiationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions~1allowIncrementalFragmentParsing/title",
          "value": "allowIncrementalFragmentParsing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions~1allowIncrementalFragmentParsing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowIncrementalFragmentParsing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/meformatreaderinstantiationoptions/allowincrementalfragmentparsing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/meformatreaderinstantiationoptions/allowincrementalfragmentparsing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
