{
  "abstract": [
    {
      "text": "An invocation option that specifies that the test automatically takes measurements at the beginning and ending of a measure block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTMeasurementInvocationOptions/XCTMeasurementInvocationNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCTMeasurementInvocationOptions@XCTMeasurementInvocationNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "XCTMeasurementInvocationNone"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTMeasurementInvocationNone"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "XCTMeasurementInvocationNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct": {
      "abstract": [
        {
          "text": "Test measurement options that control how measurement starts and stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InvocationOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions/InvocationOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InvocationOptions"
        }
      ],
      "role": "symbol",
      "title": "XCTMeasureOptions.InvocationOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasureoptions/invocationoptions-swift.struct"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasurementInvocationOptions/XCTMeasurementInvocationNone": {
      "abstract": [
        {
          "text": "An invocation option that specifies that the test automatically takes measurements at the beginning and ending of a measure block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTMeasurementInvocationNone"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasurementInvocationOptions/XCTMeasurementInvocationNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTMeasurementInvocationNone",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasurementinvocationoptions/xctmeasurementinvocationnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct/title",
          "value": "XCTMeasurementInvocationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions~1InvocationOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasurementInvocationOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctmeasurementinvocationoptions/xctmeasurementinvocationnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
