{
  "abstract": [
    {
      "text": "Indicates types of companions paired with the device.",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "The elements are NSNumber-wrapped instances of @c ",
      "type": "text"
    },
    {
      "code": "LACompanionType",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LADomainStateCompanion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LADomainStateCompanion/availableCompanionTypes-1ggnh"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)LADomainStateCompanion(py)availableCompanionTypes",
    "fragments": [
      {
        "kind": "identifier",
        "text": "availableCompanionTypes"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "availableCompanionTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "availableCompanionTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "availableCompanionTypes"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LADomainStateCompanion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LADomainStateCompanion"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LADomainStateCompanion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LADomainStateCompanion"
        }
      ],
      "role": "symbol",
      "title": "LADomainStateCompanion",
      "type": "topic",
      "url": "/documentation/localauthentication/ladomainstatecompanion"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LADomainStateCompanion/availableCompanionTypes-1ggnh": {
      "abstract": [
        {
          "text": "Indicates types of companions paired with the device.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "The elements are NSNumber-wrapped instances of @c ",
          "type": "text"
        },
        {
          "code": "LACompanionType",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "availableCompanionTypes"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LADomainStateCompanion/availableCompanionTypes-1ggnh",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableCompanionTypes",
      "type": "topic",
      "url": "/documentation/localauthentication/ladomainstatecompanion/availablecompaniontypes-1ggnh"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LADomainStateCompanion/title",
          "value": "LADomainStateCompanion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LADomainStateCompanion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LADomainStateCompanion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LADomainStateCompanion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LADomainStateCompanion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/ladomainstatecompanion/availablecompaniontypes-1ggnh"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
