{"seeAlsoSections":[{"anchor":"Find-Bar-View","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/findBarView","doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/contentView()"],"title":"Find Bar View","generated":true}],"variants":[{"paths":["/documentation/appkit/nstextfinderbarcontainer/isfindbarvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstextfinderbarcontainer/isfindbarvisible"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/isFindBarVisible"},"metadata":{"modules":[{"name":"AppKit"}],"required":true,"navigatorTitle":[{"text":"findBarVisible","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFindBarVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isFindBarVisible","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(pl)NSTextFinderBarContainer(py)findBarVisible","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"role":"symbol"},"abstract":[{"text":"Returns whether the container should display its find bar.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFindBarVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"When this property is "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" and the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/findBarView","type":"reference","isActive":true},{"type":"text","text":" property is set, then the find bar is displayed by the container. Otherwise, the find bar is not displayed."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The default value should be "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/isFindBarVisible":{"required":true,"kind":"symbol","title":"isFindBarVisible","abstract":[{"type":"text","text":"Returns whether the container should display its find bar."}],"url":"/documentation/appkit/nstextfinderbarcontainer/isfindbarvisible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFindBarVisible"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"findBarVisible","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/isFindBarVisible","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/findBarView":{"required":true,"kind":"symbol","title":"findBarView","abstract":[{"type":"text","text":"The view assigned by the text bar as the find bar view for the container."}],"url":"/documentation/appkit/nstextfinderbarcontainer/findbarview","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"findBarView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"findBarView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/findBarView","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextFinderBarContainer","kind":"identifier"}],"url":"/documentation/appkit/nstextfinderbarcontainer","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NSTextFinderBarContainer","kind":"identifier"}],"type":"topic","abstract":[{"text":"A protocol that provides a container in which the find bar is displayed.","type":"text"}],"title":"NSTextFinderBarContainer"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/contentView()":{"kind":"symbol","title":"contentView()","abstract":[{"type":"text","text":"A view hierarchy that contains all the views which display the contents being searched."}],"url":"/documentation/appkit/nstextfinderbarcontainer/contentview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"contentView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/contentView()","type":"topic"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"findBarVisible"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"findBarVisible","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Find-Bar-View","title":"Find Bar View","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/findBarView","doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer/contentView()"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isFindBarVisible","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"findBarVisible","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer~1isFindBarVisible/title","op":"replace","value":"findBarVisible"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer~1isFindBarVisible/fragments","value":[{"text":"findBarVisible","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer~1findBarView/title","value":"findBarView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer~1findBarView/fragments","value":[{"kind":"identifier","text":"findBarView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer/title","value":"NSTextFinderBarContainer"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer/fragments","value":[{"text":"NSTextFinderBarContainer","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer/navigatorTitle","value":[{"kind":"identifier","text":"NSTextFinderBarContainer"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer~1contentView()/title","value":"contentView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer~1contentView()/fragments","value":[{"text":"- ","kind":"text"},{"text":"contentView","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}