{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.compression/documentation/Compression","doc://com.apple.compression/documentation/Compression/compression_stream_flags"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/compression/compression_stream_flags/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"kind":"text","text":")"}],"externalID":"s:So24compression_stream_flagsa8rawValueABs6UInt32V_tcfc","platforms":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false},{"beta":false,"name":"watchOS","unavailable":false,"deprecated":false}],"role":"symbol","modules":[{"name":"Compression"}],"title":"init(rawValue:)"},"abstract":[{"type":"text","text":"Creates a new constant from the given raw value."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.compression/documentation/Compression/compression_stream_flags/init(_:)"],"title":"Initializers","anchor":"Initializers","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.compression/documentation/Compression/compression_stream_flags/init(rawValue:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.apple.compression/documentation/Compression/compression_stream_flags/init(rawValue:)":{"abstract":[{"type":"text","text":"Creates a new constant from the given raw value."}],"type":"topic","identifier":"doc://com.apple.compression/documentation/Compression/compression_stream_flags/init(rawValue:)","url":"/documentation/compression/compression_stream_flags/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}]},"doc://com.apple.compression/documentation/Compression/compression_stream_flags":{"abstract":[{"type":"text","text":"A set of values used to represent stream compression flags."}],"navigatorTitle":[{"kind":"identifier","text":"compression_stream_flags"}],"identifier":"doc://com.apple.compression/documentation/Compression/compression_stream_flags","role":"symbol","title":"compression_stream_flags","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"compression_stream_flags"}],"type":"topic","url":"/documentation/compression/compression_stream_flags"},"doc://com.apple.compression/documentation/Compression/compression_stream_flags/init(_:)":{"abstract":[{"type":"text","text":"Creates a new constant from the given raw value."}],"type":"topic","identifier":"doc://com.apple.compression/documentation/Compression/compression_stream_flags/init(_:)","url":"/documentation/compression/compression_stream_flags/init(_:)","kind":"symbol","title":"init(_:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}]},"doc://com.apple.compression/documentation/Compression":{"identifier":"doc://com.apple.compression/documentation/Compression","kind":"symbol","abstract":[{"text":"Leverage common compression algorithms for lossless data compression.","type":"text"}],"title":"Compression","url":"/documentation/compression","type":"topic","role":"collection"},"doc://com.externally.resolved.symbol/s:s6UInt32V":{"abstract":[{"text":"A 32-bit unsigned integer value type.","type":"text"}],"role":"symbol","title":"UInt32","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UInt32"}],"type":"topic","url":"/documentation/Swift/UInt32","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies","type":"topic","role":"overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"compression_stream_flags","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_flags/title"},{"op":"replace","value":[{"text":"compression_stream_flags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_flags/fragments"},{"value":[{"text":"compression_stream_flags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_flags/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}