{
  "abstract": [
    {
      "text": "The shared workspace object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMWorkspace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMWorkspace/shared"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AMWorkspace(cpy)sharedWorkspace",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shared"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AMWorkspace",
        "text": "AMWorkspace"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sharedWorkspace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "shared"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shared"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkspace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkspace",
              "text": "AMWorkspace"
            },
            {
              "kind": "text",
              "text": "! { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkspace": {
      "abstract": [
        {
          "text": "A workspace for running an Automator workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkspace"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkspace"
        }
      ],
      "role": "symbol",
      "title": "AMWorkspace",
      "type": "topic",
      "url": "/documentation/automator/amworkspace"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkspace/shared": {
      "abstract": [
        {
          "text": "The shared workspace object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkspace",
          "text": "AMWorkspace"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkspace/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedWorkspace"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/automator/amworkspace/shared"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sharedWorkspace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMWorkspace"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkspace",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AMWorkspace",
                    "text": "AMWorkspace"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "sharedWorkspace"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace~1shared/title",
          "value": "sharedWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/title",
          "value": "AMWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkspace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amworkspace/shared"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amworkspace/shared"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
