{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/MLCRandomInitializerTypeInvalid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCRandomInitializerType@MLCRandomInitializerTypeInvalid",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MLCRandomInitializerTypeInvalid"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCRandomInitializerTypeInvalid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MLCRandomInitializerTypeInvalid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerTypeInvalid"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType": {
      "abstract": [
        {
          "text": "An initializer type you use to create a tensor with random data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerType"
        }
      ],
      "role": "symbol",
      "title": "MLCRandomInitializerType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/MLCRandomInitializerTypeCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerTypeCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/MLCRandomInitializerTypeCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCRandomInitializerTypeCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype/mlcrandominitializertypecount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/MLCRandomInitializerTypeInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerTypeInvalid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/MLCRandomInitializerTypeInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCRandomInitializerTypeInvalid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype/mlcrandominitializertypeinvalid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/glorotUniform": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "glorotUniform"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/glorotUniform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerTypeGlorotUniform"
        }
      ],
      "role": "symbol",
      "title": "MLCRandomInitializerType.glorotUniform",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype/glorotuniform"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/uniform": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniform"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/uniform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerTypeUniform"
        }
      ],
      "role": "symbol",
      "title": "MLCRandomInitializerType.uniform",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype/uniform"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/xavier": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xavier"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/xavier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerTypeXavier"
        }
      ],
      "role": "symbol",
      "title": "MLCRandomInitializerType.xavier",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype/xavier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/uniform",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/glorotUniform",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/xavier",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType/MLCRandomInitializerTypeCount"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType~1xavier/title",
          "value": "MLCRandomInitializerTypeXavier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType~1xavier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerTypeXavier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType~1uniform/title",
          "value": "MLCRandomInitializerTypeUniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType~1uniform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerTypeUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType~1glorotUniform/title",
          "value": "MLCRandomInitializerTypeGlorotUniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType~1glorotUniform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerTypeGlorotUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType/title",
          "value": "MLCRandomInitializerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcrandominitializertype/mlcrandominitializertypeinvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
