{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowableMovement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The allowable distance, measured in points. The default distance is ","type":"text"},{"code":"10","type":"codeVoice"},{"text":" points.","type":"text"}]}],"kind":"content"}],"metadata":{"platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"3.2"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"3.2"},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"allowableMovement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowableMovement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"title":"allowableMovement","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UILongPressGestureRecognizer(py)allowableMovement"},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration","doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired","doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired"],"generated":true,"anchor":"Configuring-the-gesture-recognizer","title":"Configuring the gesture recognizer"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/allowableMovement","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer"]]},"kind":"symbol","variants":[{"paths":["/documentation/uikit/uilongpressgesturerecognizer/allowablemovement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uilongpressgesturerecognizer/allowablemovement"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The maximum movement of the fingers on the view before the gesture fails.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/allowableMovement":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowableMovement"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"kind":"symbol","url":"/documentation/uikit/uilongpressgesturerecognizer/allowablemovement","abstract":[{"text":"The maximum movement of the fingers on the view before the gesture fails.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allowableMovement"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/allowableMovement","title":"allowableMovement"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTapsRequired"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","url":"/documentation/uikit/uilongpressgesturerecognizer/numberoftapsrequired","abstract":[{"text":"The number of taps on the view necessary for gesture recognition.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"numberOfTapsRequired"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired","title":"numberOfTapsRequired"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTouchesRequired"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","url":"/documentation/uikit/uilongpressgesturerecognizer/numberoftouchesrequired","abstract":[{"text":"The number of fingers that must touch the view for gesture recognition.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"numberOfTouchesRequired"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired","title":"numberOfTouchesRequired"},"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumPressDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"kind":"symbol","url":"/documentation/uikit/uilongpressgesturerecognizer/minimumpressduration","abstract":[{"type":"text","text":"The minimum time that the user must press on the view for the gesture to be recognized."}],"navigatorTitle":[{"kind":"identifier","text":"minimumPressDuration"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration","title":"minimumPressDuration"},"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"UILongPressGestureRecognizer","kind":"identifier"}],"url":"/documentation/uikit/uilongpressgesturerecognizer","title":"UILongPressGestureRecognizer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UILongPressGestureRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"A continuous gesture recognizer that interprets long-press gestures."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"3.2","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"beta":false,"introducedAt":"3.2","name":"iPadOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"value":"allowableMovement","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"allowableMovement"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Configuring-the-gesture-recognizer","title":"Configuring the gesture recognizer","identifiers":["doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration","doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired","doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"allowableMovement","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"allowableMovement","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1allowableMovement/title"},{"op":"replace","value":[{"text":"allowableMovement","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1allowableMovement/fragments"},{"op":"replace","value":"numberOfTapsRequired","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTapsRequired/title"},{"op":"replace","value":[{"kind":"identifier","text":"numberOfTapsRequired"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTapsRequired/fragments"},{"op":"replace","value":"numberOfTouchesRequired","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTouchesRequired/title"},{"op":"replace","value":[{"text":"numberOfTouchesRequired","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTouchesRequired/fragments"},{"op":"replace","value":"minimumPressDuration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1minimumPressDuration/title"},{"op":"replace","value":[{"text":"minimumPressDuration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1minimumPressDuration/fragments"},{"op":"replace","value":"UILongPressGestureRecognizer","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer/title"},{"op":"replace","value":[{"text":"UILongPressGestureRecognizer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UILongPressGestureRecognizer"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}