{
  "abstract": [
    {
      "text": "Initializes a view that contains controls for the input parameters of a filter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/init(frame:filter:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IKFilterUIView(im)initWithFrame:filter:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "!("
      },
      {
        "kind": "externalParam",
        "text": "frame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSRect",
        "text": "NSRect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "filter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CIFilter",
        "text": "CIFilter"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithFrame:filter:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(frame:filter:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "!("
            },
            {
              "kind": "externalParam",
              "text": "frame"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "frameRect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "filter"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inFilter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CIFilter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CIFilter",
              "text": "CIFilter"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The rectangle that defines the area of the view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frameRect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Core Image filter. The view retains the filter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inFilter"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The  ",
              "type": "text"
            },
            {
              "code": "IKFilterUIView",
              "type": "codeVoice"
            },
            {
              "text": " object initialized with controls for the input parameters of the provided filter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView": {
      "abstract": [
        {
          "text": "Input parameters for filtering core image filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterUIView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterUIView"
        }
      ],
      "role": "symbol",
      "title": "IKFilterUIView",
      "type": "topic",
      "url": "/documentation/quartz/ikfilteruiview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/init(frame:filter:)": {
      "abstract": [
        {
          "text": "Initializes a view that contains controls for the input parameters of a filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIFilter",
          "text": "CIFilter"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/init(frame:filter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:filter:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:filter:)",
      "type": "topic",
      "url": "/documentation/quartz/ikfilteruiview/init(frame:filter:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/view(withFrame:filter:)": {
      "abstract": [
        {
          "text": "Creates a view that contains controls for the input parameters of a filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "view"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIFilter",
          "text": "CIFilter"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/view(withFrame:filter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWithFrame:filter:"
        }
      ],
      "role": "symbol",
      "title": "view(withFrame:filter:)",
      "type": "topic",
      "url": "/documentation/quartz/ikfilteruiview/view(withframe:filter:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CIFilter": {
      "abstract": [
        {
          "text": "An image processor that produces an image by manipulating one or more input images or by generating new image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIFilter"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CIFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIFilter",
      "type": "topic",
      "url": "/documentation/coreimage/cifilter"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-and-Initializing-a-Filter-UI-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/view(withFrame:filter:)"
      ],
      "title": "Creating and Initializing a Filter UI View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithFrame:filter:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:filter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-and-Initializing-a-Filter-UI-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView/view(withFrame:filter:)"
              ],
              "title": "Creating and Initializing a Filter UI View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithFrame:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSRect",
                    "text": "NSRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "frameRect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "filter:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CIFilter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CIFilter",
                    "text": "CIFilter"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inFilter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The rectangle that defines the area of the view.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "frameRect"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Core Image filter. The view retains the filter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inFilter"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The  ",
                    "type": "text"
                  },
                  {
                    "code": "IKFilterUIView",
                    "type": "codeVoice"
                  },
                  {
                    "text": " object initialized with controls for the input parameters of the provided filter.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView~1init(frame:filter:)/title",
          "value": "initWithFrame:filter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView~1init(frame:filter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:filter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView/title",
          "value": "IKFilterUIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterUIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterUIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView~1view(withFrame:filter:)/title",
          "value": "viewWithFrame:filter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView~1view(withFrame:filter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "viewWithFrame:filter:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/ikfilteruiview/init(frame:filter:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/ikfilteruiview/init(frame:filter:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
