{"abstract":[{"type":"text","text":"A link to the Apple Music page that contains the full information for the song."}],"seeAlsoSections":[{"title":"Reading Apple Music properties","anchor":"Reading-Apple-Music-properties","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/songs","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicID"],"generated":true}],"variants":[{"paths":["/documentation/shazamkit/shmediaitem/applemusicurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/shazamkit/shmediaitem/applemusicurl"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appleMusicURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"appleMusicURL","kind":"identifier"}],"platforms":[{"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"12.0","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"watchOS","beta":false}],"modules":[{"name":"ShazamKit"}],"roleHeading":"Instance Property","title":"appleMusicURL","externalID":"c:objc(cs)SHMediaItem(py)appleMusicURL","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appleMusicURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property"},"sections":[],"identifier":{"url":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicURL","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"references":{"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"fragments":[{"text":"struct ","kind":"text"},{"text":"URL","kind":"identifier"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","title":"URL","url":"/documentation/foundation/url","kind":"symbol","abstract":[{"type":"text","text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file."}],"role":"symbol"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/songs":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"songs"},{"text":": [","kind":"text"},{"text":"Song","kind":"typeIdentifier","preciseIdentifier":"s:8MusicKit4SongV"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/songs","kind":"symbol","type":"topic","url":"/documentation/shazamkit/shmediaitem/songs","abstract":[{"type":"text","text":"An array of MusicKit song objects that represent the song."}],"title":"songs"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem","navigatorTitle":[{"text":"SHMediaItem","kind":"identifier"}],"abstract":[{"text":"An object that represents the metadata for a reference signature.","type":"text"}],"url":"/documentation/shazamkit/shmediaitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SHMediaItem","kind":"identifier"}],"title":"SHMediaItem"},"doc://com.apple.shazamkit/documentation/ShazamKit":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit","url":"/documentation/shazamkit","type":"topic","role":"collection","kind":"symbol","title":"ShazamKit","abstract":[{"type":"text","text":"Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog."}]},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicID":{"abstract":[{"type":"text","text":"The Apple Music ID for the song."}],"navigatorTitle":[{"text":"appleMusicID","kind":"identifier"}],"url":"/documentation/shazamkit/shmediaitem/applemusicid","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleMusicID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicID","type":"topic","kind":"symbol","title":"appleMusicID"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicURL":{"abstract":[{"type":"text","text":"A link to the Apple Music page that contains the full information for the song."}],"navigatorTitle":[{"text":"appleMusicURL","kind":"identifier"}],"url":"/documentation/shazamkit/shmediaitem/applemusicurl","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleMusicURL"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicURL","type":"topic","kind":"symbol","title":"appleMusicURL"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"15.0","deprecated":false,"beta":false,"name":"iOS"},{"name":"iPadOS","introducedAt":"15.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"15.0","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","introducedAt":"12.0","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","introducedAt":"15.0","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false}],"op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"appleMusicURL","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"appleMusicURL","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Reading Apple Music properties","anchor":"Reading-Apple-Music-properties","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/appleMusicID"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"appleMusicURL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]},{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"appleMusicURL"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"SHMediaItem","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/title"},{"value":[{"kind":"identifier","text":"SHMediaItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/fragments"},{"value":[{"kind":"identifier","text":"SHMediaItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/navigatorTitle"},{"value":"appleMusicID","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1appleMusicID/title"},{"value":[{"text":"appleMusicID","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1appleMusicID/fragments"},{"value":"appleMusicURL","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1appleMusicURL/title"},{"value":[{"text":"appleMusicURL","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1appleMusicURL/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}