{"variants":[{"paths":["/documentation/shazamkit/shmediaitem/fetch(shazamid:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/shazamkit/shmediaitem/fetch(shazamid:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"c:objc(cs)SHMediaItem(cm)fetchMediaItemWithShazamID:completionHandler:","navigatorTitle":[{"kind":"identifier","text":"fetchMediaItemWithShazamID:completionHandler:"}],"modules":[{"name":"ShazamKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shazamID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)SHMediaItem","kind":"typeIdentifier","text":"SHMediaItem"},{"kind":"text","text":"?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Type Method","title":"fetch(shazamID:completionHandler:)","role":"symbol","platforms":[{"introducedAt":"15.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"15.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"12.0","deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"introducedAt":"15.0","deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false},{"introducedAt":"8.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}]},"abstract":[{"type":"text","text":"Requests the media item for the song with the specified Shazam ID."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/webURL","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/shazamID"],"anchor":"Working-with-Shazam-music-catalog-media-items","title":"Working with Shazam music catalog media items","generated":true}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/fetch(shazamID:completionHandler:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shazamID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"SHMediaItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SHMediaItem","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},{"text":")","kind":"text"}]},{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shazamID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SHMediaItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SHMediaItem","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Shazam ID of the song."}],"type":"paragraph"}],"name":"shazamID"},{"content":[{"inlineContent":[{"type":"text","text":"The completion handler that the system calls with the result of the request."}],"type":"paragraph"},{"inlineContent":[{"text":"This block takes the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"A media item.","type":"text"}]}]},"term":{"inlineContent":[{"code":"mediaItem","type":"codeVoice"}]}},{"definition":{"content":[{"inlineContent":[{"text":"An error object if a problem occurs when fetching the media item; otherwise, ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"codeVoice","code":"error"}]}}],"type":"termList"}],"name":"completionHandler"}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:","type":"text"}],"type":"paragraph"},{"code":["class func fetch(shazamID: String) async throws -> SHMediaItem"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"For information about concurrency and asynchronous code in Swift, see "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"Important","style":"important","type":"aside"}]}],"references":{"doc://com.externally.resolved.symbol/s:s5ErrorP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s8SendableP","kind":"typeIdentifier","text":"Sendable"}],"kind":"symbol","url":"/documentation/Swift/Error","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","abstract":[{"text":"A type representing an error value that can be thrown.","type":"text"}],"title":"Error","role":"symbol"},"doc://com.externally.resolved.symbol/s:s4Voida":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"url":"/documentation/Swift/Void","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","title":"Void","type":"topic"},"doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously":{"identifier":"doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously","type":"topic","title":"Calling Objective-C APIs Asynchronously","role":"article","abstract":[{"text":"Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.","type":"text"}],"kind":"article","url":"/documentation/Swift/calling-objective-c-apis-asynchronously"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem","navigatorTitle":[{"text":"SHMediaItem","kind":"identifier"}],"abstract":[{"text":"An object that represents the metadata for a reference signature.","type":"text"}],"url":"/documentation/shazamkit/shmediaitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SHMediaItem","kind":"identifier"}],"title":"SHMediaItem"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/fetch(shazamID:completionHandler:)":{"url":"/documentation/shazamkit/shmediaitem/fetch(shazamid:completionhandler:)","abstract":[{"type":"text","text":"Requests the media item for the song with the specified Shazam ID."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shazamID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)SHMediaItem","text":"SHMediaItem","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fetchMediaItemWithShazamID:completionHandler:"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/fetch(shazamID:completionHandler:)","title":"fetch(shazamID:completionHandler:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}],"kind":"symbol","url":"/documentation/Swift/String"},"doc://com.apple.shazamkit/documentation/ShazamKit":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit","url":"/documentation/shazamkit","type":"topic","role":"collection","kind":"symbol","title":"ShazamKit","abstract":[{"type":"text","text":"Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog."}]},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/webURL":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"kind":"symbol","url":"/documentation/shazamkit/shmediaitem/weburl","type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/webURL","abstract":[{"text":"A link to the Shazam Music catalog page that contains the full information for the song.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"webURL"}],"title":"webURL","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSError"}],"url":"/documentation/foundation/nserror","type":"topic","kind":"symbol","role":"symbol","title":"NSError","abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/shazamID":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shazamID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shazamID"}],"abstract":[{"type":"text","text":"The Shazam ID for the song."}],"url":"/documentation/shazamkit/shmediaitem/shazamid","kind":"symbol","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/shazamID","title":"shazamID","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"15.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"12.0","deprecated":false,"unavailable":false,"name":"macOS","beta":false},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS","beta":false},{"name":"watchOS","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Type Method","path":"/metadata/roleHeading"},{"op":"replace","value":"fetchMediaItemWithShazamID:completionHandler:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fetchMediaItemWithShazamID:completionHandler:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Working with Shazam music catalog media items","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/webURL","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/shazamID"],"anchor":"Working-with-Shazam-music-catalog-media-items","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"fetchMediaItemWithShazamID:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"shazamID"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem","preciseIdentifier":"c:objc(cs)SHMediaItem","kind":"typeIdentifier","text":"SHMediaItem"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"mediaItem"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"error"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"name":"shazamID","content":[{"inlineContent":[{"text":"The Shazam ID of the song.","type":"text"}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler that the system calls with the result of the request.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This block takes the following parameters:","type":"text"}]},{"type":"termList","items":[{"term":{"inlineContent":[{"code":"mediaItem","type":"codeVoice"}]},"definition":{"content":[{"inlineContent":[{"text":"A media item.","type":"text"}],"type":"paragraph"}]}},{"term":{"inlineContent":[{"type":"codeVoice","code":"error"}]},"definition":{"content":[{"inlineContent":[{"type":"text","text":"An error object if a problem occurs when fetching the media item; otherwise, "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/title","op":"replace","value":"SHMediaItem"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/fragments","op":"replace","value":[{"kind":"identifier","text":"SHMediaItem"}]},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/navigatorTitle","op":"replace","value":[{"text":"SHMediaItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1fetch(shazamID:completionHandler:)/title","op":"replace","value":"fetchMediaItemWithShazamID:completionHandler:"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1fetch(shazamID:completionHandler:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fetchMediaItemWithShazamID:completionHandler:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1webURL/title","op":"replace","value":"webURL"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1webURL/fragments","op":"replace","value":[{"kind":"identifier","text":"webURL"}]},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1shazamID/title","op":"replace","value":"shazamID"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1shazamID/fragments","op":"replace","value":[{"kind":"identifier","text":"shazamID"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}