{"variants":[{"paths":["/documentation/shazamkit/shmediaitem/identifiable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/Identifiable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"metadata":{"title":"Identifiable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ShazamKit"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/id"],"anchor":"Instance-Properties","generated":true}],"kind":"article","references":{"doc://com.apple.shazamkit/documentation/ShazamKit":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit","url":"/documentation/shazamkit","type":"topic","role":"collection","kind":"symbol","title":"ShazamKit","abstract":[{"type":"text","text":"Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog."}]},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem","navigatorTitle":[{"text":"SHMediaItem","kind":"identifier"}],"abstract":[{"text":"An object that represents the metadata for a reference signature.","type":"text"}],"url":"/documentation/shazamkit/shmediaitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SHMediaItem","kind":"identifier"}],"title":"SHMediaItem"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/id":{"role":"symbol","title":"id","abstract":[{"text":"A unique identifier for this media item.","type":"text"}],"type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/id","url":"/documentation/shazamkit/shmediaitem/id","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}]}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/title","op":"replace","value":"SHMediaItem"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/fragments","value":[{"text":"SHMediaItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/navigatorTitle","value":[{"text":"SHMediaItem","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}