{
  "abstract": [
    {
      "text": "Accesses the property for the specified key for reading.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subscript(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SHMediaItem(im)objectForKeyedSubscript:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "subscript"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SHMediaItemProperty",
        "text": "SHMediaItemProperty"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "keyword",
        "text": "Any"
      }
    ],
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "objectForKeyedSubscript:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Subscript",
    "symbolKind": "subscript",
    "title": "subscript(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "subscript"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SHMediaItemProperty",
              "text": "SHMediaItemProperty"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key for the media item property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of the property; otherwise, ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem": {
      "abstract": [
        {
          "text": "An object that represents the metadata for a reference signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHMediaItem"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHMediaItem"
        }
      ],
      "role": "symbol",
      "title": "SHMediaItem",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-1j7d3": {
      "abstract": [
        {
          "text": "An array of ranges that indicate the frequency skews in the reference signature that this media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frequencySkewRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-1j7d3",
      "kind": "symbol",
      "role": "symbol",
      "title": "frequencySkewRanges",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/frequencyskewranges-1j7d3"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-4yqx": {
      "abstract": [
        {
          "text": "An array of ranges that indicate the frequency skews in the reference signature that this media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "frequencySkewRanges"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-4yqx",
      "kind": "symbol",
      "role": "symbol",
      "title": "frequencySkewRanges",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/frequencyskewranges-4yqx"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subscript(_:)": {
      "abstract": [
        {
          "text": "Accesses the property for the specified key for reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SHMediaItemProperty",
          "text": "SHMediaItemProperty"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/subscript(_:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-43654": {
      "abstract": [
        {
          "text": "An array of ranges that indicate the offsets within the reference signature that this media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "timeRanges"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-43654",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeRanges",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/timeranges-43654"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-8msna": {
      "abstract": [
        {
          "text": "An array of ranges that indicate the offsets within the reference signature that this media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-8msna",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeRanges",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/timeranges-8msna"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/valueForProperty:": {
      "abstract": [
        {
          "text": "Accesses the property for the specified key for reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/valueForProperty:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "role": "symbol",
      "title": "valueForProperty:",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/valueforproperty:"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty": {
      "abstract": [
        {
          "text": "Constants for the media item property names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHMediaItemProperty"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHMediaItemProperty"
        }
      ],
      "role": "symbol",
      "title": "SHMediaItemProperty",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitemproperty"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange": {
      "abstract": [
        {
          "text": "A half-open interval from a lower bound up to, but not including, an upper bound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SHRange"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "SHRange",
      "type": "topic",
      "url": "/documentation/shazamkit/shrange"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-media-item-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-8msna",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-1j7d3"
      ],
      "title": "Working with media item properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.shazamkit/documentation/ShazamKit",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-media-item-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/valueForProperty:",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-43654",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-4yqx",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange"
              ],
              "title": "Working with media item properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "objectForKeyedSubscript:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SHMediaItemProperty",
                    "text": "SHMediaItemProperty"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The key for the media item property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "key"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The value of the property; otherwise, ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/title",
          "value": "SHMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItemProperty/title",
          "value": "SHMediaItemProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItemProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHMediaItemProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItemProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHMediaItemProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/shmediaitem/subscript(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/shazamkit/shmediaitem/subscript(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
