{"seeAlsoSections":[{"anchor":"Reading-general-media-item-properties","generated":true,"title":"Reading general media item properties","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/title","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subtitle","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artist","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artworkURL","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/genres","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/explicitContent","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/creationDate","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/isrc","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/id"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"title":"videoURL","navigatorTitle":[{"kind":"identifier","text":"videoURL"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)SHMediaItem(py)videoURL","symbolKind":"property","modules":[{"name":"ShazamKit"}],"platforms":[{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"12.0","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"},{"introducedAt":"8.0","beta":false,"unavailable":false,"deprecated":false,"name":"watchOS"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoURL","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/shazamkit/shmediaitem/videourl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/shazamkit/shmediaitem/videourl"]}],"identifier":{"url":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/videoURL","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The URL for a video for the media item, such as a music video."}],"references":{"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/explicitContent":{"url":"/documentation/shazamkit/shmediaitem/explicitcontent","title":"explicitContent","abstract":[{"text":"A Boolean value that indicates whether the media item contains explicit content.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/explicitContent","navigatorTitle":[{"kind":"identifier","text":"explicitContent"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"explicitContent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artworkURL":{"url":"/documentation/shazamkit/shmediaitem/artworkurl","role":"symbol","title":"artworkURL","abstract":[{"type":"text","text":"The URL for artwork for the media item, such as an album cover."}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artworkURL","navigatorTitle":[{"kind":"identifier","text":"artworkURL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"artworkURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/creationDate":{"url":"/documentation/shazamkit/shmediaitem/creationdate","title":"creationDate","abstract":[{"text":"The date the media item was created.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/creationDate","navigatorTitle":[{"kind":"identifier","text":"creationDate"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creationDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/videoURL":{"url":"/documentation/shazamkit/shmediaitem/videourl","role":"symbol","title":"videoURL","abstract":[{"text":"The URL for a video for the media item, such as a music video.","type":"text"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/videoURL","navigatorTitle":[{"text":"videoURL","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subtitle":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subtitle","abstract":[{"type":"text","text":"A subtitle for the media item."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"subtitle"}],"role":"symbol","kind":"symbol","title":"subtitle","type":"topic","url":"/documentation/shazamkit/shmediaitem/subtitle"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/genres":{"url":"/documentation/shazamkit/shmediaitem/genres","role":"symbol","title":"genres","abstract":[{"type":"text","text":"An array of genre names for the media item."}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/genres","navigatorTitle":[{"kind":"identifier","text":"genres"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"genres"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/id":{"role":"symbol","title":"id","abstract":[{"text":"A unique identifier for this media item.","type":"text"}],"type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/id","url":"/documentation/shazamkit/shmediaitem/id","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}]},"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"fragments":[{"text":"struct ","kind":"text"},{"text":"URL","kind":"identifier"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","title":"URL","url":"/documentation/foundation/url","kind":"symbol","abstract":[{"type":"text","text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file."}],"role":"symbol"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artist":{"url":"/documentation/shazamkit/shmediaitem/artist","role":"symbol","title":"artist","abstract":[{"type":"text","text":"The name of the artist for the media item, such as the performer of a song."}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artist","navigatorTitle":[{"kind":"identifier","text":"artist"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"artist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem","navigatorTitle":[{"text":"SHMediaItem","kind":"identifier"}],"abstract":[{"text":"An object that represents the metadata for a reference signature.","type":"text"}],"url":"/documentation/shazamkit/shmediaitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SHMediaItem","kind":"identifier"}],"title":"SHMediaItem"},"doc://com.apple.shazamkit/documentation/ShazamKit":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit","url":"/documentation/shazamkit","type":"topic","role":"collection","kind":"symbol","title":"ShazamKit","abstract":[{"type":"text","text":"Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog."}]},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/isrc":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/isrc","abstract":[{"text":"The International Standard Recording Code (ISRC) for the media item.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"isrc"}],"role":"symbol","kind":"symbol","title":"isrc","type":"topic","url":"/documentation/shazamkit/shmediaitem/isrc"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/title":{"kind":"symbol","identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/title","type":"topic","title":"title","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"/documentation/shazamkit/shmediaitem/title","abstract":[{"text":"A title for the media item.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","introducedAt":"15.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"15.0","beta":false,"unavailable":false},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"introducedAt":"12.0","deprecated":false,"name":"macOS"},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"tvOS"},{"unavailable":false,"beta":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS"},{"unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"videoURL","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"videoURL","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Reading general media item properties","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/title","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subtitle","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artist","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/artworkURL","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/genres","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/explicitContent","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/creationDate","doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/isrc"],"anchor":"Reading-general-media-item-properties"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"videoURL"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"]},{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"videoURL","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"explicitContent","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1explicitContent/title"},{"op":"replace","value":[{"text":"explicitContent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1explicitContent/fragments"},{"op":"replace","value":"artworkURL","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1artworkURL/title"},{"op":"replace","value":[{"text":"artworkURL","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1artworkURL/fragments"},{"op":"replace","value":"creationDate","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1creationDate/title"},{"op":"replace","value":[{"text":"creationDate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1creationDate/fragments"},{"op":"replace","value":"videoURL","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1videoURL/title"},{"op":"replace","value":[{"kind":"identifier","text":"videoURL"}],"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1videoURL/fragments"},{"op":"replace","value":"subtitle","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1subtitle/title"},{"op":"replace","value":[{"text":"subtitle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1subtitle/fragments"},{"value":"genres","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1genres/title"},{"value":[{"kind":"identifier","text":"genres"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1genres/fragments"},{"value":"artist","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1artist/title"},{"value":[{"kind":"identifier","text":"artist"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1artist/fragments"},{"value":"SHMediaItem","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/title"},{"value":[{"kind":"identifier","text":"SHMediaItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/fragments"},{"value":[{"text":"SHMediaItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem/navigatorTitle"},{"value":"isrc","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1isrc/title"},{"value":[{"kind":"identifier","text":"isrc"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1isrc/fragments"},{"value":"title","op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1title/title"},{"value":[{"kind":"identifier","text":"title"}],"op":"replace","path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1title/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}