{
  "abstract": [
    {
      "text": "If set, the generic view displays the audio unit parameters of the audio unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUGenericViewDisplayFlags@AUViewParametersDisplayFlag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "viewParametersDisplayFlag"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
        "text": "AUGenericViewDisplayFlags"
      }
    ],
    "modules": [
      {
        "name": "CoreAudioKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUViewParametersDisplayFlag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "viewParametersDisplayFlag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "viewParametersDisplayFlag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
              "text": "AUGenericViewDisplayFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit": {
      "abstract": [
        {
          "text": "Add user interfaces to audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreAudioKit",
      "type": "topic",
      "url": "/documentation/coreaudiokit"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags": {
      "abstract": [
        {
          "text": "Flags that describe the display of a generic view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "AUGenericViewDisplayFlags",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag": {
      "abstract": [
        {
          "text": "If set, the generic view displays the audio unit parameters of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewParametersDisplayFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewParametersDisplayFlag"
        }
      ],
      "role": "symbol",
      "title": "viewParametersDisplayFlag",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/viewparametersdisplayflag"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag": {
      "abstract": [
        {
          "text": "If set, the generic view displays the audio unit properties of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewPropertiesDisplayFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewPropertiesDisplayFlag"
        }
      ],
      "role": "symbol",
      "title": "viewPropertiesDisplayFlag",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/viewpropertiesdisplayflag"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag": {
      "abstract": [
        {
          "text": "If set, the generic view displays the title and manufacturer of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewTitleDisplayFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewTitleDisplayFlag"
        }
      ],
      "role": "symbol",
      "title": "viewTitleDisplayFlag",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/viewtitledisplayflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Display-Flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag"
      ],
      "title": "Display Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUViewParametersDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewParametersDisplayFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Display-Flags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag"
              ],
              "title": "Display Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AUViewParametersDisplayFlag"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/title",
          "value": "AUGenericViewDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewTitleDisplayFlag/title",
          "value": "AUViewTitleDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewTitleDisplayFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewTitleDisplayFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewPropertiesDisplayFlag/title",
          "value": "AUViewPropertiesDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewPropertiesDisplayFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewPropertiesDisplayFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewParametersDisplayFlag/title",
          "value": "AUViewParametersDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewParametersDisplayFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewParametersDisplayFlag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiokit/augenericviewdisplayflags/viewparametersdisplayflag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiokit/augenericviewdisplayflags/viewparametersdisplayflag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
