{
  "abstract": [
    {
      "text": "The face is a part of a real-world window.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/window"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARMeshClassification@ARMeshClassificationWindow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "window"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARMeshClassificationWindow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARMeshClassification.window"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "window"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification": {
      "abstract": [
        {
          "text": "Enumeration of different classes of real-world objects that ARKit can identify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARMeshClassification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassification"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/ceiling": {
      "abstract": [
        {
          "text": "The face is a part of a real-world ceiling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ceiling"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/ceiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationCeiling"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.ceiling",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/ceiling"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/door": {
      "abstract": [
        {
          "text": "The face is a part of a real-world door.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "door"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/door",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationDoor"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.door",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/door"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/floor": {
      "abstract": [
        {
          "text": "The face is a part of a real-world floor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/floor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationFloor"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.floor",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/floor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/none": {
      "abstract": [
        {
          "text": "A face ARKit can’t classify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationNone"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.none",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/none"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/seat": {
      "abstract": [
        {
          "text": "The face is a part of a real-world seat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seat"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/seat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationSeat"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.seat",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/seat"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/table": {
      "abstract": [
        {
          "text": "The face is a part of a real-world table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/table",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationTable"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.table",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/table"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/wall": {
      "abstract": [
        {
          "text": "The face is a part of a real-world wall.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wall"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/wall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationWall"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.wall",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/wall"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/window": {
      "abstract": [
        {
          "text": "The face is a part of a real-world window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/window",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassificationWindow"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification.window",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification/window"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/ceiling",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/door",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/floor",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/none",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/seat",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/table",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/wall"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARMeshClassificationWindow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/ceiling",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/door",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/floor",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/none",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/seat",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/table",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification/wall"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ARMeshClassificationWindow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification/title",
          "value": "ARMeshClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1floor/title",
          "value": "ARMeshClassificationFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1floor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1ceiling/title",
          "value": "ARMeshClassificationCeiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1ceiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationCeiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1table/title",
          "value": "ARMeshClassificationTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1table/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1none/title",
          "value": "ARMeshClassificationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1door/title",
          "value": "ARMeshClassificationDoor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1door/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationDoor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1window/title",
          "value": "ARMeshClassificationWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1window/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1seat/title",
          "value": "ARMeshClassificationSeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1seat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationSeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1wall/title",
          "value": "ARMeshClassificationWall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification~1wall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassificationWall"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/armeshclassification/window"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/armeshclassification/window"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
