{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/ExpressibleByFloatLiteral-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ExpressibleByFloatLiteral Implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity": {
      "abstract": [
        {
          "text": "A value that describes how fast a gesture moves across the screen, in pixels per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocity"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocity"
        }
      ],
      "role": "symbol",
      "title": "XCUIGestureVelocity",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuigesturevelocity"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/FloatLiteralType": {
      "abstract": [
        {
          "text": "The native type that specifies the gesture velocity value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FloatLiteralType"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/FloatLiteralType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FloatLiteralType"
        }
      ],
      "role": "symbol",
      "title": "XCUIGestureVelocity.FloatLiteralType",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuigesturevelocity/floatliteraltype"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/init(floatLiteral:)": {
      "abstract": [
        {
          "text": "Creates a gesture velocity with a float value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "floatLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So19XCUIGestureVelocitya14XCUIAutomationE16FloatLiteralTypea",
          "text": "FloatLiteralType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/init(floatLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(floatLiteral:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuigesturevelocity/init(floatliteral:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/init(floatLiteral:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIGestureVelocity/FloatLiteralType"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIGestureVelocity/title",
          "value": "XCUIGestureVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIGestureVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIGestureVelocity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation/xcuigesturevelocity/expressiblebyfloatliteral-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
