{
  "abstract": [
    {
      "text": "The value of the horizontal axis of the dpad.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/withMicroGamepad()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadX"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@GCMicroGamepadSnapShotDataV100@FI@dpadX",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dpadX"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dpadX"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "Use the -[GCController controllerWithMicroGamepad] method instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "Use the -[GCController controllerWithMicroGamepad] method instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use the -[GCController controllerWithMicroGamepad] method instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.11",
        "message": "Use the -[GCController controllerWithMicroGamepad] method instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "Use the -[GCController controllerWithMicroGamepad] method instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use the -[GCController controllerWithMicroGamepad] method instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dpadX"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dpadX"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The range of permissible values is ",
              "type": "text"
            },
            {
              "code": "-1.0",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ", inclusive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/withMicroGamepad()": {
      "abstract": [
        {
          "text": "Returns a snapshot of a newly created controller with a micro gamepad profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withMicroGamepad"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCController",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/withMicroGamepad()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controllerWithMicroGamepad"
        }
      ],
      "role": "symbol",
      "title": "withMicroGamepad()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/withmicrogamepad()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100": {
      "abstract": [
        {
          "text": "A structure that holds a snapshot of a micro gamepad controller’s input data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapShotDataV100"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapShotDataV100"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadSnapShotDataV100",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonA": {
      "abstract": [
        {
          "text": "The value of the A button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonA"
        }
      ],
      "role": "symbol",
      "title": "buttonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/buttona"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonX": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonX"
        }
      ],
      "role": "symbol",
      "title": "buttonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/buttonx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadX": {
      "abstract": [
        {
          "text": "The value of the horizontal axis of the dpad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpadX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dpadX"
        }
      ],
      "role": "symbol",
      "title": "dpadX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/dpadx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadY": {
      "abstract": [
        {
          "text": "The value of the vertical axis of the dpad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpadY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dpadY"
        }
      ],
      "role": "symbol",
      "title": "dpadY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/dpady"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/size": {
      "abstract": [
        {
          "text": "The size of the recorded structure, in bytes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/size"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/version": {
      "abstract": [
        {
          "text": "A value that indicates the version number of the data structure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/version"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonA",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadY",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/size",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dpadX"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpadX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonA",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/buttonX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/dpadY",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/size",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapShotDataV100/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "dpadX"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1buttonA/title",
          "value": "buttonA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1buttonA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1withMicroGamepad()/title",
          "value": "controllerWithMicroGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1withMicroGamepad()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "controllerWithMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1dpadY/title",
          "value": "dpadY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1dpadY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpadY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1dpadX/title",
          "value": "dpadX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1dpadX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpadX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100/title",
          "value": "GCMicroGamepadSnapShotDataV100"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1buttonX/title",
          "value": "buttonX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapShotDataV100~1buttonX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonX"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/dpadx"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcmicrogamepadsnapshotdatav100/dpadx"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
