{
  "abstract": [
    {
      "text": "A dictionary representation of the property state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/propertiesDictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMIOExtensionStreamProperties(py)propertiesDictionary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "propertiesDictionary"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMIOExtensionProperty",
        "text": "CMIOExtensionProperty"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
        "text": "CMIOExtensionPropertyState"
      },
      {
        "kind": "text",
        "text": "<AnyObject>]"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "propertiesDictionary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "propertiesDictionary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "propertiesDictionary"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMIOExtensionProperty",
              "text": "CMIOExtensionProperty"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
              "text": "CMIOExtensionPropertyState"
            },
            {
              "kind": "text",
              "text": "<AnyObject>] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty": {
      "abstract": [
        {
          "text": "A structure that defines the properties that providers, devices, and streams support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProperty"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProperty",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState": {
      "abstract": [
        {
          "text": "An object that describes the state of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyState"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyState"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionPropertyState",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties": {
      "abstract": [
        {
          "text": "An object that describes the properties of an extension stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionStreamProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionStreamProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionStreamProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstreamproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/propertiesDictionary": {
      "abstract": [
        {
          "text": "A dictionary representation of the property state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertiesDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
          "text": "CMIOExtensionPropertyState"
        },
        {
          "kind": "text",
          "text": "<AnyObject>]"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/propertiesDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertiesDictionary"
        }
      ],
      "role": "symbol",
      "title": "propertiesDictionary",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstreamproperties/propertiesdictionary"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/setPropertyState(_:forProperty:)": {
      "abstract": [
        {
          "text": "Sets the state of the specified property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPropertyState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
          "text": "CMIOExtensionPropertyState"
        },
        {
          "kind": "text",
          "text": "<AnyObject>?, "
        },
        {
          "kind": "externalParam",
          "text": "forProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/setPropertyState(_:forProperty:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPropertyState:forProperty:"
        }
      ],
      "role": "symbol",
      "title": "setPropertyState(_:forProperty:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstreamproperties/setpropertystate(_:forproperty:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Property-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/setPropertyState(_:forProperty:)"
      ],
      "title": "Managing Property State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "propertiesDictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "propertiesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Property-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/setPropertyState(_:forProperty:)"
              ],
              "title": "Managing Property State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,CMIOExtensionPropertyState *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "propertiesDictionary"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties~1propertiesDictionary/title",
          "value": "propertiesDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties~1propertiesDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "propertiesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties~1setPropertyState(_:forProperty:)/title",
          "value": "setPropertyState:forProperty:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties~1setPropertyState(_:forProperty:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPropertyState:forProperty:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/title",
          "value": "CMIOExtensionProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/title",
          "value": "CMIOExtensionPropertyState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/title",
          "value": "CMIOExtensionStreamProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamProperties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionstreamproperties/propertiesdictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionstreamproperties/propertiesdictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
