{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coremediaio/cmioextensionstreamproperties/sinkbufferunderruncount-9sph5"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sinkBufferUnderrunCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This value is a number the system increments whenever you’re not servicing buffers fast enough."}]},{"type":"paragraph","inlineContent":[{"text":"This property translates to the ","type":"text"},{"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount","isActive":true,"type":"reference"},{"text":" property.","type":"text"}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"text":"sinkBufferUnderrunCount","kind":"identifier"}],"symbolKind":"property","platforms":[{"introducedAt":"15.4","beta":false,"name":"Mac Catalyst"},{"introducedAt":"12.3","beta":false,"name":"macOS"}],"fragments":[{"text":"sinkBufferUnderrunCount","kind":"identifier"}],"modules":[{"name":"Core Media I/O"}],"roleHeading":"Instance Property","role":"symbol","title":"sinkBufferUnderrunCount","externalID":"c:objc(cs)CMIOExtensionStreamProperties(py)sinkBufferUnderrunCount"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremediaio/documentation/CoreMediaIO","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties"]]},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBufferUnderrunCount-9sph5"},"seeAlsoSections":[{"identifiers":["doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBufferQueueSize-4kpug","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBuffersRequiredForStartup-4b5te","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkEndOfData-30he9"],"anchor":"Configuring-Sink-Properties","title":"Configuring Sink Properties","generated":true}],"sections":[],"abstract":[{"text":"The buffer underrun count.","type":"text"}],"references":{"doc://com.apple.coremediaio/documentation/CoreMediaIO":{"role":"collection","title":"Core Media I/O","type":"topic","abstract":[{"type":"text","text":"Securely support custom camera devices in macOS."}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO","url":"/documentation/coremediaio","kind":"symbol"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkEndOfData-30he9":{"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkEndOfData-30he9","role":"symbol","kind":"symbol","url":"/documentation/coremediaio/cmioextensionstreamproperties/sinkendofdata-30he9","title":"sinkEndOfData","type":"topic","fragments":[{"text":"sinkEndOfData","kind":"identifier"}],"abstract":[{"type":"text","text":"A value that indicates whether the stream has reached its end."}]},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBufferQueueSize-4kpug":{"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBufferQueueSize-4kpug","role":"symbol","kind":"symbol","url":"/documentation/coremediaio/cmioextensionstreamproperties/sinkbufferqueuesize-4kpug","title":"sinkBufferQueueSize","type":"topic","fragments":[{"text":"sinkBufferQueueSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The buffer queue size."}]},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties":{"navigatorTitle":[{"kind":"identifier","text":"CMIOExtensionStreamProperties"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CMIOExtensionStreamProperties"}],"url":"/documentation/coremediaio/cmioextensionstreamproperties","identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties","abstract":[{"text":"An object that describes the properties of an extension stream.","type":"text"}],"role":"symbol","kind":"symbol","title":"CMIOExtensionStreamProperties","type":"topic"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount":{"title":"kCMIOStreamPropertyOutputBufferUnderrunCount","url":"/documentation/coremediaio/kcmiostreampropertyoutputbufferunderruncount","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kCMIOStreamPropertyOutputBufferUnderrunCount"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount","navigatorTitle":[{"kind":"identifier","text":"kCMIOStreamPropertyOutputBufferUnderrunCount"}],"kind":"symbol","type":"topic","abstract":[]},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBufferUnderrunCount-9sph5":{"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBufferUnderrunCount-9sph5","type":"topic","title":"sinkBufferUnderrunCount","role":"symbol","abstract":[{"text":"The buffer underrun count.","type":"text"}],"fragments":[{"text":"sinkBufferUnderrunCount","kind":"identifier"}],"url":"/documentation/coremediaio/cmioextensionstreamproperties/sinkbufferunderruncount-9sph5","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","title":"Technologies","type":"topic","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber":{"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSNumber"}],"url":"/documentation/foundation/nsnumber","title":"NSNumber","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","abstract":[{"type":"text","text":"An object wrapper for primitive scalar numeric values."}],"type":"topic","role":"symbol"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBuffersRequiredForStartup-4b5te":{"fragments":[{"text":"sinkBuffersRequiredForStartup","kind":"identifier"}],"url":"/documentation/coremediaio/cmioextensionstreamproperties/sinkbuffersrequiredforstartup-4b5te","identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties/sinkBuffersRequiredForStartup-4b5te","abstract":[{"text":"The number of buffers the stream requires for startup.","type":"text"}],"role":"symbol","kind":"symbol","title":"sinkBuffersRequiredForStartup","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CMIOExtensionStreamProperties","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/title"},{"op":"replace","value":[{"text":"CMIOExtensionStreamProperties","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/fragments"},{"op":"replace","value":[{"text":"CMIOExtensionStreamProperties","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/navigatorTitle"},{"op":"replace","value":"kCMIOStreamPropertyOutputBufferUnderrunCount","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferUnderrunCount/title"},{"value":[{"text":"kCMIOStreamPropertyOutputBufferUnderrunCount","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferUnderrunCount/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}