{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUParameterMIDIMappingFlags@kAUParameterMIDIMapping_Bipolar",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bipolar"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
        "text": "AUParameterMIDIMappingFlags"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUParameterMIDIMapping_Bipolar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bipolar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bipolar"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
              "text": "AUParameterMIDIMappingFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUParameterMIDIMappingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyChannelFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyChannelFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyChannelFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUParameterMIDIMapping_AnyChannelFlag"
        }
      ],
      "role": "symbol",
      "title": "anyChannelFlag",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags/anychannelflag"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyNoteFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyNoteFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyNoteFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUParameterMIDIMapping_AnyNoteFlag"
        }
      ],
      "role": "symbol",
      "title": "anyNoteFlag",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags/anynoteflag"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bipolar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUParameterMIDIMapping_Bipolar"
        }
      ],
      "role": "symbol",
      "title": "bipolar",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags/bipolar"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar_On": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bipolar_On"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar_On",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUParameterMIDIMapping_Bipolar_On"
        }
      ],
      "role": "symbol",
      "title": "bipolar_On",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags/bipolar_on"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/subRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/subRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUParameterMIDIMapping_SubRange"
        }
      ],
      "role": "symbol",
      "title": "subRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags/subrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/toggle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/toggle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUParameterMIDIMapping_Toggle"
        }
      ],
      "role": "symbol",
      "title": "toggle",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags/toggle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyChannelFlag",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyNoteFlag",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar_On",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/subRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/toggle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUParameterMIDIMapping_Bipolar"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_Bipolar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyChannelFlag",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/anyNoteFlag",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/bipolar_On",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/subRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags/toggle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAUParameterMIDIMapping_Bipolar"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1anyNoteFlag/title",
          "value": "kAUParameterMIDIMapping_AnyNoteFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1anyNoteFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_AnyNoteFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1bipolar_On/title",
          "value": "kAUParameterMIDIMapping_Bipolar_On"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1bipolar_On/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_Bipolar_On"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1subRange/title",
          "value": "kAUParameterMIDIMapping_SubRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1subRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_SubRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags/title",
          "value": "AUParameterMIDIMappingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMappingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMappingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1anyChannelFlag/title",
          "value": "kAUParameterMIDIMapping_AnyChannelFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1anyChannelFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_AnyChannelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1bipolar/title",
          "value": "kAUParameterMIDIMapping_Bipolar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1bipolar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_Bipolar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1toggle/title",
          "value": "kAUParameterMIDIMapping_Toggle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags~1toggle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUParameterMIDIMapping_Toggle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auparametermidimappingflags/bipolar"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auparametermidimappingflags/bipolar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
