{
  "abstract": [
    {
      "text": "The caption button view can tilt in the horzontal direction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVCaptionButtonViewMotionDirection@TVCaptionButtonViewMotionDirectionHorizontal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "horizontal"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVCaptionButtonViewMotionDirectionHorizontal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "TVCaptionButtonViewMotionDirection.horizontal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "horizontal"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection": {
      "abstract": [
        {
          "text": "The directions that the caption button view can tilt in response to user interactions on the remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirection"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirection"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all": {
      "abstract": [
        {
          "text": "The caption button view can tilt in all directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionAll"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.all",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/all"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal": {
      "abstract": [
        {
          "text": "The caption button view can tilt in the horzontal direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionHorizontal"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.horizontal",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/horizontal"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none": {
      "abstract": [
        {
          "text": "The caption button view can’t tilt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionNone"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.none",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/none"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical": {
      "abstract": [
        {
          "text": "The caption button view can tilt in the vertical direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertical"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionVertical"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.vertical",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/vertical"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tilt-Directions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical"
      ],
      "title": "Tilt Directions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVCaptionButtonViewMotionDirectionHorizontal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Tilt-Directions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical"
              ],
              "title": "Tilt Directions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "TVCaptionButtonViewMotionDirectionHorizontal"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1all/title",
          "value": "TVCaptionButtonViewMotionDirectionAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1vertical/title",
          "value": "TVCaptionButtonViewMotionDirectionVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1vertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection/title",
          "value": "TVCaptionButtonViewMotionDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1horizontal/title",
          "value": "TVCaptionButtonViewMotionDirectionHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1none/title",
          "value": "TVCaptionButtonViewMotionDirectionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/horizontal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/horizontal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
