{
  "abstract": [
    {
      "text": "An enumeration that describes if a media asset contains or supports fragments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MediaExtension",
    "externalID": "c:@E@MEFileInfoFragmentsStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FragmentsStatus"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FragmentsStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MEFileInfo.FragmentsStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FragmentsStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For QuickTime movie and ISO files, it indicates the presence of an ",
              "type": "text"
            },
            {
              "code": "mvex",
              "type": "codeVoice"
            },
            {
              "text": " box, which is necessary to signal the possible presence of later ",
              "type": "text"
            },
            {
              "code": "moof",
              "type": "codeVoice"
            },
            {
              "text": " boxes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo": {
      "abstract": [
        {
          "text": "An object that contains file properties from the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFileInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfo"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that describes if a media asset contains or supports fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FragmentsStatus"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/equatable-implementations"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/rawrepresentable-implementations"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments": {
      "abstract": [
        {
          "text": "The file is extendable by fragments and contains at least one fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsFragments"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfoContainsFragments"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus.containsFragments",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/containsfragments"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments": {
      "abstract": [
        {
          "text": "The file is extendable by fragments, but doesn’t contain any fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couldContainButDoesNotContainFragments"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfoCouldContainButDoesNotContainFragments"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus.couldContainButDoesNotContainFragments",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/couldcontainbutdoesnotcontainfragments"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments": {
      "abstract": [
        {
          "text": "The file isn’t extendable by fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couldNotContainFragments"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfoCouldNotContainFragments"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus.couldNotContainFragments",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/couldnotcontainfragments"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/duration": {
      "abstract": [
        {
          "text": "The duration of the media asset, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/duration"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/fragmentsStatus-swift.property": {
      "abstract": [
        {
          "text": "Indicates if the media asset contains fragments or is extendable by fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentsStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEFileInfo",
          "text": "MEFileInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEFileInfoFragmentsStatus",
          "text": "FragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/fragmentsStatus-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fragmentsStatus"
        }
      ],
      "role": "symbol",
      "title": "fragmentsStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-file-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/duration",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/fragmentsStatus-swift.property"
      ],
      "title": "Inspecting file properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "File-fragment-status-values",
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments"
      ],
      "title": "File fragment status values"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/Equatable-Implementations",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEFileInfoFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "File-fragment-status-values",
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments"
              ],
              "title": "File fragment status values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-file-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/duration",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/fragmentsStatus-swift.property"
              ],
              "title": "Inspecting file properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEFileInfoFragmentsStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum/title",
          "value": "MEFileInfoFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldNotContainFragments/title",
          "value": "MEFileInfoCouldNotContainFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldNotContainFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoCouldNotContainFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1fragmentsStatus-swift.property/title",
          "value": "fragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1fragmentsStatus-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/title",
          "value": "MEFileInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1containsFragments/title",
          "value": "MEFileInfoContainsFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1containsFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoContainsFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldContainButDoesNotContainFragments/title",
          "value": "MEFileInfoCouldContainButDoesNotContainFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldContainButDoesNotContainFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoCouldContainButDoesNotContainFragments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
