{
  "abstract": [
    {
      "text": "The duration between touch down and touch down of the character keys of all the long words in the session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordTouchDownDown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:objc(cs)SRKeyboardMetrics(py)longWordTouchDownDown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "longWordTouchDownDown"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
        "text": "ProbabilityMetric"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSUnitDuration",
        "text": "UnitDuration"
      },
      {
        "kind": "text",
        "text": ">]"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "longWordTouchDownDown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "longWordTouchDownDown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "longWordTouchDownDown"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/ProbabilityMetric",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
              "text": "ProbabilityMetric"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUnitDuration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSUnitDuration",
              "text": "UnitDuration"
            },
            {
              "kind": "text",
              "text": ">] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics": {
      "abstract": [
        {
          "text": "The configuration of a device’s keyboard and its usage patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRKeyboardMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/ProbabilityMetric": {
      "abstract": [
        {
          "text": "A likelihood of occurrence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProbabilityMetric"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/ProbabilityMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProbabilityMetric"
        }
      ],
      "role": "symbol",
      "title": "SRKeyboardMetrics.ProbabilityMetric",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/probabilitymetric"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/anyTapToCharKey": {
      "abstract": [
        {
          "text": "The duration between touch up of any key and touch down on a sequential character key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyTapToCharKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/anyTapToCharKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anyTapToCharKey"
        }
      ],
      "role": "symbol",
      "title": "anyTapToCharKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/anytaptocharkey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToAnyTapKey": {
      "abstract": [
        {
          "text": "The duration between touch up on a character key and touch down on the next sequential key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charKeyToAnyTapKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToAnyTapKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "charKeyToAnyTapKey"
        }
      ],
      "role": "symbol",
      "title": "charKeyToAnyTapKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/charkeytoanytapkey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToPrediction": {
      "abstract": [
        {
          "text": "The duration between touch up on a character key and touch down on a word in the prediction bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charKeyToPrediction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToPrediction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "charKeyToPrediction"
        }
      ],
      "role": "symbol",
      "title": "charKeyToPrediction",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/charkeytoprediction"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToSpaceKey": {
      "abstract": [
        {
          "text": "The duration between touch up of a character key and touch down of a sequential Space bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charKeyToSpaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToSpaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "charKeyToSpaceKey"
        }
      ],
      "role": "symbol",
      "title": "charKeyToSpaceKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/charkeytospacekey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteToSpaceKey": {
      "abstract": [
        {
          "text": "The duration between touch up of the Delete key and touch down of a sequential Space bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteToSpaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteToSpaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteToSpaceKey"
        }
      ],
      "role": "symbol",
      "title": "deleteToSpaceKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/deletetospacekey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteTouchDownUp": {
      "abstract": [
        {
          "text": "The duration between touch down and touch up of all Delete key events for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteTouchDownUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteTouchDownUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteTouchDownUp"
        }
      ],
      "role": "symbol",
      "title": "deleteTouchDownUp",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/deletetouchdownup"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordTouchDownDown": {
      "abstract": [
        {
          "text": "The duration between touch down and touch down of the character keys of all the long words in the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longWordTouchDownDown"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordTouchDownDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "longWordTouchDownDown"
        }
      ],
      "role": "symbol",
      "title": "longWordTouchDownDown",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/longwordtouchdowndown"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyToCharKey": {
      "abstract": [
        {
          "text": "The duration between touch up on a character key and touch down on any sequential character key in a short word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortWordCharKeyToCharKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyToCharKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shortWordCharKeyToCharKey"
        }
      ],
      "role": "symbol",
      "title": "shortWordCharKeyToCharKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/shortwordcharkeytocharkey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyTouchDownUp": {
      "abstract": [
        {
          "text": "The duration between touch down and touch up of all character keys in short words for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortWordCharKeyTouchDownUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyTouchDownUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shortWordCharKeyTouchDownUp"
        }
      ],
      "role": "symbol",
      "title": "shortWordCharKeyTouchDownUp",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/shortwordcharkeytouchdownup"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToCharKey": {
      "abstract": [
        {
          "text": "The duration between touch up of the Space bar and touch down of a sequential character key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceToCharKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToCharKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spaceToCharKey"
        }
      ],
      "role": "symbol",
      "title": "spaceToCharKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/spacetocharkey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToDeleteKey": {
      "abstract": [
        {
          "text": "The duration between touch up of the Space bar and touch down of a sequential Delete key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceToDeleteKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToDeleteKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spaceToDeleteKey"
        }
      ],
      "role": "symbol",
      "title": "spaceToDeleteKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/spacetodeletekey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceTouchDownUp": {
      "abstract": [
        {
          "text": "The duration between touch down and touch up of all Space bar events for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceTouchDownUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceTouchDownUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spaceTouchDownUp"
        }
      ],
      "role": "symbol",
      "title": "spaceTouchDownUp",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/spacetouchdownup"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownDown": {
      "abstract": [
        {
          "text": "The duration between touch down and touch down for any key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDownDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchDownDown"
        }
      ],
      "role": "symbol",
      "title": "touchDownDown",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/touchdowndown"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownUp": {
      "abstract": [
        {
          "text": "The duration between touch down to touch up for any key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDownUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchDownUp"
        }
      ],
      "role": "symbol",
      "title": "touchDownUp",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/touchdownup"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchUpDown": {
      "abstract": [
        {
          "text": "The duration between touch up and touch down for any key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchUpDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchUpDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchUpDown"
        }
      ],
      "role": "symbol",
      "title": "touchUpDown",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/touchupdown"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSUnitDuration": {
      "abstract": [
        {
          "text": "A unit of measure for a duration of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "UnitDuration"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUnitDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnitDuration",
      "type": "topic",
      "url": "/documentation/foundation/unitduration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Timing-Key-Use",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/ProbabilityMetric",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownUp",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchUpDown",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceTouchDownUp",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteTouchDownUp",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyTouchDownUp",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownDown",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToPrediction",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyToCharKey",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToAnyTapKey",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/anyTapToCharKey",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToCharKey",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToSpaceKey",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToDeleteKey",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteToSpaceKey"
      ],
      "title": "Timing Key Use"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "longWordTouchDownDown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longWordTouchDownDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Timing-Key-Use",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/ProbabilityMetric",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownUp",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchUpDown",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceTouchDownUp",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteTouchDownUp",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyTouchDownUp",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/touchDownDown",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToPrediction",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyToCharKey",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToAnyTapKey",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/anyTapToCharKey",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToCharKey",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/charKeyToSpaceKey",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceToDeleteKey",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteToSpaceKey"
              ],
              "title": "Timing Key Use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<SRKeyboardProbabilityMetric<NSUnitDuration *> *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "longWordTouchDownDown"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1charKeyToAnyTapKey/title",
          "value": "charKeyToAnyTapKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1charKeyToAnyTapKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "charKeyToAnyTapKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyToCharKey/title",
          "value": "shortWordCharKeyToCharKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyToCharKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shortWordCharKeyToCharKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1charKeyToSpaceKey/title",
          "value": "charKeyToSpaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1charKeyToSpaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "charKeyToSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1ProbabilityMetric/title",
          "value": "SRKeyboardProbabilityMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1ProbabilityMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardProbabilityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1ProbabilityMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardProbabilityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteToSpaceKey/title",
          "value": "deleteToSpaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteToSpaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteToSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1charKeyToPrediction/title",
          "value": "charKeyToPrediction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1charKeyToPrediction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "charKeyToPrediction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1touchDownDown/title",
          "value": "touchDownDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1touchDownDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "touchDownDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceToCharKey/title",
          "value": "spaceToCharKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceToCharKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spaceToCharKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1touchUpDown/title",
          "value": "touchUpDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1touchUpDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "touchUpDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1touchDownUp/title",
          "value": "touchDownUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1touchDownUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "touchDownUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceTouchDownUp/title",
          "value": "spaceTouchDownUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceTouchDownUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spaceTouchDownUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyTouchDownUp/title",
          "value": "shortWordCharKeyTouchDownUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyTouchDownUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shortWordCharKeyTouchDownUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/title",
          "value": "SRKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1longWordTouchDownDown/title",
          "value": "longWordTouchDownDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1longWordTouchDownDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longWordTouchDownDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceToDeleteKey/title",
          "value": "spaceToDeleteKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceToDeleteKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spaceToDeleteKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteTouchDownUp/title",
          "value": "deleteTouchDownUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteTouchDownUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteTouchDownUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSUnitDuration/title",
          "value": "NSUnitDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1anyTapToCharKey/title",
          "value": "anyTapToCharKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1anyTapToCharKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anyTapToCharKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srkeyboardmetrics/longwordtouchdowndown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srkeyboardmetrics/longwordtouchdowndown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
