{
  "abstract": [
    {
      "text": "Sample values of the ratio of error distance between the intended and actual path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/pathErrorDistanceRatio"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:objc(cs)SRKeyboardMetrics(py)pathErrorDistanceRatio",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pathErrorDistanceRatio"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pathErrorDistanceRatio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "pathErrorDistanceRatio"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pathErrorDistanceRatio"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics": {
      "abstract": [
        {
          "text": "The configuration of a device’s keyboard and its usage patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRKeyboardMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteDownErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch down to the center of the Delete key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteDownErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteDownErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteDownErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "deleteDownErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/deletedownerrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteUpErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch up to the center of the Delete key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteUpErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteUpErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteUpErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "deleteUpErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/deleteuperrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/downErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch down to the center of any key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/downErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "downErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/downerrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordDownErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch down to the center of the intended key of the characters of a long word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longWordDownErrorDistance"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordDownErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "longWordDownErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "longWordDownErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/longworddownerrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordUpErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch up to the center of the intended key of the characters of a long word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longWordUpErrorDistance"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordUpErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "longWordUpErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "longWordUpErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/longworduperrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/pathErrorDistanceRatio": {
      "abstract": [
        {
          "text": "Sample values of the ratio of error distance between the intended and actual path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathErrorDistanceRatio"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/pathErrorDistanceRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pathErrorDistanceRatio"
        }
      ],
      "role": "symbol",
      "title": "pathErrorDistanceRatio",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/patherrordistanceratio"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyDownErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch down to the center of the intended key of a character in a short word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortWordCharKeyDownErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyDownErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shortWordCharKeyDownErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "shortWordCharKeyDownErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/shortwordcharkeydownerrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyUpErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch up to the center of the intended key of a character in a short word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortWordCharKeyUpErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyUpErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shortWordCharKeyUpErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "shortWordCharKeyUpErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/shortwordcharkeyuperrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceDownErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch down to the right centroid of the Space bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceDownErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceDownErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spaceDownErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "spaceDownErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/spacedownerrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceUpErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch up to the right centroid of the Space bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spaceUpErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceUpErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spaceUpErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "spaceUpErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/spaceuperrordistance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/upErrorDistance": {
      "abstract": [
        {
          "text": "The distance from the touch up to the center of any key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upErrorDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRKeyboardProbabilityMetric",
          "text": "ProbabilityMetric"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/upErrorDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "upErrorDistance"
        }
      ],
      "role": "symbol",
      "title": "upErrorDistance",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/uperrordistance"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measuring-Key-Use",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordUpErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordDownErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/upErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/downErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceUpErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceDownErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteUpErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteDownErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyUpErrorDistance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyDownErrorDistance"
      ],
      "title": "Measuring Key Use"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pathErrorDistanceRatio"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pathErrorDistanceRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measuring-Key-Use",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordUpErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/longWordDownErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/upErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/downErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceUpErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/spaceDownErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteUpErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/deleteDownErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyUpErrorDistance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/shortWordCharKeyDownErrorDistance"
              ],
              "title": "Measuring Key Use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "pathErrorDistanceRatio"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceDownErrorDistance/title",
          "value": "spaceDownErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceDownErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spaceDownErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/title",
          "value": "SRKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteDownErrorDistance/title",
          "value": "deleteDownErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteDownErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteDownErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1longWordDownErrorDistance/title",
          "value": "longWordDownErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1longWordDownErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longWordDownErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1longWordUpErrorDistance/title",
          "value": "longWordUpErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1longWordUpErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longWordUpErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyDownErrorDistance/title",
          "value": "shortWordCharKeyDownErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyDownErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shortWordCharKeyDownErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1pathErrorDistanceRatio/title",
          "value": "pathErrorDistanceRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1pathErrorDistanceRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pathErrorDistanceRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyUpErrorDistance/title",
          "value": "shortWordCharKeyUpErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1shortWordCharKeyUpErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shortWordCharKeyUpErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1downErrorDistance/title",
          "value": "downErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1downErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteUpErrorDistance/title",
          "value": "deleteUpErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1deleteUpErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteUpErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceUpErrorDistance/title",
          "value": "spaceUpErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1spaceUpErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spaceUpErrorDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1upErrorDistance/title",
          "value": "upErrorDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1upErrorDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "upErrorDistance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srkeyboardmetrics/patherrordistanceratio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srkeyboardmetrics/patherrordistanceratio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
