{
  "abstract": [
    {
      "text": "The total number of space corrections for the keyboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSpaceCorrections"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:objc(cs)SRKeyboardMetrics(py)totalSpaceCorrections",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "totalSpaceCorrections"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "totalSpaceCorrections"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "totalSpaceCorrections"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "totalSpaceCorrections"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics": {
      "abstract": [
        {
          "text": "The configuration of a device’s keyboard and its usage patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRKeyboardMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAlteredWords": {
      "abstract": [
        {
          "text": "The total number of altered words for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalAlteredWords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAlteredWords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalAlteredWords"
        }
      ],
      "role": "symbol",
      "title": "totalAlteredWords",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalalteredwords"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAutoCorrections": {
      "abstract": [
        {
          "text": "The total number of autocorrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalAutoCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAutoCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalAutoCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalAutoCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalautocorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDeletes": {
      "abstract": [
        {
          "text": "The total number of deletions for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalDeletes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDeletes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalDeletes"
        }
      ],
      "role": "symbol",
      "title": "totalDeletes",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totaldeletes"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDrags": {
      "abstract": [
        {
          "text": "The total number of drags for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalDrags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDrags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalDrags"
        }
      ],
      "role": "symbol",
      "title": "totalDrags",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totaldrags"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalEmojis": {
      "abstract": [
        {
          "text": "The total number of emojis for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalEmojis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalEmojis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalEmojis"
        }
      ],
      "role": "symbol",
      "title": "totalEmojis",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalemojis"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalInsertKeyCorrections": {
      "abstract": [
        {
          "text": "The total number of Insert key corrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalInsertKeyCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalInsertKeyCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalInsertKeyCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalInsertKeyCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalinsertkeycorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalNearKeyCorrections": {
      "abstract": [
        {
          "text": "The total number of near key corrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalNearKeyCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalNearKeyCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalNearKeyCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalNearKeyCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalnearkeycorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathLength": {
      "abstract": [
        {
          "text": "The total length of completed paths for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalPathLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalPathLength"
        }
      ],
      "role": "symbol",
      "title": "totalPathLength",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalpathlength"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathTime": {
      "abstract": [
        {
          "text": "The total time to complete paths for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalPathTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalPathTime"
        }
      ],
      "role": "symbol",
      "title": "totalPathTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalpathtime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPaths": {
      "abstract": [
        {
          "text": "The total number of completed paths for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalPaths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPaths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalPaths"
        }
      ],
      "role": "symbol",
      "title": "totalPaths",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalpaths"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalRetroCorrections": {
      "abstract": [
        {
          "text": "The total number of retro corrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalRetroCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalRetroCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalRetroCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalRetroCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalretrocorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSkipTouchCorrections": {
      "abstract": [
        {
          "text": "The total number of skip touch corrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalSkipTouchCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSkipTouchCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalSkipTouchCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalSkipTouchCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalskiptouchcorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSpaceCorrections": {
      "abstract": [
        {
          "text": "The total number of space corrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalSpaceCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSpaceCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalSpaceCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalSpaceCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalspacecorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTaps": {
      "abstract": [
        {
          "text": "The total number of taps for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalTaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTaps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalTaps"
        }
      ],
      "role": "symbol",
      "title": "totalTaps",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totaltaps"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTranspositionCorrections": {
      "abstract": [
        {
          "text": "The total number of transposition corrections for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalTranspositionCorrections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTranspositionCorrections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalTranspositionCorrections"
        }
      ],
      "role": "symbol",
      "title": "totalTranspositionCorrections",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totaltranspositioncorrections"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalWords": {
      "abstract": [
        {
          "text": "The total number of typed words for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalWords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalWords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalWords"
        }
      ],
      "role": "symbol",
      "title": "totalWords",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics/totalwords"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Quantifying-Key-Use",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalWords",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAlteredWords",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTaps",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDrags",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDeletes",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalEmojis",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPaths",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathTime",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathLength",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAutoCorrections",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalRetroCorrections",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTranspositionCorrections",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalInsertKeyCorrections",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSkipTouchCorrections",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalNearKeyCorrections"
      ],
      "title": "Quantifying Key Use"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "totalSpaceCorrections"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalSpaceCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Quantifying-Key-Use",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalWords",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAlteredWords",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTaps",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDrags",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalDeletes",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalEmojis",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPaths",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathTime",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalPathLength",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalAutoCorrections",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalRetroCorrections",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalTranspositionCorrections",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalInsertKeyCorrections",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalSkipTouchCorrections",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics/totalNearKeyCorrections"
              ],
              "title": "Quantifying Key Use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "totalSpaceCorrections"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalPaths/title",
          "value": "totalPaths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalPaths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalPaths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalPathLength/title",
          "value": "totalPathLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalPathLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalPathLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalRetroCorrections/title",
          "value": "totalRetroCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalRetroCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalRetroCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalSpaceCorrections/title",
          "value": "totalSpaceCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalSpaceCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalSpaceCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalAlteredWords/title",
          "value": "totalAlteredWords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalAlteredWords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalAlteredWords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalTaps/title",
          "value": "totalTaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalTaps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalTaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/title",
          "value": "SRKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalTranspositionCorrections/title",
          "value": "totalTranspositionCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalTranspositionCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalTranspositionCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalWords/title",
          "value": "totalWords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalWords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalWords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalAutoCorrections/title",
          "value": "totalAutoCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalAutoCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalAutoCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalPathTime/title",
          "value": "totalPathTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalPathTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalPathTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalNearKeyCorrections/title",
          "value": "totalNearKeyCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalNearKeyCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalNearKeyCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalEmojis/title",
          "value": "totalEmojis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalEmojis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalEmojis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalSkipTouchCorrections/title",
          "value": "totalSkipTouchCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalSkipTouchCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalSkipTouchCorrections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalDeletes/title",
          "value": "totalDeletes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalDeletes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalDeletes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalDrags/title",
          "value": "totalDrags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalDrags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalDrags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalInsertKeyCorrections/title",
          "value": "totalInsertKeyCorrections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics~1totalInsertKeyCorrections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalInsertKeyCorrections"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srkeyboardmetrics/totalspacecorrections"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srkeyboardmetrics/totalspacecorrections"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
