{
  "abstract": [
    {
      "text": "Returns the global system queue with the specified quality-of-service class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/global(qos:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Dispatch",
    "externalID": "s:So17OS_dispatch_queueC8DispatchE6global3qosAbC0D3QoSV0G6SClassO_tFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "global"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "qos"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8Dispatch0A3QoSV",
        "text": "DispatchQoS"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8Dispatch0A3QoSV0B6SClassO",
        "text": "QoSClass"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
        "text": "DispatchQueue"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "global(qos:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "global"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "qos"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8Dispatch0A3QoSV",
              "text": "DispatchQoS"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8Dispatch0A3QoSV0B6SClassO",
              "text": "QoSClass"
            },
            {
              "kind": "text",
              "text": " = .default) -> "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
              "text": "DispatchQueue"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The quality-of-service level to associate with the queue. This value determines the priority at which the system schedules tasks for execution. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "qos"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method returns a queue suitable for executing tasks with the specified quality-of-service level. Calls to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/suspend()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/resume()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_context",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions have no effect on the returned queues.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Tasks submitted to the returned queue are scheduled concurrently with respect to one another.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchConcurrentQueue": {
      "abstract": [
        {
          "text": "A custom dispatch queue that schedules tasks for concurrent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchConcurrentQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchConcurrentQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchConcurrentQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchConcurrentQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchconcurrentqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/resume()": {
      "abstract": [
        {
          "text": "Resumes the invocation of block objects on a dispatch object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resume"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/resume()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_resume"
        }
      ],
      "role": "symbol",
      "title": "resume()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchobject/resume()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/suspend()": {
      "abstract": [
        {
          "text": "Suspends the invocation of block objects on a dispatch object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspend"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/suspend()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_suspend"
        }
      ],
      "role": "symbol",
      "title": "suspend()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchobject/suspend()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS": {
      "abstract": [
        {
          "text": "The quality of service, or the execution priority, to apply to tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchQoS"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchQoS"
        }
      ],
      "role": "symbol",
      "title": "DispatchQoS",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqos"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum": {
      "abstract": [
        {
          "text": "Quality-of-service classes that specify the priorities for executing tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QoSClass"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QoSClass"
        }
      ],
      "role": "symbol",
      "title": "DispatchQoS.QoSClass",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqos/qosclass-swift.enum"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/Attributes": {
      "abstract": [
        {
          "text": "Attributes that define the behavior of a dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/Attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue.Attributes",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/attributes"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/AutoreleaseFrequency": {
      "abstract": [
        {
          "text": "Constants indicating the frequency with which a dispatch queue autoreleases objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoreleaseFrequency"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/AutoreleaseFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoreleaseFrequency"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue.AutoreleaseFrequency",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/autoreleasefrequency"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/global(qos:)": {
      "abstract": [
        {
          "text": "Returns the global system queue with the specified quality-of-service class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "global"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV0B6SClassO",
          "text": "QoSClass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/global(qos:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "global(qos:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/global(qos:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/init(label:qos:attributes:autoreleaseFrequency:target:)": {
      "abstract": [
        {
          "text": "Creates a new dispatch queue to which you can submit blocks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17OS_dispatch_queueC8DispatchE10AttributesV",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "autoreleaseFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17OS_dispatch_queueC8DispatchE20AutoreleaseFrequencyO",
          "text": "AutoreleaseFrequency"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/init(label:qos:attributes:autoreleaseFrequency:target:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(label:qos:attributes:autoreleaseFrequency:target:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/init(label:qos:attributes:autoreleasefrequency:target:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/main": {
      "abstract": [
        {
          "text": "The dispatch queue associated with the main thread of the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/main",
      "kind": "symbol",
      "role": "symbol",
      "title": "main",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/main"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue": {
      "abstract": [
        {
          "text": "A custom dispatch queue that schedules tasks for serial execution on an arbitrary thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSerialQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSerialQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchSerialQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchserialqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_global-swift.class": {
      "abstract": [
        {
          "text": "A system-provided dispatch queue that schedules tasks for concurrent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_global"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_global-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_global"
        }
      ],
      "role": "symbol",
      "title": "OS_dispatch_queue_global",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_queue_global-swift.class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_main-swift.class": {
      "abstract": [
        {
          "text": "A system-provided dispatch queue that schedules tasks for serial execution on the app’s main thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_main"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_main-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_main"
        }
      ],
      "role": "symbol",
      "title": "OS_dispatch_queue_main",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_queue_main-swift.class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t": {
      "abstract": [
        {
          "text": "A dispatch queue that executes tasks concurrently and in any order, respecting any barriers that may be in place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_concurrent_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_concurrent_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_concurrent_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_concurrent_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t": {
      "abstract": [
        {
          "text": "A dispatch queue that executes tasks concurrently using threads from the global thread pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_global_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_global_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_global_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_global_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t": {
      "abstract": [
        {
          "text": "A dispatch queue that is bound to the app’s main thread and executes tasks serially on that thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_main_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_main_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_main_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_main_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_serial_t": {
      "abstract": [
        {
          "text": "A dispatch queue that executes tasks serially in first-in, first-out (FIFO) order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_serial_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_serial_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_serial_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_serial_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_serial_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_context": {
      "abstract": [
        {
          "text": "Associates an application-defined context with the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_set_context"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_context",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_set_context",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_set_context"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Dispatch-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/main",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/init(label:qos:attributes:autoreleaseFrequency:target:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/Attributes",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/AutoreleaseFrequency",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_main-swift.class",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_global-swift.class",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchConcurrentQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_serial_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t"
      ],
      "title": "Creating a Dispatch Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1suspend()/title",
          "value": "dispatch_suspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1suspend()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_suspend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1resume()/title",
          "value": "dispatch_resume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1resume()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_resume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_concurrent_t/title",
          "value": "dispatch_queue_concurrent_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_concurrent_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_concurrent_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_concurrent_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_concurrent_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_main_t/title",
          "value": "dispatch_queue_main_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_main_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_main_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_main_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_main_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_global_t/title",
          "value": "dispatch_queue_global_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_global_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_global_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_global_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_global_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_serial_t/title",
          "value": "dispatch_queue_serial_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_serial_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_serial_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchqueue/global(qos:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
