{
  "abstract": [
    {
      "text": "A Boolean value indicating whether an app built with Mac Catalyst supports automatic tabbing mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsTabbedSceneCollection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIApplicationSceneManifest.UIApplicationSupportsTabbedSceneCollection",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIApplicationSupportsTabbedSceneCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIApplicationSupportsTabbedSceneCollection"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Supports Tabbed Scene Collection",
        "name": "UIApplicationSupportsTabbedSceneCollection",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "YES"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the tabbing mode for an app built with Mac Catalyst that support multiple scenes is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWindow/TabbingMode-swift.enum/automatic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Starting with macOS 12, you can disable this behavior by adding the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsTabbedSceneCollection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key with a value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest": {
      "abstract": [
        {
          "text": "The information about the app’s scene-based life-cycle support.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Scene Manifest",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
      "kind": "symbol",
      "name": "UIApplicationSceneManifest",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSceneManifest"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSceneManifest",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app supports two or more scenes simultaneously.",
          "type": "text"
        }
      ],
      "ideTitle": "Enable Multiple Windows",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes",
      "kind": "symbol",
      "name": "UIApplicationSupportsMultipleScenes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSupportsMultipleScenes"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSupportsMultipleScenes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uiapplicationsupportsmultiplescenes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsTabbedSceneCollection": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether an app built with Mac Catalyst supports automatic tabbing mode.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Tabbed Scene Collection",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsTabbedSceneCollection",
      "kind": "symbol",
      "name": "UIApplicationSupportsTabbedSceneCollection",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSupportsTabbedSceneCollection"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSupportsTabbedSceneCollection",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uiapplicationsupportstabbedscenecollection"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSWindow/TabbingMode-swift.enum/automatic": {
      "abstract": [
        {
          "text": "A window that automatically tabs together based on the user’s tabbing preference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWindow/TabbingMode-swift.enum/automatic",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindow.TabbingMode.automatic",
      "type": "topic",
      "url": "/documentation/AppKit/NSWindow/TabbingMode-swift.enum/automatic"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiple-windows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes"
      ],
      "title": "Multiple windows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIApplicationSupportsTabbedSceneCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSupportsTabbedSceneCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Multiple-windows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes"
              ],
              "title": "Multiple windows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum~1automatic/title",
          "value": "NSWindowTabbingModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabbingModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/title",
          "value": "UIApplicationSceneManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSceneManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UIApplicationSupportsTabbedSceneCollection/title",
          "value": "UIApplicationSupportsTabbedSceneCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UIApplicationSupportsTabbedSceneCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSupportsTabbedSceneCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UIApplicationSupportsMultipleScenes/title",
          "value": "UIApplicationSupportsMultipleScenes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UIApplicationSupportsMultipleScenes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSupportsMultipleScenes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uiapplicationsupportstabbedscenecollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uiapplicationsupportstabbedscenecollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
