{
  "abstract": [
    {
      "text": "The default configuration details the system uses to create new scenes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIApplicationSceneManifest.UISceneConfigurations",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISceneConfigurations"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "UISceneConfigurations"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Scene Configuration",
        "name": "UISceneConfigurations",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The keys in the dictionary correspond to the roles played by your scenes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " supports the following keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleApplication",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplayNonInteractive",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For visionOS apps, it also supports:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For applications with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CarPlay",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " capabilities, it also supports these additional keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationSceneSessionRoleApplication",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationDashboardSceneSessionRoleApplication",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you don’t include this key in your ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file, you must implement the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method in your app delegate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest": {
      "abstract": [
        {
          "text": "The information about the app’s scene-based life-cycle support.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Scene Manifest",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
      "kind": "symbol",
      "name": "UIApplicationSceneManifest",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSceneManifest"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSceneManifest",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations": {
      "abstract": [
        {
          "text": "The default configuration details the system uses to create new scenes.",
          "type": "text"
        }
      ],
      "ideTitle": "Scene Configuration",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations",
      "kind": "symbol",
      "name": "UISceneConfigurations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneConfigurations"
        }
      ],
      "role": "symbol",
      "title": "UISceneConfigurations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display Compositor Services content in an immersive space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication",
      "kind": "symbol",
      "name": "CPSceneSessionRoleImmersiveSpaceApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSceneSessionRoleImmersiveSpaceApplication"
        }
      ],
      "role": "symbol",
      "title": "CPSceneSessionRoleImmersiveSpaceApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cpscenesessionroleimmersivespaceapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationDashboardSceneSessionRoleApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes that you use to display navigation content on a CarPlay Dashboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationDashboardSceneSessionRoleApplication",
      "kind": "symbol",
      "name": "CPTemplateApplicationDashboardSceneSessionRoleApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationDashboardSceneSessionRoleApplication"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationDashboardSceneSessionRoleApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationdashboardscenesessionroleapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display navigation content on a CarPlay Instrument Cluster.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
      "kind": "symbol",
      "name": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationinstrumentclusterscenesessionroleapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationSceneSessionRoleApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes that you use to display template content on a CarPlay-enabled vehicle screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationSceneSessionRoleApplication",
      "kind": "symbol",
      "name": "CPTemplateApplicationSceneSessionRoleApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationSceneSessionRoleApplication"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationSceneSessionRoleApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationscenesessionroleapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display SwiftUI content in an immersive space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
      "kind": "symbol",
      "name": "UISceneSessionRoleImmersiveSpaceApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneSessionRoleImmersiveSpaceApplication"
        }
      ],
      "role": "symbol",
      "title": "UISceneSessionRoleImmersiveSpaceApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/uiscenesessionroleimmersivespaceapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display content on the device’s main screen and respond to user interactions.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Session Role",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleApplication",
      "kind": "symbol",
      "name": "UIWindowSceneSessionRoleApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneSessionRoleApplication"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneSessionRoleApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/uiwindowscenesessionroleapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplay": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display noninteractive content on an externally connected display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "External Display Session Role (Legacy)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplay",
      "kind": "symbol",
      "name": "UIWindowSceneSessionRoleExternalDisplay",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneSessionRoleExternalDisplay"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneSessionRoleExternalDisplay",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/uiwindowscenesessionroleexternaldisplay"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplayNonInteractive": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display noninteractive content on an externally connected display.",
          "type": "text"
        }
      ],
      "ideTitle": "External Display Session Role Non-Interactive",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplayNonInteractive",
      "kind": "symbol",
      "name": "UIWindowSceneSessionRoleExternalDisplayNonInteractive",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneSessionRoleExternalDisplayNonInteractive"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneSessionRoleExternalDisplayNonInteractive",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/uiwindowscenesessionroleexternaldisplaynoninteractive"
    },
    "doc://com.apple.documentation/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/CarPlay"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)": {
      "abstract": [
        {
          "text": "Retrieves the configuration data for UIKit to use when creating a new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configurationForConnecting"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connectingSceneSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneConnectionOptions",
          "text": "ConnectionOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneConfiguration",
          "text": "UISceneConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:configurationForConnecting:options:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Window-scene-roles",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplayNonInteractive",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplay"
      ],
      "title": "Window scene roles"
    },
    {
      "anchor": "Immersize-space-scene-roles",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication"
      ],
      "title": "Immersize space scene roles"
    },
    {
      "anchor": "CarPlay-scene-roles",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationSceneSessionRoleApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationDashboardSceneSessionRoleApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
      ],
      "title": "CarPlay scene roles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISceneConfigurations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneConfigurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Window-scene-roles",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplayNonInteractive",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UIWindowSceneSessionRoleExternalDisplay"
              ],
              "title": "Window scene roles"
            },
            {
              "anchor": "Immersize-space-scene-roles",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication"
              ],
              "title": "Immersize space scene roles"
            },
            {
              "anchor": "CarPlay-scene-roles",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationSceneSessionRoleApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationDashboardSceneSessionRoleApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
              ],
              "title": "CarPlay scene roles"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UIWindowSceneSessionRoleExternalDisplayNonInteractive/title",
          "value": "UIWindowSceneSessionRoleExternalDisplayNonInteractive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UIWindowSceneSessionRoleExternalDisplayNonInteractive/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneSessionRoleExternalDisplayNonInteractive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations/title",
          "value": "UISceneConfigurations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneConfigurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/title",
          "value": "UIApplicationSceneManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSceneManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:configurationForConnecting:options:)/title",
          "value": "application:configurationForConnectingSceneSession:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:configurationForConnecting:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneConfiguration",
              "text": "UISceneConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationForConnectingSceneSession:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneSession",
              "text": "UISceneSession"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "connectingSceneSession"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneConnectionOptions",
              "text": "UISceneConnectionOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/title",
          "value": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UISceneSessionRoleImmersiveSpaceApplication/title",
          "value": "UISceneSessionRoleImmersiveSpaceApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UISceneSessionRoleImmersiveSpaceApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneSessionRoleImmersiveSpaceApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPSceneSessionRoleImmersiveSpaceApplication/title",
          "value": "CPSceneSessionRoleImmersiveSpaceApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPSceneSessionRoleImmersiveSpaceApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSceneSessionRoleImmersiveSpaceApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UIWindowSceneSessionRoleExternalDisplay/title",
          "value": "UIWindowSceneSessionRoleExternalDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UIWindowSceneSessionRoleExternalDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneSessionRoleExternalDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationDashboardSceneSessionRoleApplication/title",
          "value": "CPTemplateApplicationDashboardSceneSessionRoleApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationDashboardSceneSessionRoleApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationDashboardSceneSessionRoleApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UIWindowSceneSessionRoleApplication/title",
          "value": "UIWindowSceneSessionRoleApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UIWindowSceneSessionRoleApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneSessionRoleApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationSceneSessionRoleApplication/title",
          "value": "CPTemplateApplicationSceneSessionRoleApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationSceneSessionRoleApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneSessionRoleApplication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
