{"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions"],"generated":true,"anchor":"Reading-From-the-Pasteboard","title":"Reading From the Pasteboard"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nspasteboardreading/readingoptions(fortype:pasteboard:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nspasteboardreading/readingoptions(fortype:pasteboard:)"]}],"metadata":{"role":"symbol","externalID":"c:objc(pl)NSPasteboardReading(cm)readingOptionsForType:pasteboard:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readingOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pasteboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPasteboardReadingOptions","text":"ReadingOptions"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.6","name":"macOS"}],"title":"readingOptions(forType:pasteboard:)","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"readingOptionsForType:pasteboard:"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading"]]},"abstract":[{"type":"text","text":"Returns options for reading data of a specified type from a given pasteboard."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readingOptions(forType:pasteboard:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readingOptions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pasteboard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ReadingOptions","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions","preciseIdentifier":"c:@E@NSPasteboardReadingOptions","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A UTI supported by instances of the receiver for reading (one of the types returned by ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)","type":"reference","isActive":true},{"text":").","type":"text"}],"type":"paragraph"}],"name":"type"},{"content":[{"inlineContent":[{"text":"A pasteboard.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can use the pasteboard argument to provide return different based on the pasteboard name, should you need to do so."}],"type":"paragraph"}],"name":"pasteboard"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"Options for reading data of ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"pasteboard","type":"codeVoice"},{"text":". For a list of valid values, see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions"},{"text":".","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not perform other pasteboard operations in this method implementation."}]}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions":{"abstract":[{"text":"Options that specify how to interpret data on the pasteboard when initializing pasteboard data.","type":"text"}],"type":"topic","title":"NSPasteboard.ReadingOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReadingOptions","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions","role":"symbol","url":"/documentation/appkit/nspasteboard/readingoptions","navigatorTitle":[{"text":"ReadingOptions","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)":{"title":"readableTypes(for:)","role":"symbol","navigatorTitle":[{"text":"readableTypesForPasteboard:","kind":"identifier"}],"required":true,"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readableTypes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","abstract":[{"text":"Returns an array of uniform type identifier strings of data types the receiver can read from the pasteboard and initialize from.","type":"text"}],"url":"/documentation/appkit/nspasteboardreading/readabletypes(for:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard":{"url":"/documentation/appkit/nspasteboard","title":"NSPasteboard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSPasteboard"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSPasteboard","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","abstract":[{"text":"An object that transfers data to and from the pasteboard server.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readingOptions(forType:pasteboard:)":{"title":"readingOptions(forType:pasteboard:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"readingOptionsForType:pasteboard:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readingOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pasteboard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPasteboardReadingOptions","kind":"typeIdentifier","text":"ReadingOptions"}],"kind":"symbol","abstract":[{"text":"Returns options for reading data of a specified type from a given pasteboard.","type":"text"}],"url":"/documentation/appkit/nspasteboardreading/readingoptions(fortype:pasteboard:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readingOptions(forType:pasteboard:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSPasteboardReading"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading","type":"topic","kind":"symbol","title":"NSPasteboardReading","url":"/documentation/appkit/nspasteboardreading","navigatorTitle":[{"text":"NSPasteboardReading","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that defines the interface for initializing an object from a pasteboard."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType":{"abstract":[{"text":"The supported pasteboard types.","type":"text"}],"navigatorTitle":[{"text":"PasteboardType","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","url":"/documentation/appkit/nspasteboard/pasteboardtype","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PasteboardType","kind":"identifier"}],"role":"symbol","title":"NSPasteboard.PasteboardType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Method"},{"op":"replace","path":"/metadata/title","value":"readingOptionsForType:pasteboard:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"readingOptionsForType:pasteboard:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Reading-From-the-Pasteboard","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions"],"title":"Reading From the Pasteboard"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions","text":"NSPasteboardReadingOptions","preciseIdentifier":"c:@E@NSPasteboardReadingOptions","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"readingOptionsForType:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","text":"NSPasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pasteboard:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pasteboard","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"A UTI supported by instances of the receiver for reading (one of the types returned by "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)"},{"type":"text","text":")."}],"type":"paragraph"}]},{"name":"pasteboard","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pasteboard."}]},{"type":"paragraph","inlineContent":[{"text":"You can use the pasteboard argument to provide return different based on the pasteboard name, should you need to do so.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"Options for reading data of ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"pasteboard","type":"codeVoice"},{"text":". For a list of valid values, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions"},{"text":".","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptions/title","value":"NSPasteboardReadingOptions"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptions/fragments","value":[{"kind":"identifier","text":"NSPasteboardReadingOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptions/navigatorTitle","value":[{"text":"NSPasteboardReadingOptions","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading~1readableTypes(for:)/title","value":"readableTypesForPasteboard:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading~1readableTypes(for:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"readableTypesForPasteboard:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title","value":"NSPasteboard"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments","value":[{"text":"NSPasteboard","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle","value":[{"kind":"identifier","text":"NSPasteboard"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading~1readingOptions(forType:pasteboard:)/title","value":"readingOptionsForType:pasteboard:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading~1readingOptions(forType:pasteboard:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"readingOptionsForType:pasteboard:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading/title","value":"NSPasteboardReading"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading/fragments","value":[{"text":"NSPasteboardReading","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading/navigatorTitle","value":[{"kind":"identifier","text":"NSPasteboardReading"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/title","value":"NSPasteboardType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/fragments","value":[{"text":"NSPasteboardType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/navigatorTitle","value":[{"text":"NSPasteboardType","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}