{
  "abstract": [
    {
      "text": "The option to debug layers during graph compilation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/debugLayers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCGraphCompilationOptions@MLCGraphCompilationOptionsDebugLayers",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "debugLayers"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MLCGraphCompilationOptions",
        "text": "MLCGraphCompilationOptions"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCGraphCompilationOptionsDebugLayers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "debugLayers"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "debugLayers"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MLCGraphCompilationOptions",
              "text": "MLCGraphCompilationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Include this option to disable various optimizations such as layer fusion, and ensure the framework synchronizes the resulting forward and gradients tensors host memory with device memory, for layers marked as debuggable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions": {
      "abstract": [
        {
          "text": "A bitmask that specifies the options you use when compiling a graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGraphCompilationOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGraphCompilationOptions"
        }
      ],
      "role": "symbol",
      "title": "MLCGraphCompilationOptions",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraphcompilationoptions"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/computeAllGradients": {
      "abstract": [
        {
          "text": "The option to compute all gradients during graph compilation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computeAllGradients"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGraphCompilationOptions",
          "text": "MLCGraphCompilationOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/computeAllGradients",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGraphCompilationOptionsComputeAllGradients"
        }
      ],
      "role": "symbol",
      "title": "computeAllGradients",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraphcompilationoptions/computeallgradients"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/debugLayers": {
      "abstract": [
        {
          "text": "The option to debug layers during graph compilation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugLayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGraphCompilationOptions",
          "text": "MLCGraphCompilationOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/debugLayers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGraphCompilationOptionsDebugLayers"
        }
      ],
      "role": "symbol",
      "title": "debugLayers",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraphcompilationoptions/debuglayers"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/disableLayerFusion": {
      "abstract": [
        {
          "text": "The option to disable layer fusion during graph compilation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableLayerFusion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGraphCompilationOptions",
          "text": "MLCGraphCompilationOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/disableLayerFusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGraphCompilationOptionsDisableLayerFusion"
        }
      ],
      "role": "symbol",
      "title": "disableLayerFusion",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraphcompilationoptions/disablelayerfusion"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a graph compilation option with the specified raw value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraphcompilationoptions/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/linkGraphs": {
      "abstract": [
        {
          "text": "The option to link graphs during graph compilation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkGraphs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGraphCompilationOptions",
          "text": "MLCGraphCompilationOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/linkGraphs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGraphCompilationOptionsLinkGraphs"
        }
      ],
      "role": "symbol",
      "title": "linkGraphs",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraphcompilationoptions/linkgraphs"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Graph-Compilation-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/init(rawValue:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/disableLayerFusion",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/linkGraphs",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/computeAllGradients"
      ],
      "title": "Creating Graph Compilation Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCGraphCompilationOptionsDebugLayers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptionsDebugLayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Graph-Compilation-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/disableLayerFusion",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/linkGraphs",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraphCompilationOptions/computeAllGradients"
              ],
              "title": "Creating Graph Compilation Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCGraphCompilationOptionsDebugLayers"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1linkGraphs/title",
          "value": "MLCGraphCompilationOptionsLinkGraphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1linkGraphs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptionsLinkGraphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1disableLayerFusion/title",
          "value": "MLCGraphCompilationOptionsDisableLayerFusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1disableLayerFusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptionsDisableLayerFusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1debugLayers/title",
          "value": "MLCGraphCompilationOptionsDebugLayers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1debugLayers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptionsDebugLayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1computeAllGradients/title",
          "value": "MLCGraphCompilationOptionsComputeAllGradients"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions~1computeAllGradients/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptionsComputeAllGradients"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions/title",
          "value": "MLCGraphCompilationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraphCompilationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraphCompilationOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcgraphcompilationoptions/debuglayers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcgraphcompilationoptions/debuglayers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
