{
  "abstract": [
    {
      "text": "Constants that specify display styles for picker bar items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSPickerTouchBarItemControlRepresentation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ControlRepresentation"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ControlRepresentation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSPickerTouchBarItem.ControlRepresentation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ControlRepresentation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButtonTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSButtonTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttontouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that, along with its delegate, provides a list of textual suggestions for the current text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCandidateListTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCandidateListTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSCandidateListTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a system-defined color picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorPickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorPickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSColorPickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that contains a responder of your choice, such as a view, a button, or a scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCustomTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCustomTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSCustomTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nscustomtouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a bar to contain other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGroupTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGroupTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSGroupTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsgrouptouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a picker control with multiple options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify display styles for picker bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The system dynamically changes the display mode based on the available space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemControlRepresentationAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed": {
      "abstract": [
        {
          "text": "The system displays the control’s options through a popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collapsed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation.collapsed",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/collapsed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded": {
      "abstract": [
        {
          "text": "The system displays the control and all of its options directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemControlRepresentationExpanded"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation.expanded",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/expanded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify selection modes for picker bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.SelectionMode",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a two-state control that can expand into its second state, showing the contents of a bar that it owns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopoverTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopoverTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSPopoverTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nspopovertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that, along with its delegate, provides a list of objects eligible for sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingServicePickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServicePickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSSharingServicePickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservicepickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a slider control for choosing a value in a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSliderTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSliderTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSSliderTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsslidertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a stepper control for incrementing or decrementing a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStepperTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStepperTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSStepperTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nssteppertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem": {
      "abstract": [
        {
          "text": "A UI control shown in the Touch Bar on supported models of MacBook Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions": {
      "abstract": [
        {
          "text": "An object that specifies how user interface elements resize themselves when space is constrained.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceCompressionOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Touch-Bar-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum"
      ],
      "title": "Touch Bar items"
    }
  ],
  "topicSections": [
    {
      "anchor": "Display-styles",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed"
      ],
      "title": "Display styles"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPickerTouchBarItemControlRepresentation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Display-styles",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed"
              ],
              "title": "Display styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Touch-Bar-items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum"
              ],
              "title": "Touch Bar items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPickerTouchBarItemControlRepresentation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverTouchBarItem/title",
          "value": "NSPopoverTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/title",
          "value": "NSGroupTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGroupTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGroupTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/title",
          "value": "NSPickerTouchBarItemSelectionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1collapsed/title",
          "value": "NSPickerTouchBarItemControlRepresentationCollapsed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1collapsed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepperTouchBarItem/title",
          "value": "NSStepperTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepperTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStepperTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepperTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStepperTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonTouchBarItem/title",
          "value": "NSButtonTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1automatic/title",
          "value": "NSPickerTouchBarItemControlRepresentationAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderTouchBarItem/title",
          "value": "NSSliderTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/title",
          "value": "NSPickerTouchBarItemControlRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1expanded/title",
          "value": "NSPickerTouchBarItemControlRepresentationExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem/title",
          "value": "NSSharingServicePickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickerTouchBarItem/title",
          "value": "NSColorPickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/title",
          "value": "NSUserInterfaceCompressionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceCompressionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceCompressionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/title",
          "value": "NSTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem/title",
          "value": "NSCandidateListTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomTouchBarItem/title",
          "value": "NSCustomTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/title",
          "value": "NSPickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
