{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation/init()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So26AudioBytePacketTranslationVABycfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation": {
      "abstract": [
        {
          "text": "A data structure used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyByteToPacket",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketToByte",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBytePacketTranslation"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBytePacketTranslation"
        }
      ],
      "role": "symbol",
      "title": "AudioBytePacketTranslation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobytepackettranslation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobytepackettranslation/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyByteToPacket": {
      "abstract": [
        {
          "text": "Passes an audio byte packet translation structure with the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field filled out and returns the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " fields. If the value in the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field is an estimate then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " flag is set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyByteToPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyByteToPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyByteToPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePropertyByteToPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepropertybytetopacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketToByte": {
      "abstract": [
        {
          "text": "Passes an audio byte packet translation structure with the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " field filled out and returns the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field. The ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " field is ignored. If the value in the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field is an estimate then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " flag is set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyPacketToByte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketToByte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyPacketToByte"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePropertyPacketToByte",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepropertypackettobyte"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyByteToPacket/title",
          "value": "kAudioFilePropertyByteToPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyByteToPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePropertyByteToPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslation/title",
          "value": "AudioBytePacketTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBytePacketTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBytePacketTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyPacketToByte/title",
          "value": "kAudioFilePropertyPacketToByte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyPacketToByte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePropertyPacketToByte"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiobytepackettranslation/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
