{
  "abstract": [
    {
      "text": "An option that allows the participant to grant other participants read-only permissions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadOnly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSCloudKitSharingServiceOptions@NSCloudKitSharingServiceAllowReadOnly",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allowReadOnly"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSharingService",
        "text": "NSSharingService"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
        "text": "CloudKitOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCloudKitSharingServiceAllowReadOnly"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "allowReadOnly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allowReadOnly"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSharingService",
              "text": "NSSharingService"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
              "text": "CloudKitOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService": {
      "abstract": [
        {
          "text": "An object that facilitates the sharing of content with social media services, or with apps like Mail or Safari.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions": {
      "abstract": [
        {
          "text": "Constants that describe how a participant can configure a CloudKit share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CloudKitOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CloudKitOptions"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService.CloudKitOptions",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/cloudkitoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPrivate": {
      "abstract": [
        {
          "text": "An option that allows the participant to privately distribute the share to other iCloud users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowPrivate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
          "text": "CloudKitOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPrivate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCloudKitSharingServiceAllowPrivate"
        }
      ],
      "role": "symbol",
      "title": "allowPrivate",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/cloudkitoptions/allowprivate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPublic": {
      "abstract": [
        {
          "text": "An option that allows the participant to publicly distribute the share to other iCloud users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowPublic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
          "text": "CloudKitOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPublic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCloudKitSharingServiceAllowPublic"
        }
      ],
      "role": "symbol",
      "title": "allowPublic",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/cloudkitoptions/allowpublic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadOnly": {
      "abstract": [
        {
          "text": "An option that allows the participant to grant other participants read-only permissions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
          "text": "CloudKitOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCloudKitSharingServiceAllowReadOnly"
        }
      ],
      "role": "symbol",
      "title": "allowReadOnly",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/cloudkitoptions/allowreadonly"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadWrite": {
      "abstract": [
        {
          "text": "An option that allows the participant to grant other participants read-write permissions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowReadWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
          "text": "CloudKitOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCloudKitSharingServiceAllowReadWrite"
        }
      ],
      "role": "symbol",
      "title": "allowReadWrite",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/cloudkitoptions/allowreadwrite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/standard": {
      "abstract": [
        {
          "text": "An option that allows the participant to configure the share with a standard set of options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCloudKitSharingServiceOptions",
          "text": "CloudKitOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCloudKitSharingServiceStandard"
        }
      ],
      "role": "symbol",
      "title": "standard",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/cloudkitoptions/standard"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CloudKit-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPrivate",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPublic",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadWrite",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/standard"
      ],
      "title": "CloudKit Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCloudKitSharingServiceAllowReadOnly"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceAllowReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CloudKit-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPrivate",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowPublic",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/allowReadWrite",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/CloudKitOptions/standard"
              ],
              "title": "CloudKit Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCloudKitSharingServiceAllowReadOnly"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowReadOnly/title",
          "value": "NSCloudKitSharingServiceAllowReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceAllowReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions/title",
          "value": "NSCloudKitSharingServiceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1standard/title",
          "value": "NSCloudKitSharingServiceStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/title",
          "value": "NSSharingService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowReadWrite/title",
          "value": "NSCloudKitSharingServiceAllowReadWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowReadWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceAllowReadWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowPrivate/title",
          "value": "NSCloudKitSharingServiceAllowPrivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowPrivate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceAllowPrivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowPublic/title",
          "value": "NSCloudKitSharingServiceAllowPublic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1CloudKitOptions~1allowPublic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudKitSharingServiceAllowPublic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssharingservice/cloudkitoptions/allowreadonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssharingservice/cloudkitoptions/allowreadonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
