{
  "abstract": [
    {
      "text": "Provides a list of the user’s electric vehicles.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling/handle(intent:completion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INListCarsIntentHandling(im)handleListCars:completion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "handle"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "intent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INListCarsIntent",
        "text": "INListCarsIntent"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completion"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INListCarsIntentResponse",
        "text": "INListCarsIntentResponse"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "handleListCars:completion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "handle(intent:completion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INListCarsIntent",
              "text": "INListCarsIntent"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INListCarsIntentResponse",
              "text": "INListCarsIntentResponse"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INListCarsIntent",
              "text": "INListCarsIntent"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INListCarsIntentResponse",
              "text": "INListCarsIntentResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The intent object that represents the request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "intent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block you call with your response. You must call this block within your implementation of this method and pass an instance of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that contains a status code, and a list of the user’s electric vehicles, if available.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Retrieve a list of the user’s electric vehicles and create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for each, setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/carIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to a unique identifier that represents that vehicle. The identifier matches the vehicle to future ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " requests. Do not use the vehicle’s VIN, or equivalent, as the identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before returning from this method, create a response with the appropriate status code and, if you can retrieve a list of the user’s electric vehicles, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse/cars",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the array of ",
              "type": "text"
            },
            {
              "code": "INCar",
              "type": "codeVoice"
            },
            {
              "text": " objects. Then call the completion block and pass the response.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar": {
      "abstract": [
        {
          "text": "A specific electric vehicle that Maps uses during route planning and navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCar"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCar"
        }
      ],
      "role": "symbol",
      "title": "INCar",
      "type": "topic",
      "url": "/documentation/intents/incar"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/carIdentifier": {
      "abstract": [
        {
          "text": "The electric vehicle’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/carIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "carIdentifier"
        }
      ],
      "role": "symbol",
      "title": "carIdentifier",
      "type": "topic",
      "url": "/documentation/intents/incar/caridentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent": {
      "abstract": [
        {
          "text": "A request for the current power level of the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent": {
      "abstract": [
        {
          "text": "An intent for retrieving a list of the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListCarsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListCarsIntent"
        }
      ],
      "role": "symbol",
      "title": "INListCarsIntent",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting a list of the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListCarsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListCarsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INListCarsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Provides a list of the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INListCarsIntent",
          "text": "INListCarsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INListCarsIntentResponse",
          "text": "INListCarsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleListCars:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to list the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListCarsIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListCarsIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INListCarsIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse/cars": {
      "abstract": [
        {
          "text": "An array of the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cars"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse/cars",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cars"
        }
      ],
      "role": "symbol",
      "title": "cars",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintentresponse/cars"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "handleListCars:completion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleListCars:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "handleListCars:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INListCarsIntent",
                    "text": "INListCarsIntent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "intent"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INListCarsIntentResponse",
                    "text": "INListCarsIntentResponse"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "response"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The intent object that represents the request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "intent"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block you call with your response. You must call this block within your implementation of this method and pass an instance of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that contains a status code, and a list of the user’s electric vehicles, if available.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse/title",
          "value": "INListCarsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling~1handle(intent:completion:)/title",
          "value": "handleListCars:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleListCars:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1carIdentifier/title",
          "value": "carIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1carIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "carIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntent/title",
          "value": "INListCarsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling/title",
          "value": "INListCarsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse~1cars/title",
          "value": "cars"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse~1cars/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cars"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/title",
          "value": "INGetCarPowerLevelStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar/title",
          "value": "INCar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inlistcarsintenthandling/handle(intent:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inlistcarsintenthandling/handle(intent:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
