{
  "abstract": [
    {
      "text": "An event that occurs when the media appears on the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/onScreen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SRMediaEventType@SRMediaEventOnScreen",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "onScreen"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRMediaEventOnScreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SRMediaEventType.onScreen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "onScreen"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType": {
      "abstract": [
        {
          "text": "The types of user interaction with media that the sensor tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRMediaEventType"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMediaEventType"
        }
      ],
      "role": "symbol",
      "title": "SRMediaEventType",
      "type": "topic",
      "url": "/documentation/sensorkit/srmediaeventtype"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/offScreen": {
      "abstract": [
        {
          "text": "An event that occurs when the media disappears from the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offScreen"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/offScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMediaEventOffScreen"
        }
      ],
      "role": "symbol",
      "title": "SRMediaEventType.offScreen",
      "type": "topic",
      "url": "/documentation/sensorkit/srmediaeventtype/offscreen"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/onScreen": {
      "abstract": [
        {
          "text": "An event that occurs when the media appears on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onScreen"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/onScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMediaEventOnScreen"
        }
      ],
      "role": "symbol",
      "title": "SRMediaEventType.onScreen",
      "type": "topic",
      "url": "/documentation/sensorkit/srmediaeventtype/onscreen"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/offScreen"
      ],
      "title": "Event types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRMediaEventOnScreen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEventOnScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEventType/offScreen"
              ],
              "title": "Event types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SRMediaEventOnScreen"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType/title",
          "value": "SRMediaEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType~1onScreen/title",
          "value": "SRMediaEventOnScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType~1onScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEventOnScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType~1offScreen/title",
          "value": "SRMediaEventOffScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEventType~1offScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEventOffScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srmediaeventtype/onscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srmediaeventtype/onscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
