{
  "abstract": [
    {
      "text": "An abstract class that represents a location in an element’s accessibility text.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)BEAccessibilityTextMarker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BEAccessibilityTextMarker"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BEAccessibilityTextMarker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "BEAccessibilityTextMarker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Subclass ",
              "type": "text"
            },
            {
              "code": "BEAccessibilityTextMarker",
              "type": "codeVoice"
            },
            {
              "text": " in your app to represent a location in the accessibility text of an element in the document object model (DOM).",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The system uses your implementation of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to convert between accessibility text markers and locations in your app’s views, and doesn’t create instances of your subclass or access their data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker": {
      "abstract": [
        {
          "text": "An abstract class that represents a location in an element’s accessibility text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarker"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarker"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityTextMarker",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarker"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport": {
      "abstract": [
        {
          "text": "A set of methods that provide information about text offsets to support assistive features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarkerSupport"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarkerSupport"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityTextMarkerSupport",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineEndMarker(for:)": {
      "abstract": [
        {
          "text": "Returns the text marker that represents the end of the line that contains the given text marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLineEndMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineEndMarker(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLineEndMarkerForMarker:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLineEndMarker(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitylineendmarker(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineStartMarker(for:)": {
      "abstract": [
        {
          "text": "Returns the text marker that represents the start of the line that contains the given text marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLineStartMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineStartMarker(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLineStartMarkerForMarker:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLineStartMarker(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitylinestartmarker(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityMarker(for:)": {
      "abstract": [
        {
          "text": "Returns the text marker at a point in the view’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityMarker(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityMarkerForPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityMarker(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitymarker(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityNextTextMarker(_:)": {
      "abstract": [
        {
          "text": "Returns the text marker that follows the given text marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityNextTextMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityNextTextMarker(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityNextTextMarker:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityNextTextMarker(_:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitynexttextmarker(_:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityPreviousTextMarker(_:)": {
      "abstract": [
        {
          "text": "Returns the text marker that precedes the given text marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPreviousTextMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityPreviousTextMarker(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPreviousTextMarker:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPreviousTextMarker(_:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilityprevioustextmarker(_:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarker(forPosition:)": {
      "abstract": [
        {
          "text": "Returns the text marker for the text at a given index in the element’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarker(forPosition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerForPosition:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityTextMarker(forPosition:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitytextmarker(forposition:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-positions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityNextTextMarker(_:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityPreviousTextMarker(_:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineStartMarker(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineEndMarker(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityMarker(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarker(forPosition:)"
      ],
      "title": "Text positions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.2",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BEAccessibilityTextMarker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-positions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityNextTextMarker(_:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityPreviousTextMarker(_:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineStartMarker(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityLineEndMarker(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityMarker(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarker(forPosition:)"
              ],
              "title": "Text positions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BEAccessibilityTextMarker"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/title",
          "value": "BEAccessibilityTextMarkerSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityLineEndMarker(for:)/title",
          "value": "accessibilityLineEndMarkerForMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityLineEndMarker(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLineEndMarkerForMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarker(forPosition:)/title",
          "value": "accessibilityTextMarkerForPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarker(forPosition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityTextMarkerForPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityPreviousTextMarker(_:)/title",
          "value": "accessibilityPreviousTextMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityPreviousTextMarker(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPreviousTextMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityLineStartMarker(for:)/title",
          "value": "accessibilityLineStartMarkerForMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityLineStartMarker(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLineStartMarkerForMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker/title",
          "value": "BEAccessibilityTextMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityNextTextMarker(_:)/title",
          "value": "accessibilityNextTextMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityNextTextMarker(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityNextTextMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityMarker(for:)/title",
          "value": "accessibilityMarkerForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityMarker(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityMarkerForPoint:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitytextmarker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitytextmarker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
