{
  "abstract": [
    {
      "text": "An enumeration that indicates the type of container in which an element is located.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BEAccessibilityContainerType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BEAccessibilityContainerType"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BEAccessibilityContainerType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BEAccessibilityContainerType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set a value from this enumeration for an element’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/4446050-browseraccessibilitycontainertyp",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to indicate the type of container in which the element is located.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as the ",
              "type": "text"
            },
            {
              "code": "browserAccessibilityContainerType",
              "type": "codeVoice"
            },
            {
              "text": " for an element within a table cell.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/menuItem": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/menuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTraitMenuItem"
        }
      ],
      "role": "symbol",
      "title": "menuItem",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/menuitem"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/popUpButton": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a pop-up button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUpButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/popUpButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTraitPopUpButton"
        }
      ],
      "role": "symbol",
      "title": "popUpButton",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/popupbutton"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/radioButton": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a radio button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "radioButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/radioButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTraitRadioButton"
        }
      ],
      "role": "symbol",
      "title": "radioButton",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/radiobutton"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/readOnly": {
      "abstract": [
        {
          "text": "The accessibility element is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/readOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTraitReadOnly"
        }
      ],
      "role": "symbol",
      "title": "readOnly",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/readonly"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/selectionChangedNotification": {
      "abstract": [
        {
          "text": "The notification you post when the selection inside an element changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/selectionChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilitySelectionChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "selectionChangedNotification",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/selectionchangednotification"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/valueChangedNotification": {
      "abstract": [
        {
          "text": "The notification you post when the value of an element changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/valueChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityValueChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "valueChangedNotification",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/valuechangednotification"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/visited": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a link that someone previously visited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/visited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTraitVisited"
        }
      ],
      "role": "symbol",
      "title": "visited",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibility/visited"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType": {
      "abstract": [
        {
          "text": "An enumeration that indicates the type of container in which an element is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityContainerType",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/BEAccessibilityContainerTypeNone": {
      "abstract": [
        {
          "text": "The element isn’t in a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeNone"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/BEAccessibilityContainerTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "BEAccessibilityContainerTypeNone",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/beaccessibilitycontainertypenone"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/equatable-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/OptionSet-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/OptionSet-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OptionSet Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/optionset-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/SetAlgebra-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/SetAlgebra-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SetAlgebra Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/setalgebra-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert": {
      "abstract": [
        {
          "text": "An alert contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeAlert"
        }
      ],
      "role": "symbol",
      "title": "alert",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/alert"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article": {
      "abstract": [
        {
          "text": "An HTML article element contains the alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "article"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeArticle"
        }
      ],
      "role": "symbol",
      "title": "article",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/article"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList": {
      "abstract": [
        {
          "text": "A description list contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeDescriptionList"
        }
      ],
      "role": "symbol",
      "title": "descriptionList",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/descriptionlist"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog": {
      "abstract": [
        {
          "text": "A dialog contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeDialog"
        }
      ],
      "role": "symbol",
      "title": "dialog",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/dialog"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset": {
      "abstract": [
        {
          "text": "An HTML fieldset element contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fieldset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeFieldset"
        }
      ],
      "role": "symbol",
      "title": "fieldset",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/fieldset"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame": {
      "abstract": [
        {
          "text": "A frame contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeFrame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/frame"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/init(rawvalue:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark": {
      "abstract": [
        {
          "text": "A website accessibility landmark contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landmark"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeLandmark"
        }
      ],
      "role": "symbol",
      "title": "landmark",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/landmark"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list": {
      "abstract": [
        {
          "text": "A list contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "list"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeList"
        }
      ],
      "role": "symbol",
      "title": "list",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/list"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea": {
      "abstract": [
        {
          "text": "A scroll area contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeScrollArea"
        }
      ],
      "role": "symbol",
      "title": "scrollArea",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/scrollarea"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup": {
      "abstract": [
        {
          "text": "A semantic group contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semanticGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeSemanticGroup"
        }
      ],
      "role": "symbol",
      "title": "semanticGroup",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/semanticgroup"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table": {
      "abstract": [
        {
          "text": "A table contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeTable"
        }
      ],
      "role": "symbol",
      "title": "table",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/table"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree": {
      "abstract": [
        {
          "text": "A tree contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeTree"
        }
      ],
      "role": "symbol",
      "title": "tree",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/tree"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityPressedState": {
      "abstract": [
        {
          "text": "An enumeration that indicates whether an element is pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityPressedState"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityPressedState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityPressedState"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityPressedState",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitypressedstate"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport": {
      "abstract": [
        {
          "text": "A set of methods that provide information about text offsets to support assistive features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarkerSupport"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarkerSupport"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityTextMarkerSupport",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/4446050-browseraccessibilitycontainertyp": {
      "abstract": [
        {
          "text": "The kind of container that contains this element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "browserAccessibilityContainerType"
        },
        {
          "kind": "text",
          "text": ": BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/4446050-browseraccessibilitycontainertyp",
      "kind": "symbol",
      "role": "symbol",
      "title": "browserAccessibilityContainerType",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/4446050-browseraccessibilitycontainertyp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessibility",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/valueChangedNotification",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/selectionChangedNotification",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityPressedState",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/menuItem",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/popUpButton",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/radioButton",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/readOnly",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/visited"
      ],
      "title": "Accessibility"
    }
  ],
  "topicSections": [
    {
      "anchor": "Container-types",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList"
      ],
      "title": "Container types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/Equatable-Implementations",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/OptionSet-Implementations",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/SetAlgebra-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BEAccessibilityContainerType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Container-types",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/BEAccessibilityContainerTypeNone",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList"
              ],
              "title": "Container types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessibility",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/valueChangedNotification",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/selectionChangedNotification",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityPressedState",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/menuItem",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/popUpButton",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/radioButton",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/readOnly",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibility/visited"
              ],
              "title": "Accessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BEAccessibilityContainerType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1selectionChangedNotification/title",
          "value": "BEAccessibilitySelectionChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1selectionChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilitySelectionChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1article/title",
          "value": "BEAccessibilityContainerTypeArticle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1article/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeArticle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1table/title",
          "value": "BEAccessibilityContainerTypeTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1table/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1popUpButton/title",
          "value": "BEAccessibilityTraitPopUpButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1popUpButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTraitPopUpButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1tree/title",
          "value": "BEAccessibilityContainerTypeTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1tree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1semanticGroup/title",
          "value": "BEAccessibilityContainerTypeSemanticGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1semanticGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeSemanticGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1valueChangedNotification/title",
          "value": "BEAccessibilityValueChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1valueChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityValueChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/title",
          "value": "BEAccessibilityTextMarkerSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1list/title",
          "value": "BEAccessibilityContainerTypeList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1list/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1radioButton/title",
          "value": "BEAccessibilityTraitRadioButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1radioButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTraitRadioButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1alert/title",
          "value": "BEAccessibilityContainerTypeAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1scrollArea/title",
          "value": "BEAccessibilityContainerTypeScrollArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1scrollArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeScrollArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1landmark/title",
          "value": "BEAccessibilityContainerTypeLandmark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1landmark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeLandmark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1fieldset/title",
          "value": "BEAccessibilityContainerTypeFieldset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1fieldset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeFieldset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1frame/title",
          "value": "BEAccessibilityContainerTypeFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityPressedState/title",
          "value": "BEAccessibilityPressedState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityPressedState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityPressedState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityPressedState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityPressedState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/title",
          "value": "BEAccessibilityContainerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1dialog/title",
          "value": "BEAccessibilityContainerTypeDialog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1dialog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeDialog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1descriptionList/title",
          "value": "BEAccessibilityContainerTypeDescriptionList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1descriptionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeDescriptionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1visited/title",
          "value": "BEAccessibilityTraitVisited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1visited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTraitVisited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1menuItem/title",
          "value": "BEAccessibilityTraitMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1menuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTraitMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1readOnly/title",
          "value": "BEAccessibilityTraitReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibility~1readOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTraitReadOnly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitycontainertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitycontainertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
