{
  "abstract": [
    {
      "text": "A class that associates a URL with the bookmark you use to access that URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)BEDownloadMonitorLocation",
    "fragments": [
      {
        "kind": "identifier",
        "text": "BEDownloadMonitorLocation"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BEDownloadMonitorLocation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "BEDownloadMonitorLocation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BEDownloadMonitorLocation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Pass the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/bookmarkData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to your browser app to resolve the URL in the app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For information on using XPC to share data between your networking extension and browser app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/using-xpc-to-communicate-with-browser-extensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The URL bookmark in a ",
              "type": "text"
            },
            {
              "code": "Location",
              "type": "codeVoice"
            },
            {
              "text": " isn’t suitable for storing on disk and resolving in subsequent launches of your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To do this, create your own bookmark using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1417795-bookmarkdatawithoptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", passing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/bookmarkcreationoptions/1413824-withsecurityscope",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " flag.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitor-9y4hu/useDownloadsFolderWithPlaceholderType:finalFileCreatedHandler:": {
      "abstract": [
        {
          "text": "Asks the system to create a placeholder for the downloaded file in the person’s Downloads folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "useDownloadsFolderWithPlaceholderType:finalFileCreatedHandler:"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitor-9y4hu/useDownloadsFolderWithPlaceholderType:finalFileCreatedHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useDownloadsFolderWithPlaceholderType:finalFileCreatedHandler:"
        }
      ],
      "role": "symbol",
      "title": "useDownloadsFolderWithPlaceholderType:finalFileCreatedHandler:",
      "type": "topic",
      "url": "/documentation/browserenginekit/bedownloadmonitor-9y4hu/usedownloadsfolderwithplaceholdertype:finalfilecreatedhandler:"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation": {
      "abstract": [
        {
          "text": "A class that associates a URL with the bookmark you use to access that URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BEDownloadMonitorLocation"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "BEDownloadMonitorLocation",
      "type": "topic",
      "url": "/documentation/browserenginekit/bedownloadmonitorlocation"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/bookmarkData": {
      "abstract": [
        {
          "text": "A bookmark that resolves to the resource’s URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "bookmarkData"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/bookmarkData",
      "kind": "symbol",
      "role": "symbol",
      "title": "bookmarkData",
      "type": "topic",
      "url": "/documentation/browserenginekit/bedownloadmonitorlocation/bookmarkdata"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/url": {
      "abstract": [
        {
          "text": "The location of the resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "url"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/url",
      "kind": "symbol",
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/browserenginekit/bedownloadmonitorlocation/url"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/using-xpc-to-communicate-with-browser-extensions": {
      "abstract": [
        {
          "text": "Build interprocess communication between your host app and extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/using-xpc-to-communicate-with-browser-extensions",
      "kind": "article",
      "role": "article",
      "title": "Using XPC to communicate with browser extensions",
      "type": "topic",
      "url": "/documentation/browserenginekit/using-xpc-to-communicate-with-browser-extensions"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl/1417795-bookmarkdatawithoptions": {
      "abstract": [
        {
          "text": "Returns a bookmark for the URL, created with specified options and resource values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1417795-bookmarkdatawithoptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "bookmarkDataWithOptions:includingResourceValuesForKeys:relativeToURL:error:",
      "type": "topic",
      "url": "/documentation/foundation/nsurl/1417795-bookmarkdatawithoptions"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl/bookmarkcreationoptions/1413824-withsecurityscope": {
      "abstract": [
        {
          "text": "Specifies that when creating a security-scoped bookmark, upon resolution, it provides a security-scoped URL allowing read/write access to a file-system resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "withSecurityScope"
        },
        {
          "kind": "text",
          "text": ": NSURL.BookmarkCreationOptions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/bookmarkcreationoptions/1413824-withsecurityscope",
      "kind": "symbol",
      "role": "symbol",
      "title": "withSecurityScope",
      "type": "topic",
      "url": "/documentation/foundation/nsurl/bookmarkcreationoptions/1413824-withsecurityscope"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-download-placeholder",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitor-9y4hu/useDownloadsFolderWithPlaceholderType:finalFileCreatedHandler:"
      ],
      "title": "Creating a download placeholder"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-information-about-a-location",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/url",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDownloadMonitorLocation/bookmarkData"
      ],
      "title": "Getting information about a location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~1bookmarkcreationoptions~11413824-withsecurityscope/title",
          "value": "NSURLBookmarkCreationWithSecurityScope"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~11417795-bookmarkdatawithoptions/title",
          "value": "bookmarkData(options:includingResourceValuesForKeys:relativeTo:)"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~11417795-bookmarkdatawithoptions/fragments",
          "value": [
            {
              "kind": "text",
              "text": "func "
            },
            {
              "kind": "identifier",
              "text": "bookmarkData"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "identifier",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": NSURL.BookmarkCreationOptions, "
            },
            {
              "kind": "identifier",
              "text": "includingResourceValuesForKeys"
            },
            {
              "kind": "text",
              "text": ": [URLResourceKey]?, "
            },
            {
              "kind": "identifier",
              "text": "relativeTo"
            },
            {
              "kind": "text",
              "text": ": URL?) -> Data"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/bedownloadmonitorlocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
