{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BEGestureType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BEGestureType"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BEGestureType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "BEGestureType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEGestureType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureType"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/equatable-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/rawrepresentable-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleTap"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeDoubleTap"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.doubleTap",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/doubletap"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTapAndHold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleTapAndHold"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTapAndHold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeDoubleTapAndHold"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.doubleTapAndHold",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/doubletapandhold"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/forceTouch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceTouch"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/forceTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeForceTouch"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.forceTouch",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/forcetouch"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/imPhraseBoundaryDrag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imPhraseBoundaryDrag"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/imPhraseBoundaryDrag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeIMPhraseBoundaryDrag"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.imPhraseBoundaryDrag",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/imphraseboundarydrag"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/init(rawvalue:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/loupe": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loupe"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/loupe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeLoupe"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.loupe",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/loupe"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerDoubleTap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneFingerDoubleTap"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerDoubleTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeOneFingerDoubleTap"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.oneFingerDoubleTap",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/onefingerdoubletap"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneFingerTap"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeOneFingerTap"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.oneFingerTap",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/onefingertap"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTripleTap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneFingerTripleTap"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTripleTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeOneFingerTripleTap"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.oneFingerTripleTap",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/onefingertripletap"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerRangedSelectGesture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twoFingerRangedSelectGesture"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerRangedSelectGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeTwoFingerRangedSelectGesture"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.twoFingerRangedSelectGesture",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/twofingerrangedselectgesture"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerSingleTap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twoFingerSingleTap"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerSingleTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureTypeTwoFingerSingleTap"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType.twoFingerSingleTap",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype/twofingersingletap"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions": {
      "abstract": [
        {
          "text": "A set of methods that defines extended interactions in browser text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEResponderEditActions"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEResponderEditActions"
        }
      ],
      "role": "symbol",
      "title": "BEResponderEditActions",
      "type": "topic",
      "url": "/documentation/browserenginekit/berespondereditactions"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction": {
      "abstract": [
        {
          "text": "An interaction you add to a text view to support extended text gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInteraction"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInteraction"
        }
      ],
      "role": "symbol",
      "title": "BETextInteraction",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinteraction"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate": {
      "abstract": [
        {
          "text": "A set of methods that informs you about selection changes in text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "BETextInteractionDelegate",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinteractiondelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interaction-responses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions"
      ],
      "title": "Interaction responses"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTap",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTapAndHold",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/forceTouch",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/imPhraseBoundaryDrag",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/loupe",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerDoubleTap",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTap",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTripleTap",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerRangedSelectGesture",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerSingleTap"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/Equatable-Implementations",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BEGestureType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTap",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/doubleTapAndHold",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/forceTouch",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/imPhraseBoundaryDrag",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/loupe",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerDoubleTap",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTap",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/oneFingerTripleTap",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerRangedSelectGesture",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType/twoFingerSingleTap"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interaction-responses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions"
              ],
              "title": "Interaction responses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BEGestureType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1loupe/title",
          "value": "BEGestureTypeLoupe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1loupe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeLoupe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1oneFingerDoubleTap/title",
          "value": "BEGestureTypeOneFingerDoubleTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1oneFingerDoubleTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeOneFingerDoubleTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1forceTouch/title",
          "value": "BEGestureTypeForceTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1forceTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeForceTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteractionDelegate/title",
          "value": "BETextInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1doubleTap/title",
          "value": "BEGestureTypeDoubleTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1doubleTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeDoubleTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1twoFingerSingleTap/title",
          "value": "BEGestureTypeTwoFingerSingleTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1twoFingerSingleTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeTwoFingerSingleTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEResponderEditActions/title",
          "value": "BEResponderEditActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEResponderEditActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEResponderEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEResponderEditActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEResponderEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1oneFingerTap/title",
          "value": "BEGestureTypeOneFingerTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1oneFingerTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeOneFingerTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1imPhraseBoundaryDrag/title",
          "value": "BEGestureTypeIMPhraseBoundaryDrag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1imPhraseBoundaryDrag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeIMPhraseBoundaryDrag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1twoFingerRangedSelectGesture/title",
          "value": "BEGestureTypeTwoFingerRangedSelectGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1twoFingerRangedSelectGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeTwoFingerRangedSelectGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1oneFingerTripleTap/title",
          "value": "BEGestureTypeOneFingerTripleTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1oneFingerTripleTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeOneFingerTripleTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteraction/title",
          "value": "BETextInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1doubleTapAndHold/title",
          "value": "BEGestureTypeDoubleTapAndHold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType~1doubleTapAndHold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureTypeDoubleTapAndHold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType/title",
          "value": "BEGestureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/begesturetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/begesturetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
