{
  "abstract": [
    {
      "text": "An enumeration that records the state of the shift-modifier keys.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BEKeyModifierFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BEKeyModifierFlags"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BEKeyModifierFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "BEKeyModifierFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry": {
      "abstract": [
        {
          "text": "A class that represents a keyboard event in the text system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEKeyEntry"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyEntry"
        }
      ],
      "role": "symbol",
      "title": "BEKeyEntry",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeyentry"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext": {
      "abstract": [
        {
          "text": "A class that describes a key event and the text document with which the event is associated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEKeyEntryContext"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyEntryContext"
        }
      ],
      "role": "symbol",
      "title": "BEKeyEntryContext",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeyentrycontext"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags": {
      "abstract": [
        {
          "text": "An enumeration that records the state of the shift-modifier keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlags"
        }
      ],
      "role": "symbol",
      "title": "BEKeyModifierFlags",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags/equatable-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags/rawrepresentable-implementations"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/capsLock": {
      "abstract": [
        {
          "text": "The caps lock is engaged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capsLock"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/capsLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlagCapsLock"
        }
      ],
      "role": "symbol",
      "title": "BEKeyModifierFlags.capsLock",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags/capslock"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags/init(rawvalue:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/none": {
      "abstract": [
        {
          "text": "There aren’t any active key modifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlagNone"
        }
      ],
      "role": "symbol",
      "title": "BEKeyModifierFlags.none",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags/none"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/shift": {
      "abstract": [
        {
          "text": "The shift key is pressed down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shift"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/shift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlagShift"
        }
      ],
      "role": "symbol",
      "title": "BEKeyModifierFlags.shift",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags/shift"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Keyboard-input",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext"
      ],
      "title": "Keyboard input"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-caps-shift-information",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/capsLock",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/shift",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/none"
      ],
      "title": "Getting caps-shift information"
    },
    {
      "anchor": "Initializing-the-flags",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/init(rawValue:)"
      ],
      "title": "Initializing the flags"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/Equatable-Implementations",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BEKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-caps-shift-information",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/capsLock",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/shift",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags/none"
              ],
              "title": "Getting caps-shift information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Keyboard-input",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext"
              ],
              "title": "Keyboard input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BEKeyModifierFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/title",
          "value": "BEKeyEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags/title",
          "value": "BEKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags~1capsLock/title",
          "value": "BEKeyModifierFlagCapsLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags~1capsLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlagCapsLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags~1shift/title",
          "value": "BEKeyModifierFlagShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags~1shift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlagShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags~1none/title",
          "value": "BEKeyModifierFlagNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlagNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntryContext/title",
          "value": "BEKeyEntryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntryContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/bekeymodifierflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/bekeymodifierflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
