{
  "abstract": [
    {
      "text": "A delegate protocol that a browser text view uses to notify the text system of changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)BETextInputDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BETextInputDelegate"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BETextInputDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "BETextInputDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit"
      ]
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t conform to ",
              "type": "text"
            },
            {
              "code": "BETextInputDelegate",
              "type": "codeVoice"
            },
            {
              "text": " in your classes, or implement its methods.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The operating system creates objects that conform to this protocol and sets them as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/asyncInputDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on your browser’s custom text views.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput": {
      "abstract": [
        {
          "text": "A protocol to which text views conform to asynchronously integrate with the text system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInput"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInput"
        }
      ],
      "role": "symbol",
      "title": "BETextInput",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinput"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/asyncInputDelegate": {
      "abstract": [
        {
          "text": "A system-provided input delegate is assigned when the system is interested in input changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asyncInputDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInputDelegate",
          "text": "BETextInputDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/asyncInputDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asyncInputDelegate"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "asyncInputDelegate",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinput/asyncinputdelegate"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol that a browser text view uses to notify the text system of changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInputDelegate"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInputDelegate"
        }
      ],
      "role": "symbol",
      "title": "BETextInputDelegate",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/invalidateTextEntryContext(for:)": {
      "abstract": [
        {
          "text": "Tells the system the text entry context has changed and that text entry UI’s need to be refreshed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateTextEntryContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInput",
          "text": "BETextInput"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/invalidateTextEntryContext(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateTextEntryContextForTextInput:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "invalidateTextEntryContext(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate/invalidatetextentrycontext(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionDidChange(for:)": {
      "abstract": [
        {
          "text": "Tells the system when the selection has changed in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInput",
          "text": "BETextInput"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionDidChange(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionDidChangeForTextInput:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "selectionDidChange(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate/selectiondidchange(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionWillChange(for:)": {
      "abstract": [
        {
          "text": "Tells the system when the selection is about to change in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionWillChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInput",
          "text": "BETextInput"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionWillChange(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionWillChangeForTextInput:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "selectionWillChange(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate/selectionwillchange(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/shouldDeferEventHandlingToSystem(for:context:)": {
      "abstract": [
        {
          "text": "Defers the key event to the system and returns whether the key event was handled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldDeferEventHandlingToSystem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInput",
          "text": "BETextInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEKeyEntryContext",
          "text": "BEKeyEntryContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/shouldDeferEventHandlingToSystem(for:context:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldDeferEventHandlingToSystemForTextInput:context:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "shouldDeferEventHandlingToSystem(for:context:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate/shoulddefereventhandlingtosystem(for:context:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:deferReplaceTextActionToSystem:)": {
      "abstract": [
        {
          "text": "Defers a replace text action to the ssytem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInput"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInput",
          "text": "BETextInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deferReplaceTextActionToSystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:deferReplaceTextActionToSystem:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInput:deferReplaceTextActionToSystem:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "textInput(_:deferReplaceTextActionToSystem:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate/textinput(_:deferreplacetextactiontosystem:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:setCandidateSuggestions:)": {
      "abstract": [
        {
          "text": "Provides text suggestions to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInput"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)BETextInput",
          "text": "BETextInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "setCandidateSuggestions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BETextSuggestion",
          "text": "BETextSuggestion"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:setCandidateSuggestions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInput:setCandidateSuggestions:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "textInput(_:setCandidateSuggestions:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate/textinput(_:setcandidatesuggestions:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit": {
      "abstract": [
        {
          "text": "Process keyboard interactions asynchronously in your iOS browser app’s text view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
      "kind": "article",
      "role": "article",
      "title": "Integrating custom browser text views with UIKit",
      "type": "topic",
      "url": "/documentation/browserenginekit/integrating-custom-browser-text-views-with-uikit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions": {
      "abstract": [
        {
          "text": "Share content, add replacement shortcuts, and perform other rich actions in browser text views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions",
      "kind": "article",
      "role": "article",
      "title": "Supporting extended text interactions",
      "type": "topic",
      "url": "/documentation/browserenginekit/support-extended-text-interactions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-text-views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput"
      ],
      "title": "Custom text views"
    }
  ],
  "topicSections": [
    {
      "anchor": "Text-selection",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionWillChange(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionDidChange(for:)"
      ],
      "title": "Text selection"
    },
    {
      "anchor": "Deferring-actions-to-the-text-system",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/shouldDeferEventHandlingToSystem(for:context:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:deferReplaceTextActionToSystem:)"
      ],
      "title": "Deferring actions to the text system"
    },
    {
      "anchor": "Providing-completion-suggestions",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:setCandidateSuggestions:)"
      ],
      "title": "Providing completion suggestions"
    },
    {
      "anchor": "Removing-stored-context-information",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/invalidateTextEntryContext(for:)"
      ],
      "title": "Removing stored context information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BETextInputDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Text-selection",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionWillChange(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/selectionDidChange(for:)"
              ],
              "title": "Text selection"
            },
            {
              "anchor": "Deferring-actions-to-the-text-system",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/shouldDeferEventHandlingToSystem(for:context:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:deferReplaceTextActionToSystem:)"
              ],
              "title": "Deferring actions to the text system"
            },
            {
              "anchor": "Providing-completion-suggestions",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/textInput(_:setCandidateSuggestions:)"
              ],
              "title": "Providing completion suggestions"
            },
            {
              "anchor": "Removing-stored-context-information",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate/invalidateTextEntryContext(for:)"
              ],
              "title": "Removing stored context information"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-text-views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput"
              ],
              "title": "Custom text views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BETextInputDelegate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate/title",
          "value": "BETextInputDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/title",
          "value": "BETextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1invalidateTextEntryContext(for:)/title",
          "value": "invalidateTextEntryContextForTextInput:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1invalidateTextEntryContext(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateTextEntryContextForTextInput:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1selectionWillChange(for:)/title",
          "value": "selectionWillChangeForTextInput:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1selectionWillChange(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectionWillChangeForTextInput:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1shouldDeferEventHandlingToSystem(for:context:)/title",
          "value": "shouldDeferEventHandlingToSystemForTextInput:context:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1shouldDeferEventHandlingToSystem(for:context:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldDeferEventHandlingToSystemForTextInput:context:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1asyncInputDelegate/title",
          "value": "asyncInputDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1asyncInputDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "asyncInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1textInput(_:setCandidateSuggestions:)/title",
          "value": "textInput:setCandidateSuggestions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1textInput(_:setCandidateSuggestions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInput:setCandidateSuggestions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1textInput(_:deferReplaceTextActionToSystem:)/title",
          "value": "textInput:deferReplaceTextActionToSystem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1textInput(_:deferReplaceTextActionToSystem:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInput:deferReplaceTextActionToSystem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1selectionDidChange(for:)/title",
          "value": "selectionDidChangeForTextInput:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate~1selectionDidChange(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectionDidChangeForTextInput:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/betextinputdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/betextinputdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
