{
  "abstract": [
    {
      "text": "Control access to files and memory in browser extensions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-resources"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Extension resources"
  },
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/RestrictedSandboxAppliable": {
      "abstract": [
        {
          "text": "A protocol that browser extensions implement to opt into a more restricted sandbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RestrictedSandboxAppliable"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/RestrictedSandboxAppliable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RestrictedSandboxAppliable"
        }
      ],
      "role": "symbol",
      "title": "RestrictedSandboxAppliable",
      "type": "topic",
      "url": "/documentation/browserenginekit/restrictedsandboxappliable"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/RestrictedSandboxRevision": {
      "abstract": [
        {
          "text": "Revisions to the restricted sandbox rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RestrictedSandboxRevision"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/RestrictedSandboxRevision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RestrictedSandboxRevision"
        }
      ],
      "role": "symbol",
      "title": "RestrictedSandboxRevision",
      "type": "topic",
      "url": "/documentation/browserenginekit/restrictedsandboxrevision"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/accessing-files-in-browser-extensions": {
      "abstract": [
        {
          "text": "Grant extensions access to files from within your browser app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/accessing-files-in-browser-extensions",
      "kind": "article",
      "role": "article",
      "title": "Accessing files in browser extensions",
      "type": "topic",
      "url": "/documentation/browserenginekit/accessing-files-in-browser-extensions"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/attributing-memory-to-a-content-extension": {
      "abstract": [
        {
          "text": "Adhere to operating-system limits on GPU memory use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/attributing-memory-to-a-content-extension",
      "kind": "article",
      "role": "article",
      "title": "Attributing memory to a content extension",
      "type": "topic",
      "url": "/documentation/browserenginekit/attributing-memory-to-a-content-extension"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/creating-browser-extensions-in-xcode": {
      "abstract": [
        {
          "text": "Configure your Xcode project to support your alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/creating-browser-extensions-in-xcode",
      "kind": "article",
      "role": "article",
      "title": "Creating browser extensions in Xcode",
      "type": "topic",
      "url": "/documentation/browserenginekit/creating-browser-extensions-in-xcode"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle": {
      "abstract": [
        {
          "text": "Launch, communicate with, and invalidate browser extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extension lifecycle",
      "type": "topic",
      "url": "/documentation/browserenginekit/extension-lifecycle"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/limiting-resource-access-in-content-extensions": {
      "abstract": [
        {
          "text": "Reduce the impact of vulnerabilities in web content extensions by limiting privileges.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/limiting-resource-access-in-content-extensions",
      "kind": "article",
      "role": "article",
      "title": "Limiting resource access in web content extensions",
      "type": "topic",
      "url": "/documentation/browserenginekit/limiting-resource-access-in-content-extensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Browser-extensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/creating-browser-extensions-in-xcode",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle"
      ],
      "title": "Browser extensions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Access-control",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/limiting-resource-access-in-content-extensions",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/accessing-files-in-browser-extensions",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/attributing-memory-to-a-content-extension",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/RestrictedSandboxAppliable",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/RestrictedSandboxRevision"
      ],
      "title": "Access control"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Access-control",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/limiting-resource-access-in-content-extensions",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/accessing-files-in-browser-extensions",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/attributing-memory-to-a-content-extension"
              ],
              "title": "Access control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Browser-extensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/creating-browser-extensions-in-xcode",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle"
              ],
              "title": "Browser extensions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/extension-resources"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/extension-resources"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
