{
  "abstract": [
    {
      "text": "Increase confidence that your code uses pointers correctly.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/improving-control-flow-integrity-with-pointer-authentication"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Improving control flow integrity with pointer authentication"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Many common attacks against software use techniques that compromise control flow within an app, executing code within the app that the attacker wants to run instead of the intended code path.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Two examples of such attacks are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The attacker manipulates the call stack to cause functions to return to the wrong locations.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Return-oriented programming (ROP)",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The attacker manipulates the heap to cause an indirect jump instruction to jump to the wrong location.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Jump-oriented programming (JOP)",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Pointer authentication provides probabilistic protection of control flow integrity (CFI) by annotating pointers with signatures.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You sign a raw pointer to produce a signed pointer, which contains an embedded pointer authentication code (PAC).",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To use a signed pointer, you authenticate it, which validates the PAC and, if valid, returns the raw pointer.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Otherwise, if the authentication operation detects that the pointer is invalid, it returns a value that represents an invalid raw pointer.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Your process generates a segmentation fault and a crash report when it uses the invalid raw pointer.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information, see “Recognize pointer authentication failures” in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/preparing-your-app-to-work-with-pointer-authentication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The authentication operation might fail to detect that a value is invalid, and return a usable value even though its input is invalid.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The authentication check is a probabilistic signal of confidence, not a guarantee that the pointer isn’t compromised.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To generate a PAC that you use to validate a pointer, you need to identify the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "signing schema",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " that the system uses to sign the pointer, which is made up of the signing key and a discriminator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You identify a signing key by name; the CPU keeps the key’s data secret and can use different values for the same key name in different processes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Compute discriminator values as needed. For more information, see the section “Generate a discriminator”, below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In most situations, for example, storing a function pointer in a data structure, you use the ",
                      "type": "text"
                    },
                    {
                      "code": "__ptrauth",
                      "type": "codeVoice"
                    },
                    {
                      "text": " type qualifier on the field where you store the pointer.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This tells the C compiler to store the pointer more securely than it otherwise does by default.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Using the ",
                      "type": "text"
                    },
                    {
                      "code": "__ptrauth",
                      "type": "codeVoice"
                    },
                    {
                      "text": " type qualifier supports several simple, but effective, pointer authentication schemas.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In other situations, for example if you’re writing a just-in-time (JIT) compiler and you protect a pointer to a function that your JIT compiler creates, you might need to use a compiler intrinsic to sign the pointer before you pass it around in yout code.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Additionally, use compiler intrinsics to gain more control over the signing schema, taking care to ensure that an attacker can’t alter the discriminator in the same way that they can alter a signed pointer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The pointer-signing key names intrinsic operations are defined in the header file ",
              "type": "text"
            },
            {
              "code": "<ptrauth.h>",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Generate-a-discriminator",
          "level": 2,
          "text": "Generate a discriminator",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Signing pointers requires an arbitrary value called the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "discriminator",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", that the processor uses as a salt for the signing operation to ensure that signed pointers for different purposes aren’t interchangeable.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Using different discriminators in different places makes it more difficult for an attacker to compromise your code by replacing a valid signed pointer value with a different valid signed pointer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A discriminator is an arbitrary 64-bit value. Typically, you use either a constant value, or a value derived from the address in memory where the pointer is stored. Both of these approaches are supported by the ",
              "type": "text"
            },
            {
              "code": "__ptrauth",
              "type": "codeVoice"
            },
            {
              "text": " type qualifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can choose a constant discriminator value directly, or generate one based on a string using  ",
              "type": "text"
            },
            {
              "code": "ptrauth_string_discriminator",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "const int discriminator = ptrauth_string_discriminator(\"My discriminator string\");"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, combine a constant value with the pointer’s location in memory using ",
              "type": "text"
            },
            {
              "code": "ptrauth_blend_discriminator",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "#define SEED_VALUE 0x1234567890abcdef",
            "",
            "const int discriminator = ptrauth_blend_discriminator(pointer, SEED_VALUE);"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When you use a discriminator that incorporates the pointer’s memory location, you can’t copy the pointer or a data structure that contains the pointer using ",
              "type": "text"
            },
            {
              "code": "memcpy",
              "type": "codeVoice"
            },
            {
              "text": " and related functions because the discriminator isn’t valid to verify the pointer at the new memory location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Select-a-key",
          "level": 2,
          "text": "Select a key",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The cryptographic key that the system uses to generate a PAC for a pointer is known as the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "signing key",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You identify which signing key to use by name, and the system doesn’t give you access to the signing key’s value.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Choose from the four different signing keys, depending on whether you’re protecting a code pointer and whether you need a process-dependent or process-independent signing key:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A process-independent key you use to sign code pointers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_process_independent_code",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A process-dependent key you use to sign code pointers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_process_dependent_code",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A process-independent key you use to sign data pointers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_process_independent_data",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A process-dependent key you use to sign data pointers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_process_dependent_data",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Signing a pointer with a code-signing key produces a larger PAC than a data-signing key, which increases the protection of pointer authentication.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In each case, the size of a signed pointer is the same as the size of an unsigned pointer, and the PAC is stored in unused bits of the pointer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In most situations, use a process-independent signing key.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The system uses process-dependent keys to protect particularly high-value pointers such as return addresses and frame pointers, and if you use the same keys for other contexts you increase the risk that your app re-uses the same signing schema for these pointers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The header file ",
              "type": "text"
            },
            {
              "code": "ptrauth.h",
              "type": "codeVoice"
            },
            {
              "text": " also provides these names that are synonyms for the basic signing keys, that you can use to provide extra information in your code about a protected pointer’s purpose:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key you use to sign function pointers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_function_pointer",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key you use to sign return addresses on the stack.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_return_address",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key you use to sign frame pointers on the stack.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_frame_pointer",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key you use to sign pointers to block functions.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_block_function",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key you use to sign C++ v-table entries.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ptrauth_key_cxx_vtable_pointer",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Annotate-pointers-with-the-pointer-authentication-type-qualifiers",
          "level": 2,
          "text": "Annotate pointers with the pointer-authentication type qualifiers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "__ptrauth",
              "type": "codeVoice"
            },
            {
              "text": " type qualifier to tell the compiler to generate a PAC for your data pointer or function pointer, and to validate the PAC when you dereference the pointer.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The type qualifier takes three arguments:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A constant expression that identifies the name of the abstract signing key to use, discussed in the “Select a key” section above.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "key",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean that indicates whether the compiler needs to use ",
                        "type": "text"
                      },
                      {
                        "code": "ptrauth_blend_discriminator",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to vary the discriminator based on the pointer’s address.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "address",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A constant expression that the system uses as a salt in generating the PAC.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "discriminator",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "For example, to declare a data pointer that the system signs using the constant discriminator value ",
              "type": "text"
            },
            {
              "code": "0x1f35",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "void *__ptrauth(ptrauth_key_process_dependent_data, 0, 0x1f35) *pointer = &data;"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "anchor": "Sign-a-pointer",
          "level": 2,
          "text": "Sign a pointer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To sign a pointer, you need three pieces of information:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The raw pointer. While you can sign the ",
                      "type": "text"
                    },
                    {
                      "code": "NULL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " pointer, the resulting signed pointer has a non-zero value, and code that tests for ",
                      "type": "text"
                    },
                    {
                      "code": "NULL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " by comparing the pointer’s value to ",
                      "type": "text"
                    },
                    {
                      "code": "0",
                      "type": "codeVoice"
                    },
                    {
                      "text": " gets the wrong result. Therefore, you need to test raw pointers for ",
                      "type": "text"
                    },
                    {
                      "code": "NULL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and sign non-",
                      "type": "text"
                    },
                    {
                      "code": "NULL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " raw pointers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The abstract signing key, discussed in the section “Select a key”, above.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "discriminator",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", an arbitrary value discussed in the “Generate a discriminator” section above.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t store the discriminator alongside a signed pointer in memory if you generate different discriminators for different categories of pointers in your app.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Doing so makes it easy for an attacker to replace both the signed pointer and the discriminator that the system uses to validate the PAC.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To produce a signed pointer for a constant address, in this example a data pointer:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "void *signed_pointer = ptrauth_sign_constant(pointer, ptrauth_key_process_dependent_data, discriminator);"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The returned signed pointer is the same size and type as a raw pointer, and the signature information is stored in unused bits of the pointer value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Authenticate-a-signed-pointer",
          "level": 2,
          "text": "Authenticate a signed pointer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To recover the raw pointer value, if the signed pointer passes validity checks, call ",
              "type": "text"
            },
            {
              "code": "ptr_auth_data",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "void *raw_pointer = ptrauth_auth_data(signed_pointer, ptrauth_key_process_dependent_data, discriminator);"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To recover a pointer value that’s signed for use as a function pointer, if the signed pointer passes validity checks, call ",
              "type": "text"
            },
            {
              "code": "ptrauth_auth_function",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "void *function_pointer = ptrauth_auth_fuction(signed_pointer, ptrauth_key_process_dependent_code, discriminator);"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To check the validity of a signed pointer and obtain a version that’s signed with a different key and discriminator, call ",
              "type": "text"
            },
            {
              "code": "ptrauth_auth_and_resign",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "void *other_signed_pointer = ptrauth_auth_and_resign(signed_pointer, original_key, original_discriminator, new_key, new_discriminator);"
          ],
          "syntax": "c",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/protecting-code-compiled-just-in-time": {
      "abstract": [
        {
          "text": "Toggle memory between being writable and executable.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/protecting-code-compiled-just-in-time",
      "kind": "article",
      "role": "article",
      "title": "Protecting code compiled just in time",
      "type": "topic",
      "url": "/documentation/browserenginekit/protecting-code-compiled-just-in-time"
    },
    "doc://com.apple.documentation/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG": {
      "abstract": [
        {
          "text": "A discriminator value the system uses to generate pointer authentication codes for just-in-time compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_JIT_WRITE_PROTECT_TAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG",
      "kind": "symbol",
      "role": "symbol",
      "title": "BE_JIT_WRITE_PROTECT_TAG",
      "type": "topic",
      "url": "/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG"
    },
    "doc://com.apple.documentation/documentation/Security/preparing-your-app-to-work-with-pointer-authentication": {
      "abstract": [
        {
          "text": "Test your app against the arm64e architecture to ensure that it works seamlessly with enhanced security features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/preparing-your-app-to-work-with-pointer-authentication",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to work with pointer authentication",
      "type": "topic",
      "url": "/documentation/Security/preparing-your-app-to-work-with-pointer-authentication"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Just-in-time-code-compilation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/protecting-code-compiled-just-in-time",
        "doc://com.apple.documentation/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG"
      ],
      "title": "Just-in-time code compilation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Just-in-time-code-compilation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/protecting-code-compiled-just-in-time",
                "doc://com.apple.documentation/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG"
              ],
              "title": "Just-in-time code compilation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1BrowserEngineCore~1BE_JIT_WRITE_PROTECT_TAG/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BE_JIT_WRITE_PROTECT_TAG"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/improving-control-flow-integrity-with-pointer-authentication"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/improving-control-flow-integrity-with-pointer-authentication"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
