{
  "abstract": [
    {
      "text": "Integrate your web browser engine asynchronously with the text system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/text-interaction"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Text interaction"
  },
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAutoFillTextSuggestion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAutoFillTextSuggestion"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAutoFillTextSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAutoFillTextSuggestion"
        }
      ],
      "role": "symbol",
      "title": "BEAutoFillTextSuggestion",
      "type": "topic",
      "url": "/documentation/browserenginekit/beautofilltextsuggestion"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDirectionalTextRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEDirectionalTextRange"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDirectionalTextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEDirectionalTextRange"
        }
      ],
      "role": "symbol",
      "title": "BEDirectionalTextRange",
      "type": "topic",
      "url": "/documentation/browserenginekit/bedirectionaltextrange"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEExtendedTextInputTraits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEExtendedTextInputTraits"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEExtendedTextInputTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEExtendedTextInputTraits"
        }
      ],
      "role": "symbol",
      "title": "BEExtendedTextInputTraits",
      "type": "topic",
      "url": "/documentation/browserenginekit/beextendedtextinputtraits"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEGestureType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEGestureType"
        }
      ],
      "role": "symbol",
      "title": "BEGestureType",
      "type": "topic",
      "url": "/documentation/browserenginekit/begesturetype"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry": {
      "abstract": [
        {
          "text": "A class that represents a keyboard event in the text system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEKeyEntry"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyEntry"
        }
      ],
      "role": "symbol",
      "title": "BEKeyEntry",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeyentry"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext": {
      "abstract": [
        {
          "text": "A class that describes a key event and the text document with which the event is associated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEKeyEntryContext"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyEntryContext"
        }
      ],
      "role": "symbol",
      "title": "BEKeyEntryContext",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeyentrycontext"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags": {
      "abstract": [
        {
          "text": "An enumeration that records the state of the shift-modifier keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEKeyModifierFlags"
        }
      ],
      "role": "symbol",
      "title": "BEKeyModifierFlags",
      "type": "topic",
      "url": "/documentation/browserenginekit/bekeymodifierflags"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions": {
      "abstract": [
        {
          "text": "A set of methods that defines extended interactions in browser text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEResponderEditActions"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEResponderEditActions"
        }
      ],
      "role": "symbol",
      "title": "BEResponderEditActions",
      "type": "topic",
      "url": "/documentation/browserenginekit/berespondereditactions"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BESelectionFlags"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BESelectionFlags"
        }
      ],
      "role": "symbol",
      "title": "BESelectionFlags",
      "type": "topic",
      "url": "/documentation/browserenginekit/beselectionflags"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionTouchPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BESelectionTouchPhase"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionTouchPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BESelectionTouchPhase"
        }
      ],
      "role": "symbol",
      "title": "BESelectionTouchPhase",
      "type": "topic",
      "url": "/documentation/browserenginekit/beselectiontouchphase"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextAlternatives": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextAlternatives"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextAlternatives",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextAlternatives"
        }
      ],
      "role": "symbol",
      "title": "BETextAlternatives",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextalternatives"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentContext": {
      "abstract": [
        {
          "text": "Information about the text surrounding a selection in a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextDocumentContext"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextDocumentContext"
        }
      ],
      "role": "symbol",
      "title": "BETextDocumentContext",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextdocumentcontext"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextDocumentRequest"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextDocumentRequest"
        }
      ],
      "role": "symbol",
      "title": "BETextDocumentRequest",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextdocumentrequest"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest/Options-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "BETextDocumentRequest.Options",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextdocumentrequest/options-swift.struct"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput": {
      "abstract": [
        {
          "text": "A protocol to which text views conform to asynchronously integrate with the text system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInput"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInput"
        }
      ],
      "role": "symbol",
      "title": "BETextInput",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinput"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol that a browser text view uses to notify the text system of changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInputDelegate"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInputDelegate"
        }
      ],
      "role": "symbol",
      "title": "BETextInputDelegate",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinputdelegate"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction": {
      "abstract": [
        {
          "text": "An interaction you add to a text view to support extended text gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInteraction"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInteraction"
        }
      ],
      "role": "symbol",
      "title": "BETextInteraction",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinteraction"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate": {
      "abstract": [
        {
          "text": "A set of methods that informs you about selection changes in text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "BETextInteractionDelegate",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinteractiondelegate"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextReplacementOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextReplacementOptions"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextReplacementOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextReplacementOptions"
        }
      ],
      "role": "symbol",
      "title": "BETextReplacementOptions",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextreplacementoptions"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSelectionDirectionNavigation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextSelectionDirectionNavigation"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSelectionDirectionNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextSelectionDirectionNavigation"
        }
      ],
      "role": "symbol",
      "title": "BETextSelectionDirectionNavigation",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextselectiondirectionnavigation"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSuggestion": {
      "abstract": [
        {
          "text": "A text suggestion to insert into a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextSuggestion"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextSuggestion"
        }
      ],
      "role": "symbol",
      "title": "BETextSuggestion",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextsuggestion"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEWebAppManifest": {
      "abstract": [
        {
          "text": "An object that represents a web app manifest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEWebAppManifest"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEWebAppManifest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEWebAppManifest"
        }
      ],
      "role": "symbol",
      "title": "BEWebAppManifest",
      "type": "topic",
      "url": "/documentation/browserenginekit/bewebappmanifest"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit": {
      "abstract": [
        {
          "text": "Process keyboard interactions asynchronously in your iOS browser app’s text view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
      "kind": "article",
      "role": "article",
      "title": "Integrating custom browser text views with UIKit",
      "type": "topic",
      "url": "/documentation/browserenginekit/integrating-custom-browser-text-views-with-uikit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions": {
      "abstract": [
        {
          "text": "Share content, add replacement shortcuts, and perform other rich actions in browser text views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions",
      "kind": "article",
      "role": "article",
      "title": "Supporting extended text interactions",
      "type": "topic",
      "url": "/documentation/browserenginekit/support-extended-text-interactions"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/view-coordination": {
      "abstract": [
        {
          "text": "Display content in the browser’s UI that an extension renders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/view-coordination",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View coordination",
      "type": "topic",
      "url": "/documentation/browserenginekit/view-coordination"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Web-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/view-coordination",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEWebAppManifest"
      ],
      "title": "Web content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Custom-text-views",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate"
      ],
      "title": "Custom text views"
    },
    {
      "anchor": "Interaction-responses",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions"
      ],
      "title": "Interaction responses"
    },
    {
      "anchor": "Text-selection",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSelectionDirectionNavigation",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionFlags",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionTouchPhase"
      ],
      "title": "Text selection"
    },
    {
      "anchor": "Keyboard-input",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags"
      ],
      "title": "Keyboard input"
    },
    {
      "anchor": "Replacements-and-AutoFill",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAutoFillTextSuggestion",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextAlternatives",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentContext",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest/Options-swift.struct",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSuggestion",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextReplacementOptions"
      ],
      "title": "Replacements and AutoFill"
    },
    {
      "anchor": "Information-about-text",
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEExtendedTextInputTraits",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDirectionalTextRange"
      ],
      "title": "Information about text"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Custom-text-views",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/support-extended-text-interactions",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInputDelegate"
              ],
              "title": "Custom text views"
            },
            {
              "anchor": "Interaction-responses",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteraction",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInteractionDelegate",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEGestureType",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEResponderEditActions"
              ],
              "title": "Interaction responses"
            },
            {
              "anchor": "Text-selection",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSelectionDirectionNavigation",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionFlags",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BESelectionTouchPhase"
              ],
              "title": "Text selection"
            },
            {
              "anchor": "Keyboard-input",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntryContext",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyModifierFlags"
              ],
              "title": "Keyboard input"
            },
            {
              "anchor": "Replacements-and-AutoFill",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAutoFillTextSuggestion",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextAlternatives",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentContext",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextDocumentRequest/Options-swift.struct",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextSuggestion",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextReplacementOptions"
              ],
              "title": "Replacements and AutoFill"
            },
            {
              "anchor": "Information-about-text",
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEExtendedTextInputTraits",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEDirectionalTextRange"
              ],
              "title": "Information about text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Web-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/view-coordination",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEWebAppManifest"
              ],
              "title": "Web content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteractionDelegate/title",
          "value": "BETextInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAutoFillTextSuggestion/title",
          "value": "BEAutoFillTextSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAutoFillTextSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAutoFillTextSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAutoFillTextSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAutoFillTextSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextReplacementOptions/title",
          "value": "BETextReplacementOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextReplacementOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextReplacementOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextReplacementOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextReplacementOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/title",
          "value": "BEKeyEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEWebAppManifest/title",
          "value": "BEWebAppManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEWebAppManifest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEWebAppManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEWebAppManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEWebAppManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType/title",
          "value": "BEGestureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEGestureType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEGestureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextSelectionDirectionNavigation/title",
          "value": "BETextSelectionDirectionNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextSelectionDirectionNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextSelectionDirectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextSelectionDirectionNavigation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextSelectionDirectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteraction/title",
          "value": "BETextInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEResponderEditActions/title",
          "value": "BEResponderEditActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEResponderEditActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEResponderEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEResponderEditActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEResponderEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate/title",
          "value": "BETextInputDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInputDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BESelectionFlags/title",
          "value": "BESelectionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BESelectionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BESelectionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BESelectionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BESelectionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntryContext/title",
          "value": "BEKeyEntryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyEntryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEExtendedTextInputTraits/title",
          "value": "BEExtendedTextInputTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEExtendedTextInputTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEExtendedTextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEExtendedTextInputTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEExtendedTextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BESelectionTouchPhase/title",
          "value": "BESelectionTouchPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BESelectionTouchPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BESelectionTouchPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BESelectionTouchPhase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BESelectionTouchPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags/title",
          "value": "BEKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyModifierFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextAlternatives/title",
          "value": "BETextAlternatives"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextAlternatives/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextAlternatives/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEDirectionalTextRange/title",
          "value": "BEDirectionalTextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEDirectionalTextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEDirectionalTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEDirectionalTextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEDirectionalTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextSuggestion/title",
          "value": "BETextSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentRequest~1Options-swift.struct/title",
          "value": "BETextDocumentRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentRequest~1Options-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextDocumentRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentRequest~1Options-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextDocumentRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentRequest/title",
          "value": "BETextDocumentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextDocumentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextDocumentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/title",
          "value": "BETextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentContext/title",
          "value": "BETextDocumentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextDocumentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextDocumentContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextDocumentContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/text-interaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/text-interaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
