{
  "abstract": [
    {
      "text": "Build interprocess communication between your host app and extensions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/using-xpc-to-communicate-with-browser-extensions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Using XPC to communicate with browser extensions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When ",
              "type": "text"
            },
            {
              "code": "BrowserEngineKit",
              "type": "codeVoice"
            },
            {
              "text": " launches your extension processes, it provides the host app with a simple way to initiate an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " connection with the extensions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use this connection to communicate with the extensions, and to set up anonymous connections that the extensions use to communicate directly with each other.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-connection-in-the-browser-app",
          "level": 2,
          "text": "Create a connection in the browser app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your browser app has launched an extension, call the extension’s ",
              "type": "text"
            },
            {
              "code": "makeLibXPCConnection()",
              "type": "codeVoice"
            },
            {
              "text": " method to create and initialize an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that represents an XPC connection between the browser app and the extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, to get an ",
              "type": "text"
            },
            {
              "code": "xpc_connection_t",
              "type": "codeVoice"
            },
            {
              "text": " that represents a ",
              "type": "text"
            },
            {
              "code": "libxpc",
              "type": "codeVoice"
            },
            {
              "text": " connection for IPC between your host app and its networking extension:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "do {",
            "  let networkExtensionConnection = try networkProcess.makeLibXPCConnection()",
            "  // Use the connection.",
            "} catch {",
            "  // Handle the error.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework to create objects that represent messages you send over the connection.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You send all messages as dictionary objects.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, to send a URL to the network extension:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension URL {",
            "    func toXPCObject() -> xpc_object_t {",
            "\t\tlet urlString = xpc_string_create(self.absoluteString)",
            "        let dict = xpc_dictionary_create_empty()",
            "        xpc_dictionary_set_string(dict, \"x-url-key\", urlString)",
            "        return dict",
            "    }",
            "}",
            "",
            "func fetchData(from url: URL, over connection: xpc_connection_t) throws {",
            "    xpc_connection_send_message_with_reply(connection, url.toXPCObject(), nil) { reply in",
            "        // Handle the reply object.",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data type and functions that act on it are described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC/xpc-connections",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "It is recommended that you use this API for browser apps and their extensions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Handle-XPC-events-in-the-extension",
          "level": 2,
          "text": "Handle XPC events in the extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your browser app calls an extension process’s ",
              "type": "text"
            },
            {
              "code": "makeLibXPCConnection()",
              "type": "codeVoice"
            },
            {
              "text": " method, ",
              "type": "text"
            },
            {
              "code": "BrowserEngineKit",
              "type": "codeVoice"
            },
            {
              "text": " sets up the XPC connection and calls your extension’s ",
              "type": "text"
            },
            {
              "code": "handle(xpcConnection:)",
              "type": "codeVoice"
            },
            {
              "text": " method.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In your implementation of this method, install an event handler to process messages sent over this connection, and activate the connection:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class MyNetworkExtension: NetworkingExtension {",
            "",
            "\tpublic func handle(xpcConnection: xpc_connection_t) {",
            "\t\txpc_connection_set_event_handler(xpcConnection) { event in",
            "\t\t\t// Process the event, replying if necessary.",
            "\t\t}",
            "\t\txpc_connection_activate(xpcConnection)",
            "\t}",
            "\t",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t call ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_main(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " from a browser extension.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This function sets up the event loop for an XPC service, which causes problems if you call it in a process that isn’t an XPC service, for example a browser extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Pass-anonymous-connection-endpoints-between-extensions",
          "level": 2,
          "text": "Pass anonymous connection endpoints between extensions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When two extensions that are part of the same browser app need to communicate directly, send an XPC message requesting an anonymous endpoint from the browser app to the first extension.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In the first extension’s connection handler, configure and activate the connection. Wrap the connection you created in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_endpoint_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and send it in a reply to the host app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/* In the connection event handler for the connection to the browser app,",
            " * when you determine that a message is a request to open a connection to",
            " * another extension.",
            " */",
            " ",
            "// Set up the anonymous XPC connection.",
            "let anonymousConnection = xpc_connection_create(nil, nil)",
            "xpc_connection_set_event_handler(anonymousConnection) { event in",
            "\t// Process events from the other extension.",
            "}",
            "xpc_connection_activate(anonymousConnection)",
            "",
            "// Create an endpoint and send it to the browser app in reply to the message.",
            "let endpoint = xpc_endpoint_create(anonymousConnection)",
            "let reply = xpc_dictionary_create_reply(originalMessage)",
            "xpc_dictionary_set_value(reply, \"x-endpoint-key\", endpoint)",
            "",
            "xpc_connection_send_message(browserConnection, reply)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In the browser app’s reply handler, pass the ",
              "type": "text"
            },
            {
              "code": "xpc_endpoint_t",
              "type": "codeVoice"
            },
            {
              "text": " to the other extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/* The reply handler in the browser app. */",
            "",
            "let endpointRequestReplyHandler = { replyWithEndpoint in",
            "\t// Check for error.",
            "\tguard xpc_get_type(replyWithEndpoint) != XPC_TYPE_DICTIONARY else {",
            "\t\t// Handle the error.",
            "\t\treturn",
            "\t}",
            "\t// Send the dictionary that contains the endpoint to the other extension.",
            "\txpc_connection_send(otherEndpointConnection, replyWithEndpoint)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, in the extension that receives the ",
              "type": "text"
            },
            {
              "code": "xpc_endpoint_t",
              "type": "codeVoice"
            },
            {
              "text": ", call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_create_from_endpoint(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get an ",
              "type": "text"
            },
            {
              "code": "xpc_connection_t",
              "type": "codeVoice"
            },
            {
              "text": " that the receiving extension uses to message the creating extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/* The connection event handler for the receiving extension. */",
            "",
            "// Retrieve the endpoint from the connection event",
            "let\tendpoint = xpc_dictionary_get_value(reply, \"x-endpoint-key\")",
            "",
            "guard let endpoint = endpoint else {",
            "\t// Handle an incorrectly-formed message.",
            "\treturn",
            "}",
            "",
            "// Create a new connection from the endpoint.",
            "let otherExtensionConnection = xpc_connection_create_from_endpoint(endpoint)",
            "",
            "// Send messages to the other extension."
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Verify-the-identity-of-the-remote-process",
          "level": 2,
          "text": "Verify the identity of the remote process",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To be confident that your browser app or extension is communicating with the correct component, set a lightweight code requirement on the XPC connection.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The operating system tests that the executable for the process at the remote end of the connection satisfies the requirement each time the process sends a message.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "It’s possible for the process sending messages to your XPC connection to change at runtime, for example, if the listener creates an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_endpoint_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and forwards it to a different process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In the sending process, if you send a message over an XPC connection and the receiving process doesn’t satisfy the lightweight code requirement you set, the message isn’t delivered.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If you request a reply, XPC delivers the ",
              "type": "text"
            },
            {
              "code": "XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT",
              "type": "codeVoice"
            },
            {
              "text": " error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the receiving process, if a process that doesn’t satisfy the lightweight code requirement you set sends a message to your connection, the operating system drops the message and your event handler isn’t called.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sending and receiving process can each set a single lightweight code requirement on an XPC connection.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For information on creating complex requirements that test multiple properties of the communicating process’s executable, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/defining-launch-environment-and-library-constraints",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For each XPC connection on which you set a lightweight code requirement, call one of the functions below to define the lightweight code requirement and attach it to the connection.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Each function returns ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " if it sets the lightweight code requirement, or another value if it encounters an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A specific entitlement needs to exist in the executable’s code signature.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A specific entitlement needs to exist in the executable’s code signature, and have the given value.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The executable needs to be signed with a developer code-signing identity issued by Apple, an enterprise code-signing identity, or an identity suitable for Developer ID, Testflight, or App Store distribution, by the identified developer team. The signing identifier needs to have the specified value. The signing identifier is usually an app’s Bundle ID, or a similar string for non-app executables; pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if any executable by the developer team is appropriate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The executable needs to be signed by Apple, with the given signing identifier.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The executable needs to satisfy the lightweight code requirement you supply as a dictionary in the ",
                        "type": "text"
                      },
                      {
                        "code": "lwcr",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "It’s an error to call multiple functions that set lightweight code requirements on the same XPC connection, or the same function more than once.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If you do, the operating system terminates your process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, to require that the executable’s code signature contains the browser rendering extension entitlement with a value of ",
              "type": "text"
            },
            {
              "code": "com.example.browserapp",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let expectedValue = xpc_string_create(\"com.example.browserapp\")",
            "xpc_connection_set_peer_entitlement_matches_value_requirement(connection,",
            "\t\"com.apple.developer.web-browser-engine.rendering\",",
            "\texpectedValue);",
            "",
            "// Use the connection."
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle": {
      "abstract": [
        {
          "text": "Launch, communicate with, and invalidate browser extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/extension-lifecycle",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extension lifecycle",
      "type": "topic",
      "url": "/documentation/browserenginekit/extension-lifecycle"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/managing-the-browser-extension-lifecycle": {
      "abstract": [
        {
          "text": "Coordinate helper processes to efficiently support your browser app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/managing-the-browser-extension-lifecycle",
      "kind": "article",
      "role": "article",
      "title": "Managing the browser extension life cycle",
      "type": "topic",
      "url": "/documentation/browserenginekit/managing-the-browser-extension-lifecycle"
    },
    "doc://com.apple.documentation/documentation/Security/defining-launch-environment-and-library-constraints": {
      "abstract": [
        {
          "text": "Restrict your app’s components to their expected contexts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/defining-launch-environment-and-library-constraints",
      "kind": "article",
      "role": "article",
      "title": "Defining launch environment and library constraints",
      "type": "topic",
      "url": "/documentation/Security/defining-launch-environment-and-library-constraints"
    },
    "doc://com.apple.documentation/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/XPC"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc-connections": {
      "abstract": [
        {
          "text": "Create and manage connections to services using connection-based APIs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc-connections",
      "kind": "article",
      "role": "article",
      "title": "XPC connections",
      "type": "topic",
      "url": "/documentation/XPC/xpc-connections"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_create_from_endpoint(_:)": {
      "abstract": [
        {
          "text": "Creates a new connection from the specified endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_create_from_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_endpoint_t",
          "text": "xpc_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_create_from_endpoint(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_create_from_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_create_from_endpoint(_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_code_signing_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_code_signing_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_code_signing_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that contains an entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_exists_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "entitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that contains an entitlement with a specific value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "entitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that identifies it as an Apple-signed binary with the given signing identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "signing_identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_platform_identity_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature and is signed by the same team identifier as the calling process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_team_identity_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "signing_identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_team_identity_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_t": {
      "abstract": [
        {
          "text": "A type that represents a connection to a named service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_t",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_t"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_endpoint_t": {
      "abstract": [
        {
          "text": "A type that represents a connection in serialized form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_endpoint_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_endpoint_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_endpoint_t",
      "type": "topic",
      "url": "/documentation/XPC/xpc_endpoint_t"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_main(_:)": {
      "abstract": [
        {
          "text": "Starts listening for incoming connections and processes them with the specified event handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_main"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_handler_t",
          "text": "xpc_connection_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_main(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_main(_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_main(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/managing-the-browser-extension-lifecycle"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/managing-the-browser-extension-lifecycle"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_main(_:)/title",
          "value": "xpc_main"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_main(_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_main"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_handler_t",
              "text": "xpc_connection_handler_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)/title",
          "value": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "entitlement"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_endpoint_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_endpoint_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_exists_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_entitlement_exists_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_exists_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_entitlement_exists_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "entitlement"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_create_from_endpoint(_:)/title",
          "value": "xpc_connection_create_from_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_create_from_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_create_from_endpoint"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_endpoint_t",
              "text": "xpc_endpoint_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "endpoint"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_code_signing_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_code_signing_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_code_signing_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_code_signing_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "requirement"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_team_identity_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_team_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_team_identity_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_team_identity_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "signing_identifier"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_platform_identity_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_platform_identity_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_platform_identity_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "signing_identifier"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/using-xpc-to-communicate-with-browser-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/using-xpc-to-communicate-with-browser-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
