{
  "abstract": [
    {
      "text": "An annotation that underlines text.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/underline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PDFKit",
    "externalID": "c:@PDFAnnotationSubtypeUnderline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "underline"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
        "text": "PDFAnnotationSubtype"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAnnotationSubtypeUnderline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "underline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "underline"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
              "text": "PDFAnnotationSubtype"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype": {
      "abstract": [
        {
          "text": "The type of annotation, such as circle, text, or ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationSubtype",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/circle": {
      "abstract": [
        {
          "text": "An annotation that renders a circle shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/circle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeCircle"
        }
      ],
      "role": "symbol",
      "title": "circle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/circle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/freeText": {
      "abstract": [
        {
          "text": "An annotation that displays an editable text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/freeText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeFreeText"
        }
      ],
      "role": "symbol",
      "title": "freeText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/freetext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/highlight": {
      "abstract": [
        {
          "text": "An annotation that highlights text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/highlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeHighlight"
        }
      ],
      "role": "symbol",
      "title": "highlight",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/highlight"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/ink": {
      "abstract": [
        {
          "text": "An annotation that represents a freehand scribble.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/ink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeInk"
        }
      ],
      "role": "symbol",
      "title": "ink",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/ink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/line": {
      "abstract": [
        {
          "text": "An annotation that displays a single straight line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeLine"
        }
      ],
      "role": "symbol",
      "title": "line",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/line"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/link": {
      "abstract": [
        {
          "text": "An annotation that provides a hyperlink to a location in the document, or an action to perform when the user clicks or taps it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeLink"
        }
      ],
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/link"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/popup": {
      "abstract": [
        {
          "text": "An annotation that displays text in a pop-up window for entry and editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/popup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypePopup"
        }
      ],
      "role": "symbol",
      "title": "popup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/popup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/square": {
      "abstract": [
        {
          "text": "An annotation that displays a square shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeSquare"
        }
      ],
      "role": "symbol",
      "title": "square",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/square"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/stamp": {
      "abstract": [
        {
          "text": "An annotation that displays text or a graphic as if a rubber stamp imprints it on the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/stamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeStamp"
        }
      ],
      "role": "symbol",
      "title": "stamp",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/stamp"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/strikeOut": {
      "abstract": [
        {
          "text": "An annotation that strikes out text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strikeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/strikeOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeStrikeOut"
        }
      ],
      "role": "symbol",
      "title": "strikeOut",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/strikeout"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/text": {
      "abstract": [
        {
          "text": "An annotation that displays a collapsible note that contains text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeText"
        }
      ],
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/text"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/underline": {
      "abstract": [
        {
          "text": "An annotation that underlines text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/underline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeUnderline"
        }
      ],
      "role": "symbol",
      "title": "underline",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/underline"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/widget": {
      "abstract": [
        {
          "text": "An annotation that displays interactive form elements, including text or signature fields, radio buttons, checkboxes, push buttons, pop-ups, and tables.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/widget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtypeWidget"
        }
      ],
      "role": "symbol",
      "title": "widget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype/widget"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Choosing-an-Annotation-Subtype",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/circle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/freeText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/highlight",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/ink",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/line",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/link",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/popup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/square",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/stamp",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/strikeOut",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/text",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/widget"
      ],
      "title": "Choosing an Annotation Subtype"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAnnotationSubtypeUnderline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeUnderline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Choosing-an-Annotation-Subtype",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/circle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/freeText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/highlight",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/ink",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/line",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/link",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/popup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/square",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/stamp",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/strikeOut",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/text",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype/widget"
              ],
              "title": "Choosing an Annotation Subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PDFAnnotationSubtype",
                    "text": "PDFAnnotationSubtype"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAnnotationSubtypeUnderline"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1popup/title",
          "value": "PDFAnnotationSubtypePopup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1popup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypePopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1line/title",
          "value": "PDFAnnotationSubtypeLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1underline/title",
          "value": "PDFAnnotationSubtypeUnderline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1underline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeUnderline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1highlight/title",
          "value": "PDFAnnotationSubtypeHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1highlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1square/title",
          "value": "PDFAnnotationSubtypeSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1ink/title",
          "value": "PDFAnnotationSubtypeInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1ink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1link/title",
          "value": "PDFAnnotationSubtypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/title",
          "value": "PDFAnnotationSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1widget/title",
          "value": "PDFAnnotationSubtypeWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1widget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1circle/title",
          "value": "PDFAnnotationSubtypeCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1circle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1freeText/title",
          "value": "PDFAnnotationSubtypeFreeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1freeText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeFreeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1text/title",
          "value": "PDFAnnotationSubtypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1stamp/title",
          "value": "PDFAnnotationSubtypeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1stamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1strikeOut/title",
          "value": "PDFAnnotationSubtypeStrikeOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype~1strikeOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtypeStrikeOut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationsubtype/underline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationsubtype/underline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
