{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRInteractionErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRInteractionError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRInteractionError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionError"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/busy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeBusy"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.busy",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/busy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/constraintError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/constraintError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeConstraintError"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.constraintError",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/constrainterror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/dataVersionMismatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataVersionMismatch"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/dataVersionMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeDataVersionMismatch"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.dataVersionMismatch",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/dataversionmismatch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failsafeRequired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failsafeRequired"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failsafeRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeFailsafeRequired"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.failsafeRequired",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/failsaferequired"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.failure",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/failure"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeInvalidAction"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.invalidAction",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/invalidaction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCommand"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeInvalidCommand"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.invalidCommand",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/invalidcommand"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidDataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDataType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeInvalidDataType"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.invalidDataType",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/invaliddatatype"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidInState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidInState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidInState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeInvalidInState"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.invalidInState",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/invalidinstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidSubscription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSubscription"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeInvalidSubscription"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.invalidSubscription",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/invalidsubscription"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/needsTimedInteraction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsTimedInteraction"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/needsTimedInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeNeedsTimedInteraction"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.needsTimedInteraction",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/needstimedinteraction"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noCommandResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCommandResponse"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noCommandResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeNoCommandResponse"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.noCommandResponse",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/nocommandresponse"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noUpstreamSubscription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noUpstreamSubscription"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noUpstreamSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeNoUpstreamSubscription"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.noUpstreamSubscription",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/noupstreamsubscription"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/notFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/notFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeNotFound"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.notFound",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/notfound"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/pathsExhausted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathsExhausted"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/pathsExhausted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodePathsExhausted"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.pathsExhausted",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/pathsexhausted"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/resourceExhausted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceExhausted"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/resourceExhausted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeResourceExhausted"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.resourceExhausted",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/resourceexhausted"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timedRequestMismatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedRequestMismatch"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timedRequestMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeTimedRequestMismatch"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.timedRequestMismatch",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/timedrequestmismatch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeTimeout"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.timeout",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/timeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unreportableAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unreportableAttribute"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unreportableAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnreportableAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unreportableAttribute",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unreportableattribute"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedAccess"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedAccess"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedAccess",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedaccess"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedAttribute"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedAttribute",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedattribute"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCluster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedCluster"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedCluster"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedCluster",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedcluster"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedCommand"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedCommand"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedCommand",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedcommand"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEndpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedEndpoint"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedEndpoint"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedEndpoint",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedendpoint"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedEvent"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedEvent"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedEvent",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedevent"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedRead"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedRead"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedRead",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedread"
    },
    "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedWrite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedWrite"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRInteractionErrorCodeUnsupportedWrite"
        }
      ],
      "role": "symbol",
      "title": "MTRInteractionError.Code.unsupportedWrite",
      "type": "topic",
      "url": "/documentation/matter/mtrinteractionerror/code/unsupportedwrite"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/busy",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/constraintError",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/dataVersionMismatch",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failsafeRequired",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failure",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidAction",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidCommand",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidDataType",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidInState",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidSubscription",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/needsTimedInteraction",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noCommandResponse",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noUpstreamSubscription",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/notFound",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/pathsExhausted",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/resourceExhausted",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timedRequestMismatch",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timeout",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unreportableAttribute",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAccess",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAttribute",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCluster",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCommand",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEndpoint",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEvent",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedRead",
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedWrite"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRInteractionErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/busy",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/constraintError",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/dataVersionMismatch",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failsafeRequired",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/failure",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidAction",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidCommand",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidDataType",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidInState",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/invalidSubscription",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/needsTimedInteraction",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noCommandResponse",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/noUpstreamSubscription",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/notFound",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/pathsExhausted",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/resourceExhausted",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timedRequestMismatch",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/timeout",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unreportableAttribute",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAccess",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedAttribute",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCluster",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedCommand",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEndpoint",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedEvent",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedRead",
                "doc://com.apple.matter/documentation/Matter/MTRInteractionError/Code/unsupportedWrite"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRInteractionErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidAction/title",
          "value": "MTRInteractionErrorCodeInvalidAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeInvalidAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedWrite/title",
          "value": "MTRInteractionErrorCodeUnsupportedWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1timeout/title",
          "value": "MTRInteractionErrorCodeTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1timeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1needsTimedInteraction/title",
          "value": "MTRInteractionErrorCodeNeedsTimedInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1needsTimedInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeNeedsTimedInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidSubscription/title",
          "value": "MTRInteractionErrorCodeInvalidSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeInvalidSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code/title",
          "value": "MTRInteractionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedCommand/title",
          "value": "MTRInteractionErrorCodeUnsupportedCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedCluster/title",
          "value": "MTRInteractionErrorCodeUnsupportedCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1pathsExhausted/title",
          "value": "MTRInteractionErrorCodePathsExhausted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1pathsExhausted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodePathsExhausted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedEvent/title",
          "value": "MTRInteractionErrorCodeUnsupportedEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedAttribute/title",
          "value": "MTRInteractionErrorCodeUnsupportedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1dataVersionMismatch/title",
          "value": "MTRInteractionErrorCodeDataVersionMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1dataVersionMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeDataVersionMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1resourceExhausted/title",
          "value": "MTRInteractionErrorCodeResourceExhausted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1resourceExhausted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeResourceExhausted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1noUpstreamSubscription/title",
          "value": "MTRInteractionErrorCodeNoUpstreamSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1noUpstreamSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeNoUpstreamSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unreportableAttribute/title",
          "value": "MTRInteractionErrorCodeUnreportableAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unreportableAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnreportableAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1failure/title",
          "value": "MTRInteractionErrorCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedEndpoint/title",
          "value": "MTRInteractionErrorCodeUnsupportedEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1noCommandResponse/title",
          "value": "MTRInteractionErrorCodeNoCommandResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1noCommandResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeNoCommandResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedAccess/title",
          "value": "MTRInteractionErrorCodeUnsupportedAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1timedRequestMismatch/title",
          "value": "MTRInteractionErrorCodeTimedRequestMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1timedRequestMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeTimedRequestMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedRead/title",
          "value": "MTRInteractionErrorCodeUnsupportedRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1unsupportedRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeUnsupportedRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidInState/title",
          "value": "MTRInteractionErrorCodeInvalidInState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidInState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeInvalidInState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidDataType/title",
          "value": "MTRInteractionErrorCodeInvalidDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeInvalidDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidCommand/title",
          "value": "MTRInteractionErrorCodeInvalidCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1invalidCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeInvalidCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1notFound/title",
          "value": "MTRInteractionErrorCodeNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1notFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1constraintError/title",
          "value": "MTRInteractionErrorCodeConstraintError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1constraintError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeConstraintError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1busy/title",
          "value": "MTRInteractionErrorCodeBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1failsafeRequired/title",
          "value": "MTRInteractionErrorCodeFailsafeRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRInteractionError~1Code~1failsafeRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRInteractionErrorCodeFailsafeRequired"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrinteractionerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrinteractionerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
