{
  "abstract": [
    {
      "text": "The action performed by this attachment at the end of a rendering pass for a render command encoder.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLRenderPassAttachmentDescriptor(py)storeAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "storeAction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLStoreAction",
        "text": "MTLStoreAction"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "storeAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "storeAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "storeAction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLStoreAction",
              "text": "MTLStoreAction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions",
        "doc://com.apple.metal/documentation/Metal/storing-data-a-pass-makes-with-custom-sample-positions-for-a-subsequent-pass"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your app doesn’t need the data in the texture after completing the rendering pass, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " action.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Otherwise, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " action if the texture is directly stored or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " action if the texture is a multisampled texture.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In some feature sets, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " action to store and resolve the texture in a single rendering pass.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information, see:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/metal/metal-feature-set-tables.zip",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When the store action is either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property must be set to the texture to use as the target for the resolve action. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to specify the mipmap level, cube slice, and depth plane of the resolve texture, respectively.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For color render targets, the default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For depth or stencil render targets, the default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A render target that serves as the output destination for pixels generated by a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction": {
      "abstract": [
        {
          "text": "The action performed by this attachment at the start of a rendering pass for a render command encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLLoadAction",
          "text": "MTLLoadAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadAction"
        }
      ],
      "role": "symbol",
      "title": "loadAction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/loadaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane": {
      "abstract": [
        {
          "text": "The depth plane of the texture used for the multisample resolve action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveDepthPlane"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveDepthPlane"
        }
      ],
      "role": "symbol",
      "title": "resolveDepthPlane",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvedepthplane"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel": {
      "abstract": [
        {
          "text": "The mipmap level of the texture used for the multisample resolve action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveLevel"
        }
      ],
      "role": "symbol",
      "title": "resolveLevel",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvelevel"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice": {
      "abstract": [
        {
          "text": "The slice of the texture used for the multisample resolve action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveSlice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveSlice"
        }
      ],
      "role": "symbol",
      "title": "resolveSlice",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolveslice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture": {
      "abstract": [
        {
          "text": "The destination texture used when resolving multisampled texture data into single sample values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTexture"
        }
      ],
      "role": "symbol",
      "title": "resolveTexture",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvetexture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction": {
      "abstract": [
        {
          "text": "The action performed by this attachment at the end of a rendering pass for a render command encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreAction",
          "text": "MTLStoreAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeAction"
        }
      ],
      "role": "symbol",
      "title": "storeAction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/storeaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions": {
      "abstract": [
        {
          "text": "The options that modify the store action performed by this attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeActionOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreActionOptions",
          "text": "MTLStoreActionOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeActionOptions"
        }
      ],
      "role": "symbol",
      "title": "storeActionOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/storeactionoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction": {
      "abstract": [
        {
          "text": "Types of actions performed for an attachment at the end of a rendering pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStoreAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreAction"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare": {
      "abstract": [
        {
          "text": "The GPU has permission to discard the rendered contents of the attachment at the end of the render pass, replacing them with arbitrary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dontCare"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionDontCare"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.dontCare",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/dontcare"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve": {
      "abstract": [
        {
          "text": "The GPU resolves the multisampled data to one sample per pixel and stores the data to the resolve texture, discarding the multisample data afterwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multisampleResolve"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionMultisampleResolve"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.multisampleResolve",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/multisampleresolve"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store": {
      "abstract": [
        {
          "text": "The GPU stores the rendered contents to the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "store"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionStore"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.store",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/store"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve": {
      "abstract": [
        {
          "text": "The GPU stores the multisample data to the multisample texture, resolves the data to a sample per pixel, and stores the data to the resolve texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeAndMultisampleResolve"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionStoreAndMultisampleResolve"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.storeAndMultisampleResolve",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/storeandmultisampleresolve"
    },
    "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions": {
      "abstract": [
        {
          "text": "Set actions that define how a render pass loads and stores a render target.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions",
      "kind": "article",
      "role": "article",
      "title": "Setting Load and Store Actions",
      "type": "topic",
      "url": "/documentation/metal/setting-load-and-store-actions"
    },
    "doc://com.apple.metal/documentation/Metal/storing-data-a-pass-makes-with-custom-sample-positions-for-a-subsequent-pass": {
      "abstract": [
        {
          "text": "Inform Metal when your app uses programmable sample positions for its depth render targets or copies MSAA depth data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/storing-data-a-pass-makes-with-custom-sample-positions-for-a-subsequent-pass",
      "kind": "article",
      "role": "article",
      "title": "Storing Data a Pass Makes with Custom Sample Positions for a Subsequent Pass",
      "type": "topic",
      "url": "/documentation/metal/storing-data-a-pass-makes-with-custom-sample-positions-for-a-subsequent-pass"
    },
    "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf": {
      "identifier": "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf",
      "title": "Metal feature set tables (PDF)",
      "titleInlineContent": [
        {
          "text": "Metal feature set tables (PDF)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf"
    },
    "https://developer.apple.com/metal/metal-feature-set-tables.zip": {
      "identifier": "https://developer.apple.com/metal/metal-feature-set-tables.zip",
      "title": "Metal feature set tables (Numbers)",
      "titleInlineContent": [
        {
          "text": "Metal feature set tables (Numbers)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/metal/metal-feature-set-tables.zip"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Rendering-Pass-Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions"
      ],
      "title": "Specifying Rendering Pass Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "storeAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Rendering-Pass-Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions"
              ],
              "title": "Specifying Rendering Pass Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLStoreAction",
                    "text": "MTLStoreAction"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "storeAction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/title",
          "value": "MTLStoreAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1store/title",
          "value": "MTLStoreActionStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1store/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1dontCare/title",
          "value": "MTLStoreActionDontCare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1dontCare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionDontCare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveSlice/title",
          "value": "resolveSlice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveSlice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeActionOptions/title",
          "value": "storeActionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeActionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeActionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveLevel/title",
          "value": "resolveLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeAction/title",
          "value": "storeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1loadAction/title",
          "value": "loadAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1loadAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveTexture/title",
          "value": "resolveTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1multisampleResolve/title",
          "value": "MTLStoreActionMultisampleResolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1multisampleResolve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionMultisampleResolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/title",
          "value": "MTLRenderPassAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveDepthPlane/title",
          "value": "resolveDepthPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveDepthPlane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveDepthPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1storeAndMultisampleResolve/title",
          "value": "MTLStoreActionStoreAndMultisampleResolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1storeAndMultisampleResolve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionStoreAndMultisampleResolve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlrenderpassattachmentdescriptor/storeaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlrenderpassattachmentdescriptor/storeaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
