{
  "abstract": [
    {
      "text": "Evaluates a query request and provides a response describing how the system should handle the message it represents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling/handle(_:context:completion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ILMessageFilterCapabilitiesQueryHandling(im)handleCapabilitiesQueryRequest:context:completion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "handle"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryRequest",
        "text": "ILMessageFilterCapabilitiesQueryRequest"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "context"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ILMessageFilterExtensionContext",
        "text": "ILMessageFilterExtensionContext"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completion"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryResponse",
        "text": "ILMessageFilterCapabilitiesQueryResponse"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "handleCapabilitiesQueryRequest:context:completion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "handle(_:context:completion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "capabilitiesQueryRequest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryRequest",
              "text": "ILMessageFilterCapabilitiesQueryRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterExtensionContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILMessageFilterExtensionContext",
              "text": "ILMessageFilterExtensionContext"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryResponse",
              "text": "ILMessageFilterCapabilitiesQueryResponse"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "capabilitiesQueryRequest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryRequest",
              "text": "ILMessageFilterCapabilitiesQueryRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterExtensionContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILMessageFilterExtensionContext",
              "text": "ILMessageFilterExtensionContext"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryResponse",
              "text": "ILMessageFilterCapabilitiesQueryResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A query request that describes a received message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "capabilitiesQueryRequest"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The app extension context that defines APIs to defer the request to a server, if necessary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A completion block used to return a response that describes how to handle the message. You can invoke this block asynchronously.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completion"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling": {
      "abstract": [
        {
          "text": "A set of methods implemented by a Message Filter app extension to handle capabilities query requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryHandling"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryHandling"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterCapabilitiesQueryHandling",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryhandling"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling/handle(_:context:completion:)": {
      "abstract": [
        {
          "text": "Evaluates a query request and provides a response describing how the system should handle the message it represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryRequest",
          "text": "ILMessageFilterCapabilitiesQueryRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ILMessageFilterExtensionContext",
          "text": "ILMessageFilterExtensionContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryResponse",
          "text": "ILMessageFilterCapabilitiesQueryResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling/handle(_:context:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleCapabilitiesQueryRequest:context:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(_:context:completion:)",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryhandling/handle(_:context:completion:)"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryRequest": {
      "abstract": [
        {
          "text": "A request to query a Message Filter extension about sharing its sub-category capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryRequest"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryRequest"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterCapabilitiesQueryRequest",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryrequest"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse": {
      "abstract": [
        {
          "text": "A response to a message filter capabilities query request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryResponse"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryResponse"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterCapabilitiesQueryResponse",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryresponse"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterExtensionContext": {
      "abstract": [
        {
          "text": "The extension context for a Message Filter app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterExtensionContext",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefilterextensioncontext"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "handleCapabilitiesQueryRequest:context:completion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleCapabilitiesQueryRequest:context:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.identitylookup/documentation/IdentityLookup",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "handleCapabilitiesQueryRequest:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryRequest",
                    "text": "ILMessageFilterCapabilitiesQueryRequest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "capabilitiesQueryRequest"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "context:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterExtensionContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ILMessageFilterExtensionContext",
                    "text": "ILMessageFilterExtensionContext"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ILMessageFilterCapabilitiesQueryResponse",
                    "text": "ILMessageFilterCapabilitiesQueryResponse"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": ""
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A query request that describes a received message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "capabilitiesQueryRequest"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The app extension context that defines APIs to defer the request to a server, if necessary.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A completion block used to return a response that describes how to handle the message. You can invoke this block asynchronously.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryRequest/title",
          "value": "ILMessageFilterCapabilitiesQueryRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryHandling~1handle(_:context:completion:)/title",
          "value": "handleCapabilitiesQueryRequest:context:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryHandling~1handle(_:context:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleCapabilitiesQueryRequest:context:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryHandling/title",
          "value": "ILMessageFilterCapabilitiesQueryHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterExtensionContext/title",
          "value": "ILMessageFilterExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryResponse/title",
          "value": "ILMessageFilterCapabilitiesQueryResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryhandling/handle(_:context:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryhandling/handle(_:context:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
