{
  "abstract": [
    {
      "text": "An error that an App Clip activation payload returns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appclip/documentation/AppClip"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC28APActivationPayloadErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "APActivationPayloadError"
      }
    ],
    "modules": [
      {
        "name": "App Clips"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "APActivationPayloadError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "APActivationPayloadError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "APActivationPayloadError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appclip/documentation/AppClip": {
      "abstract": [
        {
          "text": "Provide people a shortcut to selected content and features of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip",
      "kind": "symbol",
      "role": "collection",
      "title": "App Clips",
      "type": "topic",
      "url": "/documentation/appclip"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError": {
      "abstract": [
        {
          "text": "An error that an App Clip activation payload returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "APActivationPayloadError"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APActivationPayloadError"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayloadError",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code": {
      "abstract": [
        {
          "text": "Error codes that an App Clip activation payload returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayloadError.Code",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/code"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/disallowed": {
      "abstract": [
        {
          "text": "The user denied location access, or the source of the App Clip invocation wasn’t an NFC tag or visual code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disallowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC28APActivationPayloadErrorCodeLeV",
          "text": "APActivationPayloadError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@APActivationPayloadErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/disallowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "disallowed",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/disallowed"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/doesNotMatch": {
      "abstract": [
        {
          "text": "The provided URL doesn’t match the invocation URL you registered for the App Clip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doesNotMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC28APActivationPayloadErrorCodeLeV",
          "text": "APActivationPayloadError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@APActivationPayloadErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/doesNotMatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "doesNotMatch",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/doesnotmatch"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/errordomain"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the activation payload’s error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "APActivationPayloadErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APActivationPayloadErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayloadErrorDomain",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadErrorDomain",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code"
      ],
      "title": "Error Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Information-About-the-Error",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/errorDomain"
      ],
      "title": "Getting Information About the Error"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/doesNotMatch",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/disallowed",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadErrorDomain/title",
          "value": "APActivationPayloadErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayloadErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadError~1Code/title",
          "value": "APActivationPayloadErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayloadErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayloadErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appclip/apactivationpayloaderror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
