{
  "abstract": [
    {
      "text": "Prepare your App Clip Codes to send to a professional printing service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appclip/documentation/AppClip"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appclip/documentation/AppClip/preparing-multiple-app-clip-codes-for-production"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "App Clips"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Preparing multiple App Clip Codes for production"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you create your App Clip Codes, you can print them yourself, or work with a professional printing service — for example, ",
              "type": "text"
            },
            {
              "identifier": "https://touchless.acc.rrd.com",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". However, if you have a lot of App Clip Codes, printing them yourself doesn’t scale well, and you’ll have more success working with a professional printing service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because you can’t see which invocation URL your App Clip Code contains just by looking at it, you need to keep track of your SVG files and their corresponding URLs. Careful file management, versioning, and change tracking are key to avoiding faulty print runs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional information, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/printing-guidelines/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Map-SVG-filenames-to-invocation-URLs",
          "level": 3,
          "text": "Map SVG filenames to invocation URLs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In general, it’s up to you to decide how to keep track of changes and which SVG files map to which invocation URLs. In most cases, a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "mapping file",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " that uses the comma-separated values (CSV) file format is the preferred option.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To reduce the risk of human error and simplify change tracking, consider using a single mapping file to create your SVG files before sending them to a printing service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re working with ",
              "type": "text"
            },
            {
              "identifier": "https://touchless.acc.rrd.com",
              "isActive": true,
              "overridingTitle": "RR Donnelley",
              "overridingTitleInlineContent": [
                {
                  "text": "RR Donnelley",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to produce App Clip Codes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a ZIP file that contains the SVG files for your App Clip Codes and the mapping file in its root folder.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The mapping file must be a CSV file with one field named ",
                      "type": "text"
                    },
                    {
                      "code": "SVG File Name",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and another named ",
                      "type": "text"
                    },
                    {
                      "code": "URL",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", with each row representing one App Clip Code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ZIP file may contain up to 10,000 SVG files, and the mapping file may contain up to 10,000 corresponding entries.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The maximum length for any filename (ZIP file, SVG files, or mapping file) is 188 characters.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows the contents of a mapping file with entries for two App Clip Codes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "SVG File Name, URL",
            "AppClipCode1.svg, https://example.com",
            "AppClipCode2.svg, https://appclip.example.com/"
          ],
          "syntax": "other",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appclip/documentation/AppClip": {
      "abstract": [
        {
          "text": "Provide people a shortcut to selected content and features of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip",
      "kind": "symbol",
      "role": "collection",
      "title": "App Clips",
      "type": "topic",
      "url": "/documentation/appclip"
    },
    "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes": {
      "abstract": [
        {
          "text": "Help users discover your App Clip by using an NFC-integrated or scan-only App Clip Code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes",
      "kind": "article",
      "role": "article",
      "title": "Creating App Clip Codes",
      "type": "topic",
      "url": "/documentation/appclip/creating-app-clip-codes"
    },
    "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar": {
      "abstract": [
        {
          "text": "Display content and provide services in an AR experience with App Clip Codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with App Clip Codes in AR",
      "type": "topic",
      "url": "/documentation/appclip/interacting-with-app-clip-codes-in-ar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/printing-guidelines/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/printing-guidelines/",
      "title": "Human Interface Guidelines > App Clips > Printing Guidelines",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > App Clips > Printing Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/printing-guidelines/"
    },
    "https://touchless.acc.rrd.com": {
      "identifier": "https://touchless.acc.rrd.com",
      "title": "RR Donnelley",
      "titleInlineContent": [
        {
          "text": "RR Donnelley",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://touchless.acc.rrd.com"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-Clip-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes",
        "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar"
      ],
      "title": "App Clip Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-Clip-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes",
                "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar"
              ],
              "title": "App Clip Codes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appclip/preparing-multiple-app-clip-codes-for-production"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appclip/preparing-multiple-app-clip-codes-for-production"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
