{
  "abstract": [
    {
      "text": "Constant indicating the user’s action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIWebViewNavigationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NavigationType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NavigationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIWebView.NavigationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NavigationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes": {
      "abstract": [
        {
          "text": "Constants that define the types of information to detect in text-based content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "UIDataDetectorTypes",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView": {
      "abstract": [
        {
          "text": "A view that embeds web content in your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "role": "symbol",
      "title": "UIWebView",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType": {
      "abstract": [
        {
          "text": "Constant indicating the user’s action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NavigationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NavigationType"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward": {
      "abstract": [
        {
          "text": "User tapped the back or forward button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeBackForward"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.backForward",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/backforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted": {
      "abstract": [
        {
          "text": "User resubmitted a form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formResubmitted"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeFormResubmitted"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.formResubmitted",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/formresubmitted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted": {
      "abstract": [
        {
          "text": "User submitted a form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSubmitted"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeFormSubmitted"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.formSubmitted",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/formsubmitted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked": {
      "abstract": [
        {
          "text": "User tapped a link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkClicked"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeLinkClicked"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.linkClicked",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/linkclicked"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other": {
      "abstract": [
        {
          "text": "Some other action occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeOther"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.other",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/other"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload": {
      "abstract": [
        {
          "text": "User tapped the reload button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeReload"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.reload",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/reload"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationBreakingMode-swift.enum": {
      "abstract": [
        {
          "text": "The manner in which column- or page-breaking occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaginationBreakingMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationBreakingMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaginationBreakingMode"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.PaginationBreakingMode",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/paginationbreakingmode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationMode-swift.enum": {
      "abstract": [
        {
          "text": "The layout of content in the web view, which determines the direction that the pages flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaginationMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaginationMode"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.PaginationMode",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/paginationmode-swift.enum"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationBreakingMode-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationMode-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIWebViewNavigationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationBreakingMode-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/PaginationMode-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIWebViewNavigationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1PaginationBreakingMode-swift.enum/title",
          "value": "UIWebPaginationBreakingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1PaginationBreakingMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebPaginationBreakingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1PaginationBreakingMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebPaginationBreakingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1backForward/title",
          "value": "UIWebViewNavigationTypeBackForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1backForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeBackForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formSubmitted/title",
          "value": "UIWebViewNavigationTypeFormSubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formSubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeFormSubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1linkClicked/title",
          "value": "UIWebViewNavigationTypeLinkClicked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1linkClicked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeLinkClicked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1other/title",
          "value": "UIWebViewNavigationTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType/title",
          "value": "UIWebViewNavigationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes/title",
          "value": "UIDataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formResubmitted/title",
          "value": "UIWebViewNavigationTypeFormResubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formResubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeFormResubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/title",
          "value": "UIWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1PaginationMode-swift.enum/title",
          "value": "UIWebPaginationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1PaginationMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebPaginationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1PaginationMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebPaginationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1reload/title",
          "value": "UIWebViewNavigationTypeReload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1reload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeReload"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwebview/navigationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwebview/navigationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
