{
  "abstract": [
    {
      "text": "Registers the specified vocabulary strings with the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INVocabulary(im)setVocabulary:ofType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setVocabulary"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSOrderedSet",
        "text": "NSOrderedSet"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "of"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INVocabularyStringType",
        "text": "INVocabularyStringType"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setVocabulary:ofType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setVocabulary(_:of:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setVocabulary"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vocabulary"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOrderedSet",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSOrderedSet",
              "text": "NSOrderedSet"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "of"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INVocabularyStringType",
              "text": "INVocabularyStringType"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The speakable content to associate with the specified ",
                  "type": "text"
                },
                {
                  "code": "type",
                  "type": "codeVoice"
                },
                {
                  "text": ". Each item should contain terms that are unique to your app and to the specific user. Sort the items in descending order of importance. In other words, the first item should be the most important, followed by items of decreasing importance. Each item must be no more than 1024 bytes in size.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vocabulary"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The designated purpose for the strings in the ",
                  "type": "text"
                },
                {
                  "code": "vocabulary",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter. You must specify one of the designated types. You cannot specify custom types of strings. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to register user-specific vocabulary terms of the specified type. You may register different sets of strings for each of the supported types, but you may register only one group of strings for each type. Calling this method again for a given type replaces the previously registered strings already assigned to that type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t use this method to register terminology that’s common to all users of your app. Use this method only to register terms that are specific to the current user. Include common terminology in the vocabulary property list file that you include with your Intents extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Calling this method isn’t a guarantee that Siri uses the terms you supply. If you specify more than just a few strings, Siri may ingest only the first few strings rather than the entire list. So always place the most important strings first in the ordered set. In addition, if any of the strings exceed the maximum size limit, Siri ignores them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It’s a programmer error to register terms that aren’t supported by any of your extension’s intents.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary": {
      "abstract": [
        {
          "text": "An object for registering user-specific vocabulary that Siri requests might include.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVocabulary"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabulary"
        }
      ],
      "role": "symbol",
      "title": "INVocabulary",
      "type": "topic",
      "url": "/documentation/intents/invocabulary"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()": {
      "abstract": [
        {
          "text": "Removes all user-specific vocabulary strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllVocabularyStrings"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllVocabularyStrings"
        }
      ],
      "role": "symbol",
      "title": "removeAllVocabularyStrings()",
      "type": "topic",
      "url": "/documentation/intents/invocabulary/removeallvocabularystrings()"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)": {
      "abstract": [
        {
          "text": "Registers the specified vocabulary strings with the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setVocabulary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOrderedSet",
          "text": "NSOrderedSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INVocabularyStringType",
          "text": "INVocabularyStringType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setVocabulary:ofType:"
        }
      ],
      "role": "symbol",
      "title": "setVocabulary(_:of:)",
      "type": "topic",
      "url": "/documentation/intents/invocabulary/setvocabulary(_:of:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)": {
      "abstract": [
        {
          "text": "Registers the specified vocabulary strings with the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setVocabularyStrings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOrderedSet",
          "text": "NSOrderedSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INVocabularyStringType",
          "text": "INVocabularyStringType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setVocabularyStrings:ofType:"
        }
      ],
      "role": "symbol",
      "title": "setVocabularyStrings(_:of:)",
      "type": "topic",
      "url": "/documentation/intents/invocabulary/setvocabularystrings(_:of:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType": {
      "abstract": [
        {
          "text": "Possible usages for a custom vocabulary term.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVocabularyStringType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringType"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app": {
      "abstract": [
        {
          "text": "Donate app-specific content, use Siri’s contact suggestions, and adopt the latest platform features to create a more consistent messaging experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Improving interactions between Siri and your messaging app",
      "type": "topic",
      "url": "/documentation/sirikit/improving-interactions-between-siri-and-your-messaging-app"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSOrderedSet": {
      "abstract": [
        {
          "text": "A static, ordered collection of unique objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSOrderedSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOrderedSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOrderedSet",
      "type": "topic",
      "url": "/documentation/foundation/nsorderedset"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-the-User-Specific-Vocabulary",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)",
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()"
      ],
      "title": "Updating the User-Specific Vocabulary"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setVocabulary:ofType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVocabulary:ofType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-the-User-Specific-Vocabulary",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)",
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()"
              ],
              "title": "Updating the User-Specific Vocabulary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setVocabulary:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSOrderedSet",
                    "text": "NSOrderedSet<id<INSpeakable>>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vocabulary"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ofType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INVocabularyStringType",
                    "text": "INVocabularyStringType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The speakable content to associate with the specified ",
                        "type": "text"
                      },
                      {
                        "code": "type",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". Each item should contain terms that are unique to your app and to the specific user. Sort the items in descending order of importance. In other words, the first item should be the most important, followed by items of decreasing importance. Each item must be no more than 1024 bytes in size.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vocabulary"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The designated purpose for the strings in the ",
                        "type": "text"
                      },
                      {
                        "code": "vocabulary",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter. You must specify one of the designated types. You cannot specify custom types of strings. For a list of possible values, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "type"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabulary(_:of:)/title",
          "value": "setVocabulary:ofType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabulary(_:of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVocabulary:ofType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabularyStrings(_:of:)/title",
          "value": "setVocabularyStrings:ofType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabularyStrings(_:of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVocabularyStrings:ofType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1removeAllVocabularyStrings()/title",
          "value": "removeAllVocabularyStrings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1removeAllVocabularyStrings()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllVocabularyStrings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType/title",
          "value": "INVocabularyStringType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary/title",
          "value": "INVocabulary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabulary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabulary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/invocabulary/setvocabulary(_:of:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/invocabulary/setvocabulary(_:of:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
