{
  "abstract": [
    {
      "text": "The number of subdivisions SceneKit uses to smooth the geometry’s surface at render time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNGeometry(py)subdivisionLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subdivisionLevel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "subdivisionLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "subdivisionLevel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subdivisionLevel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Surface subdivision",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a technique for using low-detail geometry to generate a smooth surface for rendering. When you increase the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value of a geometry, SceneKit automatically splits each face in the rendered surface, creating a more detailed, smoother geometry, as shown in . SceneKit performs this subdivision process at render time, preserving the original geometry data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2929791",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Subdividing a surface rounds away any sharp edges and corners in the geometry; however, such details may be important to a model’s design. To preserve edges, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to identify edges and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to specify how smooth or sharp they should appear after subdivision. To preserve corners, include a geometry source whose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource/semantic-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource/Semantic-swift.struct/vertexCrease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when creating the geometry.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default subdivision level is zero, specifying no subdivision—SceneKit renders the geometry exactly as its vertex data specifies.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry": {
      "abstract": [
        {
          "text": "A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometry",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement": {
      "abstract": [
        {
          "text": "The geometry element identifying which edges of the geometry’s surface should remain sharp after subdivision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgeCreasesElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometryElement",
          "text": "SCNGeometryElement"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "edgeCreasesElement"
        }
      ],
      "role": "symbol",
      "title": "edgeCreasesElement",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry/edgecreaseselement"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource": {
      "abstract": [
        {
          "text": "The geometry source specifying the smoothness or sharpness of edges after surface subdivision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgeCreasesSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "edgeCreasesSource"
        }
      ],
      "role": "symbol",
      "title": "edgeCreasesSource",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry/edgecreasessource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel": {
      "abstract": [
        {
          "text": "The number of subdivisions SceneKit uses to smooth the geometry’s surface at render time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subdivisionLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subdivisionLevel"
        }
      ],
      "role": "symbol",
      "title": "subdivisionLevel",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry/subdivisionlevel"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsAdaptiveSubdivision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsAdaptiveSubdivision"
        }
      ],
      "role": "symbol",
      "title": "wantsAdaptiveSubdivision",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry/wantsadaptivesubdivision"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource/Semantic-swift.struct/vertexCrease": {
      "abstract": [
        {
          "text": "The semantic for vertex crease data, used for subdividing surfaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexCrease"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNGeometrySourceSemantic",
          "text": "Semantic"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource/Semantic-swift.struct/vertexCrease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometrySourceSemanticVertexCrease"
        }
      ],
      "role": "symbol",
      "title": "vertexCrease",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometrysource/semantic-swift.struct/vertexcrease"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource/semantic-swift.property": {
      "abstract": [
        {
          "text": "The semantic value (or attribute) the geometry source describes for each vertex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semantic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNGeometrySourceSemantic",
          "text": "Semantic"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource/semantic-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "semantic"
        }
      ],
      "role": "symbol",
      "title": "semantic",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometrysource/semantic-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "media-2929791": {
      "alt": null,
      "identifier": "media-2929791",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/198634f31b7c2f613d42c06519779400/media-2929791@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Smoothing-and-Subdividing-Geometry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision"
      ],
      "title": "Smoothing and Subdividing Geometry"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "subdivisionLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subdivisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Smoothing-and-Subdividing-Geometry",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision"
              ],
              "title": "Smoothing and Subdividing Geometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "subdivisionLevel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title",
          "value": "SCNGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesSource/title",
          "value": "edgeCreasesSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "edgeCreasesSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource~1Semantic-swift.struct~1vertexCrease/title",
          "value": "SCNGeometrySourceSemanticVertexCrease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource~1Semantic-swift.struct~1vertexCrease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySourceSemanticVertexCrease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1subdivisionLevel/title",
          "value": "subdivisionLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1subdivisionLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subdivisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1wantsAdaptiveSubdivision/title",
          "value": "wantsAdaptiveSubdivision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1wantsAdaptiveSubdivision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsAdaptiveSubdivision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource~1semantic-swift.property/title",
          "value": "semantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource~1semantic-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "semantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesElement/title",
          "value": "edgeCreasesElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "edgeCreasesElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scngeometry/subdivisionlevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scngeometry/subdivisionlevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
