{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scngeometry/wantsadaptivesubdivision"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scngeometry/wantsadaptivesubdivision"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wantsAdaptiveSubdivision"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel","doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement","doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource"],"title":"Smoothing and Subdividing Geometry","generated":true,"anchor":"Smoothing-and-Subdividing-Geometry"}],"metadata":{"externalID":"c:objc(cs)SCNGeometry(py)wantsAdaptiveSubdivision","role":"symbol","navigatorTitle":[{"text":"wantsAdaptiveSubdivision","kind":"identifier"}],"modules":[{"name":"SceneKit"}],"roleHeading":"Instance Property","title":"wantsAdaptiveSubdivision","platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"11.0","beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"introducedAt":"11.0","beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"introducedAt":"10.13","beta":false,"name":"macOS"},{"unavailable":false,"deprecated":false,"introducedAt":"11.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"},{"unavailable":false,"deprecated":false,"introducedAt":"4.0","beta":false,"name":"watchOS"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wantsAdaptiveSubdivision","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource":{"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource","navigatorTitle":[{"text":"edgeCreasesSource","kind":"identifier"}],"type":"topic","title":"edgeCreasesSource","url":"/documentation/scenekit/scngeometry/edgecreasessource","kind":"symbol","abstract":[{"text":"The geometry source specifying the smoothness or sharpness of edges after surface subdivision.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeCreasesSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNGeometrySource","preciseIdentifier":"c:objc(cs)SCNGeometrySource","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision":{"title":"wantsAdaptiveSubdivision","url":"/documentation/scenekit/scngeometry/wantsadaptivesubdivision","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/wantsAdaptiveSubdivision","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"wantsAdaptiveSubdivision","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wantsAdaptiveSubdivision","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry":{"role":"symbol","kind":"symbol","title":"SCNGeometry","navigatorTitle":[{"text":"SCNGeometry","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNGeometry","kind":"identifier"}],"url":"/documentation/scenekit/scngeometry","abstract":[{"text":"A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement":{"abstract":[{"text":"The geometry element identifying which edges of the geometry’s surface should remain sharp after subdivision.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeCreasesElement"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SCNGeometryElement","kind":"typeIdentifier","text":"SCNGeometryElement"},{"kind":"text","text":"?"}],"role":"symbol","url":"/documentation/scenekit/scngeometry/edgecreaseselement","type":"topic","title":"edgeCreasesElement","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"edgeCreasesElement"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel":{"kind":"symbol","title":"subdivisionLevel","type":"topic","navigatorTitle":[{"text":"subdivisionLevel","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel","abstract":[{"text":"The number of subdivisions SceneKit uses to smooth the geometry’s surface at render time.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subdivisionLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"/documentation/scenekit/scngeometry/subdivisionlevel"},"doc://com.externally.resolved.symbol/s:Sb":{"type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"url":"/documentation/Swift/Bool","role":"symbol","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","role":"symbol","title":"BOOL"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1","unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.13","unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0","unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"introducedAt":"4.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"wantsAdaptiveSubdivision"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"wantsAdaptiveSubdivision"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Smoothing and Subdividing Geometry","generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/subdivisionLevel","doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesElement","doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/edgeCreasesSource"],"anchor":"Smoothing-and-Subdividing-Geometry"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"wantsAdaptiveSubdivision","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesSource/title","value":"edgeCreasesSource"},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesSource/fragments","value":[{"kind":"identifier","text":"edgeCreasesSource"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1wantsAdaptiveSubdivision/title","value":"wantsAdaptiveSubdivision"},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1wantsAdaptiveSubdivision/fragments","value":[{"kind":"identifier","text":"wantsAdaptiveSubdivision"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title","value":"SCNGeometry"},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments","value":[{"kind":"identifier","text":"SCNGeometry"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle","value":[{"text":"SCNGeometry","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesElement/title","value":"edgeCreasesElement"},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1edgeCreasesElement/fragments","value":[{"kind":"identifier","text":"edgeCreasesElement"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1subdivisionLevel/title","value":"subdivisionLevel"},{"value":[{"text":"subdivisionLevel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1subdivisionLevel/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}