{
  "abstract": [
    {
      "text": "Specifies automatic capitalization of the first letter of each sentence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/sentences"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITextAutocapitalizationType@UITextAutocapitalizationTypeSentences",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sentences"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextAutocapitalizationTypeSentences"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITextAutocapitalizationType.sentences"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sentences"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType": {
      "abstract": [
        {
          "text": "The autocapitalization behavior of a text-based view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextAutocapitalizationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextAutocapitalizationType"
        }
      ],
      "role": "symbol",
      "title": "UITextAutocapitalizationType",
      "type": "topic",
      "url": "/documentation/uikit/uitextautocapitalizationtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/allCharacters": {
      "abstract": [
        {
          "text": "Specifies automatic capitalization of all characters, such as for entry of two-character state abbreviations for the United States.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allCharacters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/allCharacters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextAutocapitalizationTypeAllCharacters"
        }
      ],
      "role": "symbol",
      "title": "UITextAutocapitalizationType.allCharacters",
      "type": "topic",
      "url": "/documentation/uikit/uitextautocapitalizationtype/allcharacters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/none": {
      "abstract": [
        {
          "text": "Specifies that there is no automatic text capitalization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextAutocapitalizationTypeNone"
        }
      ],
      "role": "symbol",
      "title": "UITextAutocapitalizationType.none",
      "type": "topic",
      "url": "/documentation/uikit/uitextautocapitalizationtype/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/sentences": {
      "abstract": [
        {
          "text": "Specifies automatic capitalization of the first letter of each sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentences"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/sentences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextAutocapitalizationTypeSentences"
        }
      ],
      "role": "symbol",
      "title": "UITextAutocapitalizationType.sentences",
      "type": "topic",
      "url": "/documentation/uikit/uitextautocapitalizationtype/sentences"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/words": {
      "abstract": [
        {
          "text": "Specifies automatic capitalization of the first letter of each word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "words"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/words",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextAutocapitalizationTypeWords"
        }
      ],
      "role": "symbol",
      "title": "UITextAutocapitalizationType.words",
      "type": "topic",
      "url": "/documentation/uikit/uitextautocapitalizationtype/words"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/none",
        "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/words",
        "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/allCharacters"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextAutocapitalizationTypeSentences"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationTypeSentences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/none",
                "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/words",
                "doc://com.apple.uikit/documentation/UIKit/UITextAutocapitalizationType/allCharacters"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITextAutocapitalizationTypeSentences"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1sentences/title",
          "value": "UITextAutocapitalizationTypeSentences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1sentences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationTypeSentences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1none/title",
          "value": "UITextAutocapitalizationTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1words/title",
          "value": "UITextAutocapitalizationTypeWords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1words/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationTypeWords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType/title",
          "value": "UITextAutocapitalizationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1allCharacters/title",
          "value": "UITextAutocapitalizationTypeAllCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextAutocapitalizationType~1allCharacters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextAutocapitalizationTypeAllCharacters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextautocapitalizationtype/sentences"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextautocapitalizationtype/sentences"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
