{
  "abstract": [
    {
      "text": "The event has a busy availability setting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/busy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKEventAvailability@EKEventAvailabilityBusy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "busy"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKEventAvailabilityBusy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKEventAvailability.busy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "busy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability": {
      "abstract": [
        {
          "text": "The event’s availability setting for scheduling purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventAvailability"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailability"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/busy": {
      "abstract": [
        {
          "text": "The event has a busy availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailabilityBusy"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability.busy",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability/busy"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/free": {
      "abstract": [
        {
          "text": "The event has a free availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "free"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/free",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailabilityFree"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability.free",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability/free"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/notSupported": {
      "abstract": [
        {
          "text": "Availability settings are not supported by the event’s calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailabilityNotSupported"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability.notSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability/notsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/tentative": {
      "abstract": [
        {
          "text": "The event has a tentative availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tentative"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/tentative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailabilityTentative"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability.tentative",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability/tentative"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/unavailable": {
      "abstract": [
        {
          "text": "The event has an unavailable availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailable"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/unavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailabilityUnavailable"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability.unavailable",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability/unavailable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/notSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/free",
        "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/tentative",
        "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/unavailable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKEventAvailabilityBusy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailabilityBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/notSupported",
                "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/free",
                "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/tentative",
                "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability/unavailable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKEventAvailabilityBusy"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1notSupported/title",
          "value": "EKEventAvailabilityNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailabilityNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1unavailable/title",
          "value": "EKEventAvailabilityUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1unavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailabilityUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability/title",
          "value": "EKEventAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1busy/title",
          "value": "EKEventAvailabilityBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailabilityBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1tentative/title",
          "value": "EKEventAvailabilityTentative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1tentative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailabilityTentative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1free/title",
          "value": "EKEventAvailabilityFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability~1free/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailabilityFree"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekeventavailability/busy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekeventavailability/busy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
