{
  "abstract": [
    {
      "text": "The physical input source doesn’t support directions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/GCPhysicalInputSourceDirectionNotApplicable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GCPhysicalInputSourceDirection@GCPhysicalInputSourceDirectionNotApplicable",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GCPhysicalInputSourceDirectionNotApplicable"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCPhysicalInputSourceDirectionNotApplicable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "GCPhysicalInputSourceDirectionNotApplicable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirectionNotApplicable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection": {
      "abstract": [
        {
          "text": "The directions that a physical input source involves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirection"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputSourceDirection",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputsourcedirection"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/GCPhysicalInputSourceDirectionNotApplicable": {
      "abstract": [
        {
          "text": "The physical input source doesn’t support directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirectionNotApplicable"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/GCPhysicalInputSourceDirectionNotApplicable",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputSourceDirectionNotApplicable",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputsourcedirection/gcphysicalinputsourcedirectionnotapplicable"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/down": {
      "abstract": [
        {
          "text": "The physical input source supports the down direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCPhysicalInputSourceDirection",
          "text": "GCPhysicalInputSourceDirection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirectionDown"
        }
      ],
      "role": "symbol",
      "title": "down",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputsourcedirection/down"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/left": {
      "abstract": [
        {
          "text": "The physical input source supports the left direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCPhysicalInputSourceDirection",
          "text": "GCPhysicalInputSourceDirection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirectionLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputsourcedirection/left"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/right": {
      "abstract": [
        {
          "text": "The physical input source supports the right direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCPhysicalInputSourceDirection",
          "text": "GCPhysicalInputSourceDirection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirectionRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputsourcedirection/right"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/up": {
      "abstract": [
        {
          "text": "The physical input source contains a value for the up direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCPhysicalInputSourceDirection",
          "text": "GCPhysicalInputSourceDirection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputSourceDirectionUp"
        }
      ],
      "role": "symbol",
      "title": "up",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputsourcedirection/up"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Directions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/up",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/right",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/down",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputSourceDirection/left"
      ],
      "title": "Directions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1left/title",
          "value": "GCPhysicalInputSourceDirectionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirectionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection/title",
          "value": "GCPhysicalInputSourceDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1up/title",
          "value": "GCPhysicalInputSourceDirectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1right/title",
          "value": "GCPhysicalInputSourceDirectionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirectionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1down/title",
          "value": "GCPhysicalInputSourceDirectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputSourceDirection~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputSourceDirectionDown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcphysicalinputsourcedirection/gcphysicalinputsourcedirectionnotapplicable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
