{
  "abstract": [
    {
      "text": "A value that indicates that the category of the session object changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionRouteChangeReason@AVAudioSessionRouteChangeReasonCategoryChange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "categoryChange"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionRouteChangeReasonCategoryChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioSession.RouteChangeReason.categoryChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "categoryChange"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason": {
      "abstract": [
        {
          "text": "Constants that indicate the reason for an audio route change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RouteChangeReason"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RouteChangeReason"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange": {
      "abstract": [
        {
          "text": "A value that indicates that the category of the session object changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoryChange"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonCategoryChange"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.categoryChange",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/categorychange"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable": {
      "abstract": [
        {
          "text": "A value that indicates a user action, such as plugging in a headset, has made a preferred audio route available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newDeviceAvailable"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonNewDeviceAvailable"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.newDeviceAvailable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/newdeviceavailable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory": {
      "abstract": [
        {
          "text": "A value that indicates that the route changed because no suitable route is now available for the specified category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuitableRouteForCategory"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.noSuitableRouteForCategory",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/nosuitablerouteforcategory"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable": {
      "abstract": [
        {
          "text": "A value that indicates that the previous audio output path is no longer available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oldDeviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonOldDeviceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.oldDeviceUnavailable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/olddeviceunavailable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override": {
      "abstract": [
        {
          "text": "A value that indicates that the output route was overridden by the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "override"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonOverride"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.override",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/override"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange": {
      "abstract": [
        {
          "text": "A value that indicates that the configuration for a set of I/O ports has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeConfigurationChange"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonRouteConfigurationChange"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.routeConfigurationChange",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/routeconfigurationchange"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown": {
      "abstract": [
        {
          "text": "A value that indicates the reason for the change is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonUnknown"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.unknown",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/unknown"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep": {
      "abstract": [
        {
          "text": "A value that indicates that the route changed when the device woke up from sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wakeFromSleep"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonWakeFromSleep"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.wakeFromSleep",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/wakefromsleep"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Route-Change-Reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange"
      ],
      "title": "Route Change Reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionRouteChangeReasonCategoryChange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonCategoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Route-Change-Reasons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange"
              ],
              "title": "Route Change Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionRouteChangeReasonCategoryChange"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason/title",
          "value": "AVAudioSessionRouteChangeReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1override/title",
          "value": "AVAudioSessionRouteChangeReasonOverride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1override/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonOverride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1routeConfigurationChange/title",
          "value": "AVAudioSessionRouteChangeReasonRouteConfigurationChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1routeConfigurationChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonRouteConfigurationChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1wakeFromSleep/title",
          "value": "AVAudioSessionRouteChangeReasonWakeFromSleep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1wakeFromSleep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonWakeFromSleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1noSuitableRouteForCategory/title",
          "value": "AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1noSuitableRouteForCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1oldDeviceUnavailable/title",
          "value": "AVAudioSessionRouteChangeReasonOldDeviceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1oldDeviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonOldDeviceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1unknown/title",
          "value": "AVAudioSessionRouteChangeReasonUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1newDeviceAvailable/title",
          "value": "AVAudioSessionRouteChangeReasonNewDeviceAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1newDeviceAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonNewDeviceAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1categoryChange/title",
          "value": "AVAudioSessionRouteChangeReasonCategoryChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1categoryChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonCategoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/routechangereason/categorychange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/routechangereason/categorychange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
