{
  "abstract": [
    {
      "text": "A status that indicates the screen’s in an accurate reference display mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIScreenReferenceDisplayModeStatus@UIScreenReferenceDisplayModeStatusEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "enabled"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIScreenReferenceDisplayModeStatusEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIScreen.ReferenceDisplayModeStatus.enabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen": {
      "abstract": [
        {
          "text": "An object that defines the properties associated with a hardware-based display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "role": "symbol",
      "title": "UIScreen",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum": {
      "abstract": [
        {
          "text": "Describes a screen’s reference display mode status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled": {
      "abstract": [
        {
          "text": "A status that indicates the screen’s in an accurate reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusEnabled"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.enabled",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/enabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited": {
      "abstract": [
        {
          "text": "A status that indicates the screen’s in a limited reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusLimited"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.limited",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/limited"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled": {
      "abstract": [
        {
          "text": "A status that indicates the screen provides a reference display mode but it’s in a disabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusNotEnabled"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.notEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/notenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported": {
      "abstract": [
        {
          "text": "A status that indicates the screen doesn’t provide a reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusNotSupported"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.notSupported",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/notsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited"
      ],
      "title": "Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIScreenReferenceDisplayModeStatusEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited"
              ],
              "title": "Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIScreenReferenceDisplayModeStatusEnabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notSupported/title",
          "value": "UIScreenReferenceDisplayModeStatusNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/title",
          "value": "UIScreenReferenceDisplayModeStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notEnabled/title",
          "value": "UIScreenReferenceDisplayModeStatusNotEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusNotEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1limited/title",
          "value": "UIScreenReferenceDisplayModeStatusLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1limited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1enabled/title",
          "value": "UIScreenReferenceDisplayModeStatusEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/title",
          "value": "UIScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/enabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/enabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
