{
  "abstract": [
    {
      "text": "The icon indicating an action to shuffle content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKMenuItemIcon@WKMenuItemIconShuffle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shuffle"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKMenuItemIconShuffle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKMenuItemIcon.shuffle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shuffle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon": {
      "abstract": [
        {
          "text": "Template images that you can use for menus.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKMenuItemIcon"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIcon"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept": {
      "abstract": [
        {
          "text": "The icon indicating an action to accept an event or item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accept"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconAccept"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.accept",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/accept"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add": {
      "abstract": [
        {
          "text": "The icon indicating an action for adding an item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconAdd"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.add",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/add"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block": {
      "abstract": [
        {
          "text": "The icon indicating an action to block or prevent something from happening.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "block"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconBlock"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.block",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/block"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline": {
      "abstract": [
        {
          "text": "The icon indicating an action to decline or cancel an event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decline"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconDecline"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.decline",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/decline"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info": {
      "abstract": [
        {
          "text": "The icon indicating an action to retrieve more information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconInfo"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.info",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/info"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe": {
      "abstract": [
        {
          "text": "The icon indicating an answer of maybe for an action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maybe"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconMaybe"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.maybe",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/maybe"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more": {
      "abstract": [
        {
          "text": "The icon indicating that more actions or options are available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "more"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconMore"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.more",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/more"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute": {
      "abstract": [
        {
          "text": "The icon indicating an action to mute the sound.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mute"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconMute"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.mute",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/mute"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause": {
      "abstract": [
        {
          "text": "The icon indicating an action to pause playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconPause"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.pause",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/pause"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play": {
      "abstract": [
        {
          "text": "The icon indicating an action to play some content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconPlay"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.play",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/play"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat": {
      "abstract": [
        {
          "text": "The icon indicating that played content should repeat in a loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconRepeat"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.repeat",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/repeat"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume": {
      "abstract": [
        {
          "text": "The icon indicating an action to resume playing some content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resume"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconResume"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.resume",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/resume"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share": {
      "abstract": [
        {
          "text": "The icon indicating an action to share content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "share"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconShare"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.share",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/share"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle": {
      "abstract": [
        {
          "text": "The icon indicating an action to shuffle content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shuffle"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconShuffle"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.shuffle",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/shuffle"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker": {
      "abstract": [
        {
          "text": "The icon indicating audio output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speaker"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconSpeaker"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.speaker",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/speaker"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash": {
      "abstract": [
        {
          "text": "The icon indicating an action to delete some content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trash"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconTrash"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.trash",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/trash"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKMenuItemIconShuffle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconShuffle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKMenuItemIconShuffle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1share/title",
          "value": "WKMenuItemIconShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1share/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1more/title",
          "value": "WKMenuItemIconMore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1more/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconMore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1play/title",
          "value": "WKMenuItemIconPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1decline/title",
          "value": "WKMenuItemIconDecline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1decline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconDecline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1repeat/title",
          "value": "WKMenuItemIconRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1add/title",
          "value": "WKMenuItemIconAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1trash/title",
          "value": "WKMenuItemIconTrash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1trash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconTrash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1info/title",
          "value": "WKMenuItemIconInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1speaker/title",
          "value": "WKMenuItemIconSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1speaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1mute/title",
          "value": "WKMenuItemIconMute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1mute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconMute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1resume/title",
          "value": "WKMenuItemIconResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1resume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1pause/title",
          "value": "WKMenuItemIconPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1accept/title",
          "value": "WKMenuItemIconAccept"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1accept/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconAccept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1shuffle/title",
          "value": "WKMenuItemIconShuffle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1shuffle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconShuffle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1maybe/title",
          "value": "WKMenuItemIconMaybe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1maybe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconMaybe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon/title",
          "value": "WKMenuItemIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1block/title",
          "value": "WKMenuItemIconBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1block/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkmenuitemicon/shuffle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkmenuitemicon/shuffle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
