{
  "abstract": [
    {
      "text": "The network request URL given by the ",
      "type": "text"
    },
    {
      "code": "ILMessageFilterExtensionNetworkURL",
      "type": "codeVoice"
    },
    {
      "text": " key in the app extension’s ",
      "type": "text"
    },
    {
      "code": "Info.plist",
      "type": "codeVoice"
    },
    {
      "text": " file is either missing or invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ILMessageFilterError@ILMessageFilterErrorInvalidNetworkURL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidNetworkURL"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ILMessageFilterErrorInvalidNetworkURL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ILMessageFilterError.Code.invalidNetworkURL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidNetworkURL"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with network requests and responses related to IdentityLookup APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterError"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterError"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code": {
      "abstract": [
        {
          "text": "IdentityLookup error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL": {
      "abstract": [
        {
          "text": "The network request URL given by the ",
          "type": "text"
        },
        {
          "code": "ILMessageFilterExtensionNetworkURL",
          "type": "codeVoice"
        },
        {
          "text": " key in the app extension’s ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file is either missing or invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNetworkURL"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorInvalidNetworkURL"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.invalidNetworkURL",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/invalidnetworkurl"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed": {
      "abstract": [
        {
          "text": "The network request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkRequestFailed"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorNetworkRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.networkRequestFailed",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/networkrequestfailed"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized": {
      "abstract": [
        {
          "text": "The app extension’s containing app isn’t authorized to allow the app extension to defer network requests to the host specified in its ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkURLUnauthorized"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorNetworkURLUnauthorized"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.networkURLUnauthorized",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/networkurlunauthorized"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral": {
      "abstract": [
        {
          "text": "The app extension tried to defer a request to its network service more than once, which isn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redundantNetworkDeferral"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorRedundantNetworkDeferral"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.redundantNetworkDeferral",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/redundantnetworkdeferral"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system": {
      "abstract": [
        {
          "text": "An unspecified system error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorSystem"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.system",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/system"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ILMessageFilterErrorInvalidNetworkURL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorInvalidNetworkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.identitylookup/documentation/IdentityLookup",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ILMessageFilterErrorInvalidNetworkURL"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkRequestFailed/title",
          "value": "ILMessageFilterErrorNetworkRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkRequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorNetworkRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1invalidNetworkURL/title",
          "value": "ILMessageFilterErrorInvalidNetworkURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1invalidNetworkURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorInvalidNetworkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1system/title",
          "value": "ILMessageFilterErrorSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1system/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/title",
          "value": "ILMessageFilterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkURLUnauthorized/title",
          "value": "ILMessageFilterErrorNetworkURLUnauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkURLUnauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorNetworkURLUnauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1redundantNetworkDeferral/title",
          "value": "ILMessageFilterErrorRedundantNetworkDeferral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1redundantNetworkDeferral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorRedundantNetworkDeferral"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/invalidnetworkurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/invalidnetworkurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
