{
  "abstract": [
    {
      "text": "The value that indicates the framework extends the selection by not moving the initial location while in a drag selection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/extend"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextSelectionNavigationModifier@NSTextSelectionNavigationModifierExtend",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extend"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
        "text": "NSTextSelectionNavigation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTextSelectionNavigationModifier",
        "text": "Modifier"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextSelectionNavigationModifierExtend"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "extend"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extend"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
              "text": "NSTextSelectionNavigation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTextSelectionNavigationModifier",
              "text": "Modifier"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation": {
      "abstract": [
        {
          "text": "An interface you use to expose methods for obtaining results from actions performed on text selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier": {
      "abstract": [
        {
          "text": "Values that describe how the framework handles different kinds of selection modifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Modifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Modifier"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Modifier",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/modifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/extend": {
      "abstract": [
        {
          "text": "The value that indicates the framework extends the selection by not moving the initial location while in a drag selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
          "text": "NSTextSelectionNavigation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionNavigationModifier",
          "text": "Modifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/extend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationModifierExtend"
        }
      ],
      "role": "symbol",
      "title": "extend",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/modifier/extend"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/multiple": {
      "abstract": [
        {
          "text": "The value that indicates the framework extends the selection visually inside the rectangular area defined by the anchor and dragged positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
          "text": "NSTextSelectionNavigation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionNavigationModifier",
          "text": "Modifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/multiple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationModifierMultiple"
        }
      ],
      "role": "symbol",
      "title": "multiple",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/modifier/multiple"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/visual": {
      "abstract": [
        {
          "text": "The value that indicates the framework extends the selection visually inside the rectangular area defined by the anchor and drag positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
          "text": "NSTextSelectionNavigation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionNavigationModifier",
          "text": "Modifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/visual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationModifierVisual"
        }
      ],
      "role": "symbol",
      "title": "visual",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/modifier/visual"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation-modifier-characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/multiple",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/visual"
      ],
      "title": "Navigation modifier characteristics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextSelectionNavigationModifierExtend"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifierExtend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation-modifier-characteristics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/multiple",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Modifier/visual"
              ],
              "title": "Navigation modifier characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextSelectionNavigationModifierExtend"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation/title",
          "value": "NSTextSelectionNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier/title",
          "value": "NSTextSelectionNavigationModifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier~1extend/title",
          "value": "NSTextSelectionNavigationModifierExtend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier~1extend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifierExtend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier~1multiple/title",
          "value": "NSTextSelectionNavigationModifierMultiple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier~1multiple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifierMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier~1visual/title",
          "value": "NSTextSelectionNavigationModifierVisual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Modifier~1visual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifierVisual"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextselectionnavigation/modifier/extend"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextselectionnavigation/modifier/extend"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
