{
  "abstract": [
    {
      "text": "A class that contains credentials for a Thread network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)THCredentials",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "THCredentials"
      }
    ],
    "modules": [
      {
        "name": "ThreadNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "THCredentials"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "THCredentials"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Thread network defines parameters that all connected devices use. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "provides these parameters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork": {
      "abstract": [
        {
          "text": "Share credentials and choose a designated network for each home.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "ThreadNetwork",
      "type": "topic",
      "url": "/documentation/threadnetwork"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient": {
      "abstract": [
        {
          "text": "A class that supports safely sharing Thread credentials between multiple clients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "THClient"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "THClient"
        }
      ],
      "role": "symbol",
      "title": "THClient",
      "type": "topic",
      "url": "/documentation/threadnetwork/thclient"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials": {
      "abstract": [
        {
          "text": "A class that contains credentials for a Thread network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "THCredentials"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "THCredentials"
        }
      ],
      "role": "symbol",
      "title": "THCredentials",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet": {
      "abstract": [
        {
          "text": "The essential operational parameters for the Thread network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeOperationalDataSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeOperationalDataSet"
        }
      ],
      "role": "symbol",
      "title": "activeOperationalDataSet",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/activeoperationaldataset"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID": {
      "abstract": [
        {
          "text": "The identifer of an active Thread network Border Agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderAgentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderAgentID"
        }
      ],
      "role": "symbol",
      "title": "borderAgentID",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/borderagentid"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel": {
      "abstract": [
        {
          "text": "The Thread network radio channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channel"
        }
      ],
      "role": "symbol",
      "title": "channel",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/channel"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/creationDate": {
      "abstract": [
        {
          "text": "The date and time that the framework stored the credential in the database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/creationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationDate"
        }
      ],
      "role": "symbol",
      "title": "creationDate",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/creationdate"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID": {
      "abstract": [
        {
          "text": "The Thread network extended PAN identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedPANID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedPANID"
        }
      ],
      "role": "symbol",
      "title": "extendedPANID",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/extendedpanid"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/lastModificationDate": {
      "abstract": [
        {
          "text": "The date and time that the framework updated the credential in the database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastModificationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/lastModificationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastModificationDate"
        }
      ],
      "role": "symbol",
      "title": "lastModificationDate",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/lastmodificationdate"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey": {
      "abstract": [
        {
          "text": "The Thread network key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkKey"
        }
      ],
      "role": "symbol",
      "title": "networkKey",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/networkkey"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName": {
      "abstract": [
        {
          "text": "The Thread network name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkName"
        }
      ],
      "role": "symbol",
      "title": "networkName",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/networkname"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID": {
      "abstract": [
        {
          "text": "The Thead network PAN identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panID"
        }
      ],
      "role": "symbol",
      "title": "panID",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/panid"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc": {
      "abstract": [
        {
          "text": "The Thread network pre-shared key for the Commissioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pskc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PSKC"
        }
      ],
      "role": "symbol",
      "title": "pskc",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/pskc"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use ThreadNetwork.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.networking.manage-thread-network-credentials",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-clients-and-sharing-credentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient"
      ],
      "title": "Managing clients and sharing credentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Thread-Parameters",
      "identifiers": [
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc"
      ],
      "title": "Getting the Thread Parameters"
    },
    {
      "anchor": "Getting-the-Framework-Parameters",
      "identifiers": [
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/creationDate",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/lastModificationDate"
      ],
      "title": "Getting the Framework Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "THCredentials"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Thread-Parameters",
              "identifiers": [
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc"
              ],
              "title": "Getting the Thread Parameters"
            },
            {
              "anchor": "Getting-the-Framework-Parameters",
              "identifiers": [
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/creationDate",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/lastModificationDate"
              ],
              "title": "Getting the Framework Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-clients-and-sharing-credentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THClient"
              ],
              "title": "Managing clients and sharing credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "THCredentials"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1panID/title",
          "value": "panID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1panID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "panID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkKey/title",
          "value": "networkKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1activeOperationalDataSet/title",
          "value": "activeOperationalDataSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1activeOperationalDataSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeOperationalDataSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1channel/title",
          "value": "channel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1borderAgentID/title",
          "value": "borderAgentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1borderAgentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderAgentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1creationDate/title",
          "value": "creationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1creationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1lastModificationDate/title",
          "value": "lastModificationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1lastModificationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastModificationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1extendedPANID/title",
          "value": "extendedPANID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1extendedPANID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedPANID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials/title",
          "value": "THCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient/title",
          "value": "THClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "THClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "THClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1pskc/title",
          "value": "PSKC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1pskc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PSKC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkName/title",
          "value": "networkName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/threadnetwork/thcredentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/threadnetwork/thcredentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
