{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mailkit/documentation/MailKit/mailkit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MailKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEComposeSessionError/Code": {
      "abstract": [
        {
          "text": "Errors that indicate invalid compose session states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEComposeSessionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MEComposeSessionError.Code",
      "type": "topic",
      "url": "/documentation/mailkit/mecomposesessionerror/code"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEComposeUserAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEComposeUserAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEComposeUserAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEComposeUserAction"
        }
      ],
      "role": "symbol",
      "title": "MEComposeUserAction",
      "type": "topic",
      "url": "/documentation/mailkit/mecomposeuseraction"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Flag"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Flag"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.Flag",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/flag"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncryptionState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageEncryptionState"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncryptionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageEncryptionState"
        }
      ],
      "role": "symbol",
      "title": "MEMessageEncryptionState",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencryptionstate"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MEMessageSecurityError.Code",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityerror/code"
    },
    "doc://com.apple.mailkit/documentation/MailKit/mailkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/mailkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MailKit Constants",
      "type": "topic",
      "url": "/documentation/mailkit/mailkit-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/mailkit-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEComposeSessionError/Code",
        "doc://com.apple.mailkit/documentation/MailKit/MEComposeUserAction",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncryptionState",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityError/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1Flag/title",
          "value": "MEMessageActionFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1Flag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1Flag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityError~1Code/title",
          "value": "MEMessageSecurityErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeUserAction/title",
          "value": "MEComposeUserAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeUserAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeUserAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeUserAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeUserAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncryptionState/title",
          "value": "MEMessageEncryptionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncryptionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncryptionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncryptionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncryptionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeSessionError~1Code/title",
          "value": "MEComposeSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeSessionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeSessionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeSessionErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/mailkit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
