{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEEmailAddress",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEEmailAddress"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEEmailAddress"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MEEmailAddress"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEEmailAddress"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEComposeContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEComposeContext"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEComposeContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEComposeContext"
        }
      ],
      "role": "symbol",
      "title": "MEComposeContext",
      "type": "topic",
      "url": "/documentation/mailkit/mecomposecontext"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessageBanner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEDecodedMessageBanner"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessageBanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEDecodedMessageBanner"
        }
      ],
      "role": "symbol",
      "title": "MEDecodedMessageBanner",
      "type": "topic",
      "url": "/documentation/mailkit/medecodedmessagebanner"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEEmailAddress"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEEmailAddress"
        }
      ],
      "role": "symbol",
      "title": "MEEmailAddress",
      "type": "topic",
      "url": "/documentation/mailkit/meemailaddress"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/addressString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/addressString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressString"
        }
      ],
      "role": "symbol",
      "title": "addressString",
      "type": "topic",
      "url": "/documentation/mailkit/meemailaddress/addressstring"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/init(rawString:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/init(rawString:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRawString:"
        }
      ],
      "role": "symbol",
      "title": "init(rawString:)",
      "type": "topic",
      "url": "/documentation/mailkit/meemailaddress/init(rawstring:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/rawString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/rawString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rawString"
        }
      ],
      "role": "symbol",
      "title": "rawString",
      "type": "topic",
      "url": "/documentation/mailkit/meemailaddress/rawstring"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEExtensionManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEExtensionManager"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtensionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEExtensionManager"
        }
      ],
      "role": "symbol",
      "title": "MEExtensionManager",
      "type": "topic",
      "url": "/documentation/mailkit/meextensionmanager"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEComposeContext",
        "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessageBanner",
        "doc://com.apple.mailkit/documentation/MailKit/MEExtensionManager"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/init(rawString:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/addressString",
        "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/rawString"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEEmailAddress"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/init(rawString:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/addressString",
                "doc://com.apple.mailkit/documentation/MailKit/MEEmailAddress/rawString"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEComposeContext",
                "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessageBanner",
                "doc://com.apple.mailkit/documentation/MailKit/MEExtensionManager"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEEmailAddress"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEDecodedMessageBanner/title",
          "value": "MEDecodedMessageBanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEDecodedMessageBanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodedMessageBanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEDecodedMessageBanner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodedMessageBanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress/title",
          "value": "MEEmailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtensionManager/title",
          "value": "MEExtensionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtensionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtensionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress~1init(rawString:)/title",
          "value": "initWithRawString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress~1init(rawString:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRawString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress~1addressString/title",
          "value": "addressString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress~1addressString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeContext/title",
          "value": "MEComposeContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress~1rawString/title",
          "value": "rawString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEmailAddress~1rawString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rawString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/meemailaddress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/meemailaddress"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
