{
  "abstract": [
    {
      "text": "A type that provides objects for manipulating email messages, such as performing actions on messages or blocking content when users view messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEExtension"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MEExtension",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEExtension"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEExtension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MEExtension"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEExtension"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To implement an app extension, you provide an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key of your extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " defines the capabilities that you support, as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>NSExtensionAttributes</key>",
            "<dict>",
            "    <key>MEExtensionCapabilities</key>",
            "    <array>",
            "        <string>MEContentBlocker</string>",
            "        <string>MEMessageActionHandler</string>",
            "        <string>MEComposeSessionHandler</string>",
            "        <string>MEMessageSecurityHandler</string>",
            "    </array>",
            "</dict>"
          ],
          "syntax": "plist",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For each capability that your extension defines, you provide an object that implements the capability. MailKit uses the following methods to request the object for a given capability. The capability also specifies a protocol that the handler implements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Capability Key",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Method",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Protocol",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "MEContentBlocker",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handler(for:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEContentBlocker",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "MEMessageActionHandler",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageActions()",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "MEComposeSessionHandler",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForContentBlocker()",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEComposeSessionHandler",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "MEMessageSecurityHandler",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageSecurity()",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "MEExtensionCapabilities",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEComposeSessionHandler": {
      "abstract": [
        {
          "text": "An object that participates in the composition of mail messages, and annotates recipient tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEComposeSessionHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEComposeSessionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEComposeSessionHandler"
        }
      ],
      "role": "symbol",
      "title": "MEComposeSessionHandler",
      "type": "topic",
      "url": "/documentation/mailkit/mecomposesessionhandler"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEContentBlocker": {
      "abstract": [
        {
          "text": "An object that provides a set of rules to block content when displaying a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEContentBlocker"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEContentBlocker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEContentBlocker"
        }
      ],
      "role": "symbol",
      "title": "MEContentBlocker",
      "type": "topic",
      "url": "/documentation/mailkit/mecontentblocker"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEExtension": {
      "abstract": [
        {
          "text": "A type that provides objects for manipulating email messages, such as performing actions on messages or blocking content when users view messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEExtension"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEExtension"
        }
      ],
      "role": "symbol",
      "title": "MEExtension",
      "type": "topic",
      "url": "/documentation/mailkit/meextension"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handler(for:)": {
      "abstract": [
        {
          "text": "Returns an object that participates in the composition of a mail message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEComposeSession",
          "text": "MEComposeSession"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MEComposeSessionHandler",
          "text": "MEComposeSessionHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handler(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerForComposeSession:"
        }
      ],
      "role": "symbol",
      "title": "handler(for:)",
      "type": "topic",
      "url": "/documentation/mailkit/meextension/handler(for:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForContentBlocker()": {
      "abstract": [
        {
          "text": "Returns an object that provides rules that the message viewer uses to block content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handlerForContentBlocker"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MEContentBlocker",
          "text": "MEContentBlocker"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForContentBlocker()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerForContentBlocker"
        }
      ],
      "role": "symbol",
      "title": "handlerForContentBlocker()",
      "type": "topic",
      "url": "/documentation/mailkit/meextension/handlerforcontentblocker()"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageActions()": {
      "abstract": [
        {
          "text": "Returns an object that performs actions on mail messages as the system downloads them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handlerForMessageActions"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MEMessageActionHandler",
          "text": "MEMessageActionHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageActions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerForMessageActions"
        }
      ],
      "role": "symbol",
      "title": "handlerForMessageActions()",
      "type": "topic",
      "url": "/documentation/mailkit/meextension/handlerformessageactions()"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageSecurity()": {
      "abstract": [
        {
          "text": "Returns an object that applies security measures such as encryption and digital signatures to messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handlerForMessageSecurity"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MEMessageSecurityHandler",
          "text": "MEMessageSecurityHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageSecurity()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerForMessageSecurity"
        }
      ],
      "role": "symbol",
      "title": "handlerForMessageSecurity()",
      "type": "topic",
      "url": "/documentation/mailkit/meextension/handlerformessagesecurity()"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler": {
      "abstract": [
        {
          "text": "An object that performs actions on messages as the system downloads them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageActionHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionHandler"
        }
      ],
      "role": "symbol",
      "title": "MEMessageActionHandler",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactionhandler"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler": {
      "abstract": [
        {
          "text": "An object that digitally signs or encrypts messages the user sends and receives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageSecurityHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageSecurityHandler"
        }
      ],
      "role": "symbol",
      "title": "MEMessageSecurityHandler",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityhandler"
    },
    "doc://com.apple.mailkit/documentation/MailKit/build-mail-app-extensions": {
      "abstract": [
        {
          "text": "Create app extensions that block content, perform message and composing actions, and help message security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/build-mail-app-extensions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Build Mail App Extensions",
      "type": "topic",
      "url": "/documentation/mailkit/build-mail-app-extensions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/build-mail-app-extensions"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Blocking-Content",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForContentBlocker()"
      ],
      "title": "Blocking Content"
    },
    {
      "anchor": "Performing-Actions-on-Messages",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageActions()"
      ],
      "title": "Performing Actions on Messages"
    },
    {
      "anchor": "Enhancing-the-Compose-Window",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handler(for:)"
      ],
      "title": "Enhancing the Compose Window"
    },
    {
      "anchor": "Encrypting-and-Signing-Messages",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageSecurity()"
      ],
      "title": "Encrypting and Signing Messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEExtension"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Blocking-Content",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForContentBlocker()"
              ],
              "title": "Blocking Content"
            },
            {
              "anchor": "Performing-Actions-on-Messages",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageActions()"
              ],
              "title": "Performing Actions on Messages"
            },
            {
              "anchor": "Enhancing-the-Compose-Window",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handler(for:)"
              ],
              "title": "Enhancing the Compose Window"
            },
            {
              "anchor": "Encrypting-and-Signing-Messages",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEExtension/handlerForMessageSecurity()"
              ],
              "title": "Encrypting and Signing Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/build-mail-app-extensions"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEExtension"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handlerForContentBlocker()/title",
          "value": "handlerForContentBlocker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handlerForContentBlocker()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handlerForContentBlocker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handler(for:)/title",
          "value": "handlerForComposeSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handler(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handlerForComposeSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEContentBlocker/title",
          "value": "MEContentBlocker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEContentBlocker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEContentBlocker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEContentBlocker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEContentBlocker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handlerForMessageSecurity()/title",
          "value": "handlerForMessageSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handlerForMessageSecurity()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handlerForMessageSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handlerForMessageActions()/title",
          "value": "handlerForMessageActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension~1handlerForMessageActions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handlerForMessageActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension/title",
          "value": "MEExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityHandler/title",
          "value": "MEMessageSecurityHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler/title",
          "value": "MEMessageActionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeSessionHandler/title",
          "value": "MEComposeSessionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeSessionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeSessionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEComposeSessionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeSessionHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/meextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/meextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
