{
  "abstract": [
    {
      "text": "An action the system performs on a message, such as setting a color or archiving it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEMessageAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEMessageAction"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEMessageAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MEMessageAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction": {
      "abstract": [
        {
          "text": "An action the system performs on a message, such as setting a color or archiving it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageAction"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Flag"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Flag"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.Flag",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/flag"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor": {
      "abstract": [
        {
          "text": "A color that the system uses to display a message in the message list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageColor"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageColor"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/flag(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEMessageActionFlag",
          "text": "Flag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/flag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flagActionWithFlag:"
        }
      ],
      "role": "symbol",
      "title": "flag(_:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/flag(_:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsRead": {
      "abstract": [
        {
          "text": "An object that marks the message as read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markAsRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "markAsReadAction"
        }
      ],
      "role": "symbol",
      "title": "markAsRead",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/markasread"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsUnread": {
      "abstract": [
        {
          "text": "An object that marks the message as unread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markAsUnread"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsUnread",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "markAsUnreadAction"
        }
      ],
      "role": "symbol",
      "title": "markAsUnread",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/markasunread"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToArchive": {
      "abstract": [
        {
          "text": "An object that moves the message to the account’s Archive mailbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveToArchive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToArchive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveToArchiveAction"
        }
      ],
      "role": "symbol",
      "title": "moveToArchive",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/movetoarchive"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToJunk": {
      "abstract": [
        {
          "text": "An object that moves the message to the account’s Junk mailbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveToJunk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToJunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveToJunkAction"
        }
      ],
      "role": "symbol",
      "title": "moveToJunk",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/movetojunk"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToTrash": {
      "abstract": [
        {
          "text": "An object that moves the message to the account’s Trash mailbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveToTrash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToTrash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveToTrashAction"
        }
      ],
      "role": "symbol",
      "title": "moveToTrash",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/movetotrash"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/setBackgroundColor(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBackgroundColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageAction",
          "text": "MEMessageAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEMessageActionMessageColor",
          "text": "MessageColor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/setBackgroundColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBackgroundColorActionWithColor:"
        }
      ],
      "role": "symbol",
      "title": "setBackgroundColor(_:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/setbackgroundcolor(_:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision": {
      "abstract": [
        {
          "text": "The action that the system performs on a message, or a request to ask the action handler again later when the message content is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageActionDecision"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionDecision"
        }
      ],
      "role": "symbol",
      "title": "MEMessageActionDecision",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactiondecision"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Determines the action that the system takes when it downloads a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decideAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessage",
          "text": "MEMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
          "text": "MEMessageActionDecision"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decideActionForMessage:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "decideAction(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactionhandler/decideaction(for:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Actions-on-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
      ],
      "title": "Performing Actions on Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Changing-the-Read-Status",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsRead",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsUnread"
      ],
      "title": "Changing the Read Status"
    },
    {
      "anchor": "Transferring-Messages",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToArchive",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToJunk",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToTrash"
      ],
      "title": "Transferring Messages"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/flag(_:)",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/setBackgroundColor(_:)"
      ],
      "title": "Type Methods"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEMessageAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Changing-the-Read-Status",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsRead",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/markAsUnread"
              ],
              "title": "Changing the Read Status"
            },
            {
              "anchor": "Transferring-Messages",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToArchive",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToJunk",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/moveToTrash"
              ],
              "title": "Transferring Messages"
            },
            {
              "anchor": "Type-Methods",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/flag(_:)",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/setBackgroundColor(_:)"
              ],
              "title": "Type Methods"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/Flag",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Actions-on-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
              ],
              "title": "Performing Actions on Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEMessageAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/title",
          "value": "MEMessageActionMessageColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1Flag/title",
          "value": "MEMessageActionFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1Flag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1Flag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler~1decideAction(for:completionHandler:)/title",
          "value": "decideActionForMessage:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler~1decideAction(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decideActionForMessage:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1moveToTrash/title",
          "value": "moveToTrashAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1moveToTrash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "moveToTrashAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1moveToJunk/title",
          "value": "moveToJunkAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1moveToJunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "moveToJunkAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1flag(_:)/title",
          "value": "flagActionWithFlag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1flag(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "flagActionWithFlag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/title",
          "value": "MEMessageAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1markAsUnread/title",
          "value": "markAsUnreadAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1markAsUnread/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "markAsUnreadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1moveToArchive/title",
          "value": "moveToArchiveAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1moveToArchive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "moveToArchiveAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision/title",
          "value": "MEMessageActionDecision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionDecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionDecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1markAsRead/title",
          "value": "markAsReadAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1markAsRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "markAsReadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1setBackgroundColor(_:)/title",
          "value": "setBackgroundColorActionWithColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1setBackgroundColor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setBackgroundColorActionWithColor:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/memessageaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/memessageaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
