{
  "abstract": [
    {
      "text": "An object that encrypts or digitally signs outgoing messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MEMessageEncoder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEMessageEncoder"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEMessageEncoder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MEMessageEncoder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage": {
      "abstract": [
        {
          "text": "An object that contains the signed or encrypted representation of a message’s RFC 2822 data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEEncodedOutgoingMessage"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEEncodedOutgoingMessage"
        }
      ],
      "role": "symbol",
      "title": "MEEncodedOutgoingMessage",
      "type": "topic",
      "url": "/documentation/mailkit/meencodedoutgoingmessage"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder": {
      "abstract": [
        {
          "text": "An object that encrypts or digitally signs outgoing messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageEncoder"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageEncoder"
        }
      ],
      "role": "symbol",
      "title": "MEMessageEncoder",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencoder"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/encode(_:composeContext:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessage",
          "text": "MEMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "composeContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEComposeContext",
          "text": "MEComposeContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageEncodingResult",
          "text": "MEMessageEncodingResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/encode(_:composeContext:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodeMessage:composeContext:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "encode(_:composeContext:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencoder/encode(_:composecontext:completionhandler:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/getEncodingStatus(for:composeContext:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getEncodingStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessage",
          "text": "MEMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "composeContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEComposeContext",
          "text": "MEComposeContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEOutgoingMessageEncodingStatus",
          "text": "MEOutgoingMessageEncodingStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/getEncodingStatus(for:composeContext:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getEncodingStatusForMessage:composeContext:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "getEncodingStatus(for:composeContext:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencoder/getencodingstatus(for:composecontext:completionhandler:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult": {
      "abstract": [
        {
          "text": "An object that contains a signed or encrypted message, or errors that indicate failure to encode the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageEncodingResult"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageEncodingResult"
        }
      ],
      "role": "symbol",
      "title": "MEMessageEncodingResult",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler": {
      "abstract": [
        {
          "text": "An object that digitally signs or encrypts messages the user sends and receives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageSecurityHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageSecurityHandler"
        }
      ],
      "role": "symbol",
      "title": "MEMessageSecurityHandler",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityhandler"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus": {
      "abstract": [
        {
          "text": "An object that contains information about security measures the user can apply when composing a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEOutgoingMessageEncodingStatus"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEOutgoingMessageEncodingStatus"
        }
      ],
      "role": "symbol",
      "title": "MEOutgoingMessageEncodingStatus",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encrypting-and-Signing-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult"
      ],
      "title": "Encrypting and Signing Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/encode(_:composeContext:completionHandler:)",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/getEncodingStatus(for:composeContext:completionHandler:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEMessageEncoder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/encode(_:composeContext:completionHandler:)",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder/getEncodingStatus(for:composeContext:completionHandler:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityHandler"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encrypting-and-Signing-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult"
              ],
              "title": "Encrypting and Signing Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEMessageEncoder"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/title",
          "value": "MEOutgoingMessageEncodingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/title",
          "value": "MEEncodedOutgoingMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEncodedOutgoingMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEncodedOutgoingMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder/title",
          "value": "MEMessageEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/title",
          "value": "MEMessageEncodingResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncodingResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncodingResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder~1getEncodingStatus(for:composeContext:completionHandler:)/title",
          "value": "getEncodingStatusForMessage:composeContext:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder~1getEncodingStatus(for:composeContext:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getEncodingStatusForMessage:composeContext:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder~1encode(_:composeContext:completionHandler:)/title",
          "value": "encodeMessage:composeContext:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder~1encode(_:composeContext:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encodeMessage:composeContext:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityHandler/title",
          "value": "MEMessageSecurityHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/memessageencoder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/memessageencoder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
