{
  "abstract": [
    {
      "text": "An object that contains details about a message’s content, such as if it’s encrypted and who digitally signed it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEMessageSecurityInformation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEMessageSecurityInformation"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEMessageSecurityInformation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MEMessageSecurityInformation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEMessageSecurityInformation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessage": {
      "abstract": [
        {
          "text": "An object that contains the RFC 2822 data for a message, without encryption or digital signatures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEDecodedMessage"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEDecodedMessage"
        }
      ],
      "role": "symbol",
      "title": "MEDecodedMessage",
      "type": "topic",
      "url": "/documentation/mailkit/medecodedmessage"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageDecoder": {
      "abstract": [
        {
          "text": "An object that decrypts messages and provides details about digital signatures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageDecoder"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageDecoder"
        }
      ],
      "role": "symbol",
      "title": "MEMessageDecoder",
      "type": "topic",
      "url": "/documentation/mailkit/memessagedecoder"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation": {
      "abstract": [
        {
          "text": "An object that contains details about a message’s content, such as if it’s encrypted and who digitally signed it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageSecurityInformation"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageSecurityInformation"
        }
      ],
      "role": "symbol",
      "title": "MEMessageSecurityInformation",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/encryptionError": {
      "abstract": [
        {
          "text": "An error that indicates the security handler couldn’t decrypt the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/encryptionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionError"
        }
      ],
      "role": "symbol",
      "title": "encryptionError",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/encryptionerror"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:)": {
      "abstract": [
        {
          "text": "Creates a message security information object that indicates if a message is encrypted, who signed it, or if an error occurred when decoding the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "signers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageSigner",
          "text": "MEMessageSigner"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "isEncrypted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signingError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "encryptionError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSigners:isEncrypted:signingError:encryptionError:"
        }
      ],
      "role": "symbol",
      "title": "init(signers:isEncrypted:signingError:encryptionError:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/init(signers:isencrypted:signingerror:encryptionerror:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "signers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageSigner",
          "text": "MEMessageSigner"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "isEncrypted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signingError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "encryptionError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "shouldBlockRemoteContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedRemoteContentBlockingReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSigners:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:"
        }
      ],
      "role": "symbol",
      "title": "init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/init(signers:isencrypted:signingerror:encryptionerror:shouldblockremotecontent:localizedremotecontentblockingreason:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/isEncrypted": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the sender encrypted the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEncrypted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/isEncrypted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEncrypted"
        }
      ],
      "role": "symbol",
      "title": "isEncrypted",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/isencrypted"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/localizedRemoteContentBlockingReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedRemoteContentBlockingReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/localizedRemoteContentBlockingReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedRemoteContentBlockingReason"
        }
      ],
      "role": "symbol",
      "title": "localizedRemoteContentBlockingReason",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/localizedremotecontentblockingreason"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/shouldBlockRemoteContent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldBlockRemoteContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/shouldBlockRemoteContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldBlockRemoteContent"
        }
      ],
      "role": "symbol",
      "title": "shouldBlockRemoteContent",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/shouldblockremotecontent"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signers": {
      "abstract": [
        {
          "text": "An array of objects that contain information about who signed the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageSigner",
          "text": "MEMessageSigner"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signers"
        }
      ],
      "role": "symbol",
      "title": "signers",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/signers"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signingError": {
      "abstract": [
        {
          "text": "An error that indicates the security handler couldn’t decode the message’s digital signatures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signingError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signingError"
        }
      ],
      "role": "symbol",
      "title": "signingError",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesecurityinformation/signingerror"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageSigner": {
      "abstract": [
        {
          "text": "An object that contains details about the person who signed a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageSigner"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageSigner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageSigner"
        }
      ],
      "role": "symbol",
      "title": "MEMessageSigner",
      "type": "topic",
      "url": "/documentation/mailkit/memessagesigner"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Decrypting-Messages-and-Verifying-Signatures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageDecoder",
        "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessage",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSigner"
      ],
      "title": "Decrypting Messages and Verifying Signatures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Describing-Message-Security-Attributes",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:)",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/isEncrypted",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/encryptionError",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signers",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signingError"
      ],
      "title": "Describing Message Security Attributes"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/localizedRemoteContentBlockingReason",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/shouldBlockRemoteContent"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEMessageSecurityInformation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Describing-Message-Security-Attributes",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:)",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/isEncrypted",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/encryptionError",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signers",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/signingError"
              ],
              "title": "Describing Message Security Attributes"
            },
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/localizedRemoteContentBlockingReason",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSecurityInformation/shouldBlockRemoteContent"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Decrypting-Messages-and-Verifying-Signatures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageDecoder",
                "doc://com.apple.mailkit/documentation/MailKit/MEDecodedMessage",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageSigner"
              ],
              "title": "Decrypting Messages and Verifying Signatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEMessageSecurityInformation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1init(signers:isEncrypted:signingError:encryptionError:)/title",
          "value": "initWithSigners:isEncrypted:signingError:encryptionError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1init(signers:isEncrypted:signingError:encryptionError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSigners:isEncrypted:signingError:encryptionError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation/title",
          "value": "MEMessageSecurityInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSecurityInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageDecoder/title",
          "value": "MEMessageDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageDecoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSigner/title",
          "value": "MEMessageSigner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSigner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSigner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSigner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageSigner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1localizedRemoteContentBlockingReason/title",
          "value": "localizedRemoteContentBlockingReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1localizedRemoteContentBlockingReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedRemoteContentBlockingReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1signers/title",
          "value": "signers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1signers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1encryptionError/title",
          "value": "encryptionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1encryptionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEDecodedMessage/title",
          "value": "MEDecodedMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEDecodedMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodedMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEDecodedMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodedMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1signingError/title",
          "value": "signingError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1signingError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signingError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1shouldBlockRemoteContent/title",
          "value": "shouldBlockRemoteContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1shouldBlockRemoteContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldBlockRemoteContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)/title",
          "value": "initWithSigners:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1init(signers:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSigners:isEncrypted:signingError:encryptionError:shouldBlockRemoteContent:localizedRemoteContentBlockingReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1isEncrypted/title",
          "value": "isEncrypted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageSecurityInformation~1isEncrypted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isEncrypted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/memessagesecurityinformation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/memessagesecurityinformation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
