{
  "abstract": [
    {
      "text": "An object that contains information about security measures the user can apply when composing a message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEOutgoingMessageEncodingStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEOutgoingMessageEncodingStatus"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEOutgoingMessageEncodingStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MEOutgoingMessageEncodingStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As a user composes a new message, MailKit requests the encoding status from your message security handler. The handler provides an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that contains:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Boolean values that indicate if the handler can sign or encrypt the message",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An error if verifying the security status fails",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An array of recipient addresses for which the handler can’t encrypt the message",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage": {
      "abstract": [
        {
          "text": "An object that contains the signed or encrypted representation of a message’s RFC 2822 data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEEncodedOutgoingMessage"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEEncodedOutgoingMessage"
        }
      ],
      "role": "symbol",
      "title": "MEEncodedOutgoingMessage",
      "type": "topic",
      "url": "/documentation/mailkit/meencodedoutgoingmessage"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder": {
      "abstract": [
        {
          "text": "An object that encrypts or digitally signs outgoing messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageEncoder"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageEncoder"
        }
      ],
      "role": "symbol",
      "title": "MEMessageEncoder",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencoder"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult": {
      "abstract": [
        {
          "text": "An object that contains a signed or encrypted message, or errors that indicate failure to encode the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageEncodingResult"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageEncodingResult"
        }
      ],
      "role": "symbol",
      "title": "MEMessageEncodingResult",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus": {
      "abstract": [
        {
          "text": "An object that contains information about security measures the user can apply when composing a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEOutgoingMessageEncodingStatus"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEOutgoingMessageEncodingStatus"
        }
      ],
      "role": "symbol",
      "title": "MEOutgoingMessageEncodingStatus",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption": {
      "abstract": [
        {
          "text": "An array of email addresses that prevent the message security handler from signing the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressesFailingEncryption"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEmailAddress",
          "text": "MEEmailAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressesFailingEncryption"
        }
      ],
      "role": "symbol",
      "title": "addressesFailingEncryption",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/addressesfailingencryption"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the message security handler can encrypt the outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canEncrypt"
        }
      ],
      "role": "symbol",
      "title": "canEncrypt",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/canencrypt"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the message security handler can digitally sign the outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canSign"
        }
      ],
      "role": "symbol",
      "title": "canSign",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/cansign"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)": {
      "abstract": [
        {
          "text": "Creates an object that describes whether the message security handler can encrypt or sign an outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "canSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "canEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "securityError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "addressesFailingEncryption"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEmailAddress",
          "text": "MEEmailAddress"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCanSign:canEncrypt:securityError:addressesFailingEncryption:"
        }
      ],
      "role": "symbol",
      "title": "init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/init(cansign:canencrypt:securityerror:addressesfailingencryption:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError": {
      "abstract": [
        {
          "text": "An error that the message encoder encountered while determining the encoding status for the outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "securityError"
        }
      ],
      "role": "symbol",
      "title": "securityError",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/securityerror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encrypting-and-Signing-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder",
        "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult"
      ],
      "title": "Encrypting and Signing Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-Encoding-Status",
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption"
      ],
      "title": "Providing Encoding Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEOutgoingMessageEncodingStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-Encoding-Status",
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption"
              ],
              "title": "Providing Encoding Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encrypting-and-Signing-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncoder",
                "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult"
              ],
              "title": "Encrypting and Signing Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEOutgoingMessageEncodingStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder/title",
          "value": "MEMessageEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1addressesFailingEncryption/title",
          "value": "addressesFailingEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1addressesFailingEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressesFailingEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/title",
          "value": "MEEncodedOutgoingMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEncodedOutgoingMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEncodedOutgoingMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/title",
          "value": "MEMessageEncodingResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncodingResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncodingResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1init(canSign:canEncrypt:securityError:addressesFailingEncryption:)/title",
          "value": "initWithCanSign:canEncrypt:securityError:addressesFailingEncryption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1init(canSign:canEncrypt:securityError:addressesFailingEncryption:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCanSign:canEncrypt:securityError:addressesFailingEncryption:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/title",
          "value": "MEOutgoingMessageEncodingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canSign/title",
          "value": "canSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canEncrypt/title",
          "value": "canEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1securityError/title",
          "value": "securityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1securityError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "securityError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/meoutgoingmessageencodingstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/meoutgoingmessageencodingstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
