{
  "abstract": [
    {
      "text": "Creates a coordinator that provides separate compensation angles for content your app takes with a capture device, and for your app’s camera preview.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/init(device:previewLayer:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureDeviceRotationCoordinator(im)initWithDevice:previewLayer:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "device"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "previewLayer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CALayer",
        "text": "CALayer"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithDevice:previewLayer:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(device:previewLayer:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "device"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "previewLayer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CALayer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A capture device the new coordinator monitors to track its physical rotation to calculate its ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelCapture",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "device"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A layer that displays a camera preview the new coordinator monitors to calculate its ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelPreview",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "previewLayer"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator": {
      "abstract": [
        {
          "text": "A class that monitors the physical orientation of a capture device and provides adjustment angles to keep images level, relative to gravity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RotationCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RotationCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.RotationCoordinator",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/rotationcoordinator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/init(device:previewLayer:)": {
      "abstract": [
        {
          "text": "Creates a coordinator that provides separate compensation angles for content your app takes with a capture device, and for your app’s camera preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/init(device:previewLayer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:previewLayer:"
        }
      ],
      "role": "symbol",
      "title": "init(device:previewLayer:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/rotationcoordinator/init(device:previewlayer:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelCapture": {
      "abstract": [
        {
          "text": "An angle the coordinator provides your app to apply to photos or videos it captures with the device so that they’re level relative to gravity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRotationAngleForHorizonLevelCapture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoRotationAngleForHorizonLevelCapture"
        }
      ],
      "role": "symbol",
      "title": "videoRotationAngleForHorizonLevelCapture",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/rotationcoordinator/videorotationangleforhorizonlevelcapture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelPreview": {
      "abstract": [
        {
          "text": "An angle the coordinator provides your app to apply to the preview layer so that it’s level relative to gravity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRotationAngleForHorizonLevelPreview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoRotationAngleForHorizonLevelPreview"
        }
      ],
      "role": "symbol",
      "title": "videoRotationAngleForHorizonLevelPreview",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/rotationcoordinator/videorotationangleforhorizonlevelpreview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CALayer": {
      "abstract": [
        {
          "text": "An object that manages image-based content and allows you to perform animations on that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CALayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CALayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CALayer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithDevice:previewLayer:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:previewLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithDevice:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
                    "text": "AVCaptureDevice"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "device"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "previewLayer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CALayer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CALayer",
                    "text": "CALayer"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "previewLayer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A capture device the new coordinator monitors to track its physical rotation to calculate its ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelCapture",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "device"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A layer that displays a camera preview the new coordinator monitors to calculate its ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/RotationCoordinator/videoRotationAngleForHorizonLevelPreview",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "previewLayer"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator~1videoRotationAngleForHorizonLevelCapture/title",
          "value": "videoRotationAngleForHorizonLevelCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator~1videoRotationAngleForHorizonLevelCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoRotationAngleForHorizonLevelCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator~1init(device:previewLayer:)/title",
          "value": "initWithDevice:previewLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator~1init(device:previewLayer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:previewLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CALayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CALayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator~1videoRotationAngleForHorizonLevelPreview/title",
          "value": "videoRotationAngleForHorizonLevelPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator~1videoRotationAngleForHorizonLevelPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoRotationAngleForHorizonLevelPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator/title",
          "value": "AVCaptureDeviceRotationCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceRotationCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1RotationCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceRotationCoordinator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/rotationcoordinator/init(device:previewlayer:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/rotationcoordinator/init(device:previewlayer:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
