{
  "abstract": [
    {
      "text": "The weather condition is unknown or irrelevant.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWeatherCondition@HKWeatherConditionNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWeatherConditionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKWeatherCondition.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition": {
      "abstract": [
        {
          "text": "Constants that indicate a type of weather.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWeatherCondition"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherCondition"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery": {
      "abstract": [
        {
          "text": "The weather condition is blustery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blustery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionBlustery"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.blustery",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/blustery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear": {
      "abstract": [
        {
          "text": "The weather condition is clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionClear"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.clear",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/clear"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy": {
      "abstract": [
        {
          "text": "The weather condition is cloudy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionCloudy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.cloudy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/cloudy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust": {
      "abstract": [
        {
          "text": "The weather condition is dust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dust"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionDust"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.dust",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/dust"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair": {
      "abstract": [
        {
          "text": "The weather condition is fair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fair"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFair"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.fair",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/fair"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy": {
      "abstract": [
        {
          "text": "The weather condition is foggy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foggy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFoggy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.foggy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/foggy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle": {
      "abstract": [
        {
          "text": "The weather condition is freezing drizzle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freezingDrizzle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFreezingDrizzle"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.freezingDrizzle",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/freezingdrizzle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail": {
      "abstract": [
        {
          "text": "The weather condition is hail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hail"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionHail"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.hail",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/hail"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze": {
      "abstract": [
        {
          "text": "The weather condition is hazy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "haze"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionHaze"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.haze",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/haze"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy": {
      "abstract": [
        {
          "text": "The weather condition is mostly cloudy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostlyCloudy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionMostlyCloudy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.mostlyCloudy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/mostlycloudy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none": {
      "abstract": [
        {
          "text": "The weather condition is unknown or irrelevant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionNone"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.none",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/none"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy": {
      "abstract": [
        {
          "text": "The weather condition is partly cloudy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partlyCloudy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionPartlyCloudy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.partlyCloudy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/partlycloudy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet": {
      "abstract": [
        {
          "text": "The weather condition is sleet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionSleet"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.sleet",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/sleet"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky": {
      "abstract": [
        {
          "text": "The weather condition is smoky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smoky"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionSmoky"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.smoky",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/smoky"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow": {
      "abstract": [
        {
          "text": "The weather condition is snow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionSnow"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.snow",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/snow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy": {
      "abstract": [
        {
          "text": "The weather condition is windy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionWindy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.windy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/windy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Weather-Conditions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle"
      ],
      "title": "Weather Conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWeatherConditionNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Weather-Conditions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle"
              ],
              "title": "Weather Conditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKWeatherConditionNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1hail/title",
          "value": "HKWeatherConditionHail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1hail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionHail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1dust/title",
          "value": "HKWeatherConditionDust"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1dust/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionDust"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1blustery/title",
          "value": "HKWeatherConditionBlustery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1blustery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionBlustery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1freezingDrizzle/title",
          "value": "HKWeatherConditionFreezingDrizzle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1freezingDrizzle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFreezingDrizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1snow/title",
          "value": "HKWeatherConditionSnow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1snow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionSnow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1clear/title",
          "value": "HKWeatherConditionClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1fair/title",
          "value": "HKWeatherConditionFair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1fair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mostlyCloudy/title",
          "value": "HKWeatherConditionMostlyCloudy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mostlyCloudy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionMostlyCloudy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition/title",
          "value": "HKWeatherCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1smoky/title",
          "value": "HKWeatherConditionSmoky"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1smoky/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionSmoky"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1foggy/title",
          "value": "HKWeatherConditionFoggy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1foggy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFoggy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1partlyCloudy/title",
          "value": "HKWeatherConditionPartlyCloudy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1partlyCloudy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionPartlyCloudy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1cloudy/title",
          "value": "HKWeatherConditionCloudy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1cloudy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionCloudy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1windy/title",
          "value": "HKWeatherConditionWindy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1windy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionWindy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1haze/title",
          "value": "HKWeatherConditionHaze"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1haze/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionHaze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1none/title",
          "value": "HKWeatherConditionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1sleet/title",
          "value": "HKWeatherConditionSleet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1sleet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionSleet"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkweathercondition/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkweathercondition/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
