{
  "abstract": [
    {
      "text": "Use the lighter of the source and destination colors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/lighten"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSCompositingOperation@NSCompositingOperationLighten",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lighten"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCompositingOperationLighten"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSCompositingOperation.lighten"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lighten"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation": {
      "abstract": [
        {
          "text": "Constants that describe compositing operators in terms of source and destination images, each having an opaque and transparent region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/clear": {
      "abstract": [
        {
          "text": "Transparency everywhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationClear"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.clear",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/clear"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/copy": {
      "abstract": [
        {
          "text": "The source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/copy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationCopy"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.copy",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/copy"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationAtop": {
      "abstract": [
        {
          "text": "The destination image wherever both images are opaque, the source image wherever it is opaque and the destination image is transparent, and transparent elsehwere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationAtop"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationAtop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationDestinationAtop"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.destinationAtop",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/destinationatop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationIn": {
      "abstract": [
        {
          "text": "The destination image wherever both images are opaque, and transparent elsewhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationDestinationIn"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.destinationIn",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/destinationin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOut": {
      "abstract": [
        {
          "text": "The destination image wherever it is opaque and the source image is transparent, and transparent elsewhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationOut"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationDestinationOut"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.destinationOut",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/destinationout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOver": {
      "abstract": [
        {
          "text": "The destination image wherever it is opaque, and the source image elsewhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationOver"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationDestinationOver"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.destinationOver",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/destinationover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/lighten": {
      "abstract": [
        {
          "text": "Use the lighter of the source and destination colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lighten"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/lighten",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationLighten"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.lighten",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/lighten"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/multiply": {
      "abstract": [
        {
          "text": "The source color is multiplied by the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiply"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/multiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationMultiply"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.multiply",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/multiply"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusDarker": {
      "abstract": [
        {
          "text": "The sum of the source and destination images, with color values approach 0 as a limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plusDarker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusDarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationPlusDarker"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.plusDarker",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/plusdarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusLighter": {
      "abstract": [
        {
          "text": "The sum of the source and destination images, with color values approach 1 as a limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plusLighter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusLighter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationPlusLighter"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.plusLighter",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/pluslighter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/screen": {
      "abstract": [
        {
          "text": "Multiplies the complement of the destination and source color values, and then complements the result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/screen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationScreen"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.screen",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/screen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceAtop": {
      "abstract": [
        {
          "text": "The source image wherever both images are opaque, the destination image wherever it is opaque but the source image is transparent, and transparent elsewhere",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAtop"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceAtop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationSourceAtop"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.sourceAtop",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/sourceatop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceIn": {
      "abstract": [
        {
          "text": "The source image wherever both images are opaque, and transparent elsewhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationSourceIn"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.sourceIn",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/sourcein"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOut": {
      "abstract": [
        {
          "text": "The source image wherever it is opaque and the destination image is transparent, and transparent elsewhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceOut"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationSourceOut"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.sourceOut",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/sourceout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOver": {
      "abstract": [
        {
          "text": "The source image wherever it is opaque, and the destination image elsewhere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceOver"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationSourceOver"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.sourceOver",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/sourceover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/xor": {
      "abstract": [
        {
          "text": "Exclusive OR of the source and destination images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/xor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationXOR"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.xor",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/xor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Operations-for-Compositing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/clear",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/copy",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOver",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceIn",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOut",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceAtop",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOver",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationIn",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOut",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationAtop",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/xor",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusDarker",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusLighter",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/multiply",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/screen"
      ],
      "title": "Operations for Compositing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCompositingOperationLighten"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationLighten"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Operations-for-Compositing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/clear",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/copy",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOver",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceIn",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceOut",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/sourceAtop",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOver",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationIn",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationOut",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/destinationAtop",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/xor",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusDarker",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/plusLighter",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/multiply",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/screen"
              ],
              "title": "Operations for Compositing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCompositingOperationLighten"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationOut/title",
          "value": "NSCompositingOperationDestinationOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationDestinationOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1plusDarker/title",
          "value": "NSCompositingOperationPlusDarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1plusDarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationPlusDarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1multiply/title",
          "value": "NSCompositingOperationMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1multiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/title",
          "value": "NSCompositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceAtop/title",
          "value": "NSCompositingOperationSourceAtop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceAtop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationSourceAtop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationAtop/title",
          "value": "NSCompositingOperationDestinationAtop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationAtop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationDestinationAtop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1plusLighter/title",
          "value": "NSCompositingOperationPlusLighter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1plusLighter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationPlusLighter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceOver/title",
          "value": "NSCompositingOperationSourceOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationSourceOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1screen/title",
          "value": "NSCompositingOperationScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1screen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1xor/title",
          "value": "NSCompositingOperationXOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1xor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationXOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1copy/title",
          "value": "NSCompositingOperationCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1copy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceIn/title",
          "value": "NSCompositingOperationSourceIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationSourceIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceOut/title",
          "value": "NSCompositingOperationSourceOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1sourceOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationSourceOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationOver/title",
          "value": "NSCompositingOperationDestinationOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationDestinationOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1lighten/title",
          "value": "NSCompositingOperationLighten"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1lighten/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationLighten"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationIn/title",
          "value": "NSCompositingOperationDestinationIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1destinationIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationDestinationIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1clear/title",
          "value": "NSCompositingOperationClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationClear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscompositingoperation/lighten"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscompositingoperation/lighten"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
