{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uiedgeinsets/zero"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiedgeinsets/zero"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zero","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"languages":["swift"]}]}],"abstract":[{"text":"An edge insets struct whose top, left, bottom, and right fields are all set to ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"property","modules":[{"name":"UIKit"}],"title":"zero","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zero","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false},{"unavailable":false,"name":"watchOS","beta":false,"introducedAt":"2.0","deprecated":false}],"roleHeading":"Type Property","externalID":"c:@UIEdgeInsetsZero","navigatorTitle":[{"text":"UIEdgeInsetsZero","kind":"identifier"}],"extendedModule":"UIKit"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/zero"},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/zero":{"title":"zero","type":"topic","navigatorTitle":[{"text":"UIEdgeInsetsZero","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"zero","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/zero","role":"symbol","url":"/documentation/uikit/uiedgeinsets/zero","kind":"symbol","abstract":[{"text":"An edge insets struct whose top, left, bottom, and right fields are all set to ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets":{"kind":"symbol","abstract":[{"text":"The inset distances for views.","type":"text"}],"url":"/documentation/uikit/uiedgeinsets","navigatorTitle":[{"text":"UIEdgeInsets","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEdgeInsets","kind":"identifier"}],"title":"UIEdgeInsets","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false},{"unavailable":false,"name":"watchOS","beta":false,"introducedAt":"2.0","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"UIEdgeInsetsZero","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"UIEdgeInsetsZero"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"UIEdgeInsetsZero","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets~1zero/title","value":"UIEdgeInsetsZero","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets~1zero/fragments","value":[{"text":"UIEdgeInsetsZero","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/title","value":"UIEdgeInsets","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/fragments","value":[{"text":"UIEdgeInsets","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/navigatorTitle","value":[{"kind":"identifier","text":"UIEdgeInsets"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}