{
  "abstract": [
    {
      "text": "The MIDI-CI device’s information.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported for CoreMIDI",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/deviceInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MIDICIResponder(py)deviceInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deviceInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MIDICIDeviceInfo",
        "text": "MIDICIDeviceInfo"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "deviceInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "No longer supported for CoreMIDI",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "No longer supported for CoreMIDI",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "No longer supported for CoreMIDI",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "No longer supported for CoreMIDI",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "No longer supported for CoreMIDI",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "deviceInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MIDICIDeviceInfo",
              "text": "MIDICIDeviceInfo"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceIdentification": {
      "abstract": [
        {
          "text": "A structure that describes a MIDI-CI device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDeviceIdentification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDeviceIdentification"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceIdentification",
      "type": "topic",
      "url": "/documentation/coremidi/midicideviceidentification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceInfo": {
      "abstract": [
        {
          "text": "An object that provides basic information about a MIDI-CI device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDeviceInfo"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDeviceInfo"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceInfo",
      "type": "topic",
      "url": "/documentation/coremidi/midicideviceinfo"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIInitiatiorMUID": {
      "abstract": [
        {
          "text": "The unique MIDI-CI negotiation identifier to use for a responder connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIInitiatiorMUID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIInitiatiorMUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIInitiatiorMUID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIInitiatiorMUID",
      "type": "topic",
      "url": "/documentation/coremidi/midiciinitiatiormuid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder": {
      "abstract": [
        {
          "text": "An object that responds to MIDI-CI inquiries from an initiator on behalf of a MIDI client, and handles profile and property exchange operations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIResponder"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIResponder"
        }
      ],
      "role": "symbol",
      "title": "MIDICIResponder",
      "type": "topic",
      "url": "/documentation/coremidi/midiciresponder"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/deviceInfo": {
      "abstract": [
        {
          "text": "The MIDI-CI device’s information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIDeviceInfo",
          "text": "MIDICIDeviceInfo"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/deviceInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceInfo"
        }
      ],
      "role": "symbol",
      "title": "deviceInfo",
      "type": "topic",
      "url": "/documentation/coremidi/midiciresponder/deviceinfo"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/initiators": {
      "abstract": [
        {
          "text": "An array of initiators.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initiators"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICIInitiatiorMUID",
          "text": "MIDICIInitiatiorMUID"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/initiators",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initiators"
        }
      ],
      "role": "symbol",
      "title": "initiators",
      "type": "topic",
      "url": "/documentation/coremidi/midiciresponder/initiators"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Responder",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIInitiatiorMUID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/initiators",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceIdentification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceInfo"
      ],
      "title": "Inspecting a Responder"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "deviceInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Responder",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIInitiatiorMUID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder/initiators",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceIdentification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceInfo"
              ],
              "title": "Inspecting a Responder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MIDICIDeviceInfo",
                    "text": "MIDICIDeviceInfo"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "deviceInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported for CoreMIDI",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceInfo/title",
          "value": "MIDICIDeviceInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder~1deviceInfo/title",
          "value": "deviceInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder~1deviceInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceIdentification/title",
          "value": "MIDICIDeviceIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder~1initiators/title",
          "value": "initiators"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder~1initiators/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initiators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/title",
          "value": "MIDICIResponder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIInitiatiorMUID/title",
          "value": "MIDICIInitiatiorMUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIInitiatiorMUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIInitiatiorMUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIInitiatiorMUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIInitiatiorMUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiciresponder/deviceinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midiciresponder/deviceinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
