{
  "abstract": [
    {
      "text": "Enhance the realism of spatial audio output by tracking a person’s head movement and accounting for their personal spatial audio profile.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/personalizing-spatial-audio-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "Personalizing-spatial-audio-in-your-app-PageImage-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "tvOS"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Personalizing spatial audio in your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that implement 3D spatial audio in supported frameworks can fine tune the listener experience by automatically updating the listener orientation according to a person’s head movement while wearing compatible AirPods, and using the personal spatial audio profile that they create in Settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 18, iPadOS 18, and tvOS 18, the system adds spatial audio effects for games by default, and offers a Control Center toggle to control the effect. If your game implements custom spatial audio, you need to disable the effect to prevent undesirable artifacts from spatializing an audio stream twice, an effect known as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "double spatialization",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Apply-a-personal-spatial-audio-profile",
          "level": 2,
          "text": "Apply a personal spatial audio profile",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A person can opt in to ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "personalized spatial audio",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " by creating a profile in settings that walks them through scanning their head using the camera on their iPhone. The system constructs a geometric representation of the shape of the person’s head that supporting audio frameworks observe to enhance the simulation of sound traveling through the physical environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.spatial-audio.profile-access",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement to your app and implement custom spatial audio with either of the following frameworks, the system automatically takes the personal spatial audio profile into account as it tailors the audio output:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/audiotoolbox/1390073-auspatialmixer_parameters",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " (in Audio Toolbox)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEngine",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/PHASE",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Enable-head-tracking-with-compatible-AirPods",
          "level": 2,
          "text": "Enable head tracking with compatible AirPods",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Head tracking adjusts the orientation of the listener according to their head movement while wearing compatible AirPods. This creates the effect that the listener is present in the 3D scene. Head tracking works by simulating the effect of detaching the left and right speakers from the person’s head and virtually placing them in stationary positions in the physical environment, to the left and right of the person, respectively.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To enable head tracking:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.coremotion.head-pose",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement to your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the API to opt in; the process varies depending on the framework:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Adjust the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEnvironmentNode",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " orientation to match the person’s head pose by setting the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property to ",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "AVAudioEngine",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Adjust the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/PHASE/PHASEListener",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " orientation by setting the  ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/PHASE/PHASEListener/automaticHeadTrackingFlags",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/PHASE/PHASEAutomaticHeadTrackingFlags/orientation",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "PHASE",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Adjust the ",
                        "type": "text"
                      },
                      {
                        "code": "AUSpatialMixer",
                        "type": "codeVoice"
                      },
                      {
                        "text": " orientation to match the person’s head pose by setting the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property to ",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Audio Toolbox",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Disable-the-system-provided-spatial-audio",
          "level": 2,
          "text": "Disable the system-provided spatial audio",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 18, iPadOS 18, and tvOS 18, the system adds an automatic spatial audio effect for apps in the App Store Connect game category when a person wears compatible AirPods. If your game already implements spatial audio with one of the supporting frameworks or third-party engine, you need to disable the automatic effect by adding the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key to your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Automatic spatial audio works by adding a reverb to the room and simulating the effect of detaching the left and right speakers from the person’s head. The speakers’ output from a virtual position at a fixed length in front of the person, with a short distance between the left and right outputs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Control Center provides UI to toggle this effect and the feature is on by default. If you opt out with the ",
              "type": "text"
            },
            {
              "code": "AVGameBypassSystemSpatialAudio",
              "type": "codeVoice"
            },
            {
              "text": " key, the system disables the effect and Control Center toggle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Personalizing-spatial-audio-in-your-app-PageImage-card.png": {
      "alt": null,
      "identifier": "Personalizing-spatial-audio-in-your-app-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/458d3629d64a7bb95149d26677821ea9/Personalizing-spatial-audio-in-your-app-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2d51b4d8ee491c3605548c128eb9cf62/Personalizing-spatial-audio-in-your-app-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEngine": {
      "abstract": [
        {
          "text": "An object that manages a graph of audio nodes, controls playback, and configures real-time rendering constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEngine"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEngine",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioEngine",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioEngine"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEnvironmentNode": {
      "abstract": [
        {
          "text": "An object that simulates a 3D audio environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEnvironmentNode",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioEnvironmentNode",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioEnvironmentNode"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the listener orientation is automatically rotated based on head orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isListenerHeadTrackingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isListenerHeadTrackingEnabled",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerEnableHeadTracking",
      "type": "topic",
      "url": "/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.coremotion.head-pose": {
      "abstract": [
        {
          "text": "An entitlement that enables someone’s head movement to determine the orientation of spatialized sound output.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.coremotion.head-pose",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.coremotion.head-pose",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.coremotion.head-pose"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.spatial-audio.profile-access": {
      "abstract": [
        {
          "text": "An entitlement that enables your app to use the personalized spatial audio profile.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.spatial-audio.profile-access",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.spatial-audio.profile-access",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.spatial-audio.profile-access"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio": {
      "abstract": [
        {
          "text": "A key that ignores the system spatial-audio toggle in Control Center.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVGameBypassSystemSpatialAudio",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio"
    },
    "doc://com.apple.documentation/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/PHASE"
    },
    "doc://com.apple.documentation/documentation/PHASE/PHASEAutomaticHeadTrackingFlags/orientation": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEAutomaticHeadTrackingFlags",
          "text": "PHASEAutomaticHeadTrackingFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PHASE/PHASEAutomaticHeadTrackingFlags/orientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/PHASE/PHASEAutomaticHeadTrackingFlags/orientation"
    },
    "doc://com.apple.documentation/documentation/PHASE/PHASEListener": {
      "abstract": [
        {
          "text": "A central point of reference that defines the location within the scene that’s most audible to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEListener"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PHASE/PHASEListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHASEListener",
      "type": "topic",
      "url": "/documentation/PHASE/PHASEListener"
    },
    "doc://com.apple.documentation/documentation/PHASE/PHASEListener/automaticHeadTrackingFlags": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticHeadTrackingFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEAutomaticHeadTrackingFlags",
          "text": "PHASEAutomaticHeadTrackingFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PHASE/PHASEListener/automaticHeadTrackingFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "automaticHeadTrackingFlags",
      "type": "topic",
      "url": "/documentation/PHASE/PHASEListener/automaticHeadTrackingFlags"
    },
    "doc://com.apple.documentation/documentation/Updates/PHASE": {
      "abstract": [
        {
          "text": "Learn about important changes to PHASE.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/PHASE",
      "kind": "article",
      "role": "article",
      "title": "PHASE updates",
      "type": "topic",
      "url": "/documentation/Updates/PHASE"
    },
    "doc://com.apple.documentation/documentation/audiotoolbox/1390073-auspatialmixer_parameters": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/audiotoolbox/1390073-auspatialmixer_parameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer_parameters"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene": {
      "abstract": [
        {
          "text": "Position sound from a specific direction and automatically raise or lower volume based on the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene",
      "kind": "article",
      "role": "article",
      "title": "Playing sound from a location in a 3D scene",
      "type": "topic",
      "url": "/documentation/phase/playing-sound-from-a-location-in-a-3d-scene"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene",
        "doc://com.apple.documentation/documentation/Updates/PHASE"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerEnableHeadTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PHASE~1PHASEListener/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASEListener"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHASEObject",
              "text": "PHASEObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1isListenerHeadTrackingEnabled/title",
          "value": "listenerHeadTrackingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1isListenerHeadTrackingEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isListenerHeadTrackingEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "listenerHeadTrackingEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PHASE~1PHASEListener~1automaticHeadTrackingFlags/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHASEAutomaticHeadTrackingFlags",
              "text": "PHASEAutomaticHeadTrackingFlags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automaticHeadTrackingFlags"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioEnvironmentNode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioNode",
              "text": "AVAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioEngine/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioEngine"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PHASE~1PHASEAutomaticHeadTrackingFlags~1orientation/title",
          "value": "PHASEAutomaticHeadTrackingFlagOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PHASE~1PHASEAutomaticHeadTrackingFlags~1orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAutomaticHeadTrackingFlagOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/personalizing-spatial-audio-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/personalizing-spatial-audio-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
