{
  "abstract": [
    {
      "text": "A base class for sound event nodes that connect to form a node hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASESoundEventNodeDefinition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASESoundEventNodeDefinition"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASESoundEventNodeDefinition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASESoundEventNodeDefinition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class defines the base functionality for an object that, depending on the derived class’s type, either plays audio or hands off the invocation to one or more other nodes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-a-Sound-Event-Node-to-Play-Audio",
          "level": 3,
          "text": "Configure a Sound Event Node to Play Audio",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To play audio with this class, retrieve a sound-event node asset (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") that generates sound events by creating and registering one of the audio-providing node definitions in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/sound-event-nodes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and pass the node definition in the ",
              "type": "text"
            },
            {
              "code": "rootNode",
              "type": "codeVoice"
            },
            {
              "text": " argument. Provide an ",
              "type": "text"
            },
            {
              "code": "identifier",
              "type": "codeVoice"
            },
            {
              "text": " argument with a unique name that your app refers to later when generating a playable ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-a-Node-Hiearchy-that-Reacts-to-Your-Apps-State",
          "level": 3,
          "text": "Configure a Node Hiearchy that Reacts to Your App’s State",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can create a hierarchy of nodes that blends audio based on your app’s parameters, or plays the right audio based on your app’s state. To create the hierarchy, register one of the control nodes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/sound-event-nodes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", passing in a unique ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDefinition/identifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " you define for the subclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The particular configuration you choose for a node hierarchy instructs PHASE on which audio to play, when to play it, or whether to hand off an invocation to one or more child nodes (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if you register and invoke a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that contains two child ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, PHASE plays the audio of one of the child sampler nodes based on the current value of the switch node’s metaparameter. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/metaParameters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAsset": {
      "abstract": [
        {
          "text": "A base class that adds a name to framework assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASEAsset",
      "type": "topic",
      "url": "/documentation/phase/phaseasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)": {
      "abstract": [
        {
          "text": "Registers the root node of the sound event asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerSoundEventAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rootNode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeAsset",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerSoundEventAssetWithRootNode:identifier:error:"
        }
      ],
      "role": "symbol",
      "title": "registerSoundEventAsset(rootNode:identifier:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/registersoundeventasset(rootnode:identifier:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition": {
      "abstract": [
        {
          "text": "A node that smoothly fades between the audio of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEBlendNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseblendnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays all its children at the same time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEContainerNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEContainerNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEContainerNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasecontainernodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDefinition": {
      "abstract": [
        {
          "text": "A base class that adds a name to framework definitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDefinition/identifier": {
      "abstract": [
        {
          "text": "A unique name for the definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDefinition/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/phase/phasedefinition/identifier"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for nodes that provide audio data to generate sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGeneratorNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGeneratorNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEGeneratorNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasegeneratornodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition": {
      "abstract": [
        {
          "text": "A sound event node that invokes one of its child nodes at random.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASERandomNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASERandomNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASERandomNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays complete audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESamplerNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESamplerNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESamplerNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesamplernodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset": {
      "abstract": [
        {
          "text": "A sound resource stored in the asset registry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundAsset",
      "type": "topic",
      "url": "/documentation/phase/phasesoundasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent": {
      "abstract": [
        {
          "text": "An object that determines which audio to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEvent"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEvent"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEvent",
      "type": "topic",
      "url": "/documentation/phase/phasesoundevent"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum": {
      "abstract": [
        {
          "text": "The playback status of audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RenderingState"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RenderingState"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEvent.RenderingState",
      "type": "topic",
      "url": "/documentation/phase/phasesoundevent/renderingstate-swift.enum"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/metaParameters": {
      "abstract": [
        {
          "text": "The object’s meta parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metaParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEMetaParameter",
          "text": "PHASEMetaParameter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/metaParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metaParameters"
        }
      ],
      "role": "symbol",
      "title": "metaParameters",
      "type": "topic",
      "url": "/documentation/phase/phasesoundevent/metaparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset": {
      "abstract": [
        {
          "text": "A template object for sounds that can play in reaction to environmental state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeAsset",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodeasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for sound event nodes that connect to form a node hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children": {
      "abstract": [
        {
          "text": "An array of child sound event nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "children"
        }
      ],
      "role": "symbol",
      "title": "children",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodedefinition/children"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition": {
      "abstract": [
        {
          "text": "A node that passes invocation to only one of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESwitchNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESwitchNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESwitchNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseswitchnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/sound-event-nodes": {
      "abstract": [
        {
          "text": "Objects that connect to form a hierarchical tree of audio actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/sound-event-nodes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sound Event Nodes",
      "type": "topic",
      "url": "/documentation/phase/sound-event-nodes"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEDefinition"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Selection-and-Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
        "doc://com.apple.phase/documentation/PHASE/PHASEAsset",
        "doc://com.apple.phase/documentation/PHASE/sound-event-nodes"
      ],
      "title": "Audio Selection and Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Child-Nodes",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children"
      ],
      "title": "Accessing Child Nodes"
    },
    {
      "anchor": "Identifying-a-Definition",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEDefinition"
      ],
      "title": "Identifying a Definition"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASESoundEventNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Child-Nodes",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children"
              ],
              "title": "Accessing Child Nodes"
            },
            {
              "anchor": "Identifying-a-Definition",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEDefinition"
              ],
              "title": "Identifying a Definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEDefinition"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Selection-and-Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
                "doc://com.apple.phase/documentation/PHASE/PHASEAsset",
                "doc://com.apple.phase/documentation/PHASE/sound-event-nodes"
              ],
              "title": "Audio Selection and Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASESoundEventNodeDefinition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDefinition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHASEDefinition",
                    "text": "PHASEDefinition"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/title",
          "value": "PHASESoundEventNodeAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition/title",
          "value": "PHASEDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/title",
          "value": "PHASERandomNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/title",
          "value": "PHASEBlendNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/title",
          "value": "PHASESoundAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundEventAsset(rootNode:identifier:)/title",
          "value": "registerSoundEventAssetWithRootNode:identifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundEventAsset(rootNode:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerSoundEventAssetWithRootNode:identifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAsset/title",
          "value": "PHASEAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/title",
          "value": "PHASESoundEventNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition~1children/title",
          "value": "children"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition~1children/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "children"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent/title",
          "value": "PHASESoundEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1RenderingState-swift.enum/title",
          "value": "PHASERenderingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1RenderingState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERenderingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1RenderingState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERenderingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/title",
          "value": "PHASESwitchNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESwitchNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESwitchNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/title",
          "value": "PHASEContainerNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEContainerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEContainerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/title",
          "value": "PHASEGeneratorNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeneratorNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeneratorNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/title",
          "value": "PHASESamplerNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESamplerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESamplerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1metaParameters/title",
          "value": "metaParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1metaParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metaParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasesoundeventnodedefinition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasesoundeventnodedefinition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
