{
  "abstract": [
    {
      "text": "Errors that the PHASE framework reports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/phase-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "PHASE Errors"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct": {
      "abstract": [
        {
          "text": "An asset error that PHASE reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEAssetError"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEAssetError"
        }
      ],
      "role": "symbol",
      "title": "PHASEAssetError",
      "type": "topic",
      "url": "/documentation/phase/phaseasseterror-swift.struct"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes that identify framework asset errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PHASEAssetError.Code",
      "type": "topic",
      "url": "/documentation/phase/phaseasseterror-swift.struct/code"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetErrorDomain": {
      "abstract": [
        {
          "text": "A unique error domain for PHASE assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEAssetErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEAssetErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PHASEAssetErrorDomain",
      "type": "topic",
      "url": "/documentation/phase/phaseasseterrordomain"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct": {
      "abstract": [
        {
          "text": "An error that PHASE reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEError"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEError"
        }
      ],
      "role": "symbol",
      "title": "PHASEError",
      "type": "topic",
      "url": "/documentation/phase/phaseerror-swift.struct"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors in PHASE.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PHASEError.Code",
      "type": "topic",
      "url": "/documentation/phase/phaseerror-swift.struct/code"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEErrorDomain": {
      "abstract": [
        {
          "text": "A unique error domain for the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PHASEErrorDomain",
      "type": "topic",
      "url": "/documentation/phase/phaseerrordomain"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct": {
      "abstract": [
        {
          "text": "A sound event error that PHASE reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventError"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventError"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventError",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventerror-swift.struct"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes that identify sound event errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventError.Code",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventerror-swift.struct/code"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventErrorDomain": {
      "abstract": [
        {
          "text": "A unique error domain for sound events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventErrorDomain",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventerrordomain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Framework-Errors",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct",
        "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct/Code",
        "doc://com.apple.phase/documentation/PHASE/PHASEErrorDomain"
      ],
      "title": "Framework Errors"
    },
    {
      "anchor": "Asset-Errors",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct",
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct/Code",
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetErrorDomain"
      ],
      "title": "Asset Errors"
    },
    {
      "anchor": "Sound-Event-Errors",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct/Code",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventErrorDomain"
      ],
      "title": "Sound Event Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Framework-Errors",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEError-swift.struct/Code",
                "doc://com.apple.phase/documentation/PHASE/PHASEErrorDomain"
              ],
              "title": "Framework Errors"
            },
            {
              "anchor": "Asset-Errors",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetError-swift.struct/Code",
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetErrorDomain"
              ],
              "title": "Asset Errors"
            },
            {
              "anchor": "Sound-Event-Errors",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventError-swift.struct/Code",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventErrorDomain"
              ],
              "title": "Sound Event Errors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventErrorDomain/title",
          "value": "PHASESoundEventErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetErrorDomain/title",
          "value": "PHASEAssetErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEError-swift.struct~1Code/title",
          "value": "PHASEError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEErrorDomain/title",
          "value": "PHASEErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetError-swift.struct~1Code/title",
          "value": "PHASEAssetError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventError-swift.struct~1Code/title",
          "value": "PHASESoundEventError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phase-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phase-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
