{
  "abstract": [
    {
      "text": "A collection of settings for groups.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASEGroupPreset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASEGroupPreset"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEGroupPreset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASEGroupPreset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Group presets pair groups with audio settings that your app can apply to specific sounds at a particular time in your app’s life cycle. This class enables many predefined group settings to take effect all at once.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Toggle-Between-Group-Presets",
          "level": 3,
          "text": "Toggle Between Group Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The group preset’s utility materializes when you switch between settings. The following example creates two group presets: one for an in-game experience and another for a menu that displays when the user pauses the app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// Create sound group objects.",
                    "let bgmGroup = PHASEGroup(identifier:\"backgroundMusicGroup\")",
                    "let voGroup = PHASEGroup(identifier:\"voiceOverGroup\")",
                    "let menuGroup = PHASEGroup(identifier:\"menuSoundsGroup\")",
                    "",
                    "// Register the groups with the engine.",
                    "bgmGroup.register(engine: myEngine)",
                    "voGroup.register(engine: myEngine)",
                    "menuGroup.register(engine: myEngine)",
                    "        ",
                    "// Create settings for the groups.",
                    "let groupSettingFullVolume = PHASEGroupPresetSetting(gain: 1.0, rate: 1.0, gainCurveType: .linear, rateCurveType: .linear)",
                    "let groupSettingZeroVolume = PHASEGroupPresetSetting(gain: 0.0, rate: 1.0, gainCurveType: .linear, rateCurveType: .linear)",
                    "        ",
                    "// Create a dictionary for the `settings` argument of the group preset initializer.",
                    "var pauseMenuDictionary: [String : PHASEGroupPresetSetting] = [:]",
                    "        ",
                    "// Enable volume only for menu group sounds.",
                    "pauseMenuDictionary[menuGroup.identifier] = groupSettingFullVolume",
                    "pauseMenuDictionary[bgmGroup.identifier] = groupSettingZeroVolume",
                    "pauseMenuDictionary[voGroup.identifier] = groupSettingZeroVolume",
                    "let pauseMenuPreset = PHASEGroupPreset(engine: myEngine, settings: pauseMenuDictionary, timeToTarget: 1.0, timeToReset: 1.0)",
                    "        ",
                    "// Create a settings dictionary for the in-game experience.",
                    "var inGameDictionary: [String : PHASEGroupPresetSetting] = [:]",
                    "",
                    "// Enable volume only for in-game sounds.",
                    "inGameDictionary[menuGroup.identifier] = groupSettingZeroVolume",
                    "inGameDictionary[bgmGroup.identifier] = groupSettingFullVolume",
                    "inGameDictionary[voGroup.identifier] = groupSettingFullVolume",
                    "let inGamePreset = PHASEGroupPreset(engine: myEngine, settings: inGameDictionary, timeToTarget: 1.0, timeToReset: 1.0)",
                    "        ",
                    "// Activate the pause menu preset when the user pauses the app.",
                    "pauseMenuPreset.activate()",
                    "",
                    "// Activate the in-game preset when the user resumes the app.",
                    "inGamePreset.activate()",
                    "",
                    "// Clear the current preset by deactivating it.",
                    "if let groupPreset = myEngine.activeGroupPreset {",
                    "    groupPreset.deactivate()",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// Create groups for the sounds. ",
                    "PHASEGroup* bgmGroup = [[PHASEGroup alloc] initWithEngine:_objects->mEngine uid:@\"backgroundMusicGroup\"];",
                    "PHASEGroup* voGroup = [[PHASEGroup alloc] initWithEngine:_objects->mEngine uid:@\"voiceOverGroup\"];",
                    "PHASEGroup* menuGroup = [[PHASEGroup alloc] initWithEngine:_objects->mEngine uid:@\"menuSoundsGroup\"];",
                    "",
                    "// Create settings for the groups.",
                    "PHASEGroupPresetSetting* groupSettingFullVolume = [PHASEGroupPresetSetting alloc] initWithGain:1",
                    "    rate:1 gainCurveType:PHASECurveTypeLinear rateCurveType:PHASECurveTypeLinear];",
                    "                                                ",
                    "PHASEGroupPresetSetting* groupSettingZeroVolume = [PHASEGroupPresetSetting alloc] initWithGain:0",
                    "    rate:1 gainCurveType:PHASECurveTypeLinear rateCurveType:PHASECurveTypeLinear];",
                    "",
                    "// Create a dictionary for the `settings` argument of the group preset initializer.",
                    "NSMutableDictionary<PHASEGroup*, PHASEGroupPresetSetting*> pauseMenuDictionary;",
                    "",
                    "// Enable volume only for menu group sounds.",
                    "[pauseMenuDictionary setObject:groupSettingFullVolume forKey:menuGroup]",
                    "[pauseMenuDictionary setObject:groupSettingZeroVolume forKey:bgmGroup]",
                    "[pauseMenuDictionary setObject:groupSettingZeroVolume forKey:voGroup]",
                    "PHASEGroupPreset* pauseMenuPreset = [[PHASEGroupPreset alloc] initWithEngine:myPHASEEngine",
                    "    settings:pauseMenuDictionary timeToTarget:1 timeToReset:1];",
                    "",
                    "// Create a settings dictionary for the in-game experience.",
                    "NSMutableDictionary<PHASEGroup*, PHASEGroupPresetSetting*> inGameDictionary;",
                    "",
                    "// Enable volume only for in-game sounds.",
                    "[inGameDictionary setObject:groupSettingZeroVolume forKey:menuGroup]",
                    "[inGameDictionary setObject:groupSettingFullVolume forKey:bgmGroup]",
                    "[inGameDictionary setObject:groupSettingFullVolume forKey:voGroup]",
                    "PHASEGroupPreset* inGamePreset = [[PHASEGroupPreset alloc] initWithEngine:myPHASEEngine",
                    "    settings:inGameDictionary timeToTarget:1 timeToReset:1];",
                    "",
                    "// Activate the pause menu preset when the user pauses the app.",
                    "[pauseMenuPreset activate];",
                    "",
                    "// Activate the in-game preset when the user resumes the app. ",
                    "[inGamePreset activate];",
                    "",
                    "// Clear the current preset by deactivating it.",
                    "[myPHASEEngine.activeGroupPreset deactivate]",
                    ""
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker": {
      "abstract": [
        {
          "text": "An object that manages competing sounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDucker"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDucker"
        }
      ],
      "role": "symbol",
      "title": "PHASEDucker",
      "type": "topic",
      "url": "/documentation/phase/phaseducker"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroup": {
      "abstract": [
        {
          "text": "A container that shares audio parameters with a collection of sounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGroup"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGroup"
        }
      ],
      "role": "symbol",
      "title": "PHASEGroup",
      "type": "topic",
      "url": "/documentation/phase/phasegroup"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset": {
      "abstract": [
        {
          "text": "A collection of settings for groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGroupPreset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGroupPreset"
        }
      ],
      "role": "symbol",
      "title": "PHASEGroupPreset",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate()": {
      "abstract": [
        {
          "text": "Applies settings to the designated groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activate"
        }
      ],
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/activate()"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate(timeToTargetOverride:)": {
      "abstract": [
        {
          "text": "Applies settings with an overriden fade duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timeToTargetOverride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate(timeToTargetOverride:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateWithTimeToTargetOverride:"
        }
      ],
      "role": "symbol",
      "title": "activate(timeToTargetOverride:)",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/activate(timetotargetoverride:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate()": {
      "abstract": [
        {
          "text": "Reverts settings for the preset’s groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deactivate"
        }
      ],
      "role": "symbol",
      "title": "deactivate()",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/deactivate()"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate(timeToResetOverride:)": {
      "abstract": [
        {
          "text": "Reverts settings for the preset’s groups using a timed adjustment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timeToResetOverride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate(timeToResetOverride:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deactivateWithTimeToResetOverride:"
        }
      ],
      "role": "symbol",
      "title": "deactivate(timeToResetOverride:)",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/deactivate(timetoresetoverride:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/init(engine:settings:timeToTarget:timeToReset:)": {
      "abstract": [
        {
          "text": "Creates a group preset with the designated engine, settings, and fade parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "engine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEEngine",
          "text": "PHASEEngine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "settings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGroupPresetSetting",
          "text": "PHASEGroupPresetSetting"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeToTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeToReset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/init(engine:settings:timeToTarget:timeToReset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEngine:settings:timeToTarget:timeToReset:"
        }
      ],
      "role": "symbol",
      "title": "init(engine:settings:timeToTarget:timeToReset:)",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/init(engine:settings:timetotarget:timetoreset:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/settings": {
      "abstract": [
        {
          "text": "A dictionary with preset setting values and group objects as keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "settings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGroupPresetSetting",
          "text": "PHASEGroupPresetSetting"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/settings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "settings"
        }
      ],
      "role": "symbol",
      "title": "settings",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/settings"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToReset": {
      "abstract": [
        {
          "text": "A duration in which the framework restores the group’s original state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeToReset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeToReset"
        }
      ],
      "role": "symbol",
      "title": "timeToReset",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/timetoreset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToTarget": {
      "abstract": [
        {
          "text": "A duration in which the engine fades the settings from their original value to their new value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeToTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeToTarget"
        }
      ],
      "role": "symbol",
      "title": "timeToTarget",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset/timetotarget"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting": {
      "abstract": [
        {
          "text": "Settings for group presets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGroupPresetSetting"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGroupPresetSetting"
        }
      ],
      "role": "symbol",
      "title": "PHASEGroupPresetSetting",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppresetsetting"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sound-Grouping-and-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker"
      ],
      "title": "Sound Grouping and Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Group-Preset",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/init(engine:settings:timeToTarget:timeToReset:)"
      ],
      "title": "Creating a Group Preset"
    },
    {
      "anchor": "Applying-Settings",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/settings"
      ],
      "title": "Applying Settings"
    },
    {
      "anchor": "Fading-Between-Settings",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToTarget",
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToReset"
      ],
      "title": "Fading Between Settings"
    },
    {
      "anchor": "Activating-a-Group-Preset",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate()",
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate(timeToTargetOverride:)"
      ],
      "title": "Activating a Group Preset"
    },
    {
      "anchor": "Deactivating-a-Group-Preset",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate()",
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate(timeToResetOverride:)"
      ],
      "title": "Deactivating a Group Preset"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEGroupPreset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Group-Preset",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/init(engine:settings:timeToTarget:timeToReset:)"
              ],
              "title": "Creating a Group Preset"
            },
            {
              "anchor": "Applying-Settings",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/settings"
              ],
              "title": "Applying Settings"
            },
            {
              "anchor": "Fading-Between-Settings",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToTarget",
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/timeToReset"
              ],
              "title": "Fading Between Settings"
            },
            {
              "anchor": "Activating-a-Group-Preset",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate()",
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/activate(timeToTargetOverride:)"
              ],
              "title": "Activating a Group Preset"
            },
            {
              "anchor": "Deactivating-a-Group-Preset",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate()",
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset/deactivate(timeToResetOverride:)"
              ],
              "title": "Deactivating a Group Preset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sound-Grouping-and-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker"
              ],
              "title": "Sound Grouping and Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASEGroupPreset"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker/title",
          "value": "PHASEDucker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset/title",
          "value": "PHASEGroupPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1activate(timeToTargetOverride:)/title",
          "value": "activateWithTimeToTargetOverride:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1activate(timeToTargetOverride:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateWithTimeToTargetOverride:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1timeToTarget/title",
          "value": "timeToTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1timeToTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeToTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1deactivate()/title",
          "value": "deactivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1deactivate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deactivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1timeToReset/title",
          "value": "timeToReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1timeToReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeToReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1init(engine:settings:timeToTarget:timeToReset:)/title",
          "value": "initWithEngine:settings:timeToTarget:timeToReset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1init(engine:settings:timeToTarget:timeToReset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEngine:settings:timeToTarget:timeToReset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1settings/title",
          "value": "settings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1settings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1deactivate(timeToResetOverride:)/title",
          "value": "deactivateWithTimeToResetOverride:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1deactivate(timeToResetOverride:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deactivateWithTimeToResetOverride:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPresetSetting/title",
          "value": "PHASEGroupPresetSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPresetSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPresetSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPresetSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPresetSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1activate()/title",
          "value": "activate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset~1activate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroup/title",
          "value": "PHASEGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasegrouppreset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasegrouppreset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
