{
  "abstract": [
    {
      "text": "A collection of segments that connect to graph a complex curve over a linear input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASEEnvelope",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASEEnvelope"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEEnvelope"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASEEnvelope"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASEEnvelope"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In traditional audio uses, an ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "envelope",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " defines a complex graph that determines the volume of audio data over an input duration. PHASE uses envelopes in a similar way. Given a value on the envelope’s input axis, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/evaluate(x:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function plots and returns the result on the output axis. The following are possible uses of this class:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sound event nodes, such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", can shape their volume using an envelope; see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition/addRange(envelope:subtree:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Distance models shape sounds with a 3D position using an envelope; see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An envelope can do more than shape audio. To gradually change an envelope’s input value over time, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMappedMetaParameterDefinition",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class, which creates a function with a metaparameter value as input. An app can use the numeric result for any purpose. For example, the x-axis can be distance and the y-axis can be playback rate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "At runtime, PHASE determines whether a particular member of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/segments",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array slopes up or down along the domain depending on the envelope’s particular use case.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-an-Envelope-and-Shape-its-Curve",
          "level": 3,
          "text": "Create an Envelope and Shape its Curve",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use an envelope in your app, define its shape by defining a series of segments. Each segment specifies a curve that collectively connect to form a graph. The following code creates an envelope with a single segment that’s shaped like the lettter ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "s:",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// Create a segments array.",
                    "var segments: [PHASEEnvelopeSegment] = []",
                    "",
                    "// Create a single segment with a sigmoid curve to give \"ease in, ",
                    "//  ease out\" movement along the domain. Define an endpoint of (1, 1).",
                    "let segment = PHASEEnvelopeSegment(",
                    "    endPoint: simd_make_double2(1.0, 1.0), curveType: .sigmoid)",
                    "",
                    "// Add the segment to the array.",
                    "segments.append(segment)",
                    "",
                    "// Create the envelope and set the start point to (-1, -1).",
                    "let envelope = PHASEEnvelope(startPoint: simd_make_double2(-1.0, -1.0),",
                    "    segments: segments)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// Create a segments array.",
                    "NSMutableArray<PHASEEnvelopeSegment*>* segments = ",
                    "    [NSMutableArray new];",
                    "",
                    "// Create a single segment with a sigmoid curve to give \"ease in, ",
                    "//  ease out\" movement along the domain. Define an endpoint of (1, 1).",
                    "PHASEEnvelopeSegment* segment = [[PHASEEnvelopeSegment alloc] ",
                    "    initWithEndPoint:simd_make_double2(1.0, 1.0) ",
                    "    curveType:PHASECurveTypeSigmoid];",
                    "",
                    "// Add the segment to the array.",
                    "[segments addObject:segment];",
                    "",
                    "// Create the envelope and set the start point to (-1, -1).",
                    "PHASEEnvelope* envelope = [[PHASEEnvelope alloc] ",
                    "    initWithStartPoint:simd_make_double2(-1.0, -1.0) ",
                    "    segments:segments];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "The graph flexes at runtime depending on the source content on which the envelope operates. A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " doesn’t constrain the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/evaluate(x:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function’s output to predertermined values. Instead, PHASE applies the envelope’s curves to the source content as a rate of change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition": {
      "abstract": [
        {
          "text": "A node that smoothly fades between the audio of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEBlendNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseblendnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition/addRange(envelope:subtree:)": {
      "abstract": [
        {
          "text": "Adds a child node with an envelope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "envelope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEEnvelope",
          "text": "PHASEEnvelope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subtree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition/addRange(envelope:subtree:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addRangeWithEnvelope:subtree:"
        }
      ],
      "role": "symbol",
      "title": "addRange(envelope:subtree:)",
      "type": "topic",
      "url": "/documentation/phase/phaseblendnodedefinition/addrange(envelope:subtree:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType": {
      "abstract": [
        {
          "text": "Options that apply a mathematical function to an input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECurveType"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveType"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope": {
      "abstract": [
        {
          "text": "A collection of segments that connect to graph a complex curve over a linear input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEEnvelope"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEEnvelope"
        }
      ],
      "role": "symbol",
      "title": "PHASEEnvelope",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/domain": {
      "abstract": [
        {
          "text": "The range of the envelope’s possible input values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASENumericPair",
          "text": "PHASENumericPair"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/domain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "role": "symbol",
      "title": "domain",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope/domain"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/evaluate(x:)": {
      "abstract": [
        {
          "text": "Provides the height of the envelope for an input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/evaluate(x:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluateForValue:"
        }
      ],
      "role": "symbol",
      "title": "evaluate(x:)",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope/evaluate(x:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/init(startPoint:segments:)": {
      "abstract": [
        {
          "text": "Creates an envelope with a start point and segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "startPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "segments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEEnvelopeSegment",
          "text": "PHASEEnvelopeSegment"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/init(startPoint:segments:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithStartPoint:segments:"
        }
      ],
      "role": "symbol",
      "title": "init(startPoint:segments:)",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope/init(startpoint:segments:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/range": {
      "abstract": [
        {
          "text": "The bounds of the output value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASENumericPair",
          "text": "PHASENumericPair"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "range"
        }
      ],
      "role": "symbol",
      "title": "range",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope/range"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/segments": {
      "abstract": [
        {
          "text": "An array of the envelope’s segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEEnvelopeSegment",
          "text": "PHASEEnvelopeSegment"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/segments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segments"
        }
      ],
      "role": "symbol",
      "title": "segments",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope/segments"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/startPoint": {
      "abstract": [
        {
          "text": "The starting point along the envelope’s duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/startPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startPoint"
        }
      ],
      "role": "symbol",
      "title": "startPoint",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelope/startpoint"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters": {
      "abstract": [
        {
          "text": "A graph of points and curves that shapes the volume of a sound over distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEEnvelopeDistanceModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEEnvelopeDistanceModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEEnvelopeDistanceModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelopedistancemodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeSegment": {
      "abstract": [
        {
          "text": "A curved portion of an envelope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEEnvelopeSegment"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEEnvelopeSegment"
        }
      ],
      "role": "symbol",
      "title": "PHASEEnvelopeSegment",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelopesegment"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEMappedMetaParameterDefinition": {
      "abstract": [
        {
          "text": "A metaparameter that graphs an input value on a set of mathematical curves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEMappedMetaParameterDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMappedMetaParameterDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEMappedMetaParameterDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEMappedMetaParameterDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasemappedmetaparameterdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASENumericPair": {
      "abstract": [
        {
          "text": "An ordered pair that defines a bounding box for an envelope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASENumericPair"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASENumericPair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASENumericPair"
        }
      ],
      "role": "symbol",
      "title": "PHASENumericPair",
      "type": "topic",
      "url": "/documentation/phase/phasenumericpair"
    },
    "doc://com.apple.phase/documentation/PHASE/playback-parameterization": {
      "abstract": [
        {
          "text": "Change the characteristics of in-flight audio by adjusting its properties at runtime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/playback-parameterization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Playback Parameterization",
      "type": "topic",
      "url": "/documentation/phase/playback-parameterization"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Dynamic-Sound-Control",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeSegment",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType",
        "doc://com.apple.phase/documentation/PHASE/PHASENumericPair",
        "doc://com.apple.phase/documentation/PHASE/playback-parameterization"
      ],
      "title": "Dynamic Sound Control"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Envelope",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/init(startPoint:segments:)"
      ],
      "title": "Creating an Envelope"
    },
    {
      "anchor": "Inspecting-the-Envelope",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/evaluate(x:)",
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/segments",
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/startPoint"
      ],
      "title": "Inspecting the Envelope"
    },
    {
      "anchor": "Bounding-the-Input",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/domain",
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/range"
      ],
      "title": "Bounding the Input"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEEnvelope"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Envelope",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/init(startPoint:segments:)"
              ],
              "title": "Creating an Envelope"
            },
            {
              "anchor": "Inspecting-the-Envelope",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/evaluate(x:)",
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/segments",
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/startPoint"
              ],
              "title": "Inspecting the Envelope"
            },
            {
              "anchor": "Bounding-the-Input",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/domain",
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelope/range"
              ],
              "title": "Bounding the Input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Dynamic-Sound-Control",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeSegment",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType",
                "doc://com.apple.phase/documentation/PHASE/PHASENumericPair",
                "doc://com.apple.phase/documentation/PHASE/playback-parameterization"
              ],
              "title": "Dynamic Sound Control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASEEnvelope"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeSegment/title",
          "value": "PHASEEnvelopeSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelopeSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeSegment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelopeSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1evaluate(x:)/title",
          "value": "evaluateForValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1evaluate(x:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "evaluateForValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1segments/title",
          "value": "segments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1segments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "segments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/title",
          "value": "PHASEBlendNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1domain/title",
          "value": "domain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1domain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType/title",
          "value": "PHASECurveType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeDistanceModelParameters/title",
          "value": "PHASEEnvelopeDistanceModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeDistanceModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelopeDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeDistanceModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelopeDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMappedMetaParameterDefinition/title",
          "value": "PHASEMappedMetaParameterDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMappedMetaParameterDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMappedMetaParameterDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMappedMetaParameterDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMappedMetaParameterDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1range/title",
          "value": "range"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope/title",
          "value": "PHASEEnvelope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1init(startPoint:segments:)/title",
          "value": "initWithStartPoint:segments:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1init(startPoint:segments:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStartPoint:segments:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1startPoint/title",
          "value": "startPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelope~1startPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASENumericPair/title",
          "value": "PHASENumericPair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASENumericPair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASENumericPair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASENumericPair/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASENumericPair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition~1addRange(envelope:subtree:)/title",
          "value": "addRangeWithEnvelope:subtree:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition~1addRange(envelope:subtree:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addRangeWithEnvelope:subtree:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phaseenvelope"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phaseenvelope"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
