{
  "abstract": [
    {
      "text": "An object that manages competing sounds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEDucker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASEDucker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASEDucker"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEDucker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASEDucker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a sound plays in any of the source groups, this class lowers the volume of all the target groups so the listener hears the source sound more clearly. You set the source and target using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects; see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/sourceGroups",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/targetGroups",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Lower-Background-Music-During-a-Monologue",
          "level": 3,
          "text": "Lower Background Music During a Monologue",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When an app plays a monologue, the background music may need to lower, or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "duck",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", to enhance the clarity of the vocals. The following code demonstrates a ducker that configures a group for background music, and another group for the vocals.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let bgmGroup = PHASEGroup(identifier: \"backgroundMusicGroup\")",
                    "let voGroup = PHASEGroup(identifier: \"voiceOverGroup\")",
                    "",
                    "let ducker = PHASEDucker(engine: myEngine, sourceGroups: [voGroup],",
                    "    targetGroups: [bgmGroup], gain: 0.25, attackTime: 0.25, releaseTime: 0.5,",
                    "    attackCurve: .linear, releaseCurve: .linear)",
                    "",
                    "ducker.activate()"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "PHASEGroup* bgmGroup = [[PHASEGroup alloc] ",
                    "    initWithEngine:_objects->mEngine uid:@\"backgroundMusicGroup\"];",
                    "PHASEGroup* voGroup = [[PHASEGroup alloc] ",
                    "    initWithEngine:_objects->mEngine uid:@\"voiceOverGroup\"];",
                    "",
                    "auto ducker = [[PHASEDucker alloc] ",
                    "    initWithEngine:_objects->mEngine",
                    "        sourceGroups:[NSSet setWithObject:voGroup]",
                    "        targetGroups:[NSSet setWithObject:bgmGroup]",
                    "        gain:0.25",
                    "        attackTime:0.25",
                    "        releaseTime:0.5",
                    "        attackCurve:PHASECurveTypeLinear",
                    "        releaseCurve:PHASECurveTypeLinear];",
                    "",
                    "[ducker activate];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "When an app sets up the ducking configuration in advance, PHASE automatically lowers the background music at runtime when the vocals play.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker": {
      "abstract": [
        {
          "text": "An object that manages competing sounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDucker"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDucker"
        }
      ],
      "role": "symbol",
      "title": "PHASEDucker",
      "type": "topic",
      "url": "/documentation/phase/phaseducker"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/activate()": {
      "abstract": [
        {
          "text": "Instructs the ducker to begin altering sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/activate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activate"
        }
      ],
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/activate()"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackCurve": {
      "abstract": [
        {
          "text": "A mathematical curve that shapes transition progress as sound reduction begins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attackCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASECurveType",
          "text": "PHASECurveType"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attackCurve"
        }
      ],
      "role": "symbol",
      "title": "attackCurve",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/attackcurve"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackTime": {
      "abstract": [
        {
          "text": "The amount of time for sound reduction to reach maximum strength.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attackTime"
        }
      ],
      "role": "symbol",
      "title": "attackTime",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/attacktime"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/deactivate()": {
      "abstract": [
        {
          "text": "Stops the ducker from altering sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/deactivate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deactivate"
        }
      ],
      "role": "symbol",
      "title": "deactivate()",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/deactivate()"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/gain": {
      "abstract": [
        {
          "text": "The amount of volume reduction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/gain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gain"
        }
      ],
      "role": "symbol",
      "title": "gain",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/gain"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/identifier": {
      "abstract": [
        {
          "text": "A unique value for the ducker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/identifier"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)": {
      "abstract": [
        {
          "text": "Creates an object that manages competing sounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "engine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEEngine",
          "text": "PHASEEngine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGroup",
          "text": "PHASEGroup"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "targetGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGroup",
          "text": "PHASEGroup"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "releaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attackCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASECurveType",
          "text": "PHASECurveType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "releaseCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASECurveType",
          "text": "PHASECurveType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEngine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:"
        }
      ],
      "role": "symbol",
      "title": "init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/init(engine:sourcegroups:targetgroups:gain:attacktime:releasetime:attackcurve:releasecurve:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/isActive": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the ducker reduces sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/isActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "role": "symbol",
      "title": "isActive",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/isactive"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseCurve": {
      "abstract": [
        {
          "text": "A mathematical curve that shapes transition progress as sound reduction ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "releaseCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASECurveType",
          "text": "PHASECurveType"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "releaseCurve"
        }
      ],
      "role": "symbol",
      "title": "releaseCurve",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/releasecurve"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseTime": {
      "abstract": [
        {
          "text": "The amount of time to transition from maximum sound reduction to no reduction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "releaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "releaseTime"
        }
      ],
      "role": "symbol",
      "title": "releaseTime",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/releasetime"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/sourceGroups": {
      "abstract": [
        {
          "text": "The sounds that determine volume reduction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGroup",
          "text": "PHASEGroup"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/sourceGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceGroups"
        }
      ],
      "role": "symbol",
      "title": "sourceGroups",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/sourcegroups"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDucker/targetGroups": {
      "abstract": [
        {
          "text": "The sounds that reduce in volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGroup",
          "text": "PHASEGroup"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDucker/targetGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetGroups"
        }
      ],
      "role": "symbol",
      "title": "targetGroups",
      "type": "topic",
      "url": "/documentation/phase/phaseducker/targetgroups"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroup": {
      "abstract": [
        {
          "text": "A container that shares audio parameters with a collection of sounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGroup"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGroup"
        }
      ],
      "role": "symbol",
      "title": "PHASEGroup",
      "type": "topic",
      "url": "/documentation/phase/phasegroup"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset": {
      "abstract": [
        {
          "text": "A collection of settings for groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGroupPreset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGroupPreset"
        }
      ],
      "role": "symbol",
      "title": "PHASEGroupPreset",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppreset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting": {
      "abstract": [
        {
          "text": "Settings for group presets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGroupPresetSetting"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGroupPresetSetting"
        }
      ],
      "role": "symbol",
      "title": "PHASEGroupPresetSetting",
      "type": "topic",
      "url": "/documentation/phase/phasegrouppresetsetting"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sound-Grouping-and-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset",
        "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting"
      ],
      "title": "Sound Grouping and Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Ducker",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)"
      ],
      "title": "Creating a Ducker"
    },
    {
      "anchor": "Specifying-Sounds",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/sourceGroups",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/targetGroups"
      ],
      "title": "Specifying Sounds"
    },
    {
      "anchor": "Configuring-Volume-Reduction",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/gain",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/identifier",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/isActive",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackTime",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackCurve",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseTime",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseCurve"
      ],
      "title": "Configuring Volume Reduction"
    },
    {
      "anchor": "Altering-Sound",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/activate()",
        "doc://com.apple.phase/documentation/PHASE/PHASEDucker/deactivate()"
      ],
      "title": "Altering Sound"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEDucker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Ducker",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)"
              ],
              "title": "Creating a Ducker"
            },
            {
              "anchor": "Specifying-Sounds",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/sourceGroups",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/targetGroups"
              ],
              "title": "Specifying Sounds"
            },
            {
              "anchor": "Configuring-Volume-Reduction",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/gain",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/identifier",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/isActive",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackTime",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/attackCurve",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseTime",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/releaseCurve"
              ],
              "title": "Configuring Volume Reduction"
            },
            {
              "anchor": "Altering-Sound",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/activate()",
                "doc://com.apple.phase/documentation/PHASE/PHASEDucker/deactivate()"
              ],
              "title": "Altering Sound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sound-Grouping-and-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGroup",
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPreset",
                "doc://com.apple.phase/documentation/PHASE/PHASEGroupPresetSetting"
              ],
              "title": "Sound Grouping and Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASEDucker"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker/title",
          "value": "PHASEDucker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDucker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset/title",
          "value": "PHASEGroupPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1deactivate()/title",
          "value": "deactivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1deactivate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deactivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1targetGroups/title",
          "value": "targetGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1targetGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)/title",
          "value": "initWithEngine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1init(engine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEngine:sourceGroups:targetGroups:gain:attackTime:releaseTime:attackCurve:releaseCurve:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1attackCurve/title",
          "value": "attackCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1attackCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attackCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1gain/title",
          "value": "gain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1gain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1sourceGroups/title",
          "value": "sourceGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1sourceGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1releaseCurve/title",
          "value": "releaseCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1releaseCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "releaseCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1attackTime/title",
          "value": "attackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1attackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1releaseTime/title",
          "value": "releaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1releaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "releaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1isActive/title",
          "value": "active"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1isActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "active"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroup/title",
          "value": "PHASEGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPresetSetting/title",
          "value": "PHASEGroupPresetSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPresetSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPresetSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGroupPresetSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGroupPresetSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1activate()/title",
          "value": "activate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDucker~1activate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phaseducker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phaseducker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
