{
  "abstract": [
    {
      "text": "An audio-layering object that produces environmental effects and plays sound with a 3D position and orientation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASESpatialMixerDefinition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASESpatialMixerDefinition"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASESpatialMixerDefinition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASESpatialMixerDefinition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class enables the app to define a relationship between a source and listener in six degrees of freedom: orientation (roll, pitch, yaw) and a 3D position (x, y, z).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The framework plays back an audio source with ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "distance modeling",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/distanceModelParameters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), direct path transmission effects and any combination of environmental effects, such as reverb (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), and directivity (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/listenerDirectivityModelParameters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). ",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The result enables an app to implement directive point or omnidirectional sound sources — with or without direction, respectively — and volumetric sources with a defined shape.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For a walkthrough of spatial mixing, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition": {
      "abstract": [
        {
          "text": "An object to initialize a mixer with a given configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasemixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition": {
      "abstract": [
        {
          "text": "An audio-layering object that produces environmental effects and plays sound with a 3D position and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/distanceModelParameters": {
      "abstract": [
        {
          "text": "An effect that changes sound as it carries over a distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceModelParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEDistanceModelParameters",
          "text": "PHASEDistanceModelParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/distanceModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distanceModelParameters"
        }
      ],
      "role": "symbol",
      "title": "distanceModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/distancemodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)": {
      "abstract": [
        {
          "text": "Creates a mixer with the designated spatial pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "spatialPipeline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
          "text": "PHASESpatialPipeline"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSpatialPipeline:"
        }
      ],
      "role": "symbol",
      "title": "init(spatialPipeline:)",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/init(spatialpipeline:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:identifier:)": {
      "abstract": [
        {
          "text": "Creates a named mixer with the designated spatial pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "spatialPipeline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
          "text": "PHASESpatialPipeline"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSpatialPipeline:identifier:"
        }
      ],
      "role": "symbol",
      "title": "init(spatialPipeline:identifier:)",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/init(spatialpipeline:identifier:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/listenerDirectivityModelParameters": {
      "abstract": [
        {
          "text": "A data set that determines how well the listener hears depending on its direction relative to a sound source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listenerDirectivityModelParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEDirectivityModelParameters",
          "text": "PHASEDirectivityModelParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/listenerDirectivityModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listenerDirectivityModelParameters"
        }
      ],
      "role": "symbol",
      "title": "listenerDirectivityModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/listenerdirectivitymodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/sourceDirectivityModelParameters": {
      "abstract": [
        {
          "text": "A data set that directs sound such that it’s louder when directed at the listener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDirectivityModelParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEDirectivityModelParameters",
          "text": "PHASEDirectivityModelParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/sourceDirectivityModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceDirectivityModelParameters"
        }
      ],
      "role": "symbol",
      "title": "sourceDirectivityModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/sourcedirectivitymodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline": {
      "abstract": [
        {
          "text": "An object that adds sound layers for environmental effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialPipeline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
          "text": "PHASESpatialPipeline"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spatialPipeline"
        }
      ],
      "role": "symbol",
      "title": "spatialPipeline",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/spatialpipeline"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline": {
      "abstract": [
        {
          "text": "An object that specifies the volume of optional environmental effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialPipeline"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialPipeline"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialPipeline",
      "type": "topic",
      "url": "/documentation/phase/phasespatialpipeline"
    },
    "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene": {
      "abstract": [
        {
          "text": "Position sound from a specific direction and automatically raise or lower volume based on the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene",
      "kind": "article",
      "role": "article",
      "title": "Playing sound from a location in a 3D scene",
      "type": "topic",
      "url": "/documentation/phase/playing-sound-from-a-location-in-a-3d-scene"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Spatial-Mixer",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:identifier:)"
      ],
      "title": "Creating a Spatial Mixer"
    },
    {
      "anchor": "Setting-a-Pipeline",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline"
      ],
      "title": "Setting a Pipeline"
    },
    {
      "anchor": "Changing-Sound-Over-Distance",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/distanceModelParameters"
      ],
      "title": "Changing Sound Over Distance"
    },
    {
      "anchor": "Configuring-Directivity",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/listenerDirectivityModelParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/sourceDirectivityModelParameters"
      ],
      "title": "Configuring Directivity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASESpatialMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Spatial-Mixer",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:identifier:)"
              ],
              "title": "Creating a Spatial Mixer"
            },
            {
              "anchor": "Setting-a-Pipeline",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline"
              ],
              "title": "Setting a Pipeline"
            },
            {
              "anchor": "Changing-Sound-Over-Distance",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/distanceModelParameters"
              ],
              "title": "Changing Sound Over Distance"
            },
            {
              "anchor": "Configuring-Directivity",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/listenerDirectivityModelParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/sourceDirectivityModelParameters"
              ],
              "title": "Configuring Directivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASESpatialMixerDefinition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHASEMixerDefinition",
                    "text": "PHASEMixerDefinition"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1listenerDirectivityModelParameters/title",
          "value": "listenerDirectivityModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1listenerDirectivityModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "listenerDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/title",
          "value": "PHASESpatialMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1spatialPipeline/title",
          "value": "spatialPipeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1spatialPipeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/title",
          "value": "PHASESpatialPipeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1sourceDirectivityModelParameters/title",
          "value": "sourceDirectivityModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1sourceDirectivityModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1init(spatialPipeline:identifier:)/title",
          "value": "initWithSpatialPipeline:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1init(spatialPipeline:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSpatialPipeline:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1distanceModelParameters/title",
          "value": "distanceModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1distanceModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1init(spatialPipeline:)/title",
          "value": "initWithSpatialPipeline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1init(spatialPipeline:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSpatialPipeline:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixerDefinition/title",
          "value": "PHASEMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMixerDefinition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasespatialmixerdefinition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasespatialmixerdefinition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
