{
  "abstract": [
    {
      "text": "Options that inform PHASE of an audio-stream buffer’s playback priority.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHASEPushStreamBufferOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASEPushStreamBufferOptions"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEPushStreamBufferOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PHASEPushStreamBufferOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your app provides audio buffers that PHASE plays through a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", use this structure to inform PHASE of a particular buffer’s priority.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Associate an option to a particular buffer by passing it in to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode/scheduleBuffer(buffer:time:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode": {
      "abstract": [
        {
          "text": "Calibration options for sound pressure level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECalibrationMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECalibrationMode"
        }
      ],
      "role": "symbol",
      "title": "PHASECalibrationMode",
      "type": "topic",
      "url": "/documentation/phase/phasecalibrationmode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for nodes that provide audio data to generate sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGeneratorNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGeneratorNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEGeneratorNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasegeneratornodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode": {
      "abstract": [
        {
          "text": "Loop options for audio playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPlaybackMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPlaybackMode"
        }
      ],
      "role": "symbol",
      "title": "PHASEPlaybackMode",
      "type": "topic",
      "url": "/documentation/phase/phaseplaybackmode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions": {
      "abstract": [
        {
          "text": "Options that inform PHASE of an audio-stream buffer’s playback priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamBufferOptions",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default": {
      "abstract": [
        {
          "text": "Indicates a buffer processes after existing buffers in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/default"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a push stream buffer option with the given raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/init(rawvalue:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts": {
      "abstract": [
        {
          "text": "Indicates a buffer begins processing immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interrupts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferInterrupts"
        }
      ],
      "role": "symbol",
      "title": "interrupts",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/interrupts"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop": {
      "abstract": [
        {
          "text": "Indicates a buffer begins processing when an existing buffer loops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interruptsAtLoop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferInterruptsAtLoop"
        }
      ],
      "role": "symbol",
      "title": "interruptsAtLoop",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/interruptsatloop"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops": {
      "abstract": [
        {
          "text": "Indicates a buffer restarts after it finishes processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferLoops"
        }
      ],
      "role": "symbol",
      "title": "loops",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/loops"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode": {
      "abstract": [
        {
          "text": "An audio stream you manage to provide a sound buffer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNode"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamNode",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreamnode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode/scheduleBuffer(buffer:time:options:)": {
      "abstract": [
        {
          "text": "Schedules audio data playback at a specific time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "buffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioPCMBuffer",
          "text": "AVAudioPCMBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioTime",
          "text": "AVAudioTime"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode/scheduleBuffer(buffer:time:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduleBuffer:atTime:options:"
        }
      ],
      "role": "symbol",
      "title": "scheduleBuffer(buffer:time:options:)",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreamnode/schedulebuffer(buffer:time:options:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays a sequence of audio buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreamnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays complete audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESamplerNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESamplerNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESamplerNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesamplernodedefinition"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Providing-Nodes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
        "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode",
        "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition"
      ],
      "title": "Audio-Providing Nodes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Option",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/init(rawValue:)"
      ],
      "title": "Creating an Option"
    },
    {
      "anchor": "Options",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEPushStreamBufferOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Options",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Providing-Nodes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
                "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode",
                "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition"
              ],
              "title": "Audio-Providing Nodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASEPushStreamBufferOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/title",
          "value": "PHASEPushStreamBufferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interruptsAtLoop/title",
          "value": "PHASEPushStreamBufferInterruptsAtLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interruptsAtLoop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferInterruptsAtLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPlaybackMode/title",
          "value": "PHASEPlaybackMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPlaybackMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPlaybackMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPlaybackMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPlaybackMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECalibrationMode/title",
          "value": "PHASECalibrationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECalibrationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECalibrationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECalibrationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECalibrationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNodeDefinition/title",
          "value": "PHASEPushStreamNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode~1scheduleBuffer(buffer:time:options:)/title",
          "value": "scheduleBuffer:atTime:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode~1scheduleBuffer(buffer:time:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scheduleBuffer:atTime:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1default/title",
          "value": "PHASEPushStreamBufferDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/title",
          "value": "PHASEGeneratorNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeneratorNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeneratorNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interrupts/title",
          "value": "PHASEPushStreamBufferInterrupts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interrupts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferInterrupts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode/title",
          "value": "PHASEPushStreamNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/title",
          "value": "PHASESamplerNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESamplerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESamplerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1loops/title",
          "value": "PHASEPushStreamBufferLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1loops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferLoops"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasepushstreambufferoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasepushstreambufferoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
