{
  "abstract": [
    {
      "text": "A sound event node that invokes one of its child nodes at random.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASERandomNodeDefinition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASERandomNodeDefinition"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASERandomNodeDefinition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASERandomNodeDefinition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the framework invokes a random node, it passes the invocation on to one of its children at random. The weight you choose for a child node in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/addSubtree(_:weight:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " argument skews the node’s selection chances.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-from-Alternate-Sounds",
          "level": 3,
          "text": "Choose from Alternate Sounds",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class can model real-world cases where an event varies slightly, such as when footsteps sound slightly different because of the unique ground composition at each step.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3918860",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code creates an instance of this class that selects from three different footstep sounds. The weights determine that an uncommon footstep noise plays half as frequently as the common footstep. And a third footstep noise plays 10% of the time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// Create several nodes from prior-registered footstep sound assets.",
                    "let footstep1 = PHASESamplerNodeDefinition(",
                    "    soundAssetIdentifier: \"footstep1\",",
                    "    mixerDefinition: myMixer, identifier: \"footstep1\")",
                    "let footstep2 = PHASESamplerNodeDefinition(",
                    "    soundAssetIdentifier: \"footstep2\",",
                    "    mixerDefinition: myMixer, identifier: \"footstep2\")",
                    "let footstep3 = PHASESamplerNodeDefinition(",
                    "    soundAssetIdentifier: \"footstep3\",    ",
                    "    mixerDefinition: myMixer, identifier: \"footstep3\")",
                    "",
                    "// Create the random node.",
                    "let randomNode = PHASERandomNodeDefinition(identifier: \"randomNode\")",
                    "",
                    "// Connect leaf nodes to the tree and set the weights. ",
                    "randomNode.addSubtree(footstep1, weight: 10)",
                    "randomNode.addSubtree(footstep2, weight: 5)",
                    "randomNode.addSubtree(footstep3, weight: 1)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// Create several nodes from prior-registered footstep sound assets.",
                    "PHASESamplerNodeDefinition* footstep1 = ",
                    "    [[PHASESamplerNodeDefinition alloc] ",
                    "        initWithSoundAssetUID:@\"footstep1\" ",
                    "        mixerDefinition:mixNode uid:@\"footstep1\"];",
                    "PHASESamplerNodeDefinition* footstep2 = ",
                    "    [[PHASESamplerNodeDefinition alloc] ",
                    "        initWithSoundAssetUID:@\"footstep2\" ",
                    "        mixerDefinition:mixNode uid:@\"footstep2\"];",
                    "PHASESamplerNodeDefinition* footstep3 = ",
                    "    [[PHASESamplerNodeDefinition alloc] ",
                    "        initWithSoundAssetUID:@\"footstep3\" ",
                    "        mixerDefinition:mixNode uid:@\"footstep3\"];",
                    "",
                    "// Create the random node.",
                    "PHASERandomNodeDefinition* randomNode = ",
                    "    [[PHASERandomNodeDefinition alloc] initWithUID:@\"randomNode\"];",
                    "",
                    "// Connect leaf nodes to the tree and set the weights. ",
                    "[randomNode addSubtree:footstep1 weight:@10];",
                    "[randomNode addSubtree:footstep2 weight:@5];",
                    "[randomNode addSubtree:footstep3 weight:@1];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition": {
      "abstract": [
        {
          "text": "A node that smoothly fades between the audio of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEBlendNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseblendnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays all its children at the same time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEContainerNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEContainerNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEContainerNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasecontainernodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition": {
      "abstract": [
        {
          "text": "A sound event node that invokes one of its child nodes at random.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASERandomNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASERandomNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASERandomNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/addSubtree(_:weight:)": {
      "abstract": [
        {
          "text": "Adds a node tree that’s one of the random-selection options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSubtree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/addSubtree(_:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSubtree:weight:"
        }
      ],
      "role": "symbol",
      "title": "addSubtree(_:weight:)",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition/addsubtree(_:weight:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init()": {
      "abstract": [
        {
          "text": "Creates a random node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition/init()"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init(identifier:)": {
      "abstract": [
        {
          "text": "Creates a random node with the name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init(identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:)",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition/init(identifier:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/uniqueSelectionQueueLength": {
      "abstract": [
        {
          "text": "The length of the unique selection queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueSelectionQueueLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/uniqueSelectionQueueLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueSelectionQueueLength"
        }
      ],
      "role": "symbol",
      "title": "uniqueSelectionQueueLength",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition/uniqueselectionqueuelength"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for sound event nodes that connect to form a node hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition": {
      "abstract": [
        {
          "text": "A node that passes invocation to only one of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESwitchNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESwitchNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESwitchNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseswitchnodedefinition"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3918860": {
      "alt": "Illustration of a flowchart that represents a sound event node tree. The chart contains three boxes, which represent nodes. At left, a box labeled Random Node extends an arrow, which points to a box in the upper right that’s labeled Sampler Node Footstep Variation One. The box labeled Random Node extends another arrow, which points to a box in the lower right that’s labeled Sampler Node Footstep Variation Two. ",
      "identifier": "media-3918860",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3e7605629beec5855ca52d33b3bf11de/media-3918860@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d2e65cdc0965a0d56a46c3f03efd9f90/media-3918860~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Control-Nodes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition"
      ],
      "title": "Control Nodes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Node",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init()",
        "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init(identifier:)"
      ],
      "title": "Creating a Node"
    },
    {
      "anchor": "Adding-Descendent-Nodes",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/addSubtree(_:weight:)"
      ],
      "title": "Adding Descendent Nodes"
    },
    {
      "anchor": "Defining-Selection-Queue-Length",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/uniqueSelectionQueueLength"
      ],
      "title": "Defining Selection Queue Length"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASERandomNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Node",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init()",
                "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/init(identifier:)"
              ],
              "title": "Creating a Node"
            },
            {
              "anchor": "Adding-Descendent-Nodes",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/addSubtree(_:weight:)"
              ],
              "title": "Adding Descendent Nodes"
            },
            {
              "anchor": "Defining-Selection-Queue-Length",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition/uniqueSelectionQueueLength"
              ],
              "title": "Defining Selection Queue Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Control-Nodes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition"
              ],
              "title": "Control Nodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASERandomNodeDefinition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
                    "text": "PHASESoundEventNodeDefinition"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1init(identifier:)/title",
          "value": "initWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1init(identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1addSubtree(_:weight:)/title",
          "value": "addSubtree:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1addSubtree(_:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addSubtree:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/title",
          "value": "PHASEContainerNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEContainerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEContainerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/title",
          "value": "PHASESwitchNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESwitchNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESwitchNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/title",
          "value": "PHASESoundEventNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/title",
          "value": "PHASEBlendNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1uniqueSelectionQueueLength/title",
          "value": "uniqueSelectionQueueLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1uniqueSelectionQueueLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueSelectionQueueLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/title",
          "value": "PHASERandomNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phaserandomnodedefinition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phaserandomnodedefinition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
