{
  "abstract": [
    {
      "text": "A central repository of audio assets.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASEAssetRegistry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHASEAssetRegistry"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEAssetRegistry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHASEAssetRegistry"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHASEAssetRegistry"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class manages audio by registering two types of assets throughout the app’s life cycle:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A sound asset identifies the particular audio data that your app intends to play.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A sound event asset provides audio with an avenue to the output device, and either represents a single sound or a dynamic set of sounds that play individually, depending on the app’s state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re done with a sound asset, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/unregisterAsset(identifier:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to free up its system resources.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry": {
      "abstract": [
        {
          "text": "A central repository of audio assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEAssetRegistry"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEAssetRegistry"
        }
      ],
      "role": "symbol",
      "title": "PHASEAssetRegistry",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/asset(forIdentifier:)": {
      "abstract": [
        {
          "text": "Provides the asset named with the designated identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEAsset",
          "text": "PHASEAsset"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/asset(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "asset(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/asset(foridentifier:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/globalMetaParameters": {
      "abstract": [
        {
          "text": "A dictionary of metaparameters that all sound event assets share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "globalMetaParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEMetaParameter",
          "text": "PHASEMetaParameter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/globalMetaParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "globalMetaParameters"
        }
      ],
      "role": "symbol",
      "title": "globalMetaParameters",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/globalmetaparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerGlobalMetaParameter(metaParameterDefinition:)": {
      "abstract": [
        {
          "text": "Registers a global metaparameter with the asset registry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerGlobalMetaParameter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metaParameterDefinition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEMetaParameterDefinition",
          "text": "PHASEMetaParameterDefinition"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEGlobalMetaParameterAsset",
          "text": "PHASEGlobalMetaParameterAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerGlobalMetaParameter(metaParameterDefinition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerGlobalMetaParameter:error:"
        }
      ],
      "role": "symbol",
      "title": "registerGlobalMetaParameter(metaParameterDefinition:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/registerglobalmetaparameter(metaparameterdefinition:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(data:identifier:format:normalizationMode:)": {
      "abstract": [
        {
          "text": "Loads a sound asset from memory and adds it to the engine’s list of registered assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerSoundAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioFormat",
          "text": "AVAudioFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "normalizationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASENormalizationMode",
          "text": "PHASENormalizationMode"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundAsset",
          "text": "PHASESoundAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(data:identifier:format:normalizationMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerSoundAssetWithData:identifier:format:normalizationMode:error:"
        }
      ],
      "role": "symbol",
      "title": "registerSoundAsset(data:identifier:format:normalizationMode:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/registersoundasset(data:identifier:format:normalizationmode:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)": {
      "abstract": [
        {
          "text": "Loads a sound asset from the argument URL and adds it to the engine’s list of registered assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerSoundAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "assetType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASEAsset",
          "text": "PHASEAsset"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEAssetType",
          "text": "AssetType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "channelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioChannelLayout",
          "text": "AVAudioChannelLayout"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "normalizationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASENormalizationMode",
          "text": "PHASENormalizationMode"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundAsset",
          "text": "PHASESoundAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerSoundAssetAtURL:identifier:assetType:channelLayout:normalizationMode:error:"
        }
      ],
      "role": "symbol",
      "title": "registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/registersoundasset(url:identifier:assettype:channellayout:normalizationmode:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)": {
      "abstract": [
        {
          "text": "Registers the root node of the sound event asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerSoundEventAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rootNode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeAsset",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerSoundEventAssetWithRootNode:identifier:error:"
        }
      ],
      "role": "symbol",
      "title": "registerSoundEventAsset(rootNode:identifier:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/registersoundeventasset(rootnode:identifier:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/unregisterAsset(identifier:completion:)": {
      "abstract": [
        {
          "text": "Deallocates system memory for a given asset and removes it from the engine’s list of registered assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/unregisterAsset(identifier:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unregisterAssetWithIdentifier:completion:"
        }
      ],
      "role": "symbol",
      "title": "unregisterAsset(identifier:completion:)",
      "type": "topic",
      "url": "/documentation/phase/phaseassetregistry/unregisterasset(identifier:completion:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEngine": {
      "abstract": [
        {
          "text": "An object that manages audio assets, controls playback, and configures environmental effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEEngine"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEEngine"
        }
      ],
      "role": "symbol",
      "title": "PHASEEngine",
      "type": "topic",
      "url": "/documentation/phase/phaseengine"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEngine/UpdateMode": {
      "abstract": [
        {
          "text": "Modes that determine when the framework consumes API calls and updates internal state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UpdateMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEngine/UpdateMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UpdateMode"
        }
      ],
      "role": "symbol",
      "title": "PHASEEngine.UpdateMode",
      "type": "topic",
      "url": "/documentation/phase/phaseengine/updatemode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEMedium": {
      "abstract": [
        {
          "text": "A property or quality of the environment that affects how sound travels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEMedium"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMedium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEMedium"
        }
      ],
      "role": "symbol",
      "title": "PHASEMedium",
      "type": "topic",
      "url": "/documentation/phase/phasemedium"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASENormalizationMode": {
      "abstract": [
        {
          "text": "Options that determine whether the framework adjusts a sound asset’s loudness for the user’s output device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASENormalizationMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASENormalizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASENormalizationMode"
        }
      ],
      "role": "symbol",
      "title": "PHASENormalizationMode",
      "type": "topic",
      "url": "/documentation/phase/phasenormalizationmode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset": {
      "abstract": [
        {
          "text": "The manner in which PHASE diffuses resonating sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEReverbPreset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPreset"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset": {
      "abstract": [
        {
          "text": "A sound resource stored in the asset registry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundAsset",
      "type": "topic",
      "url": "/documentation/phase/phasesoundasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset": {
      "abstract": [
        {
          "text": "A template object for sounds that can play in reaction to environmental state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeAsset",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodeasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode": {
      "abstract": [
        {
          "text": "The manner in which PHASE outputs spatial audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatializationMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatializationMode"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatializationMode",
      "type": "topic",
      "url": "/documentation/phase/phasespatializationmode"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEEngine",
        "doc://com.apple.phase/documentation/PHASE/PHASEEngine/UpdateMode",
        "doc://com.apple.phase/documentation/PHASE/PHASENormalizationMode",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset",
        "doc://com.apple.phase/documentation/PHASE/PHASEMedium"
      ],
      "title": "Setup"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Load shared audio data that your app can access and play from any scope.",
          "type": "text"
        }
      ],
      "anchor": "Registering-Sound-Assets",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)",
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(data:identifier:format:normalizationMode:)",
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/unregisterAsset(identifier:completion:)"
      ],
      "title": "Registering Sound Assets"
    },
    {
      "abstract": [
        {
          "text": "Define playback objects that your app invokes for one-time audio output, or a sophisticated hierarchy that varies the output based on your app’s state.",
          "type": "text"
        }
      ],
      "anchor": "Registering-Sound-Event-Assets",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)",
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/asset(forIdentifier:)"
      ],
      "title": "Registering Sound Event Assets"
    },
    {
      "abstract": [
        {
          "text": "Centralize audio parameters that change the charactaristics of in-flight audio, and synchronize across multiple playback events.",
          "type": "text"
        }
      ],
      "anchor": "Registering-Global-Metaparameters",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerGlobalMetaParameter(metaParameterDefinition:)",
        "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/globalMetaParameters"
      ],
      "title": "Registering Global Metaparameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEAssetRegistry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetRegistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetRegistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Load shared audio data that your app can access and play from any scope.",
                  "type": "text"
                }
              ],
              "anchor": "Registering-Sound-Assets",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)",
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundAsset(data:identifier:format:normalizationMode:)",
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/unregisterAsset(identifier:completion:)"
              ],
              "title": "Registering Sound Assets"
            },
            {
              "abstract": [
                {
                  "text": "Define playback objects that your app invokes for one-time audio output, or a sophisticated hierarchy that varies the output based on your app’s state.",
                  "type": "text"
                }
              ],
              "anchor": "Registering-Sound-Event-Assets",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerSoundEventAsset(rootNode:identifier:)",
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/asset(forIdentifier:)"
              ],
              "title": "Registering Sound Event Assets"
            },
            {
              "abstract": [
                {
                  "text": "Centralize audio parameters that change the charactaristics of in-flight audio, and synchronize across multiple playback events.",
                  "type": "text"
                }
              ],
              "anchor": "Registering-Global-Metaparameters",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/registerGlobalMetaParameter(metaParameterDefinition:)",
                "doc://com.apple.phase/documentation/PHASE/PHASEAssetRegistry/globalMetaParameters"
              ],
              "title": "Registering Global Metaparameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEEngine",
                "doc://com.apple.phase/documentation/PHASE/PHASEEngine/UpdateMode",
                "doc://com.apple.phase/documentation/PHASE/PHASENormalizationMode",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset",
                "doc://com.apple.phase/documentation/PHASE/PHASEMedium"
              ],
              "title": "Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHASEAssetRegistry"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundEventAsset(rootNode:identifier:)/title",
          "value": "registerSoundEventAssetWithRootNode:identifier:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundEventAsset(rootNode:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerSoundEventAssetWithRootNode:identifier:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/title",
          "value": "PHASESoundEventNodeAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMedium/title",
          "value": "PHASEMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMedium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMedium/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEngine~1UpdateMode/title",
          "value": "PHASEUpdateMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEngine~1UpdateMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEUpdateMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEngine~1UpdateMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEUpdateMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1asset(forIdentifier:)/title",
          "value": "assetForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1asset(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "assetForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode/title",
          "value": "PHASESpatializationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/title",
          "value": "PHASESoundAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEngine/title",
          "value": "PHASEEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEngine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1unregisterAsset(identifier:completion:)/title",
          "value": "unregisterAssetWithIdentifier:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1unregisterAsset(identifier:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unregisterAssetWithIdentifier:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry/title",
          "value": "PHASEAssetRegistry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetRegistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAssetRegistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1globalMetaParameters/title",
          "value": "globalMetaParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1globalMetaParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "globalMetaParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset/title",
          "value": "PHASEReverbPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundAsset(data:identifier:format:normalizationMode:)/title",
          "value": "registerSoundAssetWithData:identifier:format:normalizationMode:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundAsset(data:identifier:format:normalizationMode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerSoundAssetWithData:identifier:format:normalizationMode:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerGlobalMetaParameter(metaParameterDefinition:)/title",
          "value": "registerGlobalMetaParameter:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerGlobalMetaParameter(metaParameterDefinition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerGlobalMetaParameter:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASENormalizationMode/title",
          "value": "PHASENormalizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASENormalizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASENormalizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASENormalizationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASENormalizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)/title",
          "value": "registerSoundAssetAtURL:identifier:assetType:channelLayout:normalizationMode:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAssetRegistry~1registerSoundAsset(url:identifier:assetType:channelLayout:normalizationMode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerSoundAssetAtURL:identifier:assetType:channelLayout:normalizationMode:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phaseassetregistry"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phaseassetregistry"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
