{
  "abstract": [
    {
      "text": "Objects that connect to form a hierarchical tree of audio actions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/sound-event-nodes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sound Event Nodes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To play sound, your app assembles a hieararchical structure of audio ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "nodes",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " that determine which sound to play at the moment. A tree with two sampler nodes branching from a switch node plays only one sampler, depending on your app’s state. You set the control logic in advance that specifies the conditions upon which the switch node toggles. To play the same audio consistently, create a tree with a single sampler node.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To invoke the tree, create a sound event that references the tree and call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/start(completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the sound event.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAsset": {
      "abstract": [
        {
          "text": "A base class that adds a name to framework assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASEAsset",
      "type": "topic",
      "url": "/documentation/phase/phaseasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition": {
      "abstract": [
        {
          "text": "A node that smoothly fades between the audio of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEBlendNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEBlendNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseblendnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode": {
      "abstract": [
        {
          "text": "Calibration options for sound pressure level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECalibrationMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECalibrationMode"
        }
      ],
      "role": "symbol",
      "title": "PHASECalibrationMode",
      "type": "topic",
      "url": "/documentation/phase/phasecalibrationmode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays all its children at the same time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEContainerNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEContainerNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEContainerNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasecontainernodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for nodes that provide audio data to generate sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGeneratorNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGeneratorNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEGeneratorNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasegeneratornodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode": {
      "abstract": [
        {
          "text": "Loop options for audio playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPlaybackMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPlaybackMode"
        }
      ],
      "role": "symbol",
      "title": "PHASEPlaybackMode",
      "type": "topic",
      "url": "/documentation/phase/phaseplaybackmode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions": {
      "abstract": [
        {
          "text": "Options that inform PHASE of an audio-stream buffer’s playback priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamBufferOptions",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode": {
      "abstract": [
        {
          "text": "An audio stream you manage to provide a sound buffer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNode"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamNode",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreamnode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays a sequence of audio buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreamnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition": {
      "abstract": [
        {
          "text": "A sound event node that invokes one of its child nodes at random.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASERandomNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASERandomNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASERandomNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaserandomnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition": {
      "abstract": [
        {
          "text": "A node that plays complete audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESamplerNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESamplerNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESamplerNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesamplernodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset": {
      "abstract": [
        {
          "text": "A sound resource stored in the asset registry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundAsset",
      "type": "topic",
      "url": "/documentation/phase/phasesoundasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent": {
      "abstract": [
        {
          "text": "An object that determines which audio to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEvent"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEvent"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEvent",
      "type": "topic",
      "url": "/documentation/phase/phasesoundevent"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum": {
      "abstract": [
        {
          "text": "The playback status of audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RenderingState"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RenderingState"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEvent.RenderingState",
      "type": "topic",
      "url": "/documentation/phase/phasesoundevent/renderingstate-swift.enum"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/start(completion:)": {
      "abstract": [
        {
          "text": "Invokes the sound event and runs the specified code on completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEvent",
          "text": "PHASESoundEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASESoundEventStartHandlerReason",
          "text": "StartHandlerReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/start(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "start(completion:)",
      "type": "topic",
      "url": "/documentation/phase/phasesoundevent/start(completion:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset": {
      "abstract": [
        {
          "text": "A template object for sounds that can play in reaction to environmental state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeAsset"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeAsset",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodeasset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for sound event nodes that connect to form a node hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition": {
      "abstract": [
        {
          "text": "A node that passes invocation to only one of its child nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESwitchNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESwitchNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESwitchNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseswitchnodedefinition"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Selection-and-Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
        "doc://com.apple.phase/documentation/PHASE/PHASEAsset"
      ],
      "title": "Audio Selection and Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Audio-Providing-Nodes",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
        "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode",
        "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition"
      ],
      "title": "Audio-Providing Nodes"
    },
    {
      "anchor": "Control-Nodes",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition"
      ],
      "title": "Control Nodes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Audio-Providing-Nodes",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESamplerNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEPlaybackMode",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamNode",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
                "doc://com.apple.phase/documentation/PHASE/PHASECalibrationMode",
                "doc://com.apple.phase/documentation/PHASE/PHASEGeneratorNodeDefinition"
              ],
              "title": "Audio-Providing Nodes"
            },
            {
              "anchor": "Control-Nodes",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESwitchNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASERandomNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEBlendNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition"
              ],
              "title": "Control Nodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Selection-and-Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESoundAsset",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEvent/RenderingState-swift.enum",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeAsset",
                "doc://com.apple.phase/documentation/PHASE/PHASEAsset"
              ],
              "title": "Audio Selection and Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAsset/title",
          "value": "PHASEAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode/title",
          "value": "PHASEPushStreamNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/title",
          "value": "PHASEContainerNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEContainerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEContainerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/title",
          "value": "PHASESoundEventNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/title",
          "value": "PHASEGeneratorNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeneratorNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeneratorNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeneratorNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/title",
          "value": "PHASERandomNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASERandomNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERandomNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/title",
          "value": "PHASESamplerNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESamplerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESamplerNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESamplerNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNodeDefinition/title",
          "value": "PHASEPushStreamNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/title",
          "value": "PHASESoundEventNodeAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/title",
          "value": "PHASESoundAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPlaybackMode/title",
          "value": "PHASEPlaybackMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPlaybackMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPlaybackMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPlaybackMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPlaybackMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECalibrationMode/title",
          "value": "PHASECalibrationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECalibrationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECalibrationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECalibrationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECalibrationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1start(completion:)/title",
          "value": "startWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1start(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/title",
          "value": "PHASEPushStreamBufferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1RenderingState-swift.enum/title",
          "value": "PHASERenderingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1RenderingState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERenderingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent~1RenderingState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASERenderingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent/title",
          "value": "PHASESoundEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/title",
          "value": "PHASEBlendNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEBlendNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEBlendNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/title",
          "value": "PHASESwitchNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESwitchNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESwitchNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESwitchNodeDefinition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/sound-event-nodes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/sound-event-nodes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
