{
  "abstract": [
    {
      "text": "Define environmental characteristics that determine how sound plays in your app’s 3D soundscape.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/spatial-mixing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Spatial Mixing"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Spatial mixing refers to the process by which PHASE emits one or more simultaneous sounds in 3D space and layers in optional environmental effects. For a walkthrough that demonstrates spatial mixing, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEAmbientMixerDefinition": {
      "abstract": [
        {
          "text": "An audio-layering object that outputs sound in a particular direction in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEAmbientMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEAmbientMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEAmbientMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEAmbientMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phaseambientmixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelParameters": {
      "abstract": [
        {
          "text": "An object that directs sound in a heart-shaped curve surrounding a sound source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECardioidDirectivityModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECardioidDirectivityModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASECardioidDirectivityModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasecardioiddirectivitymodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelSubbandParameters": {
      "abstract": [
        {
          "text": "A data set that projects sound of a certain frequency outward in the shape of a heart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECardioidDirectivityModelSubbandParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelSubbandParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECardioidDirectivityModelSubbandParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASECardioidDirectivityModelSubbandParameters",
      "type": "topic",
      "url": "/documentation/phase/phasecardioiddirectivitymodelsubbandparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEChannelMixerDefinition": {
      "abstract": [
        {
          "text": "An audio-layering object that routes sound directly to the device’s output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEChannelMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEChannelMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEChannelMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEChannelMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasechannelmixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelParameters": {
      "abstract": [
        {
          "text": "An object that directs sound in a cone-shaped curve that extends from a sound source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEConeDirectivityModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEConeDirectivityModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEConeDirectivityModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phaseconedirectivitymodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelSubbandParameters": {
      "abstract": [
        {
          "text": "A data set that projects sound of a certain frequency outward in the shape of a cone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEConeDirectivityModelSubbandParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelSubbandParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEConeDirectivityModelSubbandParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEConeDirectivityModelSubbandParameters",
      "type": "topic",
      "url": "/documentation/phase/phaseconedirectivitymodelsubbandparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDefinition": {
      "abstract": [
        {
          "text": "A base class that adds a name to framework definitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDirectivityModelParameters": {
      "abstract": [
        {
          "text": "A base class for objects that direct sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDirectivityModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDirectivityModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDirectivityModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEDirectivityModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasedirectivitymodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelFadeOutParameters": {
      "abstract": [
        {
          "text": "A distance over which the framework fades out sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDistanceModelFadeOutParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelFadeOutParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDistanceModelFadeOutParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEDistanceModelFadeOutParameters",
      "type": "topic",
      "url": "/documentation/phase/phasedistancemodelfadeoutparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelParameters": {
      "abstract": [
        {
          "text": "A base class for a sound’s rate of change over distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEDistanceModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEDistanceModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEDistanceModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasedistancemodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters": {
      "abstract": [
        {
          "text": "A graph of points and curves that shapes the volume of a sound over distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEEnvelopeDistanceModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEEnvelopeDistanceModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEEnvelopeDistanceModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phaseenvelopedistancemodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEGeometricSpreadingDistanceModelParameters": {
      "abstract": [
        {
          "text": "An object that dissipates sound frequencies over distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEGeometricSpreadingDistanceModelParameters"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEGeometricSpreadingDistanceModelParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEGeometricSpreadingDistanceModelParameters"
        }
      ],
      "role": "symbol",
      "title": "PHASEGeometricSpreadingDistanceModelParameters",
      "type": "topic",
      "url": "/documentation/phase/phasegeometricspreadingdistancemodelparameters"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEMixer": {
      "abstract": [
        {
          "text": "An object that combines multiple audio signals into a single signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEMixer"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEMixer"
        }
      ],
      "role": "symbol",
      "title": "PHASEMixer",
      "type": "topic",
      "url": "/documentation/phase/phasemixer"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition": {
      "abstract": [
        {
          "text": "An object to initialize a mixer with a given configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASEMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasemixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialCategory": {
      "abstract": [
        {
          "text": "Sound resonance effects for spatial mixing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialCategory"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialCategory"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialCategory",
      "type": "topic",
      "url": "/documentation/phase/phasespatialcategory"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition": {
      "abstract": [
        {
          "text": "An audio-layering object that produces environmental effects and plays sound with a 3D position and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline": {
      "abstract": [
        {
          "text": "An object that specifies the volume of optional environmental effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialPipeline"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialPipeline"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialPipeline",
      "type": "topic",
      "url": "/documentation/phase/phasespatialpipeline"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline/Flags-swift.struct": {
      "abstract": [
        {
          "text": "Sound resonance options for a spatial pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Flags"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline/Flags-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Flags"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialPipeline.Flags",
      "type": "topic",
      "url": "/documentation/phase/phasespatialpipeline/flags-swift.struct"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipelineEntry": {
      "abstract": [
        {
          "text": "An audio layer with an adjustable volume for a spatial mixer’s output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialPipelineEntry"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipelineEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialPipelineEntry"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialPipelineEntry",
      "type": "topic",
      "url": "/documentation/phase/phasespatialpipelineentry"
    },
    "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene": {
      "abstract": [
        {
          "text": "Position sound from a specific direction and automatically raise or lower volume based on the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/playing-sound-from-a-location-in-a-3d-scene",
      "kind": "article",
      "role": "article",
      "title": "Playing sound from a location in a 3D scene",
      "type": "topic",
      "url": "/documentation/phase/playing-sound-from-a-location-in-a-3d-scene"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Layering-and-Effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEChannelMixerDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEAmbientMixerDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition",
        "doc://com.apple.phase/documentation/PHASE/PHASEMixer",
        "doc://com.apple.phase/documentation/PHASE/PHASEDefinition"
      ],
      "title": "Audio Layering and Effects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setup",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition"
      ],
      "title": "Setup"
    },
    {
      "anchor": "Sound-Reflections-and-Resonance",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipelineEntry",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialCategory",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline/Flags-swift.struct"
      ],
      "title": "Sound Reflections and Resonance"
    },
    {
      "anchor": "Distance-Modeling",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEGeometricSpreadingDistanceModelParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelFadeOutParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelParameters"
      ],
      "title": "Distance Modeling"
    },
    {
      "anchor": "Sound-Directivity",
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelSubbandParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelSubbandParameters",
        "doc://com.apple.phase/documentation/PHASE/PHASEDirectivityModelParameters"
      ],
      "title": "Sound Directivity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setup",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition"
              ],
              "title": "Setup"
            },
            {
              "anchor": "Sound-Reflections-and-Resonance",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipelineEntry",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialCategory",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline/Flags-swift.struct"
              ],
              "title": "Sound Reflections and Resonance"
            },
            {
              "anchor": "Distance-Modeling",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEGeometricSpreadingDistanceModelParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASEEnvelopeDistanceModelParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelFadeOutParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASEDistanceModelParameters"
              ],
              "title": "Distance Modeling"
            },
            {
              "anchor": "Sound-Directivity",
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASECardioidDirectivityModelSubbandParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASEConeDirectivityModelSubbandParameters",
                "doc://com.apple.phase/documentation/PHASE/PHASEDirectivityModelParameters"
              ],
              "title": "Sound Directivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Layering-and-Effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEChannelMixerDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEAmbientMixerDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEMixerDefinition",
                "doc://com.apple.phase/documentation/PHASE/PHASEMixer",
                "doc://com.apple.phase/documentation/PHASE/PHASEDefinition"
              ],
              "title": "Audio Layering and Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECardioidDirectivityModelSubbandParameters/title",
          "value": "PHASECardioidDirectivityModelSubbandParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECardioidDirectivityModelSubbandParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECardioidDirectivityModelSubbandParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECardioidDirectivityModelSubbandParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECardioidDirectivityModelSubbandParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeDistanceModelParameters/title",
          "value": "PHASEEnvelopeDistanceModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeDistanceModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelopeDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEEnvelopeDistanceModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEEnvelopeDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline~1Flags-swift.struct/title",
          "value": "PHASESpatialPipelineFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline~1Flags-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipelineFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline~1Flags-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipelineFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/title",
          "value": "PHASESpatialMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEChannelMixerDefinition/title",
          "value": "PHASEChannelMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEChannelMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEChannelMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEChannelMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEChannelMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEConeDirectivityModelParameters/title",
          "value": "PHASEConeDirectivityModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEConeDirectivityModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEConeDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEConeDirectivityModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEConeDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDistanceModelParameters/title",
          "value": "PHASEDistanceModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDistanceModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDistanceModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAmbientMixerDefinition/title",
          "value": "PHASEAmbientMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAmbientMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAmbientMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEAmbientMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEAmbientMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDirectivityModelParameters/title",
          "value": "PHASEDirectivityModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDirectivityModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDirectivityModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixerDefinition/title",
          "value": "PHASEMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixer/title",
          "value": "PHASEMixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEMixer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEMixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeometricSpreadingDistanceModelParameters/title",
          "value": "PHASEGeometricSpreadingDistanceModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeometricSpreadingDistanceModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeometricSpreadingDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEGeometricSpreadingDistanceModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEGeometricSpreadingDistanceModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition/title",
          "value": "PHASEDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipelineEntry/title",
          "value": "PHASESpatialPipelineEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipelineEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipelineEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipelineEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipelineEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEConeDirectivityModelSubbandParameters/title",
          "value": "PHASEConeDirectivityModelSubbandParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEConeDirectivityModelSubbandParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEConeDirectivityModelSubbandParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEConeDirectivityModelSubbandParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEConeDirectivityModelSubbandParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDistanceModelFadeOutParameters/title",
          "value": "PHASEDistanceModelFadeOutParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDistanceModelFadeOutParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDistanceModelFadeOutParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEDistanceModelFadeOutParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEDistanceModelFadeOutParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/title",
          "value": "PHASESpatialPipeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECardioidDirectivityModelParameters/title",
          "value": "PHASECardioidDirectivityModelParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECardioidDirectivityModelParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECardioidDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECardioidDirectivityModelParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECardioidDirectivityModelParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialCategory/title",
          "value": "PHASESpatialCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/spatial-mixing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/spatial-mixing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
