{"abstract":[{"type":"text","text":"Initializes a new paste configuration with the UTIs declared as supported by a specified class."}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(forAccepting:)-6is3h","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uipasteconfiguration/init(foraccepting:)-6is3h"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uipasteconfiguration/init(foraccepting:)-6is3h"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"forAccepting","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aClass","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading","preciseIdentifier":"c:objc(pl)NSItemProviderReading","text":"NSItemProviderReading","kind":"typeIdentifier"},{"text":".Type)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A class conforming to the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading"},{"type":"text","text":" protocol."}]}],"name":"aClass"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A paste configuration initialized with acceptable uniform type identifiers (UTIs) supported by the specified class."}]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you use this initializer, the property "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading/2888305-readabletypeidentifiersforitempr"},{"type":"text","text":", implemented on "},{"code":"aClass","type":"codeVoice"},{"type":"text","text":", is used to determine the acceptable UTIs."}]}]}],"sections":[],"metadata":{"title":"init(forAccepting:)","role":"symbol","roleHeading":"Initializer","platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"11.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"11.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false}],"navigatorTitle":[{"kind":"identifier","text":"initWithTypeIdentifiersForAcceptingClass:"}],"symbolKind":"init","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAccepting"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSItemProviderReading","text":"NSItemProviderReading"},{"kind":"text","text":".Type)"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIPasteConfiguration(im)initWithTypeIdentifiersForAcceptingClass:"},"seeAlsoSections":[{"title":"Initializing a paste configuration","generated":true,"anchor":"Initializing-a-paste-configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init()","doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(acceptableTypeIdentifiers:)","doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(forAccepting:)-84r2r"]}],"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading","type":"topic","role":"symbol","url":"/documentation/foundation/nsitemproviderreading","kind":"symbol","title":"NSItemProviderReading","abstract":[{"type":"text","text":"The protocol for implementing a class to allow an item provider to create an instance of the class."}],"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSItemProviderReading"}]},"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(acceptableTypeIdentifiers:)":{"title":"init(acceptableTypeIdentifiers:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(acceptableTypeIdentifiers:)","abstract":[{"type":"text","text":"Initializes a new paste configuration with a specified array of acceptable UTIs."}],"navigatorTitle":[{"kind":"identifier","text":"initWithAcceptableTypeIdentifiers:"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acceptableTypeIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"type":"topic","role":"symbol","url":"/documentation/uikit/uipasteconfiguration/init(acceptabletypeidentifiers:)","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading":{"fragments":[{"text":"protocol ","kind":"text"},{"text":"NSItemProviderReading","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The protocol for implementing a class to allow an item provider to create an instance of the class."}],"role":"symbol","kind":"symbol","url":"/documentation/foundation/nsitemproviderreading","identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading","title":"NSItemProviderReading"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(forAccepting:)-6is3h":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(forAccepting:)-6is3h","type":"topic","role":"symbol","url":"/documentation/uikit/uipasteconfiguration/init(foraccepting:)-6is3h","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTypeIdentifiersForAcceptingClass:"}],"title":"init(forAccepting:)","abstract":[{"type":"text","text":"Initializes a new paste configuration with the UTIs declared as supported by a specified class."}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAccepting"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSItemProviderReading","text":"NSItemProviderReading"},{"kind":"text","text":".Type)"}]},"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(forAccepting:)-84r2r":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(forAccepting:)-84r2r","url":"/documentation/uikit/uipasteconfiguration/init(foraccepting:)-84r2r","title":"init(forAccepting:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"forAccepting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".Type)","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIPasteConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration","role":"symbol","url":"/documentation/uikit/uipasteconfiguration","abstract":[{"type":"text","text":"The interface that an object implements to declare its ability to accept specific data types for pasting and for drag-and-drop activities."}],"title":"UIPasteConfiguration","navigatorTitle":[{"text":"UIPasteConfiguration","kind":"identifier"}]},"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading/2888305-readabletypeidentifiersforitempr":{"fragments":[{"kind":"text","text":"static var "},{"kind":"identifier","text":"readableTypeIdentifiersForItemProvider"},{"kind":"text","text":": [String]"}],"role":"symbol","abstract":[{"text":"An array of UTI strings representing the data types supported by the class.","type":"text"}],"kind":"symbol","title":"readableTypeIdentifiersForItemProvider","url":"/documentation/foundation/nsitemproviderreading/2888305-readabletypeidentifiersforitempr","type":"topic","identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading/2888305-readabletypeidentifiersforitempr"},"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init()":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Initializes a new paste configuration."}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init()","url":"/documentation/uikit/uipasteconfiguration/init()","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1","unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"initWithTypeIdentifiersForAcceptingClass:","op":"replace","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTypeIdentifiersForAcceptingClass:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Initializing-a-paste-configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init()","doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration/init(acceptableTypeIdentifiers:)"],"title":"Initializing a paste configuration","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithTypeIdentifiersForAcceptingClass:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Class<NSItemProviderReading>","kind":"typeIdentifier","preciseIdentifier":"c:QOobjc(pl)NSItemProviderReading"},{"text":" *) ","kind":"text"},{"text":"aClass","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"name":"aClass","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A class conforming to the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading"},{"type":"text","text":" protocol."}]}]}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A paste configuration initialized with acceptable uniform type identifiers (UTIs) supported by the specified class."}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"value":"initWithAcceptableTypeIdentifiers:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration~1init(acceptableTypeIdentifiers:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptableTypeIdentifiers:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration~1init(acceptableTypeIdentifiers:)/fragments"},{"value":"initWithTypeIdentifiersForAcceptingClass:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration~1init(forAccepting:)-6is3h/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTypeIdentifiersForAcceptingClass:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration~1init(forAccepting:)-6is3h/fragments","op":"replace"},{"value":"UIPasteConfiguration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIPasteConfiguration"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration/fragments","op":"replace"},{"value":[{"text":"UIPasteConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration/navigatorTitle","op":"replace"},{"value":"init","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration~1init()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration~1init()/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}