{
  "abstract": [
    {
      "text": "Specifies a collision boundary based on the bounds of the animation reference system, with optional insets.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/setTranslatesReferenceBoundsIntoBoundary(with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UICollisionBehavior(im)setTranslatesReferenceBoundsIntoBoundaryWithInsets:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setTranslatesReferenceBoundsIntoBoundary"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@UIEdgeInsets",
        "text": "UIEdgeInsets"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setTranslatesReferenceBoundsIntoBoundary(with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setTranslatesReferenceBoundsIntoBoundary"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "insets"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@UIEdgeInsets",
              "text": "UIEdgeInsets"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Insets to apply to the reference system’s bounds when defining the collision boundary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "insets"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The result of using this method depends on how you’ve initialized the dynamic animator (of class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") that you’ve added the collision behavior to. See the overview in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a discussion of initialization options and modes for animators.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Here is how the dynamic animator’s initialization impacts use of this method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For a view-only dynamic animator, the reference bounds are those of the reference view",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For a collection-view dynamic animator, the reference bounds are those of the collection view layout",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For a dynamic-item dynamic animator, there are no reference bounds.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For a collision behavior added to a view-only or collection-view dynamic animator, activate a reference-system-based collision boundary by setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/translatesReferenceBoundsIntoBoundary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior": {
      "abstract": [
        {
          "text": "An object that confers to a specified array of dynamic items the ability to engage in collisions with each other and with the behavior’s specified boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollisionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollisionBehavior"
        }
      ],
      "role": "symbol",
      "title": "UICollisionBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:for:)": {
      "abstract": [
        {
          "text": "Adds a collision boundary, specified as a Bezier path, to the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addBoundary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBezierPath",
          "text": "UIBezierPath"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addBoundaryWithIdentifier:forPath:"
        }
      ],
      "role": "symbol",
      "title": "addBoundary(withIdentifier:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/addboundary(withidentifier:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:from:to:)": {
      "abstract": [
        {
          "text": "Adds a collision boundary, specified as a line segment, to the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addBoundary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:from:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addBoundaryWithIdentifier:fromPoint:toPoint:"
        }
      ],
      "role": "symbol",
      "title": "addBoundary(withIdentifier:from:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/addboundary(withidentifier:from:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundary(withIdentifier:)": {
      "abstract": [
        {
          "text": "Returns a specified Bezier-path boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBezierPath",
          "text": "UIBezierPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundary(withIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundaryWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "boundary(withIdentifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/boundary(withidentifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundaryIdentifiers": {
      "abstract": [
        {
          "text": "The set of boundary identifiers that you’ve added to the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundaryIdentifiers"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundaryIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundaryIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "boundaryIdentifiers",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/boundaryidentifiers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode": {
      "abstract": [
        {
          "text": "The type of edges that participate in collisions for the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollisionBehavior",
          "text": "UICollisionBehavior"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICollisionBehaviorMode",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionMode"
        }
      ],
      "role": "symbol",
      "title": "collisionMode",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/collisionmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeAllBoundaries()": {
      "abstract": [
        {
          "text": "Removes all previously-specified collision boundaries from the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllBoundaries"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeAllBoundaries()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllBoundaries"
        }
      ],
      "role": "symbol",
      "title": "removeAllBoundaries()",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/removeallboundaries()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeBoundary(withIdentifier:)": {
      "abstract": [
        {
          "text": "Removes a specific collision boundary from the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeBoundary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeBoundary(withIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeBoundaryWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "removeBoundary(withIdentifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/removeboundary(withidentifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/setTranslatesReferenceBoundsIntoBoundary(with:)": {
      "abstract": [
        {
          "text": "Specifies a collision boundary based on the bounds of the animation reference system, with optional insets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTranslatesReferenceBoundsIntoBoundary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/setTranslatesReferenceBoundsIntoBoundary(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
        }
      ],
      "role": "symbol",
      "title": "setTranslatesReferenceBoundsIntoBoundary(with:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/settranslatesreferenceboundsintoboundary(with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/translatesReferenceBoundsIntoBoundary": {
      "abstract": [
        {
          "text": "Specifies whether a boundary based on the reference system is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translatesReferenceBoundsIntoBoundary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/translatesReferenceBoundsIntoBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "translatesReferenceBoundsIntoBoundary"
        }
      ],
      "role": "symbol",
      "title": "translatesReferenceBoundsIntoBoundary",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/translatesreferenceboundsintoboundary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator": {
      "abstract": [
        {
          "text": "An object that provides physics-related capabilities and animations for its dynamic items, and provides the context for those animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicAnimator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicAnimator"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicAnimator",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicanimator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "UIEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiedgeinsets"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-collision-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:from:to:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundaryIdentifiers",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundary(withIdentifier:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeAllBoundaries()",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeBoundary(withIdentifier:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/translatesReferenceBoundsIntoBoundary"
      ],
      "title": "Configuring a collision behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-collision-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/addBoundary(withIdentifier:from:to:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundaryIdentifiers",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/boundary(withIdentifier:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeAllBoundaries()",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/removeBoundary(withIdentifier:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/translatesReferenceBoundsIntoBoundary"
              ],
              "title": "Configuring a collision behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@UIEdgeInsets",
                    "text": "UIEdgeInsets"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "insets"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Insets to apply to the reference system’s bounds when defining the collision boundary.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "insets"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1translatesReferenceBoundsIntoBoundary/title",
          "value": "translatesReferenceBoundsIntoBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1translatesReferenceBoundsIntoBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "translatesReferenceBoundsIntoBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1boundaryIdentifiers/title",
          "value": "boundaryIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1boundaryIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boundaryIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1setTranslatesReferenceBoundsIntoBoundary(with:)/title",
          "value": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1setTranslatesReferenceBoundsIntoBoundary(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTranslatesReferenceBoundsIntoBoundaryWithInsets:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/title",
          "value": "UIEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/title",
          "value": "UIDynamicAnimator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1addBoundary(withIdentifier:from:to:)/title",
          "value": "addBoundaryWithIdentifier:fromPoint:toPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1addBoundary(withIdentifier:from:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addBoundaryWithIdentifier:fromPoint:toPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1collisionMode/title",
          "value": "collisionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1collisionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collisionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1removeBoundary(withIdentifier:)/title",
          "value": "removeBoundaryWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1removeBoundary(withIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeBoundaryWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1removeAllBoundaries()/title",
          "value": "removeAllBoundaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1removeAllBoundaries()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllBoundaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/title",
          "value": "UICollisionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1boundary(withIdentifier:)/title",
          "value": "boundaryWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1boundary(withIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "boundaryWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1addBoundary(withIdentifier:for:)/title",
          "value": "addBoundaryWithIdentifier:forPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1addBoundary(withIdentifier:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addBoundaryWithIdentifier:forPath:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollisionbehavior/settranslatesreferenceboundsintoboundary(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollisionbehavior/settranslatesreferenceboundsintoboundary(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
