{
  "abstract": [
    {
      "text": "The command object for seeking backward through a single media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekBackwardCommand"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPRemoteCommandCenter(py)seekBackwardCommand",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "seekBackwardCommand"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPRemoteCommand",
        "text": "MPRemoteCommand"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "seekBackwardCommand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "seekBackwardCommand"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "seekBackwardCommand"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPRemoteCommand",
              "text": "MPRemoteCommand"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the object in this property to register your app’s handler for seeking backward in the current track. In your handler, begin seeking backward through the current media item. You can disable the command if your app does not support it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand": {
      "abstract": [
        {
          "text": "An object that responds to remote command events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommand"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter": {
      "abstract": [
        {
          "text": "An object that responds to remote control events sent by external accessories and system controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandCenter",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackPositionCommand": {
      "abstract": [
        {
          "text": "The command object for changing the playback position in a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changePlaybackPositionCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPChangePlaybackPositionCommand",
          "text": "MPChangePlaybackPositionCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackPositionCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changePlaybackPositionCommand"
        }
      ],
      "role": "symbol",
      "title": "changePlaybackPositionCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter/changeplaybackpositioncommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackRateCommand": {
      "abstract": [
        {
          "text": "The command object for changing the playback rate of the current media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changePlaybackRateCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPChangePlaybackRateCommand",
          "text": "MPChangePlaybackRateCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackRateCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changePlaybackRateCommand"
        }
      ],
      "role": "symbol",
      "title": "changePlaybackRateCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter/changeplaybackratecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekBackwardCommand": {
      "abstract": [
        {
          "text": "The command object for seeking backward through a single media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seekBackwardCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPRemoteCommand",
          "text": "MPRemoteCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekBackwardCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seekBackwardCommand"
        }
      ],
      "role": "symbol",
      "title": "seekBackwardCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter/seekbackwardcommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekForwardCommand": {
      "abstract": [
        {
          "text": "The command object for seeking forward through a single media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seekForwardCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPRemoteCommand",
          "text": "MPRemoteCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekForwardCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seekForwardCommand"
        }
      ],
      "role": "symbol",
      "title": "seekForwardCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter/seekforwardcommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipBackwardCommand": {
      "abstract": [
        {
          "text": "The command object for playing a previous point in a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skipBackwardCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSkipIntervalCommand",
          "text": "MPSkipIntervalCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipBackwardCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "skipBackwardCommand"
        }
      ],
      "role": "symbol",
      "title": "skipBackwardCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter/skipbackwardcommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipForwardCommand": {
      "abstract": [
        {
          "text": "The command object for playing a future point in a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skipForwardCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSkipIntervalCommand",
          "text": "MPSkipIntervalCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipForwardCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "skipForwardCommand"
        }
      ],
      "role": "symbol",
      "title": "skipForwardCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter/skipforwardcommand"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigating-a-tracks-contents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackRateCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekForwardCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipBackwardCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipForwardCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackPositionCommand"
      ],
      "title": "Navigating a track’s contents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "seekBackwardCommand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seekBackwardCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigating-a-tracks-contents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackRateCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/seekForwardCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipBackwardCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/skipForwardCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter/changePlaybackPositionCommand"
              ],
              "title": "Navigating a track’s contents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPRemoteCommand",
                    "text": "MPRemoteCommand"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "seekBackwardCommand"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand/title",
          "value": "MPRemoteCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1changePlaybackRateCommand/title",
          "value": "changePlaybackRateCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1changePlaybackRateCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "changePlaybackRateCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/title",
          "value": "MPRemoteCommandCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1seekBackwardCommand/title",
          "value": "seekBackwardCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1seekBackwardCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seekBackwardCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1skipBackwardCommand/title",
          "value": "skipBackwardCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1skipBackwardCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "skipBackwardCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1seekForwardCommand/title",
          "value": "seekForwardCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1seekForwardCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seekForwardCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1skipForwardCommand/title",
          "value": "skipForwardCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1skipForwardCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "skipForwardCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1changePlaybackPositionCommand/title",
          "value": "changePlaybackPositionCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter~1changePlaybackPositionCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "changePlaybackPositionCommand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpremotecommandcenter/seekbackwardcommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpremotecommandcenter/seekbackwardcommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
