{
  "abstract": [
    {
      "text": "The device is submerged, but less than 1 meter under water.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedShallow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMWaterSubmersionDepthState@CMWaterSubmersionDepthStateSubmergedShallow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "submergedShallow"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMWaterSubmersionDepthStateSubmergedShallow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CMWaterSubmersionMeasurement.DepthState.submergedShallow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "submergedShallow"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement": {
      "abstract": [
        {
          "text": "An update that contains data about the pressure and depth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionMeasurement"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionMeasurement"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState": {
      "abstract": [
        {
          "text": "A state based on the device’s depth under water.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DepthState"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DepthState"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/approachingMaxDepth": {
      "abstract": [
        {
          "text": "The device is approaching the maximum safe diving depth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "approachingMaxDepth"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/approachingMaxDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStateApproachingMaxDepth"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.approachingMaxDepth",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/approachingmaxdepth"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/notSubmerged": {
      "abstract": [
        {
          "text": "The device is not submerged in water.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSubmerged"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/notSubmerged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStateNotSubmerged"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.notSubmerged",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/notsubmerged"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/pastMaxDepth": {
      "abstract": [
        {
          "text": "The device has exceeded the maximum safe diving depth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pastMaxDepth"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/pastMaxDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStatePastMaxDepth"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.pastMaxDepth",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/pastmaxdepth"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/sensorDepthError": {
      "abstract": [
        {
          "text": "An error with the depth sensor occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorDepthError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/sensorDepthError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStateSensorDepthError"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.sensorDepthError",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/sensordeptherror"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedDeep": {
      "abstract": [
        {
          "text": "The device is submerged at least 1 meter under water.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submergedDeep"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedDeep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStateSubmergedDeep"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.submergedDeep",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/submergeddeep"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedShallow": {
      "abstract": [
        {
          "text": "The device is submerged, but less than 1 meter under water.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submergedShallow"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedShallow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStateSubmergedShallow"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.submergedShallow",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/submergedshallow"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/unknown": {
      "abstract": [
        {
          "text": "The device’s depth state is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionDepthStateUnknown"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState.unknown",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Depth-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/notSubmerged",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedDeep",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/approachingMaxDepth",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/pastMaxDepth",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/sensorDepthError",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/unknown"
      ],
      "title": "Depth states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMWaterSubmersionDepthStateSubmergedShallow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateSubmergedShallow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Depth-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/notSubmerged",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/submergedDeep",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/approachingMaxDepth",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/pastMaxDepth",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/sensorDepthError",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState/unknown"
              ],
              "title": "Depth states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CMWaterSubmersionDepthStateSubmergedShallow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1pastMaxDepth/title",
          "value": "CMWaterSubmersionDepthStatePastMaxDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1pastMaxDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStatePastMaxDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1submergedShallow/title",
          "value": "CMWaterSubmersionDepthStateSubmergedShallow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1submergedShallow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateSubmergedShallow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/title",
          "value": "CMWaterSubmersionMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState/title",
          "value": "CMWaterSubmersionDepthState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1approachingMaxDepth/title",
          "value": "CMWaterSubmersionDepthStateApproachingMaxDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1approachingMaxDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateApproachingMaxDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1unknown/title",
          "value": "CMWaterSubmersionDepthStateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1sensorDepthError/title",
          "value": "CMWaterSubmersionDepthStateSensorDepthError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1sensorDepthError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateSensorDepthError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1submergedDeep/title",
          "value": "CMWaterSubmersionDepthStateSubmergedDeep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1submergedDeep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateSubmergedDeep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1notSubmerged/title",
          "value": "CMWaterSubmersionDepthStateNotSubmerged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState~1notSubmerged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthStateNotSubmerged"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/submergedshallow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate/submergedshallow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
