{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/log"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCLossType@MLCLossTypeLog",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "log"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCLossTypeLog"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLCLossType.log"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "log"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType": {
      "abstract": [
        {
          "text": "A loss function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLossType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossType"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/MLCLossTypeCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/MLCLossTypeCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCLossTypeCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/mlclosstypecount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/categoricalCrossEntropy": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoricalCrossEntropy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/categoricalCrossEntropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeCategoricalCrossEntropy"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.categoricalCrossEntropy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/categoricalcrossentropy"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/cosineDistance": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cosineDistance"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/cosineDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeCosineDistance"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.cosineDistance",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/cosinedistance"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the loss type, suitable for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/hinge": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hinge"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/hinge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeHinge"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.hinge",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/hinge"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/huber": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "huber"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/huber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeHuber"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.huber",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/huber"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/log": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/log",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeLog"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.log",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/log"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanAbsoluteError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meanAbsoluteError"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanAbsoluteError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeMeanAbsoluteError"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.meanAbsoluteError",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/meanabsoluteerror"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanSquaredError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meanSquaredError"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanSquaredError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeMeanSquaredError"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.meanSquaredError",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/meansquarederror"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/sigmoidCrossEntropy": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoidCrossEntropy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/sigmoidCrossEntropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeSigmoidCrossEntropy"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.sigmoidCrossEntropy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/sigmoidcrossentropy"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/softmaxCrossEntropy": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softmaxCrossEntropy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/softmaxCrossEntropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossTypeSoftmaxCrossEntropy"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType.softmaxCrossEntropy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype/softmaxcrossentropy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/categoricalCrossEntropy",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/cosineDistance",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/hinge",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/huber",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanAbsoluteError",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanSquaredError",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/sigmoidCrossEntropy",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/softmaxCrossEntropy",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/debugDescription"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCLossTypeLog"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/categoricalCrossEntropy",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/cosineDistance",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/hinge",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/huber",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanAbsoluteError",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/meanSquaredError",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/sigmoidCrossEntropy",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/softmaxCrossEntropy",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/MLCLossTypeCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType/debugDescription"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCLossTypeLog"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1categoricalCrossEntropy/title",
          "value": "MLCLossTypeCategoricalCrossEntropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1categoricalCrossEntropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeCategoricalCrossEntropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1meanSquaredError/title",
          "value": "MLCLossTypeMeanSquaredError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1meanSquaredError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeMeanSquaredError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1log/title",
          "value": "MLCLossTypeLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1log/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1hinge/title",
          "value": "MLCLossTypeHinge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1hinge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeHinge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1huber/title",
          "value": "MLCLossTypeHuber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1huber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeHuber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1meanAbsoluteError/title",
          "value": "MLCLossTypeMeanAbsoluteError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1meanAbsoluteError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeMeanAbsoluteError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1cosineDistance/title",
          "value": "MLCLossTypeCosineDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1cosineDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeCosineDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1sigmoidCrossEntropy/title",
          "value": "MLCLossTypeSigmoidCrossEntropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1sigmoidCrossEntropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeSigmoidCrossEntropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType/title",
          "value": "MLCLossType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1softmaxCrossEntropy/title",
          "value": "MLCLossTypeSoftmaxCrossEntropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1softmaxCrossEntropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeSoftmaxCrossEntropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1debugDescription/title",
          "value": "MLCLossTypeDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossTypeDebugDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlclosstype/log"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlclosstype/log"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
