{
  "abstract": [
    {
      "text": "Computes and returns the best possible move for the current player.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/bestMoveForActivePlayer()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GKStrategist(im)bestMoveForActivePlayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bestMoveForActivePlayer"
      },
      {
        "kind": "text",
        "text": "() -> (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)GKGameModelUpdate",
        "text": "GKGameModelUpdate"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "bestMoveForActivePlayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "bestMoveForActivePlayer()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bestMoveForActivePlayer"
            },
            {
              "kind": "text",
              "text": "() -> (any "
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelUpdate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)GKGameModelUpdate",
              "text": "GKGameModelUpdate"
            },
            {
              "kind": "text",
              "text": ")?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An object describing the move found by the strategist.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method looks ahead at the possible moves for the current player (as specified by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/activePlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of the strategist’s game model), as well as possible future moves by other players on subsequent turns, and examines the state of the game model resulting from each possible move. Your game model class rates the desirability of its current state, allowing the strategist to find the sequence of future moves that results in the best outcome for the current player and to return the first move in that sequence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The object returned is an instance of your custom class implementing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. Your game model’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/gameModelUpdates(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method creates this object, describing in your game’s terms a possible move. For example, the game model update class for a Tic-Tac-Toe game would add properties indicating which position an X or O marker is to be placed in. To make use of the strategist’s selection, examine this information you added to the object when creating it. You can implement a computer-controlled player by performing the selected move, or provide hints to a human player by indicating the selected move in your game’s user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMonteCarloStrategist",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class, or a custom class that requires randomization, you must set the the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/randomSource",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property before calling the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/bestMoveForActivePlayer()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method. (For the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMinmaxStrategist",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class, or custom classes with deterministic strategies, a random source is optional.)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "This method returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the current player is invalid or has no available moves.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/activePlayer": {
      "abstract": [
        {
          "text": "The player whose turn it currently is in the game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePlayer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKGameModelPlayer",
          "text": "GKGameModelPlayer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/activePlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activePlayer"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "activePlayer",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgamemodel/activeplayer"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/gameModelUpdates(for:)": {
      "abstract": [
        {
          "text": "Returns the set of moves available to the specified player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameModelUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKGameModelPlayer",
          "text": "GKGameModelPlayer"
        },
        {
          "kind": "text",
          "text": ") -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKGameModelUpdate",
          "text": "GKGameModelUpdate"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/gameModelUpdates(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gameModelUpdatesForPlayer:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "gameModelUpdates(for:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgamemodel/gamemodelupdates(for:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelUpdate": {
      "abstract": [
        {
          "text": "Implement this protocol to describe a move in your turn-based game so that a strategist object can plan game moves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameModelUpdate"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameModelUpdate"
        }
      ],
      "role": "symbol",
      "title": "GKGameModelUpdate",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgamemodelupdate"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMinmaxStrategist": {
      "abstract": [
        {
          "text": "An AI that chooses moves in turn-based games using a ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "deterministic",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMinmaxStrategist"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMinmaxStrategist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMinmaxStrategist"
        }
      ],
      "role": "symbol",
      "title": "GKMinmaxStrategist",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkminmaxstrategist"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMonteCarloStrategist": {
      "abstract": [
        {
          "text": "An AI that chooses moves in turn-based games using a ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "probabilistic",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMonteCarloStrategist"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMonteCarloStrategist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMonteCarloStrategist"
        }
      ],
      "role": "symbol",
      "title": "GKMonteCarloStrategist",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkmontecarlostrategist"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist": {
      "abstract": [
        {
          "text": "A general interface for objects that provide artificial intelligence for use in turn-based (and similar) games.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKStrategist"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKStrategist"
        }
      ],
      "role": "symbol",
      "title": "GKStrategist",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstrategist"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/bestMoveForActivePlayer()": {
      "abstract": [
        {
          "text": "Computes and returns the best possible move for the current player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bestMoveForActivePlayer"
        },
        {
          "kind": "text",
          "text": "() -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKGameModelUpdate",
          "text": "GKGameModelUpdate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/bestMoveForActivePlayer()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bestMoveForActivePlayer"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "bestMoveForActivePlayer()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstrategist/bestmoveforactiveplayer()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/randomSource": {
      "abstract": [
        {
          "text": "A randomizer object to be used when the strategist randomly selects a move.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "randomSource"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKRandom",
          "text": "GKRandom"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist/randomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "randomSource"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "randomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstrategist/randomsource"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "bestMoveForActivePlayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bestMoveForActivePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStrategist"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)GKGameModelUpdate",
                    "text": "id<GKGameModelUpdate>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "bestMoveForActivePlayer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An object describing the move found by the strategist.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist~1randomSource/title",
          "value": "randomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist~1randomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "randomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist/title",
          "value": "GKStrategist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKStrategist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKStrategist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModel~1gameModelUpdates(for:)/title",
          "value": "gameModelUpdatesForPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModel~1gameModelUpdates(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "gameModelUpdatesForPlayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMinmaxStrategist/title",
          "value": "GKMinmaxStrategist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMinmaxStrategist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMinmaxStrategist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMinmaxStrategist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMinmaxStrategist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist~1bestMoveForActivePlayer()/title",
          "value": "bestMoveForActivePlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStrategist~1bestMoveForActivePlayer()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bestMoveForActivePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModel~1activePlayer/title",
          "value": "activePlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModel~1activePlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMonteCarloStrategist/title",
          "value": "GKMonteCarloStrategist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMonteCarloStrategist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMonteCarloStrategist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMonteCarloStrategist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMonteCarloStrategist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelUpdate/title",
          "value": "GKGameModelUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameModelUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelUpdate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameModelUpdate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkstrategist/bestmoveforactiveplayer()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gkstrategist/bestmoveforactiveplayer()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
