{
  "abstract": [
    {
      "text": "The heart rate sensor’s location is not otherwise on this list.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/other"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKHeartRateSensorLocation@HKHeartRateSensorLocationOther",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "other"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKHeartRateSensorLocationOther"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKHeartRateSensorLocation.other"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "other"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation": {
      "abstract": [
        {
          "text": "Constants that indicate where on the body the heart rate sensor is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocation"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocation"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/chest": {
      "abstract": [
        {
          "text": "The heart rate sensor is located on the user’s chest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chest"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/chest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationChest"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.chest",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/chest"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/earLobe": {
      "abstract": [
        {
          "text": "The heart rate sensor is located on the user’s earlobe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "earLobe"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/earLobe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationEarLobe"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.earLobe",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/earlobe"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/finger": {
      "abstract": [
        {
          "text": "The heart rate sensor is located on the user’s finger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finger"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/finger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationFinger"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.finger",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/finger"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/foot": {
      "abstract": [
        {
          "text": "The heart rate sensor is located on the user’s foot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foot"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/foot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationFoot"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.foot",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/foot"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/hand": {
      "abstract": [
        {
          "text": "The heart rate sensor is located on the user’s hand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hand"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/hand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationHand"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.hand",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/hand"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/other": {
      "abstract": [
        {
          "text": "The heart rate sensor’s location is not otherwise on this list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationOther"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.other",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/other"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/wrist": {
      "abstract": [
        {
          "text": "The heart rate sensor is located on the user’s wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrist"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/wrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateSensorLocationWrist"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateSensorLocation.wrist",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratesensorlocation/wrist"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/chest",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/wrist",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/finger",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/hand",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/earLobe",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/foot"
      ],
      "title": "Locations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKHeartRateSensorLocationOther"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/chest",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/wrist",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/finger",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/hand",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/earLobe",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateSensorLocation/foot"
              ],
              "title": "Locations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKHeartRateSensorLocationOther"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation/title",
          "value": "HKHeartRateSensorLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1hand/title",
          "value": "HKHeartRateSensorLocationHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1hand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1chest/title",
          "value": "HKHeartRateSensorLocationChest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1chest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationChest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1earLobe/title",
          "value": "HKHeartRateSensorLocationEarLobe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1earLobe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationEarLobe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1foot/title",
          "value": "HKHeartRateSensorLocationFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1foot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1other/title",
          "value": "HKHeartRateSensorLocationOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1wrist/title",
          "value": "HKHeartRateSensorLocationWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1wrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1finger/title",
          "value": "HKHeartRateSensorLocationFinger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateSensorLocation~1finger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateSensorLocationFinger"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkheartratesensorlocation/other"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkheartratesensorlocation/other"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
