{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults/init(connectionHandle:usedFeatures:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So56BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResultsV16connectionHandle04usedF0ABs6UInt16V_So0a12HCISupportedF0Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "connectionHandle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
        "text": "BluetoothConnectionHandle"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "usedFeatures"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCISupportedFeatures",
        "text": "BluetoothHCISupportedFeatures"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(connectionHandle:usedFeatures:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "connectionHandle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
              "text": "BluetoothConnectionHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "usedFeatures"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCISupportedFeatures",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCISupportedFeatures",
              "text": "BluetoothHCISupportedFeatures"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcieventlereadremoteusedfeaturescompleteresults"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults/init(connectionHandle:usedFeatures:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "connectionHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
          "text": "BluetoothConnectionHandle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "usedFeatures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCISupportedFeatures",
          "text": "BluetoothHCISupportedFeatures"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults/init(connectionHandle:usedFeatures:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(connectionHandle:usedFeatures:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcieventlereadremoteusedfeaturescompleteresults/init(connectionhandle:usedfeatures:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCISupportedFeatures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCISupportedFeatures"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCISupportedFeatures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCISupportedFeatures"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCISupportedFeatures",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcisupportedfeatures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults/title",
          "value": "BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEventLEReadRemoteUsedFeaturesCompleteResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCISupportedFeatures/title",
          "value": "BluetoothHCISupportedFeatures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCISupportedFeatures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCISupportedFeatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCISupportedFeatures/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCISupportedFeatures"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcieventlereadremoteusedfeaturescompleteresults/init(connectionhandle:usedfeatures:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
