{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textInput"},{"kind":"text","text":": (any "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The document instance whose class adopts the UITextInput protocol.","type":"text"}]}],"name":"textInput"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextinputdelegate/textdidchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextinputdelegate/textdidchange(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)"},"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionDidChange(_:)"]},{"generated":true,"title":"Notifying the delegate of textual changes","anchor":"Notifying-the-delegate-of-textual-changes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate"]]},"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"textDidChange:"}],"role":"symbol","roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)UITextInputDelegate(im)textDidChange:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDidChange"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":")?)"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false}],"title":"textDidChange(_:)"},"abstract":[{"text":"Tells the input delegate when text has changed in the document.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITextInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInput"}],"title":"UITextInput","abstract":[{"type":"text","text":"A set of methods for interacting with the text input system and enabling features in documents."}],"url":"/documentation/uikit/uitextinput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextInput"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate":{"url":"/documentation/uikit/uitextinputdelegate","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate","navigatorTitle":[{"kind":"identifier","text":"UITextInputDelegate"}],"abstract":[{"type":"text","text":"An intermediary between a document and the text input system."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInputDelegate"}],"title":"UITextInputDelegate"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"textWillChange:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)","abstract":[{"text":"Tells the input delegate when text is about to change in the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textWillChange"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"type":"topic","title":"textWillChange(_:)","required":true,"role":"symbol","kind":"symbol","url":"/documentation/uikit/uitextinputdelegate/textwillchange(_:)"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)":{"abstract":[{"type":"text","text":"Tells the input delegate when text has changed in the document."}],"url":"/documentation/uikit/uitextinputdelegate/textdidchange(_:)","navigatorTitle":[{"kind":"identifier","text":"textDidChange:"}],"type":"topic","title":"textDidChange(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDidChange"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionDidChange(_:)":{"kind":"symbol","role":"symbol","url":"/documentation/uikit/uitextinputdelegate/selectiondidchange(_:)","navigatorTitle":[{"kind":"identifier","text":"selectionDidChange:"}],"title":"selectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionDidChange"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"type":"topic","required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionDidChange(_:)","abstract":[{"text":"Tells the input delegate when the selection has changed in the document.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"textDidChange:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"textDidChange:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionDidChange(_:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)"],"title":"Notifying the delegate of textual changes","anchor":"Notifying-the-delegate-of-textual-changes","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"textDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UITextInput>","preciseIdentifier":"c:Qoobjc(pl)UITextInput"},{"kind":"text","text":") "},{"kind":"internalParam","text":"textInput"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"textInput","content":[{"inlineContent":[{"type":"text","text":"The document instance whose class adopts the UITextInput protocol."}],"type":"paragraph"}]}]},"op":"replace"},{"value":"UITextInput","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/title","op":"replace"},{"value":[{"kind":"identifier","text":"UITextInput"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UITextInput"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/navigatorTitle","op":"replace"},{"value":"UITextInputDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate/title","op":"replace"},{"value":[{"text":"UITextInputDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UITextInputDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate/navigatorTitle","op":"replace"},{"value":"textWillChange:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textWillChange(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"textWillChange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textWillChange(_:)/fragments","op":"replace"},{"value":"textDidChange:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textDidChange(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textDidChange:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textDidChange(_:)/fragments","op":"replace"},{"value":"selectionDidChange:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1selectionDidChange(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"selectionDidChange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1selectionDidChange(_:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}