{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextinputdelegate/textwillchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextinputdelegate/textwillchange(_:)"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the input delegate when text is about to change in the document."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textWillChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"textInput","kind":"internalParam"},{"text":": (any ","kind":"text"},{"text":"UITextInput","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"parameters","parameters":[{"name":"textInput","content":[{"inlineContent":[{"text":"The document instance whose class adopts the UITextInput protocol.","type":"text"}],"type":"paragraph"}]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionWillChange(_:)"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)"],"anchor":"Notifying-the-delegate-of-textual-changes","generated":true,"title":"Notifying the delegate of textual changes"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate"]]},"metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"textWillChange:","kind":"identifier"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UITextInputDelegate(im)textWillChange:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textWillChange","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"textWillChange(_:)","symbolKind":"method","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"required":true},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInput"}],"title":"UITextInput","abstract":[{"type":"text","text":"A set of methods for interacting with the text input system and enabling features in documents."}],"url":"/documentation/uikit/uitextinput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextInput"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate":{"url":"/documentation/uikit/uitextinputdelegate","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate","navigatorTitle":[{"kind":"identifier","text":"UITextInputDelegate"}],"abstract":[{"type":"text","text":"An intermediary between a document and the text input system."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInputDelegate"}],"title":"UITextInputDelegate"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionWillChange(_:)":{"kind":"symbol","role":"symbol","url":"/documentation/uikit/uitextinputdelegate/selectionwillchange(_:)","navigatorTitle":[{"kind":"identifier","text":"selectionWillChange:"}],"title":"selectionWillChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionWillChange"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"type":"topic","required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionWillChange(_:)","abstract":[{"text":"Tells the input delegate when the selection is about to change in the document.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"textWillChange:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textWillChange(_:)","abstract":[{"text":"Tells the input delegate when text is about to change in the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textWillChange"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"type":"topic","title":"textWillChange(_:)","required":true,"role":"symbol","kind":"symbol","url":"/documentation/uikit/uitextinputdelegate/textwillchange(_:)"},"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)":{"abstract":[{"type":"text","text":"Tells the input delegate when text has changed in the document."}],"url":"/documentation/uikit/uitextinputdelegate/textdidchange(_:)","navigatorTitle":[{"kind":"identifier","text":"textDidChange:"}],"type":"topic","title":"textDidChange(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDidChange"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"kind":"text","text":")?)"}],"required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface":{"identifier":"doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface","abstract":[{"text":"Design a flexible, functional, and responsive interface for editing text.","type":"text"}],"title":"Configuring a custom keyboard interface","role":"article","url":"/documentation/uikit/configuring-a-custom-keyboard-interface","kind":"article","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"textWillChange:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textWillChange:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/selectionWillChange(_:)"],"anchor":"Related-Documentation"},{"title":"Notifying the delegate of textual changes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInputDelegate/textDidChange(_:)"],"generated":true,"anchor":"Notifying-the-delegate-of-textual-changes"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textWillChange:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UITextInput","text":"id<UITextInput>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textInput","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"name":"textInput","content":[{"type":"paragraph","inlineContent":[{"text":"The document instance whose class adopts the UITextInput protocol.","type":"text"}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/title","op":"replace","value":"UITextInput"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextInput"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/navigatorTitle","op":"replace","value":[{"text":"UITextInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate/title","op":"replace","value":"UITextInputDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate/fragments","op":"replace","value":[{"text":"UITextInputDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextInputDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1selectionWillChange(_:)/title","op":"replace","value":"selectionWillChange:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1selectionWillChange(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectionWillChange:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textWillChange(_:)/title","op":"replace","value":"textWillChange:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textWillChange(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"textWillChange:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textDidChange(_:)/title","op":"replace","value":"textDidChange:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputDelegate~1textDidChange(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"textDidChange:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}