{
  "abstract": [
    {
      "text": "A wrapper around a compiled graph object that adds a required modifiable context to support dynamically sized models and set execute-time options.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:10Accelerate9BNNSGraphO7ContextC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Context"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Context"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "BNNSGraph.Context"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Context"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance provides a wrapper around the C API ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " types. Because this class manages its own memory, you don’t need to call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to deallocate its resources.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for the Swift overlays to BNNS Graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraph"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraph"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/CompileOptions": {
      "abstract": [
        {
          "text": "The compilation options that BNNS uses when compiling a source mlmodelc file to a graph object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompileOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/CompileOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompileOptions"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.CompileOptions",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/compileoptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context": {
      "abstract": [
        {
          "text": "A wrapper around a compiled graph object that adds a required modifiable context to support dynamically sized models and set execute-time options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.Context",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentCount(forFunction:)": {
      "abstract": [
        {
          "text": "Returns the number of arguments for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentCount(forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "argumentCount(forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/argumentcount(forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentNames(forFunction:)": {
      "abstract": [
        {
          "text": "Returns the names of arguments for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentNames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentNames(forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "argumentNames(forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/argumentnames(forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentPosition(forFunction:argument:)": {
      "abstract": [
        {
          "text": "Returns the index into the arguments array for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentPosition(forFunction:argument:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "argumentPosition(forFunction:argument:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/argumentposition(forfunction:argument:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/checkForNaNsAndInfinities": {
      "abstract": [
        {
          "text": "A Boolean value that specifies that the context checks intermediate tensors for NaNs and infinities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkForNaNsAndInfinities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/checkForNaNsAndInfinities",
      "kind": "symbol",
      "role": "symbol",
      "title": "checkForNaNsAndInfinities",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/checkfornansandinfinities"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/executeFunction(_:arguments:)-8bhcn": {
      "abstract": [
        {
          "text": "Executes the specified function using an array of input and output tensors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executeFunction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSTensor",
          "text": "BNNSTensor"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/executeFunction(_:arguments:)-8bhcn",
      "kind": "symbol",
      "role": "symbol",
      "title": "executeFunction(_:arguments:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/executefunction(_:arguments:)-8bhcn"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/executeFunction(_:arguments:)-95snr": {
      "abstract": [
        {
          "text": "Executes the specified function using an array of input and output pointers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executeFunction"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/executeFunction(_:arguments:)-95snr",
      "kind": "symbol",
      "role": "symbol",
      "title": "executeFunction(_:arguments:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/executefunction(_:arguments:)-95snr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionCount": {
      "abstract": [
        {
          "text": "The number of input arguments for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "functionCount",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/functioncount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionNames": {
      "abstract": [
        {
          "text": "Returns the names of callable functions in the graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionNames",
      "kind": "symbol",
      "role": "symbol",
      "title": "functionNames",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/functionnames"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/init(compileFromPath:functionName:options:)": {
      "abstract": [
        {
          "text": "Returns a new context that wraps a graph object representing the compiled mlmodelc file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "compileFromPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "functionName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO",
          "text": "BNNSGraph"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO14CompileOptionsV",
          "text": "CompileOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/init(compileFromPath:functionName:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(compileFromPath:functionName:options:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/init(compilefrompath:functionname:options:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setBatchSize(_:forFunction:)": {
      "abstract": [
        {
          "text": "Sets the batch size for a graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBatchSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setBatchSize(_:forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setBatchSize(_:forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/setbatchsize(_:forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)": {
      "abstract": [
        {
          "text": "Specifies the dynamic shapes for a graph and, if possible, infers the output shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDynamicShapes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO",
          "text": "BNNSGraph"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO5ShapeV",
          "text": "Shape"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO",
          "text": "BNNSGraph"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO5ShapeV",
          "text": "Shape"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDynamicShapes(_:forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/setdynamicshapes(_:forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/tensor(forFunction:argument:fillKnownDynamicShapes:)": {
      "abstract": [
        {
          "text": "Returns an unallocated tensor for a given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillKnownDynamicShapes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSTensor",
          "text": "BNNSTensor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/tensor(forFunction:argument:fillKnownDynamicShapes:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "tensor(forFunction:argument:fillKnownDynamicShapes:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/tensor(forfunction:argument:fillknowndynamicshapes:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Error": {
      "abstract": [
        {
          "text": "Error codes that a graph context throws.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.Error",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/PointerArgument": {
      "abstract": [
        {
          "text": "A type that BNNS Graph accepts as an input-output argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointerArgument"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/PointerArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointerArgument"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.PointerArgument",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/pointerargument"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape": {
      "abstract": [
        {
          "text": "The specification of the shape of an argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Shape"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.Shape",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/shape"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)": {
      "abstract": [
        {
          "text": "Destroys the specified graph context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphContextDestroy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_context_t",
          "text": "bnns_graph_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphContextDestroy"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphContextDestroy(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcontextdestroy(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t": {
      "abstract": [
        {
          "text": "An object that wraps a compiled graph object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_context_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_context_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_context_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_context_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t": {
      "abstract": [
        {
          "text": "The compiled graph object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-graph-context",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/init(compileFromPath:functionName:options:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/CompileOptions"
      ],
      "title": "Creating a graph context"
    },
    {
      "anchor": "Specifying-and-querying-a-graph-contexts-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setBatchSize(_:forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentCount(forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentNames(forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentPosition(forFunction:argument:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionCount",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionNames",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/checkForNaNsAndInfinities"
      ],
      "title": "Specifying and querying a graph context’s properties"
    },
    {
      "anchor": "Specifying-a-tensors-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/tensor(forFunction:argument:fillKnownDynamicShapes:)"
      ],
      "title": "Specifying a tensor’s properties"
    },
    {
      "anchor": "Executing-a-graph",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/executeFunction(_:arguments:)-8bhcn",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/executeFunction(_:arguments:)-95snr",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/PointerArgument"
      ],
      "title": "Executing a graph"
    },
    {
      "anchor": "Handling-errors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Error"
      ],
      "title": "Handling errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/title",
          "value": "bnns_graph_context_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextDestroy(_:)/title",
          "value": "BNNSGraphContextDestroy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextDestroy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphContextDestroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/title",
          "value": "bnns_graph_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsgraph/context"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
