{
  "abstract": [
    {
      "text": "The specification of the shape of an argument.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:10Accelerate9BNNSGraphO5ShapeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Shape"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Shape"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSGraph.Shape"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Shape"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function uses arrays of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structures as its input and output. This structure wraps the C API ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type and derives its rank from the number of elements in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/dimensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for the Swift overlays to BNNS Graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraph"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraph"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentCount(forFunction:)": {
      "abstract": [
        {
          "text": "Returns the number of arguments for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentCount(forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "argumentCount(forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/argumentcount(forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentNames(forFunction:)": {
      "abstract": [
        {
          "text": "Returns the names of arguments for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentNames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentNames(forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "argumentNames(forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/argumentnames(forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentPosition(forFunction:argument:)": {
      "abstract": [
        {
          "text": "Returns the index into the arguments array for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentPosition(forFunction:argument:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "argumentPosition(forFunction:argument:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/argumentposition(forfunction:argument:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/checkForNaNsAndInfinities": {
      "abstract": [
        {
          "text": "A Boolean value that specifies that the context checks intermediate tensors for NaNs and infinities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkForNaNsAndInfinities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/checkForNaNsAndInfinities",
      "kind": "symbol",
      "role": "symbol",
      "title": "checkForNaNsAndInfinities",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/checkfornansandinfinities"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionCount": {
      "abstract": [
        {
          "text": "The number of input arguments for the given function argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "functionCount",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/functioncount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionNames": {
      "abstract": [
        {
          "text": "Returns the names of callable functions in the graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionNames",
      "kind": "symbol",
      "role": "symbol",
      "title": "functionNames",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/functionnames"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setBatchSize(_:forFunction:)": {
      "abstract": [
        {
          "text": "Sets the batch size for a graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBatchSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setBatchSize(_:forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setBatchSize(_:forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/setbatchsize(_:forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)": {
      "abstract": [
        {
          "text": "Specifies the dynamic shapes for a graph and, if possible, infers the output shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDynamicShapes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO",
          "text": "BNNSGraph"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO5ShapeV",
          "text": "Shape"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO",
          "text": "BNNSGraph"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate9BNNSGraphO5ShapeV",
          "text": "Shape"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDynamicShapes(_:forFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/context/setdynamicshapes(_:forfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape": {
      "abstract": [
        {
          "text": "The specification of the shape of an argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Shape"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.Shape",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/shape"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/ArrayLiteralElement": {
      "abstract": [
        {
          "text": "The type of the elements of an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArrayLiteralElement"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/ArrayLiteralElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArrayLiteralElement"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraph.Shape.ArrayLiteralElement",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/shape/arrayliteralelement"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/dimensions": {
      "abstract": [
        {
          "text": "An array that contains the dimensions of the shape structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimensions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/dimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "dimensions",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/shape/dimensions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/init(_:)": {
      "abstract": [
        {
          "text": "Creates a shape structure from the given array elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/shape/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/init(arrayLiteral:)": {
      "abstract": [
        {
          "text": "Creates a shape structure from the given array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "arrayLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "...)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/init(arrayLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(arrayLiteral:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraph/shape/init(arrayliteral:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t": {
      "abstract": [
        {
          "text": "The specification of the shape of an argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_shape_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_shape_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_shape_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_shape_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-and-querying-a-graph-contexts-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setBatchSize(_:forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/setDynamicShapes(_:forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentCount(forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentNames(forFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/argumentPosition(forFunction:argument:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionCount",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/functionNames",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Context/checkForNaNsAndInfinities"
      ],
      "title": "Specifying and querying a graph context’s properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-shape-structure",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/init(arrayLiteral:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/init(_:)"
      ],
      "title": "Creating a shape structure"
    },
    {
      "anchor": "Querying-a-shape-structures-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/dimensions"
      ],
      "title": "Querying a shape structure’s properties"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraph/Shape/ArrayLiteralElement"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/title",
          "value": "bnns_graph_shape_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_shape_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_shape_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsgraph/shape"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
