{
  "abstract": [
    {
      "text": "Asks the delegate to perform an action when the Add (+) button is clicked.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetListPerformAddAction(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NCWidgetListViewDelegate(im)widgetListPerformAddAction:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "widgetListPerformAddAction"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NCWidgetListViewController",
        "text": "NCWidgetListViewController"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Notification Center"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "widgetListPerformAddAction:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.10",
        "message": "Use WidgetKit instead. Today View extensions have been deprecated.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "widgetListPerformAddAction(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "widgetListPerformAddAction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "list"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NCWidgetListViewController",
              "text": "NCWidgetListViewController"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The widget’s list view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "list"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a widget’s list is in editing mode, the list view controller can display an Add (+) button. The button’s action calls ",
              "type": "text"
            },
            {
              "code": "widgetListPerformAddAction:",
              "type": "codeVoice"
            },
            {
              "text": " in the delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to display the default search view in the add action, you can use the ",
              "type": "text"
            },
            {
              "code": "presentViewControllerInWidget:",
              "type": "codeVoice"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "code": "NSViewController",
              "type": "codeVoice"
            },
            {
              "text": "  to present an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance in the widget’s principal view controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter": {
      "abstract": [
        {
          "text": "Create and manage widgets for the Today view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter",
      "kind": "symbol",
      "role": "collection",
      "title": "Notification Center",
      "type": "topic",
      "url": "/documentation/notificationcenter"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController": {
      "abstract": [
        {
          "text": "An object that provides a list view for displaying content in a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetListViewController"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetListViewController"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetListViewController",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetlistviewcontroller"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate": {
      "abstract": [
        {
          "text": "The interface for handling content display and editing in the list view of a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetListViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetListViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetListViewDelegate",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetlistviewdelegate"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:didRemoveRow:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified row was removed from the list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NCWidgetListViewController",
          "text": "NCWidgetListViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemoveRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:didRemoveRow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetList:didRemoveRow:"
        }
      ],
      "role": "symbol",
      "title": "widgetList(_:didRemoveRow:)",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetlistviewdelegate/widgetlist(_:didremoverow:)"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:shouldRemoveRow:)": {
      "abstract": [
        {
          "text": "Asks the delegate to allow or prohibit the specified row to be removed from the list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NCWidgetListViewController",
          "text": "NCWidgetListViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldRemoveRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:shouldRemoveRow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetList:shouldRemoveRow:"
        }
      ],
      "role": "symbol",
      "title": "widgetList(_:shouldRemoveRow:)",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetlistviewdelegate/widgetlist(_:shouldremoverow:)"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetListPerformAddAction(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate to perform an action when the Add (+) button is clicked.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetListPerformAddAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NCWidgetListViewController",
          "text": "NCWidgetListViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetListPerformAddAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetListPerformAddAction:"
        }
      ],
      "role": "symbol",
      "title": "widgetListPerformAddAction(_:)",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetlistviewdelegate/widgetlistperformaddaction(_:)"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController": {
      "abstract": [
        {
          "text": "An object that provides a default search view within a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewController"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewController"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetSearchViewController",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetsearchviewcontroller"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-and-Deleting-Rows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:didRemoveRow:)",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:shouldRemoveRow:)"
      ],
      "title": "Adding and Deleting Rows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "widgetListPerformAddAction:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetListPerformAddAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-and-Deleting-Rows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:didRemoveRow:)",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewDelegate/widgetList(_:shouldRemoveRow:)"
              ],
              "title": "Adding and Deleting Rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "widgetListPerformAddAction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NCWidgetListViewController",
                    "text": "NCWidgetListViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "list"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The widget’s list view controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "list"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewController/title",
          "value": "NCWidgetListViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetListViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetListViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate~1widgetList(_:shouldRemoveRow:)/title",
          "value": "widgetList:shouldRemoveRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate~1widgetList(_:shouldRemoveRow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetList:shouldRemoveRow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate~1widgetList(_:didRemoveRow:)/title",
          "value": "widgetList:didRemoveRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate~1widgetList(_:didRemoveRow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetList:didRemoveRow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate/title",
          "value": "NCWidgetListViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetListViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetListViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/title",
          "value": "NCWidgetSearchViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate~1widgetListPerformAddAction(_:)/title",
          "value": "widgetListPerformAddAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewDelegate~1widgetListPerformAddAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetListPerformAddAction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/notificationcenter/ncwidgetlistviewdelegate/widgetlistperformaddaction(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/notificationcenter/ncwidgetlistviewdelegate/widgetlistperformaddaction(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
