{"metadata":{"roleHeading":"Instance Method","title":"appController(_:didFinishLaunching:)","symbolKind":"method","navigatorTitle":[{"text":"appController:didFinishLaunchingWithOptions:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TVApplicationController","text":"TVApplicationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishLaunching","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"modules":[{"name":"TVMLKit"}],"externalID":"c:objc(pl)TVApplicationControllerDelegate(im)appController:didFinishLaunchingWithOptions:","platforms":[{"unavailable":false,"name":"tvOS","message":"Please use SwiftUI or UIKit","beta":false,"introducedAt":"9.0","deprecatedAt":"18.0","deprecated":false}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TVApplicationController","preciseIdentifier":"c:objc(cs)TVApplicationController","kind":"typeIdentifier","identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController"},{"text":", ","kind":"text"},{"text":"didFinishLaunching","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController","type":"reference","isActive":true},{"text":" object that finished launching.","type":"text"}]}],"name":"appController"},{"content":[{"inlineContent":[{"type":"text","text":"The launch options passed to the app controller."}],"type":"paragraph"}],"name":"options"}]}],"deprecationSummary":[{"inlineContent":[{"text":"Please use SwiftUI or UIKit","type":"text"}],"type":"paragraph"}],"identifier":{"url":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFinishLaunching:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.tvmlkit/documentation/TVMLKit","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/tvmlkit/tvapplicationcontrollerdelegate/appcontroller(_:didfinishlaunching:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/tvmlkit/tvapplicationcontrollerdelegate/appcontroller(_:didfinishlaunching:)"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFail:)","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didStop:)","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:evaluateAppJavaScriptIn:)","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/player(for:)"],"anchor":"Managing-the-App-Controller","title":"Managing the App Controller","generated":true}],"kind":"symbol","abstract":[{"text":"Tells the delegate the app controller has finished launching.","type":"text"}],"references":{"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didStop:)":{"navigatorTitle":[{"text":"appController:didStopWithOptions:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"appController(_:didStop:)","deprecated":true,"abstract":[{"type":"text","text":"Tells the delegate the app has stopped for any reason."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TVApplicationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TVApplicationController"},{"text":", ","kind":"text"},{"text":"didStop","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didStop:)","role":"symbol","url":"/documentation/tvmlkit/tvapplicationcontrollerdelegate/appcontroller(_:didstop:)"},"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController":{"kind":"symbol","url":"/documentation/tvmlkit/tvapplicationcontroller","title":"TVApplicationController","navigatorTitle":[{"kind":"identifier","text":"TVApplicationController"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TVApplicationController"}],"abstract":[{"type":"text","text":"An object that bridges the UI, navigation stack, storage, and event handling from JavaScript."}],"type":"topic","identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController","deprecated":true},"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFail:)":{"navigatorTitle":[{"kind":"identifier","text":"appController:didFailWithError:"}],"type":"topic","kind":"symbol","title":"appController(_:didFail:)","deprecated":true,"abstract":[{"type":"text","text":"Tell the delegate the app controller failed due to an error."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TVApplicationController","text":"TVApplicationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFail:)","role":"symbol","url":"/documentation/tvmlkit/tvapplicationcontrollerdelegate/appcontroller(_:didfail:)"},"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/player(for:)":{"navigatorTitle":[{"text":"playerForAppController:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"player(for:)","deprecated":true,"abstract":[{"type":"text","text":"Asks the delegate for a custom player object for a particular player bridge."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TVApplicationController","text":"TVApplicationController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TVPlayer","text":"TVPlayer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/player(for:)","role":"symbol","url":"/documentation/tvmlkit/tvapplicationcontrollerdelegate/player(for:)"},"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFinishLaunching:)":{"type":"topic","navigatorTitle":[{"text":"appController:didFinishLaunchingWithOptions:","kind":"identifier"}],"role":"symbol","deprecated":true,"title":"appController(_:didFinishLaunching:)","url":"/documentation/tvmlkit/tvapplicationcontrollerdelegate/appcontroller(_:didfinishlaunching:)","abstract":[{"text":"Tells the delegate the app controller has finished launching.","type":"text"}],"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFinishLaunching:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TVApplicationController","text":"TVApplicationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishLaunching","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}]},"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:evaluateAppJavaScriptIn:)":{"url":"/documentation/tvmlkit/tvapplicationcontrollerdelegate/appcontroller(_:evaluateappjavascriptin:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TVApplicationController","text":"TVApplicationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluateAppJavaScriptIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JSContext"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:evaluateAppJavaScriptIn:)","deprecated":true,"title":"appController(_:evaluateAppJavaScriptIn:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"appController:evaluateAppJavaScriptInContext:","kind":"identifier"}],"abstract":[{"type":"text","text":"Tells the delegate to add JavaScript classes and objects."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","role":"symbol","url":"/documentation/Swift/String","type":"topic","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"title":"String"},"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate":{"navigatorTitle":[{"text":"TVApplicationControllerDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"TVApplicationControllerDelegate","deprecated":true,"abstract":[{"type":"text","text":"A protocol used to observe and manage the different states of an application controller."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TVApplicationControllerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate","role":"symbol","url":"/documentation/tvmlkit/tvapplicationcontrollerdelegate"},"doc://com.apple.tvmlkit/documentation/TVMLKit":{"identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit","role":"collection","url":"/documentation/tvmlkit","type":"topic","abstract":[{"type":"text","text":"Create client-server apps by incorporating JavaScript and TVML files in your binary app."}],"kind":"symbol","deprecated":true,"title":"TVMLKit"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","url":"/documentation/technologies","type":"topic","abstract":[{"type":"text","text":""}],"kind":"technologies","title":"Technologies"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecatedAt":"18.0","deprecated":false,"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"appController:didFinishLaunchingWithOptions:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appController:didFinishLaunchingWithOptions:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.tvmlkit/documentation/TVMLKit","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Managing the App Controller","identifiers":["doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didFail:)","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:didStop:)","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/appController(_:evaluateAppJavaScriptIn:)","doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate/player(for:)"],"anchor":"Managing-the-App-Controller"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["tvOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"appController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TVApplicationController","identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TVApplicationController"},{"text":" *) ","kind":"text"},{"text":"appController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFinishLaunchingWithOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"appController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController","isActive":true},{"type":"text","text":" object that finished launching."}]}]},{"name":"options","content":[{"inlineContent":[{"text":"The launch options passed to the app controller.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"value":[{"type":"paragraph","inlineContent":[{"text":"Please use SwiftUI or UIKit","type":"text"}]}],"op":"replace","path":"/deprecationSummary"},{"value":"appController:didStopWithOptions:","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:didStop:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"appController:didStopWithOptions:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:didStop:)/fragments"},{"value":"TVApplicationController","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/title"},{"value":[{"text":"TVApplicationController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/fragments"},{"value":[{"text":"TVApplicationController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/navigatorTitle"},{"value":"appController:didFailWithError:","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:didFail:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"appController:didFailWithError:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:didFail:)/fragments"},{"value":"playerForAppController:","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1player(for:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerForAppController:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1player(for:)/fragments"},{"value":"appController:didFinishLaunchingWithOptions:","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:didFinishLaunching:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appController:didFinishLaunchingWithOptions:"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:didFinishLaunching:)/fragments"},{"value":"appController:evaluateAppJavaScriptInContext:","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:evaluateAppJavaScriptIn:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"appController:evaluateAppJavaScriptInContext:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate~1appController(_:evaluateAppJavaScriptIn:)/fragments"},{"value":"TVApplicationControllerDelegate","op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/title"},{"value":[{"text":"TVApplicationControllerDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/fragments"},{"value":[{"text":"TVApplicationControllerDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}