{
  "abstract": [
    {
      "text": "The normal state of a table cell.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewCellStateMask/UITableViewCellStateDefaultMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITableViewCellStateMask@UITableViewCellStateDefaultMask",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITableViewCellStateDefaultMask"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITableViewCellStateDefaultMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "UITableViewCellStateDefaultMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStateDefaultMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask": {
      "abstract": [
        {
          "text": "Constants used to determine the new state of a cell as it transitions between states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StateMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StateMask"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell.StateMask",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/statemask"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask/showingDeleteConfirmation": {
      "abstract": [
        {
          "text": "The state of a table view cell that shows a button requesting confirmation of a delete gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showingDeleteConfirmation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellStateMask",
          "text": "StateMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask/showingDeleteConfirmation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewCellStateShowingDeleteConfirmationMask"
        }
      ],
      "role": "symbol",
      "title": "showingDeleteConfirmation",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/statemask/showingdeleteconfirmation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask/showingEditControl": {
      "abstract": [
        {
          "text": "The state of a table view cell when the table view is in editing mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showingEditControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellStateMask",
          "text": "StateMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask/showingEditControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewCellStateShowingEditControlMask"
        }
      ],
      "role": "symbol",
      "title": "showingEditControl",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/statemask/showingeditcontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCellStateMask/UITableViewCellStateDefaultMask": {
      "abstract": [
        {
          "text": "The normal state of a table cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITableViewCellStateDefaultMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCellStateMask/UITableViewCellStateDefaultMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITableViewCellStateDefaultMask",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcellstatemask/uitableviewcellstatedefaultmask"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask/showingEditControl",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/StateMask/showingDeleteConfirmation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask~1showingDeleteConfirmation/title",
          "value": "UITableViewCellStateShowingDeleteConfirmationMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask~1showingDeleteConfirmation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStateShowingDeleteConfirmationMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask~1showingEditControl/title",
          "value": "UITableViewCellStateShowingEditControlMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask~1showingEditControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStateShowingEditControlMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask/title",
          "value": "UITableViewCellStateMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStateMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1StateMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStateMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewcellstatemask/uitableviewcellstatedefaultmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
