{
  "abstract": [
    {
      "text": "Key for the model creator’s custom metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/creatorDefinedKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreML",
    "externalID": "c:@MLModelCreatorDefinedKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "creatorDefinedKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MLModelMetadataKey",
        "text": "MLModelMetadataKey"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLModelCreatorDefinedKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "creatorDefinedKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "creatorDefinedKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MLModelMetadataKey",
              "text": "MLModelMetadataKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key provides read-only access to custom metadata about the model, generated by the model’s author. The custom metadata is a dictionary of type ",
              "type": "text"
            },
            {
              "code": "[String: String]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This key corresponds to the ",
              "type": "text"
            },
            {
              "code": "userDefined",
              "type": "codeVoice"
            },
            {
              "text": " field specified in the ",
              "type": "text"
            },
            {
              "identifier": "https://apple.github.io/coremltools/mlmodel/Format/Model.html#metadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey": {
      "abstract": [
        {
          "text": "The set of keys the model uses to store values in its metadata dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "MLModelMetadataKey",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/author": {
      "abstract": [
        {
          "text": "Key for the author of the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "author"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLModelMetadataKey",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/author",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelAuthorKey"
        }
      ],
      "role": "symbol",
      "title": "author",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey/author"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/creatorDefinedKey": {
      "abstract": [
        {
          "text": "Key for the model creator’s custom metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creatorDefinedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLModelMetadataKey",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/creatorDefinedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelCreatorDefinedKey"
        }
      ],
      "role": "symbol",
      "title": "creatorDefinedKey",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey/creatordefinedkey"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/description": {
      "abstract": [
        {
          "text": "Key for the overall description of the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLModelMetadataKey",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/description",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "description",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey/description"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/license": {
      "abstract": [
        {
          "text": "Key for the license of the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "license"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLModelMetadataKey",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/license",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelLicenseKey"
        }
      ],
      "role": "symbol",
      "title": "license",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey/license"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/versionString": {
      "abstract": [
        {
          "text": "Key for the version of the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLModelMetadataKey",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/versionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelVersionStringKey"
        }
      ],
      "role": "symbol",
      "title": "versionString",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey/versionstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://apple.github.io/coremltools/mlmodel/Format/Model.html#metadata": {
      "identifier": "https://apple.github.io/coremltools/mlmodel/Format/Model.html#metadata",
      "title": "Core ML Model Specification",
      "titleInlineContent": [
        {
          "text": "Core ML Model Specification",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://apple.github.io/coremltools/mlmodel/Format/Model.html#metadata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/author",
        "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/description",
        "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/license",
        "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/versionString"
      ],
      "title": "Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLModelCreatorDefinedKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelCreatorDefinedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/author",
                "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/description",
                "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/license",
                "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey/versionString"
              ],
              "title": "Metadata Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MLModelMetadataKey",
                    "text": "MLModelMetadataKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLModelCreatorDefinedKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1license/title",
          "value": "MLModelLicenseKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1license/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelLicenseKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1description/title",
          "value": "MLModelDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1description/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1author/title",
          "value": "MLModelAuthorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1author/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelAuthorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1creatorDefinedKey/title",
          "value": "MLModelCreatorDefinedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1creatorDefinedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelCreatorDefinedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1versionString/title",
          "value": "MLModelVersionStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey~1versionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelVersionStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey/title",
          "value": "MLModelMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelMetadataKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmodelmetadatakey/creatordefinedkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlmodelmetadatakey/creatordefinedkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
