{
  "abstract": [
    {
      "text": "The tracking mode used for the segments of the control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell/trackingMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSegmentedCell(py)trackingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "trackingMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSegmentedControl",
        "text": "NSSegmentedControl"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
        "text": "SwitchTracking"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "trackingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "trackingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trackingMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSegmentedControl",
              "text": "NSSegmentedControl"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
              "text": "SwitchTracking"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Possible values for ",
              "type": "text"
            },
            {
              "code": "trackingMode",
              "type": "codeVoice"
            },
            {
              "text": " are described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectOne",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSSegmentedCell",
          "type": "codeVoice"
        },
        {
          "text": " object implements the appearance and behavior of a horizontal button divided into multiple segments. This class is used in conjunction with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class to implement a segmented control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSegmentedCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentedCell"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedCell",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell/trackingMode": {
      "abstract": [
        {
          "text": "The tracking mode used for the segments of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSegmentedControl",
          "text": "NSSegmentedControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
          "text": "SwitchTracking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell/trackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingMode"
        }
      ],
      "role": "symbol",
      "title": "trackingMode",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcell/trackingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl": {
      "abstract": [
        {
          "text": "Display one or more buttons in a single horizontal group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking": {
      "abstract": [
        {
          "text": "The following constants specify the type of tracking behavior a segmented control exhibits. They are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SwitchTracking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SwitchTracking"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectOne": {
      "abstract": [
        {
          "text": "Only one segment in the control can be selected at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectOne"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectOne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentSwitchTrackingSelectOne"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking.selectOne",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking/selectone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode": {
      "abstract": [
        {
          "text": "The type of tracking behavior the control exhibits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSegmentedControl",
          "text": "NSSegmentedControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
          "text": "SwitchTracking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingMode"
        }
      ],
      "role": "symbol",
      "title": "trackingMode",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/trackingmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "trackingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedCell"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
                    "text": "NSSegmentSwitchTracking"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "trackingMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking/title",
          "value": "NSSegmentSwitchTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title",
          "value": "NSSegmentedControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1selectOne/title",
          "value": "NSSegmentSwitchTrackingSelectOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1selectOne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingSelectOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedCell~1trackingMode/title",
          "value": "trackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedCell~1trackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1trackingMode/title",
          "value": "trackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1trackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedCell/title",
          "value": "NSSegmentedCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedCell"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssegmentedcell/trackingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssegmentedcell/trackingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
