{
  "abstract": [
    {
      "text": "The value that represents the empty options set.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManagerSegmentOptions/NSTextLayoutManagerSegmentOptionsNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextLayoutManagerSegmentOptions@NSTextLayoutManagerSegmentOptionsNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutManagerSegmentOptionsNone"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutManagerSegmentOptionsNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSTextLayoutManagerSegmentOptionsNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptionsNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions": {
      "abstract": [
        {
          "text": "Values that describe where and how the framework extends segments of a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SegmentOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager.SegmentOptions",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManagerSegmentOptions/NSTextLayoutManagerSegmentOptionsNone": {
      "abstract": [
        {
          "text": "The value that represents the empty options set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManagerSegmentOptions/NSTextLayoutManagerSegmentOptionsNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutManagerSegmentOptionsNone",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanagersegmentoptions/nstextlayoutmanagersegmentoptionsnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions/title",
          "value": "NSTextLayoutManagerSegmentOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextlayoutmanagersegmentoptions/nstextlayoutmanagersegmentoptionsnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
