{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsimagestackdescriptor/width"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnsimagestackdescriptor/width"]}],"kind":"symbol","metadata":{"modules":[{"name":"Accelerate"}],"role":"symbol","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","deprecatedAt":"14.0","introducedAt":"10.0","message":"BNNS switched to new Layer Parameters data structures"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","deprecatedAt":"14.0","introducedAt":"10.0","message":"BNNS switched to new Layer Parameters data structures"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","deprecatedAt":"14.0","introducedAt":"13.1","message":"BNNS switched to new Layer Parameters data structures"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","deprecatedAt":"11.0","introducedAt":"10.12","message":"BNNS switched to new Layer Parameters data structures"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","deprecatedAt":"14.0","introducedAt":"10.0","message":"BNNS switched to new Layer Parameters data structures"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS","deprecatedAt":"1.0","introducedAt":"1.0","message":"BNNS switched to new Layer Parameters data structures"},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS","deprecatedAt":"7.0","introducedAt":"3.0","message":"BNNS switched to new Layer Parameters data structures"}],"navigatorTitle":[{"kind":"identifier","text":"width"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"width","externalID":"c:@SA@BNNSImageStackDescriptor@FI@width"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"BNNS switched to new Layer Parameters data structures"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width"},"references":{"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"BNNSImageStackDescriptor","url":"/documentation/accelerate/bnnsimagestackdescriptor","navigatorTitle":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor","role":"symbol","abstract":[],"deprecated":true},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@size_t":{"abstract":[{"type":"text","text":""}],"title":"size_t","type":"topic","kind":"symbol","url":"/documentation/kernel/size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"width"}],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/width","title":"width","type":"topic"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false},{"name":"watchOS","beta":false,"unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"width","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","kind":"typeIdentifier","text":"size_t","preciseIdentifier":"c:@T@size_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":[],"path":"/deprecationSummary"},{"op":"replace","value":"BNNSImageStackDescriptor","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/title"},{"op":"replace","value":[{"kind":"identifier","text":"BNNSImageStackDescriptor"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/fragments"},{"op":"replace","value":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/navigatorTitle"},{"op":"replace","value":"width","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1width/title"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1width/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}