{
  "abstract": [
    {
      "text": "The last known action was for the lock to be secured using physical movement on the interior of the door.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementInterior"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValueLockMechanismLastKnownAction@HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "securedUsingPhysicalMovementInterior"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedUsingPhysicalMovementInterior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "securedUsingPhysicalMovementInterior"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction": {
      "abstract": [
        {
          "text": "Possible values for the last known action of the locking mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownAction"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownAction"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedRemotely": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be secured remotely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securedRemotely"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedRemotely",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredRemotely"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedRemotely",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedremotely"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovement": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be secured using physical movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securedUsingPhysicalMovement"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovement"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedUsingPhysicalMovement",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedusingphysicalmovement"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementExterior": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be secured using physical movement on the exterior of the door.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securedUsingPhysicalMovementExterior"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementExterior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementExterior"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedUsingPhysicalMovementExterior",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedusingphysicalmovementexterior"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementInterior": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be secured using physical movement on the interior of the door.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securedUsingPhysicalMovementInterior"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementInterior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedUsingPhysicalMovementInterior",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedusingphysicalmovementinterior"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithAutomaticSecureTimeout": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be secured automatically after a timeout period expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securedWithAutomaticSecureTimeout"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithAutomaticSecureTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredWithAutomaticSecureTimeout"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedWithAutomaticSecureTimeout",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedwithautomaticsecuretimeout"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithKeypad": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be secured using a keypad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securedWithKeypad"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithKeypad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredWithKeypad"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.securedWithKeypad",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedwithkeypad"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredRemotely": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be unsecured remotely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsecuredRemotely"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredRemotely",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredRemotely"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.unsecuredRemotely",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/unsecuredremotely"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovement": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be unsecured using physical movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsecuredUsingPhysicalMovement"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovement"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.unsecuredUsingPhysicalMovement",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/unsecuredusingphysicalmovement"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementExterior": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be unsecured using physical movement on the exterior of the door.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsecuredUsingPhysicalMovementExterior"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementExterior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementExterior"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.unsecuredUsingPhysicalMovementExterior",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/unsecuredusingphysicalmovementexterior"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementInterior": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be unsecured using physical movement on the interior of the door.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsecuredUsingPhysicalMovementInterior"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementInterior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementInterior"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.unsecuredUsingPhysicalMovementInterior",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/unsecuredusingphysicalmovementinterior"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredWithKeypad": {
      "abstract": [
        {
          "text": "The last known action was for the lock to be unsecured using a keypad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsecuredWithKeypad"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredWithKeypad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredWithKeypad"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockMechanismLastKnownAction.unsecuredWithKeypad",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/unsecuredwithkeypad"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Lock-Mechanism-Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedRemotely",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovement",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementExterior",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithAutomaticSecureTimeout",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithKeypad",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredRemotely",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovement",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementExterior",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementInterior",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredWithKeypad"
      ],
      "title": "Lock Mechanism Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Lock-Mechanism-Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedRemotely",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovement",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedUsingPhysicalMovementExterior",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithAutomaticSecureTimeout",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/securedWithKeypad",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredRemotely",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovement",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementExterior",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredUsingPhysicalMovementInterior",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockMechanismLastKnownAction/unsecuredWithKeypad"
              ],
              "title": "Lock Mechanism Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedUsingPhysicalMovementInterior/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedUsingPhysicalMovementInterior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredUsingPhysicalMovementExterior/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementExterior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredUsingPhysicalMovementExterior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementExterior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedWithAutomaticSecureTimeout/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredWithAutomaticSecureTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedWithAutomaticSecureTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredWithAutomaticSecureTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredUsingPhysicalMovement/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredUsingPhysicalMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedWithKeypad/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredWithKeypad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedWithKeypad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredWithKeypad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedUsingPhysicalMovementExterior/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementExterior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedUsingPhysicalMovementExterior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementExterior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedRemotely/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredRemotely"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedRemotely/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredRemotely"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredUsingPhysicalMovementInterior/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementInterior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredUsingPhysicalMovementInterior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementInterior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredRemotely/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredRemotely"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredRemotely/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredRemotely"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredWithKeypad/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredWithKeypad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1unsecuredWithKeypad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionUnsecuredWithKeypad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedUsingPhysicalMovement/title",
          "value": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockMechanismLastKnownAction~1securedUsingPhysicalMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedusingphysicalmovementinterior"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluelockmechanismlastknownaction/securedusingphysicalmovementinterior"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
