{
  "abstract": [
    {
      "text": "Counter sampling is allowed at the start and end of a render pass’s vertex and fragment stages, and at the start and end of compute and blit passes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atStageBoundary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLCounterSamplingPoint@MTLCounterSamplingPointAtStageBoundary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "atStageBoundary"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCounterSamplingPointAtStageBoundary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLCounterSamplingPoint.atStageBoundary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "atStageBoundary"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/sampling-gpu-data-into-counter-sample-buffers"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint": {
      "abstract": [
        {
          "text": "Options for different times when you can sample GPU counters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPoint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPoint"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atBlitBoundary": {
      "abstract": [
        {
          "text": "Counter sampling is allowed between blit commands in a blit pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atBlitBoundary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atBlitBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPointAtBlitBoundary"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint.atBlitBoundary",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint/atblitboundary"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDispatchBoundary": {
      "abstract": [
        {
          "text": "Counter sampling is allowed between kernel dispatches in a compute pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atDispatchBoundary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDispatchBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPointAtDispatchBoundary"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint.atDispatchBoundary",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint/atdispatchboundary"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDrawBoundary": {
      "abstract": [
        {
          "text": "Counter sampling is allowed between draw commands in a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atDrawBoundary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDrawBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPointAtDrawBoundary"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint.atDrawBoundary",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint/atdrawboundary"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atStageBoundary": {
      "abstract": [
        {
          "text": "Counter sampling is allowed at the start and end of a render pass’s vertex and fragment stages, and at the start and end of compute and blit passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atStageBoundary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atStageBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPointAtStageBoundary"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint.atStageBoundary",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint/atstageboundary"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atTileDispatchBoundary": {
      "abstract": [
        {
          "text": "Counter sampling is allowed between tile dispatches in a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atTileDispatchBoundary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atTileDispatchBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPointAtTileDispatchBoundary"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint.atTileDispatchBoundary",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint/attiledispatchboundary"
    },
    "doc://com.apple.metal/documentation/Metal/sampling-gpu-data-into-counter-sample-buffers": {
      "abstract": [
        {
          "text": "Retrieve a GPU’s counter data at a time the GPU supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/sampling-gpu-data-into-counter-sample-buffers",
      "kind": "article",
      "role": "article",
      "title": "Sampling GPU Data into Counter Sample Buffers",
      "type": "topic",
      "url": "/documentation/metal/sampling-gpu-data-into-counter-sample-buffers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-Sampling-Boundary-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atBlitBoundary",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDispatchBoundary",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDrawBoundary",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atTileDispatchBoundary"
      ],
      "title": "Reading Sampling Boundary Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCounterSamplingPointAtStageBoundary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPointAtStageBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-Sampling-Boundary-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atBlitBoundary",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDispatchBoundary",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atDrawBoundary",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint/atTileDispatchBoundary"
              ],
              "title": "Reading Sampling Boundary Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLCounterSamplingPointAtStageBoundary"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atBlitBoundary/title",
          "value": "MTLCounterSamplingPointAtBlitBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atBlitBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPointAtBlitBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atDispatchBoundary/title",
          "value": "MTLCounterSamplingPointAtDispatchBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atDispatchBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPointAtDispatchBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atTileDispatchBoundary/title",
          "value": "MTLCounterSamplingPointAtTileDispatchBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atTileDispatchBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPointAtTileDispatchBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atStageBoundary/title",
          "value": "MTLCounterSamplingPointAtStageBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atStageBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPointAtStageBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint/title",
          "value": "MTLCounterSamplingPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atDrawBoundary/title",
          "value": "MTLCounterSamplingPointAtDrawBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint~1atDrawBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPointAtDrawBoundary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcountersamplingpoint/atstageboundary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcountersamplingpoint/atstageboundary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
