{
  "abstract": [
    {
      "text": "Returns a new binary arithmetic layer.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the BNNSGraph API instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryArithmeticLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryArithmeticLayer/init(inputA:inputADescriptorType:inputB:inputBDescriptorType:output:outputDescriptorType:function:activation:filterParameters:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:10Accelerate4BNNSO21BinaryArithmeticLayerC6inputA0F15ADescriptorType0F1B0f11BDescriptorH06output0j10DescriptorH08function10activation16filterParametersAESgSo011BNNSNDArrayK0a_AC0kH0OAqsqsC0dC8FunctionOAC010ActivationQ0OSo010BNNSFilterO0aSgtcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "inputA"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
        "text": "BNNSNDArrayDescriptor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "inputADescriptorType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO",
        "text": "BNNS"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
        "text": "DescriptorType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "inputB"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
        "text": "BNNSNDArrayDescriptor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "inputBDescriptorType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO",
        "text": "BNNS"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
        "text": "DescriptorType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "output"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
        "text": "BNNSNDArrayDescriptor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "outputDescriptorType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO",
        "text": "BNNS"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
        "text": "DescriptorType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "function"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO",
        "text": "BNNS"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO24ArithmeticBinaryFunctionO",
        "text": "ArithmeticBinaryFunction"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "activation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO",
        "text": "BNNS"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate4BNNSO18ActivationFunctionO",
        "text": "ActivationFunction"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "filterParameters"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@BNNSFilterParameters",
        "text": "BNNSFilterParameters"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "message": "Use the BNNSGraph API instead.",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(inputA:inputADescriptorType:inputB:inputBDescriptorType:output:outputDescriptorType:function:activation:filterParameters:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "inputA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
              "text": "BNNSNDArrayDescriptor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "inputADescriptorType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO",
              "text": "BNNS"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DescriptorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
              "text": "DescriptorType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "inputB"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
              "text": "BNNSNDArrayDescriptor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "inputBDescriptorType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO",
              "text": "BNNS"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DescriptorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
              "text": "DescriptorType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "output"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
              "text": "BNNSNDArrayDescriptor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "outputDescriptorType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO",
              "text": "BNNS"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DescriptorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
              "text": "DescriptorType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "function"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO",
              "text": "BNNS"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ArithmeticBinaryFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO24ArithmeticBinaryFunctionO",
              "text": "ArithmeticBinaryFunction"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "activation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO",
              "text": "BNNS"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ActivationFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate4BNNSO18ActivationFunctionO",
              "text": "ActivationFunction"
            },
            {
              "kind": "text",
              "text": " = .identity, "
            },
            {
              "kind": "externalParam",
              "text": "filterParameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@BNNSFilterParameters",
              "text": "BNNSFilterParameters"
            },
            {
              "kind": "text",
              "text": "? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The descriptor of the first input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inputA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The descriptor type of the first input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inputADescriptorType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The descriptor of the second input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inputB"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The descriptor type of the second input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inputBDescriptorType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The descriptor of the output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "output"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The descriptor type of the output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outputDescriptorType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The arithmetic function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "function"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The activation function that the layer applies to the output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "activation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The filter runtime parameters.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "filterParameters"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The data types of the inputs must be equal to the output data type. The size of the inputs must either 1, or the maximum size of either input and the output. Arithmetic layers only support arrays with a data type of ",
                  "type": "text"
                },
                {
                  "code": "float",
                  "type": "codeVoice"
                },
                {
                  "text": ", and a data layout of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/vector",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/matrixRowMajor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/matrixColumnMajor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/imageCHW",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to BNNS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "role": "symbol",
      "title": "BNNS",
      "type": "topic",
      "url": "/documentation/accelerate/bnns"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ActivationFunction": {
      "abstract": [
        {
          "text": "Constants that describe activation functions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ActivationFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNS.ActivationFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/activationfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ArithmeticBinaryFunction": {
      "abstract": [
        {
          "text": "Constants that describe binary arithmetic functions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArithmeticBinaryFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ArithmeticBinaryFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArithmeticBinaryFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNS.ArithmeticBinaryFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/arithmeticbinaryfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryArithmeticLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a binary arithmetic filter and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BinaryArithmeticLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryArithmeticLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BinaryArithmeticLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.BinaryArithmeticLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/binaryarithmeticlayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryArithmeticLayer/init(inputA:inputADescriptorType:inputB:inputBDescriptorType:output:outputDescriptorType:function:activation:filterParameters:)": {
      "abstract": [
        {
          "text": "Returns a new binary arithmetic layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "inputA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputADescriptorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
          "text": "DescriptorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputBDescriptorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
          "text": "DescriptorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputDescriptorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO14DescriptorTypeO",
          "text": "DescriptorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "function"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO24ArithmeticBinaryFunctionO",
          "text": "ArithmeticBinaryFunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "activation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO18ActivationFunctionO",
          "text": "ActivationFunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filterParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryArithmeticLayer/init(inputA:inputADescriptorType:inputB:inputBDescriptorType:output:outputDescriptorType:function:activation:filterParameters:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(inputA:inputADescriptorType:inputB:inputBDescriptorType:output:outputDescriptorType:function:activation:filterParameters:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/binaryarithmeticlayer/init(inputa:inputadescriptortype:inputb:inputbdescriptortype:output:outputdescriptortype:function:activation:filterparameters:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/imageCHW": {
      "abstract": [
        {
          "text": "A constant that represents a 3D image stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageCHW"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/imageCHW",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNS.DataLayout.imageCHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/datalayout/imagechw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/matrixColumnMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 2D column-major matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrixColumnMajor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/matrixColumnMajor",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNS.DataLayout.matrixColumnMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/datalayout/matrixcolumnmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/matrixRowMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 2D row-major matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrixRowMajor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/matrixRowMajor",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNS.DataLayout.matrixRowMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/datalayout/matrixrowmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/vector": {
      "abstract": [
        {
          "text": "A constant that represents a 1D vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DataLayout/vector",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNS.DataLayout.vector",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/datalayout/vector"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DescriptorType": {
      "abstract": [
        {
          "text": "Constants that describe the input and output types of an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DescriptorType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/DescriptorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DescriptorType"
        }
      ],
      "role": "symbol",
      "title": "BNNS.DescriptorType",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/descriptortype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters": {
      "abstract": [
        {
          "text": "A structure that contains common filter parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor": {
      "abstract": [
        {
          "text": "A structure that describes the shape, stride, data type, and, optionally, the memory location of an n-dimensional array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSNDArrayDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSNDArrayDescriptor"
        }
      ],
      "role": "symbol",
      "title": "BNNSNDArrayDescriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsndarraydescriptor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/title",
          "value": "BNNSFilterParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSNDArrayDescriptor/title",
          "value": "BNNSNDArrayDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSNDArrayDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSNDArrayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSNDArrayDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSNDArrayDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns/binaryarithmeticlayer/init(inputa:inputadescriptortype:inputb:inputbdescriptortype:output:outputdescriptortype:function:activation:filterparameters:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
