{
  "abstract": [
    {
      "text": "Converts the font to a lighter weight using ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convertWeight(_:of:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/lighterFontAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFontAction@NSLighterFontAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lighterFontAction"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLighterFontAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSFontAction.lighterFontAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lighterFontAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction": {
      "abstract": [
        {
          "text": "Actions that modify a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/addTraitFontAction": {
      "abstract": [
        {
          "text": "Converts the font to have an additional trait using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toHaveTrait:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTraitFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/addTraitFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAddTraitFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.addTraitFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/addtraitfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/heavierFontAction": {
      "abstract": [
        {
          "text": "Converts the font to a heavier weight using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convertWeight(_:of:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heavierFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/heavierFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHeavierFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.heavierFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/heavierfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/lighterFontAction": {
      "abstract": [
        {
          "text": "Converts the font to a lighter weight using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convertWeight(_:of:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lighterFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/lighterFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLighterFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.lighterFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/lighterfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/noFontChangeAction": {
      "abstract": [
        {
          "text": "No action; the font is returned unchanged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noFontChangeAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/noFontChangeAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoFontChangeAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.noFontChangeAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/nofontchangeaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/removeTraitFontAction": {
      "abstract": [
        {
          "text": "Converts the font to remove a trait using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toNotHaveTrait:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTraitFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/removeTraitFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRemoveTraitFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.removeTraitFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/removetraitfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeDownFontAction": {
      "abstract": [
        {
          "text": "Converts the font to a smaller size using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toSize:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeDownFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeDownFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSizeDownFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.sizeDownFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/sizedownfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeUpFontAction": {
      "abstract": [
        {
          "text": "Converts the font to a larger size using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toSize:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeUpFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeUpFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSizeUpFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.sizeUpFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/sizeupfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAction/viaPanelFontAction": {
      "abstract": [
        {
          "text": "Converts the font according to the ",
          "type": "text"
        },
        {
          "code": "NSFontPanel",
          "type": "codeVoice"
        },
        {
          "text": " method ",
          "type": "text"
        },
        {
          "code": "panelConvertFont:",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viaPanelFontAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAction/viaPanelFontAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViaPanelFontAction"
        }
      ],
      "role": "symbol",
      "title": "NSFontAction.viaPanelFontAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfontaction/viapanelfontaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toHaveTrait:)": {
      "abstract": [
        {
          "text": "Returns a new version of the font object containing a single additional trait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toHaveTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toHaveTrait:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertFont:toHaveTrait:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:toHaveTrait:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmanager/convert(_:tohavetrait:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toNotHaveTrait:)": {
      "abstract": [
        {
          "text": "Returns a new version of a font object without the specified traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toNotHaveTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toNotHaveTrait:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertFont:toNotHaveTrait:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:toNotHaveTrait:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmanager/convert(_:tonothavetrait:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toSize:)": {
      "abstract": [
        {
          "text": "Returns a font object whose traits are the same as those of the given font, except for the size, which is changed to the given size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convert(_:toSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertFont:toSize:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:toSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmanager/convert(_:tosize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convertWeight(_:of:)": {
      "abstract": [
        {
          "text": "Returns a font object whose weight is greater or lesser than that of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertWeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager/convertWeight(_:of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertWeight:ofFont:"
        }
      ],
      "role": "symbol",
      "title": "convertWeight(_:of:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmanager/convertweight(_:of:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/noFontChangeAction",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/viaPanelFontAction",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/addTraitFontAction",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeUpFontAction",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeDownFontAction",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/heavierFontAction",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAction/removeTraitFontAction"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLighterFontAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLighterFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/noFontChangeAction",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/viaPanelFontAction",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/addTraitFontAction",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeUpFontAction",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/sizeDownFontAction",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/heavierFontAction",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAction/removeTraitFontAction"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSLighterFontAction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1noFontChangeAction/title",
          "value": "NSNoFontChangeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1noFontChangeAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoFontChangeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1removeTraitFontAction/title",
          "value": "NSRemoveTraitFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1removeTraitFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRemoveTraitFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1sizeDownFontAction/title",
          "value": "NSSizeDownFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1sizeDownFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSizeDownFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convert(_:toSize:)/title",
          "value": "convertFont:toSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convert(_:toSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertFont:toSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1sizeUpFontAction/title",
          "value": "NSSizeUpFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1sizeUpFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSizeUpFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convert(_:toNotHaveTrait:)/title",
          "value": "convertFont:toNotHaveTrait:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convert(_:toNotHaveTrait:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertFont:toNotHaveTrait:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1addTraitFontAction/title",
          "value": "NSAddTraitFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1addTraitFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAddTraitFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1lighterFontAction/title",
          "value": "NSLighterFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1lighterFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLighterFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1heavierFontAction/title",
          "value": "NSHeavierFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1heavierFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHeavierFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1viaPanelFontAction/title",
          "value": "NSViaPanelFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction~1viaPanelFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViaPanelFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convert(_:toHaveTrait:)/title",
          "value": "convertFont:toHaveTrait:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convert(_:toHaveTrait:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertFont:toHaveTrait:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convertWeight(_:of:)/title",
          "value": "convertWeight:ofFont:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager~1convertWeight(_:of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertWeight:ofFont:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction/title",
          "value": "NSFontAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontaction/lighterfontaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontaction/lighterfontaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
