{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/systemLayoutFittingSizeDidChange(forChildContentContainer:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Notifies the container that a child view controller was resized using Auto Layout."}],"sections":[],"metadata":{"modules":[{"name":"UIKit"}],"platforms":[{"unavailable":false,"introducedAt":"8.0","beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"introducedAt":"8.0","beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false}],"title":"systemLayoutFittingSizeDidChange(forChildContentContainer:)","externalID":"c:objc(pl)UIContentContainer(im)systemLayoutFittingSizeDidChangeForChildContentContainer:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemLayoutFittingSizeDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forChildContentContainer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIContentContainer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIContentContainer"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"systemLayoutFittingSizeDidChangeForChildContentContainer:","kind":"identifier"}],"required":true,"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentContainer/size(forChildContentContainer:withParentContainerSize:)","doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSizeDidChange(forChildContentContainer:)","doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSize"],"anchor":"Responding-to-changes-in-child-view-controllers","title":"Responding to changes in child view controllers"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemLayoutFittingSizeDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forChildContentContainer","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"container","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIContentContainer","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer","text":"UIContentContainer","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"container","content":[{"inlineContent":[{"type":"text","text":"The child view controller that received the resizing message."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method is called when a view controller that doesn’t use Auto Layout has a child view controller that uses Auto Layout and the child view controller is resized. When the child view controller responds to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/systemLayoutSizeFitting(_:)"},{"text":" method, the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/systemLayoutFittingSizeDidChange(forChildContentContainer:)"},{"text":" method is sent to the parent view controller.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIContentContainer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicontentcontainer/systemlayoutfittingsizedidchange(forchildcontentcontainer:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicontentcontainer/systemlayoutfittingsizedidchange(forchildcontentcontainer:)"]}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIView/systemLayoutSizeFitting(_:)":{"title":"systemLayoutSizeFitting(_:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/systemLayoutSizeFitting(_:)","navigatorTitle":[{"kind":"identifier","text":"systemLayoutSizeFittingSize:"}],"url":"/documentation/uikit/uiview/systemlayoutsizefitting(_:)","abstract":[{"type":"text","text":"Returns the optimal size of the view based on its current constraints."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemLayoutSizeFitting"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIContentContainer":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContentContainer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A set of methods for adapting the contents of your view controllers to size and trait changes.","type":"text"}],"url":"/documentation/uikit/uicontentcontainer","title":"UIContentContainer","navigatorTitle":[{"text":"UIContentContainer","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/size(forChildContentContainer:withParentContainerSize:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/size(forChildContentContainer:withParentContainerSize:)","required":true,"abstract":[{"text":"Returns the size of the specified child view controller’s content.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChildContentContainer"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIContentContainer","text":"UIContentContainer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withParentContainerSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"sizeForChildContentContainer:withParentContainerSize:"}],"title":"size(forChildContentContainer:withParentContainerSize:)","url":"/documentation/uikit/uicontentcontainer/size(forchildcontentcontainer:withparentcontainersize:)"},"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSizeDidChange(forChildContentContainer:)":{"url":"/documentation/uikit/uicontentcontainer/preferredcontentsizedidchange(forchildcontentcontainer:)","role":"symbol","title":"preferredContentSizeDidChange(forChildContentContainer:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSizeDidChange(forChildContentContainer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredContentSizeDidChange"},{"text":"(","kind":"text"},{"text":"forChildContentContainer","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIContentContainer","text":"UIContentContainer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","required":true,"navigatorTitle":[{"text":"preferredContentSizeDidChangeForChildContentContainer:","kind":"identifier"}],"abstract":[{"type":"text","text":"Notifies an interested controller that the preferred content size of one of its children changed."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/systemLayoutFittingSizeDidChange(forChildContentContainer:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/systemLayoutFittingSizeDidChange(forChildContentContainer:)","abstract":[{"text":"Notifies the container that a child view controller was resized using Auto Layout.","type":"text"}],"role":"symbol","type":"topic","required":true,"title":"systemLayoutFittingSizeDidChange(forChildContentContainer:)","kind":"symbol","url":"/documentation/uikit/uicontentcontainer/systemlayoutfittingsizedidchange(forchildcontentcontainer:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemLayoutFittingSizeDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forChildContentContainer","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIContentContainer","text":"UIContentContainer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"systemLayoutFittingSizeDidChangeForChildContentContainer:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSize":{"title":"preferredContentSize","kind":"symbol","abstract":[{"text":"The preferred size for the container’s content.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uicontentcontainer/preferredcontentsize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"preferredContentSize"}],"type":"topic","required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"systemLayoutFittingSizeDidChangeForChildContentContainer:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"systemLayoutFittingSizeDidChangeForChildContentContainer:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIContentContainer"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Responding-to-changes-in-child-view-controllers","title":"Responding to changes in child view controllers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentContainer/size(forChildContentContainer:withParentContainerSize:)","doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSizeDidChange(forChildContentContainer:)","doc://com.apple.uikit/documentation/UIKit/UIContentContainer/preferredContentSize"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"systemLayoutFittingSizeDidChangeForChildContentContainer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIContentContainer","text":"id<UIContentContainer>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"container","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":{"parameters":[{"name":"container","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The child view controller that received the resizing message."}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1systemLayoutSizeFitting(_:)/title","value":"systemLayoutSizeFittingSize:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1systemLayoutSizeFitting(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"systemLayoutSizeFittingSize:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/title","value":"UIContentContainer"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/fragments","value":[{"text":"UIContentContainer","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/navigatorTitle","value":[{"text":"UIContentContainer","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1size(forChildContentContainer:withParentContainerSize:)/title","value":"sizeForChildContentContainer:withParentContainerSize:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1size(forChildContentContainer:withParentContainerSize:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeForChildContentContainer:withParentContainerSize:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1preferredContentSizeDidChange(forChildContentContainer:)/title","value":"preferredContentSizeDidChangeForChildContentContainer:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1preferredContentSizeDidChange(forChildContentContainer:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1systemLayoutFittingSizeDidChange(forChildContentContainer:)/title","value":"systemLayoutFittingSizeDidChangeForChildContentContainer:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1systemLayoutFittingSizeDidChange(forChildContentContainer:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"systemLayoutFittingSizeDidChangeForChildContentContainer:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1preferredContentSize/title","value":"preferredContentSize"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer~1preferredContentSize/fragments","value":[{"kind":"identifier","text":"preferredContentSize"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}