{
  "abstract": [
    {
      "text": "Determines the action that the system takes when it downloads a message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MEMessageActionHandler(im)decideActionForMessage:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "decideAction"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MEMessage",
        "text": "MEMessage"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
        "text": "MEMessageActionDecision"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "decideActionForMessage:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "decideAction(for:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decideAction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "message"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEMessage",
              "text": "MEMessage"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
              "text": "MEMessageActionDecision"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decideAction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "message"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEMessage",
              "text": "MEMessage"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
              "text": "MEMessageActionDecision"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The message the system downloads.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "message"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block you call that indicates the action to perform on the message, or if MailKit should invoke this method again after it downloads the message content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "func decideAction(for message: MEMessage) async -> MEMessageActionDecision?"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "As MailKit downloads messages, it invokes this method to determine what action, if any, it should perform on the message. MailKit initially calls this method before downloading the message content. If you can determine the action to take without requiring the entire body, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that indicates the action to take. Use the properties of ",
              "type": "text"
            },
            {
              "code": "message",
              "type": "codeVoice"
            },
            {
              "text": " to determine the action to take. For example, if the user chooses to set the color of messages from a particular person, use the message’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage/fromAddress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you can’t determine the action without the entire message content and ",
              "type": "text"
            },
            {
              "code": "bodyData",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", call the completion handler and pass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision/invokeAgainWithBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as the decision. MailKit invokes this method again later after the ",
              "type": "text"
            },
            {
              "code": "bodyData",
              "type": "codeVoice"
            },
            {
              "text": " in the message is available.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows an implementation that sets the color of all messages with Project Mars in the subject to red. Because this example only relies on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage/subject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of the message, it calls the completion handler with an action immediately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func decideActionForMessage(for message: MEMessage, completionHandler: @escaping (MEMessageActionDecision?) -> Void) {",
            "    var action: MEMessageActionDecision? = nil",
            "",
            "    // Check if the subject of the email is about Project Mars.",
            "    if message.subject.contains(\"Project Mars\") {",
            "        // Create an action to set the color of the",
            "        // message in the message list to red.",
            "         action = MEMessageActionDecision.action(.setColorActionWith(.red))",
            "    }",
            "    ",
            "    // Call the completion handler with the action, if any.",
            "    completionHandler(action)",
            "",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Always call the completion handler. If you don’t have an action to specify, pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The next example shows a different implementation that relies on the message body content to determine if a message is junk. In this case, when ",
              "type": "text"
            },
            {
              "code": "bodyData",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the handler calls the completion handler and passes ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision/invokeAgainWithBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When MailKit downloads the message content, it invokes this method again. This time, the handler converts the body data to a string. If the string indicates that the message is junk, the handler calls the completion handler passing an action that moves the message to the user’s Junk mailbox.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func decideActionForMessage(for message: MEMessage, completionHandler: @escaping (MEMessageActionDecision?) -> Void) {",
            "    var action: MEMessageActionDecision? = nil",
            "",
            "    // Check if the message content is available.",
            "    if message.bodyData == nil {",
            "        // If it isn't, request a repeat call when it is.",
            "        action = MEMessageActionDecision.invokeAgainWithBody",
            "    } else if let bodyData = message.bodyData,",
            "              let body = String(data: bodyData, encoding: .utf8){",
            "        ",
            "        // Determine if the message is junk or not.",
            "        let isJunk = body.contains(\"Make money fast!\")",
            "        ",
            "        // If it is, then call the completion handler with an action",
            "        // to move the message to the Junk mailbox.",
            "        if isJunk {",
            "            action = MEMessageActionDecision.action(.moveToJunk)",
            "        }",
            "    }",
            "    ",
            "    // Call the completion handler with the action, if any.",
            "    completionHandler(action)",
            "",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessage": {
      "abstract": [
        {
          "text": "An object that contains information about a mail message, such as the subject, addressees, date sent, and the message contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessage"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessage"
        }
      ],
      "role": "symbol",
      "title": "MEMessage",
      "type": "topic",
      "url": "/documentation/mailkit/memessage"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessage/fromAddress": {
      "abstract": [
        {
          "text": "The sender’s email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fromAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEmailAddress",
          "text": "MEEmailAddress"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage/fromAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fromAddress"
        }
      ],
      "role": "symbol",
      "title": "fromAddress",
      "type": "topic",
      "url": "/documentation/mailkit/memessage/fromaddress"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessage/subject": {
      "abstract": [
        {
          "text": "The subject of the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage/subject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subject"
        }
      ],
      "role": "symbol",
      "title": "subject",
      "type": "topic",
      "url": "/documentation/mailkit/memessage/subject"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction": {
      "abstract": [
        {
          "text": "An action the system performs on a message, such as setting a color or archiving it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageAction"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor": {
      "abstract": [
        {
          "text": "A color that the system uses to display a message in the message list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageColor"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageColor"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision": {
      "abstract": [
        {
          "text": "The action that the system performs on a message, or a request to ask the action handler again later when the message content is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageActionDecision"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionDecision"
        }
      ],
      "role": "symbol",
      "title": "MEMessageActionDecision",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactiondecision"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision/invokeAgainWithBody": {
      "abstract": [
        {
          "text": "An object that indicates the handler needs the message content before it can decide what action to take on a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invokeAgainWithBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
          "text": "MEMessageActionDecision"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision/invokeAgainWithBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invokeAgainWithBody"
        }
      ],
      "role": "symbol",
      "title": "invokeAgainWithBody",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactiondecision/invokeagainwithbody"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler": {
      "abstract": [
        {
          "text": "An object that performs actions on messages as the system downloads them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageActionHandler"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionHandler"
        }
      ],
      "role": "symbol",
      "title": "MEMessageActionHandler",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactionhandler"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Determines the action that the system takes when it downloads a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decideAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessage",
          "text": "MEMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
          "text": "MEMessageActionDecision"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler/decideAction(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decideActionForMessage:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "decideAction(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageactionhandler/decideaction(for:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Actions-on-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
      ],
      "title": "Performing Actions on Messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "decideActionForMessage:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decideActionForMessage:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionHandler"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Actions-on-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
              ],
              "title": "Performing Actions on Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "decideActionForMessage:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MEMessage",
                    "text": "MEMessage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "message"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageActionDecision",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MEMessageActionDecision",
                    "text": "MEMessageActionDecision"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "decision"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The message the system downloads.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "message"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block you call that indicates the action to perform on the message, or if MailKit should invoke this method again after it downloads the message content.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/title",
          "value": "MEMessageActionMessageColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage/title",
          "value": "MEMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision~1invokeAgainWithBody/title",
          "value": "invokeAgainWithBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision~1invokeAgainWithBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "invokeAgainWithBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/title",
          "value": "MEMessageAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage~1subject/title",
          "value": "subject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage~1subject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler/title",
          "value": "MEMessageActionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision/title",
          "value": "MEMessageActionDecision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionDecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionDecision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionDecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler~1decideAction(for:completionHandler:)/title",
          "value": "decideActionForMessage:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageActionHandler~1decideAction(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decideActionForMessage:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage~1fromAddress/title",
          "value": "fromAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessage~1fromAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fromAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/memessageactionhandler/decideaction(for:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/memessageactionhandler/decideaction(for:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
