{
  "abstract": [
    {
      "text": "The Last Page action.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFActionNamedName@kPDFActionNamedLastPage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lastPage"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kPDFActionNamedLastPage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PDFActionNamedName.lastPage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lastPage"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionNamedName"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionNamedName"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find": {
      "abstract": [
        {
          "text": "The Find action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "find"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedFind"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.find",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/find"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage": {
      "abstract": [
        {
          "text": "The First Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedFirstPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.firstPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/firstpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack": {
      "abstract": [
        {
          "text": "The Go Back action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goBack"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedGoBack"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.goBack",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/goback"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward": {
      "abstract": [
        {
          "text": "The Go Forward action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goForward"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedGoForward"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.goForward",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/goforward"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage": {
      "abstract": [
        {
          "text": "The Go to Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goToPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedGoToPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.goToPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/gotopage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage": {
      "abstract": [
        {
          "text": "The Last Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedLastPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.lastPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/lastpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage": {
      "abstract": [
        {
          "text": "The Next Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedNextPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.nextPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/nextpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none": {
      "abstract": [
        {
          "text": "The action has no name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedNone"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.none",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/none"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage": {
      "abstract": [
        {
          "text": "The Previous Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedPreviousPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.previousPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/previouspage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print": {
      "abstract": [
        {
          "text": "The Print action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "print"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedPrint"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.print",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/print"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn": {
      "abstract": [
        {
          "text": "The Zoom In action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomIn"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedZoomIn"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.zoomIn",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/zoomin"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut": {
      "abstract": [
        {
          "text": "The Zoom Out action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomOut"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedZoomOut"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.zoomOut",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/zoomout"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kPDFActionNamedLastPage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedLastPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kPDFActionNamedLastPage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1lastPage/title",
          "value": "kPDFActionNamedLastPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1lastPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedLastPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/title",
          "value": "PDFActionNamedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomIn/title",
          "value": "kPDFActionNamedZoomIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedZoomIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1nextPage/title",
          "value": "kPDFActionNamedNextPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1nextPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedNextPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1none/title",
          "value": "kPDFActionNamedNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goForward/title",
          "value": "kPDFActionNamedGoForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedGoForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomOut/title",
          "value": "kPDFActionNamedZoomOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedZoomOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1find/title",
          "value": "kPDFActionNamedFind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1find/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedFind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1previousPage/title",
          "value": "kPDFActionNamedPreviousPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1previousPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedPreviousPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goToPage/title",
          "value": "kPDFActionNamedGoToPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goToPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedGoToPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1print/title",
          "value": "kPDFActionNamedPrint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1print/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedPrint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1firstPage/title",
          "value": "kPDFActionNamedFirstPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1firstPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedFirstPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goBack/title",
          "value": "kPDFActionNamedGoBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedGoBack"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfactionnamedname/lastpage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfactionnamedname/lastpage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
