{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/cancel()"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"modules":[{"name":"Link Presentation"}],"externalID":"c:objc(cs)LPMetadataProvider(im)cancel","role":"symbol","title":"cancel()","navigatorTitle":[{"kind":"identifier","text":"cancel"}],"roleHeading":"Instance Method","symbolKind":"method","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"13.0"},{"introducedAt":"13.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"10.15","beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"introducedAt":"18.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"This method invokes the completion handler with the error code","type":"text"},{"text":" ","type":"text"},{"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","type":"reference","isActive":true},{"text":" if the request hasn’t already","type":"text"},{"text":" ","type":"text"},{"text":"completed.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Cancels a metadata request."}],"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/startFetchingMetadata(for:completionHandler:)-54z5i","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/shouldFetchSubresources","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/timeout"],"anchor":"Fetching-metadata","title":"Fetching metadata"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Link-Presentation/documentation/LinkPresentation","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/linkpresentation/lpmetadataprovider/cancel()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/linkpresentation/lpmetadataprovider/cancel()"]}],"references":{"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled":{"abstract":[{"type":"text","text":"An error indicating that the metadata fetch was canceled by the client."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchCancelled"}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","title":"LPError.Code.metadataFetchCancelled","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchCancelled"}],"url":"/documentation/linkpresentation/lperror/code/metadatafetchcancelled","role":"symbol"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/startFetchingMetadata(for:completionHandler:)-54z5i":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startFetchingMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"LPLinkMetadata","preciseIdentifier":"c:objc(cs)LPLinkMetadata","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/linkpresentation/lpmetadataprovider/startfetchingmetadata(for:completionhandler:)-54z5i","abstract":[{"type":"text","text":"Fetches metadata for the given URL."}],"title":"startFetchingMetadata(for:completionHandler:)","navigatorTitle":[{"text":"startFetchingMetadataForURL:completionHandler:","kind":"identifier"}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/startFetchingMetadata(for:completionHandler:)-54z5i","type":"topic"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation":{"title":"Link Presentation","type":"topic","kind":"symbol","role":"collection","url":"/documentation/linkpresentation","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation","abstract":[{"type":"text","text":"Fetch, provide, and present rich links in your app."}]},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/cancel()":{"type":"topic","url":"/documentation/linkpresentation/lpmetadataprovider/cancel()","navigatorTitle":[{"kind":"identifier","text":"cancel"}],"role":"symbol","title":"cancel()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/cancel()","abstract":[{"type":"text","text":"Cancels a metadata request."}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","role":"overview","type":"topic","title":"Technologies"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/shouldFetchSubresources":{"type":"topic","url":"/documentation/linkpresentation/lpmetadataprovider/shouldfetchsubresources","navigatorTitle":[{"text":"shouldFetchSubresources","kind":"identifier"}],"role":"symbol","title":"shouldFetchSubresources","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldFetchSubresources","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/shouldFetchSubresources","abstract":[{"type":"text","text":"A Boolean value indicating whether to download subresources specified by the"},{"type":"text","text":" "},{"type":"text","text":"metadata."}]},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider":{"type":"topic","url":"/documentation/linkpresentation/lpmetadataprovider","navigatorTitle":[{"text":"LPMetadataProvider","kind":"identifier"}],"role":"symbol","title":"LPMetadataProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LPMetadataProvider","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider","abstract":[{"type":"text","text":"An object that retrieves metadata for a URL."}]},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/timeout":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"url":"/documentation/linkpresentation/lpmetadataprovider/timeout","abstract":[{"type":"text","text":"The time interval after which the request automatically fails if it hasn’t"},{"text":" ","type":"text"},{"text":"already completed.","type":"text"}],"title":"timeout","navigatorTitle":[{"text":"timeout","kind":"identifier"}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/timeout","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"13.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"10.15","unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"introducedAt":"18.0","unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"cancel","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"cancel","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Link-Presentation/documentation/LinkPresentation","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/startFetchingMetadata(for:completionHandler:)-54z5i","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/shouldFetchSubresources","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPMetadataProvider/timeout"],"anchor":"Fetching-metadata","title":"Fetching metadata"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"LPErrorMetadataFetchCancelled","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/title","op":"replace"},{"value":[{"kind":"identifier","text":"LPErrorMetadataFetchCancelled"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/fragments","op":"replace"},{"value":"startFetchingMetadataForURL:completionHandler:","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1startFetchingMetadata(for:completionHandler:)-54z5i/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startFetchingMetadataForURL:completionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1startFetchingMetadata(for:completionHandler:)-54z5i/fragments","op":"replace"},{"value":"cancel","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1cancel()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cancel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1cancel()/fragments","op":"replace"},{"value":"shouldFetchSubresources","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1shouldFetchSubresources/title","op":"replace"},{"value":[{"text":"shouldFetchSubresources","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1shouldFetchSubresources/fragments","op":"replace"},{"value":"LPMetadataProvider","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider/title","op":"replace"},{"value":[{"text":"LPMetadataProvider","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider/navigatorTitle","value":[{"kind":"identifier","text":"LPMetadataProvider"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1timeout/title","value":"timeout","op":"replace"},{"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPMetadataProvider~1timeout/fragments","value":[{"kind":"identifier","text":"timeout"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}