{
  "abstract": [
    {
      "text": "An enumeration that defines the status of a requested voice call.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safetykit/documentation/SafetyKit",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SafetyKit",
    "externalID": "c:@E@SAEmergencyResponseManagerVoiceCallStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VoiceCallStatus"
      }
    ],
    "modules": [
      {
        "name": "SafetyKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VoiceCallStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SAEmergencyResponseManager.VoiceCallStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VoiceCallStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit": {
      "abstract": [
        {
          "text": "Detect and respond to car crash events in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SafetyKit",
      "type": "topic",
      "url": "/documentation/safetykit"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager": {
      "abstract": [
        {
          "text": "Provides actions in response to a Crash Detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManager"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManager"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus": {
      "abstract": [
        {
          "text": "An enumeration that defines the status of a requested voice call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VoiceCallStatus"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VoiceCallStatus"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager.VoiceCallStatus",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/equatable-implementations"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/rawrepresentable-implementations"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/active": {
      "abstract": [
        {
          "text": "The system successfully placed a call to the desired contact and that call is currently active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/active",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManagerVoiceCallStatusActive"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager.VoiceCallStatus.active",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/active"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/dialing": {
      "abstract": [
        {
          "text": "The system is dialing the desired contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialing"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/dialing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManagerVoiceCallStatusDialing"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager.VoiceCallStatus.dialing",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/dialing"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/disconnected": {
      "abstract": [
        {
          "text": "The voice call to the desired contact disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnected"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/disconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManagerVoiceCallStatusDisconnected"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager.VoiceCallStatus.disconnected",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/disconnected"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/failed": {
      "abstract": [
        {
          "text": "The voice call failed to connect to the desired contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManagerVoiceCallStatusFailed"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager.VoiceCallStatus.failed",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/failed"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus/init(rawvalue:)"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate": {
      "abstract": [
        {
          "text": "The object that receives voice call status updates and requested emergency response actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SAEmergencyResponseDelegate",
          "text": "SAEmergencyResponseDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/delegate"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)": {
      "abstract": [
        {
          "text": "Request the system to dial a voice call on behalf of someone involved in a crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialVoiceCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toPhoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dialVoiceCallToPhoneNumber:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "dialVoiceCall(toPhoneNumber:completionHandler:)",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/dialvoicecall(tophonenumber:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Placing-a-voice-call",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate"
      ],
      "title": "Placing a voice call"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-call-status",
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/active",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/dialing",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/disconnected",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/failed"
      ],
      "title": "Determining call status"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/Equatable-Implementations",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safetykit/documentation/SafetyKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-call-status",
              "identifiers": [
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/active",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/dialing",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/disconnected",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus/failed"
              ],
              "title": "Determining call status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Placing-a-voice-call",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate"
              ],
              "title": "Placing a voice call"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SAEmergencyResponseManagerVoiceCallStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SAEmergencyResponseManagerVoiceCallStatus"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1disconnected/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatusDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1disconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatusDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1dialing/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatusDialing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1dialing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatusDialing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1failed/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatusFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatusFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/title",
          "value": "SAEmergencyResponseManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1dialVoiceCall(toPhoneNumber:completionHandler:)/title",
          "value": "dialVoiceCallToPhoneNumber:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1dialVoiceCall(toPhoneNumber:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dialVoiceCallToPhoneNumber:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1active/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatusActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus~1active/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatusActive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
