{
  "abstract": [
    {
      "text": "Constants that state whether larger or smaller measurements, relative to a set baseline, indicate better performance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "c:@E@XCTPerformanceMeasurementPolarity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Polarity"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Polarity"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "XCTPerformanceMeasurement.Polarity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Polarity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement": {
      "abstract": [
        {
          "text": "A measurement from a single iteration of a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum": {
      "abstract": [
        {
          "text": "Constants that state whether larger or smaller measurements, relative to a set baseline, indicate better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Polarity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Polarity"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger": {
      "abstract": [
        {
          "text": "A performance measurement where a larger value, relative to a set baseline, indicates better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersLarger"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity.prefersLarger",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/preferslarger"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller": {
      "abstract": [
        {
          "text": "A performance measurement where a smaller value, relative to a set baseline, indicates better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersSmaller"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementPolarityPrefersSmaller"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity.prefersSmaller",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/preferssmaller"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified": {
      "abstract": [
        {
          "text": "A performance measurement that doesn’t specify whether a larger or smaller value, relative to a set baseline, indicates better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementPolarityUnspecified"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity.unspecified",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/unspecified"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue": {
      "abstract": [
        {
          "text": "The measured value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleValue"
        }
      ],
      "role": "symbol",
      "title": "doubleValue",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/doublevalue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property": {
      "abstract": [
        {
          "text": "A constant that states whether larger or smaller measurements, relative to a set baseline, indicate better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polarity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTPerformanceMeasurement",
          "text": "XCTPerformanceMeasurement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTPerformanceMeasurementPolarity",
          "text": "Polarity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "polarity"
        }
      ],
      "role": "symbol",
      "title": "polarity",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol": {
      "abstract": [
        {
          "text": "A string that represents the unit of measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitSymbol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unitSymbol"
        }
      ],
      "role": "symbol",
      "title": "unitSymbol",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/unitsymbol"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value": {
      "abstract": [
        {
          "text": "The measured value, including the unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnit",
          "text": "Unit"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/value"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Measured-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property"
      ],
      "title": "Accessing Measured Values"
    }
  ],
  "topicSections": [
    {
      "anchor": "Polarity-Types",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified"
      ],
      "title": "Polarity Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTPerformanceMeasurementPolarity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Polarity-Types",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified"
              ],
              "title": "Polarity Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Measured-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property"
              ],
              "title": "Accessing Measured Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTPerformanceMeasurementPolarity"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1unspecified/title",
          "value": "XCTPerformanceMeasurementPolarityUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1unitSymbol/title",
          "value": "unitSymbol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1unitSymbol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unitSymbol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersLarger/title",
          "value": "XCTPerformanceMeasurementPolarityPrefersLarger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersLarger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1doubleValue/title",
          "value": "doubleValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1doubleValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/title",
          "value": "XCTPerformanceMeasurementPolarity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1polarity-swift.property/title",
          "value": "polarity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1polarity-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "polarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersSmaller/title",
          "value": "XCTPerformanceMeasurementPolarityPrefersSmaller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersSmaller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityPrefersSmaller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/title",
          "value": "XCTPerformanceMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
