{
  "abstract": [
    {
      "text": "A list of ordered rules that defines the networks on which the DNS settings will apply.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/onDemandRules"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEDNSSettingsManager(py)onDemandRules",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "onDemandRules"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NEOnDemandRule",
        "text": "NEOnDemandRule"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "onDemandRules"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "onDemandRules"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "onDemandRules"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRule",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEOnDemandRule",
              "text": "NEOnDemandRule"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An On Demand rule with the action ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defines a network on which the DNS settings apply. An On Demand rule with the action ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/disconnect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " causes DNS settings to not apply. An On Demand rule with the action of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can be used to enable the DNS settings on a network with excluded domains, as specified using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/neverConnect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " rule.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager": {
      "abstract": [
        {
          "text": "An object you use to create and manage a DNS settings configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEDNSSettingsManager"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEDNSSettingsManager"
        }
      ],
      "role": "symbol",
      "title": "NEDNSSettingsManager",
      "type": "topic",
      "url": "/documentation/networkextension/nednssettingsmanager"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/dnsSettings": {
      "abstract": [
        {
          "text": "An object that contains the configuration settings for a DNS server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dnsSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEDNSSettings",
          "text": "NEDNSSettings"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/dnsSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dnsSettings"
        }
      ],
      "role": "symbol",
      "title": "dnsSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nednssettingsmanager/dnssettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean you use to query the enabled state of the DNS settings configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/networkextension/nednssettingsmanager/isenabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/localizedDescription": {
      "abstract": [
        {
          "text": "A string that contains the display name of the DNS settings configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/localizedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDescription"
        }
      ],
      "role": "symbol",
      "title": "localizedDescription",
      "type": "topic",
      "url": "/documentation/networkextension/nednssettingsmanager/localizeddescription"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/onDemandRules": {
      "abstract": [
        {
          "text": "A list of ordered rules that defines the networks on which the DNS settings will apply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onDemandRules"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEOnDemandRule",
          "text": "NEOnDemandRule"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/onDemandRules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "onDemandRules"
        }
      ],
      "role": "symbol",
      "title": "onDemandRules",
      "type": "topic",
      "url": "/documentation/networkextension/nednssettingsmanager/ondemandrules"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/neverConnect": {
      "abstract": [
        {
          "text": "Do not start the VPN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neverConnect"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/neverConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEEvaluateConnectionRuleActionNeverConnect"
        }
      ],
      "role": "symbol",
      "title": "NEEvaluateConnectionRuleAction.neverConnect",
      "type": "topic",
      "url": "/documentation/networkextension/neevaluateconnectionruleaction/neverconnect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRule": {
      "abstract": [
        {
          "text": "A base class shared by all VPN On Demand rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEOnDemandRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRule"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRule",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect": {
      "abstract": [
        {
          "text": "Start the VPN connection for every connection attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connect"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionConnect"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.connect",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/connect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/disconnect": {
      "abstract": [
        {
          "text": "Do not start the VPN connection, and disconnect the VPN connection if it is not currently disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnect"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/disconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionDisconnect"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.disconnect",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/disconnect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection": {
      "abstract": [
        {
          "text": "Start the VPN after evaluating the destination host being accessed against the rule’s parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluateConnection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionEvaluateConnection"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.evaluateConnection",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/evaluateconnection"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-DNS-configuration-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/isEnabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/dnsSettings",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/localizedDescription"
      ],
      "title": "Accessing DNS configuration properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "onDemandRules"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "onDemandRules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-DNS-configuration-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/isEnabled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/dnsSettings",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager/localizedDescription"
              ],
              "title": "Accessing DNS configuration properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NEOnDemandRule *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "onDemandRules"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1connect/title",
          "value": "NEOnDemandRuleActionConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1connect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRule/title",
          "value": "NEOnDemandRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1dnsSettings/title",
          "value": "dnsSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1dnsSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dnsSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1disconnect/title",
          "value": "NEOnDemandRuleActionDisconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1disconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1localizedDescription/title",
          "value": "localizedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1localizedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRuleAction~1neverConnect/title",
          "value": "NEEvaluateConnectionRuleActionNeverConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRuleAction~1neverConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEEvaluateConnectionRuleActionNeverConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1onDemandRules/title",
          "value": "onDemandRules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager~1onDemandRules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "onDemandRules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1evaluateConnection/title",
          "value": "NEOnDemandRuleActionEvaluateConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1evaluateConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionEvaluateConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager/title",
          "value": "NEDNSSettingsManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSSettingsManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSSettingsManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nednssettingsmanager/ondemandrules"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nednssettingsmanager/ondemandrules"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
