{
  "abstract": [
    {
      "text": "The unknown-person view controller delegate.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use +[CNContactViewController viewControllerForUnknownContact:] from ContactsUI.framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbookui/documentation/AddressBookUI",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController/unknownPersonViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABUnknownPersonViewController(py)unknownPersonViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknownPersonViewDelegate"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)ABUnknownPersonViewControllerDelegate",
        "text": "ABUnknownPersonViewControllerDelegate"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "Address Book UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "unknownPersonViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "Use +[CNContactViewController viewControllerForUnknownContact:] from ContactsUI.framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "Use +[CNContactViewController viewControllerForUnknownContact:] from ContactsUI.framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use +[CNContactViewController viewControllerForUnknownContact:] from ContactsUI.framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "unknownPersonViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "unowned(unsafe)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknownPersonViewDelegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)ABUnknownPersonViewControllerDelegate",
              "text": "ABUnknownPersonViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The delegate must adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbookui/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/addressbookui"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABUnknownPersonViewController",
          "type": "codeVoice"
        },
        {
          "text": " class (whose instances are known as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "unknown-person view controllers",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ") implements a view controller used to create a person record from a set of person properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewController"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewController"
        }
      ],
      "role": "symbol",
      "title": "ABUnknownPersonViewController",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontroller"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController/unknownPersonViewDelegate": {
      "abstract": [
        {
          "text": "The unknown-person view controller delegate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownPersonViewDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ABUnknownPersonViewControllerDelegate",
          "text": "ABUnknownPersonViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController/unknownPersonViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unknownPersonViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "unknownPersonViewDelegate",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontroller/unknownpersonviewdelegate"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate": {
      "abstract": [
        {
          "text": "The methods you use to respond to events in an unknown person view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "ABUnknownPersonViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontrollerdelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-View-Controller-Interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate"
      ],
      "title": "Responding to View Controller Interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "unknownPersonViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unknownPersonViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbookui/documentation/AddressBookUI",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-View-Controller-Interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate"
              ],
              "title": "Responding to View Controller Interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)ABUnknownPersonViewControllerDelegate",
                    "text": "id<ABUnknownPersonViewControllerDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "unknownPersonViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use +[CNContactViewController viewControllerForUnknownContact:] from ContactsUI.framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController~1unknownPersonViewDelegate/title",
          "value": "unknownPersonViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController~1unknownPersonViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unknownPersonViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate/title",
          "value": "ABUnknownPersonViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController/title",
          "value": "ABUnknownPersonViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbookui/abunknownpersonviewcontroller/unknownpersonviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbookui/abunknownpersonviewcontroller/unknownpersonviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
