{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision/resizingRestrictions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So38UIWindowSceneGeometryPreferencesVisionC5UIKitE20resizingRestrictionsSo0aB0CACE08ResizingH0OSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resizingRestrictions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIWindowScene",
        "text": "UIWindowScene"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So13UIWindowSceneC5UIKitE20ResizingRestrictionsO",
        "text": "ResizingRestrictions"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "resizingRestrictions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resizingRestrictions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindowScene",
              "text": "UIWindowScene"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So13UIWindowSceneC5UIKitE20ResizingRestrictionsO",
              "text": "ResizingRestrictions"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene": {
      "abstract": [
        {
          "text": "A scene that manages one or more windows for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences": {
      "abstract": [
        {
          "text": "An abstract superclass for representing window scene geometry preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometryPreferences"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GeometryPreferences"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Vision"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Vision"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.Vision",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/vision"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision/resizingRestrictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizingRestrictions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13UIWindowSceneC5UIKitE20ResizingRestrictionsO",
          "text": "ResizingRestrictions"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision/resizingRestrictions",
      "kind": "symbol",
      "role": "symbol",
      "title": "resizingRestrictions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/vision/resizingrestrictions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResizingRestrictions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResizingRestrictions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ResizingRestrictions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/resizingrestrictions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/title",
          "value": "UIWindowSceneGeometryPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/title",
          "value": "UIWindowSceneGeometryPreferencesVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title",
          "value": "UIWindowScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/geometrypreferences/vision/resizingrestrictions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
