{
  "abstract": [
    {
      "text": "Removes a text range from the set of matches.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidateFoundRange:inDocument:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextSearchAggregator(im)invalidateFoundRange:inDocument:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "invalidateFoundRange:inDocument:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "invalidateFoundRange:inDocument:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "invalidateFoundRange:inDocument:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "invalidateFoundRange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextRange",
              "text": "UITextRange"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inDocument:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextSearchDocumentIdentifier",
              "text": "UITextSearchDocumentIdentifier"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "document"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text range to remove from the set of matches.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string that uniquely identifies the document containing the text range. ",
                  "type": "text"
                },
                {
                  "code": "Nil",
                  "type": "codeVoice"
                },
                {
                  "text": " when searching a single document.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "document"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to invalidate a text range when removing or changing text in the document. This causes the system find panel to update its current state, and if the range is the highlighted range, the find panel advances to the next found result.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextRange": {
      "abstract": [
        {
          "text": "A range of characters in a text container with a starting index and an ending index in string backing a text-entry object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextRange"
        }
      ],
      "role": "symbol",
      "title": "UITextRange",
      "type": "topic",
      "url": "/documentation/uikit/uitextrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s aggregator to collect matching text ranges for a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchAggregator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchAggregator",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/allFoundRanges": {
      "abstract": [
        {
          "text": "An ordered set of all the text ranges that match the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "allFoundRanges"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/allFoundRanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "allFoundRanges",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/allfoundranges"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/finishedSearching": {
      "abstract": [
        {
          "text": "Finishes the search for text ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "finishedSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/finishedSearching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishedSearching"
        }
      ],
      "role": "symbol",
      "title": "finishedSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/finishedsearching"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/foundRange:forSearchString:inDocument:": {
      "abstract": [
        {
          "text": "Adds a text range to the set of matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "foundRange:forSearchString:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/foundRange:forSearchString:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "foundRange:forSearchString:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "foundRange:forSearchString:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/foundrange:forsearchstring:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidate": {
      "abstract": [
        {
          "text": "Invalidates all currently shown ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "role": "symbol",
      "title": "invalidate",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/invalidate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidateFoundRange:inDocument:": {
      "abstract": [
        {
          "text": "Removes a text range from the set of matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "invalidateFoundRange:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidateFoundRange:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateFoundRange:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "invalidateFoundRange:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/invalidatefoundrange:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a specific document when searching for matching text across multiple documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchDocumentIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchDocumentIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchdocumentidentifier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tracking-search-results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/foundRange:forSearchString:inDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidate",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/finishedSearching",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/allFoundRanges"
      ],
      "title": "Tracking search results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/title",
          "value": "UITextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearchaggregator-c.protocol/invalidatefoundrange:indocument:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
