{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:16_PassKit_SwiftUI03AddA20ToWalletButtonFilterV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AddPassToWalletButtonFilter"
      }
    ],
    "modules": [
      {
        "name": "PassKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AddPassToWalletButtonFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AddPassToWalletButtonFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AddPassToWalletButtonFilter"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButton": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AddPassToWalletButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AddPassToWalletButton"
        }
      ],
      "role": "symbol",
      "title": "AddPassToWalletButton",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AddPassToWalletButtonFilter"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AddPassToWalletButtonFilter"
        }
      ],
      "role": "symbol",
      "title": "AddPassToWalletButtonFilter",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbuttonfilter"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/paymentNetwork(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentNetwork"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI03AddA20ToWalletButtonFilterV",
          "text": "AddPassToWalletButtonFilter"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/paymentNetwork(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentNetwork(_:)",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbuttonfilter/paymentnetwork(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/primaryAccountIdentifier(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccountIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI03AddA20ToWalletButtonFilterV",
          "text": "AddPassToWalletButtonFilter"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/primaryAccountIdentifier(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "primaryAccountIdentifier(_:)",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbuttonfilter/primaryaccountidentifier(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/productIdentifier(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI03AddA20ToWalletButtonFilterV",
          "text": "AddPassToWalletButtonFilter"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/productIdentifier(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "productIdentifier(_:)",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbuttonfilter/productidentifier(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AddPassToWalletButtonResponse"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AddPassToWalletButtonResponse"
        }
      ],
      "role": "symbol",
      "title": "AddPassToWalletButtonResponse",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbuttonresponse"
    },
    "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AddPassToWalletButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AddPassToWalletButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "AddPassToWalletButtonStyle",
      "type": "topic",
      "url": "/documentation/passkit/addpasstowalletbuttonstyle"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassButton": {
      "abstract": [
        {
          "text": "Provides a button that enables users to add passes to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassButton"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassButton",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassbutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue": {
      "abstract": [
        {
          "text": "An object that can represent a detail about a payment card or other item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKLabeledValue"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKLabeledValue"
        }
      ],
      "role": "symbol",
      "title": "PKLabeledValue",
      "type": "topic",
      "url": "/documentation/passkit/pklabeledvalue"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKObject": {
      "abstract": [
        {
          "text": "An opaque type that acts as the superclass for the pass object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKObject"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKObject"
        }
      ],
      "role": "symbol",
      "title": "PKObject",
      "type": "topic",
      "url": "/documentation/passkit/pkobject"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKObject",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPassButton",
        "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
        "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButton",
        "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonResponse",
        "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonStyle"
      ],
      "title": "Common objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/paymentNetwork(_:)",
        "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/primaryAccountIdentifier(_:)",
        "doc://com.apple.passkit/documentation/PassKit/AddPassToWalletButtonFilter/productIdentifier(_:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/title",
          "value": "PKLabeledValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassButton/title",
          "value": "PKAddPassButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKObject/title",
          "value": "PKObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/addpasstowalletbuttonfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
