{
  "abstract": [
    {
      "text": "Error code constants for identity operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/wallet",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/error-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931637-code": {
      "abstract": [
        {
          "text": "The error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": Code"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931637-code",
      "kind": "symbol",
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931637-code"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931638-errorcode": {
      "abstract": [
        {
          "text": "The integer error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorCode"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931638-errorcode",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorCode",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931638-errorcode"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931640-erroruserinfo": {
      "abstract": [
        {
          "text": "The error user information dictionary for the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorUserInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931640-erroruserinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorUserInfo",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931640-erroruserinfo"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931651-userinfo": {
      "abstract": [
        {
          "text": "The user information for the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931651-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931651-userinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an identity error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for identity operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/cancelled": {
      "abstract": [
        {
          "text": "An error that indicates the user cancels the presented sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/cancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/cancelled"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/invalidElement": {
      "abstract": [
        {
          "text": "An error that indicates an element the app requests isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/invalidElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidElement",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/invalidelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/invalidNonce": {
      "abstract": [
        {
          "text": "An error that indicates the number is too large or unsuitable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/invalidNonce",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidNonce",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/invalidnonce"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/networkUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates a network isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/networkUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkUnavailable",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/networkunavailable"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/noElementsRequested": {
      "abstract": [
        {
          "text": "An error that indicates the elements aren’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noElementsRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/noElementsRequested",
      "kind": "symbol",
      "role": "symbol",
      "title": "noElementsRequested",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/noelementsrequested"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/notSupported": {
      "abstract": [
        {
          "text": "An error that indicates the request originates from a device the framework doesn’t support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/notSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "notSupported",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/notsupported"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/requestAlreadyInProgress": {
      "abstract": [
        {
          "text": "An error that indicates a request is already in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAlreadyInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/requestAlreadyInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestAlreadyInProgress",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/requestalreadyinprogress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15PKIdentityErrorLeV",
          "text": "PKIdentityError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIdentityError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/unknown"
    },
    "doc://com.apple.passkit/documentation/PassKit/wallet": {
      "abstract": [
        {
          "text": "Manage tickets, boarding passes, payment cards and other passes in the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/wallet",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Wallet",
      "type": "topic",
      "url": "/documentation/passkit/wallet"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-error",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931637-code",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931638-errorcode",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931651-userinfo",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkidentityerror/3931640-erroruserinfo"
      ],
      "title": "Inspecting an error"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/cancelled",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/invalidElement",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/invalidNonce",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/notSupported",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/networkUnavailable",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/noElementsRequested",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/requestAlreadyInProgress",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-error",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code"
              ],
              "title": "Inspecting an error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/title",
          "value": "PKIdentityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/error-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/error-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
