{
  "abstract": [
    {
      "text": "A set of actions for viewing and updating PINs, passwords, and signing abilities associated with digital identities on the JPKI applet.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7PassKit16JPKIPassContentsV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JPKIPassContents"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JPKIPassContents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "JPKIPassContents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JPKIPassContents"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Supports access to installed digital identities associated with the pass. You can use these actions to perform all operations to view, modify, and act on the credientials the applet contains.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents": {
      "abstract": [
        {
          "text": "A set of actions for viewing and updating PINs, passwords, and signing abilities associated with digital identities on the JPKI applet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JPKIPassContents"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JPKIPassContents"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/AuthenticationRequest": {
      "abstract": [
        {
          "text": "The user authentification request based on the generics type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthenticationRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/AuthenticationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthenticationRequest"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.AuthenticationRequest",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/authenticationrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Certificate": {
      "abstract": [
        {
          "text": "The certificate data associated with an identity document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Certificate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Certificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Certificate"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.Certificate",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/certificate"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Error": {
      "abstract": [
        {
          "text": "Defines a set of possible errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.Error",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/error"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Identity": {
      "abstract": [
        {
          "text": "Defines the common functionality that JPKI digital identities support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Identity"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Identity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Identity"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.Identity",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/identity"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Signature": {
      "abstract": [
        {
          "text": "The resulting signed data and certificate you use to sign the pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Signature"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Signature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Signature"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.Signature",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/signature"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/SigningIdentity-swift.struct": {
      "abstract": [
        {
          "text": "The authentication for signing user identification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SigningIdentity"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/SigningIdentity-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SigningIdentity"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.SigningIdentity",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/signingidentity-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/UserIdentity-swift.struct": {
      "abstract": [
        {
          "text": "The functionality for the type of user identification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserIdentity"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/UserIdentity-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserIdentity"
        }
      ],
      "role": "symbol",
      "title": "JPKIPassContents.UserIdentity",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/useridentity-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/init(_:)": {
      "abstract": [
        {
          "text": "Initializes with the digital identity state of the provided pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/init(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/signingIdentity-swift.property": {
      "abstract": [
        {
          "text": "Allows access to the signing identity, if present in the JPKI applet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signingIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7PassKit16JPKIPassContentsV",
          "text": "JPKIPassContents"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7PassKit16JPKIPassContentsV15SigningIdentityV",
          "text": "SigningIdentity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/signingIdentity-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "signingIdentity",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/signingidentity-swift.property"
    },
    "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/userIdentity-swift.property": {
      "abstract": [
        {
          "text": "Allows for access to the user identity, if present in the JPKI applet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7PassKit16JPKIPassContentsV",
          "text": "JPKIPassContents"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7PassKit16JPKIPassContentsV12UserIdentityV",
          "text": "UserIdentity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/userIdentity-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "userIdentity",
      "type": "topic",
      "url": "/documentation/passkit/jpkipasscontents/useridentity-swift.property"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddIdentityDocumentConfiguration": {
      "abstract": [
        {
          "text": "Configuration to define the identity document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddIdentityDocumentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddIdentityDocumentConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddIdentityDocumentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PKAddIdentityDocumentConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/pkaddidentitydocumentconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview": {
      "abstract": [
        {
          "text": "A preview object that contains information representing the pass you add to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassMetadataPreview"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassMetadataPreview"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassMetadataPreview",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassmetadatapreview"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentMetadata": {
      "abstract": [
        {
          "text": "A set of configured metadata defining the required information to add the corresponding pass to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityDocumentMetadata"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityDocumentMetadata"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityDocumentMetadata",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydocumentmetadata"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor": {
      "abstract": [
        {
          "text": "An object for requesting information from a user’s national ID card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityNationalIDCardDescriptor"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityNationalIDCardDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityNationalIDCardDescriptor",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitynationalidcarddescriptor"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKJapanIndividualNumberCardMetadata": {
      "abstract": [
        {
          "text": "A class that contains metadata indicating the specific product instance to provision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKJapanIndividualNumberCardMetadata"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKJapanIndividualNumberCardMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKJapanIndividualNumberCardMetadata"
        }
      ],
      "role": "symbol",
      "title": "PKJapanIndividualNumberCardMetadata",
      "type": "topic",
      "url": "/documentation/passkit/pkjapanindividualnumbercardmetadata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Japan-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddIdentityDocumentConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentMetadata",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor",
        "doc://com.apple.passkit/documentation/PassKit/PKJapanIndividualNumberCardMetadata"
      ],
      "title": "Japan passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-the-digital-identity",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/init(_:)"
      ],
      "title": "Initializing the digital identity"
    },
    {
      "anchor": "Defining-access-to-the-identity-passes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/UserIdentity-swift.struct",
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/SigningIdentity-swift.struct",
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Signature",
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Certificate",
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/AuthenticationRequest",
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Identity"
      ],
      "title": "Defining access to the identity passes"
    },
    {
      "anchor": "Error-cases",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/Error"
      ],
      "title": "Error cases"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/signingIdentity-swift.property",
        "doc://com.apple.passkit/documentation/PassKit/JPKIPassContents/userIdentity-swift.property"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddIdentityDocumentConfiguration/title",
          "value": "PKAddIdentityDocumentConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddIdentityDocumentConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddIdentityDocumentConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddIdentityDocumentConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddIdentityDocumentConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/title",
          "value": "PKIdentityNationalIDCardDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityNationalIDCardDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityNationalIDCardDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKJapanIndividualNumberCardMetadata/title",
          "value": "PKJapanIndividualNumberCardMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKJapanIndividualNumberCardMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKJapanIndividualNumberCardMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKJapanIndividualNumberCardMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKJapanIndividualNumberCardMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassMetadataPreview/title",
          "value": "PKAddPassMetadataPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassMetadataPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassMetadataPreview/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentMetadata/title",
          "value": "PKIdentityDocumentMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentMetadata"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/jpkipasscontents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
