{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonStyleV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PayWithApplePayButtonStyle"
      }
    ],
    "modules": [
      {
        "name": "PassKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PayWithApplePayButtonStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PayWithApplePayButtonStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PayWithApplePayButtonStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButton": {
      "abstract": [
        {
          "text": "An object that displays a button either to trigger payments through Apple Pay or to prompt the user to set up a card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButton"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButton",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButton": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButton"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButton",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButtonLabel",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButtonStyle",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonstyle"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/automatic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonStyleV",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/automatic",
      "kind": "symbol",
      "role": "symbol",
      "title": "automatic",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonstyle/automatic"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/black": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonStyleV",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/black",
      "kind": "symbol",
      "role": "symbol",
      "title": "black",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonstyle/black"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/white": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "white"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonStyleV",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/white",
      "kind": "symbol",
      "role": "symbol",
      "title": "white",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonstyle/white"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/whiteOutline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whiteOutline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonStyleV",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/whiteOutline",
      "kind": "symbol",
      "role": "symbol",
      "title": "whiteOutline",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonstyle/whiteoutline"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-Pay-buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButton",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButton",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel"
      ],
      "title": "Apple Pay buttons"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/automatic",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/black",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/white",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle/whiteOutline"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButton/title",
          "value": "PKPaymentButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/paywithapplepaybuttonstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
