{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PayWithApplePayButtonLabel"
      }
    ],
    "modules": [
      {
        "name": "PassKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PayWithApplePayButtonLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PayWithApplePayButtonLabel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PayWithApplePayButtonLabel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButton": {
      "abstract": [
        {
          "text": "An object that displays a button either to trigger payments through Apple Pay or to prompt the user to set up a card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButton"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButton",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButton": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButton"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButton",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButtonLabel",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/addMoney": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMoney"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/addMoney",
      "kind": "symbol",
      "role": "symbol",
      "title": "addMoney",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/addmoney"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/book": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "book"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/book",
      "kind": "symbol",
      "role": "symbol",
      "title": "book",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/book"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/buy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/buy",
      "kind": "symbol",
      "role": "symbol",
      "title": "buy",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/buy"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/checkout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/checkout",
      "kind": "symbol",
      "role": "symbol",
      "title": "checkout",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/checkout"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/continue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`continue`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/continue",
      "kind": "symbol",
      "role": "symbol",
      "title": "continue",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/continue"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/contribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/contribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "contribute",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/contribute"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/donate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "donate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/donate",
      "kind": "symbol",
      "role": "symbol",
      "title": "donate",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/donate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/inStore": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/inStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "inStore",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/instore"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/order": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "order"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/order",
      "kind": "symbol",
      "role": "symbol",
      "title": "order",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/order"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/plain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/plain",
      "kind": "symbol",
      "role": "symbol",
      "title": "plain",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/plain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/reload": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/reload",
      "kind": "symbol",
      "role": "symbol",
      "title": "reload",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/reload"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/rent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/rent",
      "kind": "symbol",
      "role": "symbol",
      "title": "rent",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/rent"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/setUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/setUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "setUp",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/setup"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/subscribe": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/subscribe",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscribe",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/subscribe"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/support": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "support"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/support",
      "kind": "symbol",
      "role": "symbol",
      "title": "support",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/support"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/tip": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/tip",
      "kind": "symbol",
      "role": "symbol",
      "title": "tip",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/tip"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/topUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI012PayWithAppleE11ButtonLabelV",
          "text": "PayWithApplePayButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/topUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "topUp",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonlabel/topup"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButtonStyle",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonstyle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-Pay-buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButton",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButton",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonStyle"
      ],
      "title": "Apple Pay buttons"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/addMoney",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/book",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/buy",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/checkout",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/continue",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/contribute",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/donate",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/inStore",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/order",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/plain",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/reload",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/rent",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/setUp",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/subscribe",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/support",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/tip",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonLabel/topUp"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButton/title",
          "value": "PKPaymentButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/paywithapplepaybuttonlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
