{
  "abstract": [
    {
      "text": "The type of payment pass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKAddPaymentPassStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKAddPaymentPassStyle"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAddPaymentPassStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PKAddPaymentPassStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails": {
      "abstract": [
        {
          "text": "An array of labeled values that describe a card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cardDetails"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKLabeledValue",
          "text": "PKLabeledValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cardDetails"
        }
      ],
      "role": "symbol",
      "title": "cardDetails",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/carddetails"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName": {
      "abstract": [
        {
          "text": "The name of the person as shown on the card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cardholderName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cardholderName"
        }
      ],
      "role": "symbol",
      "title": "cardholderName",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/cardholdername"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme": {
      "abstract": [
        {
          "text": "The encryption scheme to be used in this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKEncryptionScheme",
          "text": "PKEncryptionScheme"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionScheme"
        }
      ],
      "role": "symbol",
      "title": "encryptionScheme",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/encryptionscheme"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription": {
      "abstract": [
        {
          "text": "A short description of the card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDescription"
        }
      ],
      "role": "symbol",
      "title": "localizedDescription",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/localizeddescription"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix": {
      "abstract": [
        {
          "text": "The last four or five digits of the card’s number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccountSuffix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAccountSuffix"
        }
      ],
      "role": "symbol",
      "title": "primaryAccountSuffix",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/primaryaccountsuffix"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIdentifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "productIdentifiers",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/productidentifiers"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style": {
      "abstract": [
        {
          "text": "A value that indicates whether a pass is for access or for payment use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddPaymentPassStyle",
          "text": "PKAddPaymentPassStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/style"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle": {
      "abstract": [
        {
          "text": "The type of payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassStyle"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassStyle",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassstyle"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/access": {
      "abstract": [
        {
          "text": "A pass that authorizes the user to access a location or resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "access"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/access",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassStyleAccess"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassStyle.access",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassstyle/access"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassstyle/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/payment": {
      "abstract": [
        {
          "text": "A pass used by a customer for purchasing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payment"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/payment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassStylePayment"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassStyle.payment",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassstyle/payment"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme": {
      "abstract": [
        {
          "text": "Encryption schemes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKEncryptionScheme"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKEncryptionScheme"
        }
      ],
      "role": "symbol",
      "title": "PKEncryptionScheme",
      "type": "topic",
      "url": "/documentation/passkit/pkencryptionscheme"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue": {
      "abstract": [
        {
          "text": "An object that can represent a detail about a payment card or other item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKLabeledValue"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKLabeledValue"
        }
      ],
      "role": "symbol",
      "title": "PKLabeledValue",
      "type": "topic",
      "url": "/documentation/passkit/pklabeledvalue"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-pass-request-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme",
        "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails",
        "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style"
      ],
      "title": "Payment pass request properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Payment-pass-styles",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/access",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/payment"
      ],
      "title": "Payment pass styles"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKAddPaymentPassStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Payment-pass-styles",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/access",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle/payment"
              ],
              "title": "Payment pass styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-pass-request-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme",
                "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails",
                "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style"
              ],
              "title": "Payment pass request properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKAddPaymentPassStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1productIdentifiers/title",
          "value": "productIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1productIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1localizedDescription/title",
          "value": "localizedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1localizedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1primaryAccountSuffix/title",
          "value": "primaryAccountSuffix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1primaryAccountSuffix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAccountSuffix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle~1payment/title",
          "value": "PKAddPaymentPassStylePayment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle~1payment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStylePayment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle~1access/title",
          "value": "PKAddPaymentPassStyleAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle~1access/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyleAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1encryptionScheme/title",
          "value": "encryptionScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1encryptionScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle/title",
          "value": "PKAddPaymentPassStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/title",
          "value": "PKLabeledValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKEncryptionScheme/title",
          "value": "PKEncryptionScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKEncryptionScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKEncryptionScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKEncryptionScheme/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKEncryptionScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardholderName/title",
          "value": "cardholderName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardholderName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cardholderName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardDetails/title",
          "value": "cardDetails"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardDetails/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cardDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
