{
  "abstract": [
    {
      "text": "Contains the configuration data for a view controller that lets the user add a payment pass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKAddPaymentPassRequestConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKAddPaymentPassRequestConfiguration"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAddPaymentPassRequestConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKAddPaymentPassRequestConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequestConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The encryption scheme, cardholder name, and primary account suffix are required for configuration. The configuration information is used for setup and display only. It should not contain any sensitive information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Adding payment passes requires a special entitlement issued by Apple. Your app must include this entitlement before you can use this class. For more information on requesting this entitlement, see the Card Issuers section at ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/apple-pay/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration": {
      "abstract": [
        {
          "text": "Contains the configuration data for a view controller that lets the user add a payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassRequestConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassRequestConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassRequestConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails": {
      "abstract": [
        {
          "text": "An array of labeled values that describe a card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cardDetails"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKLabeledValue",
          "text": "PKLabeledValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cardDetails"
        }
      ],
      "role": "symbol",
      "title": "cardDetails",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/carddetails"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName": {
      "abstract": [
        {
          "text": "The name of the person as shown on the card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cardholderName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cardholderName"
        }
      ],
      "role": "symbol",
      "title": "cardholderName",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/cardholdername"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme": {
      "abstract": [
        {
          "text": "The encryption scheme to be used in this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKEncryptionScheme",
          "text": "PKEncryptionScheme"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionScheme"
        }
      ],
      "role": "symbol",
      "title": "encryptionScheme",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/encryptionscheme"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/init(encryptionScheme:)": {
      "abstract": [
        {
          "text": "Instantiates a new request configuration with the given encryption scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "encryptionScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKEncryptionScheme",
          "text": "PKEncryptionScheme"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/init(encryptionScheme:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEncryptionScheme:"
        }
      ],
      "role": "symbol",
      "title": "init(encryptionScheme:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/init(encryptionscheme:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription": {
      "abstract": [
        {
          "text": "A short description of the card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDescription"
        }
      ],
      "role": "symbol",
      "title": "localizedDescription",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/localizeddescription"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/paymentNetwork": {
      "abstract": [
        {
          "text": "The payment network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/paymentNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentNetwork"
        }
      ],
      "role": "symbol",
      "title": "paymentNetwork",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/paymentnetwork"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountIdentifier": {
      "abstract": [
        {
          "text": "A primary account identifier, used to filter out pass libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccountIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAccountIdentifier"
        }
      ],
      "role": "symbol",
      "title": "primaryAccountIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/primaryaccountidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix": {
      "abstract": [
        {
          "text": "The last four or five digits of the card’s number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccountSuffix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAccountSuffix"
        }
      ],
      "role": "symbol",
      "title": "primaryAccountSuffix",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/primaryaccountsuffix"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIdentifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "productIdentifiers",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/productidentifiers"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/requiresFelicaSecureElement": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the payment pass requires the Felica Secure Element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresFelicaSecureElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/requiresFelicaSecureElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresFelicaSecureElement"
        }
      ],
      "role": "symbol",
      "title": "requiresFelicaSecureElement",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/requiresfelicasecureelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style": {
      "abstract": [
        {
          "text": "A value that indicates whether a pass is for access or for payment use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddPaymentPassStyle",
          "text": "PKAddPaymentPassStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequestconfiguration/style"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle": {
      "abstract": [
        {
          "text": "The type of payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassStyle"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassStyle",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassstyle"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/init(requestConfiguration:delegate:)": {
      "abstract": [
        {
          "text": "Returns an initialized add payment view controller object, using the provided configuration and delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "requestConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassRequestConfiguration",
          "text": "PKAddPaymentPassRequestConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKAddPaymentPassViewControllerDelegate",
          "text": "PKAddPaymentPassViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/init(requestConfiguration:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRequestConfiguration:delegate:"
        }
      ],
      "role": "symbol",
      "title": "init(requestConfiguration:delegate:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontroller/init(requestconfiguration:delegate:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme": {
      "abstract": [
        {
          "text": "Encryption schemes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKEncryptionScheme"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKEncryptionScheme"
        }
      ],
      "role": "symbol",
      "title": "PKEncryptionScheme",
      "type": "topic",
      "url": "/documentation/passkit/pkencryptionscheme"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue": {
      "abstract": [
        {
          "text": "An object that can represent a detail about a payment card or other item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKLabeledValue"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKLabeledValue"
        }
      ],
      "role": "symbol",
      "title": "PKLabeledValue",
      "type": "topic",
      "url": "/documentation/passkit/pklabeledvalue"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/apple-pay/": {
      "identifier": "https://developer.apple.com/apple-pay/",
      "title": "developer.apple.com/apple-pay/",
      "titleInlineContent": [
        {
          "text": "developer.apple.com/apple-pay/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/apple-pay/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-add-payment-pass-view-controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/init(requestConfiguration:delegate:)"
      ],
      "title": "Creating an add-payment-pass view controller"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-request-configuration",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/init(encryptionScheme:)",
        "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme"
      ],
      "title": "Creating a request configuration"
    },
    {
      "anchor": "Filtering-pass-libraries",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/paymentNetwork",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/requiresFelicaSecureElement"
      ],
      "title": "Filtering pass libraries"
    },
    {
      "anchor": "Payment-pass-request-properties",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme",
        "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails",
        "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle"
      ],
      "title": "Payment pass request properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKAddPaymentPassRequestConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequestConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequestConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-request-configuration",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/init(encryptionScheme:)",
                "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme"
              ],
              "title": "Creating a request configuration"
            },
            {
              "anchor": "Filtering-pass-libraries",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/paymentNetwork",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/requiresFelicaSecureElement"
              ],
              "title": "Filtering pass libraries"
            },
            {
              "anchor": "Payment-pass-request-properties",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardholderName",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/encryptionScheme",
                "doc://com.apple.passkit/documentation/PassKit/PKEncryptionScheme",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/localizedDescription",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/primaryAccountSuffix",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/cardDetails",
                "doc://com.apple.passkit/documentation/PassKit/PKLabeledValue",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/productIdentifiers",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequestConfiguration/style",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassStyle"
              ],
              "title": "Payment pass request properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-add-payment-pass-view-controller",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/init(requestConfiguration:delegate:)"
              ],
              "title": "Creating an add-payment-pass view controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKAddPaymentPassRequestConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardholderName/title",
          "value": "cardholderName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardholderName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cardholderName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1productIdentifiers/title",
          "value": "productIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1productIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardDetails/title",
          "value": "cardDetails"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1cardDetails/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cardDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1requiresFelicaSecureElement/title",
          "value": "requiresFelicaSecureElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1requiresFelicaSecureElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresFelicaSecureElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKEncryptionScheme/title",
          "value": "PKEncryptionScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKEncryptionScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKEncryptionScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKEncryptionScheme/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKEncryptionScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle/title",
          "value": "PKAddPaymentPassStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1paymentNetwork/title",
          "value": "paymentNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1paymentNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1init(encryptionScheme:)/title",
          "value": "initWithEncryptionScheme:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1init(encryptionScheme:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEncryptionScheme:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1primaryAccountIdentifier/title",
          "value": "primaryAccountIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1primaryAccountIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAccountIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController~1init(requestConfiguration:delegate:)/title",
          "value": "initWithRequestConfiguration:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController~1init(requestConfiguration:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRequestConfiguration:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1localizedDescription/title",
          "value": "localizedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1localizedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1primaryAccountSuffix/title",
          "value": "primaryAccountSuffix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1primaryAccountSuffix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAccountSuffix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration/title",
          "value": "PKAddPaymentPassRequestConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequestConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequestConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/title",
          "value": "PKLabeledValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKLabeledValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1encryptionScheme/title",
          "value": "encryptionScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequestConfiguration~1encryptionScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionScheme"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassrequestconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassrequestconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
