{
  "abstract": [
    {
      "text": "Methods that let the system prompt you for an add payment request, and inform you when a request has succeeded or failed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKAddPaymentPassViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKAddPaymentPassViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAddPaymentPassViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKAddPaymentPassViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Delegates for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class must adopt this protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Adding payment passes requires a special entitlement issued by Apple. Your app must include this entitlement before you can use this class. For more information on requesting this entitlement, see the Card Issuers section at ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/apple-pay/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError": {
      "abstract": [
        {
          "text": "Error codes for adding payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest": {
      "abstract": [
        {
          "text": "Contains the card data needed to add a card to Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassRequest"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController": {
      "abstract": [
        {
          "text": "Displays an interface that lets users add cards to Apple Pay from within your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/delegate": {
      "abstract": [
        {
          "text": "The object that acts as the delegate for the add payment view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKAddPaymentPassViewControllerDelegate",
          "text": "PKAddPaymentPassViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontroller/delegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate": {
      "abstract": [
        {
          "text": "Methods that let the system prompt you for an add payment request, and inform you when a request has succeeded or failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
          "text": "PKAddPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishAdding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentPass",
          "text": "PKPaymentPass"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "addPaymentPassViewController(_:didFinishAdding:error:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/addpaymentpassviewcontroller(_:didfinishadding:error:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)": {
      "abstract": [
        {
          "text": "Asks the delegate to create an add payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
          "text": "PKAddPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "generateRequestWithCertificateChain"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "nonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nonceSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassRequest",
          "text": "PKAddPaymentPassRequest"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "https://developer.apple.com/apple-pay/": {
      "identifier": "https://developer.apple.com/apple-pay/",
      "title": "developer.apple.com/apple-pay/",
      "titleInlineContent": [
        {
          "text": "developer.apple.com/apple-pay/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/apple-pay/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-add-payment-view-controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/delegate"
      ],
      "title": "Working with add payment view controllers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Requesting-to-add-payment-cards-to-Apple-Pay",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)"
      ],
      "title": "Requesting to add payment cards to Apple Pay"
    },
    {
      "anchor": "Payment-pass-errors",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError"
      ],
      "title": "Payment pass errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKAddPaymentPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Requesting-to-add-payment-cards-to-Apple-Pay",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)"
              ],
              "title": "Requesting to add payment cards to Apple Pay"
            },
            {
              "anchor": "Payment-pass-errors",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError"
              ],
              "title": "Payment pass errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-add-payment-view-controllers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController/delegate"
              ],
              "title": "Working with add payment view controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKAddPaymentPassViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)/title",
          "value": "addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate/title",
          "value": "PKAddPaymentPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/title",
          "value": "PKAddPaymentPassError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController/title",
          "value": "PKAddPaymentPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:didFinishAdding:error:)/title",
          "value": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:didFinishAdding:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequest/title",
          "value": "PKAddPaymentPassRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
