{
  "abstract": [
    {
      "text": "An error object that PassKit uses when it adds Secure Element passes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC31PKAddSecureElementPassErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKAddSecureElementPassError"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAddSecureElementPassError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKAddSecureElementPassError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543377-errorcode": {
      "abstract": [
        {
          "text": "The code that provides context for the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorCode"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543377-errorcode",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorCode",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543377-errorcode"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543379-erroruserinfo": {
      "abstract": [
        {
          "text": "A dictionary that contains custom information that relates to the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorUserInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543379-erroruserinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorUserInfo",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543379-erroruserinfo"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727659": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the two add secure element pass errors are equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static func "
        },
        {
          "kind": "identifier",
          "text": "== "
        },
        {
          "kind": "text",
          "text": "(PKAddSecureElementPassError, PKAddSecureElementPassError) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727659",
      "kind": "symbol",
      "role": "symbol",
      "title": "==(_:_:)",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727659"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727660-code": {
      "abstract": [
        {
          "text": "The code that provides context for the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": Code"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727660-code",
      "kind": "symbol",
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727660-code"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727661-hash": {
      "abstract": [
        {
          "text": "Hashes the Secure Element pass error object by feeding the item into the given hasher.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": inout Hasher)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727661-hash",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash(into:)",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727661-hash"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727662-hashvalue": {
      "abstract": [
        {
          "text": "The hash value for the Secure Element pass error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727662-hashvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727662-hashvalue"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727663-init": {
      "abstract": [
        {
          "text": "Creates a Secure Element payment pass error object of the specified type with the specified user information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(Code, "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any])"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727663-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:userInfo:)",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727663-init"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727664-userinfo": {
      "abstract": [
        {
          "text": "A dictionary that contains custom information that relates to the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727664-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727664-userinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError": {
      "abstract": [
        {
          "text": "Error codes for adding payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError": {
      "abstract": [
        {
          "text": "An error object that PassKit uses when it adds Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code": {
      "abstract": [
        {
          "text": "Error codes for problems that occur when you add a secure element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotReadyError": {
      "abstract": [
        {
          "text": "The device isn’t ready to add Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotReadyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotReadyError",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceNotReadyError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/devicenotreadyerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotSupportedError": {
      "abstract": [
        {
          "text": "The device doesn’t support adding Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotSupportedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotSupportedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceNotSupportedError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/devicenotsupportederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/errordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/genericError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/genericError",
      "kind": "symbol",
      "role": "symbol",
      "title": "genericError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/genericerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/invalidConfigurationError": {
      "abstract": [
        {
          "text": "An error that occurs when they system attempts to add a Secure Element pass using an invalid configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfigurationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/invalidConfigurationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidConfigurationError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/invalidconfigurationerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/osVersionNotSupportedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osVersionNotSupportedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/osVersionNotSupportedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "osVersionNotSupportedError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/osversionnotsupportederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unavailableError": {
      "abstract": [
        {
          "text": "PassKit is temporarily unable to add Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unavailableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unavailableError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/unavailableerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unknownError": {
      "abstract": [
        {
          "text": "An error that occurs when PassKit cancels the addition of a Secure Element pass due to an unknown failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/unknownerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/userCanceledError": {
      "abstract": [
        {
          "text": "An error that occurs when the user cancels the addition of a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/userCanceledError",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCanceledError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/usercancelederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for errors that occur when adding a secure pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an identity error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for identity operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for identity errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError": {
      "abstract": [
        {
          "text": "Errors that the PassKit framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassKitError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassKitError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code": {
      "abstract": [
        {
          "text": "Errors that the PassKit framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for PassKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassError"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassError",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpasserror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpasserrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionErrorCode",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionerrorcode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonPaymentAuthorizationPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonPaymentAuthorizationPhase"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonPaymentAuthorizationPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonPaymentAuthorizationPhase"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButtonPaymentAuthorizationPhase",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonpaymentauthorizationphase"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonPaymentAuthorizationPhase",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-secure-element-pass-error-object",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727663-init"
      ],
      "title": "Creating a secure element pass error object"
    },
    {
      "anchor": "Identifying-errors",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotReadyError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotSupportedError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/invalidConfigurationError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unavailableError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unknownError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/userCanceledError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code"
      ],
      "title": "Identifying errors"
    },
    {
      "anchor": "Getting-error-information",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727660-code",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543377-errorcode",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727664-userinfo",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3543379-erroruserinfo",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain"
      ],
      "title": "Getting error information"
    },
    {
      "anchor": "Comparing-errors",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727659"
      ],
      "title": "Comparing errors"
    },
    {
      "anchor": "Hashing",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727661-hash",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkaddsecureelementpasserror/3727662-hashvalue"
      ],
      "title": "Hashing"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/errorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/genericError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/osVersionNotSupportedError"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/title",
          "value": "PKPassKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassErrorDomain/title",
          "value": "PKAddSecureElementPassErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/title",
          "value": "PKIdentityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/title",
          "value": "PKAddPaymentPassError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/title",
          "value": "PKAddSecureElementPassErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassErrorDomain/title",
          "value": "PKShareSecureElementPassErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitErrorDomain/title",
          "value": "PKPassKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassError~1Code/title",
          "value": "PKShareSecureElementPassErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityErrorDomain/title",
          "value": "PKIdentityErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/title",
          "value": "PKVehicleConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddsecureelementpasserror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
