{
  "abstract": [
    {
      "text": "The result of an attempt to suppress automatic pass presentation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKAutomaticPassPresentationSuppressionResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKAutomaticPassPresentationSuppressionResult"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAutomaticPassPresentationSuppressionResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PKAutomaticPassPresentationSuppressionResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult": {
      "abstract": [
        {
          "text": "The result of an attempt to suppress automatic pass presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting": {
      "abstract": [
        {
          "text": "The device is already presenting passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyPresenting"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultAlreadyPresenting"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.alreadyPresenting",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/alreadypresenting"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled": {
      "abstract": [
        {
          "text": "The system canceled the suppression before calling the response handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultCancelled"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.cancelled",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/cancelled"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied": {
      "abstract": [
        {
          "text": "The user prevented the suppression, or an internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultDenied"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.denied",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/denied"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported": {
      "abstract": [
        {
          "text": "The device doesn’t support the suppression of automatic pass presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.notSupported",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/notsupported"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success": {
      "abstract": [
        {
          "text": "Suppression of automatic presentation successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultSuccess"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.success",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/success"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)": {
      "abstract": [
        {
          "text": "Reenables the automatic display of the Apple Pay interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endAutomaticPassPresentationSuppression"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRequestToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKSuppressionRequestToken",
          "text": "PKSuppressionRequestToken"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endAutomaticPassPresentationSuppressionWithRequestToken:"
        }
      ],
      "role": "symbol",
      "title": "endAutomaticPassPresentationSuppression(withRequestToken:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/endautomaticpasspresentationsuppression(withrequesttoken:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system suppresses the automatic presentation of Apple Pay passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSuppressingAutomaticPassPresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isSuppressingAutomaticPassPresentation"
        }
      ],
      "role": "symbol",
      "title": "isSuppressingAutomaticPassPresentation()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/issuppressingautomaticpasspresentation()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u": {
      "abstract": [
        {
          "text": "Presents a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentSecureElementPass:"
        }
      ],
      "role": "symbol",
      "title": "present(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/present(_:)-9467u"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)": {
      "abstract": [
        {
          "text": "Prevents the device from automatically displaying the Apple Pay interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAutomaticPassPresentationSuppression"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "responseHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAutomaticPassPresentationSuppressionResult",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKSuppressionRequestToken",
          "text": "PKSuppressionRequestToken"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAutomaticPassPresentationSuppressionWithResponseHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAutomaticPassPresentationSuppression(responseHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/requestautomaticpasspresentationsuppression(responsehandler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken": {
      "abstract": [
        {
          "text": "A token that represents a request to suppress the automatic presentation of payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSuppressionRequestToken"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSuppressionRequestToken"
        }
      ],
      "role": "symbol",
      "title": "PKSuppressionRequestToken",
      "type": "topic",
      "url": "/documentation/passkit/pksuppressionrequesttoken"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-and-suppressing-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)",
        "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken"
      ],
      "title": "Presenting and suppressing passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKAutomaticPassPresentationSuppressionResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-and-suppressing-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)",
                "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken"
              ],
              "title": "Presenting and suppressing passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKAutomaticPassPresentationSuppressionResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuppressionRequestToken/title",
          "value": "PKSuppressionRequestToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuppressionRequestToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuppressionRequestToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuppressionRequestToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuppressionRequestToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1requestAutomaticPassPresentationSuppression(responseHandler:)/title",
          "value": "requestAutomaticPassPresentationSuppressionWithResponseHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1requestAutomaticPassPresentationSuppression(responseHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAutomaticPassPresentationSuppressionWithResponseHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1cancelled/title",
          "value": "PKAutomaticPassPresentationSuppressionResultCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1success/title",
          "value": "PKAutomaticPassPresentationSuppressionResultSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1denied/title",
          "value": "PKAutomaticPassPresentationSuppressionResultDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1present(_:)-9467u/title",
          "value": "presentSecureElementPass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1present(_:)-9467u/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentSecureElementPass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/title",
          "value": "PKAutomaticPassPresentationSuppressionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isSuppressingAutomaticPassPresentation()/title",
          "value": "isSuppressingAutomaticPassPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isSuppressingAutomaticPassPresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isSuppressingAutomaticPassPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1endAutomaticPassPresentationSuppression(withRequestToken:)/title",
          "value": "endAutomaticPassPresentationSuppressionWithRequestToken:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1endAutomaticPassPresentationSuppression(withRequestToken:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "endAutomaticPassPresentationSuppressionWithRequestToken:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1alreadyPresenting/title",
          "value": "PKAutomaticPassPresentationSuppressionResultAlreadyPresenting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1alreadyPresenting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultAlreadyPresenting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1notSupported/title",
          "value": "PKAutomaticPassPresentationSuppressionResultNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkautomaticpasspresentationsuppressionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkautomaticpasspresentationsuppressionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
