{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKBarcodeEventSignatureRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKBarcodeEventSignatureRequest"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKBarcodeEventSignatureRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKBarcodeEventSignatureRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureRequest"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventSignatureRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/amount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/amount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amount"
        }
      ],
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/amount"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/barcodeIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barcodeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/barcodeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barcodeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "barcodeIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/barcodeidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/currencyCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currencyCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/currencyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currencyCode"
        }
      ],
      "role": "symbol",
      "title": "currencyCode",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/currencycode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/deviceAccountIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceAccountIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/deviceAccountIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceAccountIdentifier"
        }
      ],
      "role": "symbol",
      "title": "deviceAccountIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/deviceaccountidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/merchantName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "merchantName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/merchantName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "merchantName"
        }
      ],
      "role": "symbol",
      "title": "merchantName",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/merchantname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/partialSignature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/partialSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "partialSignature"
        }
      ],
      "role": "symbol",
      "title": "partialSignature",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/partialsignature"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/rawMerchantName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawMerchantName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/rawMerchantName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rawMerchantName"
        }
      ],
      "role": "symbol",
      "title": "rawMerchantName",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/rawmerchantname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionDate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transactionDate"
        }
      ],
      "role": "symbol",
      "title": "transactionDate",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/transactiondate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transactionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "transactionIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/transactionidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transactionStatus"
        }
      ],
      "role": "symbol",
      "title": "transactionStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest/transactionstatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureResponse"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureResponse"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventSignatureResponse",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignatureresponse"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKBarcodeEventSignatureRequest",
          "text": "PKBarcodeEventSignatureRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKSignatureRequestCompletionBlock",
          "text": "PKSignatureRequestCompletionBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleSignatureRequest:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(_:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentinformationrequesthandling/handle(_:completion:)-18x2y"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSignatureRequestCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSignatureRequestCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "PKSignatureRequestCompletionBlock",
      "type": "topic",
      "url": "/documentation/passkit/pksignaturerequestcompletionblock"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Signing-the-transaction",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse",
        "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock"
      ],
      "title": "Signing the transaction"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Transaction-Details",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/amount",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/currencyCode",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionDate",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionStatus",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/merchantName",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/rawMerchantName"
      ],
      "title": "Getting Transaction Details"
    },
    {
      "anchor": "Getting-Signing-Information",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/partialSignature",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/barcodeIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/deviceAccountIdentifier"
      ],
      "title": "Getting Signing Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKBarcodeEventSignatureRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Transaction-Details",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/amount",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/currencyCode",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionDate",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/transactionStatus",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/merchantName",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/rawMerchantName"
              ],
              "title": "Getting Transaction Details"
            },
            {
              "anchor": "Getting-Signing-Information",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/partialSignature",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/barcodeIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest/deviceAccountIdentifier"
              ],
              "title": "Getting Signing Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Signing-the-transaction",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse",
                "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock"
              ],
              "title": "Signing the transaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKBarcodeEventSignatureRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1currencyCode/title",
          "value": "currencyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1currencyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currencyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1partialSignature/title",
          "value": "partialSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1partialSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "partialSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureResponse/title",
          "value": "PKBarcodeEventSignatureResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1amount/title",
          "value": "amount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1amount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSignatureRequestCompletionBlock/title",
          "value": "PKSignatureRequestCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSignatureRequestCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSignatureRequestCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSignatureRequestCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSignatureRequestCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1rawMerchantName/title",
          "value": "rawMerchantName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1rawMerchantName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rawMerchantName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1transactionStatus/title",
          "value": "transactionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1transactionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transactionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1merchantName/title",
          "value": "merchantName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1merchantName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "merchantName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1transactionIdentifier/title",
          "value": "transactionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1transactionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transactionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest/title",
          "value": "PKBarcodeEventSignatureRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1transactionDate/title",
          "value": "transactionDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1transactionDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transactionDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1deviceAccountIdentifier/title",
          "value": "deviceAccountIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1deviceAccountIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceAccountIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handle(_:completion:)-18x2y/title",
          "value": "handleSignatureRequest:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handle(_:completion:)-18x2y/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleSignatureRequest:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1barcodeIdentifier/title",
          "value": "barcodeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest~1barcodeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barcodeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkbarcodeeventsignaturerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkbarcodeeventsignaturerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
