{
  "abstract": [
    {
      "text": "An object that represents a request to set up a deferred payment, such as a hotel booking or a pre-order.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKDeferredPaymentRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKDeferredPaymentRequest"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKDeferredPaymentRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKDeferredPaymentRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This request receives a merchant-specific payment token, if the payment network supports merchant-specific payment tokens.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You must set the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/deferredPaymentRequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property on a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object to use the ",
                  "type": "text"
                },
                {
                  "code": "PKDeferredPaymentRequest",
                  "type": "codeVoice"
                },
                {
                  "text": " class and set up a deferred payment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "PKDeferredPaymentRequest",
              "type": "codeVoice"
            },
            {
              "text": " object to provide the user with payment details and a way to manage payment methods for a deferred payment. You can optionally display a billing agreement and set up merchant token life cycle notifications for the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the merchant token life cycle notifications, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MerchantTokenNotificationServices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/MerchantTokenNotificationServices": {
      "abstract": [
        {
          "text": "Retrieve and manage payment life-cycle events for your Apple Pay merchant tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MerchantTokenNotificationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Pay Merchant Token Management API",
      "type": "topic",
      "url": "/documentation/MerchantTokenNotificationServices"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to set up an automatic reload payment, such as a store card top-up or a prepaid account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticReloadPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticreloadpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest": {
      "abstract": [
        {
          "text": "An object that represents a request to set up a deferred payment, such as a hotel booking or a pre-order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDeferredPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDeferredPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKDeferredPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/billingAgreement": {
      "abstract": [
        {
          "text": "The localized billing agreement the framework displays to the user prior to payment authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingAgreement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/billingAgreement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "billingAgreement"
        }
      ],
      "role": "symbol",
      "title": "billingAgreement",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/billingagreement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/deferredBilling": {
      "abstract": [
        {
          "text": "An object that contains details about the deferred payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredBilling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKDeferredPaymentSummaryItem",
          "text": "PKDeferredPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/deferredBilling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deferredBilling"
        }
      ],
      "role": "symbol",
      "title": "deferredBilling",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/deferredbilling"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDate": {
      "abstract": [
        {
          "text": "The date before which you must cancel a deferred payment without incurring any cancellation charges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeCancellationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "freeCancellationDate"
        }
      ],
      "role": "symbol",
      "title": "freeCancellationDate",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/freecancellationdate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDateTimeZone": {
      "abstract": [
        {
          "text": "The time zone at the destination location of the payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeCancellationDateTimeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8TimeZoneV",
          "text": "TimeZone"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDateTimeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "freeCancellationDateTimeZone"
        }
      ],
      "role": "symbol",
      "title": "freeCancellationDateTimeZone",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/freecancellationdatetimezone"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/init(paymentDescription:deferredBilling:managementURL:)": {
      "abstract": [
        {
          "text": "Creates a deferred payment request with the payment description, deferred billing summary, and management URL you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "paymentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deferredBilling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKDeferredPaymentSummaryItem",
          "text": "PKDeferredPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "managementURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/init(paymentDescription:deferredBilling:managementURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPaymentDescription:deferredBilling:managementURL:"
        }
      ],
      "role": "symbol",
      "title": "init(paymentDescription:deferredBilling:managementURL:)",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/init(paymentdescription:deferredbilling:managementurl:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/managementURL": {
      "abstract": [
        {
          "text": "A URL that links to a page on your web site where the user can manage the payment method for the deferred payment, including deleting it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managementURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/managementURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managementURL"
        }
      ],
      "role": "symbol",
      "title": "managementURL",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/managementurl"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/paymentDescription": {
      "abstract": [
        {
          "text": "A description of the deferred payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/paymentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentDescription"
        }
      ],
      "role": "symbol",
      "title": "paymentDescription",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/paymentdescription"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/tokenNotificationURL": {
      "abstract": [
        {
          "text": "A URL to receive life-cycle notifications for the merchant-specific payment token the system issues for the request, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenNotificationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/tokenNotificationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenNotificationURL"
        }
      ],
      "role": "symbol",
      "title": "tokenNotificationURL",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest/tokennotificationurl"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentSummaryItem": {
      "abstract": [
        {
          "text": "An object that defines a summary item for a payment that occurs at a later date, such as a pre-order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDeferredPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDeferredPaymentSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKDeferredPaymentSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentsummaryitem"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest": {
      "abstract": [
        {
          "text": "An object that represents a request for payment, including details about payment-processing capabilities, the payment amount, and shipping information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/deferredPaymentRequest": {
      "abstract": [
        {
          "text": "A request to set up a deferred payment, such as a hotel booking or a pre-order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredPaymentRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKDeferredPaymentRequest",
          "text": "PKDeferredPaymentRequest"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/deferredPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deferredPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "deferredPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/deferredpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext": {
      "abstract": [
        {
          "text": "A class that defines the context for a single payment token in a payment request for multimerchant payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentTokenContext"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentTokenContext"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentTokenContext",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenttokencontext"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to set up a recurring payment, typically a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKRecurringPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext"
      ],
      "title": "Payment requests"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-deferred-payment-request",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/init(paymentDescription:deferredBilling:managementURL:)"
      ],
      "title": "Creating a deferred payment request"
    },
    {
      "anchor": "Describing-a-deferred-payment",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDate",
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/billingAgreement",
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/paymentDescription",
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDateTimeZone"
      ],
      "title": "Describing a deferred payment"
    },
    {
      "anchor": "Setting-payment-summary-items",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/deferredBilling",
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentSummaryItem"
      ],
      "title": "Setting payment summary items"
    },
    {
      "anchor": "Managing-payment-tokens",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/managementURL",
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/tokenNotificationURL"
      ],
      "title": "Managing payment tokens"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKDeferredPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-deferred-payment-request",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/init(paymentDescription:deferredBilling:managementURL:)"
              ],
              "title": "Creating a deferred payment request"
            },
            {
              "anchor": "Describing-a-deferred-payment",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDate",
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/billingAgreement",
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/paymentDescription",
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/freeCancellationDateTimeZone"
              ],
              "title": "Describing a deferred payment"
            },
            {
              "anchor": "Setting-payment-summary-items",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/deferredBilling",
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentSummaryItem"
              ],
              "title": "Setting payment summary items"
            },
            {
              "anchor": "Managing-payment-tokens",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/managementURL",
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest/tokenNotificationURL"
              ],
              "title": "Managing payment tokens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext"
              ],
              "title": "Payment requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKDeferredPaymentRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/title",
          "value": "PKPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1paymentDescription/title",
          "value": "paymentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1paymentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1managementURL/title",
          "value": "managementURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1managementURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "managementURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1freeCancellationDate/title",
          "value": "freeCancellationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1freeCancellationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "freeCancellationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentSummaryItem/title",
          "value": "PKDeferredPaymentSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1init(paymentDescription:deferredBilling:managementURL:)/title",
          "value": "initWithPaymentDescription:deferredBilling:managementURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1init(paymentDescription:deferredBilling:managementURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPaymentDescription:deferredBilling:managementURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1tokenNotificationURL/title",
          "value": "tokenNotificationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1tokenNotificationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tokenNotificationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1billingAgreement/title",
          "value": "billingAgreement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1billingAgreement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "billingAgreement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1deferredPaymentRequest/title",
          "value": "deferredPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1deferredPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentRequest/title",
          "value": "PKAutomaticReloadPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticReloadPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticReloadPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1deferredBilling/title",
          "value": "deferredBilling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1deferredBilling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deferredBilling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest/title",
          "value": "PKRecurringPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentTokenContext/title",
          "value": "PKPaymentTokenContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentTokenContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentTokenContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentTokenContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentTokenContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest/title",
          "value": "PKDeferredPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1freeCancellationDateTimeZone/title",
          "value": "freeCancellationDateTimeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest~1freeCancellationDateTimeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "freeCancellationDateTimeZone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkdeferredpaymentrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkdeferredpaymentrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
