{
  "abstract": [
    {
      "text": "A structure that describes errors that can occur while processing the disbursement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC23PKDisbursementErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKDisbursementError"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKDisbursementError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKDisbursementError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKDisbursementError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156684": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether two values are equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static func "
        },
        {
          "kind": "identifier",
          "text": "== "
        },
        {
          "kind": "text",
          "text": "(PKDisbursementError, PKDisbursementError) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156684",
      "kind": "symbol",
      "role": "symbol",
      "title": "==(_:_:)",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156684"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156685-code": {
      "abstract": [
        {
          "text": "The code that describes the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": Code"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156685-code",
      "kind": "symbol",
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156685-code"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156686-errorcode": {
      "abstract": [
        {
          "text": "An integer value that represents the error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorCode"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156686-errorcode",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorCode",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156686-errorcode"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156688-erroruserinfo": {
      "abstract": [
        {
          "text": "A dictionary that contains additional details about the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorUserInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156688-erroruserinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorUserInfo",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156688-erroruserinfo"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156689-hash": {
      "abstract": [
        {
          "text": "Hashes the essential components of this value by feeding them into the given hasher.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": inout Hasher)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156689-hash",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash(into:)",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156689-hash"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156690-hashvalue": {
      "abstract": [
        {
          "text": "The hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156690-hashvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156690-hashvalue"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156691-init": {
      "abstract": [
        {
          "text": "Creates a new error structure with the error code and user info you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(Code, "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any])"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156691-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:userInfo:)",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156691-init"
    },
    "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156696-userinfo": {
      "abstract": [
        {
          "text": "A dictionary that contains additional details about the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156696-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156696-userinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError": {
      "abstract": [
        {
          "text": "A structure that describes errors that can occur while processing the disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDisbursementError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDisbursementError"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementError",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/Code": {
      "abstract": [
        {
          "text": "Values that describe errors that can occur while processing the disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerror/errordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/recipientContactInvalidError": {
      "abstract": [
        {
          "text": "A value that indicates the recipient’s contact information is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientContactInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23PKDisbursementErrorCodeLeV",
          "text": "PKDisbursementError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKDisbursementErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/recipientContactInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "recipientContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerror/recipientcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/unknownError": {
      "abstract": [
        {
          "text": "A value that indicates an unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23PKDisbursementErrorCodeLeV",
          "text": "PKDisbursementError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKDisbursementErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerror/unknownerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/unsupportedCardError": {
      "abstract": [
        {
          "text": "A value that indicates that the framework doesn’t support the card the individual presented for this disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedCardError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23PKDisbursementErrorCodeLeV",
          "text": "PKDisbursementError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKDisbursementErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/unsupportedCardError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedCardError",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerror/unsupportedcarderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementErrorDomain": {
      "abstract": [
        {
          "text": "The error domain to use for errors with in-app disbursements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDisbursementErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDisbursementErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementErrorKey": {
      "abstract": [
        {
          "text": "Values that describe errors that can occur when processing disbursements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDisbursementErrorKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDisbursementErrorKey"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementErrorKey",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementerrorkey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError": {
      "abstract": [
        {
          "text": "An error type that you create to indicate problems with address or contact information on an Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code": {
      "abstract": [
        {
          "text": "An error code that you provide to indicate problems with address or contact information on an Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for specific errors associated with Apple Pay in-app or web payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey": {
      "abstract": [
        {
          "text": "Additional details about an error on the Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentErrorKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentErrorKey"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentErrorKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterrorkey"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementErrorKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156691-init"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Error-details",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156685-code",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/Code",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156686-errorcode",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156688-erroruserinfo",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156690-hashvalue",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156696-userinfo"
      ],
      "title": "Error details"
    },
    {
      "anchor": "Type-properties",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/recipientContactInvalidError",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/unknownError",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/unsupportedCardError"
      ],
      "title": "Type properties"
    },
    {
      "anchor": "Utility-methods",
      "identifiers": [
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156689-hash",
        "doc://com.apple.documentation/documentation/passkit_apple_pay_and_wallet/pkdisbursementerror/4156684"
      ],
      "title": "Utility methods"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/title",
          "value": "PKPaymentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementErrorDomain/title",
          "value": "PKDisbursementErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementError~1Code/title",
          "value": "PKDisbursementErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey/title",
          "value": "PKPaymentErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementErrorKey/title",
          "value": "PKDisbursementErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementErrorKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorDomain/title",
          "value": "PKPaymentErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkdisbursementerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
