{
  "abstract": [
    {
      "text": "An object that represents a request to disburse funds from a merchant to an individual.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKDisbursementRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKDisbursementRequest"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKDisbursementRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKDisbursementRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this object to create a disbursement (payment) request from a merchant to a user account — for example, a withdrawal from an online account.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest": {
      "abstract": [
        {
          "text": "An object that represents a request to disburse funds from a merchant to an individual.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDisbursementRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDisbursementRequest"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/applicationData": {
      "abstract": [
        {
          "text": "Optional merchant-supplied information about the disbursement request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/applicationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationData"
        }
      ],
      "role": "symbol",
      "title": "applicationData",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/applicationdata"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currency": {
      "abstract": [
        {
          "text": "The currency to use for this disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV8CurrencyV",
          "text": "Currency"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currency",
      "kind": "symbol",
      "role": "symbol",
      "title": "currency",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/currency"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currencyCode": {
      "abstract": [
        {
          "text": "The currency code string for this disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "currencyCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currencyCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "currencyCode",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/currencycode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementCardUnsupportedError()": {
      "abstract": [
        {
          "text": "Creates an error that indicates that the selected payment pass doesn’t support receiving funds through disbursements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disbursementCardUnsupportedError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementCardUnsupportedError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disbursementCardUnsupportedError"
        }
      ],
      "role": "symbol",
      "title": "disbursementCardUnsupportedError()",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/disbursementcardunsupportederror()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementContactInvalidError(withContactField:localizedDescription:)": {
      "abstract": [
        {
          "text": "Creates a recipient contact error with the supplied field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disbursementContactInvalidError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContactField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKContactField",
          "text": "PKContactField"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementContactInvalidError(withContactField:localizedDescription:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disbursementContactInvalidErrorWithContactField:localizedDescription:"
        }
      ],
      "role": "symbol",
      "title": "disbursementContactInvalidError(withContactField:localizedDescription:)",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/disbursementcontactinvaliderror(withcontactfield:localizeddescription:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/init(merchantIdentifier:currency:region:supportedNetworks:merchantCapabilities:summaryItems:)": {
      "abstract": [
        {
          "text": "Creates a disbursement request with the parameters you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "merchantIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "currency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV8CurrencyV",
          "text": "Currency"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "region"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV6RegionV",
          "text": "Region"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedNetworks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "merchantCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "summaryItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentSummaryItem",
          "text": "PKPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/init(merchantIdentifier:currency:region:supportedNetworks:merchantCapabilities:summaryItems:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(merchantIdentifier:currency:region:supportedNetworks:merchantCapabilities:summaryItems:)",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/init(merchantidentifier:currency:region:supportednetworks:merchantcapabilities:summaryitems:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/initWithMerchantIdentifier:currencyCode:regionCode:supportedNetworks:merchantCapabilities:summaryItems:": {
      "abstract": [
        {
          "text": "Creates a new instance of a disbursement request with the merchant identifier, currency and region codes, and other parameters you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithMerchantIdentifier:currencyCode:regionCode:supportedNetworks:merchantCapabilities:summaryItems:"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/initWithMerchantIdentifier:currencyCode:regionCode:supportedNetworks:merchantCapabilities:summaryItems:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithMerchantIdentifier:currencyCode:regionCode:supportedNetworks:merchantCapabilities:summaryItems:"
        }
      ],
      "role": "symbol",
      "title": "initWithMerchantIdentifier:currencyCode:regionCode:supportedNetworks:merchantCapabilities:summaryItems:",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/initwithmerchantidentifier:currencycode:regioncode:supportednetworks:merchantcapabilities:summaryitems:"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantCapabilities": {
      "abstract": [
        {
          "text": "A value that represents the payment-processing capabilities of the merchant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "merchantCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "merchantCapabilities"
        }
      ],
      "role": "symbol",
      "title": "merchantCapabilities",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/merchantcapabilities"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantIdentifier": {
      "abstract": [
        {
          "text": "A string that identifies the merchant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "merchantIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "merchantIdentifier"
        }
      ],
      "role": "symbol",
      "title": "merchantIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/merchantidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/recipientContact": {
      "abstract": [
        {
          "text": "A contact object that describes the recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKContact",
          "text": "PKContact"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/recipientContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipientContact"
        }
      ],
      "role": "symbol",
      "title": "recipientContact",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/recipientcontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/region": {
      "abstract": [
        {
          "text": "The geographic region that describes the location for this disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "region"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV6RegionV",
          "text": "Region"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/region",
      "kind": "symbol",
      "role": "symbol",
      "title": "region",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/region"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/regionCode": {
      "abstract": [
        {
          "text": "The merchant’s country code string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "regionCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/regionCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionCode",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/regioncode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/requiredRecipientContactFields": {
      "abstract": [
        {
          "text": "An array that indicates which of the recipient’s contact details the merchant requires in order to process a disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiredRecipientContactFields"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKContactField",
          "text": "PKContactField"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/requiredRecipientContactFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiredRecipientContactFields"
        }
      ],
      "role": "symbol",
      "title": "requiredRecipientContactFields",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/requiredrecipientcontactfields"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/summaryItems": {
      "abstract": [
        {
          "text": "An array of payment summary item objects that the framework presents to people.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summaryItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentSummaryItem",
          "text": "PKPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/summaryItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "summaryItems"
        }
      ],
      "role": "symbol",
      "title": "summaryItems",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/summaryitems"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedNetworks": {
      "abstract": [
        {
          "text": "An array of payment networks the merchant supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedNetworks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedNetworks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedNetworks"
        }
      ],
      "role": "symbol",
      "title": "supportedNetworks",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/supportednetworks"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-1cl0f": {
      "abstract": [
        {
          "text": "An array of regions that describe the locations to support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedRegions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV6RegionV",
          "text": "Region"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-1cl0f",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedRegions",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/supportedregions-1cl0f"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-j9ug": {
      "abstract": [
        {
          "text": "An array of two-letter region codes that describes the regions to support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "supportedRegions"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-j9ug",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedRegions",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/supportedregions-j9ug"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementSummaryItem": {
      "abstract": [
        {
          "text": "A summary item that represents a disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDisbursementSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDisbursementSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementsummaryitem"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKInstantFundsOutFeeSummaryItem": {
      "abstract": [
        {
          "text": "A summary item that represents a fee for an instant funds out transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInstantFundsOutFeeSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKInstantFundsOutFeeSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInstantFundsOutFeeSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKInstantFundsOutFeeSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkinstantfundsoutfeesummaryitem"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem": {
      "abstract": [
        {
          "text": "An object that defines a summary item in a payment request, taxes, discounts, shipping, a grand total, and the like.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentsummaryitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/init(merchantIdentifier:currency:region:supportedNetworks:merchantCapabilities:summaryItems:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Setting-currency-and-region-information",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currency",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/region",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-1cl0f"
      ],
      "title": "Setting currency and region information"
    },
    {
      "anchor": "Setting-the-summary-items",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/summaryItems",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementSummaryItem",
        "doc://com.apple.passkit/documentation/PassKit/PKInstantFundsOutFeeSummaryItem"
      ],
      "title": "Setting the summary items"
    },
    {
      "anchor": "Setting-custom-application-data",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/applicationData"
      ],
      "title": "Setting custom application data"
    },
    {
      "anchor": "Setting-the-merchant-information",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantCapabilities",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedNetworks"
      ],
      "title": "Setting the merchant information"
    },
    {
      "anchor": "Requesting-recipient-contact-fields",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/recipientContact",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/requiredRecipientContactFields"
      ],
      "title": "Requesting recipient contact fields"
    },
    {
      "anchor": "Handling-errors",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementCardUnsupportedError()",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementContactInvalidError(withContactField:localizedDescription:)"
      ],
      "title": "Handling errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKDisbursementRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/initWithMerchantIdentifier:currencyCode:regionCode:supportedNetworks:merchantCapabilities:summaryItems:"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Setting-currency-and-region-information",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currencyCode",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/regionCode",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-j9ug"
              ],
              "title": "Setting currency and region information"
            },
            {
              "anchor": "Setting-the-summary-items",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/summaryItems",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementSummaryItem",
                "doc://com.apple.passkit/documentation/PassKit/PKInstantFundsOutFeeSummaryItem"
              ],
              "title": "Setting the summary items"
            },
            {
              "anchor": "Setting-custom-application-data",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/applicationData"
              ],
              "title": "Setting custom application data"
            },
            {
              "anchor": "Setting-the-merchant-information",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/merchantCapabilities",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedNetworks"
              ],
              "title": "Setting the merchant information"
            },
            {
              "anchor": "Requesting-recipient-contact-fields",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/recipientContact",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/requiredRecipientContactFields"
              ],
              "title": "Requesting recipient contact fields"
            },
            {
              "anchor": "Handling-errors",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementCardUnsupportedError()",
                "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/disbursementContactInvalidError(withContactField:localizedDescription:)"
              ],
              "title": "Handling errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKDisbursementRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1merchantIdentifier/title",
          "value": "merchantIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1merchantIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "merchantIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1applicationData/title",
          "value": "applicationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1applicationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1summaryItems/title",
          "value": "summaryItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1summaryItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "summaryItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1merchantCapabilities/title",
          "value": "merchantCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1merchantCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "merchantCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKInstantFundsOutFeeSummaryItem/title",
          "value": "PKInstantFundsOutFeeSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKInstantFundsOutFeeSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInstantFundsOutFeeSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKInstantFundsOutFeeSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInstantFundsOutFeeSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentSummaryItem/title",
          "value": "PKPaymentSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1disbursementCardUnsupportedError()/title",
          "value": "disbursementCardUnsupportedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1disbursementCardUnsupportedError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "disbursementCardUnsupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest/title",
          "value": "PKDisbursementRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1recipientContact/title",
          "value": "recipientContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1recipientContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipientContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1disbursementContactInvalidError(withContactField:localizedDescription:)/title",
          "value": "disbursementContactInvalidErrorWithContactField:localizedDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1disbursementContactInvalidError(withContactField:localizedDescription:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "disbursementContactInvalidErrorWithContactField:localizedDescription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1supportedNetworks/title",
          "value": "supportedNetworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1supportedNetworks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedNetworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1requiredRecipientContactFields/title",
          "value": "requiredRecipientContactFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest~1requiredRecipientContactFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiredRecipientContactFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementSummaryItem/title",
          "value": "PKDisbursementSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementSummaryItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkdisbursementrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkdisbursementrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
