{
  "abstract": [
    {
      "text": "An object that represents the elements an app requests from identity documents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKIdentityElement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKIdentityElement"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKIdentityElement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKIdentityElement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If an app requests an element from a document type that doesn’t support it, the system ignores the element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityAuthorizationController": {
      "abstract": [
        {
          "text": "An object that presents a sheet that prompts the user to allow a request for identity information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityAuthorizationController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityAuthorizationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityAuthorizationController"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityAuthorizationController",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityauthorizationcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityButton": {
      "abstract": [
        {
          "text": "An object that displays a button to trigger the identity verification flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityButton"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityButton",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitybutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocument": {
      "abstract": [
        {
          "text": "An object that represents the response to a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityDocument"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityDocument"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityDocument",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydocument"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement": {
      "abstract": [
        {
          "text": "An object that represents the elements an app requests from identity documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityElement"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityElement",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address": {
      "abstract": [
        {
          "text": "An element that represents the user’s home address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressElement"
        }
      ],
      "role": "symbol",
      "title": "address",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/address"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age": {
      "abstract": [
        {
          "text": "An element that represents the user’s age, in years.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "age"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ageElement"
        }
      ],
      "role": "symbol",
      "title": "age",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/age"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age(atLeast:)": {
      "abstract": [
        {
          "text": "Returns an element that represents the user’s age is at least the age you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "age"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atLeast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age(atLeast:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ageThresholdElementWithAge:"
        }
      ],
      "role": "symbol",
      "title": "age(atLeast:)",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/age(atleast:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth": {
      "abstract": [
        {
          "text": "An element that represents the user’s date of birth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateOfBirth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateOfBirthElement"
        }
      ],
      "role": "symbol",
      "title": "dateOfBirth",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/dateofbirth"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentDHSComplianceStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDHSComplianceStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentDHSComplianceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDHSComplianceStatusElement"
        }
      ],
      "role": "symbol",
      "title": "documentDHSComplianceStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentdhscompliancestatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate": {
      "abstract": [
        {
          "text": "An element that represents the expiration date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentExpirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentExpirationDateElement"
        }
      ],
      "role": "symbol",
      "title": "documentExpirationDate",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentexpirationdate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate": {
      "abstract": [
        {
          "text": "An element that represents the issue date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentIssueDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentIssueDateElement"
        }
      ],
      "role": "symbol",
      "title": "documentIssueDate",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentissuedate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber": {
      "abstract": [
        {
          "text": "An element that represents the document’s number, as the issuing authority defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentNumberElement"
        }
      ],
      "role": "symbol",
      "title": "documentNumber",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentnumber"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges": {
      "abstract": [
        {
          "text": "An element that represents the user’s driving privileges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drivingPrivileges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drivingPrivilegesElement"
        }
      ],
      "role": "symbol",
      "title": "drivingPrivileges",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/drivingprivileges"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName": {
      "abstract": [
        {
          "text": "An element that represents the user’s family name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "familyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "familyNameElement"
        }
      ],
      "role": "symbol",
      "title": "familyName",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/familyname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName": {
      "abstract": [
        {
          "text": "An element that represents the user’s given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "givenName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "givenNameElement"
        }
      ],
      "role": "symbol",
      "title": "givenName",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/givenname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority": {
      "abstract": [
        {
          "text": "An element that represents the user’s issuing authority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "issuingAuthority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "issuingAuthorityElement"
        }
      ],
      "role": "symbol",
      "title": "issuingAuthority",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/issuingauthority"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait": {
      "abstract": [
        {
          "text": "An element that represents the user’s photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitElement"
        }
      ],
      "role": "symbol",
      "title": "portrait",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/portrait"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/sex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/sex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sexElement"
        }
      ],
      "role": "symbol",
      "title": "sex",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/sex"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityRequest": {
      "abstract": [
        {
          "text": "An object that represents a request for identity information from a Wallet pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityRequest"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButton": {
      "abstract": [
        {
          "text": "A view that displays a button for identity verification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VerifyIdentityWithWalletButton"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VerifyIdentityWithWalletButton"
        }
      ],
      "role": "symbol",
      "title": "VerifyIdentityWithWalletButton",
      "type": "topic",
      "url": "/documentation/passkit/verifyidentitywithwalletbutton"
    },
    "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButtonLabel": {
      "abstract": [
        {
          "text": "A type that represents the label you use with a verify identity button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VerifyIdentityWithWalletButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButtonLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VerifyIdentityWithWalletButtonLabel"
        }
      ],
      "role": "symbol",
      "title": "VerifyIdentityWithWalletButtonLabel",
      "type": "topic",
      "url": "/documentation/passkit/verifyidentitywithwalletbuttonlabel"
    },
    "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButtonStyle": {
      "abstract": [
        {
          "text": "A type that represents the style you use with a verify identity button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VerifyIdentityWithWalletButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VerifyIdentityWithWalletButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "VerifyIdentityWithWalletButtonStyle",
      "type": "topic",
      "url": "/documentation/passkit/verifyidentitywithwalletbuttonstyle"
    },
    "doc://com.apple.passkit/documentation/PassKit/requesting-identity-data-from-a-wallet-pass": {
      "abstract": [
        {
          "text": "Initiate a request for identity information by prompting a user for permission and decrypting a response payload.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/requesting-identity-data-from-a-wallet-pass",
      "kind": "article",
      "role": "article",
      "title": "Requesting identity data from a Wallet pass",
      "type": "topic",
      "url": "/documentation/passkit/requesting-identity-data-from-a-wallet-pass"
    },
    "doc://com.apple.passkit/documentation/PassKit/verifying-wallet-identity-requests": {
      "abstract": [
        {
          "text": "Decrypt and verify an in-app presentment request on your server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/verifying-wallet-identity-requests",
      "kind": "article",
      "role": "article",
      "title": "Verifying Wallet identity requests",
      "type": "topic",
      "url": "/documentation/passkit/verifying-wallet-identity-requests"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identity-sheet-interactions-and-authorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/requesting-identity-data-from-a-wallet-pass",
        "doc://com.apple.passkit/documentation/PassKit/verifying-wallet-identity-requests",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityAuthorizationController",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocument",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityButton",
        "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButton",
        "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButtonLabel",
        "doc://com.apple.passkit/documentation/PassKit/VerifyIdentityWithWalletButtonStyle"
      ],
      "title": "Identity sheet interactions and authorization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-identity-elements",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait"
      ],
      "title": "Getting identity elements"
    },
    {
      "anchor": "Getting-an-age-identity-element",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age(atLeast:)"
      ],
      "title": "Getting an age identity element"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentDHSComplianceStatus",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/sex"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIdentityElement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-identity-elements",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait"
              ],
              "title": "Getting identity elements"
            },
            {
              "anchor": "Getting-an-age-identity-element",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/age(atLeast:)"
              ],
              "title": "Getting an age identity element"
            },
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentDHSComplianceStatus",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/sex"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identity-sheet-interactions-and-authorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/requesting-identity-data-from-a-wallet-pass",
                "doc://com.apple.passkit/documentation/PassKit/verifying-wallet-identity-requests",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityAuthorizationController",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocument",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityButton"
              ],
              "title": "Identity sheet interactions and authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKIdentityElement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1sex/title",
          "value": "sexElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1sex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sexElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1dateOfBirth/title",
          "value": "dateOfBirthElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1dateOfBirth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateOfBirthElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1portrait/title",
          "value": "portraitElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1portrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "portraitElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityAuthorizationController/title",
          "value": "PKIdentityAuthorizationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityAuthorizationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityAuthorizationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityAuthorizationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityAuthorizationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentIssueDate/title",
          "value": "documentIssueDateElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentIssueDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentIssueDateElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityButton/title",
          "value": "PKIdentityButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1age(atLeast:)/title",
          "value": "ageThresholdElementWithAge:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1age(atLeast:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "ageThresholdElementWithAge:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1familyName/title",
          "value": "familyNameElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1familyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "familyNameElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentDHSComplianceStatus/title",
          "value": "documentDHSComplianceStatusElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentDHSComplianceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentDHSComplianceStatusElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityRequest/title",
          "value": "PKIdentityRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/title",
          "value": "PKIdentityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentExpirationDate/title",
          "value": "documentExpirationDateElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentExpirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentExpirationDateElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1givenName/title",
          "value": "givenNameElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1givenName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "givenNameElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1age/title",
          "value": "ageElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1age/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ageElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentNumber/title",
          "value": "documentNumberElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentNumberElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1drivingPrivileges/title",
          "value": "drivingPrivilegesElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1drivingPrivileges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drivingPrivilegesElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1issuingAuthority/title",
          "value": "issuingAuthorityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1issuingAuthority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "issuingAuthorityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocument/title",
          "value": "PKIdentityDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1address/title",
          "value": "addressElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkidentityelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkidentityelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
