{
  "abstract": [
    {
      "text": "A type that describes the structure and behavior of an identity document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKIdentityDocumentDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKIdentityDocumentDescriptor"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKIdentityDocumentDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKIdentityDocumentDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentDescriptor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A descriptor object describes the type of document that your app can request or check whether a document is available to request. For example, you use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to request information from a user’s driver’s license (or equivalent document).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Different document types behave differently, requiring different properties or response formats. Don’t define your own implementation of this protocol or subclass an existing implementation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor": {
      "abstract": [
        {
          "text": "A type that describes the structure and behavior of an identity document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityDocumentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityDocumentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityDocumentDescriptor",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydocumentdescriptor"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)": {
      "abstract": [
        {
          "text": "Adds a list of identity element and defines the way an app, or it’s server, stores the elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addElements"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "intentToStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityIntentToStore",
          "text": "PKIdentityIntentToStore"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addElements:withIntentToStore:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "addElements(_:intentToStore:)",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydocumentdescriptor/addelements(_:intenttostore:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/elements": {
      "abstract": [
        {
          "text": "A list of identity elements to request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elements"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/elements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elements"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "elements",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydocumentdescriptor/elements"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/intentToStore(element:)": {
      "abstract": [
        {
          "text": "Gets the intent to store for an identity element you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intentToStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityIntentToStore",
          "text": "PKIdentityIntentToStore"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/intentToStore(element:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intentToStoreForElement:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "intentToStore(element:)",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydocumentdescriptor/intenttostore(element:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor": {
      "abstract": [
        {
          "text": "An object for requesting information from a user’s driver’s license or equivalent document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityDriversLicenseDescriptor"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityDriversLicenseDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityDriversLicenseDescriptor",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitydriverslicensedescriptor"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement": {
      "abstract": [
        {
          "text": "An object that represents the elements an app requests from identity documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityElement"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityElement",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore": {
      "abstract": [
        {
          "text": "An object that represents your intention to store an identity element or values derived from an identity element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityIntentToStore"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityIntentToStore"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityIntentToStore",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityintenttostore"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor": {
      "abstract": [
        {
          "text": "An object for requesting information from a user’s national ID card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityNationalIDCardDescriptor"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityNationalIDCardDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityNationalIDCardDescriptor",
      "type": "topic",
      "url": "/documentation/passkit/pkidentitynationalidcarddescriptor"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-a-document",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"
      ],
      "title": "Describing a document"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-elements",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/elements",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement"
      ],
      "title": "Inspecting elements"
    },
    {
      "anchor": "Adding-an-identity-element",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"
      ],
      "title": "Adding an identity element"
    },
    {
      "anchor": "Getting-an-elements-intent",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/intentToStore(element:)"
      ],
      "title": "Getting an elements intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIdentityDocumentDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-elements",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/elements",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement"
              ],
              "title": "Inspecting elements"
            },
            {
              "anchor": "Adding-an-identity-element",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"
              ],
              "title": "Adding an identity element"
            },
            {
              "anchor": "Getting-an-elements-intent",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/intentToStore(element:)"
              ],
              "title": "Getting an elements intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-a-document",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"
              ],
              "title": "Describing a document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKIdentityDocumentDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1elements/title",
          "value": "elements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1elements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1addElements(_:intentToStore:)/title",
          "value": "addElements:withIntentToStore:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1addElements(_:intentToStore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addElements:withIntentToStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/title",
          "value": "PKIdentityNationalIDCardDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityNationalIDCardDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityNationalIDCardDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/title",
          "value": "PKIdentityIntentToStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityIntentToStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityIntentToStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/title",
          "value": "PKIdentityDocumentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDocumentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1intentToStore(element:)/title",
          "value": "intentToStoreForElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1intentToStore(element:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "intentToStoreForElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/title",
          "value": "PKIdentityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDriversLicenseDescriptor/title",
          "value": "PKIdentityDriversLicenseDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDriversLicenseDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDriversLicenseDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDriversLicenseDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityDriversLicenseDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkidentitydocumentdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkidentitydocumentdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
