{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/passkit/pkidentityintenttostore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/passkit/pkidentityintenttostore"]}],"sections":[],"abstract":[{"type":"text","text":"An object that represents your intention to store an identity element or values derived from an identity element."}],"seeAlsoSections":[{"title":"Describing a document","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor","doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor"],"generated":true,"anchor":"Describing-a-document"}],"metadata":{"role":"symbol","title":"PKIdentityIntentToStore","modules":[{"name":"PassKit (Apple Pay and Wallet)"}],"symbolKind":"class","externalID":"c:objc(cs)PKIdentityIntentToStore","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PKIdentityIntentToStore","kind":"identifier"}],"platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"16.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"16.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"16.0"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}],"navigatorTitle":[{"text":"PKIdentityIntentToStore","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PKIdentityIntentToStore","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.passkit/documentation/PassKit"]]},"topicSections":[{"title":"Creating a default intent","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore(days:)"],"anchor":"Creating-a-default-intent"},{"title":"Getting default intents","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore","doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/willNotStore"],"anchor":"Getting-default-intents"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"},"references":{"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor":{"type":"topic","title":"PKIdentityDocumentDescriptor","navigatorTitle":[{"kind":"identifier","text":"PKIdentityDocumentDescriptor"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A type that describes the structure and behavior of an identity document."}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor","url":"/documentation/passkit/pkidentitydocumentdescriptor","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIdentityDocumentDescriptor"}]},"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore":{"kind":"symbol","title":"mayStore","abstract":[{"type":"text","text":"An object that indicates your app may store a data element for an indefinite length of time."}],"navigatorTitle":[{"text":"mayStoreIntent","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mayStore"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKIdentityIntentToStore","text":"PKIdentityIntentToStore","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/passkit/pkidentityintenttostore/maystore","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"type":"topic","title":"CVarArg","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","role":"symbol","url":"/documentation/Swift/CVarArg","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore":{"type":"topic","title":"PKIdentityIntentToStore","navigatorTitle":[{"kind":"identifier","text":"PKIdentityIntentToStore"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An object that represents your intention to store an identity element or values derived from an identity element."}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore","url":"/documentation/passkit/pkidentityintenttostore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIdentityIntentToStore"}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"role":"symbol","type":"topic","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"type":"text","text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects."}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","url":"/documentation/objectivec/nsobject","type":"topic","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"title":"NSObject"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore(days:)":{"type":"topic","title":"mayStore(days:)","kind":"symbol","url":"/documentation/passkit/pkidentityintenttostore/maystore(days:)","navigatorTitle":[{"text":"mayStoreIntentForDays:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mayStore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"days","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"An object that indicates your app may store a data element for the length of time you specify."}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore(days:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","role":"symbol","url":"/documentation/Swift/Equatable","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","title":"Equatable"},"doc://com.apple.passkit/documentation/PassKit":{"type":"topic","title":"PassKit (Apple Pay and Wallet)","abstract":[{"text":"Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.","type":"text"}],"identifier":"doc://com.apple.passkit/documentation/PassKit","url":"/documentation/passkit","kind":"symbol","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"title":"NSObjectProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/willNotStore":{"kind":"symbol","title":"willNotStore","abstract":[{"type":"text","text":"An object that indicates your app won’t store a data element any longer than necessary to complete a request."}],"navigatorTitle":[{"text":"willNotStoreIntent","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"willNotStore"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKIdentityIntentToStore","text":"PKIdentityIntentToStore","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/passkit/pkidentityintenttostore/willnotstore","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/willNotStore"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"title":"NSCopying","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}],"url":"/documentation/foundation/nscopying","kind":"symbol","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","title":"Hashable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Equatable","preciseIdentifier":"s:SQ"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"url":"/documentation/Swift/CustomStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"type":"topic","title":"CustomStringConvertible","abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor":{"kind":"symbol","title":"PKIdentityDriversLicenseDescriptor","abstract":[{"type":"text","text":"An object for requesting information from a user’s driver’s license or equivalent document."}],"navigatorTitle":[{"kind":"identifier","text":"PKIdentityDriversLicenseDescriptor"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIdentityDriversLicenseDescriptor"}],"role":"symbol","url":"/documentation/passkit/pkidentitydriverslicensedescriptor","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"introducedAt":"16.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"16.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"16.0","name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Class","op":"replace"},{"path":"/metadata/title","value":"PKIdentityIntentToStore","op":"replace"},{"path":"/metadata/symbolKind","value":"class","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"PKIdentityIntentToStore"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"PKIdentityIntentToStore"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.passkit/documentation/PassKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Creating a default intent","anchor":"Creating-a-default-intent","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore(days:)"]},{"title":"Getting default intents","anchor":"Getting-default-intents","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/mayStore","doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore/willNotStore"]}],"op":"replace"},{"path":"/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"],"type":"conformsTo"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"anchor":"Describing-a-document","title":"Describing a document","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityDriversLicenseDescriptor","doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PKIdentityIntentToStore","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace"},{"value":"PKIdentityDocumentDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/title"},{"value":[{"kind":"identifier","text":"PKIdentityDocumentDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/fragments"},{"value":[{"text":"PKIdentityDocumentDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/navigatorTitle"},{"value":"mayStoreIntent","op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore~1mayStore/title"},{"value":[{"text":"mayStoreIntent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore~1mayStore/fragments"},{"value":"PKIdentityIntentToStore","op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/title"},{"value":[{"kind":"identifier","text":"PKIdentityIntentToStore"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/fragments"},{"value":[{"text":"PKIdentityIntentToStore","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/navigatorTitle"},{"value":"mayStoreIntentForDays:","op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore~1mayStore(days:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mayStoreIntentForDays:"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore~1mayStore(days:)/fragments"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"willNotStoreIntent","op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore~1willNotStore/title"},{"value":[{"text":"willNotStoreIntent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore~1willNotStore/fragments"},{"value":"PKIdentityDriversLicenseDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDriversLicenseDescriptor/title"},{"value":[{"text":"PKIdentityDriversLicenseDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDriversLicenseDescriptor/fragments"},{"value":[{"text":"PKIdentityDriversLicenseDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDriversLicenseDescriptor/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}