{
  "abstract": [
    {
      "text": "A protocol for a UI app extension to authorize a user to add a payment card to Wallet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKIssuerProvisioningExtensionAuthorizationProviding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKIssuerProvisioningExtensionAuthorizationProviding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The principal class of your app’s authorization user interface extension target must conform to the ",
              "type": "text"
            },
            {
              "code": "PKIssuerProvisioningExtensionAuthorizationProviding",
              "type": "codeVoice"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before you can add a payment card provisioning UI extension you need an entitlement from Apple. For more information on requesting an entitlement, contact apple-pay-inquiries@apple.com.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding": {
      "abstract": [
        {
          "text": "A protocol for a UI app extension to authorize a user to add a payment card to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionAuthorizationProviding",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationproviding"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding/completionHandler": {
      "abstract": [
        {
          "text": "A completion handler the system calls to find the result of authorizing the addition of the payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKIssuerProvisioningExtensionAuthorizationResult",
          "text": "PKIssuerProvisioningExtensionAuthorizationResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding/completionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "completionHandler",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationproviding/completionhandler"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult": {
      "abstract": [
        {
          "text": "A value that indicates the result of authorizing the addition of a payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationResult"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionAuthorizationResult",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler": {
      "abstract": [
        {
          "text": "An abstract superclass for an app extension to add a payment card to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionHandler"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionHandler"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionHandler",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionhandler"
    },
    "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions": {
      "abstract": [
        {
          "text": "Support adding an issued card to Apple Pay from directly within Apple Wallet",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "using Wallet Extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing Wallet Extensions",
      "type": "topic",
      "url": "/documentation/passkit/implementing-wallet-extensions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extend-Wallet-to-add-issuer-cards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler"
      ],
      "title": "Extend Wallet to add issuer cards"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-the-result-of-authorization",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding/completionHandler",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult"
      ],
      "title": "Providing the result of authorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationProviding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-the-result-of-authorization",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding/completionHandler",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult"
              ],
              "title": "Providing the result of authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extend-Wallet-to-add-issuer-cards",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler"
              ],
              "title": "Extend Wallet to add issuer cards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler/title",
          "value": "PKIssuerProvisioningExtensionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding~1completionHandler/title",
          "value": "completionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding~1completionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkissuerprovisioningextensionauthorizationproviding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkissuerprovisioningextensionauthorizationproviding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
