{
  "abstract": [
    {
      "text": "An abstract superclass for an app extension to add a payment card to Wallet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKIssuerProvisioningExtensionHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKIssuerProvisioningExtensionHandler"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKIssuerProvisioningExtensionHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKIssuerProvisioningExtensionHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The principal class of your app’s extension target must be a subclass of ",
              "type": "text"
            },
            {
              "code": "PKIssuerProvisioningExtensionHandler",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app must be installed and the user open the app at least once for the system to call the extension handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before you can add a payment card provisioning extension you need an entitlement from Apple. For more information on requesting an entitlement, contact apple-pay-inquiries@apple.com.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding": {
      "abstract": [
        {
          "text": "A protocol for a UI app extension to authorize a user to add a payment card to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionAuthorizationProviding",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationproviding"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler": {
      "abstract": [
        {
          "text": "An abstract superclass for an app extension to add a payment card to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionHandler"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionHandler"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionHandler",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionhandler"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates an object with the data the system needs to add a card to Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generateAddPaymentPassRequestForPassEntryWithIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassRequestConfiguration",
          "text": "PKAddPaymentPassRequestConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "certificateChain"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "nonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nonceSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassRequest",
          "text": "PKAddPaymentPassRequest"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "generateAddPaymentPassRequestForPassEntryWithIdentifier:configuration:certificateChain:nonce:nonceSignature:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionhandler/generateaddpaymentpassrequestforpassentrywithidentifier(_:configuration:certificatechain:nonce:noncesignature:completionhandler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/passEntries(completion:)": {
      "abstract": [
        {
          "text": "Reports the list of passes available to add to an iPhone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passEntries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIssuerProvisioningExtensionPassEntry",
          "text": "PKIssuerProvisioningExtensionPassEntry"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/passEntries(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passEntriesWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "passEntries(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionhandler/passentries(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/remotePassEntries(completion:)": {
      "abstract": [
        {
          "text": "Reports the list of passes available to add to an Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remotePassEntries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIssuerProvisioningExtensionPassEntry",
          "text": "PKIssuerProvisioningExtensionPassEntry"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/remotePassEntries(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remotePassEntriesWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "remotePassEntries(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionhandler/remotepassentries(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/status(completion:)": {
      "abstract": [
        {
          "text": "Reports the status of your Wallet extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIssuerProvisioningExtensionStatus",
          "text": "PKIssuerProvisioningExtensionStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/status(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "status(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionhandler/status(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPassEntry": {
      "abstract": [
        {
          "text": "An object that represents an item available to add to as a Wallet pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionPassEntry"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPassEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionPassEntry"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionPassEntry",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionpassentry"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPaymentPassEntry": {
      "abstract": [
        {
          "text": "An object that represents a payment card available to add as a payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionPaymentPassEntry"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPaymentPassEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionPaymentPassEntry"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionPaymentPassEntry",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionpaymentpassentry"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionStatus": {
      "abstract": [
        {
          "text": "An object that indicates whether there are any payment cards available to add as Wallet passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionStatus"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionStatus"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionstatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions": {
      "abstract": [
        {
          "text": "Support adding an issued card to Apple Pay from directly within Apple Wallet",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "using Wallet Extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing Wallet Extensions",
      "type": "topic",
      "url": "/documentation/passkit/implementing-wallet-extensions"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extend-Wallet-to-add-issuer-cards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding"
      ],
      "title": "Extend Wallet to add issuer cards"
    }
  ],
  "topicSections": [
    {
      "anchor": "Returning-extension-status",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/status(completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionStatus"
      ],
      "title": "Returning extension status"
    },
    {
      "anchor": "Returning-available-passes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/passEntries(completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/remotePassEntries(completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPassEntry",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPaymentPassEntry"
      ],
      "title": "Returning available passes"
    },
    {
      "anchor": "Returning-information-for-adding-a-pass",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)"
      ],
      "title": "Returning information for adding a pass"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIssuerProvisioningExtensionHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Returning-extension-status",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/status(completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionStatus"
              ],
              "title": "Returning extension status"
            },
            {
              "anchor": "Returning-available-passes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/passEntries(completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/remotePassEntries(completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPassEntry",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionPaymentPassEntry"
              ],
              "title": "Returning available passes"
            },
            {
              "anchor": "Returning-information-for-adding-a-pass",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionHandler/generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)"
              ],
              "title": "Returning information for adding a pass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extend-Wallet-to-add-issuer-cards",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/implementing-wallet-extensions",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationProviding"
              ],
              "title": "Extend Wallet to add issuer cards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKIssuerProvisioningExtensionHandler"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionStatus/title",
          "value": "PKIssuerProvisioningExtensionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1remotePassEntries(completion:)/title",
          "value": "remotePassEntriesWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1remotePassEntries(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "remotePassEntriesWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)/title",
          "value": "generateAddPaymentPassRequestForPassEntryWithIdentifier:configuration:certificateChain:nonce:nonceSignature:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1generateAddPaymentPassRequestForPassEntryWithIdentifier(_:configuration:certificateChain:nonce:nonceSignature:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "generateAddPaymentPassRequestForPassEntryWithIdentifier:configuration:certificateChain:nonce:nonceSignature:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1status(completion:)/title",
          "value": "statusWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1status(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "statusWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionPassEntry/title",
          "value": "PKIssuerProvisioningExtensionPassEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionPassEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionPassEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionPassEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionPassEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionPaymentPassEntry/title",
          "value": "PKIssuerProvisioningExtensionPaymentPassEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionPaymentPassEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionPaymentPassEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionPaymentPassEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionPaymentPassEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler/title",
          "value": "PKIssuerProvisioningExtensionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1passEntries(completion:)/title",
          "value": "passEntriesWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionHandler~1passEntries(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passEntriesWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationProviding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkissuerprovisioningextensionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkissuerprovisioningextensionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
