{
  "abstract": [
    {
      "text": "Capabilities for processing payment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKMerchantCapability",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKMerchantCapability"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKMerchantCapability"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKMerchantCapability"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKMerchantCapability"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability": {
      "abstract": [
        {
          "text": "Capabilities for processing payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKMerchantCapability"
        }
      ],
      "role": "symbol",
      "title": "PKMerchantCapability",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capability3DS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capability3DS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capability3DS",
      "kind": "symbol",
      "role": "symbol",
      "title": "capability3DS",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/capability3ds"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityCredit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilityCredit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityCredit",
      "kind": "symbol",
      "role": "symbol",
      "title": "capabilityCredit",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/capabilitycredit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityDebit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilityDebit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityDebit",
      "kind": "symbol",
      "role": "symbol",
      "title": "capabilityDebit",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/capabilitydebit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityEMV": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilityEMV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityEMV",
      "kind": "symbol",
      "role": "symbol",
      "title": "capabilityEMV",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/capabilityemv"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/credit": {
      "abstract": [
        {
          "text": "Support for credit cards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/credit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKMerchantCapabilityCredit"
        }
      ],
      "role": "symbol",
      "title": "credit",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/credit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/debit": {
      "abstract": [
        {
          "text": "Support for debit cards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/debit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKMerchantCapabilityDebit"
        }
      ],
      "role": "symbol",
      "title": "debit",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/debit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/emv": {
      "abstract": [
        {
          "text": "Support for the EMV protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emv"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/emv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKMerchantCapabilityEMV"
        }
      ],
      "role": "symbol",
      "title": "emv",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/emv"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a merchant capability using the raw value you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/instantFundsOut": {
      "abstract": [
        {
          "text": "The value that indicates the merchant supports disbursing funds using Instant Funds Out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantFundsOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/instantFundsOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKMerchantCapabilityInstantFundsOut"
        }
      ],
      "role": "symbol",
      "title": "instantFundsOut",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/instantfundsout"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/threeDSecure": {
      "abstract": [
        {
          "text": "Support for the 3-D Secure protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threeDSecure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/threeDSecure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKMerchantCapability3DS"
        }
      ],
      "role": "symbol",
      "title": "threeDSecure",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcapability/threedsecure"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCategoryCode": {
      "abstract": [
        {
          "text": "The optional four-digit type, in ISO 18245 format, that represents the type of goods or service the merchant provides for the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKMerchantCategoryCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCategoryCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKMerchantCategoryCode",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcategorycode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKMerchantCategoryCodeNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKMerchantCategoryCodeNone"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKMerchantCategoryCodeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKMerchantCategoryCodeNone",
      "type": "topic",
      "url": "/documentation/passkit/pkmerchantcategorycodenone"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/MerchantCategoryCode-swift.struct": {
      "abstract": [
        {
          "text": "An optional four-digit struct, in ISO 18245 format, that represents the type of goods or service the merchant provides for the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MerchantCategoryCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/MerchantCategoryCode-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MerchantCategoryCode"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentRequest.MerchantCategoryCode",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/merchantcategorycode-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCapabilities": {
      "abstract": [
        {
          "text": "A bit field of the payment-processing protocols and card types that you support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "merchantCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "merchantCapabilities"
        }
      ],
      "role": "symbol",
      "title": "merchantCapabilities",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/merchantcapabilities"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCategoryCode-7vg6z": {
      "abstract": [
        {
          "text": "An optional four-digit property, in ISO 18245 format, that represents the type of goods or service the merchant provides for the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "merchantCategoryCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCategoryCode-7vg6z",
      "kind": "symbol",
      "role": "symbol",
      "title": "merchantCategoryCode",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/merchantcategorycode-7vg6z"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantIdentifier": {
      "abstract": [
        {
          "text": "Your merchant identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "merchantIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "merchantIdentifier"
        }
      ],
      "role": "symbol",
      "title": "merchantIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/merchantidentifier"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-merchant-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/MerchantCategoryCode-swift.struct",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCapabilities"
      ],
      "title": "Setting merchant information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/instantFundsOut",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/threeDSecure",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/emv",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/credit",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/debit"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capability3DS",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityCredit",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityDebit",
        "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/capabilityEMV"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKMerchantCapability"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/instantFundsOut",
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/threeDSecure",
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/emv",
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/credit",
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCapability/debit"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-merchant-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCategoryCode",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCategoryCode-7vg6z",
                "doc://com.apple.passkit/documentation/PassKit/PKMerchantCategoryCodeNone",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/merchantCapabilities"
              ],
              "title": "Setting merchant information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKMerchantCapability"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1merchantIdentifier/title",
          "value": "merchantIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1merchantIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "merchantIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1merchantCapabilities/title",
          "value": "merchantCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1merchantCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "merchantCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1emv/title",
          "value": "PKMerchantCapabilityEMV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1emv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapabilityEMV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability/title",
          "value": "PKMerchantCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1threeDSecure/title",
          "value": "PKMerchantCapability3DS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1threeDSecure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapability3DS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1credit/title",
          "value": "PKMerchantCapabilityCredit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1credit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapabilityCredit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1instantFundsOut/title",
          "value": "PKMerchantCapabilityInstantFundsOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1instantFundsOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapabilityInstantFundsOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1debit/title",
          "value": "PKMerchantCapabilityDebit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKMerchantCapability~1debit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKMerchantCapabilityDebit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkmerchantcapability"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkmerchantcapability"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
