{
  "abstract": [
    {
      "text": "An object that presents a sheet that prompts the user to authorize a payment request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKPaymentAuthorizationController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPaymentAuthorizationController"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentAuthorizationController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKPaymentAuthorizationController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After the user authorizes the payment request for a transaction, the delegate is called with a payment token used to authorize the transaction’s payment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class performs the same role as the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class, but it does not depend on the UIKit framework. This means that the authorization controller can be used in places where a view controller cannot (for example, in watchOS apps or in SiriKit extensions).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController": {
      "abstract": [
        {
          "text": "An object that presents a sheet that prompts the user to authorize a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationController"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationController",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments()": {
      "abstract": [
        {
          "text": "Returns whether the user can make payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canMakePayments"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canMakePayments"
        }
      ],
      "role": "symbol",
      "title": "canMakePayments()",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/canmakepayments()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:)": {
      "abstract": [
        {
          "text": "Returns whether the user can make payments through the specified network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canMakePayments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "usingNetworks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canMakePaymentsUsingNetworks:"
        }
      ],
      "role": "symbol",
      "title": "canMakePayments(usingNetworks:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/canmakepayments(usingnetworks:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:capabilities:)": {
      "abstract": [
        {
          "text": "Returns whether the user can make payments using a card from the specified network with the specified capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canMakePayments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "usingNetworks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "capabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:capabilities:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canMakePaymentsUsingNetworks:capabilities:"
        }
      ],
      "role": "symbol",
      "title": "canMakePayments(usingNetworks:capabilities:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/canmakepayments(usingnetworks:capabilities:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate": {
      "abstract": [
        {
          "text": "The controller’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKPaymentAuthorizationControllerDelegate",
          "text": "PKPaymentAuthorizationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/delegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)": {
      "abstract": [
        {
          "text": "Dismisses the payment sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismiss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "dismiss(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/dismiss(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(disbursementRequest:)": {
      "abstract": [
        {
          "text": "Creates a new payment authorization controller with the disbursement request you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "disbursementRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKDisbursementRequest",
          "text": "PKDisbursementRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(disbursementRequest:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDisbursementRequest:"
        }
      ],
      "role": "symbol",
      "title": "init(disbursementRequest:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/init(disbursementrequest:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(paymentRequest:)": {
      "abstract": [
        {
          "text": "Initializes and returns a payment authorization controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "paymentRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequest",
          "text": "PKPaymentRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(paymentRequest:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPaymentRequest:"
        }
      ],
      "role": "symbol",
      "title": "init(paymentRequest:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/init(paymentrequest:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)": {
      "abstract": [
        {
          "text": "Presents the payment sheet modally over your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "present(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/present(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this device can process disbursement requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDisbursements"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDisbursements"
        }
      ],
      "role": "symbol",
      "title": "supportsDisbursements()",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/supportsdisbursements()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this device can process disbursement requests using the specified payment network brands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDisbursements"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDisbursementsUsingNetworks:"
        }
      ],
      "role": "symbol",
      "title": "supportsDisbursements(using:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/supportsdisbursements(using:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:capabilities:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether this device can process disbursement requests using the specified payment network brands and capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDisbursements"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "capabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKMerchantCapability",
          "text": "PKMerchantCapability"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:capabilities:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDisbursementsUsingNetworks:capabilities:"
        }
      ],
      "role": "symbol",
      "title": "supportsDisbursements(using:capabilities:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/supportsdisbursements(using:capabilities:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate": {
      "abstract": [
        {
          "text": "Methods that let you respond to user interactions with your payment authorization controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController": {
      "abstract": [
        {
          "text": "An object that presents a sheet that prompts the user to authorize a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewController"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-Pay-availability",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController"
      ],
      "title": "Apple Pay availability"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-payment-authorization-controller",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(paymentRequest:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(disbursementRequest:)"
      ],
      "title": "Creating a payment authorization controller"
    },
    {
      "anchor": "Determining-whether-the-user-can-make-payments-or-disbursements",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments()",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:capabilities:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements()",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:capabilities:)"
      ],
      "title": "Determining whether the user can make payments or disbursements"
    },
    {
      "anchor": "Handling-user-interactions",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)"
      ],
      "title": "Handling user interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentAuthorizationController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-payment-authorization-controller",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(paymentRequest:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/init(disbursementRequest:)"
              ],
              "title": "Creating a payment authorization controller"
            },
            {
              "anchor": "Determining-whether-the-user-can-make-payments-or-disbursements",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments()",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/canMakePayments(usingNetworks:capabilities:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements()",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/supportsDisbursements(using:capabilities:)"
              ],
              "title": "Determining whether the user can make payments or disbursements"
            },
            {
              "anchor": "Handling-user-interactions",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)"
              ],
              "title": "Handling user interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Apple-Pay-availability",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController"
              ],
              "title": "Apple Pay availability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentAuthorizationController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1init(paymentRequest:)/title",
          "value": "initWithPaymentRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1init(paymentRequest:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPaymentRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1supportsDisbursements()/title",
          "value": "supportsDisbursements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1supportsDisbursements()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "supportsDisbursements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/title",
          "value": "PKPaymentAuthorizationViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1supportsDisbursements(using:capabilities:)/title",
          "value": "supportsDisbursementsUsingNetworks:capabilities:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1supportsDisbursements(using:capabilities:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "supportsDisbursementsUsingNetworks:capabilities:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1init(disbursementRequest:)/title",
          "value": "initWithDisbursementRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1init(disbursementRequest:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDisbursementRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1supportsDisbursements(using:)/title",
          "value": "supportsDisbursementsUsingNetworks:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1supportsDisbursements(using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "supportsDisbursementsUsingNetworks:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1dismiss(completion:)/title",
          "value": "dismissWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1dismiss(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1canMakePayments()/title",
          "value": "canMakePayments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1canMakePayments()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "canMakePayments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1present(completion:)/title",
          "value": "presentWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1present(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1canMakePayments(usingNetworks:capabilities:)/title",
          "value": "canMakePaymentsUsingNetworks:capabilities:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1canMakePayments(usingNetworks:capabilities:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "canMakePaymentsUsingNetworks:capabilities:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate/title",
          "value": "PKPaymentAuthorizationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController/title",
          "value": "PKPaymentAuthorizationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1canMakePayments(usingNetworks:)/title",
          "value": "canMakePaymentsUsingNetworks:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1canMakePayments(usingNetworks:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "canMakePaymentsUsingNetworks:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
