{
  "abstract": [
    {
      "text": "Cases that indicate payment pass activation states.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPaymentPassActivationState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPaymentPassActivationState"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentPassActivationState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "message": "Use PKSecureElementPassActivationState instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "message": "Use PKSecureElementPassActivationState instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "message": "Use PKSecureElementPassActivationState instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.4",
        "introducedAt": "11.0",
        "message": "Use PKSecureElementPassActivationState instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.4",
        "introducedAt": "1.0",
        "message": "Use PKSecureElementPassActivationState instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.0",
        "message": "Use PKSecureElementPassActivationState instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PKPaymentPassActivationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass/activationState": {
      "abstract": [
        {
          "text": "The current activation state of the pass.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentPassActivationState",
          "text": "PKPaymentPassActivationState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass/activationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activationState"
        }
      ],
      "role": "symbol",
      "title": "activationState",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpass/activationstate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState": {
      "abstract": [
        {
          "text": "Cases that indicate payment pass activation states.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationState"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPassActivationState",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activated": {
      "abstract": [
        {
          "text": "Active and ready for payment use.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activated"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationStateActivated"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPassActivationState.activated",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate/activated"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activating": {
      "abstract": [
        {
          "text": "Not ready for use but activation is in progress.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activating"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationStateActivating"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPassActivationState.activating",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate/activating"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/deactivated": {
      "abstract": [
        {
          "text": "Not active because the issuer disabled the account associated with the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivated"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/deactivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationStateDeactivated"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPassActivationState.deactivated",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate/deactivated"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/requiresActivation": {
      "abstract": [
        {
          "text": "Not active but may be activated by the issuer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresActivation"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/requiresActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationStateRequiresActivation"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPassActivationState.requiresActivation",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate/requiresactivation"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/suspended": {
      "abstract": [
        {
          "text": "Not active and can’t be activated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/suspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPassActivationStateSuspended"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPassActivationState.suspended",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpassactivationstate/suspended"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum": {
      "abstract": [
        {
          "text": "The activation states of a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PassActivationState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PassActivationState"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-activation-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass/activationState"
      ],
      "title": "Determining activation state"
    }
  ],
  "topicSections": [
    {
      "anchor": "Activation-states",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activated",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/requiresActivation",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activating",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/suspended",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/deactivated"
      ],
      "title": "Activation states"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.4",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.4",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentPassActivationState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activation-states",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activated",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/requiresActivation",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/activating",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/suspended",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPassActivationState/deactivated"
              ],
              "title": "Activation states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-activation-state",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass/activationState"
              ],
              "title": "Determining activation state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentPassActivationState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1activated/title",
          "value": "PKPaymentPassActivationStateActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1activated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationStateActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass~1activationState/title",
          "value": "activationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass~1activationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1suspended/title",
          "value": "PKPaymentPassActivationStateSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1suspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationStateSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1activating/title",
          "value": "PKPaymentPassActivationStateActivating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1activating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationStateActivating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState/title",
          "value": "PKPaymentPassActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1deactivated/title",
          "value": "PKPaymentPassActivationStateDeactivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1deactivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationStateDeactivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/title",
          "value": "PKSecureElementPassActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1requiresActivation/title",
          "value": "PKPaymentPassActivationStateRequiresActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPassActivationState~1requiresActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPassActivationStateRequiresActivation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentpassactivationstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentpassactivationstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
