{
  "abstract": [
    {
      "text": "Provides an interface to the user’s library of passes.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKPassLibrary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPassLibrary"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPassLibrary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKPassLibrary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "PKPassLibrary",
              "type": "codeVoice"
            },
            {
              "text": " isn’t thread-safe. Use instances of this class only on a single thread.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult": {
      "abstract": [
        {
          "text": "The result of an attempt to suppress automatic pass presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary": {
      "abstract": [
        {
          "text": "Provides an interface to the user’s library of passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibrary",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/activate(_:activationData:completion:)": {
      "abstract": [
        {
          "text": "Activates a Secure Element pass using the specified data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "activationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/activate(_:activationData:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateSecureElementPass:withActivationData:completion:"
        }
      ],
      "role": "symbol",
      "title": "activate(_:activationData:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/activate(_:activationdata:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Presents a user interface for adding multiple passes at once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPasses"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPassLibraryAddPassesStatus",
          "text": "PKPassLibraryAddPassesStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPasses:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addPasses(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/addpasses(_:withcompletionhandler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the library can add FeliCa™ passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canAddFelicaPass"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canAddFelicaPass"
        }
      ],
      "role": "symbol",
      "title": "canAddFelicaPass()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/canaddfelicapass()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether PassKit can add a Secure Element pass for the specified account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canAddSecureElementPass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "primaryAccountIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canAddSecureElementPassWithPrimaryAccountIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "canAddSecureElementPass(primaryAccountIdentifier:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/canaddsecureelementpass(primaryaccountidentifier:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the user’s pass library contains the specified pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsPass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsPass:"
        }
      ],
      "role": "symbol",
      "title": "containsPass(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/containspass(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/encryptedServiceProviderData(for:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptedServiceProviderData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/encryptedServiceProviderData(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptedServiceProviderDataForSecureElementPass:completion:"
        }
      ],
      "role": "symbol",
      "title": "encryptedServiceProviderData(for:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/encryptedserviceproviderdata(for:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)": {
      "abstract": [
        {
          "text": "Reenables the automatic display of the Apple Pay interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endAutomaticPassPresentationSuppression"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRequestToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKSuppressionRequestToken",
          "text": "PKSuppressionRequestToken"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endAutomaticPassPresentationSuppressionWithRequestToken:"
        }
      ],
      "role": "symbol",
      "title": "endAutomaticPassPresentationSuppression(withRequestToken:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/endautomaticpasspresentationsuppression(withrequesttoken:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the pass library is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPassLibraryAvailable"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPassLibraryAvailable"
        }
      ],
      "role": "symbol",
      "title": "isPassLibraryAvailable()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/ispasslibraryavailable()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSecureElementPassActivationAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports creating Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSecureElementPassActivationAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSecureElementPassActivationAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secureElementPassActivationAvailable"
        }
      ],
      "role": "symbol",
      "title": "isSecureElementPassActivationAvailable",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/issecureelementpassactivationavailable"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system suppresses the automatic presentation of Apple Pay passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSuppressingAutomaticPassPresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isSuppressingAutomaticPassPresentation"
        }
      ],
      "role": "symbol",
      "title": "isSuppressingAutomaticPassPresentation()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/issuppressingautomaticpasspresentation()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/openPaymentSetup()": {
      "abstract": [
        {
          "text": "Opens the user interface to set up credit cards for Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openPaymentSetup"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/openPaymentSetup()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openPaymentSetup"
        }
      ],
      "role": "symbol",
      "title": "openPaymentSetup()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/openpaymentsetup()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)": {
      "abstract": [
        {
          "text": "Returns the pass with the specified pass type identifier and serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "serialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passWithPassTypeIdentifier:serialNumber:"
        }
      ],
      "role": "symbol",
      "title": "pass(withPassTypeIdentifier:serialNumber:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/pass(withpasstypeidentifier:serialnumber:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()": {
      "abstract": [
        {
          "text": "Returns the passes in the user’s pass library that the app can access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passes"
        }
      ],
      "role": "symbol",
      "title": "passes()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/passes()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)": {
      "abstract": [
        {
          "text": "Returns the passes of the specified pass type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPassType",
          "text": "PKPassType"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passesOfType:"
        }
      ],
      "role": "symbol",
      "title": "passes(of:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/passes(of:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withReaderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passesWithReaderIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "passes(withReaderIdentifier:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/passes(withreaderidentifier:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u": {
      "abstract": [
        {
          "text": "Presents a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentSecureElementPass:"
        }
      ],
      "role": "symbol",
      "title": "present(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/present(_:)-9467u"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses": {
      "abstract": [
        {
          "text": "The Secure Element passes that PassKit stores on paired devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteSecureElementPasses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remoteSecureElementPasses"
        }
      ],
      "role": "symbol",
      "title": "remoteSecureElementPasses",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/remotesecureelementpasses"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/removePass(_:)": {
      "abstract": [
        {
          "text": "Removes the pass from the user’s pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removePass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/removePass(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removePass:"
        }
      ],
      "role": "symbol",
      "title": "removePass(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/removepass(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/replacePass(with:)": {
      "abstract": [
        {
          "text": "Replaces a pass in the user’s pass library with the specified pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacePass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/replacePass(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacePassWithPass:"
        }
      ],
      "role": "symbol",
      "title": "replacePass(with:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/replacepass(with:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)": {
      "abstract": [
        {
          "text": "Prevents the device from automatically displaying the Apple Pay interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAutomaticPassPresentationSuppression"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "responseHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAutomaticPassPresentationSuppressionResult",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKSuppressionRequestToken",
          "text": "PKSuppressionRequestToken"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAutomaticPassPresentationSuppressionWithResponseHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAutomaticPassPresentationSuppression(responseHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/requestautomaticpasspresentationsuppression(responsehandler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)": {
      "abstract": [
        {
          "text": "Calls a completion handler that returns the custom data for a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceProviderData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceProviderDataForSecureElementPass:completion:"
        }
      ],
      "role": "symbol",
      "title": "serviceProviderData(for:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/serviceproviderdata(for:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/sign(_:using:completion:)": {
      "abstract": [
        {
          "text": "Signs an opaque value using a cryptographic signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sign"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/sign(_:using:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signData:withSecureElementPass:completion:"
        }
      ],
      "role": "symbol",
      "title": "sign(_:using:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/sign(_:using:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus": {
      "abstract": [
        {
          "text": "Statuses that PassKit uses when it adds passes to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddPassesStatus"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddPassesStatus"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey": {
      "abstract": [
        {
          "text": "The user info keys that a pass library notification uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryNotificationKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName": {
      "abstract": [
        {
          "text": "The types of notifications that the pass library posts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationName"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationName"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryNotificationName",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken": {
      "abstract": [
        {
          "text": "A token that represents a request to suppress the automatic presentation of payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSuppressionRequestToken"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSuppressionRequestToken"
        }
      ],
      "role": "symbol",
      "title": "PKSuppressionRequestToken",
      "type": "topic",
      "url": "/documentation/passkit/pksuppressionrequesttoken"
    },
    "doc://com.apple.passkit/documentation/PassKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/passkit/deprecated-symbols"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Accessing-passes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses"
      ],
      "title": "Accessing passes"
    },
    {
      "anchor": "Adding-passes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus"
      ],
      "title": "Adding passes"
    },
    {
      "anchor": "Managing-passes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSecureElementPassActivationAvailable",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/activate(_:activationData:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/replacePass(with:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/removePass(_:)"
      ],
      "title": "Managing passes"
    },
    {
      "anchor": "Presenting-and-suppressing-passes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)",
        "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken"
      ],
      "title": "Presenting and suppressing passes"
    },
    {
      "anchor": "Setting-up-payments",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/openPaymentSetup()"
      ],
      "title": "Setting up payments"
    },
    {
      "anchor": "Signing-data",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/sign(_:using:completion:)"
      ],
      "title": "Signing data"
    },
    {
      "anchor": "Receiving-notifications",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName"
      ],
      "title": "Receiving notifications"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/deprecated-symbols"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/encryptedServiceProviderData(for:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPassLibrary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-passes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses"
              ],
              "title": "Accessing passes"
            },
            {
              "anchor": "Adding-passes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus"
              ],
              "title": "Adding passes"
            },
            {
              "anchor": "Managing-passes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSecureElementPassActivationAvailable",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/activate(_:activationData:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/replacePass(with:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/removePass(_:)"
              ],
              "title": "Managing passes"
            },
            {
              "anchor": "Presenting-and-suppressing-passes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/present(_:)-9467u",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isSuppressingAutomaticPassPresentation()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/requestAutomaticPassPresentationSuppression(responseHandler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/endAutomaticPassPresentationSuppression(withRequestToken:)",
                "doc://com.apple.passkit/documentation/PassKit/PKSuppressionRequestToken"
              ],
              "title": "Presenting and suppressing passes"
            },
            {
              "anchor": "Setting-up-payments",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/openPaymentSetup()"
              ],
              "title": "Setting up payments"
            },
            {
              "anchor": "Signing-data",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/sign(_:using:completion:)"
              ],
              "title": "Signing data"
            },
            {
              "anchor": "Receiving-notifications",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName"
              ],
              "title": "Receiving notifications"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/encryptedServiceProviderData(for:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPassLibrary"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/title",
          "value": "PKPassLibraryNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1remoteSecureElementPasses/title",
          "value": "remoteSecureElementPasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1remoteSecureElementPasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteSecureElementPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddFelicaPass()/title",
          "value": "canAddFelicaPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddFelicaPass()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canAddFelicaPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1activate(_:activationData:completion:)/title",
          "value": "activateSecureElementPass:withActivationData:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1activate(_:activationData:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateSecureElementPass:withActivationData:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isSuppressingAutomaticPassPresentation()/title",
          "value": "isSuppressingAutomaticPassPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isSuppressingAutomaticPassPresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isSuppressingAutomaticPassPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/title",
          "value": "PKPassLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(withReaderIdentifier:)/title",
          "value": "passesWithReaderIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(withReaderIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passesWithReaderIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1removePass(_:)/title",
          "value": "removePass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1removePass(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removePass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isPassLibraryAvailable()/title",
          "value": "isPassLibraryAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isPassLibraryAvailable()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isPassLibraryAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1requestAutomaticPassPresentationSuppression(responseHandler:)/title",
          "value": "requestAutomaticPassPresentationSuppressionWithResponseHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1requestAutomaticPassPresentationSuppression(responseHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAutomaticPassPresentationSuppressionWithResponseHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1serviceProviderData(for:completion:)/title",
          "value": "serviceProviderDataForSecureElementPass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1serviceProviderData(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "serviceProviderDataForSecureElementPass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/title",
          "value": "PKAutomaticPassPresentationSuppressionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationName/title",
          "value": "PKPassLibraryNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddSecureElementPass(primaryAccountIdentifier:)/title",
          "value": "canAddSecureElementPassWithPrimaryAccountIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddSecureElementPass(primaryAccountIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canAddSecureElementPassWithPrimaryAccountIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isSecureElementPassActivationAvailable/title",
          "value": "secureElementPassActivationAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isSecureElementPassActivationAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secureElementPassActivationAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1sign(_:using:completion:)/title",
          "value": "signData:withSecureElementPass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1sign(_:using:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "signData:withSecureElementPass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1pass(withPassTypeIdentifier:serialNumber:)/title",
          "value": "passWithPassTypeIdentifier:serialNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1pass(withPassTypeIdentifier:serialNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passWithPassTypeIdentifier:serialNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1addPasses(_:withCompletionHandler:)/title",
          "value": "addPasses:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1addPasses(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPasses:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes()/title",
          "value": "passes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1containsPass(_:)/title",
          "value": "containsPass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1containsPass(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "containsPass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1openPaymentSetup()/title",
          "value": "openPaymentSetup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1openPaymentSetup()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openPaymentSetup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1replacePass(with:)/title",
          "value": "replacePassWithPass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1replacePass(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacePassWithPass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1endAutomaticPassPresentationSuppression(withRequestToken:)/title",
          "value": "endAutomaticPassPresentationSuppressionWithRequestToken:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1endAutomaticPassPresentationSuppression(withRequestToken:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "endAutomaticPassPresentationSuppressionWithRequestToken:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuppressionRequestToken/title",
          "value": "PKSuppressionRequestToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuppressionRequestToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuppressionRequestToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuppressionRequestToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuppressionRequestToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/title",
          "value": "PKPassLibraryAddPassesStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1encryptedServiceProviderData(for:completion:)/title",
          "value": "encryptedServiceProviderDataForSecureElementPass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1encryptedServiceProviderData(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encryptedServiceProviderDataForSecureElementPass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1present(_:)-9467u/title",
          "value": "presentSecureElementPass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1present(_:)-9467u/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentSecureElementPass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(of:)/title",
          "value": "passesOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passesOfType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
