{
  "abstract": [
    {
      "text": "A type that represents a payment method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PKPaymentNetwork",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPaymentNetwork"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentNetwork"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKPaymentNetwork"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentRequest_h"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKAutomaticReloadPaymentRequest_h",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticreloadpaymentrequest_h"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentSummaryItem_h"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKAutomaticReloadPaymentSummaryItem_h",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticreloadpaymentsummaryitem_h"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKCONSTANTS_H": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKCONSTANTS_H"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKCONSTANTS_H",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKCONSTANTS_H",
      "type": "topic",
      "url": "/documentation/passkit/pkconstants_h"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork": {
      "abstract": [
        {
          "text": "A type that represents a payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetwork"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentNetwork",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/JCB": {
      "abstract": [
        {
          "text": "A JCB payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JCB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/JCB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkJCB"
        }
      ],
      "role": "symbol",
      "title": "JCB",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/jcb"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/NAPAS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NAPAS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/NAPAS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkNAPAS"
        }
      ],
      "role": "symbol",
      "title": "NAPAS",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/napas"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex": {
      "abstract": [
        {
          "text": "An American Express payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkAmex"
        }
      ],
      "role": "symbol",
      "title": "amex",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/amex"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat": {
      "abstract": [
        {
          "text": "A Bancomat payment card.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bancomat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBancomat"
        }
      ],
      "role": "symbol",
      "title": "bancomat",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/bancomat"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact": {
      "abstract": [
        {
          "text": "A Bancontact payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bancontact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBancontact"
        }
      ],
      "role": "symbol",
      "title": "bancontact",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/bancontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bankAxept"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBankAxept"
        }
      ],
      "role": "symbol",
      "title": "bankAxept",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/bankaxept"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode": {
      "abstract": [
        {
          "text": "A QR code to use for payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barcode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkBarcode"
        }
      ],
      "role": "symbol",
      "title": "barcode",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/barcode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carteBancaire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkCarteBancaire"
        }
      ],
      "role": "symbol",
      "title": "carteBancaire",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/cartebancaire"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaires": {
      "abstract": [
        {
          "text": "A Cartes Bancaires payment card.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carteBancaires"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaires",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkCarteBancaires"
        }
      ],
      "role": "symbol",
      "title": "carteBancaires",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/cartebancaires"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires": {
      "abstract": [
        {
          "text": "A Cartes Bancaires payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cartesBancaires"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkCartesBancaires"
        }
      ],
      "role": "symbol",
      "title": "cartesBancaires",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/cartesbancaires"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay": {
      "abstract": [
        {
          "text": "A China Union Pay payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chinaUnionPay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkChinaUnionPay"
        }
      ],
      "role": "symbol",
      "title": "chinaUnionPay",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/chinaunionpay"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort": {
      "abstract": [
        {
          "text": "The Dankort payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dankort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkDankort"
        }
      ],
      "role": "symbol",
      "title": "dankort",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/dankort"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover": {
      "abstract": [
        {
          "text": "A Discover payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkDiscover"
        }
      ],
      "role": "symbol",
      "title": "discover",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/discover"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos": {
      "abstract": [
        {
          "text": "The electronic funds transfer at point of sale (EFTPOS) payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eftpos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkEftpos"
        }
      ],
      "role": "symbol",
      "title": "eftpos",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/eftpos"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron": {
      "abstract": [
        {
          "text": "An Electron debit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electron"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkElectron"
        }
      ],
      "role": "symbol",
      "title": "electron",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/electron"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo": {
      "abstract": [
        {
          "text": "The Elo payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkElo"
        }
      ],
      "role": "symbol",
      "title": "elo",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/elo"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard": {
      "abstract": [
        {
          "text": "A Girocard payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "girocard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkGirocard"
        }
      ],
      "role": "symbol",
      "title": "girocard",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/girocard"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit": {
      "abstract": [
        {
          "text": "An iD payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idCredit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkIDCredit"
        }
      ],
      "role": "symbol",
      "title": "idCredit",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/idcredit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new payment network structure with the raw value you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/init(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new payment network structure with the string you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac": {
      "abstract": [
        {
          "text": "The Interac payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interac"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkInterac"
        }
      ],
      "role": "symbol",
      "title": "interac",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/interac"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mada": {
      "abstract": [
        {
          "text": "A mada payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mada"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mada",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkMada"
        }
      ],
      "role": "symbol",
      "title": "mada",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/mada"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/maestro": {
      "abstract": [
        {
          "text": "A Maestro payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maestro"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/maestro",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkMaestro"
        }
      ],
      "role": "symbol",
      "title": "maestro",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/maestro"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/masterCard": {
      "abstract": [
        {
          "text": "A Mastercard payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masterCard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/masterCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkMasterCard"
        }
      ],
      "role": "symbol",
      "title": "masterCard",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/mastercard"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/meeza": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meeza"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/meeza",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkMeeza"
        }
      ],
      "role": "symbol",
      "title": "meeza",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/meeza"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mir": {
      "abstract": [
        {
          "text": "A Mir payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mir"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mir",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkMir"
        }
      ],
      "role": "symbol",
      "title": "mir",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/mir"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/nanaco": {
      "abstract": [
        {
          "text": "A Nanaco payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nanaco"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/nanaco",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkNanaco"
        }
      ],
      "role": "symbol",
      "title": "nanaco",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/nanaco"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/pagoBancomat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pagoBancomat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/pagoBancomat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkPagoBancomat"
        }
      ],
      "role": "symbol",
      "title": "pagoBancomat",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/pagobancomat"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/postFinance": {
      "abstract": [
        {
          "text": "A PostFinance AG payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postFinance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/postFinance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkPostFinance"
        }
      ],
      "role": "symbol",
      "title": "postFinance",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/postfinance"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/privateLabel": {
      "abstract": [
        {
          "text": "Store credit and debit cards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privateLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/privateLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkPrivateLabel"
        }
      ],
      "role": "symbol",
      "title": "privateLabel",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/privatelabel"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/quicPay": {
      "abstract": [
        {
          "text": "A QUICPay payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quicPay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/quicPay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkQuicPay"
        }
      ],
      "role": "symbol",
      "title": "quicPay",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/quicpay"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/suica": {
      "abstract": [
        {
          "text": "A Suica payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suica"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/suica",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkSuica"
        }
      ],
      "role": "symbol",
      "title": "suica",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/suica"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/tmoney": {
      "abstract": [
        {
          "text": "The TMoney card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tmoney"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/tmoney",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkTmoney"
        }
      ],
      "role": "symbol",
      "title": "tmoney",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/tmoney"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/vPay": {
      "abstract": [
        {
          "text": "A Visa V Pay payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vPay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/vPay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkVPay"
        }
      ],
      "role": "symbol",
      "title": "vPay",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/vpay"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/visa": {
      "abstract": [
        {
          "text": "A Visa payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visa"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/visa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkVisa"
        }
      ],
      "role": "symbol",
      "title": "visa",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/visa"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/waon": {
      "abstract": [
        {
          "text": "A WAON payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/waon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentNetworkWaon"
        }
      ],
      "role": "symbol",
      "title": "waon",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentnetwork/waon"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/availableNetworks()": {
      "abstract": [
        {
          "text": "Returns the list of available payment methods that Apple Pay supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableNetworks"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/availableNetworks()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableNetworks"
        }
      ],
      "role": "symbol",
      "title": "availableNetworks()",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/availablenetworks()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/supportedNetworks": {
      "abstract": [
        {
          "text": "The payment methods that you support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedNetworks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentNetwork",
          "text": "PKPaymentNetwork"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/supportedNetworks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedNetworks"
        }
      ],
      "role": "symbol",
      "title": "supportedNetworks",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/supportednetworks"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKPaymentTokenContext_h"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKPaymentTokenContext_h",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenttokencontext_h"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentRequest_h"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKRecurringPaymentRequest_h",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest_h"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-the-payment-networks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/availableNetworks()",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/supportedNetworks"
      ],
      "title": "Selecting the payment networks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Payment-networks",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/JCB",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mada",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/maestro",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/masterCard",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/meeza",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mir",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/nanaco",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/NAPAS",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/pagoBancomat",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/postFinance",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/privateLabel",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/quicPay",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/suica",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/tmoney",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/visa",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/vPay",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/waon",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaires"
      ],
      "title": "Payment networks"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/init(_:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentNetwork"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Payment-networks",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/amex",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancomat",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bancontact",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/bankAxept",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/barcode",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaire",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/cartesBancaires",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/chinaUnionPay",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/dankort",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/discover",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/eftpos",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/electron",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/elo",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/girocard",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/idCredit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/interac",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/JCB",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mada",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/maestro",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/masterCard",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/meeza",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/mir",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/nanaco",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/NAPAS",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/pagoBancomat",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/postFinance",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/privateLabel",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/quicPay",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/suica",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/tmoney",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/visa",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/vPay",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/waon",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentNetwork/carteBancaires"
              ],
              "title": "Payment networks"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest_h",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem_h",
                "doc://com.apple.passkit/documentation/PassKit/PKCONSTANTS_H",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext_h",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest_h"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-the-payment-networks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/availableNetworks()",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/supportedNetworks"
              ],
              "title": "Selecting the payment networks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentNetwork"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1elo/title",
          "value": "PKPaymentNetworkElo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1elo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkElo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1suica/title",
          "value": "PKPaymentNetworkSuica"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1suica/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkSuica"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1quicPay/title",
          "value": "PKPaymentNetworkQuicPay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1quicPay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkQuicPay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1privateLabel/title",
          "value": "PKPaymentNetworkPrivateLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1privateLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkPrivateLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1JCB/title",
          "value": "PKPaymentNetworkJCB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1JCB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkJCB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1supportedNetworks/title",
          "value": "supportedNetworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1supportedNetworks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedNetworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1barcode/title",
          "value": "PKPaymentNetworkBarcode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1barcode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBarcode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1interac/title",
          "value": "PKPaymentNetworkInterac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1interac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkInterac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1tmoney/title",
          "value": "PKPaymentNetworkTmoney"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1tmoney/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkTmoney"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1girocard/title",
          "value": "PKPaymentNetworkGirocard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1girocard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkGirocard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1waon/title",
          "value": "PKPaymentNetworkWaon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1waon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkWaon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1postFinance/title",
          "value": "PKPaymentNetworkPostFinance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1postFinance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkPostFinance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork/title",
          "value": "PKPaymentNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1meeza/title",
          "value": "PKPaymentNetworkMeeza"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1meeza/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkMeeza"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1mir/title",
          "value": "PKPaymentNetworkMir"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1mir/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkMir"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1visa/title",
          "value": "PKPaymentNetworkVisa"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1visa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkVisa"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bankAxept/title",
          "value": "PKPaymentNetworkBankAxept"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bankAxept/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBankAxept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancomat/title",
          "value": "PKPaymentNetworkBancomat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancomat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBancomat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1NAPAS/title",
          "value": "PKPaymentNetworkNAPAS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1NAPAS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkNAPAS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancontact/title",
          "value": "PKPaymentNetworkBancontact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1bancontact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkBancontact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1carteBancaire/title",
          "value": "PKPaymentNetworkCarteBancaire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1carteBancaire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkCarteBancaire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1idCredit/title",
          "value": "PKPaymentNetworkIDCredit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1idCredit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkIDCredit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1dankort/title",
          "value": "PKPaymentNetworkDankort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1dankort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkDankort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1pagoBancomat/title",
          "value": "PKPaymentNetworkPagoBancomat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1pagoBancomat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkPagoBancomat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1vPay/title",
          "value": "PKPaymentNetworkVPay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1vPay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkVPay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1discover/title",
          "value": "PKPaymentNetworkDiscover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1discover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkDiscover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1carteBancaires/title",
          "value": "PKPaymentNetworkCarteBancaires"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1carteBancaires/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkCarteBancaires"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1nanaco/title",
          "value": "PKPaymentNetworkNanaco"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1nanaco/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkNanaco"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1mada/title",
          "value": "PKPaymentNetworkMada"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1mada/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkMada"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1cartesBancaires/title",
          "value": "PKPaymentNetworkCartesBancaires"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1cartesBancaires/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkCartesBancaires"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1maestro/title",
          "value": "PKPaymentNetworkMaestro"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1maestro/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkMaestro"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1eftpos/title",
          "value": "PKPaymentNetworkEftpos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1eftpos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkEftpos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1masterCard/title",
          "value": "PKPaymentNetworkMasterCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1masterCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkMasterCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1availableNetworks()/title",
          "value": "availableNetworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1availableNetworks()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "availableNetworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1amex/title",
          "value": "PKPaymentNetworkAmex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1amex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkAmex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1chinaUnionPay/title",
          "value": "PKPaymentNetworkChinaUnionPay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1chinaUnionPay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkChinaUnionPay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1electron/title",
          "value": "PKPaymentNetworkElectron"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentNetwork~1electron/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentNetworkElectron"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentnetwork"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentnetwork"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
