{
  "abstract": [
    {
      "text": "Methods that let you respond to user interactions with your payment authorization controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKPaymentAuthorizationControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPaymentAuthorizationControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentAuthorizationControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKPaymentAuthorizationControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol is implemented by the payment authorization controller’s delegate. You implement this protocol to respond to user interaction with that controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, the payment authorization controller automatically waits for its delegate to finish responding to one method before it calls other delegate methods. You indicate that the delegate is finished with the current method by calling that method’s completion block. This action tells the pay authorization controller to proceed with the next step in the authorization process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There is one exception to this step-by-step procedure: The pay authorization controller calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerDidFinish(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method as soon as the user cancels a payment without authorizing. The controller can call this method at any time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate": {
      "abstract": [
        {
          "text": "The controller’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKPaymentAuthorizationControllerDelegate",
          "text": "PKPaymentAuthorizationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/delegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)": {
      "abstract": [
        {
          "text": "Dismisses the payment sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismiss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "dismiss(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/dismiss(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)": {
      "abstract": [
        {
          "text": "Presents the payment sheet modally over your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "present(completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontroller/present(completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate": {
      "abstract": [
        {
          "text": "Methods that let you respond to user interactions with your payment authorization controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user authorized the payment request, and asks for a result.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAuthorizePayment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPayment",
          "text": "PKPayment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentAuthorizationStatus",
          "text": "PKPaymentAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didAuthorizePayment:completion:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didAuthorizePayment:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didauthorizepayment:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:handler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user authorized the payment request, and asks for a result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAuthorizePayment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPayment",
          "text": "PKPayment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationResult",
          "text": "PKPaymentAuthorizationResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didAuthorizePayment:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didAuthorizePayment:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didauthorizepayment:handler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didChangeCouponCode:handler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user entered or updated a coupon code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didChangeCouponCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestCouponCodeUpdate",
          "text": "PKPaymentRequestCouponCodeUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didChangeCouponCode:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didChangeCouponCode:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didChangeCouponCode:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didchangecouponcode:handler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)": {
      "abstract": [
        {
          "text": "Requests an object that validates the identity of a merchant for a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRequestMerchantSessionUpdate"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestMerchantSessionUpdate",
          "text": "PKPaymentRequestMerchantSessionUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didRequestMerchantSessionUpdate:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didrequestmerchantsessionupdate:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the payment method, and asks for an updated payment request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPaymentMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentMethod",
          "text": "PKPaymentMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentSummaryItem",
          "text": "PKPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didSelectPaymentMethod:completion:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didSelectPaymentMethod:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didselectpaymentmethod:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:handler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the payment method, and asks for an updated payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPaymentMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentMethod",
          "text": "PKPaymentMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestPaymentMethodUpdate",
          "text": "PKPaymentRequestPaymentMethodUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didSelectPaymentMethod:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didSelectPaymentMethod:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didselectpaymentmethod:handler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected a shipping address.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectShippingContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKContact",
          "text": "PKContact"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentAuthorizationStatus",
          "text": "PKPaymentAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKShippingMethod",
          "text": "PKShippingMethod"
        },
        {
          "kind": "text",
          "text": "], ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentSummaryItem",
          "text": "PKPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didSelectShippingContact:completion:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didSelectShippingContact:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didselectshippingcontact:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:handler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected a shipping address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectShippingContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKContact",
          "text": "PKContact"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestShippingContactUpdate",
          "text": "PKPaymentRequestShippingContactUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didSelectShippingContact:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didSelectShippingContact:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didselectshippingcontact:handler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected a shipping method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectShippingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKShippingMethod",
          "text": "PKShippingMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentAuthorizationStatus",
          "text": "PKPaymentAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentSummaryItem",
          "text": "PKPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didSelectShippingMethod:completion:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didSelectShippingMethod:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didselectshippingmethod:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:handler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected a shipping method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectShippingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKShippingMethod",
          "text": "PKShippingMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestShippingMethodUpdate",
          "text": "PKPaymentRequestShippingMethodUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationController:didSelectShippingMethod:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationController(_:didSelectShippingMethod:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontroller(_:didselectshippingmethod:handler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerDidFinish(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that payment authorization has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationControllerDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationControllerDidFinish:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "paymentAuthorizationControllerDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontrollerdidfinish(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerWillAuthorizePayment(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is authorizing the payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationControllerWillAuthorizePayment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerWillAuthorizePayment(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationControllerWillAuthorizePayment:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationControllerWillAuthorizePayment(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/paymentauthorizationcontrollerwillauthorizepayment(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/presentationWindow(for:)": {
      "abstract": [
        {
          "text": "Returns the window in which to present a payment authorization sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationWindow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationController",
          "text": "PKPaymentAuthorizationController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/presentationWindow(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationWindowForPaymentAuthorizationController:"
        }
      ],
      "role": "symbol",
      "title": "presentationWindow(for:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate/presentationwindow(for:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-user-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)"
      ],
      "title": "Handling user interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-user-interactions",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/presentationWindow(for:)"
      ],
      "title": "Handling user interactions"
    },
    {
      "anchor": "Handling-users-payment-method-selection",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:handler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:completion:)"
      ],
      "title": "Handling user’s payment method selection"
    },
    {
      "anchor": "Handling-coupons",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didChangeCouponCode:handler:)"
      ],
      "title": "Handling coupons"
    },
    {
      "anchor": "Handling-shipping-information",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:handler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:handler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:completion:)"
      ],
      "title": "Handling shipping information"
    },
    {
      "anchor": "Handling-users-payment-authorization",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerWillAuthorizePayment(_:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:handler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerDidFinish(_:)"
      ],
      "title": "Handling user’s payment authorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentAuthorizationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-user-interactions",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/presentationWindow(for:)"
              ],
              "title": "Handling user interactions"
            },
            {
              "anchor": "Handling-users-payment-method-selection",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:handler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectPaymentMethod:completion:)"
              ],
              "title": "Handling user’s payment method selection"
            },
            {
              "anchor": "Handling-coupons",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didChangeCouponCode:handler:)"
              ],
              "title": "Handling coupons"
            },
            {
              "anchor": "Handling-shipping-information",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:handler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingContact:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:handler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didSelectShippingMethod:completion:)"
              ],
              "title": "Handling shipping information"
            },
            {
              "anchor": "Handling-users-payment-authorization",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerWillAuthorizePayment(_:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:handler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationController(_:didAuthorizePayment:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationControllerDelegate/paymentAuthorizationControllerDidFinish(_:)"
              ],
              "title": "Handling user’s payment authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-user-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/delegate",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/present(completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationController/dismiss(completion:)"
              ],
              "title": "Handling user interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentAuthorizationControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectPaymentMethod:completion:)/title",
          "value": "paymentAuthorizationController:didSelectPaymentMethod:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectPaymentMethod:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didSelectPaymentMethod:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1present(completion:)/title",
          "value": "presentWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1present(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate/title",
          "value": "PKPaymentAuthorizationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)/title",
          "value": "paymentAuthorizationController:didRequestMerchantSessionUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didRequestMerchantSessionUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didRequestMerchantSessionUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationControllerWillAuthorizePayment(_:)/title",
          "value": "paymentAuthorizationControllerWillAuthorizePayment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationControllerWillAuthorizePayment(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationControllerWillAuthorizePayment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didAuthorizePayment:handler:)/title",
          "value": "paymentAuthorizationController:didAuthorizePayment:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didAuthorizePayment:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didAuthorizePayment:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1presentationWindow(for:)/title",
          "value": "presentationWindowForPaymentAuthorizationController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1presentationWindow(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentationWindowForPaymentAuthorizationController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationControllerDidFinish(_:)/title",
          "value": "paymentAuthorizationControllerDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationControllerDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationControllerDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1dismiss(completion:)/title",
          "value": "dismissWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1dismiss(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingContact:handler:)/title",
          "value": "paymentAuthorizationController:didSelectShippingContact:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingContact:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didSelectShippingContact:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectPaymentMethod:handler:)/title",
          "value": "paymentAuthorizationController:didSelectPaymentMethod:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectPaymentMethod:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didSelectPaymentMethod:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didAuthorizePayment:completion:)/title",
          "value": "paymentAuthorizationController:didAuthorizePayment:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didAuthorizePayment:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didAuthorizePayment:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingContact:completion:)/title",
          "value": "paymentAuthorizationController:didSelectShippingContact:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingContact:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didSelectShippingContact:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingMethod:handler:)/title",
          "value": "paymentAuthorizationController:didSelectShippingMethod:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingMethod:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didSelectShippingMethod:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingMethod:completion:)/title",
          "value": "paymentAuthorizationController:didSelectShippingMethod:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didSelectShippingMethod:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didSelectShippingMethod:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didChangeCouponCode:handler:)/title",
          "value": "paymentAuthorizationController:didChangeCouponCode:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationControllerDelegate~1paymentAuthorizationController(_:didChangeCouponCode:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationController:didChangeCouponCode:handler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
