{
  "abstract": [
    {
      "text": "The user info keys that a pass library notification uses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PKPassLibraryNotificationKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPassLibraryNotificationKey"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPassLibraryNotificationKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKPassLibraryNotificationKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey": {
      "abstract": [
        {
          "text": "The user info keys that a pass library notification uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryNotificationKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey": {
      "abstract": [
        {
          "text": "An array of added passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addedPassesUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddedPassesUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "addedPassesUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/addedpassesuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a pass library notification key according to the provided raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey": {
      "abstract": [
        {
          "text": "The pass’s pass type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passTypeIdentifierUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryPassTypeIdentifierUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "passTypeIdentifierUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/passtypeidentifieruserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recoveredPassesUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryRecoveredPassesUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "recoveredPassesUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/recoveredpassesuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey": {
      "abstract": [
        {
          "text": "An array of dictionaries that describes the removed passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removedPassInfosUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryRemovedPassInfosUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "removedPassInfosUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/removedpassinfosuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey": {
      "abstract": [
        {
          "text": "An array of replaced passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementPassesUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryReplacementPassesUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "replacementPassesUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/replacementpassesuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey": {
      "abstract": [
        {
          "text": "The pass’s serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serialNumberUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibrarySerialNumberUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "serialNumberUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/serialnumberuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName": {
      "abstract": [
        {
          "text": "The types of notifications that the pass library posts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationName"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationName"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryNotificationName",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationname"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Receiving-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName"
      ],
      "title": "Receiving notifications"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-pass-library-notification-key",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/init(rawValue:)"
      ],
      "title": "Creating a pass library notification key"
    },
    {
      "anchor": "Notification-keys",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey"
      ],
      "title": "Notification keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPassLibraryNotificationKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Notification-keys",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey"
              ],
              "title": "Notification keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Receiving-notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationName"
              ],
              "title": "Receiving notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPassLibraryNotificationKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1serialNumberUserInfoKey/title",
          "value": "PKPassLibrarySerialNumberUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1serialNumberUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrarySerialNumberUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/title",
          "value": "PKPassLibraryNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1addedPassesUserInfoKey/title",
          "value": "PKPassLibraryAddedPassesUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1addedPassesUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddedPassesUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1passTypeIdentifierUserInfoKey/title",
          "value": "PKPassLibraryPassTypeIdentifierUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1passTypeIdentifierUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryPassTypeIdentifierUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1replacementPassesUserInfoKey/title",
          "value": "PKPassLibraryReplacementPassesUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1replacementPassesUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryReplacementPassesUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1recoveredPassesUserInfoKey/title",
          "value": "PKPassLibraryRecoveredPassesUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1recoveredPassesUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryRecoveredPassesUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationName/title",
          "value": "PKPassLibraryNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1removedPassInfosUserInfoKey/title",
          "value": "PKPassLibraryRemovedPassInfosUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1removedPassInfosUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryRemovedPassInfosUserInfoKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibrarynotificationkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibrarynotificationkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
