{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKPaymentInformationRequestHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKPaymentInformationRequestHandling"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentInformationRequestHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKPaymentInformationRequestHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPaymentInformationRequestHandling"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before you can add a QR code purchase extension you need an entitlement from Apple. For more information on requesting an entitlement, contact apple-pay-inquiries@apple.com.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventConfigurationRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventConfigurationRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventConfigurationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventConfigurationRequest"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventConfigurationRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventconfigurationrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventMetadataRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventMetadataRequest"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventMetadataRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventmetadatarequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventMetadataResponse"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventMetadataResponse"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventMetadataResponse",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventmetadataresponse"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureRequest"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventSignatureRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignaturerequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureResponse"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKBarcodeEventSignatureResponse"
        }
      ],
      "role": "symbol",
      "title": "PKBarcodeEventSignatureResponse",
      "type": "topic",
      "url": "/documentation/passkit/pkbarcodeeventsignatureresponse"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKInformationRequestCompletionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInformationRequestCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKInformationRequestCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInformationRequestCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "PKInformationRequestCompletionBlock",
      "type": "topic",
      "url": "/documentation/passkit/pkinformationrequestcompletionblock"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationEventExtension": {
      "abstract": [
        {
          "text": "An abstract superclass for an extension to collect payment information and sign transaction data in a QR code purchase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentInformationEventExtension"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationEventExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentInformationEventExtension"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentInformationEventExtension",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentinformationeventextension"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentInformationRequestHandling"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentInformationRequestHandling"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentInformationRequestHandling",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentinformationrequesthandling"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKBarcodeEventSignatureRequest",
          "text": "PKBarcodeEventSignatureRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKSignatureRequestCompletionBlock",
          "text": "PKSignatureRequestCompletionBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleSignatureRequest:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(_:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentinformationrequesthandling/handle(_:completion:)-18x2y"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-3cth8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKBarcodeEventConfigurationRequest",
          "text": "PKBarcodeEventConfigurationRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-3cth8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleConfigurationRequest:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(_:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentinformationrequesthandling/handle(_:completion:)-3cth8"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handleInformationRequest(_:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleInformationRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKBarcodeEventMetadataRequest",
          "text": "PKBarcodeEventMetadataRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKInformationRequestCompletionBlock",
          "text": "PKInformationRequestCompletionBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handleInformationRequest(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleInformationRequest:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handleInformationRequest(_:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentinformationrequesthandling/handleinformationrequest(_:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSignatureRequestCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSignatureRequestCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "PKSignatureRequestCompletionBlock",
      "type": "topic",
      "url": "/documentation/passkit/pksignaturerequestcompletionblock"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QR-transaction-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationEventExtension"
      ],
      "title": "QR transaction information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-transaction-information",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-3cth8",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handleInformationRequest(_:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventConfigurationRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataResponse",
        "doc://com.apple.passkit/documentation/PassKit/PKInformationRequestCompletionBlock"
      ],
      "title": "Getting the transaction information"
    },
    {
      "anchor": "Signing-the-transaction",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse",
        "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock"
      ],
      "title": "Signing the transaction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentInformationRequestHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentInformationRequestHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentInformationRequestHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-transaction-information",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-3cth8",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handleInformationRequest(_:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventConfigurationRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventMetadataResponse",
                "doc://com.apple.passkit/documentation/PassKit/PKInformationRequestCompletionBlock"
              ],
              "title": "Getting the transaction information"
            },
            {
              "anchor": "Signing-the-transaction",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationRequestHandling/handle(_:completion:)-18x2y",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKBarcodeEventSignatureResponse",
                "doc://com.apple.passkit/documentation/PassKit/PKSignatureRequestCompletionBlock"
              ],
              "title": "Signing the transaction"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QR-transaction-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentInformationEventExtension"
              ],
              "title": "QR transaction information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentInformationRequestHandling"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventMetadataResponse/title",
          "value": "PKBarcodeEventMetadataResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventMetadataResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventMetadataResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventMetadataResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventMetadataResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKInformationRequestCompletionBlock/title",
          "value": "PKInformationRequestCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKInformationRequestCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInformationRequestCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKInformationRequestCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInformationRequestCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handle(_:completion:)-3cth8/title",
          "value": "handleConfigurationRequest:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handle(_:completion:)-3cth8/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleConfigurationRequest:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationEventExtension/title",
          "value": "PKPaymentInformationEventExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationEventExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentInformationEventExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationEventExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentInformationEventExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSignatureRequestCompletionBlock/title",
          "value": "PKSignatureRequestCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSignatureRequestCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSignatureRequestCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSignatureRequestCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSignatureRequestCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventMetadataRequest/title",
          "value": "PKBarcodeEventMetadataRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventMetadataRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventMetadataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventMetadataRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventMetadataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handleInformationRequest(_:completion:)/title",
          "value": "handleInformationRequest:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handleInformationRequest(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleInformationRequest:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventConfigurationRequest/title",
          "value": "PKBarcodeEventConfigurationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventConfigurationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventConfigurationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventConfigurationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventConfigurationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest/title",
          "value": "PKBarcodeEventSignatureRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handle(_:completion:)-18x2y/title",
          "value": "handleSignatureRequest:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling~1handle(_:completion:)-18x2y/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleSignatureRequest:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureResponse/title",
          "value": "PKBarcodeEventSignatureResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKBarcodeEventSignatureResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKBarcodeEventSignatureResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling/title",
          "value": "PKPaymentInformationRequestHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentInformationRequestHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentInformationRequestHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentInformationRequestHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentinformationrequesthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentinformationrequesthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
