{
  "abstract": [
    {
      "text": "A class that represents a request to set up a recurring payment, typically a subscription.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKRecurringPaymentRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKRecurringPaymentRequest"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKRecurringPaymentRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKRecurringPaymentRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You must set the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/recurringPaymentRequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property on a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object to use this class to request a recurring payment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to provide the user with payment details and a way to manage payment methods for a recurring payment. You can optionally display a billing agreement and set up merchant token life cycle notifications for the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the merchant token life cycle notifications, see Apple Pay Merchant Token Management API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to set up an automatic reload payment, such as a store card top-up or a prepaid account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticReloadPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticreloadpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest": {
      "abstract": [
        {
          "text": "An object that represents a request to set up a deferred payment, such as a hotel booking or a pre-order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDeferredPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDeferredPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKDeferredPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkdeferredpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest": {
      "abstract": [
        {
          "text": "An object that represents a request for payment, including details about payment-processing capabilities, the payment amount, and shipping information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/recurringPaymentRequest": {
      "abstract": [
        {
          "text": "An optional request to set up a recurring payment, typically a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurringPaymentRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKRecurringPaymentRequest",
          "text": "PKRecurringPaymentRequest"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/recurringPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recurringPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "recurringPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/recurringpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext": {
      "abstract": [
        {
          "text": "A class that defines the context for a single payment token in a payment request for multimerchant payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentTokenContext"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentTokenContext"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentTokenContext",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenttokencontext"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to set up a recurring payment, typically a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKRecurringPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/billingAgreement": {
      "abstract": [
        {
          "text": "A localized billing agreement that the payment sheet displays to the user before the user authorizes the payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingAgreement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/billingAgreement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "billingAgreement"
        }
      ],
      "role": "symbol",
      "title": "billingAgreement",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/billingagreement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/init(paymentDescription:regularBilling:managementURL:)": {
      "abstract": [
        {
          "text": "Create a recurring payment object with a description, regular billing information, and a management URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "paymentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "regularBilling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKRecurringPaymentSummaryItem",
          "text": "PKRecurringPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "managementURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/init(paymentDescription:regularBilling:managementURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPaymentDescription:regularBilling:managementURL:"
        }
      ],
      "role": "symbol",
      "title": "init(paymentDescription:regularBilling:managementURL:)",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/init(paymentdescription:regularbilling:managementurl:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/managementURL": {
      "abstract": [
        {
          "text": "A URL to a web page where the user can update or delete the payment method for the recurring payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managementURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/managementURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managementURL"
        }
      ],
      "role": "symbol",
      "title": "managementURL",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/managementurl"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/paymentDescription": {
      "abstract": [
        {
          "text": "A description that you provide of the recurring payment and that Apple Pay displays to the user in the payment sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/paymentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentDescription"
        }
      ],
      "role": "symbol",
      "title": "paymentDescription",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/paymentdescription"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/regularBilling": {
      "abstract": [
        {
          "text": "The regular billing cycle for the recurring payment, including start and end dates, an interval, and an interval count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularBilling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKRecurringPaymentSummaryItem",
          "text": "PKRecurringPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/regularBilling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularBilling"
        }
      ],
      "role": "symbol",
      "title": "regularBilling",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/regularbilling"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/tokenNotificationURL": {
      "abstract": [
        {
          "text": "A URL you provide to receive life-cycle notifications from the Apple Pay servers about the Apple Pay merchant token for the recurring payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenNotificationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/tokenNotificationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenNotificationURL"
        }
      ],
      "role": "symbol",
      "title": "tokenNotificationURL",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/tokennotificationurl"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/trialBilling": {
      "abstract": [
        {
          "text": "The trial billing cycle for the recurring payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trialBilling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKRecurringPaymentSummaryItem",
          "text": "PKRecurringPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/trialBilling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trialBilling"
        }
      ],
      "role": "symbol",
      "title": "trialBilling",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentrequest/trialbilling"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem": {
      "abstract": [
        {
          "text": "An object that defines a summary item for a payment that occurs repeatedly at a specified interval, such as a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKRecurringPaymentSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKRecurringPaymentSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkrecurringpaymentsummaryitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext"
      ],
      "title": "Payment requests"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-recurring-payment-request",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/init(paymentDescription:regularBilling:managementURL:)"
      ],
      "title": "Creating a recurring payment request"
    },
    {
      "anchor": "Describing-a-recurring-payment",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/paymentDescription",
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/billingAgreement"
      ],
      "title": "Describing a recurring payment"
    },
    {
      "anchor": "Setting-payment-summary-items",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/regularBilling",
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/trialBilling",
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem"
      ],
      "title": "Setting payment summary items"
    },
    {
      "anchor": "Managing-payment-tokens",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/tokenNotificationURL",
        "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/managementURL"
      ],
      "title": "Managing payment tokens"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKRecurringPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-recurring-payment-request",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/init(paymentDescription:regularBilling:managementURL:)"
              ],
              "title": "Creating a recurring payment request"
            },
            {
              "anchor": "Describing-a-recurring-payment",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/paymentDescription",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/billingAgreement"
              ],
              "title": "Describing a recurring payment"
            },
            {
              "anchor": "Setting-payment-summary-items",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/regularBilling",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/trialBilling",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentSummaryItem"
              ],
              "title": "Setting payment summary items"
            },
            {
              "anchor": "Managing-payment-tokens",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/tokenNotificationURL",
                "doc://com.apple.passkit/documentation/PassKit/PKRecurringPaymentRequest/managementURL"
              ],
              "title": "Managing payment tokens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKDeferredPaymentRequest",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentTokenContext"
              ],
              "title": "Payment requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKRecurringPaymentRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1trialBilling/title",
          "value": "trialBilling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1trialBilling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trialBilling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1tokenNotificationURL/title",
          "value": "tokenNotificationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1tokenNotificationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tokenNotificationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem/title",
          "value": "PKRecurringPaymentSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1regularBilling/title",
          "value": "regularBilling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1regularBilling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularBilling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1recurringPaymentRequest/title",
          "value": "recurringPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1recurringPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentRequest/title",
          "value": "PKAutomaticReloadPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticReloadPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticReloadPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1billingAgreement/title",
          "value": "billingAgreement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1billingAgreement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "billingAgreement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1managementURL/title",
          "value": "managementURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1managementURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "managementURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1paymentDescription/title",
          "value": "paymentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1paymentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest/title",
          "value": "PKDeferredPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDeferredPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDeferredPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentTokenContext/title",
          "value": "PKPaymentTokenContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentTokenContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentTokenContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentTokenContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentTokenContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest/title",
          "value": "PKRecurringPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKRecurringPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/title",
          "value": "PKPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1init(paymentDescription:regularBilling:managementURL:)/title",
          "value": "initWithPaymentDescription:regularBilling:managementURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKRecurringPaymentRequest~1init(paymentDescription:regularBilling:managementURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPaymentDescription:regularBilling:managementURL:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkrecurringpaymentrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkrecurringpaymentrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
