{
  "abstract": [
    {
      "text": "A pass with a credential that the device stores in a certified payment information chip.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKSecureElementPass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKSecureElementPass"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKSecureElementPass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKSecureElementPass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AsyncShareablePassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/asyncshareablepassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController": {
      "abstract": [
        {
          "text": "Lets your app show a pass and prompt the user to add that pass to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassesViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassesviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration": {
      "abstract": [
        {
          "text": "An object that describes the configuration of a secure element payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController": {
      "abstract": [
        {
          "text": "A view controller that manages the addition of secure element payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPass": {
      "abstract": [
        {
          "text": "An object that represents a single pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "role": "symbol",
      "title": "PKPass",
      "type": "topic",
      "url": "/documentation/passkit/pkpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass": {
      "abstract": [
        {
          "text": "An object that represents a provisioned payment card for in-app payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPass"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPass",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass": {
      "abstract": [
        {
          "text": "A pass with a credential that the device stores in a certified payment information chip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum": {
      "abstract": [
        {
          "text": "The activation states of a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PassActivationState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PassActivationState"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier for the device-specific account number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceAccountIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceAccountIdentifier"
        }
      ],
      "role": "symbol",
      "title": "deviceAccountIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/deviceaccountidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountNumberSuffix": {
      "abstract": [
        {
          "text": "A display-ready version of the device-specific account number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceAccountNumberSuffix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountNumberSuffix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceAccountNumberSuffix"
        }
      ],
      "role": "symbol",
      "title": "deviceAccountNumberSuffix",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/deviceaccountnumbersuffix"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/devicePassIdentifier": {
      "abstract": [
        {
          "text": "An opaque value for the pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePassIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/devicePassIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePassIdentifier"
        }
      ],
      "role": "symbol",
      "title": "devicePassIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/devicepassidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/pairedTerminalIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier of the paired terminal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pairedTerminalIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/pairedTerminalIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pairedTerminalIdentifier"
        }
      ],
      "role": "symbol",
      "title": "pairedTerminalIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/pairedterminalidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/passActivationState-swift.property": {
      "abstract": [
        {
          "text": "The activation state of the pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passActivationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKSecureElementPassActivationState",
          "text": "PassActivationState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/passActivationState-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passActivationState"
        }
      ],
      "role": "symbol",
      "title": "passActivationState",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.property"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountIdentifier": {
      "abstract": [
        {
          "text": "An opaque value that identifies the primary account number that funds the pass’s transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccountIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAccountIdentifier"
        }
      ],
      "role": "symbol",
      "title": "primaryAccountIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/primaryaccountidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountNumberSuffix": {
      "abstract": [
        {
          "text": "A display-ready version of the primary account number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccountNumberSuffix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountNumberSuffix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAccountNumberSuffix"
        }
      ],
      "role": "symbol",
      "title": "primaryAccountNumberSuffix",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/primaryaccountnumbersuffix"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassResult"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassResult",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Preview"
        }
      ],
      "role": "symbol",
      "title": "PKShareablePassMetadata.Preview",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata/preview-swift.class"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPass"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-purpose-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
        "doc://com.apple.passkit/documentation/PassKit/PKPass",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
        "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
        "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult"
      ],
      "title": "General purpose passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-activation-state",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/passActivationState-swift.property",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum"
      ],
      "title": "Getting the activation state"
    },
    {
      "anchor": "Getting-the-hardware-attributes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountNumberSuffix",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/devicePassIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/pairedTerminalIdentifier"
      ],
      "title": "Getting the hardware attributes"
    },
    {
      "anchor": "Getting-the-account-attributes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountIdentifier",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountNumberSuffix"
      ],
      "title": "Getting the account attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-activation-state",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/passActivationState-swift.property",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum"
              ],
              "title": "Getting the activation state"
            },
            {
              "anchor": "Getting-the-hardware-attributes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/deviceAccountNumberSuffix",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/devicePassIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/pairedTerminalIdentifier"
              ],
              "title": "Getting the hardware attributes"
            },
            {
              "anchor": "Getting-the-account-attributes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountIdentifier",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/primaryAccountNumberSuffix"
              ],
              "title": "Getting the account attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPass"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-purpose-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKPass",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
                "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult"
              ],
              "title": "General purpose passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKSecureElementPass"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKPass",
                    "text": "PKPass"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1pairedTerminalIdentifier/title",
          "value": "pairedTerminalIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1pairedTerminalIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pairedTerminalIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1primaryAccountNumberSuffix/title",
          "value": "primaryAccountNumberSuffix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1primaryAccountNumberSuffix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAccountNumberSuffix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/title",
          "value": "PKShareablePassMetadataPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/title",
          "value": "PKShareSecureElementPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass/title",
          "value": "PKPaymentPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1deviceAccountNumberSuffix/title",
          "value": "deviceAccountNumberSuffix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1deviceAccountNumberSuffix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceAccountNumberSuffix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1passActivationState-swift.property/title",
          "value": "passActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1passActivationState-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/title",
          "value": "PKAddSecureElementPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/title",
          "value": "PKSecureElementPassActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/title",
          "value": "PKShareSecureElementPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/title",
          "value": "PKPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/title",
          "value": "PKShareSecureElementPassResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1deviceAccountIdentifier/title",
          "value": "deviceAccountIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1deviceAccountIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceAccountIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1devicePassIdentifier/title",
          "value": "devicePassIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1devicePassIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "devicePassIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/title",
          "value": "PKAddPassesViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1primaryAccountIdentifier/title",
          "value": "primaryAccountIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1primaryAccountIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAccountIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/title",
          "value": "PKAddSecureElementPassConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pksecureelementpass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pksecureelementpass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
