{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKShareSecureElementPassViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKShareSecureElementPassViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKShareSecureElementPassViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKShareSecureElementPassViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AsyncShareablePassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/asyncshareablepassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController": {
      "abstract": [
        {
          "text": "Lets your app show a pass and prompt the user to add that pass to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassesViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassesviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration": {
      "abstract": [
        {
          "text": "An object that describes the configuration of a secure element payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController": {
      "abstract": [
        {
          "text": "A view controller that manages the addition of secure element payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPass": {
      "abstract": [
        {
          "text": "An object that represents a single pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "role": "symbol",
      "title": "PKPass",
      "type": "topic",
      "url": "/documentation/passkit/pkpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass": {
      "abstract": [
        {
          "text": "A pass with a credential that the device stores in a certified payment information chip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassResult"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassResult",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didCreateShare:activationCode:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shareSecureElementPassViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKShareSecureElementPassViewController",
          "text": "PKShareSecureElementPassViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCreateShare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "activationCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didCreateShare:activationCode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shareSecureElementPassViewController:didCreateShareURL:activationCode:"
        }
      ],
      "role": "symbol",
      "title": "shareSecureElementPassViewController(_:didCreateShare:activationCode:)",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate/sharesecureelementpassviewcontroller(_:didcreateshare:activationcode:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didFinishWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shareSecureElementPassViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKShareSecureElementPassViewController",
          "text": "PKShareSecureElementPassViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKShareSecureElementPassResult",
          "text": "PKShareSecureElementPassResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didFinishWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shareSecureElementPassViewController:didFinishWithResult:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "shareSecureElementPassViewController(_:didFinishWith:)",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate/sharesecureelementpassviewcontroller(_:didfinishwith:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Preview"
        }
      ],
      "role": "symbol",
      "title": "PKShareablePassMetadata.Preview",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata/preview-swift.class"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-purpose-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
        "doc://com.apple.passkit/documentation/PassKit/PKPass",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
        "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
        "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult"
      ],
      "title": "General purpose passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didCreateShare:activationCode:)",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didFinishWith:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKShareSecureElementPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didCreateShare:activationCode:)",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate/shareSecureElementPassViewController(_:didFinishWith:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-purpose-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKPass",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult"
              ],
              "title": "General purpose passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKShareSecureElementPassViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/title",
          "value": "PKAddSecureElementPassConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/title",
          "value": "PKShareSecureElementPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/title",
          "value": "PKAddSecureElementPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/title",
          "value": "PKShareablePassMetadataPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate~1shareSecureElementPassViewController(_:didCreateShare:activationCode:)/title",
          "value": "shareSecureElementPassViewController:didCreateShareURL:activationCode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate~1shareSecureElementPassViewController(_:didCreateShare:activationCode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shareSecureElementPassViewController:didCreateShareURL:activationCode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/title",
          "value": "PKAddPassesViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate~1shareSecureElementPassViewController(_:didFinishWith:)/title",
          "value": "shareSecureElementPassViewController:didFinishWithResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate~1shareSecureElementPassViewController(_:didFinishWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shareSecureElementPassViewController:didFinishWithResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/title",
          "value": "PKPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/title",
          "value": "PKShareSecureElementPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/title",
          "value": "PKShareSecureElementPassResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
