{
  "abstract": [
    {
      "text": "An object that represents a balance that’s available for transactions, such as points or money.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKStoredValuePassBalance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKStoredValuePassBalance"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKStoredValuePassBalance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKStoredValuePassBalance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "A stored balance of type of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " requires a valid currency code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance": {
      "abstract": [
        {
          "text": "An object that represents a balance that’s available for transactions, such as points or money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalance"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalance"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassBalance",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/==(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether two pass balance objects contain the same values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "=="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
          "text": "PKStoredValuePassBalance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
          "text": "PKStoredValuePassBalance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/==(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "==(_:_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/==(_:_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct": {
      "abstract": [
        {
          "text": "The type of value that the balance represents, such as money or points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BalanceType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BalanceType"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassBalance.BalanceType",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash": {
      "abstract": [
        {
          "text": "An identifier indicating a balance that represents money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
          "text": "PKStoredValuePassBalance"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
          "text": "BalanceType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalanceTypeCash"
        }
      ],
      "role": "symbol",
      "title": "cash",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct/cash"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/amount-2nwf5": {
      "abstract": [
        {
          "text": "The current balance of a stored-value pass in money or points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@NSDecimal",
          "text": "Decimal"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/amount-2nwf5",
      "kind": "symbol",
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/amount-2nwf5"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/amount-2vfd3": {
      "abstract": [
        {
          "text": "The current balance in money or points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "amount"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/amount-2vfd3",
      "kind": "symbol",
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/amount-2vfd3"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/balanceType-swift.property": {
      "abstract": [
        {
          "text": "The type of value that the balance represents, such as money or points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
          "text": "PKStoredValuePassBalance"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
          "text": "BalanceType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/balanceType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "balanceType"
        }
      ],
      "role": "symbol",
      "title": "balanceType",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.property"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/currencyCode": {
      "abstract": [
        {
          "text": "The ISO 4217 currency code of the balance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currencyCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/currencyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currencyCode"
        }
      ],
      "role": "symbol",
      "title": "currencyCode",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/currencycode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/expiryDate": {
      "abstract": [
        {
          "text": "The date that the balance expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expiryDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/expiryDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expiryDate"
        }
      ],
      "role": "symbol",
      "title": "expiryDate",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/expirydate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/isEqualToBalance:": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether two pass balance objects contain the same values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isEqualToBalance:"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/isEqualToBalance:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEqualToBalance:"
        }
      ],
      "role": "symbol",
      "title": "isEqualToBalance:",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/isequaltobalance:"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties": {
      "abstract": [
        {
          "text": "An object that represents the properties of a pass that contains a balance used for specific transactions, such as a transit pass or loyalty card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStoredValuePassProperties"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassProperties"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassProperties",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassproperties"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties": {
      "abstract": [
        {
          "text": "The properties of a pass used as a ticket for the Suica transportation system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSuicaPassProperties"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSuicaPassProperties"
        }
      ],
      "role": "symbol",
      "title": "PKSuicaPassProperties",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties": {
      "abstract": [
        {
          "text": "The properties of a transit pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKTransitPassProperties"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKTransitPassProperties"
        }
      ],
      "role": "symbol",
      "title": "PKTransitPassProperties",
      "type": "topic",
      "url": "/documentation/passkit/pktransitpassproperties"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stored-value-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties"
      ],
      "title": "Stored-value passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-pass-status",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/expiryDate",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/amount-2nwf5",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/balanceType-swift.property",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/currencyCode",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct"
      ],
      "title": "Getting the pass status"
    },
    {
      "anchor": "Comparing-pass-balance-objects",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/==(_:_:)"
      ],
      "title": "Comparing pass balance objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKStoredValuePassBalance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-pass-status",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/expiryDate",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/amount-2vfd3",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/balanceType-swift.property",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/currencyCode",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct"
              ],
              "title": "Getting the pass status"
            },
            {
              "anchor": "Comparing-pass-balance-objects",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/isEqualToBalance:"
              ],
              "title": "Comparing pass balance objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stored-value-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties"
              ],
              "title": "Stored-value passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKStoredValuePassBalance"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct~1cash/title",
          "value": "PKStoredValuePassBalanceTypeCash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct~1cash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceTypeCash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1balanceType-swift.property/title",
          "value": "balanceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1balanceType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "balanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassProperties/title",
          "value": "PKStoredValuePassProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct/title",
          "value": "PKStoredValuePassBalanceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties/title",
          "value": "PKSuicaPassProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1currencyCode/title",
          "value": "currencyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1currencyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currencyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/title",
          "value": "PKStoredValuePassBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKTransitPassProperties/title",
          "value": "PKTransitPassProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKTransitPassProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKTransitPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKTransitPassProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKTransitPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1expiryDate/title",
          "value": "expiryDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1expiryDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expiryDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkstoredvaluepassbalance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkstoredvaluepassbalance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
