{
  "abstract": [
    {
      "text": "The properties of a pass used as a ticket for the Suica transportation system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKSuicaPassProperties",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKSuicaPassProperties"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKSuicaPassProperties"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKSuicaPassProperties"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Suica pass is a card used for transportation in Japan.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance": {
      "abstract": [
        {
          "text": "An object that represents a balance that’s available for transactions, such as points or money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalance"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalance"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassBalance",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties": {
      "abstract": [
        {
          "text": "An object that represents the properties of a pass that contains a balance used for specific transactions, such as a transit pass or loyalty card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStoredValuePassProperties"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassProperties"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassProperties",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassproperties"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties": {
      "abstract": [
        {
          "text": "The properties of a pass used as a ticket for the Suica transportation system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSuicaPassProperties"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSuicaPassProperties"
        }
      ],
      "role": "symbol",
      "title": "PKSuicaPassProperties",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/init(for:)": {
      "abstract": [
        {
          "text": "Instantiates a Suica pass properties object that contains the properties supported in the specified pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/init(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passPropertiesForPass:"
        }
      ],
      "role": "symbol",
      "title": "init(for:)",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/init(for:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBalanceAllowedForCommute": {
      "abstract": [
        {
          "text": "A Boolean value that indicates how the balance can be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBalanceAllowedForCommute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBalanceAllowedForCommute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "balanceAllowedForCommute"
        }
      ],
      "role": "symbol",
      "title": "isBalanceAllowedForCommute",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/isbalanceallowedforcommute"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlacklisted": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the transit pass issuer disabled the pass.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBlacklisted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlacklisted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blacklisted"
        }
      ],
      "role": "symbol",
      "title": "isBlacklisted",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/isblacklisted"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlocked": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the pass issuer disabled the pass.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBlocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlocked",
      "kind": "symbol",
      "role": "symbol",
      "title": "isBlocked",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/isblocked"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isGreenCarTicketUsed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the customer has redeemed the Green Car ticket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGreenCarTicketUsed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isGreenCarTicketUsed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "greenCarTicketUsed"
        }
      ],
      "role": "symbol",
      "title": "isGreenCarTicketUsed",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/isgreencarticketused"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInShinkansenStation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the pass has tapped in at a Shinkansen Station and has not tapped out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInShinkansenStation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInShinkansenStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inShinkansenStation"
        }
      ],
      "role": "symbol",
      "title": "isInShinkansenStation",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/isinshinkansenstation"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInStation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the transit pass has tapped in at a station and has not tapped out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInStation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inStation"
        }
      ],
      "role": "symbol",
      "title": "isInStation",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/isinstation"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isLowBalanceGateNotificationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the terminal provides feedback if the balance is low after a deduction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLowBalanceGateNotificationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isLowBalanceGateNotificationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowBalanceGateNotificationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isLowBalanceGateNotificationEnabled",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/islowbalancegatenotificationenabled"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalance": {
      "abstract": [
        {
          "text": "The current usable stored value on the transit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitBalance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transitBalance"
        }
      ],
      "role": "symbol",
      "title": "transitBalance",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/transitbalance"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalanceCurrencyCode": {
      "abstract": [
        {
          "text": "The currency code associated with the balance on the pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitBalanceCurrencyCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalanceCurrencyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transitBalanceCurrencyCode"
        }
      ],
      "role": "symbol",
      "title": "transitBalanceCurrencyCode",
      "type": "topic",
      "url": "/documentation/passkit/pksuicapassproperties/transitbalancecurrencycode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties": {
      "abstract": [
        {
          "text": "The properties of a transit pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKTransitPassProperties"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKTransitPassProperties"
        }
      ],
      "role": "symbol",
      "title": "PKTransitPassProperties",
      "type": "topic",
      "url": "/documentation/passkit/pktransitpassproperties"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stored-value-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance"
      ],
      "title": "Stored-value passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-suica-pass-properties",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/init(for:)"
      ],
      "title": "Initializing suica pass properties"
    },
    {
      "anchor": "Getting-pass-status",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlocked",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlacklisted",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isGreenCarTicketUsed",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInShinkansenStation",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInStation"
      ],
      "title": "Getting pass status"
    },
    {
      "anchor": "Getting-suica-balance-information",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalance",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalanceCurrencyCode",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBalanceAllowedForCommute",
        "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isLowBalanceGateNotificationEnabled"
      ],
      "title": "Getting suica balance information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKSuicaPassProperties"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-suica-pass-properties",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/init(for:)"
              ],
              "title": "Initializing suica pass properties"
            },
            {
              "anchor": "Getting-pass-status",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBlacklisted",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isGreenCarTicketUsed",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInShinkansenStation",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isInStation"
              ],
              "title": "Getting pass status"
            },
            {
              "anchor": "Getting-suica-balance-information",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalance",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/transitBalanceCurrencyCode",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isBalanceAllowedForCommute",
                "doc://com.apple.passkit/documentation/PassKit/PKSuicaPassProperties/isLowBalanceGateNotificationEnabled"
              ],
              "title": "Getting suica balance information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stored-value-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassProperties",
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance"
              ],
              "title": "Stored-value passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKSuicaPassProperties"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKTransitPassProperties",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKTransitPassProperties",
                    "text": "PKTransitPassProperties"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassProperties/title",
          "value": "PKStoredValuePassProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isInStation/title",
          "value": "inStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isInStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isGreenCarTicketUsed/title",
          "value": "greenCarTicketUsed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isGreenCarTicketUsed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "greenCarTicketUsed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isLowBalanceGateNotificationEnabled/title",
          "value": "lowBalanceGateNotificationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isLowBalanceGateNotificationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowBalanceGateNotificationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isBlacklisted/title",
          "value": "blacklisted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isBlacklisted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blacklisted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isBalanceAllowedForCommute/title",
          "value": "balanceAllowedForCommute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isBalanceAllowedForCommute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "balanceAllowedForCommute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1transitBalance/title",
          "value": "transitBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1transitBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transitBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isInShinkansenStation/title",
          "value": "inShinkansenStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1isInShinkansenStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inShinkansenStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1init(for:)/title",
          "value": "passPropertiesForPass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1init(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "passPropertiesForPass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties/title",
          "value": "PKSuicaPassProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSuicaPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1transitBalanceCurrencyCode/title",
          "value": "transitBalanceCurrencyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSuicaPassProperties~1transitBalanceCurrencyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transitBalanceCurrencyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKTransitPassProperties/title",
          "value": "PKTransitPassProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKTransitPassProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKTransitPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKTransitPassProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKTransitPassProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/title",
          "value": "PKStoredValuePassBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pksuicapassproperties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pksuicapassproperties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
