{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKVehicleConnectionSessionConnectionState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKVehicleConnectionSessionConnectionState"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKVehicleConnectionSessionConnectionState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PKVehicleConnectionSessionConnectionState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddCarKeyPassConfiguration": {
      "abstract": [
        {
          "text": "A specialized configuration object that PassKit uses when it creates a digital car key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddCarKeyPassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddCarKeyPassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddCarKeyPassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PKAddCarKeyPassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/pkaddcarkeypassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectiondelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSession"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSession"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionSession",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsession"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSessionConnectionState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSessionConnectionState"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionSessionConnectionState",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsessionconnectionstate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connected"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSessionConnectionStateConnected"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionSessionConnectionState.connected",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsessionconnectionstate/connected"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connecting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connecting"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connecting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSessionConnectionStateConnecting"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionSessionConnectionState.connecting",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsessionconnectionstate/connecting"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/disconnected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnected"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/disconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSessionConnectionStateDisconnected"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionSessionConnectionState.disconnected",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsessionconnectionstate/disconnected"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/failedToConnect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToConnect"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/failedToConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionSessionConnectionStateFailedToConnect"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionSessionConnectionState.failedToConnect",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsessionconnectionstate/failedtoconnect"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionsessionconnectionstate/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Digital-car-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddCarKeyPassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSession",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionDelegate"
      ],
      "title": "Digital car keys"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connected",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connecting",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/disconnected",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/failedToConnect"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKVehicleConnectionSessionConnectionState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connected",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/connecting",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/disconnected",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSessionConnectionState/failedToConnect"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Digital-car-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddCarKeyPassConfiguration",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionSession",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionDelegate"
              ],
              "title": "Digital car keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKVehicleConnectionSessionConnectionState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSession/title",
          "value": "PKVehicleConnectionSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1failedToConnect/title",
          "value": "PKVehicleConnectionSessionConnectionStateFailedToConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1failedToConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionStateFailedToConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1disconnected/title",
          "value": "PKVehicleConnectionSessionConnectionStateDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1disconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionStateDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState/title",
          "value": "PKVehicleConnectionSessionConnectionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1connecting/title",
          "value": "PKVehicleConnectionSessionConnectionStateConnecting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1connecting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionStateConnecting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddCarKeyPassConfiguration/title",
          "value": "PKAddCarKeyPassConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddCarKeyPassConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddCarKeyPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddCarKeyPassConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddCarKeyPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionDelegate/title",
          "value": "PKVehicleConnectionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1connected/title",
          "value": "PKVehicleConnectionSessionConnectionStateConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionSessionConnectionState~1connected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionSessionConnectionStateConnected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkvehicleconnectionsessionconnectionstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkvehicleconnectionsessionconnectionstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
