{
  "abstract": [
    {
      "text": "Fulfill the requirements to provide Apple Pay as a payment option on your website or in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/apple-pay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/setting-up-apple-pay"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Setting up Apple Pay"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To set up your Apple developer account and Xcode to implement Apple Pay in your apps, you complete three steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a merchant identifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a Payment Processing certificate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enable Apple Pay in Xcode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Create-a-merchant-identifier",
          "level": 3,
          "text": "Create a merchant identifier",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To enable your app to use Apple Pay, register an identifier with Apple that uniquely identifies your business as a merchant able to accept payments. This ID never expires, and you can use it in multiple websites and apps. See ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-merchant-identifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the setup steps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-payment-processing-certificate",
          "level": 3,
          "text": "Create a payment processing certificate",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Using your registered merchant identifier, create a certificate to secure transaction data. Apple Pay servers use the certificate’s public key to encrypt payment data. You (or your payment service provider) use the private key to decrypt the data to process payments. See ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-payment-processing-certificate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the setup steps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you use an e-commerce provider or a payment platform, contact them for information about how to use their service with Apple Pay. See ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/apple-pay/#payment-platforms",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a list of service providers.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Enable-Apple-Pay-capability-in-Xcode",
          "level": 3,
          "text": "Enable Apple Pay capability in Xcode",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After creating a merchant identifier, enable the Apple Pay capability in your Xcode project.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open your project with Xcode. In the Project navigator, select the project.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose the target for the app from either the Project/Targets pop-up menu or in the Targets section of the outline view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Signing & Capabilities tab in the project editor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the toolbar, click the Library button (+) to open the Capabilities library and select the Apple Pay capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Within the Apple Pay capability, click the refresh button to synchronize your merchant identifiers from the Apple Developer site.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the merchant identifier to use with this app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The screenshot below shows the Apple Pay capability without any merchant identifiers:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3737978",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-Apple-Pay-on-the-web",
          "level": 3,
          "text": "Configure Apple Pay on the web",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re also developing websites using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can use the same merchant ID and Payment Processing Certificate for your website. However, Apple Pay on the web requires additional setup; see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web/configuring_your_environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/tech-talks/111381",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the ",
              "type": "text"
            },
            {
              "identifier": "http://developer.apple.com/apple-pay/Apple-Pay-Merchant-Integration-Guide.pdf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/Xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.documentation/documentation/apple_pay_on_the_web": {
      "abstract": [
        {
          "text": "Support Apple Pay on your website with JavaScript-based APIs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Pay on the Web",
      "type": "topic",
      "url": "/documentation/apple_pay_on_the_web"
    },
    "doc://com.apple.documentation/documentation/apple_pay_on_the_web/configuring_your_environment": {
      "abstract": [
        {
          "text": "Create your Apple Pay merchant ID and certificates, and verify your domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web/configuring_your_environment",
      "kind": "article",
      "role": "article",
      "title": "Configuring Your Environment",
      "type": "topic",
      "url": "/documentation/apple_pay_on_the_web/configuring_your_environment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/apple-pay": {
      "abstract": [
        {
          "text": "Request and process Apple Pay payments in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/apple-pay",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Pay",
      "type": "topic",
      "url": "/documentation/passkit/apple-pay"
    },
    "doc://com.apple.passkit/documentation/PassKit/complying-with-regional-regulations": {
      "abstract": [
        {
          "text": "Check regional regulations for possible requirements for your Apple Pay-based implementation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/complying-with-regional-regulations",
      "kind": "article",
      "role": "article",
      "title": "Complying with regional regulations",
      "type": "topic",
      "url": "/documentation/passkit/complying-with-regional-regulations"
    },
    "doc://com.apple.passkit/documentation/PassKit/offering-apple-pay-in-your-app": {
      "abstract": [
        {
          "text": "Collect payments with iPhone and Apple Watch using Apple Pay.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/offering-apple-pay-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Offering Apple Pay in Your App",
      "type": "topic",
      "url": "/documentation/passkit/offering-apple-pay-in-your-app"
    },
    "http://developer.apple.com/apple-pay/Apple-Pay-Merchant-Integration-Guide.pdf": {
      "identifier": "http://developer.apple.com/apple-pay/Apple-Pay-Merchant-Integration-Guide.pdf",
      "title": "Apple Pay Merchant Integration Guide",
      "titleInlineContent": [
        {
          "text": "Apple Pay Merchant Integration Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://developer.apple.com/apple-pay/Apple-Pay-Merchant-Integration-Guide.pdf"
    },
    "https://developer.apple.com/apple-pay/#payment-platforms": {
      "identifier": "https://developer.apple.com/apple-pay/#payment-platforms",
      "title": "Payment Platforms",
      "titleInlineContent": [
        {
          "text": "Payment Platforms",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/apple-pay/#payment-platforms"
    },
    "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-merchant-identifier": {
      "identifier": "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-merchant-identifier",
      "title": "Create a merchant identifier",
      "titleInlineContent": [
        {
          "text": "Create a merchant identifier",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-merchant-identifier"
    },
    "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-payment-processing-certificate": {
      "identifier": "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-payment-processing-certificate",
      "title": "Create a payment processing certificate",
      "titleInlineContent": [
        {
          "text": "Create a payment processing certificate",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/configure-app-capabilities/configure-apple-pay#create-a-payment-processing-certificate"
    },
    "https://developer.apple.com/videos/play/tech-talks/111381": {
      "identifier": "https://developer.apple.com/videos/play/tech-talks/111381",
      "title": "Get Started with Apple Pay on the Web",
      "titleInlineContent": [
        {
          "text": "Get Started with Apple Pay on the Web",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/tech-talks/111381"
    },
    "media-3737978": {
      "alt": "A screenshot showing the Apple Pay capability without any listed merchant identifiers. Beneath the empty list of merchant identifiers is a button to add a merchant identifier, and a button to refresh identifiers from the Apple Developer site.",
      "identifier": "media-3737978",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1872acfd24b98f341033640914195123/media-3737978@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-Pay-setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/offering-apple-pay-in-your-app",
        "doc://com.apple.passkit/documentation/PassKit/complying-with-regional-regulations"
      ],
      "title": "Apple Pay setup"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Apple-Pay-setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/offering-apple-pay-in-your-app",
                "doc://com.apple.passkit/documentation/PassKit/complying-with-regional-regulations"
              ],
              "title": "Apple Pay setup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/setting-up-apple-pay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/setting-up-apple-pay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
