{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The delegate that receives updates about the color selection."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)UIColorPickerViewControllerDelegate","kind":"typeIdentifier","text":"UIColorPickerViewControllerDelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewControllerDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController"]]},"kind":"symbol","metadata":{"modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIColorPickerViewControllerDelegate","text":"UIColorPickerViewControllerDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"14.0","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"externalID":"c:objc(cs)UIColorPickerViewController(py)delegate","title":"delegate","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicolorpickerviewcontroller/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicolorpickerviewcontroller/delegate"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewControllerDelegate","doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/selectedColor","doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/supportsAlpha"],"anchor":"Configuring-the-color-picker-view-controller","generated":true,"title":"Configuring the color picker view controller"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController":{"abstract":[{"text":"A view controller that manages the interface for selecting a color.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"UIColorPickerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIColorPickerViewController"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController","kind":"symbol","url":"/documentation/uikit/uicolorpickerviewcontroller","role":"symbol","type":"topic","title":"UIColorPickerViewController"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/supportsAlpha":{"abstract":[{"type":"text","text":"A Boolean value that enables alpha value control."}],"title":"supportsAlpha","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/supportsAlpha","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsAlpha"}],"url":"/documentation/uikit/uicolorpickerviewcontroller/supportsalpha","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportsAlpha"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/selectedColor":{"abstract":[{"type":"text","text":"The color selected by the user."}],"title":"selectedColor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/selectedColor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedColor"}],"url":"/documentation/uikit/uicolorpickerviewcontroller/selectedcolor","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]},"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/delegate":{"abstract":[{"type":"text","text":"The delegate that receives updates about the color selection."}],"title":"delegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/delegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"/documentation/uikit/uicolorpickerviewcontroller/delegate","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)UIColorPickerViewControllerDelegate","kind":"typeIdentifier","text":"UIColorPickerViewControllerDelegate"},{"kind":"text","text":")?"}]},"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewControllerDelegate":{"role":"symbol","title":"UIColorPickerViewControllerDelegate","type":"topic","url":"/documentation/uikit/uicolorpickerviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIColorPickerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegate protocol to inform about changes in color selection.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewControllerDelegate","kind":"symbol","navigatorTitle":[{"text":"UIColorPickerViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"delegate","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Configuring-the-color-picker-view-controller","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewControllerDelegate","doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/selectedColor","doc://com.apple.uikit/documentation/UIKit/UIColorPickerViewController/supportsAlpha"],"title":"Configuring the color picker view controller","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<UIColorPickerViewControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)UIColorPickerViewControllerDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"UIColorPickerViewController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController/title"},{"value":[{"kind":"identifier","text":"UIColorPickerViewController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController/fragments"},{"value":[{"text":"UIColorPickerViewController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController/navigatorTitle"},{"value":"supportsAlpha","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController~1supportsAlpha/title"},{"value":[{"kind":"identifier","text":"supportsAlpha"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController~1supportsAlpha/fragments"},{"value":"selectedColor","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController~1selectedColor/title"},{"value":[{"kind":"identifier","text":"selectedColor"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController~1selectedColor/fragments"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController~1delegate/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewController~1delegate/fragments"},{"value":"UIColorPickerViewControllerDelegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewControllerDelegate/title"},{"value":[{"text":"UIColorPickerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewControllerDelegate/fragments"},{"value":[{"text":"UIColorPickerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColorPickerViewControllerDelegate/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}