{
  "abstract": [
    {
      "text": "Plays an animation with the specified options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "RealityKit",
    "externalID": "s:17RealityFoundation6EntityCAAE13playAnimation_18transitionDuration16blendLayerOffset21separateAnimatedValue12startsPaused5clockAA0E18PlaybackControllerCAA0E8ResourceC_SdSiS2byXlSgtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "playAnimation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:17RealityFoundation17AnimationResourceC",
        "text": "AnimationResource"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "transitionDuration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "blendLayerOffset"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "separateAnimatedValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "startsPaused"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "clock"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
        "text": "CMClockOrTimebase"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:17RealityFoundation27AnimationPlaybackControllerC",
        "text": "AnimationPlaybackController"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@discardableResult"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "playAnimation"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "animation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/AnimationResource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:17RealityFoundation17AnimationResourceC",
              "text": "AnimationResource"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "transitionDuration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": " = 0, "
            },
            {
              "kind": "externalParam",
              "text": "blendLayerOffset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " = 0, "
            },
            {
              "kind": "externalParam",
              "text": "separateAnimatedValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = false, "
            },
            {
              "kind": "externalParam",
              "text": "startsPaused"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = false, "
            },
            {
              "kind": "externalParam",
              "text": "clock"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMClockOrTimebaseRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
              "text": "CMClockOrTimebase"
            },
            {
              "kind": "text",
              "text": "? = nil) -> "
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/AnimationPlaybackController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:17RealityFoundation27AnimationPlaybackControllerC",
              "text": "AnimationPlaybackController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The animation to play.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "animation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The duration in seconds over which the animation",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "fades in or cross-fades.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "transitionDuration"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An integer that specifies the order in which to",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "apply animations when more than one animation is playing. Valid values",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "are ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "code": "1",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "blendLayerOffset"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "When set to false, this value indicates that the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "animation will write directly to the entity’s base value. When set to true,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "this value indicates that the animation will write to an interim value for",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the duration of the animation. If this value is set to true then when the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "animation completes, the entity’s value will be reset to the base value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "separateAnimatedValue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean that pauses the progress of an animation when",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "set to ",
                  "type": "text"
                },
                {
                  "code": "true",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "startsPaused"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional clock to drive the animation with a custom",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "timescale.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "clock"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to play an animation and configure playback options.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "RealityKit supports blending up to two different animations at the same",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "time. When RealityKit applies multiple animations to an entity, the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "order in which it applies the animations affects the final animation.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "blendLayerOffset",
              "type": "codeVoice"
            },
            {
              "text": " parameter to specify the order of animations",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "when playing multiple animations at the same time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/AnimationPlaybackController": {
      "abstract": [
        {
          "text": "A controller that manages animation playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationPlaybackController"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/AnimationPlaybackController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationPlaybackController"
        }
      ],
      "role": "symbol",
      "title": "AnimationPlaybackController",
      "type": "topic",
      "url": "/documentation/realitykit/animationplaybackcontroller"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/AnimationResource": {
      "abstract": [
        {
          "text": "An animation for the properties of scenes or entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationResource"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/AnimationResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationResource"
        }
      ],
      "role": "symbol",
      "title": "AnimationResource",
      "type": "topic",
      "url": "/documentation/realitykit/animationresource"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity": {
      "abstract": [
        {
          "text": "An element of a RealityKit scene to which you attach components that provide",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "appearance and behavior characteristics for the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Entity"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entity"
        }
      ],
      "role": "symbol",
      "title": "Entity",
      "type": "topic",
      "url": "/documentation/realitykit/entity"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/ParameterSet": {
      "abstract": [
        {
          "text": "Represents a reference to the parameters for a particular entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParameterSet"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/ParameterSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParameterSet"
        }
      ],
      "role": "symbol",
      "title": "Entity.ParameterSet",
      "type": "topic",
      "url": "/documentation/realitykit/entity/parameterset"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/availableAnimations": {
      "abstract": [
        {
          "text": "The list of animations associated with the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableAnimations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation17AnimationResourceC",
          "text": "AnimationResource"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/availableAnimations",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableAnimations",
      "type": "topic",
      "url": "/documentation/realitykit/entity/availableanimations"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/bindableValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bindableValues"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation23BindableValuesReferenceV",
          "text": "BindableValuesReference"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/bindableValues",
      "kind": "symbol",
      "role": "symbol",
      "title": "bindableValues",
      "type": "topic",
      "url": "/documentation/realitykit/entity/bindablevalues"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/defaultAnimationClock": {
      "abstract": [
        {
          "text": "Returns the default animation clock for this entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultAnimationClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/defaultAnimationClock",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultAnimationClock",
      "type": "topic",
      "url": "/documentation/realitykit/entity/defaultanimationclock"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/parameters": {
      "abstract": [
        {
          "text": "Represents a reference to the parameters for a particular entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation6EntityC",
          "text": "Entity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation6EntityCAAE12ParameterSetV",
          "text": "ParameterSet"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/parameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "parameters",
      "type": "topic",
      "url": "/documentation/realitykit/entity/parameters"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:)": {
      "abstract": [
        {
          "text": "Plays an animation with the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation17AnimationResourceC",
          "text": "AnimationResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blendLayerOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "separateAnimatedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startsPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27AnimationPlaybackControllerC",
          "text": "AnimationPlaybackController"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:)",
      "type": "topic",
      "url": "/documentation/realitykit/entity/playanimation(_:transitionduration:blendlayeroffset:separateanimatedvalue:startspaused:clock:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:handoffType:)": {
      "abstract": [
        {
          "text": "Plays an animation with the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation17AnimationResourceC",
          "text": "AnimationResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blendLayerOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "separateAnimatedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startsPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "handoffType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation20AnimationHandoffTypeV",
          "text": "AnimationHandoffType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27AnimationPlaybackControllerC",
          "text": "AnimationPlaybackController"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:handoffType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:handoffType:)",
      "type": "topic",
      "url": "/documentation/realitykit/entity/playanimation(_:transitionduration:blendlayeroffset:separateanimatedvalue:startspaused:clock:handofftype:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:startsPaused:)": {
      "abstract": [
        {
          "text": "Plays the given animation on the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation17AnimationResourceC",
          "text": "AnimationResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startsPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27AnimationPlaybackControllerC",
          "text": "AnimationPlaybackController"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:startsPaused:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "playAnimation(_:transitionDuration:startsPaused:)",
      "type": "topic",
      "url": "/documentation/realitykit/entity/playanimation(_:transitionduration:startspaused:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(named:transitionDuration:startsPaused:recursive:)": {
      "abstract": [
        {
          "text": "Plays all the animations with the given name on the entity.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startsPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recursive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27AnimationPlaybackControllerC",
          "text": "AnimationPlaybackController"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(named:transitionDuration:startsPaused:recursive:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "playAnimation(named:transitionDuration:startsPaused:recursive:)",
      "type": "topic",
      "url": "/documentation/realitykit/entity/playanimation(named:transitionduration:startspaused:recursive:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/stopAllAnimations(recursive:)": {
      "abstract": [
        {
          "text": "Stops all playing of animations on this entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAllAnimations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "recursive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/stopAllAnimations(recursive:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "stopAllAnimations(recursive:)",
      "type": "topic",
      "url": "/documentation/realitykit/entity/stopallanimations(recursive:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity/subscript(_:)": {
      "abstract": [
        {
          "text": "Resolves the entity from the given entity path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation10BindTargetO",
          "text": "BindTarget"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation10BindTargetO10EntityPathV",
          "text": "EntityPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation6EntityC",
          "text": "Entity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity/subscript(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/realitykit/entity/subscript(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMClockOrTimebaseRef": {
      "abstract": [
        {
          "text": "A type you use in argument lists and function results to indicate that you can pass either a clock or timebase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMClockOrTimebaseRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMClockOrTimebase",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMClockOrTimebase"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animating-an-entity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/availableAnimations",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:blendLayerOffset:separateAnimatedValue:startsPaused:clock:handoffType:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(_:transitionDuration:startsPaused:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/stopAllAnimations(recursive:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/defaultAnimationClock",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/parameters",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/ParameterSet",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/playAnimation(named:transitionDuration:startsPaused:recursive:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/bindableValues",
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity/subscript(_:)"
      ],
      "title": "Animating an entity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMClockOrTimebaseRef/title",
          "value": "CMClockOrTimebaseRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMClockOrTimebaseRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMClockOrTimebaseRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/entity/playanimation(_:transitionduration:blendlayeroffset:separateanimatedvalue:startspaused:clock:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
