{
  "abstract": [
    {
      "text": "Returns the scores for the local player and other players for the specified type of player, time period, and ranks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:range:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKLeaderboard(im)loadEntriesForPlayerScope:timeScope:range:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "loadEntries"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKLeaderboard",
        "text": "GKLeaderboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
        "text": "PlayerScope"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "timeScope"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKLeaderboard",
        "text": "GKLeaderboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
        "text": "TimeScope"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "range"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "NSRange"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKLeaderboard",
        "text": "GKLeaderboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
        "text": "Entry"
      },
      {
        "kind": "text",
        "text": "?, ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKLeaderboard",
        "text": "GKLeaderboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
        "text": "Entry"
      },
      {
        "kind": "text",
        "text": "]?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "loadEntriesForPlayerScope:timeScope:range:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "loadEntries(for:timeScope:range:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "loadEntries"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "playerScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
              "text": "PlayerScope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "timeScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
              "text": "TimeScope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
              "text": "Entry"
            },
            {
              "kind": "text",
              "text": "?, ["
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
              "text": "Entry"
            },
            {
              "kind": "text",
              "text": "]?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "loadEntries"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "playerScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
              "text": "PlayerScope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "timeScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
              "text": "TimeScope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> ("
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
              "text": "Entry"
            },
            {
              "kind": "text",
              "text": "?, ["
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboard",
              "text": "GKLeaderboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
              "text": "Entry"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specifies whether to get scores from friends or all players.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "playerScope"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specifies the time period for the scores. This parameter is applicable to nonrecurring leaderboards only. For recurring leaderboards, pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum/allTime",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for this parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "timeScope"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specifies the range of ranks to use for getting the scores. The difference between the minimum rank and maximum rank must not exceed ",
                  "type": "text"
                },
                {
                  "code": "100",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that GameKit calls when this method completes the request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The block receives the following parameters:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The score for the local player, or ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if the player has no score.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "localPlayerEntry",
                        "type": "text"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The scores this method loads that match the ",
                            "type": "text"
                          },
                          {
                            "code": "playerScope",
                            "type": "codeVoice"
                          },
                          {
                            "text": ", ",
                            "type": "text"
                          },
                          {
                            "code": "timeScope",
                            "type": "codeVoice"
                          },
                          {
                            "text": ", and ",
                            "type": "text"
                          },
                          {
                            "code": "range",
                            "type": "codeVoice"
                          },
                          {
                            "text": " parameters, including the local player’s score if it exists.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "entries",
                        "type": "text"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The total number of players whose scores match the ",
                            "type": "text"
                          },
                          {
                            "code": "playerScope",
                            "type": "codeVoice"
                          },
                          {
                            "text": " and ",
                            "type": "text"
                          },
                          {
                            "code": "timeScope",
                            "type": "codeVoice"
                          },
                          {
                            "text": " parameters, but not the ",
                            "type": "text"
                          },
                          {
                            "code": "range",
                            "type": "codeVoice"
                          },
                          {
                            "text": " parameter.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "totalPlayerCount",
                        "type": "text"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "Describes an error if it occurs, or ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if the operation completes.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "error",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "GameKit uses the following algorithm to fetch ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " scores:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Begins with the set of all possible scores for the leaderboard.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Discards any scores that don’t match the ",
                      "type": "text"
                    },
                    {
                      "code": "playerScope",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "timeScope",
                      "type": "codeVoice"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For each player, keeps the best score that player earns and discards the rest.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sorts the scores from best to worst.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Uses the range property to determine which scores return.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard": {
      "abstract": [
        {
          "text": "A leaderboard for a game that Game Center stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboard"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboard"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry": {
      "abstract": [
        {
          "text": "Information about a single score by a player on a leaderboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Entry"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entry"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard.Entry",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/entry"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum": {
      "abstract": [
        {
          "text": "Specifies the type of players for filtering data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PlayerScope"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PlayerScope"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard.PlayerScope",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/playerscope-swift.enum"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum": {
      "abstract": [
        {
          "text": "Specifies the time period for filtering data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeScope"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeScope"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard.TimeScope",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/timescope-swift.enum"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum/allTime": {
      "abstract": [
        {
          "text": "Loads a player’s best score.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allTime"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum/allTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardTimeScopeAllTime"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard.TimeScope.allTime",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/timescope-swift.enum/alltime"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:completionHandler:)": {
      "abstract": [
        {
          "text": "Returns the scores for the local player and other players for the specified time period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadEntries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
          "text": "TimeScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
          "text": "Entry"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
          "text": "Entry"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadEntriesForPlayers:timeScope:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadEntries(for:timeScope:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadentries(for:timescope:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:range:completionHandler:)": {
      "abstract": [
        {
          "text": "Returns the scores for the local player and other players for the specified type of player, time period, and ranks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadEntries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
          "text": "PlayerScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
          "text": "TimeScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
          "text": "Entry"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
          "text": "Entry"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:range:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadEntriesForPlayerScope:timeScope:range:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadEntries(for:timeScope:range:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadentries(for:timescope:range:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards": {
      "abstract": [
        {
          "text": "Let players measure their own progress and compare their skills with friends and others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards",
      "kind": "article",
      "role": "article",
      "title": "Encourage progress and competition with leaderboards",
      "type": "topic",
      "url": "/documentation/gamekit/encourage-progress-and-competition-with-leaderboards"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-Scores",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:completionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry"
      ],
      "title": "Loading Scores"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "loadEntriesForPlayerScope:timeScope:range:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadEntriesForPlayerScope:timeScope:range:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-Scores",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadEntries(for:timeScope:completionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry"
              ],
              "title": "Loading Scores"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "loadEntriesForPlayerScope:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/PlayerScope-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
                    "text": "GKLeaderboardPlayerScope"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "playerScope"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "timeScope:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
                    "text": "GKLeaderboardTimeScope"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "timeScope"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "range:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@_NSRange",
                    "text": "NSRange"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "range"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/Entry",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GKLeaderboardEntry",
                    "text": "GKLeaderboardEntry"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "localPlayerEntry"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<GKLeaderboardEntry *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "entries"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "totalPlayerCount"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies whether to get scores from friends or all players.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "playerScope"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies the time period for the scores. This parameter is applicable to nonrecurring leaderboards only. For recurring leaderboards, pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/TimeScope-swift.enum/allTime",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for this parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "timeScope"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies the range of ranks to use for getting the scores. The difference between the minimum rank and maximum rank must not exceed ",
                        "type": "text"
                      },
                      {
                        "code": "100",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "range"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block that GameKit calls when this method completes the request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The block receives the following parameters:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The score for the local player, or ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if the player has no score.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "localPlayerEntry",
                              "type": "text"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The scores this method loads that match the ",
                                  "type": "text"
                                },
                                {
                                  "code": "playerScope",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": ", ",
                                  "type": "text"
                                },
                                {
                                  "code": "timeScope",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": ", and ",
                                  "type": "text"
                                },
                                {
                                  "code": "range",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " parameters, including the local player’s score if it exists.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "entries",
                              "type": "text"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The total number of players whose scores match the ",
                                  "type": "text"
                                },
                                {
                                  "code": "playerScope",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " and ",
                                  "type": "text"
                                },
                                {
                                  "code": "timeScope",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " parameters, but not the ",
                                  "type": "text"
                                },
                                {
                                  "code": "range",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " parameter.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "totalPlayerCount",
                              "type": "text"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "Describes an error if it occurs, or ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if the operation completes.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "error",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1Entry/title",
          "value": "GKLeaderboardEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1Entry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1Entry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadEntries(for:timeScope:completionHandler:)/title",
          "value": "loadEntriesForPlayers:timeScope:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadEntries(for:timeScope:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadEntriesForPlayers:timeScope:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1TimeScope-swift.enum~1allTime/title",
          "value": "GKLeaderboardTimeScopeAllTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1TimeScope-swift.enum~1allTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardTimeScopeAllTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1PlayerScope-swift.enum/title",
          "value": "GKLeaderboardPlayerScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1PlayerScope-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardPlayerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1PlayerScope-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardPlayerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadEntries(for:timeScope:range:completionHandler:)/title",
          "value": "loadEntriesForPlayerScope:timeScope:range:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadEntries(for:timeScope:range:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadEntriesForPlayerScope:timeScope:range:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1TimeScope-swift.enum/title",
          "value": "GKLeaderboardTimeScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1TimeScope-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardTimeScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1TimeScope-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardTimeScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/title",
          "value": "GKLeaderboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkleaderboard/loadentries(for:timescope:range:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkleaderboard/loadentries(for:timescope:range:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
