{
  "abstract": [
    {
      "text": "Performs the default text checking on the entire document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInDocument(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSTextView(im)checkTextInDocument:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "checkTextInDocument"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "checkTextInDocument:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "checkTextInDocument(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "checkTextInDocument"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sender"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The control sending the message. May be ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sender"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Immediately performs the text checking and replaces the document content with the checked content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The checks performed are specified by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/enabledTextCheckingTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ";",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkText(in:types:options:)": {
      "abstract": [
        {
          "text": "Check and replace the text in the range using the specified checking types and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "types"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextCheckingTypes",
          "text": "NSTextCheckingTypes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSpellChecker",
          "text": "NSSpellChecker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextCheckingOptionKey",
          "text": "OptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkText(in:types:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "checkTextInRange:types:options:"
        }
      ],
      "role": "symbol",
      "title": "checkText(in:types:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/checktext(in:types:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInDocument(_:)": {
      "abstract": [
        {
          "text": "Performs the default text checking on the entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkTextInDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInDocument(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "checkTextInDocument:"
        }
      ],
      "role": "symbol",
      "title": "checkTextInDocument(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/checktextindocument(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInSelection(_:)": {
      "abstract": [
        {
          "text": "Performs the default text checking on the current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkTextInSelection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInSelection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "checkTextInSelection:"
        }
      ],
      "role": "symbol",
      "title": "checkTextInSelection(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/checktextinselection(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/enabledTextCheckingTypes": {
      "abstract": [
        {
          "text": "The default text checking types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabledTextCheckingTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextCheckingTypes",
          "text": "NSTextCheckingTypes"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/enabledTextCheckingTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabledTextCheckingTypes"
        }
      ],
      "role": "symbol",
      "title": "enabledTextCheckingTypes",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/enabledtextcheckingtypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)": {
      "abstract": [
        {
          "text": "Handles the text checking results returned by the text view",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleTextCheckingResults"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextCheckingResult",
          "text": "NSTextCheckingResult"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "types"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextCheckingTypes",
          "text": "NSTextCheckingTypes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSpellChecker",
          "text": "NSSpellChecker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextCheckingOptionKey",
          "text": "OptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "orthography"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOrthography",
          "text": "NSOrthography"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "wordCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleTextCheckingResults:forRange:types:options:orthography:wordCount:"
        }
      ],
      "role": "symbol",
      "title": "handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/handletextcheckingresults(_:forrange:types:options:orthography:wordcount:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDashSubstitutionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether automatic dash substitution is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticDashSubstitutionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDashSubstitutionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticDashSubstitutionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticDashSubstitutionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomaticdashsubstitutionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDataDetectionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether automatic data detection is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticDataDetectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDataDetectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticDataDetectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticDataDetectionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomaticdatadetectionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticSpellingCorrectionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether automatic spelling correction is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticSpellingCorrectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticSpellingCorrectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticSpellingCorrectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticSpellingCorrectionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomaticspellingcorrectionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextReplacementEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether automatic text replacement is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticTextReplacementEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextReplacementEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticTextReplacementEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticTextReplacementEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomatictextreplacementenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/performValidatedReplacement(in:with:)": {
      "abstract": [
        {
          "text": "Replaces text in the range you specify with the attributed string you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performValidatedReplacement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/performValidatedReplacement(in:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performValidatedReplacementInRange:withAttributedString:"
        }
      ],
      "role": "symbol",
      "title": "performValidatedReplacement(in:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/performvalidatedreplacement(in:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDashSubstitution(_:)": {
      "abstract": [
        {
          "text": "Toggles the state of the automatic dash substitution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleAutomaticDashSubstitution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDashSubstitution(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleAutomaticDashSubstitution:"
        }
      ],
      "role": "symbol",
      "title": "toggleAutomaticDashSubstitution(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggleautomaticdashsubstitution(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDataDetection(_:)": {
      "abstract": [
        {
          "text": "Toggles the state of the automatic data detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleAutomaticDataDetection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDataDetection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleAutomaticDataDetection:"
        }
      ],
      "role": "symbol",
      "title": "toggleAutomaticDataDetection(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggleautomaticdatadetection(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticSpellingCorrection(_:)": {
      "abstract": [
        {
          "text": "Toggles the state of the automatic spelling correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleAutomaticSpellingCorrection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticSpellingCorrection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleAutomaticSpellingCorrection:"
        }
      ],
      "role": "symbol",
      "title": "toggleAutomaticSpellingCorrection(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggleautomaticspellingcorrection(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticTextReplacement(_:)": {
      "abstract": [
        {
          "text": "Toggles the state of the automatic text replacement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleAutomaticTextReplacement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticTextReplacement(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleAutomaticTextReplacement:"
        }
      ],
      "role": "symbol",
      "title": "toggleAutomaticTextReplacement(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggleautomatictextreplacement(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-and-substituting-text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInSelection(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkText(in:types:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/enabledTextCheckingTypes",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDashSubstitutionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDashSubstitution(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDataDetectionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDataDetection(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticSpellingCorrectionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticSpellingCorrection(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextReplacementEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticTextReplacement(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/performValidatedReplacement(in:with:)"
      ],
      "title": "Checking and substituting text"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "checkTextInDocument:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkTextInDocument:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-and-substituting-text",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkTextInSelection(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/checkText(in:types:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/enabledTextCheckingTypes",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDashSubstitutionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDashSubstitution(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticDataDetectionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticDataDetection(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticSpellingCorrectionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticSpellingCorrection(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextReplacementEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticTextReplacement(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/performValidatedReplacement(in:with:)"
              ],
              "title": "Checking and substituting text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "checkTextInDocument:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sender"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The control sending the message. May be ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sender"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)/title",
          "value": "handleTextCheckingResults:forRange:types:options:orthography:wordCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1handleTextCheckingResults(_:forRange:types:options:orthography:wordCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleTextCheckingResults:forRange:types:options:orthography:wordCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1checkTextInDocument(_:)/title",
          "value": "checkTextInDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1checkTextInDocument(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkTextInDocument:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1checkText(in:types:options:)/title",
          "value": "checkTextInRange:types:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1checkText(in:types:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkTextInRange:types:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticTextReplacement(_:)/title",
          "value": "toggleAutomaticTextReplacement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticTextReplacement(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleAutomaticTextReplacement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1performValidatedReplacement(in:with:)/title",
          "value": "performValidatedReplacementInRange:withAttributedString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1performValidatedReplacement(in:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performValidatedReplacementInRange:withAttributedString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticDashSubstitution(_:)/title",
          "value": "toggleAutomaticDashSubstitution:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticDashSubstitution(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleAutomaticDashSubstitution:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticDashSubstitutionEnabled/title",
          "value": "automaticDashSubstitutionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticDashSubstitutionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticDashSubstitutionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticDataDetection(_:)/title",
          "value": "toggleAutomaticDataDetection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticDataDetection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleAutomaticDataDetection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticDataDetectionEnabled/title",
          "value": "automaticDataDetectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticDataDetectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticDataDetectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticSpellingCorrection(_:)/title",
          "value": "toggleAutomaticSpellingCorrection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticSpellingCorrection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleAutomaticSpellingCorrection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1enabledTextCheckingTypes/title",
          "value": "enabledTextCheckingTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1enabledTextCheckingTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabledTextCheckingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticSpellingCorrectionEnabled/title",
          "value": "automaticSpellingCorrectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticSpellingCorrectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticSpellingCorrectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticTextReplacementEnabled/title",
          "value": "automaticTextReplacementEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticTextReplacementEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticTextReplacementEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1checkTextInSelection(_:)/title",
          "value": "checkTextInSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1checkTextInSelection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkTextInSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextview/checktextindocument(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextview/checktextindocument(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
