{
  "abstract": [
    {
      "text": "Draws the background of the text view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawBackground(in:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextView(im)drawViewBackgroundInRect:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "drawBackground"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "in"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSRect",
        "text": "NSRect"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "drawViewBackgroundInRect:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "drawBackground(in:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "drawBackground"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "in"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The rectangle in which to draw the background.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rect"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Subclasses can override this method to perform additional drawing behind the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/cleanUpAfterDragOperation()": {
      "abstract": [
        {
          "text": "Releases the drag information still existing after the dragging session has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cleanUpAfterDragOperation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/cleanUpAfterDragOperation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cleanUpAfterDragOperation"
        }
      ],
      "role": "symbol",
      "title": "cleanUpAfterDragOperation()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/cleanupafterdragoperation()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawBackground(in:)": {
      "abstract": [
        {
          "text": "Draws the background of the text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawBackground"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawBackground(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawViewBackgroundInRect:"
        }
      ],
      "role": "symbol",
      "title": "drawBackground(in:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/drawbackground(in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawInsertionPoint(in:color:turnedOn:)": {
      "abstract": [
        {
          "text": "Draws or erases the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawInsertionPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "turnedOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawInsertionPoint(in:color:turnedOn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawInsertionPointInRect:color:turnedOn:"
        }
      ],
      "role": "symbol",
      "title": "drawInsertionPoint(in:color:turnedOn:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/drawinsertionpoint(in:color:turnedon:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableDocumentContentTextView()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollableDocumentContentTextView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrollView",
          "text": "NSScrollView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableDocumentContentTextView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollableDocumentContentTextView"
        }
      ],
      "role": "symbol",
      "title": "scrollableDocumentContentTextView()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/scrollabledocumentcontenttextview()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollablePlainDocumentContentTextView()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollablePlainDocumentContentTextView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrollView",
          "text": "NSScrollView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollablePlainDocumentContentTextView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollablePlainDocumentContentTextView"
        }
      ],
      "role": "symbol",
      "title": "scrollablePlainDocumentContentTextView()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/scrollableplaindocumentcontenttextview()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableTextView()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollableTextView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrollView",
          "text": "NSScrollView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableTextView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollableTextView"
        }
      ],
      "role": "symbol",
      "title": "scrollableTextView()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/scrollabletextview()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/setConstrainedFrameSize(_:)": {
      "abstract": [
        {
          "text": "Attempts to set the frame size as if by user action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setConstrainedFrameSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/setConstrainedFrameSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setConstrainedFrameSize:"
        }
      ],
      "role": "symbol",
      "title": "setConstrainedFrameSize(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/setconstrainedframesize(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/setNeedsDisplay(_:avoidAdditionalLayout:)": {
      "abstract": [
        {
          "text": "Marks the receiver as requiring display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "avoidAdditionalLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/setNeedsDisplay(_:avoidAdditionalLayout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInRect:avoidAdditionalLayout:"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplay(_:avoidAdditionalLayout:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/setneedsdisplay(_:avoidadditionallayout:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldDrawInsertionPoint": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the receiver should draw its insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldDrawInsertionPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldDrawInsertionPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldDrawInsertionPoint"
        }
      ],
      "role": "symbol",
      "title": "shouldDrawInsertionPoint",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/shoulddrawinsertionpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/showFindIndicator(for:)": {
      "abstract": [
        {
          "text": "Causes a temporary highlighting effect to appear around the visible portion (or portions) of the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showFindIndicator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/showFindIndicator(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showFindIndicatorForRange:"
        }
      ],
      "role": "symbol",
      "title": "showFindIndicator(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/showfindindicator(for:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-text-display",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/setNeedsDisplay(_:avoidAdditionalLayout:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldDrawInsertionPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawInsertionPoint(in:color:turnedOn:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/setConstrainedFrameSize(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/cleanUpAfterDragOperation()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/showFindIndicator(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableDocumentContentTextView()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollablePlainDocumentContentTextView()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableTextView()"
      ],
      "title": "Controlling text display"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "drawViewBackgroundInRect:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawViewBackgroundInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-text-display",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/setNeedsDisplay(_:avoidAdditionalLayout:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldDrawInsertionPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/drawInsertionPoint(in:color:turnedOn:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/setConstrainedFrameSize(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/cleanUpAfterDragOperation()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/showFindIndicator(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableDocumentContentTextView()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollablePlainDocumentContentTextView()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/scrollableTextView()"
              ],
              "title": "Controlling text display"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "drawViewBackgroundInRect:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSRect",
                    "text": "NSRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rect"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The rectangle in which to draw the background.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rect"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1shouldDrawInsertionPoint/title",
          "value": "shouldDrawInsertionPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1shouldDrawInsertionPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldDrawInsertionPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1drawInsertionPoint(in:color:turnedOn:)/title",
          "value": "drawInsertionPointInRect:color:turnedOn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1drawInsertionPoint(in:color:turnedOn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawInsertionPointInRect:color:turnedOn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setNeedsDisplay(_:avoidAdditionalLayout:)/title",
          "value": "setNeedsDisplayInRect:avoidAdditionalLayout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setNeedsDisplay(_:avoidAdditionalLayout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsDisplayInRect:avoidAdditionalLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1showFindIndicator(for:)/title",
          "value": "showFindIndicatorForRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1showFindIndicator(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showFindIndicatorForRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1drawBackground(in:)/title",
          "value": "drawViewBackgroundInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1drawBackground(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawViewBackgroundInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1cleanUpAfterDragOperation()/title",
          "value": "cleanUpAfterDragOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1cleanUpAfterDragOperation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cleanUpAfterDragOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1scrollableDocumentContentTextView()/title",
          "value": "scrollableDocumentContentTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1scrollableDocumentContentTextView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "scrollableDocumentContentTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1scrollablePlainDocumentContentTextView()/title",
          "value": "scrollablePlainDocumentContentTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1scrollablePlainDocumentContentTextView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "scrollablePlainDocumentContentTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1scrollableTextView()/title",
          "value": "scrollableTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1scrollableTextView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "scrollableTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setConstrainedFrameSize(_:)/title",
          "value": "setConstrainedFrameSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setConstrainedFrameSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setConstrainedFrameSize:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextview/drawbackground(in:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextview/drawbackground(in:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
