{
  "abstract": [
    {
      "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager allow the user to import files by dragging.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextView/importsGraphics"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSTextView(py)importsGraphics",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "importsGraphics"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "importsGraphics"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "importsGraphics"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "importsGraphics"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to allow the user to import files by dragging onto the text views sharing the receiver’s layout manager, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " otherwise.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Text views that are set to accept dragged files are also set to allow rich text. By default, text views don’t accept dragged files but do allow rich text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsImageEditing": {
      "abstract": [
        {
          "text": "Indicates whether image attachments should permit editing of their images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsImageEditing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsImageEditing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsImageEditing"
        }
      ],
      "role": "symbol",
      "title": "allowsImageEditing",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/allowsimageediting"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsUndo": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the receiver allows undo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsUndo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsUndo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsUndo"
        }
      ],
      "role": "symbol",
      "title": "allowsUndo",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/allowsundo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/defaultParagraphStyle": {
      "abstract": [
        {
          "text": "The receiver’s default paragraph style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultParagraphStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/defaultParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "defaultParagraphStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/defaultparagraphstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/displaysLinkToolTips": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the text view automatically supplies the destination of a link as a tooltip for text that has a link attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displaysLinkToolTips"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/displaysLinkToolTips",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displaysLinkToolTips"
        }
      ],
      "role": "symbol",
      "title": "displaysLinkToolTips",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/displayslinktooltips"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/importsGraphics": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager allow the user to import files by dragging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "importsGraphics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/importsGraphics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "importsGraphics"
        }
      ],
      "role": "symbol",
      "title": "importsGraphics",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/importsgraphics"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticLinkDetectionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that enables or disables automatic link detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticLinkDetectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticLinkDetectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticLinkDetectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticLinkDetectionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomaticlinkdetectionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticQuoteSubstitutionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that enables and disables automatic quotation mark substitution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticQuoteSubstitutionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticQuoteSubstitutionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticQuoteSubstitutionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticQuoteSubstitutionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomaticquotesubstitutionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextCompletionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the text view supplies autocompletion suggestions as the user types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticTextCompletionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextCompletionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticTextCompletionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticTextCompletionEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isautomatictextcompletionenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager allow the user to edit text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEditable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editable"
        }
      ],
      "role": "symbol",
      "title": "isEditable",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/iseditable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isFieldEditor": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager behave as field editors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFieldEditor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isFieldEditor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fieldEditor"
        }
      ],
      "role": "symbol",
      "title": "isFieldEditor",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isfieldeditor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isRichText": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager allow the user to apply attributes to specific ranges of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRichText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isRichText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "richText"
        }
      ],
      "role": "symbol",
      "title": "isRichText",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isrichtext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isSelectable": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager allow the user to select text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSelectable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isSelectable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectable"
        }
      ],
      "role": "symbol",
      "title": "isSelectable",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/isselectable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/outline(_:)": {
      "abstract": [
        {
          "text": "Adds the outline attribute to the selected text attributes if absent; removes the attribute if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/outline(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outline:"
        }
      ],
      "role": "symbol",
      "title": "outline(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/outline(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/setBaseWritingDirection(_:range:)": {
      "abstract": [
        {
          "text": "Sets the base writing direction of a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBaseWritingDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingDirection",
          "text": "NSWritingDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/setBaseWritingDirection(_:range:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBaseWritingDirection:range:"
        }
      ],
      "role": "symbol",
      "title": "setBaseWritingDirection(_:range:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/setbasewritingdirection(_:range:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/textStorage": {
      "abstract": [
        {
          "text": "The receiver’s text storage object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextStorage",
          "text": "NSTextStorage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/textStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textStorage"
        }
      ],
      "role": "symbol",
      "title": "textStorage",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/textstorage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticLinkDetection(_:)": {
      "abstract": [
        {
          "text": "Changes the state of automatic link detection from enabled to disabled and vice versa.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleAutomaticLinkDetection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticLinkDetection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleAutomaticLinkDetection:"
        }
      ],
      "role": "symbol",
      "title": "toggleAutomaticLinkDetection(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggleautomaticlinkdetection(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticQuoteSubstitution(_:)": {
      "abstract": [
        {
          "text": "Changes the state of automatic quotation mark substitution from enabled to disabled and vice versa.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleAutomaticQuoteSubstitution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticQuoteSubstitution(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleAutomaticQuoteSubstitution:"
        }
      ],
      "role": "symbol",
      "title": "toggleAutomaticQuoteSubstitution(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggleautomaticquotesubstitution(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleBaseWritingDirection:": {
      "abstract": [
        {
          "text": "Changes the base writing direction of a paragraph between left-to-right and right-to-left.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "toggleBaseWritingDirection:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleBaseWritingDirection:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleBaseWritingDirection:"
        }
      ],
      "role": "symbol",
      "title": "toggleBaseWritingDirection:",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/togglebasewritingdirection:"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/1508376-init": {
      "abstract": [
        {
          "text": "Creates an attributed string with an attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "attachment"
        },
        {
          "kind": "text",
          "text": ": NSTextAttachment)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/1508376-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(attachment:)",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/1508376-init"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring/1414947-insert": {
      "abstract": [
        {
          "text": "Inserts the characters and attributes of the given attributed string into the receiver at the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "(NSAttributedString, "
        },
        {
          "kind": "identifier",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": Int)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring/1414947-insert",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(_:at:)",
      "type": "topic",
      "url": "/documentation/foundation/nsmutableattributedstring/1414947-insert"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring/1414947-insert",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/1508376-init",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/textStorage"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Setting-behavioral-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsUndo",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isSelectable",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isFieldEditor",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isRichText",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/setBaseWritingDirection(_:range:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/defaultParagraphStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/outline(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsImageEditing",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticQuoteSubstitutionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticQuoteSubstitution(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticLinkDetectionEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticLinkDetection(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/displaysLinkToolTips",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticTextCompletionEnabled"
      ],
      "title": "Setting behavioral attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "importsGraphics"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "importsGraphics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring/1414947-insert",
                "doc://com.apple.documentation/documentation/foundation/nsattributedstring/1508376-init",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/textStorage"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Setting-behavioral-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsUndo",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isSelectable",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isFieldEditor",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isRichText",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/setBaseWritingDirection(_:range:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleBaseWritingDirection:",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/defaultParagraphStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/outline(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/allowsImageEditing",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticQuoteSubstitutionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticQuoteSubstitution(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isAutomaticLinkDetectionEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleAutomaticLinkDetection(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/displaysLinkToolTips"
              ],
              "title": "Setting behavioral attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "importsGraphics"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticLinkDetectionEnabled/title",
          "value": "automaticLinkDetectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticLinkDetectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticLinkDetectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isFieldEditor/title",
          "value": "fieldEditor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isFieldEditor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fieldEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isEditable/title",
          "value": "editable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isEditable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setBaseWritingDirection(_:range:)/title",
          "value": "setBaseWritingDirection:range:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setBaseWritingDirection(_:range:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBaseWritingDirection:range:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticTextCompletionEnabled/title",
          "value": "automaticTextCompletionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticTextCompletionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticTextCompletionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticLinkDetection(_:)/title",
          "value": "toggleAutomaticLinkDetection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticLinkDetection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleAutomaticLinkDetection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1textStorage/title",
          "value": "textStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1textStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1displaysLinkToolTips/title",
          "value": "displaysLinkToolTips"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1displaysLinkToolTips/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displaysLinkToolTips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1outline(_:)/title",
          "value": "outline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1outline(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "outline:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1allowsImageEditing/title",
          "value": "allowsImageEditing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1allowsImageEditing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsImageEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isRichText/title",
          "value": "richText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isRichText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "richText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsattributedstring~11508376-init/title",
          "value": "attributedStringWithAttachment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1allowsUndo/title",
          "value": "allowsUndo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1allowsUndo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsUndo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsmutableattributedstring~11414947-insert/title",
          "value": "insertAttributedString:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isSelectable/title",
          "value": "selectable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isSelectable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1importsGraphics/title",
          "value": "importsGraphics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1importsGraphics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "importsGraphics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticQuoteSubstitutionEnabled/title",
          "value": "automaticQuoteSubstitutionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isAutomaticQuoteSubstitutionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticQuoteSubstitutionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticQuoteSubstitution(_:)/title",
          "value": "toggleAutomaticQuoteSubstitution:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleAutomaticQuoteSubstitution(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleAutomaticQuoteSubstitution:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1defaultParagraphStyle/title",
          "value": "defaultParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1defaultParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultParagraphStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextview/importsgraphics"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextview/importsgraphics"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
