{
  "abstract": [
    {
      "text": "The range of characters affected by a method that changes characters (as opposed to attributes).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserTextChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSTextView(py)rangeForUserTextChange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rangeForUserTextChange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "NSRange"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "rangeForUserTextChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "rangeForUserTextChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rangeForUserTextChange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the receiver isn’t editable the range has a location of ",
              "type": "text"
            },
            {
              "code": "NSNotFound",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/acceptableDragTypes": {
      "abstract": [
        {
          "text": "The data types that the receiver accepts as the destination view of a dragging operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptableDragTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/acceptableDragTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptableDragTypes"
        }
      ],
      "role": "symbol",
      "title": "acceptableDragTypes",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/acceptabledragtypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/didChangeText()": {
      "abstract": [
        {
          "text": "Sends out necessary notifications when a text change completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeText"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/didChangeText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didChangeText"
        }
      ],
      "role": "symbol",
      "title": "didChangeText()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/didchangetext()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager allow the user to edit text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEditable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editable"
        }
      ],
      "role": "symbol",
      "title": "isEditable",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/iseditable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserCharacterAttributeChange": {
      "abstract": [
        {
          "text": "The range of characters affected by an action method that changes character (not paragraph) attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeForUserCharacterAttributeChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserCharacterAttributeChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangeForUserCharacterAttributeChange"
        }
      ],
      "role": "symbol",
      "title": "rangeForUserCharacterAttributeChange",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/rangeforusercharacterattributechange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserParagraphAttributeChange": {
      "abstract": [
        {
          "text": "The range of characters affected by an action method that changes paragraph (not character) attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeForUserParagraphAttributeChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserParagraphAttributeChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangeForUserParagraphAttributeChange"
        }
      ],
      "role": "symbol",
      "title": "rangeForUserParagraphAttributeChange",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/rangeforuserparagraphattributechange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserTextChange": {
      "abstract": [
        {
          "text": "The range of characters affected by a method that changes characters (as opposed to attributes).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeForUserTextChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserTextChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangeForUserTextChange"
        }
      ],
      "role": "symbol",
      "title": "rangeForUserTextChange",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/rangeforusertextchange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserCharacterAttributeChange": {
      "abstract": [
        {
          "text": "An array containing the ranges of characters affected by an action method that changes character (not paragraph) attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangesForUserCharacterAttributeChange"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserCharacterAttributeChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangesForUserCharacterAttributeChange"
        }
      ],
      "role": "symbol",
      "title": "rangesForUserCharacterAttributeChange",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/rangesforusercharacterattributechange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserParagraphAttributeChange": {
      "abstract": [
        {
          "text": "An array containing the ranges of characters affected by a method that changes paragraph (not character) attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangesForUserParagraphAttributeChange"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserParagraphAttributeChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangesForUserParagraphAttributeChange"
        }
      ],
      "role": "symbol",
      "title": "rangesForUserParagraphAttributeChange",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/rangesforuserparagraphattributechange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserTextChange": {
      "abstract": [
        {
          "text": "An array containing the ranges of characters affected by a method that changes characters (as opposed to attributes).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangesForUserTextChange"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserTextChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangesForUserTextChange"
        }
      ],
      "role": "symbol",
      "title": "rangesForUserTextChange",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/rangesforusertextchange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)": {
      "abstract": [
        {
          "text": "Returns an adjusted selected range based on the selection granularity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "granularity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSelectionGranularity",
          "text": "NSSelectionGranularity"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionRangeForProposedRange:granularity:"
        }
      ],
      "role": "symbol",
      "title": "selectionRange(forProposedRange:granularity:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/selectionrange(forproposedrange:granularity:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(in:replacementString:)": {
      "abstract": [
        {
          "text": "Initiates a series of delegate messages (and general notifications) to determine whether modifications can be made to the characters and attributes of the receiver’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldChangeText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replacementString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(in:replacementString:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldChangeTextInRange:replacementString:"
        }
      ],
      "role": "symbol",
      "title": "shouldChangeText(in:replacementString:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/shouldchangetext(in:replacementstring:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(inRanges:replacementStrings:)": {
      "abstract": [
        {
          "text": "Initiates a series of delegate messages (and general notifications) to determine whether modifications can be made to the characters and attributes of the receiver’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldChangeText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "replacementStrings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(inRanges:replacementStrings:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldChangeTextInRanges:replacementStrings:"
        }
      ],
      "role": "symbol",
      "title": "shouldChangeText(inRanges:replacementStrings:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/shouldchangetext(inranges:replacementstrings:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartDeleteRange(forProposedRange:)": {
      "abstract": [
        {
          "text": "Returns an extended range that includes adjacent whitespace that should be deleted along with the proposed range in order to preserve proper spacing and punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartDeleteRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartDeleteRange(forProposedRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smartDeleteRangeForProposedRange:"
        }
      ],
      "role": "symbol",
      "title": "smartDeleteRange(forProposedRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/smartdeleterange(forproposedrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartInsertDeleteEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the receiver inserts or deletes space around selected words so as to preserve proper spacing and punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartInsertDeleteEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartInsertDeleteEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smartInsertDeleteEnabled"
        }
      ],
      "role": "symbol",
      "title": "smartInsertDeleteEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/smartinsertdeleteenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateDragTypeRegistration()": {
      "abstract": [
        {
          "text": "Updates the acceptable drag types of all text views associated with the receiver’s layout manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateDragTypeRegistration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateDragTypeRegistration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateDragTypeRegistration"
        }
      ],
      "role": "symbol",
      "title": "updateDragTypeRegistration()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/updatedragtyperegistration()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateFontPanel()": {
      "abstract": [
        {
          "text": "Updates the Font panel to contain the font attributes of the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateFontPanel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateFontPanel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateFontPanel"
        }
      ],
      "role": "symbol",
      "title": "updateFontPanel()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/updatefontpanel()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateRuler()": {
      "abstract": [
        {
          "text": "Updates the ruler view in the receiver’s enclosing scroll view to reflect the selection’s paragraph and marker attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateRuler"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateRuler()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateRuler"
        }
      ],
      "role": "symbol",
      "title": "updateRuler()",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/updateruler()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/usesRuler": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether the text views sharing the receiver’s layout manager use a ruler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesRuler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/usesRuler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesRuler"
        }
      ],
      "role": "symbol",
      "title": "usesRuler",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/usesruler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/usesRuler",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Customizing-subclass-behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateFontPanel()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateRuler()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/acceptableDragTypes",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateDragTypeRegistration()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserCharacterAttributeChange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserCharacterAttributeChange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserParagraphAttributeChange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserParagraphAttributeChange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserTextChange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(in:replacementString:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(inRanges:replacementStrings:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/didChangeText()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartInsertDeleteEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartDeleteRange(forProposedRange:)"
      ],
      "title": "Customizing subclass behaviors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "rangeForUserTextChange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangeForUserTextChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/usesRuler",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/isEditable"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Customizing-subclass-behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateFontPanel()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateRuler()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/acceptableDragTypes",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/updateDragTypeRegistration()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserCharacterAttributeChange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserCharacterAttributeChange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangeForUserParagraphAttributeChange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserParagraphAttributeChange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/rangesForUserTextChange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(in:replacementString:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/shouldChangeText(inRanges:replacementStrings:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/didChangeText()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartInsertDeleteEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/smartDeleteRange(forProposedRange:)"
              ],
              "title": "Customizing subclass behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@_NSRange",
                    "text": "NSRange"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "rangeForUserTextChange"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1updateRuler()/title",
          "value": "updateRuler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1updateRuler()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateRuler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1usesRuler/title",
          "value": "usesRuler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1usesRuler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesRuler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1shouldChangeText(in:replacementString:)/title",
          "value": "shouldChangeTextInRange:replacementString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1shouldChangeText(in:replacementString:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldChangeTextInRange:replacementString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangesForUserCharacterAttributeChange/title",
          "value": "rangesForUserCharacterAttributeChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangesForUserCharacterAttributeChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangesForUserCharacterAttributeChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1smartInsertDeleteEnabled/title",
          "value": "smartInsertDeleteEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1smartInsertDeleteEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smartInsertDeleteEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1shouldChangeText(inRanges:replacementStrings:)/title",
          "value": "shouldChangeTextInRanges:replacementStrings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1shouldChangeText(inRanges:replacementStrings:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldChangeTextInRanges:replacementStrings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangesForUserParagraphAttributeChange/title",
          "value": "rangesForUserParagraphAttributeChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangesForUserParagraphAttributeChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangesForUserParagraphAttributeChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangeForUserParagraphAttributeChange/title",
          "value": "rangeForUserParagraphAttributeChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangeForUserParagraphAttributeChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangeForUserParagraphAttributeChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionRange(forProposedRange:granularity:)/title",
          "value": "selectionRangeForProposedRange:granularity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionRange(forProposedRange:granularity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectionRangeForProposedRange:granularity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangeForUserCharacterAttributeChange/title",
          "value": "rangeForUserCharacterAttributeChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangeForUserCharacterAttributeChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangeForUserCharacterAttributeChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1smartDeleteRange(forProposedRange:)/title",
          "value": "smartDeleteRangeForProposedRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1smartDeleteRange(forProposedRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "smartDeleteRangeForProposedRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangesForUserTextChange/title",
          "value": "rangesForUserTextChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangesForUserTextChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangesForUserTextChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1didChangeText()/title",
          "value": "didChangeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1didChangeText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didChangeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1updateDragTypeRegistration()/title",
          "value": "updateDragTypeRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1updateDragTypeRegistration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateDragTypeRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isEditable/title",
          "value": "editable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1isEditable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1updateFontPanel()/title",
          "value": "updateFontPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1updateFontPanel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateFontPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangeForUserTextChange/title",
          "value": "rangeForUserTextChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1rangeForUserTextChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangeForUserTextChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1acceptableDragTypes/title",
          "value": "acceptableDragTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1acceptableDragTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptableDragTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextview/rangeforusertextchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextview/rangeforusertextchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
