{
  "abstract": [
    {
      "text": "Sets the receiver to use all ligatures available for the fonts and languages used when setting text, for the glyphs in the selection if the receiver is a rich text view, or for all glyphs if it’s a plain text view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextView/useAllLigatures(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextView(im)useAllLigatures:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "useAllLigatures"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "useAllLigatures:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "useAllLigatures(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "useAllLigatures"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sender"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The control that sent the message; may be ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sender"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/alignJustified(_:)": {
      "abstract": [
        {
          "text": "Applies full justification to selected paragraphs (or all text, if the receiver is a plain text object).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignJustified"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/alignJustified(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alignJustified:"
        }
      ],
      "role": "symbol",
      "title": "alignJustified(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/alignjustified(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeAttributes(_:)": {
      "abstract": [
        {
          "text": "Changes the attributes of the current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeAttributes:"
        }
      ],
      "role": "symbol",
      "title": "changeAttributes(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/changeattributes(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeColor(_:)": {
      "abstract": [
        {
          "text": "Sets the color of the selected text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeColor:"
        }
      ],
      "role": "symbol",
      "title": "changeColor(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/changecolor(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/loosenKerning(_:)": {
      "abstract": [
        {
          "text": "Increases the space between glyphs in the receiver’s selection, or in all text if the receiver is a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loosenKerning"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/loosenKerning(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loosenKerning:"
        }
      ],
      "role": "symbol",
      "title": "loosenKerning(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/loosenkerning(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/lowerBaseline(_:)": {
      "abstract": [
        {
          "text": "Lowers the baseline offset of selected text by 1 point, or of all text if the receiver is a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowerBaseline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/lowerBaseline(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowerBaseline:"
        }
      ],
      "role": "symbol",
      "title": "lowerBaseline(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/lowerbaseline(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/raiseBaseline(_:)": {
      "abstract": [
        {
          "text": "Raises the baseline offset of selected text by 1 point, or of all text if the receiver is a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBaseline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/raiseBaseline(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "raiseBaseline:"
        }
      ],
      "role": "symbol",
      "title": "raiseBaseline(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/raisebaseline(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/setAlignment(_:range:)": {
      "abstract": [
        {
          "text": "Sets the alignment of the paragraphs containing characters in the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAlignment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextAlignment",
          "text": "NSTextAlignment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/setAlignment(_:range:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAlignment:range:"
        }
      ],
      "role": "symbol",
      "title": "setAlignment(_:range:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/setalignment(_:range:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/tightenKerning(_:)": {
      "abstract": [
        {
          "text": "Decreases the space between glyphs in the receiver’s selection, or for all glyphs if the receiver is a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tightenKerning"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/tightenKerning(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tightenKerning:"
        }
      ],
      "role": "symbol",
      "title": "tightenKerning(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/tightenkerning(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleTraditionalCharacterShape(_:)": {
      "abstract": [
        {
          "text": "Toggles the ",
          "type": "text"
        },
        {
          "code": "NSCharacterShapeAttributeName",
          "type": "codeVoice"
        },
        {
          "text": " attribute at the current selection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleTraditionalCharacterShape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleTraditionalCharacterShape(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleTraditionalCharacterShape:"
        }
      ],
      "role": "symbol",
      "title": "toggleTraditionalCharacterShape(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/toggletraditionalcharactershape(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffKerning(_:)": {
      "abstract": [
        {
          "text": "Sets the receiver to use nominal glyph spacing for the glyphs in its selection, or for all glyphs if the receiver is a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnOffKerning"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffKerning(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "turnOffKerning:"
        }
      ],
      "role": "symbol",
      "title": "turnOffKerning(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/turnoffkerning(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffLigatures(_:)": {
      "abstract": [
        {
          "text": "Sets the receiver to use only required ligatures when setting text, for the glyphs in the selection if the receiver is a rich text view, or for all glyphs if it’s a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnOffLigatures"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffLigatures(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "turnOffLigatures:"
        }
      ],
      "role": "symbol",
      "title": "turnOffLigatures(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/turnoffligatures(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/typingAttributes": {
      "abstract": [
        {
          "text": "The receiver’s typing attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typingAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/typingAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typingAttributes"
        }
      ],
      "role": "symbol",
      "title": "typingAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/typingattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/useAllLigatures(_:)": {
      "abstract": [
        {
          "text": "Sets the receiver to use all ligatures available for the fonts and languages used when setting text, for the glyphs in the selection if the receiver is a rich text view, or for all glyphs if it’s a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useAllLigatures"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/useAllLigatures(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useAllLigatures:"
        }
      ],
      "role": "symbol",
      "title": "useAllLigatures(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/useallligatures(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardKerning(_:)": {
      "abstract": [
        {
          "text": "Set the receiver to use pair kerning data for the glyphs in its selection, or for all glyphs if the receiver is a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useStandardKerning"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardKerning(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useStandardKerning:"
        }
      ],
      "role": "symbol",
      "title": "useStandardKerning(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/usestandardkerning(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardLigatures(_:)": {
      "abstract": [
        {
          "text": "Sets the receiver to use the standard ligatures available for the fonts and languages used when setting text, for the glyphs in the selection if the receiver is a rich text view, or for all glyphs if it’s a plain text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useStandardLigatures"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardLigatures(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useStandardLigatures:"
        }
      ],
      "role": "symbol",
      "title": "useStandardLigatures(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/usestandardligatures(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-text-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/alignJustified(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeAttributes(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeColor(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/setAlignment(_:range:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/typingAttributes",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardKerning(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/lowerBaseline(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/raiseBaseline(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffKerning(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/loosenKerning(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/tightenKerning(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardLigatures(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffLigatures(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleTraditionalCharacterShape(_:)"
      ],
      "title": "Setting text attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "useAllLigatures:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "useAllLigatures:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-text-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/alignJustified(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeAttributes(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/changeColor(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/setAlignment(_:range:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/typingAttributes",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardKerning(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/lowerBaseline(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/raiseBaseline(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffKerning(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/loosenKerning(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/tightenKerning(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/useStandardLigatures(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/turnOffLigatures(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView/toggleTraditionalCharacterShape(_:)"
              ],
              "title": "Setting text attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "useAllLigatures:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sender"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The control that sent the message; may be ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sender"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1changeColor(_:)/title",
          "value": "changeColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1changeColor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1useStandardKerning(_:)/title",
          "value": "useStandardKerning:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1useStandardKerning(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "useStandardKerning:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1useStandardLigatures(_:)/title",
          "value": "useStandardLigatures:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1useStandardLigatures(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "useStandardLigatures:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1turnOffKerning(_:)/title",
          "value": "turnOffKerning:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1turnOffKerning(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "turnOffKerning:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleTraditionalCharacterShape(_:)/title",
          "value": "toggleTraditionalCharacterShape:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1toggleTraditionalCharacterShape(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleTraditionalCharacterShape:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1changeAttributes(_:)/title",
          "value": "changeAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1changeAttributes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1tightenKerning(_:)/title",
          "value": "tightenKerning:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1tightenKerning(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tightenKerning:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1useAllLigatures(_:)/title",
          "value": "useAllLigatures:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1useAllLigatures(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "useAllLigatures:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1loosenKerning(_:)/title",
          "value": "loosenKerning:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1loosenKerning(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loosenKerning:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1alignJustified(_:)/title",
          "value": "alignJustified:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1alignJustified(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "alignJustified:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1typingAttributes/title",
          "value": "typingAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1typingAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typingAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1turnOffLigatures(_:)/title",
          "value": "turnOffLigatures:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1turnOffLigatures(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "turnOffLigatures:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setAlignment(_:range:)/title",
          "value": "setAlignment:range:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setAlignment(_:range:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAlignment:range:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1raiseBaseline(_:)/title",
          "value": "raiseBaseline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1raiseBaseline(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "raiseBaseline:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1lowerBaseline(_:)/title",
          "value": "lowerBaseline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1lowerBaseline(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lowerBaseline:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextview/useallligatures(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextview/useallligatures(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
