{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "deprecated",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "deprecated",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/internalError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC14GKSessionErrorLeV08internalB0SoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "internalError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC14GKSessionErrorLeV",
        "text": "GKSessionError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@GKSessionError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "9.0",
        "message": "No longer supported",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "3.0",
        "message": "No longer supported",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "internalError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "internalError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC14GKSessionErrorLeV",
              "text": "GKSessionError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKSessionError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the session error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/cancelledError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/cancelledError",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancelledError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/cancellederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/cannotEnableError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotEnableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/cannotEnableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "cannotEnableError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/cannotenableerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectionClosedError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionClosedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectionClosedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionClosedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/connectionclosederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectionFailedError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectionFailedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionFailedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/connectionfailederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectivityError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectivityError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectivityError",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectivityError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/connectivityerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/dataTooBigError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataTooBigError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/dataTooBigError",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataTooBigError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/datatoobigerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/declinedError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declinedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/declinedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "declinedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/declinederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/inProgressError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgressError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/inProgressError",
      "kind": "symbol",
      "role": "symbol",
      "title": "inProgressError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/inprogresserror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/internalError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/internalerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/invalidParameterError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/invalidParameterError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameterError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/invalidparametererror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/notConnectedError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnectedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/notConnectedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "notConnectedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/notconnectederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/peerNotFoundError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerNotFoundError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/peerNotFoundError",
      "kind": "symbol",
      "role": "symbol",
      "title": "peerNotFoundError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/peernotfounderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/systemError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/systemError",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/systemerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/timedOutError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOutError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/timedOutError",
      "kind": "symbol",
      "role": "symbol",
      "title": "timedOutError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/timedouterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/transportError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/transportError",
      "kind": "symbol",
      "role": "symbol",
      "title": "transportError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/transporterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/unknownError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14GKSessionErrorLeV",
          "text": "GKSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKSessionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/unknownerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/cancelledError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/cannotEnableError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectionClosedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectionFailedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/connectivityError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/dataTooBigError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/declinedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/inProgressError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/invalidParameterError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/notConnectedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/peerNotFoundError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/systemError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/timedOutError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/transportError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/unknownError"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/title",
          "value": "GKSessionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gksessionerror-swift.struct/internalerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
