{
  "abstract": [
    {
      "text": "A list of options that define the type of statistical calculations performed and the way in which HealthKit merges data from multiple sources.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/options"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9HealthKit37HKStatisticsCollectionQueryDescriptorV7optionsSo0C7OptionsVvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@HKStatisticsOptions",
        "text": "HKStatisticsOptions"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "options"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@HKStatisticsOptions",
              "text": "HKStatisticsOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor": {
      "abstract": [
        {
          "text": "A query descriptor that gathers a collection of statistics calculated over a series of fixed-length time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollectionQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/anchorDate": {
      "abstract": [
        {
          "text": "The date that anchors the collection’s time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/anchorDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "anchorDate",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/anchordate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/intervalComponents": {
      "abstract": [
        {
          "text": "The date components that define the time interval for each statistics object in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intervalComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/intervalComponents",
      "kind": "symbol",
      "role": "symbol",
      "title": "intervalComponents",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/intervalcomponents"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/options": {
      "abstract": [
        {
          "text": "A list of options that define the type of statistical calculations performed and the way in which HealthKit merges data from multiple sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKStatisticsOptions",
          "text": "HKStatisticsOptions"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/options",
      "kind": "symbol",
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/options"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/predicate": {
      "abstract": [
        {
          "text": "A predicate that defines the set of data that the query uses to calculate the statistics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantitySample",
          "text": "HKQuantitySample"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/predicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "predicate",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/predicate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions": {
      "abstract": [
        {
          "text": "Options for specifying the statistic to calculate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsOptions"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsOptions"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsOptions",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticsoptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Query-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/predicate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/anchorDate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/intervalComponents"
      ],
      "title": "Accessing Query Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/title",
          "value": "HKStatisticsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkstatisticscollectionquerydescriptor/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
