{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSError/statusOperationPaused"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11FSErrorCodeLeV21statusOperationPausedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "statusOperationPaused"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11FSErrorCodeLeV",
        "text": "FSError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@FSErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "statusOperationPaused"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "statusOperationPaused"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11FSErrorCodeLeV",
              "text": "FSError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@FSErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSError": {
      "abstract": [
        {
          "text": "An error encountered when performing an FSKit operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSError"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSError"
        }
      ],
      "role": "symbol",
      "title": "FSError",
      "type": "topic",
      "url": "/documentation/fskit/fserror"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code": {
      "abstract": [
        {
          "text": "A code that indicates a specific FSKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code"
    },
    "doc://FSKit/documentation/FSKit/FSError/invalidDirectoryCookie": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDirectoryCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/invalidDirectoryCookie",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidDirectoryCookie",
      "type": "topic",
      "url": "/documentation/fskit/fserror/invaliddirectorycookie"
    },
    "doc://FSKit/documentation/FSKit/FSError/moduleLoadFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moduleLoadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/moduleLoadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "moduleLoadFailed",
      "type": "topic",
      "url": "/documentation/fskit/fserror/moduleloadfailed"
    },
    "doc://FSKit/documentation/FSKit/FSError/resourceDamaged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceDamaged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/resourceDamaged",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceDamaged",
      "type": "topic",
      "url": "/documentation/fskit/fserror/resourcedamaged"
    },
    "doc://FSKit/documentation/FSKit/FSError/resourceUnrecognized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUnrecognized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/resourceUnrecognized",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceUnrecognized",
      "type": "topic",
      "url": "/documentation/fskit/fserror/resourceunrecognized"
    },
    "doc://FSKit/documentation/FSKit/FSError/resourceUnusable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUnusable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/resourceUnusable",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceUnusable",
      "type": "topic",
      "url": "/documentation/fskit/fserror/resourceunusable"
    },
    "doc://FSKit/documentation/FSKit/FSError/statusOperationInProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOperationInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/statusOperationInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "statusOperationInProgress",
      "type": "topic",
      "url": "/documentation/fskit/fserror/statusoperationinprogress"
    },
    "doc://FSKit/documentation/FSKit/FSError/statusOperationPaused": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOperationPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/statusOperationPaused",
      "kind": "symbol",
      "role": "symbol",
      "title": "statusOperationPaused",
      "type": "topic",
      "url": "/documentation/fskit/fserror/statusoperationpaused"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-errors",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSError/invalidDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSError/moduleLoadFailed",
        "doc://FSKit/documentation/FSKit/FSError/resourceDamaged",
        "doc://FSKit/documentation/FSKit/FSError/resourceUnrecognized",
        "doc://FSKit/documentation/FSKit/FSError/resourceUnusable",
        "doc://FSKit/documentation/FSKit/FSError/statusOperationInProgress"
      ],
      "title": "Identifying errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/title",
          "value": "FSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fserror/statusoperationpaused"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
