{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-9bvga"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIViewController(py)contentUnavailableConfigurationState",
    "fragments": [
      {
        "kind": "identifier",
        "text": "contentUnavailableConfigurationState"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "contentUnavailableConfigurationState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "contentUnavailableConfigurationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIContentUnavailableConfigurationState",
              "text": "UIContentUnavailableConfigurationState"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "contentUnavailableConfigurationState"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class": {
      "abstract": [
        {
          "text": "An object that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-6kqfk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-6kqfk",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfiguration-6kqfk"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-9bvga": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-9bvga",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfigurationstate-9bvga"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsUpdateContentUnavailableConfiguration()": {
      "abstract": [
        {
          "text": "Requests that the system update the content-unavailable configuration for the latest state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsUpdateContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsUpdateContentUnavailableConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsUpdateContentUnavailableConfiguration"
        }
      ],
      "role": "symbol",
      "title": "setNeedsUpdateContentUnavailableConfiguration()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/setneedsupdatecontentunavailableconfiguration()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:": {
      "abstract": [
        {
          "text": "Updates the content-unavailable configuration for the provided state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfigurationUsingState:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfigurationUsingState:"
        }
      ],
      "role": "symbol",
      "title": "updateContentUnavailableConfigurationUsingState:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/updatecontentunavailableconfigurationusingstate:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Indicating-missing-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-6kqfk",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsUpdateContentUnavailableConfiguration()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class"
      ],
      "title": "Indicating missing content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setNeedsUpdateContentUnavailableConfiguration()/title",
          "value": "setNeedsUpdateContentUnavailableConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setNeedsUpdateContentUnavailableConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsUpdateContentUnavailableConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller/contentunavailableconfigurationstate-9bvga"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
