{
  "abstract": [
    {
      "text": "Registers a view controller to participate with 3D Touch preview (peek) and commit (pop).",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIViewController(im)registerForPreviewingWithDelegate:sourceView:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "registerForPreviewing"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewingDelegate",
        "text": "UIViewControllerPreviewingDelegate"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "sourceView"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIView",
        "text": "UIView"
      },
      {
        "kind": "text",
        "text": ") -> any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
        "text": "UIViewControllerPreviewing"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "registerForPreviewingWithDelegate:sourceView:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "UIViewControllerPreviewing is deprecated. Please use UIContextMenuInteraction.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "UIViewControllerPreviewing is deprecated. Please use UIContextMenuInteraction.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "UIViewControllerPreviewing is deprecated. Please use UIContextMenuInteraction.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "UIViewControllerPreviewing is deprecated. Please use UIContextMenuInteraction.",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "registerForPreviewing(with:sourceView:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "registerForPreviewing"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewingDelegate",
              "text": "UIViewControllerPreviewingDelegate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "sourceView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": ") -> any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
              "text": "UIViewControllerPreviewing"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The delegate object mediates the presentation of views from the preview (peek) view controller and the commit (pop) view controller. In practice, these two are typically the same view controller. The delegate performs this mediation through your implementation of the methods of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "delegate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view, in the view hierarchy of the receiver of this method call, that invokes a preview when pressed by the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "When lightly pressed, the source view remains visually sharp while surrounding content blurs. When pressed more deeply, the system calls the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method in your ",
                  "type": "text"
                },
                {
                  "code": "delegate",
                  "type": "codeVoice"
                },
                {
                  "text": " object, which presents the preview (peek) view from another view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sourceView"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A context object for managing the preview. This object conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A preview, or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "peek",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " in end-user terminology, provides additional content related to the view the user pressed (that is, related to the ",
              "type": "text"
            },
            {
              "code": "sourceView",
              "type": "codeVoice"
            },
            {
              "text": " view).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Calling this method does three things:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Registers the previewing view controller (the one that receives this method call) to participate with 3D Touch preview and commit",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Designates the source view, from the receiver’s view hierarchy, as the view to respond to a forceful touch",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Designates a delegate object for mediating the presentation of the preview (peek) and commit (pop) views as a user requests them in turn by pressing more deeply",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can designate more than one source view for a single registered view controller, but you cannot designate a single view as a source view more than once.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The lifetime of this method’s returned context object is managed by the system. If you need to explicitly unregister a view controller, pass its context object to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. If you do not unregister a view controller, the system automatically unregisters it when the view controller is deallocated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction": {
      "abstract": [
        {
          "text": "An interaction object that you use to display relevant actions for your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()": {
      "abstract": [
        {
          "text": "Attempts to rotate all windows to the orientation of the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptRotationToDeviceOrientation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attemptRotationToDeviceOrientation"
        }
      ],
      "role": "symbol",
      "title": "attemptRotationToDeviceOrientation()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/attemptrotationtodeviceorientation()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether appearance and rotation methods are forwarded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers"
        }
      ],
      "role": "symbol",
      "title": "automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/automaticallyforwardappearanceandrotationmethodstochildviewcontrollers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)": {
      "abstract": [
        {
          "text": "Called on a view controller to determine whether it wants to respond to an unwind action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformUnwindSegueAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformUnwindSegueAction:fromViewController:withSender:"
        }
      ],
      "role": "symbol",
      "title": "canPerformUnwindSegueAction(_:from:withSender:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/canperformunwindsegueaction(_:from:withsender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/didAnimateFirstHalfOfRotationToInterfaceOrientation:": {
      "abstract": [
        {
          "text": "Sent to the view controller after the completion of the first half of the user interface rotation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "didAnimateFirstHalfOfRotationToInterfaceOrientation:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/didAnimateFirstHalfOfRotationToInterfaceOrientation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didAnimateFirstHalfOfRotationToInterfaceOrientation:"
        }
      ],
      "role": "symbol",
      "title": "didAnimateFirstHalfOfRotationToInterfaceOrientation:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/didanimatefirsthalfofrotationtointerfaceorientation:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)": {
      "abstract": [
        {
          "text": "Sent to the view controller after the user interface rotates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didRotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didRotateFromInterfaceOrientation:"
        }
      ],
      "role": "symbol",
      "title": "didRotate(from:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/didrotate(from:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissModalViewControllerAnimated:": {
      "abstract": [
        {
          "text": "Dismisses the view controller that was presented by the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dismissModalViewControllerAnimated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissModalViewControllerAnimated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissModalViewControllerAnimated:"
        }
      ],
      "role": "symbol",
      "title": "dismissModalViewControllerAnimated:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/dismissmodalviewcontrolleranimated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()": {
      "abstract": [
        {
          "text": "Dismisses a movie player view controller using the standard movie player transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissMoviePlayerViewControllerAnimated"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissMoviePlayerViewControllerAnimated"
        }
      ],
      "role": "symbol",
      "title": "dismissMoviePlayerViewControllerAnimated()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/dismissmovieplayerviewcontrolleranimated()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)": {
      "abstract": [
        {
          "text": "Called when an unwind segue action wants to search a container’s children for a view controller to handle the unwind action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forUnwindSegueAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerForUnwindSegueAction:fromViewController:withSender:"
        }
      ],
      "role": "symbol",
      "title": "forUnwindSegueAction(_:from:withSender:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/forunwindsegueaction(_:from:withsender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)": {
      "abstract": [
        {
          "text": "Retrieves the trait collection for a child view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideTraitCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overrideTraitCollectionForChildViewController:"
        }
      ],
      "role": "symbol",
      "title": "overrideTraitCollection(forChild:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/overridetraitcollection(forchild:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentModalViewController:animated:": {
      "abstract": [
        {
          "text": "Presents a modal view managed by the given view controller to the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "presentModalViewController:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentModalViewController:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentModalViewController:animated:"
        }
      ],
      "role": "symbol",
      "title": "presentModalViewController:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/presentmodalviewcontroller:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)": {
      "abstract": [
        {
          "text": "Presents the movie player view controller using the standard movie player transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentMoviePlayerViewControllerAnimated"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMoviePlayerViewController",
          "text": "MPMoviePlayerViewController"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentMoviePlayerViewControllerAnimated:"
        }
      ],
      "role": "symbol",
      "title": "presentMoviePlayerViewControllerAnimated(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/presentmovieplayerviewcontrolleranimated(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)": {
      "abstract": [
        {
          "text": "Registers a view controller to participate with 3D Touch preview (peek) and commit (pop).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForPreviewing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewingDelegate",
          "text": "UIViewControllerPreviewingDelegate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForPreviewingWithDelegate:sourceView:"
        }
      ],
      "role": "symbol",
      "title": "registerForPreviewing(with:sourceView:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/registerforpreviewing(with:sourceview:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()": {
      "abstract": [
        {
          "text": "Returns the footer view to transition during an interface orientation change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotatingFooterView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatingFooterView"
        }
      ],
      "role": "symbol",
      "title": "rotatingFooterView()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/rotatingfooterview()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()": {
      "abstract": [
        {
          "text": "Returns the header view to transition during an interface orientation change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotatingHeaderView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatingHeaderView"
        }
      ],
      "role": "symbol",
      "title": "rotatingHeaderView()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/rotatingheaderview()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)": {
      "abstract": [
        {
          "text": "Called when an unwind segue action needs to transition between two view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segueForUnwinding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIStoryboardSegue",
          "text": "UIStoryboardSegue"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segueForUnwindingToViewController:fromViewController:identifier:"
        }
      ],
      "role": "symbol",
      "title": "segueForUnwinding(to:from:identifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/segueforunwinding(to:from:identifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)": {
      "abstract": [
        {
          "text": "Changes the traits assigned to the specified child view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOverrideTraitCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOverrideTraitCollection:forChildViewController:"
        }
      ],
      "role": "symbol",
      "title": "setOverrideTraitCollection(_:forChild:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/setoverridetraitcollection(_:forchild:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether rotation methods are forwarded to child view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldAutomaticallyForwardRotationMethods"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAutomaticallyForwardRotationMethods"
        }
      ],
      "role": "symbol",
      "title": "shouldAutomaticallyForwardRotationMethods()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/shouldautomaticallyforwardrotationmethods()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)": {
      "abstract": [
        {
          "text": "Unregisters a previously registered view controller identified by its context object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterForPreviewing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContext"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unregisterForPreviewingWithContext:"
        }
      ],
      "role": "symbol",
      "title": "unregisterForPreviewing(withContext:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/unregisterforpreviewing(withcontext:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)": {
      "abstract": [
        {
          "text": "Sent to the view controller before performing a one-step user interface rotation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willAnimateRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willAnimateRotationToInterfaceOrientation:duration:"
        }
      ],
      "role": "symbol",
      "title": "willAnimateRotation(to:duration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/willanimaterotation(to:duration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)": {
      "abstract": [
        {
          "text": "Sent to the view controller just before the user interface begins rotating.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willRotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willRotateToInterfaceOrientation:duration:"
        }
      ],
      "role": "symbol",
      "title": "willRotate(to:duration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/willrotate(to:duration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing": {
      "abstract": [
        {
          "text": "A set of methods that define the interface for configuring a previewing view controller on devices that support 3D Touch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewing"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerPreviewing",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewing"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate": {
      "abstract": [
        {
          "text": "A set of methods used by the delegate to respond, with a preview view controller and a commit view controller, to the user pressing a view object on the screen of a device that supports 3D Touch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewingDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewingDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerPreviewingDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewingdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)": {
      "abstract": [
        {
          "text": "Called when the user has pressed a source view in a previewing view controller, thereby obtaining a surrounding blur to indicate that a preview (peek) is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewingContext"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewControllerForLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewingContext:viewControllerForLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "previewingContext(_:viewControllerForLocation:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewingdelegate/previewingcontext(_:viewcontrollerforlocation:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)"
      ],
      "title": "Deprecated methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "registerForPreviewingWithDelegate:sourceView:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForPreviewingWithDelegate:sourceView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/didAnimateFirstHalfOfRotationToInterfaceOrientation:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissModalViewControllerAnimated:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentModalViewController:animated:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()"
              ],
              "title": "Deprecated methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)UIViewControllerPreviewing",
                    "text": "id<UIViewControllerPreviewing>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "registerForPreviewingWithDelegate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)UIViewControllerPreviewingDelegate",
                    "text": "id<UIViewControllerPreviewingDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "delegate"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sourceView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIView",
                    "text": "UIView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sourceView"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The delegate object mediates the presentation of views from the preview (peek) view controller and the commit (pop) view controller. In practice, these two are typically the same view controller. The delegate performs this mediation through your implementation of the methods of the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " protocol.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "delegate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The view, in the view hierarchy of the receiver of this method call, that invokes a preview when pressed by the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "When lightly pressed, the source view remains visually sharp while surrounding content blurs. When pressed more deeply, the system calls the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " method in your ",
                        "type": "text"
                      },
                      {
                        "code": "delegate",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object, which presents the preview (peek) view from another view controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sourceView"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A context object for managing the preview. This object conforms to the ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " protocol.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willRotate(to:duration:)/title",
          "value": "willRotateToInterfaceOrientation:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willRotate(to:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willRotateToInterfaceOrientation:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1registerForPreviewing(with:sourceView:)/title",
          "value": "registerForPreviewingWithDelegate:sourceView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1registerForPreviewing(with:sourceView:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForPreviewingWithDelegate:sourceView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1forUnwindSegueAction(_:from:withSender:)/title",
          "value": "viewControllerForUnwindSegueAction:fromViewController:withSender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1forUnwindSegueAction(_:from:withSender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForUnwindSegueAction:fromViewController:withSender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1unregisterForPreviewing(withContext:)/title",
          "value": "unregisterForPreviewingWithContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1unregisterForPreviewing(withContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unregisterForPreviewingWithContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1segueForUnwinding(to:from:identifier:)/title",
          "value": "segueForUnwindingToViewController:fromViewController:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1segueForUnwinding(to:from:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "segueForUnwindingToViewController:fromViewController:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1dismissMoviePlayerViewControllerAnimated()/title",
          "value": "dismissMoviePlayerViewControllerAnimated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1dismissMoviePlayerViewControllerAnimated()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissMoviePlayerViewControllerAnimated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1didRotate(from:)/title",
          "value": "didRotateFromInterfaceOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1didRotate(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didRotateFromInterfaceOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate~1previewingContext(_:viewControllerForLocation:)/title",
          "value": "previewingContext:viewControllerForLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate~1previewingContext(_:viewControllerForLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewingContext:viewControllerForLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewing/title",
          "value": "UIViewControllerPreviewing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1attemptRotationToDeviceOrientation()/title",
          "value": "attemptRotationToDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1attemptRotationToDeviceOrientation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attemptRotationToDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1canPerformUnwindSegueAction(_:from:withSender:)/title",
          "value": "canPerformUnwindSegueAction:fromViewController:withSender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1canPerformUnwindSegueAction(_:from:withSender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformUnwindSegueAction:fromViewController:withSender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1overrideTraitCollection(forChild:)/title",
          "value": "overrideTraitCollectionForChildViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1overrideTraitCollection(forChild:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "overrideTraitCollectionForChildViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1presentMoviePlayerViewControllerAnimated(_:)/title",
          "value": "presentMoviePlayerViewControllerAnimated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1presentMoviePlayerViewControllerAnimated(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentMoviePlayerViewControllerAnimated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setOverrideTraitCollection(_:forChild:)/title",
          "value": "setOverrideTraitCollection:forChildViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setOverrideTraitCollection(_:forChild:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setOverrideTraitCollection:forChildViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingFooterView()/title",
          "value": "rotatingFooterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingFooterView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotatingFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/title",
          "value": "UIContextMenuInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate/title",
          "value": "UIViewControllerPreviewingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1shouldAutomaticallyForwardRotationMethods()/title",
          "value": "shouldAutomaticallyForwardRotationMethods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1shouldAutomaticallyForwardRotationMethods()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldAutomaticallyForwardRotationMethods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingHeaderView()/title",
          "value": "rotatingHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingHeaderView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotatingHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willAnimateRotation(to:duration:)/title",
          "value": "willAnimateRotationToInterfaceOrientation:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willAnimateRotation(to:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willAnimateRotationToInterfaceOrientation:duration:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller/registerforpreviewing(with:sourceview:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller/registerforpreviewing(with:sourceview:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
