{
  "abstract": [
    {
      "text": "Returns the view controller that responds to the action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewController/targetViewController(forAction:sender:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIViewController(im)targetViewControllerForAction:sender:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "targetViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "forAction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10ObjectiveC8SelectorV",
        "text": "Selector"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "sender"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIViewController",
        "text": "UIViewController"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "targetViewControllerForAction:sender:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "targetViewController(forAction:sender:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "targetViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "forAction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10ObjectiveC8SelectorV",
              "text": "Selector"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "sender"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The requested action.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "action"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object sending the request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sender"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The view controller that handles the specified action or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no view controller handles the action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method returns the current view controller if that view controller overrides the method indicated by the ",
              "type": "text"
            },
            {
              "code": "action",
              "type": "codeVoice"
            },
            {
              "text": " parameter. If the current view controller does not override that method, UIKit walks up the view hierarchy and returns the first view controller that does override it. If no view controller handles the action, this method returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A view controller can selectively respond to an action by returning an appropriate value from its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/canPerformAction(_:withSender:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResponder/canPerformAction(_:withSender:)": {
      "abstract": [
        {
          "text": "Requests the receiving responder to enable or disable the specified command in the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/canPerformAction(_:withSender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformAction:withSender:"
        }
      ],
      "role": "symbol",
      "title": "canPerformAction(_:withSender:)",
      "type": "topic",
      "url": "/documentation/uikit/uiresponder/canperformaction(_:withsender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/activePresentationController": {
      "abstract": [
        {
          "text": "The presentation controller that’s managing the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePresentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPresentationController",
          "text": "UIPresentationController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/activePresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activePresentationController"
        }
      ],
      "role": "symbol",
      "title": "activePresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/activepresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController": {
      "abstract": [
        {
          "text": "The nearest popover presentation controller that is managing the current view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverPresentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverPresentationController",
          "text": "UIPopoverPresentationController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverPresentationController"
        }
      ],
      "role": "symbol",
      "title": "popoverPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/popoverpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentationController": {
      "abstract": [
        {
          "text": "The presentation controller that’s managing the current view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPresentationController",
          "text": "UIPresentationController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationController"
        }
      ],
      "role": "symbol",
      "title": "presentationController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/presentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/restoresFocusAfterTransition": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an item that previously was focused should again become focused when the item’s view controller becomes visible and focusable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoresFocusAfterTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/restoresFocusAfterTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restoresFocusAfterTransition"
        }
      ],
      "role": "symbol",
      "title": "restoresFocusAfterTransition",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/restoresfocusaftertransition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/sheetPresentationController": {
      "abstract": [
        {
          "text": "The sheet presentation controller for the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheetPresentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISheetPresentationController",
          "text": "UISheetPresentationController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/sheetPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sheetPresentationController"
        }
      ],
      "role": "symbol",
      "title": "sheetPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/sheetpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/targetViewController(forAction:sender:)": {
      "abstract": [
        {
          "text": "Returns the view controller that responds to the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/targetViewController(forAction:sender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetViewControllerForAction:sender:"
        }
      ],
      "role": "symbol",
      "title": "targetViewController(forAction:sender:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/targetviewcontroller(foraction:sender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator": {
      "abstract": [
        {
          "text": "Returns the active transition coordinator object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionCoordinator"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerTransitionCoordinator",
          "text": "UIViewControllerTransitionCoordinator"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transitionCoordinator"
        }
      ],
      "role": "symbol",
      "title": "transitionCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/transitioncoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitioningDelegate": {
      "abstract": [
        {
          "text": "The delegate object that provides transition animator, interactive controller, and custom presentation controller objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitioningDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerTransitioningDelegate",
          "text": "UIViewControllerTransitioningDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitioningDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transitioningDelegate"
        }
      ],
      "role": "symbol",
      "title": "transitioningDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/transitioningdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/customizing-and-resizing-sheets-in-uikit": {
      "abstract": [
        {
          "text": "Discover how to create a layered and customized sheet experience in UIKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/customizing-and-resizing-sheets-in-uikit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing and resizing sheets in UIKit",
      "type": "topic",
      "url": "/documentation/uikit/customizing-and-resizing-sheets-in-uikit"
    },
    "doc://com.externally.resolved.symbol/c:@T@SEL": {
      "abstract": [
        {
          "text": "Defines an opaque type that represents a method selector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "SEL",
      "type": "topic",
      "url": "/documentation/objectivec/sel"
    },
    "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Selector"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Selector",
      "type": "topic",
      "url": "/documentation/objectivec/selector"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-a-custom-transition-or-presentation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitioningDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentationController",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/sheetPresentationController",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/activePresentationController",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/restoresFocusAfterTransition",
        "doc://com.apple.uikit/documentation/UIKit/customizing-and-resizing-sheets-in-uikit"
      ],
      "title": "Adding a custom transition or presentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "targetViewControllerForAction:sender:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetViewControllerForAction:sender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-a-custom-transition-or-presentation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitioningDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentationController",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/sheetPresentationController",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/activePresentationController",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/restoresFocusAfterTransition",
                "doc://com.apple.uikit/documentation/UIKit/customizing-and-resizing-sheets-in-uikit"
              ],
              "title": "Adding a custom transition or presentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIViewController",
                    "text": "UIViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "targetViewControllerForAction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SEL",
                    "text": "SEL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "action"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sender:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sender"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The requested action.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "action"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The object sending the request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sender"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The view controller that handles the specified action or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if no view controller handles the action.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1restoresFocusAfterTransition/title",
          "value": "restoresFocusAfterTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1restoresFocusAfterTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "restoresFocusAfterTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1transitioningDelegate/title",
          "value": "transitioningDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1transitioningDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transitioningDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1sheetPresentationController/title",
          "value": "sheetPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1sheetPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sheetPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1presentationController/title",
          "value": "presentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1presentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1targetViewController(forAction:sender:)/title",
          "value": "targetViewControllerForAction:sender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1targetViewController(forAction:sender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetViewControllerForAction:sender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1canPerformAction(_:withSender:)/title",
          "value": "canPerformAction:withSender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1canPerformAction(_:withSender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformAction:withSender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1transitionCoordinator/title",
          "value": "transitionCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1transitionCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transitionCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1activePresentationController/title",
          "value": "activePresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1activePresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activePresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1popoverPresentationController/title",
          "value": "popoverPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1popoverPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "popoverPresentationController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller/targetviewcontroller(foraction:sender:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller/targetviewcontroller(foraction:sender:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
