{
  "abstract": [
    {
      "text": "Positions the assistant cell at the bottom of all visible cells.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/bottom"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPAssistantCellPosition@CPAssistantCellPositionBottom",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottom"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPAssistantCellPositionBottom"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CPListItem.AssistantCellPosition.bottom"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottom"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem": {
      "abstract": [
        {
          "text": "A selectable row in a list template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "role": "symbol",
      "title": "CPListItem",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition": {
      "abstract": [
        {
          "text": "Constants to specify the position of the assistant cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssistantCellPosition"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssistantCellPosition"
        }
      ],
      "role": "symbol",
      "title": "CPListItem.AssistantCellPosition",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/assistantcellposition"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/bottom": {
      "abstract": [
        {
          "text": "Positions the assistant cell at the bottom of all visible cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPAssistantCellPositionBottom"
        }
      ],
      "role": "symbol",
      "title": "CPListItem.AssistantCellPosition.bottom",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/assistantcellposition/bottom"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/top": {
      "abstract": [
        {
          "text": "Positions the assistant cell at the top of all visible cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPAssistantCellPositionTop"
        }
      ],
      "role": "symbol",
      "title": "CPListItem.AssistantCellPosition.top",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/assistantcellposition/top"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-the-Assistant-Cell-Position",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/top"
      ],
      "title": "Controlling the Assistant Cell Position"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPAssistantCellPositionBottom"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellPositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-the-Assistant-Cell-Position",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellPosition/top"
              ],
              "title": "Controlling the Assistant Cell Position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CPAssistantCellPositionBottom"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition~1bottom/title",
          "value": "CPAssistantCellPositionBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellPositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition/title",
          "value": "CPAssistantCellPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/title",
          "value": "CPListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition~1top/title",
          "value": "CPAssistantCellPositionTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellPosition~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellPositionTop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cplistitem/assistantcellposition/bottom"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cplistitem/assistantcellposition/bottom"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
