{
  "abstract": [
    {
      "text": "The system default color.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPTimeRemainingColor@CPTimeRemainingColorDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPTimeRemainingColorDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CPTimeRemainingColor.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The color is white when the map template’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle/dark",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and black when the style is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle/light",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle": {
      "abstract": [
        {
          "text": "The style that the map template uses when displaying trip estimates during active nagivation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tripEstimateStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTripEstimateStyle",
          "text": "CPTripEstimateStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/tripEstimateStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tripEstimateStyle"
        }
      ],
      "role": "symbol",
      "title": "tripEstimateStyle",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/tripestimatestyle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor": {
      "abstract": [
        {
          "text": "The color the system uses when displaying the time remaining for a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColor"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColor"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default": {
      "abstract": [
        {
          "text": "The system default color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorDefault"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.default",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/default"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green": {
      "abstract": [
        {
          "text": "A shade of green.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorGreen"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.green",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/green"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange": {
      "abstract": [
        {
          "text": "A shade of orange.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orange"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorOrange"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.orange",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/orange"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red": {
      "abstract": [
        {
          "text": "A shade of red.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorRed"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.red",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/red"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle/dark": {
      "abstract": [
        {
          "text": "The dark trip estimate display style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dark"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle/dark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripEstimateStyleDark"
        }
      ],
      "role": "symbol",
      "title": "CPTripEstimateStyle.dark",
      "type": "topic",
      "url": "/documentation/carplay/cptripestimatestyle/dark"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle/light": {
      "abstract": [
        {
          "text": "The light trip estimate display style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "light"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTripEstimateStyle/light",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripEstimateStyleLight"
        }
      ],
      "role": "symbol",
      "title": "CPTripEstimateStyle.light",
      "type": "topic",
      "url": "/documentation/carplay/cptripestimatestyle/light"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red"
      ],
      "title": "Colors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPTimeRemainingColorDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red"
              ],
              "title": "Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CPTimeRemainingColorDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1green/title",
          "value": "CPTimeRemainingColorGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1orange/title",
          "value": "CPTimeRemainingColorOrange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1orange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorOrange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle~1light/title",
          "value": "CPTripEstimateStyleLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle~1light/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripEstimateStyleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1tripEstimateStyle/title",
          "value": "tripEstimateStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1tripEstimateStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tripEstimateStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/title",
          "value": "CPTimeRemainingColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle~1dark/title",
          "value": "CPTripEstimateStyleDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTripEstimateStyle~1dark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripEstimateStyleDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1red/title",
          "value": "CPTimeRemainingColorRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1default/title",
          "value": "CPTimeRemainingColorDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cptimeremainingcolor/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cptimeremainingcolor/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
