{
  "abstract": [
    {
      "text": "A shade of green.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPTimeRemainingColor@CPTimeRemainingColorGreen",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "green"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPTimeRemainingColorGreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CPTimeRemainingColor.green"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "green"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor": {
      "abstract": [
        {
          "text": "The color the system uses when displaying the time remaining for a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColor"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColor"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default": {
      "abstract": [
        {
          "text": "The system default color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorDefault"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.default",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/default"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green": {
      "abstract": [
        {
          "text": "A shade of green.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorGreen"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.green",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/green"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange": {
      "abstract": [
        {
          "text": "A shade of orange.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orange"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorOrange"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.orange",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/orange"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red": {
      "abstract": [
        {
          "text": "A shade of red.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTimeRemainingColorRed"
        }
      ],
      "role": "symbol",
      "title": "CPTimeRemainingColor.red",
      "type": "topic",
      "url": "/documentation/carplay/cptimeremainingcolor/red"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange",
        "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red"
      ],
      "title": "Colors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPTimeRemainingColorGreen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/default",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/orange",
                "doc://com.apple.carplay/documentation/CarPlay/CPTimeRemainingColor/red"
              ],
              "title": "Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CPTimeRemainingColorGreen"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1default/title",
          "value": "CPTimeRemainingColorDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1red/title",
          "value": "CPTimeRemainingColorRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1green/title",
          "value": "CPTimeRemainingColorGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1orange/title",
          "value": "CPTimeRemainingColorOrange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor~1orange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColorOrange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/title",
          "value": "CPTimeRemainingColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTimeRemainingColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTimeRemainingColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cptimeremainingcolor/green"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cptimeremainingcolor/green"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
