{
  "abstract": [
    {
      "text": "Returns the public authentication certificate associated with a user identity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration",
        "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/certificate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBUserIdentity(py)certificate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "certificate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecCertificateRef",
        "text": "SecCertificate"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "certificate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "certificate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "certificate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SecCertificateRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecCertificateRef",
              "text": "SecCertificate"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The public authentication certificate, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if none exists.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Collaboration framework supports certificate-based authentication in addition to passwords. If a certificate is stored for a user identity, it will be the default method of authentication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a .Mac account is associated with a user identity, the authentication certificate is automatically downloaded from the .Mac servers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity": {
      "abstract": [
        {
          "text": "An object of the ",
          "type": "text"
        },
        {
          "code": "CBUserIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class represents a user identity and is used for accessing the attributes of a user identity from an identity authority. The principal attributes of ",
          "type": "text"
        },
        {
          "code": "CBUserIdentity",
          "type": "codeVoice"
        },
        {
          "text": " are a POSIX user identifier (UID), password, and certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUserIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUserIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBUserIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbuseridentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/authenticate(withPassword:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the given password is correct for the identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/authenticate(withPassword:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authenticateWithPassword:"
        }
      ],
      "role": "symbol",
      "title": "authenticate(withPassword:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbuseridentity/authenticate(withpassword:)"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/certificate": {
      "abstract": [
        {
          "text": "Returns the public authentication certificate associated with a user identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/certificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "certificate"
        }
      ],
      "role": "symbol",
      "title": "certificate",
      "type": "topic",
      "url": "/documentation/collaboration/cbuseridentity/certificate"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/isEnabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the identity is allowed to authenticate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/collaboration/cbuseridentity/isenabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@SecCertificateRef": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an X.509 certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SecCertificateRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecCertificate",
      "type": "topic",
      "url": "/documentation/Security/SecCertificate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Password-Authentication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/authenticate(withPassword:)",
        "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/isEnabled"
      ],
      "title": "Password Authentication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "certificate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "certificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.collaboration/documentation/Collaboration",
                "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Password-Authentication",
              "generated": true,
              "identifiers": [
                "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/authenticate(withPassword:)",
                "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity/isEnabled"
              ],
              "title": "Password Authentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@SecCertificateRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecCertificateRef",
                    "text": "SecCertificateRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "certificate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecCertificateRef/title",
          "value": "SecCertificateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecCertificateRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@__SecCertificate",
              "text": "__SecCertificate"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity~1authenticate(withPassword:)/title",
          "value": "authenticateWithPassword:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity~1authenticate(withPassword:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "authenticateWithPassword:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity/title",
          "value": "CBUserIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUserIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUserIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity~1certificate/title",
          "value": "certificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity~1certificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "certificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbuseridentity/certificate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/collaboration/cbuseridentity/certificate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
