{
  "abstract": [
    {
      "text": "A constant that automatically determines an indicator style according to the button’s properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorAutomatic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIButtonConfigurationIndicator@UIButtonConfigurationIndicatorAutomatic",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIButtonConfigurationIndicatorAutomatic"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIButtonConfigurationIndicatorAutomatic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "UIButtonConfigurationIndicatorAutomatic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "UIButtonConfigurationIndicatorAutomatic"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With this behavior, the system automatically shows an indicator if the button shows a menu and has single-selection behavior (when its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/isContextMenuInteractionEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/showsMenuAsPrimaryAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/changesSelectionAsPrimaryAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/changesSelectionAsPrimaryAction": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the button tracks a selection, either through a menu or a toggle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changesSelectionAsPrimaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/changesSelectionAsPrimaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changesSelectionAsPrimaryAction"
        }
      ],
      "role": "symbol",
      "title": "changesSelectionAsPrimaryAction",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/changesselectionasprimaryaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator": {
      "abstract": [
        {
          "text": "Constants that determine the style of the indicator that appears on a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationIndicator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationIndicator",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationindicator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorAutomatic": {
      "abstract": [
        {
          "text": "A constant that automatically determines an indicator style according to the button’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationIndicatorAutomatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorAutomatic",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationIndicatorAutomatic",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationindicator/uibuttonconfigurationindicatorautomatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorNone": {
      "abstract": [
        {
          "text": "A constant that doesn’t show an indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationIndicatorNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationIndicatorNone",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationindicator/uibuttonconfigurationindicatornone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorPopup": {
      "abstract": [
        {
          "text": "A constant that shows a popup-style indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationIndicatorPopup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorPopup",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationIndicatorPopup",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationindicator/uibuttonconfigurationindicatorpopup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/isContextMenuInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the control enables its context menu interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isContextMenuInteractionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/isContextMenuInteractionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextMenuInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isContextMenuInteractionEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/iscontextmenuinteractionenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/showsMenuAsPrimaryAction": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the context menu interaction is the control’s primary action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsMenuAsPrimaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/showsMenuAsPrimaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsMenuAsPrimaryAction"
        }
      ],
      "role": "symbol",
      "title": "showsMenuAsPrimaryAction",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/showsmenuasprimaryaction"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Indicator-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorNone",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator/UIButtonConfigurationIndicatorPopup"
      ],
      "title": "Indicator styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1showsMenuAsPrimaryAction/title",
          "value": "showsMenuAsPrimaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1showsMenuAsPrimaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsMenuAsPrimaryAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isContextMenuInteractionEnabled/title",
          "value": "contextMenuInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isContextMenuInteractionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contextMenuInteractionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1changesSelectionAsPrimaryAction/title",
          "value": "changesSelectionAsPrimaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1changesSelectionAsPrimaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "changesSelectionAsPrimaryAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibuttonconfigurationindicator/uibuttonconfigurationindicatorautomatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
