{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DOM Rule Enumeration (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Modification Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1393660-dom-modification-enumeration-leg"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Direction Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403298-dom-direction-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Measurement Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1418446-dom-measurement-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Delta Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1420212-dom-delta-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Filter Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1455659-dom-filter-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Keyboard Input Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476191-dom-keyboard-input-enumeration-l"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Location Enumeration  (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476932-dom-location-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Element Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1517978-dom-element-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Inheritance Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1518003-dom-inheritance-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Type Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1538223-dom-type-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Phase Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1558620-dom-phase-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Plugin Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569747-webkit-plugin-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Loading Fail Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569748-webkit-loading-fail-enumeration"
    },
    "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Alignment Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1574395-dom-alignment-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CHARSET_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CHARSET_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CHARSET_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CHARSET_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_CHARSET_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_charset_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FONT_FACE_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FONT_FACE_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FONT_FACE_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FONT_FACE_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_FONT_FACE_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_font_face_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_IMPORT_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_IMPORT_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_IMPORT_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_IMPORT_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_IMPORT_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_import_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAMES_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_KEYFRAMES_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAMES_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_KEYFRAMES_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_KEYFRAMES_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_keyframes_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAME_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_KEYFRAME_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAME_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_KEYFRAME_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_KEYFRAME_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_keyframe_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_MEDIA_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_MEDIA_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_MEDIA_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_MEDIA_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_MEDIA_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_media_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NAMESPACE_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NAMESPACE_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_NAMESPACE_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_namespace_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_PAGE_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_PAGE_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_PAGE_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_PAGE_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_PAGE_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_page_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_STYLE_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_STYLE_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_STYLE_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_STYLE_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_STYLE_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_style_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SUPPORTS_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SUPPORTS_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SUPPORTS_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SUPPORTS_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SUPPORTS_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_supports_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAMES_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_WEBKIT_KEYFRAMES_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAMES_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_WEBKIT_KEYFRAMES_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_WEBKIT_KEYFRAMES_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_webkit_keyframes_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAME_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_WEBKIT_KEYFRAME_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAME_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_WEBKIT_KEYFRAME_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_WEBKIT_KEYFRAME_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_webkit_keyframe_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_REGION_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_WEBKIT_REGION_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_REGION_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_WEBKIT_REGION_RULE"
        }
      ],
      "role": "symbol",
      "title": "DOM_WEBKIT_REGION_RULE",
      "type": "topic",
      "url": "/documentation/webkit/dom_webkit_region_rule"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
        "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
        "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
        "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_CHARSET_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_FONT_FACE_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_IMPORT_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAMES_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAME_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_MEDIA_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_PAGE_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_STYLE_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SUPPORTS_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAMES_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAME_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_REGION_RULE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_RULE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_CHARSET_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_FONT_FACE_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_IMPORT_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAMES_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_KEYFRAME_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_MEDIA_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_PAGE_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_STYLE_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SUPPORTS_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAMES_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_KEYFRAME_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_WEBKIT_REGION_RULE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_RULE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
                "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
                "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
                "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_IMPORT_RULE/title",
          "value": "DOM_IMPORT_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_IMPORT_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_IMPORT_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SUPPORTS_RULE/title",
          "value": "DOM_SUPPORTS_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SUPPORTS_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SUPPORTS_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WEBKIT_REGION_RULE/title",
          "value": "DOM_WEBKIT_REGION_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WEBKIT_REGION_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_WEBKIT_REGION_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_PAGE_RULE/title",
          "value": "DOM_PAGE_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_PAGE_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_PAGE_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WEBKIT_KEYFRAME_RULE/title",
          "value": "DOM_WEBKIT_KEYFRAME_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WEBKIT_KEYFRAME_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_WEBKIT_KEYFRAME_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FONT_FACE_RULE/title",
          "value": "DOM_FONT_FACE_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FONT_FACE_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FONT_FACE_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_KEYFRAMES_RULE/title",
          "value": "DOM_KEYFRAMES_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_KEYFRAMES_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_KEYFRAMES_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CHARSET_RULE/title",
          "value": "DOM_CHARSET_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CHARSET_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CHARSET_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_STYLE_RULE/title",
          "value": "DOM_STYLE_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_STYLE_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_STYLE_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WEBKIT_KEYFRAMES_RULE/title",
          "value": "DOM_WEBKIT_KEYFRAMES_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WEBKIT_KEYFRAMES_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_WEBKIT_KEYFRAMES_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_MEDIA_RULE/title",
          "value": "DOM_MEDIA_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_MEDIA_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_MEDIA_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NAMESPACE_RULE/title",
          "value": "DOM_NAMESPACE_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NAMESPACE_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NAMESPACE_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_KEYFRAME_RULE/title",
          "value": "DOM_KEYFRAME_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_KEYFRAME_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_KEYFRAME_RULE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/1403866-dom-rule-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/1403866-dom-rule-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
