{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DOM Measurement Enumeration (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Modification Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1393660-dom-modification-enumeration-leg"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Direction Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403298-dom-direction-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Rule Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403866-dom-rule-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Delta Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1420212-dom-delta-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Filter Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1455659-dom-filter-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Keyboard Input Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476191-dom-keyboard-input-enumeration-l"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Location Enumeration  (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476932-dom-location-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Element Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1517978-dom-element-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Inheritance Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1518003-dom-inheritance-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Type Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1538223-dom-type-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Phase Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1558620-dom-phase-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Plugin Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569747-webkit-plugin-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Loading Fail Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569748-webkit-loading-fail-enumeration"
    },
    "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Alignment Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1574395-dom-alignment-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_ATTR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_ATTR"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_ATTR",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_attr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_CM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_CM"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_CM",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_cm"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_COUNTER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_COUNTER"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_COUNTER",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_counter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_DEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_DEG"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_DEG",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_deg"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_DIMENSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_DIMENSION"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_DIMENSION",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_dimension"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_EMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_EMS"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_EMS",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_ems"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_EXS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_EXS"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_EXS",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_exs"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_GRAD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_GRAD"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_GRAD",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_grad"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_HZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_HZ"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_HZ",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_hz"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_IDENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_IDENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_IDENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_ident"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_IN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_IN"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_IN",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_in"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_KHZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_KHZ"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_KHZ",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_khz"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_MM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_MM"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_MM",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_mm"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_MS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_MS"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_MS",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_ms"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_NUMBER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_NUMBER"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_NUMBER",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_number"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_PC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_PC"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_PC",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_pc"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PERCENTAGE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_PERCENTAGE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PERCENTAGE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_PERCENTAGE"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_PERCENTAGE",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_percentage"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_PT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_PT"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_PT",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_pt"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_PX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_PX"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_PX",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_px"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RAD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_RAD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RAD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_RAD"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_RAD",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_rad"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_RECT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_RECT"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_RECT",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_rect"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RGBCOLOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_RGBCOLOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RGBCOLOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_RGBCOLOR"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_RGBCOLOR",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_rgbcolor"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_S"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_S"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_S",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_s"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_STRING"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_STRING",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_string"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_UNKNOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_UNKNOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_UNKNOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_UNKNOWN"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_UNKNOWN",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_unknown"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_URI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_URI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_URI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_URI"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_URI",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_uri"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_VH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_VH"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_VH",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_vh"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMAX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_VMAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_VMAX"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_VMAX",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_vmax"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_VMIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_VMIN"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_VMIN",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_vmin"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_VW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_VW"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_VW",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_vw"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
        "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
        "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
        "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PC",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PERCENTAGE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PX",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RAD",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RECT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RGBCOLOR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_STRING",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_UNKNOWN",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_URI",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VH",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMAX",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMIN",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VW"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PC",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PERCENTAGE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_PX",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RAD",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RECT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_RGBCOLOR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_STRING",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_UNKNOWN",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_URI",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VH",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMAX",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VMIN",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_VW"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
                "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
                "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
                "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_HZ/title",
          "value": "DOM_CSS_HZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_HZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_HZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PT/title",
          "value": "DOM_CSS_PT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_PT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DIMENSION/title",
          "value": "DOM_CSS_DIMENSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DIMENSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_DIMENSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VW/title",
          "value": "DOM_CSS_VW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_VW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_GRAD/title",
          "value": "DOM_CSS_GRAD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_GRAD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_GRAD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_RAD/title",
          "value": "DOM_CSS_RAD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_RAD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_RAD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_RGBCOLOR/title",
          "value": "DOM_CSS_RGBCOLOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_RGBCOLOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_RGBCOLOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_COUNTER/title",
          "value": "DOM_CSS_COUNTER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_COUNTER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_COUNTER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MM/title",
          "value": "DOM_CSS_MM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_MM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EMS/title",
          "value": "DOM_CSS_EMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_EMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IDENT/title",
          "value": "DOM_CSS_IDENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IDENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_IDENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VMIN/title",
          "value": "DOM_CSS_VMIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VMIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_VMIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PERCENTAGE/title",
          "value": "DOM_CSS_PERCENTAGE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PERCENTAGE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_PERCENTAGE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_S/title",
          "value": "DOM_CSS_S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_S/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_UNKNOWN/title",
          "value": "DOM_CSS_UNKNOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_UNKNOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_UNKNOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VH/title",
          "value": "DOM_CSS_VH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_VH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PC/title",
          "value": "DOM_CSS_PC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_PC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VMAX/title",
          "value": "DOM_CSS_VMAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_VMAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_VMAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_ATTR/title",
          "value": "DOM_CSS_ATTR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_ATTR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_ATTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EXS/title",
          "value": "DOM_CSS_EXS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EXS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_EXS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MS/title",
          "value": "DOM_CSS_MS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_MS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_NUMBER/title",
          "value": "DOM_CSS_NUMBER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_NUMBER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_NUMBER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_CM/title",
          "value": "DOM_CSS_CM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_CM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_CM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DEG/title",
          "value": "DOM_CSS_DEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_DEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PX/title",
          "value": "DOM_CSS_PX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_PX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_PX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_KHZ/title",
          "value": "DOM_CSS_KHZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_KHZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_KHZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_RECT/title",
          "value": "DOM_CSS_RECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_RECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_RECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_STRING/title",
          "value": "DOM_CSS_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IN/title",
          "value": "DOM_CSS_IN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_IN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_URI/title",
          "value": "DOM_CSS_URI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_URI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_URI"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/1418446-dom-measurement-enumeration-lega"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/1418446-dom-measurement-enumeration-lega"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
