{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DOM Filter Enumeration (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Modification Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1393660-dom-modification-enumeration-leg"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Direction Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403298-dom-direction-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Rule Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403866-dom-rule-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Measurement Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1418446-dom-measurement-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Delta Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1420212-dom-delta-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Keyboard Input Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476191-dom-keyboard-input-enumeration-l"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Location Enumeration  (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476932-dom-location-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Element Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1517978-dom-element-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Inheritance Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1518003-dom-inheritance-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Type Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1538223-dom-type-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Phase Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1558620-dom-phase-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Plugin Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569747-webkit-plugin-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Loading Fail Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569748-webkit-loading-fail-enumeration"
    },
    "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Alignment Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1574395-dom-alignment-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FILTER_ACCEPT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FILTER_ACCEPT"
        }
      ],
      "role": "symbol",
      "title": "DOM_FILTER_ACCEPT",
      "type": "topic",
      "url": "/documentation/webkit/dom_filter_accept"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FILTER_REJECT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FILTER_REJECT"
        }
      ],
      "role": "symbol",
      "title": "DOM_FILTER_REJECT",
      "type": "topic",
      "url": "/documentation/webkit/dom_filter_reject"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FILTER_SKIP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FILTER_SKIP"
        }
      ],
      "role": "symbol",
      "title": "DOM_FILTER_SKIP",
      "type": "topic",
      "url": "/documentation/webkit/dom_filter_skip"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ALL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ALL"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ALL",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_all"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ATTRIBUTE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ATTRIBUTE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ATTRIBUTE",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_attribute"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_CDATA_SECTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_CDATA_SECTION"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_CDATA_SECTION",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_cdata_section"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_COMMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_COMMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_COMMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_comment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_DOCUMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_document"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_FRAGMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_FRAGMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_DOCUMENT_FRAGMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_document_fragment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_DOCUMENT_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_document_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ELEMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ELEMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ELEMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_element"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ENTITY",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_entity"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY_REFERENCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY_REFERENCE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ENTITY_REFERENCE",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_entity_reference"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_NOTATION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_NOTATION"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_NOTATION",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_notation"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_PROCESSING_INSTRUCTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_PROCESSING_INSTRUCTION"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_PROCESSING_INSTRUCTION",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_processing_instruction"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_TEXT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_TEXT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_TEXT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_text"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
        "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
        "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
        "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
                "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
                "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
                "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_TEXT/title",
          "value": "DOM_SHOW_TEXT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_TEXT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_TEXT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT/title",
          "value": "DOM_SHOW_DOCUMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_DOCUMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_ACCEPT/title",
          "value": "DOM_FILTER_ACCEPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_ACCEPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_ACCEPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_CDATA_SECTION/title",
          "value": "DOM_SHOW_CDATA_SECTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_CDATA_SECTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_CDATA_SECTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_PROCESSING_INSTRUCTION/title",
          "value": "DOM_SHOW_PROCESSING_INSTRUCTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_PROCESSING_INSTRUCTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_PROCESSING_INSTRUCTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ELEMENT/title",
          "value": "DOM_SHOW_ELEMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ELEMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ELEMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_REJECT/title",
          "value": "DOM_FILTER_REJECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_REJECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_REJECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY/title",
          "value": "DOM_SHOW_ENTITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ENTITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ALL/title",
          "value": "DOM_SHOW_ALL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ALL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ALL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_SKIP/title",
          "value": "DOM_FILTER_SKIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_SKIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_SKIP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_COMMENT/title",
          "value": "DOM_SHOW_COMMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_COMMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_COMMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_FRAGMENT/title",
          "value": "DOM_SHOW_DOCUMENT_FRAGMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_FRAGMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_DOCUMENT_FRAGMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_NOTATION/title",
          "value": "DOM_SHOW_NOTATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_NOTATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_NOTATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ATTRIBUTE/title",
          "value": "DOM_SHOW_ATTRIBUTE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ATTRIBUTE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ATTRIBUTE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_TYPE/title",
          "value": "DOM_SHOW_DOCUMENT_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_DOCUMENT_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY_REFERENCE/title",
          "value": "DOM_SHOW_ENTITY_REFERENCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY_REFERENCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ENTITY_REFERENCE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/1455659-dom-filter-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/1455659-dom-filter-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
