{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DOM Element Enumeration (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Modification Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1393660-dom-modification-enumeration-leg"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Direction Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403298-dom-direction-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Rule Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403866-dom-rule-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Measurement Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1418446-dom-measurement-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Delta Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1420212-dom-delta-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Filter Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1455659-dom-filter-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Keyboard Input Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476191-dom-keyboard-input-enumeration-l"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Location Enumeration  (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476932-dom-location-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Inheritance Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1518003-dom-inheritance-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Type Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1538223-dom-type-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Phase Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1558620-dom-phase-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Plugin Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569747-webkit-plugin-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Loading Fail Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569748-webkit-loading-fail-enumeration"
    },
    "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Alignment Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1574395-dom-alignment-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ATTRIBUTE_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ATTRIBUTE_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ATTRIBUTE_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_attribute_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CDATA_SECTION_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CDATA_SECTION_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_CDATA_SECTION_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_cdata_section_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_COMMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_COMMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_COMMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_comment_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_FRAGMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_FRAGMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_FRAGMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_fragment_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_CONTAINED_BY",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_contained_by"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINS"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_CONTAINS",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_contains"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_DISCONNECTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_DISCONNECTED"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_DISCONNECTED",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_disconnected"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_FOLLOWING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_FOLLOWING"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_FOLLOWING",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_following"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_implementation_specific"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_PRECEDING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_PRECEDING"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_PRECEDING",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_preceding"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_TYPE_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_TYPE_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_TYPE_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_type_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ELEMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ELEMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ELEMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_element_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ENTITY_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_entity_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_REFERENCE_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_REFERENCE_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ENTITY_REFERENCE_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_entity_reference_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NOTATION_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NOTATION_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_NOTATION_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_notation_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_PROCESSING_INSTRUCTION_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_PROCESSING_INSTRUCTION_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_PROCESSING_INSTRUCTION_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_PROCESSING_INSTRUCTION_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_PROCESSING_INSTRUCTION_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_processing_instruction_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_TEXT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_TEXT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_TEXT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_TEXT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_TEXT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_text_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
        "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
        "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
        "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_PROCESSING_INSTRUCTION_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_TEXT_NODE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_PROCESSING_INSTRUCTION_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_TEXT_NODE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
                "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
                "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
                "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ATTRIBUTE_NODE/title",
          "value": "DOM_ATTRIBUTE_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ATTRIBUTE_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ATTRIBUTE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINS/title",
          "value": "DOM_DOCUMENT_POSITION_CONTAINS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_CONTAINS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_NODE/title",
          "value": "DOM_DOCUMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINED_BY/title",
          "value": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINED_BY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CDATA_SECTION_NODE/title",
          "value": "DOM_CDATA_SECTION_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CDATA_SECTION_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CDATA_SECTION_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_FRAGMENT_NODE/title",
          "value": "DOM_DOCUMENT_FRAGMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_FRAGMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_FRAGMENT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ELEMENT_NODE/title",
          "value": "DOM_ELEMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ELEMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ELEMENT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC/title",
          "value": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_PROCESSING_INSTRUCTION_NODE/title",
          "value": "DOM_PROCESSING_INSTRUCTION_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_PROCESSING_INSTRUCTION_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_PROCESSING_INSTRUCTION_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_TEXT_NODE/title",
          "value": "DOM_TEXT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_TEXT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_TEXT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOTATION_NODE/title",
          "value": "DOM_NOTATION_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOTATION_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NOTATION_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_TYPE_NODE/title",
          "value": "DOM_DOCUMENT_TYPE_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_TYPE_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_TYPE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_DISCONNECTED/title",
          "value": "DOM_DOCUMENT_POSITION_DISCONNECTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_DISCONNECTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_DISCONNECTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_FOLLOWING/title",
          "value": "DOM_DOCUMENT_POSITION_FOLLOWING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_FOLLOWING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_FOLLOWING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_REFERENCE_NODE/title",
          "value": "DOM_ENTITY_REFERENCE_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_REFERENCE_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ENTITY_REFERENCE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_NODE/title",
          "value": "DOM_ENTITY_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ENTITY_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_PRECEDING/title",
          "value": "DOM_DOCUMENT_POSITION_PRECEDING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_PRECEDING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_PRECEDING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_COMMENT_NODE/title",
          "value": "DOM_COMMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_COMMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_COMMENT_NODE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/1517978-dom-element-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/1517978-dom-element-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
