{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/1538223-dom-type-enumeration-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DOM Type Enumeration (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Modification Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1393660-dom-modification-enumeration-leg"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Direction Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403298-dom-direction-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Rule Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1403866-dom-rule-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Measurement Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1418446-dom-measurement-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Delta Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1420212-dom-delta-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Filter Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1455659-dom-filter-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Keyboard Input Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476191-dom-keyboard-input-enumeration-l"
    },
    "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Location Enumeration  (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1476932-dom-location-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Element Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1517978-dom-element-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Inheritance Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1518003-dom-inheritance-enumeration-lega"
    },
    "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Phase Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1558620-dom-phase-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Plugin Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569747-webkit-plugin-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebKit Loading Fail Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1569748-webkit-loading-fail-enumeration"
    },
    "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DOM Alignment Enumeration (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/1574395-dom-alignment-enumeration-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ANY_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ANY_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ANY_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_any_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_UNORDERED_NODE_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ANY_UNORDERED_NODE_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_UNORDERED_NODE_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ANY_UNORDERED_NODE_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ANY_UNORDERED_NODE_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_any_unordered_node_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_BOOLEAN_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_BOOLEAN_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_BOOLEAN_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_BOOLEAN_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_BOOLEAN_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_boolean_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FIRST_ORDERED_NODE_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FIRST_ORDERED_NODE_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FIRST_ORDERED_NODE_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FIRST_ORDERED_NODE_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_FIRST_ORDERED_NODE_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_first_ordered_node_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NUMBER_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NUMBER_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NUMBER_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NUMBER_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_NUMBER_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_number_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_ITERATOR_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ORDERED_NODE_ITERATOR_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_ITERATOR_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ORDERED_NODE_ITERATOR_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ORDERED_NODE_ITERATOR_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_ordered_node_iterator_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_SNAPSHOT_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ORDERED_NODE_SNAPSHOT_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_SNAPSHOT_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ORDERED_NODE_SNAPSHOT_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ORDERED_NODE_SNAPSHOT_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_ordered_node_snapshot_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_STRING_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_STRING_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_STRING_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_STRING_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_STRING_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_string_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_ITERATOR_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_UNORDERED_NODE_ITERATOR_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_ITERATOR_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_UNORDERED_NODE_ITERATOR_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_UNORDERED_NODE_ITERATOR_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_unordered_node_iterator_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_SNAPSHOT_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_UNORDERED_NODE_SNAPSHOT_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_SNAPSHOT_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_UNORDERED_NODE_SNAPSHOT_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_UNORDERED_NODE_SNAPSHOT_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_unordered_node_snapshot_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
        "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
        "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
        "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
        "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
        "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_UNORDERED_NODE_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_BOOLEAN_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_FIRST_ORDERED_NODE_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NUMBER_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_ITERATOR_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_SNAPSHOT_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_STRING_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_ITERATOR_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_SNAPSHOT_TYPE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ANY_UNORDERED_NODE_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_BOOLEAN_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_FIRST_ORDERED_NODE_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NUMBER_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_ITERATOR_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ORDERED_NODE_SNAPSHOT_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_STRING_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_ITERATOR_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_UNORDERED_NODE_SNAPSHOT_TYPE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/1403866-dom-rule-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1574395-dom-alignment-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1418446-dom-measurement-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1476932-dom-location-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1455659-dom-filter-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1517978-dom-element-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1393660-dom-modification-enumeration-leg",
                "doc://com.apple.webkit/documentation/WebKit/1569747-webkit-plugin-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1569748-webkit-loading-fail-enumeration",
                "doc://com.apple.webkit/documentation/WebKit/1518003-dom-inheritance-enumeration-lega",
                "doc://com.apple.webkit/documentation/WebKit/1403298-dom-direction-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1476191-dom-keyboard-input-enumeration-l",
                "doc://com.apple.webkit/documentation/WebKit/1420212-dom-delta-enumeration-legacy",
                "doc://com.apple.webkit/documentation/WebKit/1558620-dom-phase-enumeration-legacy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_UNORDERED_NODE_ITERATOR_TYPE/title",
          "value": "DOM_UNORDERED_NODE_ITERATOR_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_UNORDERED_NODE_ITERATOR_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_UNORDERED_NODE_ITERATOR_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FIRST_ORDERED_NODE_TYPE/title",
          "value": "DOM_FIRST_ORDERED_NODE_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FIRST_ORDERED_NODE_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FIRST_ORDERED_NODE_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NUMBER_TYPE/title",
          "value": "DOM_NUMBER_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NUMBER_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NUMBER_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ORDERED_NODE_SNAPSHOT_TYPE/title",
          "value": "DOM_ORDERED_NODE_SNAPSHOT_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ORDERED_NODE_SNAPSHOT_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ORDERED_NODE_SNAPSHOT_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ANY_TYPE/title",
          "value": "DOM_ANY_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ANY_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ANY_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ORDERED_NODE_ITERATOR_TYPE/title",
          "value": "DOM_ORDERED_NODE_ITERATOR_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ORDERED_NODE_ITERATOR_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ORDERED_NODE_ITERATOR_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ANY_UNORDERED_NODE_TYPE/title",
          "value": "DOM_ANY_UNORDERED_NODE_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ANY_UNORDERED_NODE_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ANY_UNORDERED_NODE_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_UNORDERED_NODE_SNAPSHOT_TYPE/title",
          "value": "DOM_UNORDERED_NODE_SNAPSHOT_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_UNORDERED_NODE_SNAPSHOT_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_UNORDERED_NODE_SNAPSHOT_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_BOOLEAN_TYPE/title",
          "value": "DOM_BOOLEAN_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_BOOLEAN_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_BOOLEAN_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_STRING_TYPE/title",
          "value": "DOM_STRING_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_STRING_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_STRING_TYPE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/1538223-dom-type-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/1538223-dom-type-enumeration-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
