{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Accessing Previous Webpages (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebBackForwardList",
          "type": "codeVoice"
        },
        {
          "text": " object maintains a list of visited pages used to go back and forward to the most recent page. A ",
          "type": "text"
        },
        {
          "code": "WebBackForwardList",
          "type": "codeVoice"
        },
        {
          "text": " object maintains only the list data—it does not perform actual page loads (in other words, it does not make any client requests). If you need to perform a page load, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to find out how to do this.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebBackForwardList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebBackForwardList"
        }
      ],
      "role": "symbol",
      "title": "WebBackForwardList",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object encapsulates the data displayed in a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " object. There is one ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object per frame displayed in a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": ". An entire webpage is represented by a hierarchy of ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " objects in which the root object is called the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "main frame",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "role": "symbol",
      "title": "WebFrame",
      "type": "topic",
      "url": "/documentation/webkit/webframe"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s": {
      "abstract": [
        {
          "text": "Connects to a given URL by initiating an asynchronous client request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRequest:"
        }
      ],
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webframe/load(_:)-47p2s"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory": {
      "abstract": [
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects are used to maintain the pages visited by users. Visited pages are represented by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects. You add and remove history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods. These methods post appropriate notifications when items are added or removed so you can update the display. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " organizes the ",
          "type": "text"
        },
        {
          "code": "WebHistoryItem",
          "type": "codeVoice"
        },
        {
          "text": " objects by the day they were visited, ordered from most recent to oldest. You can request all the days that contain history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method or request the items visited on a particular day using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects can be loaded and saved by specifying a file URL (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "role": "symbol",
      "title": "WebHistory",
      "type": "topic",
      "url": "/documentation/webkit/webhistory"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)": {
      "abstract": [
        {
          "text": "Inserts or updates the specified items in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addItems:"
        }
      ],
      "role": "symbol",
      "title": "addItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/additems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)": {
      "abstract": [
        {
          "text": "Loads the contents of the specified web history file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFromURL:error:"
        }
      ],
      "role": "symbol",
      "title": "load(from:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/load(from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)": {
      "abstract": [
        {
          "text": "Returns web history items that were last visited on the specified date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "onDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendarDate",
          "text": "NSCalendarDate"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisitedOnDay:"
        }
      ],
      "role": "symbol",
      "title": "orderedItemsLastVisited(onDay:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/ordereditemslastvisited(onday:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays": {
      "abstract": [
        {
          "text": "An array of all calendar days represented in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        }
      ],
      "role": "symbol",
      "title": "orderedLastVisitedDays",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/orderedlastvisiteddays"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)": {
      "abstract": [
        {
          "text": "Removes the specified items from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeItems:"
        }
      ],
      "role": "symbol",
      "title": "removeItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/removeitems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem": {
      "abstract": [
        {
          "text": "WebHistoryItem objects encapsulate information about visiting a page so that users can return to that page. WebHistory and WebBackForwardList objects manage lists of WebHistoryItem objects. WebHistoryItem objects are created and added to these lists automatically when loading pages, so you do not need to create WebHistoryItem objects directly.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "role": "symbol",
      "title": "WebHistoryItem",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitem"
    },
    "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Archiving Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/archiving-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Downloading Information (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/downloading-information-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Implementing Plugins (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/implementing-plugins-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Incorporating Scripts (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/incorporating-scripts-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Loading Resources (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/loading-resources-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Opening a File (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/opening-a-file-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Policies (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-policies-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Up a Web View (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-up-a-web-view-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working With Document Web Views (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-document-web-views-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working with Frames (legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-frames-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WebKit-Legacy-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
        "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
        "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
        "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
        "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
        "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
      ],
      "title": "WebKit Legacy APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Previous-Webpages-Legacy",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem"
      ],
      "title": "Accessing Previous Webpages (Legacy)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Previous-Webpages-Legacy",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem"
              ],
              "title": "Accessing Previous Webpages (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WebKit-Legacy-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
                "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
                "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
                "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
                "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
                "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
              ],
              "title": "WebKit Legacy APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/title",
          "value": "WebBackForwardList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title",
          "value": "loadRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/title",
          "value": "removeItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/title",
          "value": "addItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/title",
          "value": "loadFromURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFromURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/title",
          "value": "WebFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/title",
          "value": "orderedLastVisitedDays"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orderedLastVisitedDays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/title",
          "value": "WebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/title",
          "value": "orderedItemsLastVisitedOnDay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "orderedItemsLastVisitedOnDay:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/title",
          "value": "WebHistoryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/accessing-previous-webpages-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/accessing-previous-webpages-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
