{
  "abstract": [
    {
      "text": "Explore the constants that identify the types of data that websites store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/data-store-record-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Data Store Record Types"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object includes these constants in its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord/dataTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord": {
      "abstract": [
        {
          "text": "A record of the data that a particular website stores persistently.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataRecord"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataRecord"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataRecord",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatarecord"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord/dataTypes": {
      "abstract": [
        {
          "text": "The types of data associated with the record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord/dataTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataTypes"
        }
      ],
      "role": "symbol",
      "title": "dataTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatarecord/datatypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeCookies": {
      "abstract": [
        {
          "text": "Cookies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeCookies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeCookies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeCookies"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeCookies",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypecookies"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeDiskCache": {
      "abstract": [
        {
          "text": "On-disk caches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeDiskCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeDiskCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeDiskCache"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeDiskCache",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypediskcache"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeIndexedDBDatabases": {
      "abstract": [
        {
          "text": "IndexedDB databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeIndexedDBDatabases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeIndexedDBDatabases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeIndexedDBDatabases"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeIndexedDBDatabases",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypeindexeddbdatabases"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeLocalStorage": {
      "abstract": [
        {
          "text": "HTML local storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeLocalStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeLocalStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeLocalStorage"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeLocalStorage",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypelocalstorage"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeMemoryCache": {
      "abstract": [
        {
          "text": "In-memory caches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeMemoryCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeMemoryCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeMemoryCache"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeMemoryCache",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypememorycache"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeOfflineWebApplicationCache": {
      "abstract": [
        {
          "text": "HTML offline web app caches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeOfflineWebApplicationCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeOfflineWebApplicationCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeOfflineWebApplicationCache"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeOfflineWebApplicationCache",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypeofflinewebapplicationcache"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeSessionStorage": {
      "abstract": [
        {
          "text": "HTML session storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeSessionStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeSessionStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeSessionStorage"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeSessionStorage",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypesessionstorage"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeWebSQLDatabases": {
      "abstract": [
        {
          "text": "WebSQL databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeWebSQLDatabases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeWebSQLDatabases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataTypeWebSQLDatabases"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataTypeWebSQLDatabases",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatatypewebsqldatabases"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Data-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord/dataTypes"
      ],
      "title": "Getting the Data Type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Cookie-Type",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeCookies"
      ],
      "title": "Cookie Type"
    },
    {
      "anchor": "Cache-Types",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeMemoryCache",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeDiskCache",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeOfflineWebApplicationCache"
      ],
      "title": "Cache Types"
    },
    {
      "anchor": "Storage-Types",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeLocalStorage",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeSessionStorage"
      ],
      "title": "Storage Types"
    },
    {
      "anchor": "Database-Types",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeWebSQLDatabases",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeIndexedDBDatabases"
      ],
      "title": "Database Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Cookie-Type",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeCookies"
              ],
              "title": "Cookie Type"
            },
            {
              "anchor": "Cache-Types",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeMemoryCache",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeDiskCache",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeOfflineWebApplicationCache"
              ],
              "title": "Cache Types"
            },
            {
              "anchor": "Storage-Types",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeLocalStorage",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeSessionStorage"
              ],
              "title": "Storage Types"
            },
            {
              "anchor": "Database-Types",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeWebSQLDatabases",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataTypeIndexedDBDatabases"
              ],
              "title": "Database Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Data-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord/dataTypes"
              ],
              "title": "Getting the Data Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeMemoryCache/title",
          "value": "WKWebsiteDataTypeMemoryCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeMemoryCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeMemoryCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeSessionStorage/title",
          "value": "WKWebsiteDataTypeSessionStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeSessionStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeSessionStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeOfflineWebApplicationCache/title",
          "value": "WKWebsiteDataTypeOfflineWebApplicationCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeOfflineWebApplicationCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeOfflineWebApplicationCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord~1dataTypes/title",
          "value": "dataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord~1dataTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeIndexedDBDatabases/title",
          "value": "WKWebsiteDataTypeIndexedDBDatabases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeIndexedDBDatabases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeIndexedDBDatabases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeDiskCache/title",
          "value": "WKWebsiteDataTypeDiskCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeDiskCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeDiskCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeLocalStorage/title",
          "value": "WKWebsiteDataTypeLocalStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeLocalStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeLocalStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeWebSQLDatabases/title",
          "value": "WKWebsiteDataTypeWebSQLDatabases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeWebSQLDatabases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeWebSQLDatabases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord/title",
          "value": "WKWebsiteDataRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeCookies/title",
          "value": "WKWebsiteDataTypeCookies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataTypeCookies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataTypeCookies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/data-store-record-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/data-store-record-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
