{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@DOM_FILTER_ACCEPT@DOM_FILTER_ACCEPT",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOM_FILTER_ACCEPT"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOM_FILTER_ACCEPT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DOM_FILTER_ACCEPT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOM_FILTER_ACCEPT"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FILTER_ACCEPT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_ACCEPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FILTER_ACCEPT"
        }
      ],
      "role": "symbol",
      "title": "DOM_FILTER_ACCEPT",
      "type": "topic",
      "url": "/documentation/webkit/dom_filter_accept"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FILTER_REJECT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FILTER_REJECT"
        }
      ],
      "role": "symbol",
      "title": "DOM_FILTER_REJECT",
      "type": "topic",
      "url": "/documentation/webkit/dom_filter_reject"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_FILTER_SKIP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_FILTER_SKIP"
        }
      ],
      "role": "symbol",
      "title": "DOM_FILTER_SKIP",
      "type": "topic",
      "url": "/documentation/webkit/dom_filter_skip"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ALL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ALL"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ALL",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_all"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ATTRIBUTE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ATTRIBUTE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ATTRIBUTE",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_attribute"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_CDATA_SECTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_CDATA_SECTION"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_CDATA_SECTION",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_cdata_section"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_COMMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_COMMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_COMMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_comment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_DOCUMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_document"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_FRAGMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_FRAGMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_DOCUMENT_FRAGMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_document_fragment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_TYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_DOCUMENT_TYPE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_DOCUMENT_TYPE",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_document_type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ELEMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ELEMENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ELEMENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_element"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ENTITY",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_entity"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY_REFERENCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_ENTITY_REFERENCE"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_ENTITY_REFERENCE",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_entity_reference"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_NOTATION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_NOTATION"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_NOTATION",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_notation"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_PROCESSING_INSTRUCTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_PROCESSING_INSTRUCTION"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_PROCESSING_INSTRUCTION",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_processing_instruction"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SHOW_TEXT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SHOW_TEXT"
        }
      ],
      "role": "symbol",
      "title": "DOM_SHOW_TEXT",
      "type": "topic",
      "url": "/documentation/webkit/dom_show_text"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOM_FILTER_ACCEPT"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_ACCEPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_REJECT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_FILTER_SKIP",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ALL",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ATTRIBUTE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_CDATA_SECTION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_COMMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_FRAGMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_DOCUMENT_TYPE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ELEMENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_ENTITY_REFERENCE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_NOTATION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_PROCESSING_INSTRUCTION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SHOW_TEXT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "DOM_FILTER_ACCEPT"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_CDATA_SECTION/title",
          "value": "DOM_SHOW_CDATA_SECTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_CDATA_SECTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_CDATA_SECTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_REJECT/title",
          "value": "DOM_FILTER_REJECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_REJECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_REJECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_COMMENT/title",
          "value": "DOM_SHOW_COMMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_COMMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_COMMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ATTRIBUTE/title",
          "value": "DOM_SHOW_ATTRIBUTE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ATTRIBUTE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ATTRIBUTE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_TYPE/title",
          "value": "DOM_SHOW_DOCUMENT_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_DOCUMENT_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_FRAGMENT/title",
          "value": "DOM_SHOW_DOCUMENT_FRAGMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT_FRAGMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_DOCUMENT_FRAGMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ALL/title",
          "value": "DOM_SHOW_ALL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ALL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ALL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY/title",
          "value": "DOM_SHOW_ENTITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ENTITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY_REFERENCE/title",
          "value": "DOM_SHOW_ENTITY_REFERENCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ENTITY_REFERENCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ENTITY_REFERENCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_PROCESSING_INSTRUCTION/title",
          "value": "DOM_SHOW_PROCESSING_INSTRUCTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_PROCESSING_INSTRUCTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_PROCESSING_INSTRUCTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_TEXT/title",
          "value": "DOM_SHOW_TEXT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_TEXT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_TEXT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT/title",
          "value": "DOM_SHOW_DOCUMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_DOCUMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_DOCUMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_NOTATION/title",
          "value": "DOM_SHOW_NOTATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_NOTATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_NOTATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ELEMENT/title",
          "value": "DOM_SHOW_ELEMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SHOW_ELEMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SHOW_ELEMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_ACCEPT/title",
          "value": "DOM_FILTER_ACCEPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_ACCEPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_ACCEPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_SKIP/title",
          "value": "DOM_FILTER_SKIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_FILTER_SKIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_FILTER_SKIP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/dom_filter_accept"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/dom_filter_accept"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
