{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@DOM_CSS_UNKNOWN@DOM_CSS_S",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOM_CSS_S"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOM_CSS_S"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DOM_CSS_S"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOM_CSS_S"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_ATTR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_ATTR"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_ATTR",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_attr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_CM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_CM"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_CM",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_cm"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_COUNTER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_COUNTER"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_COUNTER",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_counter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_DEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_DEG"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_DEG",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_deg"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_DIMENSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_DIMENSION"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_DIMENSION",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_dimension"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_EMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_EMS"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_EMS",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_ems"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_EXS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_EXS"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_EXS",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_exs"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_GRAD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_GRAD"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_GRAD",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_grad"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_HZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_HZ"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_HZ",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_hz"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_IDENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_IDENT"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_IDENT",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_ident"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_IN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_IN"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_IN",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_in"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_KHZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_KHZ"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_KHZ",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_khz"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_MM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_MM"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_MM",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_mm"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_MS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_MS"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_MS",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_ms"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_NUMBER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_NUMBER"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_NUMBER",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_number"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CSS_S"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_S",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CSS_S"
        }
      ],
      "role": "symbol",
      "title": "DOM_CSS_S",
      "type": "topic",
      "url": "/documentation/webkit/dom_css_s"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOM_CSS_S"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_ATTR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_CM",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_COUNTER",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DEG",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_DIMENSION",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EMS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_EXS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_GRAD",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_HZ",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IDENT",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_IN",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_KHZ",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MM",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_MS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CSS_NUMBER"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "DOM_CSS_S"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_S/title",
          "value": "DOM_CSS_S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_S/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EMS/title",
          "value": "DOM_CSS_EMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_EMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_KHZ/title",
          "value": "DOM_CSS_KHZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_KHZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_KHZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_GRAD/title",
          "value": "DOM_CSS_GRAD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_GRAD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_GRAD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IDENT/title",
          "value": "DOM_CSS_IDENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IDENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_IDENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EXS/title",
          "value": "DOM_CSS_EXS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_EXS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_EXS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DEG/title",
          "value": "DOM_CSS_DEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_DEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_COUNTER/title",
          "value": "DOM_CSS_COUNTER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_COUNTER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_COUNTER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_HZ/title",
          "value": "DOM_CSS_HZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_HZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_HZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MS/title",
          "value": "DOM_CSS_MS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_MS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_ATTR/title",
          "value": "DOM_CSS_ATTR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_ATTR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_ATTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IN/title",
          "value": "DOM_CSS_IN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_IN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_IN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_NUMBER/title",
          "value": "DOM_CSS_NUMBER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_NUMBER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_NUMBER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_CM/title",
          "value": "DOM_CSS_CM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_CM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_CM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DIMENSION/title",
          "value": "DOM_CSS_DIMENSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_DIMENSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_DIMENSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MM/title",
          "value": "DOM_CSS_MM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CSS_MM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CSS_MM"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/dom_css_s"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/dom_css_s"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
