{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@DOM_ELEMENT_NODE@DOM_ENTITY_REFERENCE_NODE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOM_ENTITY_REFERENCE_NODE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOM_ENTITY_REFERENCE_NODE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DOM_ENTITY_REFERENCE_NODE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOM_ENTITY_REFERENCE_NODE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ATTRIBUTE_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ATTRIBUTE_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ATTRIBUTE_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_attribute_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_CDATA_SECTION_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_CDATA_SECTION_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_CDATA_SECTION_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_cdata_section_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_COMMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_COMMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_COMMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_comment_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_FRAGMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_FRAGMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_FRAGMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_fragment_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_CONTAINED_BY",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_contained_by"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_CONTAINS"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_CONTAINS",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_contains"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_DISCONNECTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_DISCONNECTED"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_DISCONNECTED",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_disconnected"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_FOLLOWING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_FOLLOWING"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_FOLLOWING",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_following"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_implementation_specific"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_PRECEDING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_POSITION_PRECEDING"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_POSITION_PRECEDING",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_position_preceding"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_TYPE_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOCUMENT_TYPE_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOCUMENT_TYPE_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_document_type_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ELEMENT_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ELEMENT_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ELEMENT_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_element_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ENTITY_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_entity_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_REFERENCE_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_REFERENCE_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_ENTITY_REFERENCE_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_ENTITY_REFERENCE_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_entity_reference_node"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NOTATION_NODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NOTATION_NODE"
        }
      ],
      "role": "symbol",
      "title": "DOM_NOTATION_NODE",
      "type": "topic",
      "url": "/documentation/webkit/dom_notation_node"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOM_ENTITY_REFERENCE_NODE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ENTITY_REFERENCE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_ATTRIBUTE_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_CDATA_SECTION_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_COMMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_FRAGMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINED_BY",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_CONTAINS",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_DISCONNECTED",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_FOLLOWING",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_POSITION_PRECEDING",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOCUMENT_TYPE_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ELEMENT_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_ENTITY_NODE",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NOTATION_NODE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "DOM_ENTITY_REFERENCE_NODE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_FRAGMENT_NODE/title",
          "value": "DOM_DOCUMENT_FRAGMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_FRAGMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_FRAGMENT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC/title",
          "value": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINED_BY/title",
          "value": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINED_BY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_CONTAINED_BY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_FOLLOWING/title",
          "value": "DOM_DOCUMENT_POSITION_FOLLOWING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_FOLLOWING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_FOLLOWING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CDATA_SECTION_NODE/title",
          "value": "DOM_CDATA_SECTION_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_CDATA_SECTION_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_CDATA_SECTION_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_PRECEDING/title",
          "value": "DOM_DOCUMENT_POSITION_PRECEDING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_PRECEDING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_PRECEDING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_NODE/title",
          "value": "DOM_DOCUMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_REFERENCE_NODE/title",
          "value": "DOM_ENTITY_REFERENCE_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_REFERENCE_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ENTITY_REFERENCE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOTATION_NODE/title",
          "value": "DOM_NOTATION_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOTATION_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NOTATION_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_DISCONNECTED/title",
          "value": "DOM_DOCUMENT_POSITION_DISCONNECTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_DISCONNECTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_DISCONNECTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_NODE/title",
          "value": "DOM_ENTITY_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ENTITY_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ENTITY_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_TYPE_NODE/title",
          "value": "DOM_DOCUMENT_TYPE_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_TYPE_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_TYPE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINS/title",
          "value": "DOM_DOCUMENT_POSITION_CONTAINS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOCUMENT_POSITION_CONTAINS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOCUMENT_POSITION_CONTAINS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ATTRIBUTE_NODE/title",
          "value": "DOM_ATTRIBUTE_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ATTRIBUTE_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ATTRIBUTE_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ELEMENT_NODE/title",
          "value": "DOM_ELEMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_ELEMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_ELEMENT_NODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_COMMENT_NODE/title",
          "value": "DOM_COMMENT_NODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_COMMENT_NODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_COMMENT_NODE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/dom_entity_reference_node"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/dom_entity_reference_node"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
