{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@DOMExceptionCode@DOM_INVALID_CHARACTER_ERR",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOM_INVALID_CHARACTER_ERR"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@DOMExceptionCode",
        "text": "DOMExceptionCode"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOM_INVALID_CHARACTER_ERR"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DOM_INVALID_CHARACTER_ERR"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOM_INVALID_CHARACTER_ERR"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMExceptionCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@DOMExceptionCode",
              "text": "DOMExceptionCode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMExceptionCode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMExceptionCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMExceptionCode"
        }
      ],
      "role": "symbol",
      "title": "DOMExceptionCode",
      "type": "topic",
      "url": "/documentation/webkit/domexceptioncode"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOMSTRING_SIZE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOMSTRING_SIZE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOMSTRING_SIZE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_domstring_size_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_HIERARCHY_REQUEST_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_HIERARCHY_REQUEST_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_HIERARCHY_REQUEST_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_hierarchy_request_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INDEX_SIZE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INDEX_SIZE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INDEX_SIZE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_index_size_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INUSE_ATTRIBUTE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INUSE_ATTRIBUTE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INUSE_ATTRIBUTE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_inuse_attribute_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_ACCESS_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_ACCESS_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_ACCESS_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_access_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_CHARACTER_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_CHARACTER_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_CHARACTER_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_character_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_MODIFICATION_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_MODIFICATION_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_MODIFICATION_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_modification_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_STATE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_STATE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_STATE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_state_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NAMESPACE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NAMESPACE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_NAMESPACE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_namespace_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_FOUND_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NOT_FOUND_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_FOUND_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NOT_FOUND_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_NOT_FOUND_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_not_found_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_SUPPORTED_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NOT_SUPPORTED_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_SUPPORTED_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NOT_SUPPORTED_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_NOT_SUPPORTED_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_not_supported_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NO_DATA_ALLOWED_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NO_DATA_ALLOWED_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NO_DATA_ALLOWED_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NO_DATA_ALLOWED_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_NO_DATA_ALLOWED_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_no_data_allowed_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NO_MODIFICATION_ALLOWED_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NO_MODIFICATION_ALLOWED_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NO_MODIFICATION_ALLOWED_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NO_MODIFICATION_ALLOWED_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_NO_MODIFICATION_ALLOWED_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_no_modification_allowed_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_SYNTAX_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_SYNTAX_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_SYNTAX_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_SYNTAX_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_SYNTAX_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_syntax_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_WRONG_DOCUMENT_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_WRONG_DOCUMENT_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_WRONG_DOCUMENT_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_WRONG_DOCUMENT_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_WRONG_DOCUMENT_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_wrong_document_err"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_FOUND_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_SUPPORTED_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NO_DATA_ALLOWED_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NO_MODIFICATION_ALLOWED_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_SYNTAX_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_WRONG_DOCUMENT_ERR"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOM_INVALID_CHARACTER_ERR"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_CHARACTER_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/DOMExceptionCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_FOUND_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NOT_SUPPORTED_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NO_DATA_ALLOWED_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NO_MODIFICATION_ALLOWED_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_SYNTAX_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_WRONG_DOCUMENT_ERR"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "DOM_INVALID_CHARACTER_ERR"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NO_DATA_ALLOWED_ERR/title",
          "value": "DOM_NO_DATA_ALLOWED_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NO_DATA_ALLOWED_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NO_DATA_ALLOWED_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INUSE_ATTRIBUTE_ERR/title",
          "value": "DOM_INUSE_ATTRIBUTE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INUSE_ATTRIBUTE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INUSE_ATTRIBUTE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WRONG_DOCUMENT_ERR/title",
          "value": "DOM_WRONG_DOCUMENT_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_WRONG_DOCUMENT_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_WRONG_DOCUMENT_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SYNTAX_ERR/title",
          "value": "DOM_SYNTAX_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_SYNTAX_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_SYNTAX_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_STATE_ERR/title",
          "value": "DOM_INVALID_STATE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_STATE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_STATE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOMSTRING_SIZE_ERR/title",
          "value": "DOM_DOMSTRING_SIZE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOMSTRING_SIZE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOMSTRING_SIZE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOT_SUPPORTED_ERR/title",
          "value": "DOM_NOT_SUPPORTED_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOT_SUPPORTED_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NOT_SUPPORTED_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOT_FOUND_ERR/title",
          "value": "DOM_NOT_FOUND_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NOT_FOUND_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NOT_FOUND_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_MODIFICATION_ERR/title",
          "value": "DOM_INVALID_MODIFICATION_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_MODIFICATION_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_MODIFICATION_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_CHARACTER_ERR/title",
          "value": "DOM_INVALID_CHARACTER_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_CHARACTER_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_CHARACTER_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_ACCESS_ERR/title",
          "value": "DOM_INVALID_ACCESS_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_ACCESS_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_ACCESS_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NAMESPACE_ERR/title",
          "value": "DOM_NAMESPACE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NAMESPACE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NAMESPACE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_HIERARCHY_REQUEST_ERR/title",
          "value": "DOM_HIERARCHY_REQUEST_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_HIERARCHY_REQUEST_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_HIERARCHY_REQUEST_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INDEX_SIZE_ERR/title",
          "value": "DOM_INDEX_SIZE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INDEX_SIZE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INDEX_SIZE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMExceptionCode/title",
          "value": "DOMExceptionCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMExceptionCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMExceptionCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMExceptionCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMExceptionCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NO_MODIFICATION_ALLOWED_ERR/title",
          "value": "DOM_NO_MODIFICATION_ALLOWED_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NO_MODIFICATION_ALLOWED_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NO_MODIFICATION_ALLOWED_ERR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/dom_invalid_character_err"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/dom_invalid_character_err"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
