{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMCSSRule"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"]}],"metadata":{"externalID":"c:objc(cs)DOMCSSPageRule","platforms":[{"name":"macOS","deprecatedAt":"10.14","unavailable":false,"beta":false,"introducedAt":"10.4","deprecated":false}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSPageRule"}],"navigatorTitle":[{"kind":"identifier","text":"DOMCSSPageRule"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","title":"DOMCSSPageRule","modules":[{"name":"WebKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/selectorText","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/style"]}],"seeAlsoSections":[{"title":"Document Object Model (DOM) APIs","generated":true,"anchor":"Document-Object-Model-DOM-APIs","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSPageRule","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["/documentation/webkit/domcsspagerule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/webkit/domcsspagerule"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule":{"kind":"symbol","title":"DOMCSSMediaRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"deprecated":true,"url":"/documentation/webkit/domcssmediarule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSMediaRule"}]},"doc://com.externally.resolved.symbol/s:SQ":{"title":"Equatable","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule":{"kind":"symbol","title":"DOMCSSFontFaceRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"deprecated":true,"url":"/documentation/webkit/domcssfontfacerule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSFontFaceRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMBlob":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMBlob","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMBlob","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMBlob","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMBlob","url":"/documentation/webkit/domblob","deprecated":true},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","title":"NSCopying"},"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCharacterData","kind":"identifier"}],"url":"/documentation/webkit/domcharacterdata","title":"DOMCharacterData","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOMCharacterData","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","type":"topic","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRuleList","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRuleList","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRuleList","url":"/documentation/webkit/domcssrulelist","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRule","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRule","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRule","url":"/documentation/webkit/domcssrule","deprecated":true},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"NSObjectProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMAttr":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAttr"}],"url":"/documentation/webkit/domattr","title":"DOMAttr","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAttr","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAttr"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSPageRule"}],"url":"/documentation/webkit/domcsspagerule","title":"DOMCSSPageRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSPageRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule":{"url":"/documentation/webkit/domcssimportrule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSImportRule"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSImportRule"}],"deprecated":true,"title":"DOMCSSImportRule","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCDATASection"}],"url":"/documentation/webkit/domcdatasection","title":"DOMCDATASection","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCDATASection"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCounter":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOMCounter"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCounter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCounter"}],"role":"symbol","kind":"symbol","title":"DOMCounter","url":"/documentation/webkit/domcounter","deprecated":true},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","url":"/documentation/Swift/CVarArg","type":"topic","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/selectorText":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectorText"}],"deprecated":true,"abstract":[],"type":"topic","url":"/documentation/webkit/domcsspagerule/selectortext","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/selectorText","title":"selectorText","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectorText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]},"doc://com.apple.webkit/documentation/WebKit/DOMComment":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMComment","abstract":[],"role":"symbol","title":"DOMComment","url":"/documentation/webkit/domcomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMComment"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMComment"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration":{"navigatorTitle":[{"kind":"identifier","text":"DOMCSSStyleDeclaration"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSStyleDeclaration"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domcssstyledeclaration","title":"DOMCSSStyleDeclaration"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"kind":"symbol","type":"topic","role":"symbol","title":"CustomDebugStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSCharsetRule"}],"url":"/documentation/webkit/domcsscharsetrule","title":"DOMCSSCharsetRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSCharsetRule"}]},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/style":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"style"}],"title":"style","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/style","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMCSSStyleDeclaration","text":"DOMCSSStyleDeclaration"},{"kind":"text","text":"!"}],"url":"/documentation/webkit/domcsspagerule/style","kind":"symbol","deprecated":true,"abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue":{"navigatorTitle":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domcssprimitivevalue","title":"DOMCSSPrimitiveValue"},"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"type":"topic","role":"symbol","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","title":"Hashable"},"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","abstract":[],"role":"symbol","title":"DOMAbstractView","url":"/documentation/webkit/domabstractview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAbstractView"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAbstractView"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"deprecatedAt":"10.14","unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.4"}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"DOMCSSPageRule","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/selectorText","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule/style"],"anchor":"Instance-Properties"}],"path":"/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMCSSRule"]}],"path":"/relationshipsSections","op":"replace"},{"op":"replace","value":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration"],"generated":true,"anchor":"Document-Object-Model-DOM-APIs","title":"Document Object Model (DOM) APIs"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSPageRule","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","preciseIdentifier":"c:objc(cs)DOMCSSRule","text":"DOMCSSRule","kind":"typeIdentifier"}]}]},"path":"/primaryContentSections/0"},{"value":"DOMCSSMediaRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title","op":"replace"},{"value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments","op":"replace"},{"value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle","op":"replace"},{"value":"DOMCSSFontFaceRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title","op":"replace"},{"value":[{"text":"DOMCSSFontFaceRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle","op":"replace"},{"value":"DOMBlob","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title","op":"replace"},{"value":[{"text":"DOMBlob","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments","op":"replace"},{"value":[{"text":"DOMBlob","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title","value":"DOMCharacterData"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments","value":[{"text":"DOMCharacterData","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle","value":[{"kind":"identifier","text":"DOMCharacterData"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title","value":"DOMCSSRuleList"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments","value":[{"text":"DOMCSSRuleList","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle","value":[{"text":"DOMCSSRuleList","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title","value":"DOMCSSRule"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments","value":[{"kind":"identifier","text":"DOMCSSRule"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSRule"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title","value":"DOMAttr"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments","value":[{"text":"DOMAttr","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle","value":[{"text":"DOMAttr","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title","value":"DOMCSSPageRule"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments","value":[{"kind":"identifier","text":"DOMCSSPageRule"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSPageRule"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title","value":"DOMCSSImportRule"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments","value":[{"kind":"identifier","text":"DOMCSSImportRule"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSImportRule"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title","value":"DOMCDATASection"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments","value":[{"kind":"identifier","text":"DOMCDATASection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle","value":[{"kind":"identifier","text":"DOMCDATASection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title","value":"DOMCounter"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments","value":[{"kind":"identifier","text":"DOMCounter"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle","value":[{"text":"DOMCounter","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule~1selectorText/title","value":"selectorText"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule~1selectorText/fragments","value":[{"text":"selectorText","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title","value":"DOMComment"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments","value":[{"kind":"identifier","text":"DOMComment"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle","value":[{"kind":"identifier","text":"DOMComment"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSStyleDeclaration/title","value":"DOMCSSStyleDeclaration"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSStyleDeclaration/fragments","value":[{"kind":"identifier","text":"DOMCSSStyleDeclaration"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSStyleDeclaration/navigatorTitle","value":[{"text":"DOMCSSStyleDeclaration","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title","value":"DOMCSSCharsetRule"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments","value":[{"text":"DOMCSSCharsetRule","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSCharsetRule"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule~1style/title","value":"style"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule~1style/fragments","value":[{"text":"style","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title","value":"DOMCSSPrimitiveValue"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments","value":[{"text":"DOMCSSPrimitiveValue","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title","value":"DOMAbstractView"},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments","value":[{"text":"DOMAbstractView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle","value":[{"kind":"identifier","text":"DOMAbstractView"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}