{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOMEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DOMEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOMEvent"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOMEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DOMEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "role": "symbol",
      "title": "DOMAbstractView",
      "type": "topic",
      "url": "/documentation/webkit/domabstractview"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAttr": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "role": "symbol",
      "title": "DOMAttr",
      "type": "topic",
      "url": "/documentation/webkit/domattr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMBlob": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "role": "symbol",
      "title": "DOMBlob",
      "type": "topic",
      "url": "/documentation/webkit/domblob"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "role": "symbol",
      "title": "DOMCDATASection",
      "type": "topic",
      "url": "/documentation/webkit/domcdatasection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSCharsetRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsscharsetrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSFontFaceRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssfontfacerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSImportRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssimportrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSMediaRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssmediarule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPageRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsspagerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPrimitiveValue",
      "type": "topic",
      "url": "/documentation/webkit/domcssprimitivevalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRuleList",
      "type": "topic",
      "url": "/documentation/webkit/domcssrulelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "role": "symbol",
      "title": "DOMCharacterData",
      "type": "topic",
      "url": "/documentation/webkit/domcharacterdata"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMComment": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "role": "symbol",
      "title": "DOMComment",
      "type": "topic",
      "url": "/documentation/webkit/domcomment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCounter": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "role": "symbol",
      "title": "DOMCounter",
      "type": "topic",
      "url": "/documentation/webkit/domcounter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMEvent",
      "type": "topic",
      "url": "/documentation/webkit/domevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/bubbles": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bubbles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/bubbles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bubbles"
        }
      ],
      "role": "symbol",
      "title": "bubbles",
      "type": "topic",
      "url": "/documentation/webkit/domevent/bubbles"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelBubble": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelBubble"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelBubble",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelBubble"
        }
      ],
      "role": "symbol",
      "title": "cancelBubble",
      "type": "topic",
      "url": "/documentation/webkit/domevent/cancelbubble"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelable": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelable"
        }
      ],
      "role": "symbol",
      "title": "cancelable",
      "type": "topic",
      "url": "/documentation/webkit/domevent/cancelable"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/currentTarget": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentTarget"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)DOMEventTarget",
          "text": "DOMEventTarget"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/currentTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentTarget"
        }
      ],
      "role": "symbol",
      "title": "currentTarget",
      "type": "topic",
      "url": "/documentation/webkit/domevent/currenttarget"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/eventPhase": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/eventPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventPhase"
        }
      ],
      "role": "symbol",
      "title": "eventPhase",
      "type": "topic",
      "url": "/documentation/webkit/domevent/eventphase"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent(_:canBubbleArg:cancelableArg:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "canBubbleArg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cancelableArg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent(_:canBubbleArg:cancelableArg:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initEvent:canBubbleArg:cancelableArg:"
        }
      ],
      "role": "symbol",
      "title": "initEvent(_:canBubbleArg:cancelableArg:)",
      "type": "topic",
      "url": "/documentation/webkit/domevent/initevent(_:canbubblearg:cancelablearg:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent:::": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initEvent:::"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent:::",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initEvent:::"
        }
      ],
      "role": "symbol",
      "title": "initEvent:::",
      "type": "topic",
      "url": "/documentation/webkit/domevent/initevent:::"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/preventDefault()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preventDefault"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/preventDefault()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preventDefault"
        }
      ],
      "role": "symbol",
      "title": "preventDefault()",
      "type": "topic",
      "url": "/documentation/webkit/domevent/preventdefault()"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/returnValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/returnValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnValue"
        }
      ],
      "role": "symbol",
      "title": "returnValue",
      "type": "topic",
      "url": "/documentation/webkit/domevent/returnvalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/srcElement": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "srcElement"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)DOMEventTarget",
          "text": "DOMEventTarget"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/srcElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "srcElement"
        }
      ],
      "role": "symbol",
      "title": "srcElement",
      "type": "topic",
      "url": "/documentation/webkit/domevent/srcelement"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/stopPropagation()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopPropagation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/stopPropagation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopPropagation"
        }
      ],
      "role": "symbol",
      "title": "stopPropagation()",
      "type": "topic",
      "url": "/documentation/webkit/domevent/stoppropagation()"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/target": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)DOMEventTarget",
          "text": "DOMEventTarget"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/target",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/webkit/domevent/target"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/timeStamp": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DOMTimeStamp",
          "text": "DOMTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/timeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStamp"
        }
      ],
      "role": "symbol",
      "title": "timeStamp",
      "type": "topic",
      "url": "/documentation/webkit/domevent/timestamp"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent/type": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/webkit/domevent/type"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMutationEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMMutationEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMutationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMMutationEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMMutationEvent",
      "type": "topic",
      "url": "/documentation/webkit/dommutationevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMObject": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMObject"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMObject"
        }
      ],
      "role": "symbol",
      "title": "DOMObject",
      "type": "topic",
      "url": "/documentation/webkit/domobject"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMOverflowEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMOverflowEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMOverflowEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMOverflowEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMOverflowEvent",
      "type": "topic",
      "url": "/documentation/webkit/domoverflowevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMProgressEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMProgressEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMProgressEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMProgressEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMProgressEvent",
      "type": "topic",
      "url": "/documentation/webkit/domprogressevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMUIEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMUIEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMUIEvent",
      "type": "topic",
      "url": "/documentation/webkit/domuievent"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMMutationEvent",
        "doc://com.apple.webkit/documentation/WebKit/DOMOverflowEvent",
        "doc://com.apple.webkit/documentation/WebKit/DOMProgressEvent",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Object-Model-DOM-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
        "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
        "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
        "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
        "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
        "doc://com.apple.webkit/documentation/WebKit/DOMComment",
        "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
      ],
      "title": "Document Object Model (DOM) APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/bubbles",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelBubble",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelable",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/currentTarget",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/eventPhase",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/returnValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/srcElement",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/target",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/timeStamp",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/type"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent(_:canBubbleArg:cancelableArg:)",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/preventDefault()",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent/stopPropagation()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOMEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/bubbles",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelBubble",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/cancelable",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/currentTarget",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/eventPhase",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/returnValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/srcElement",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/target",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/timeStamp",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/type"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent(_:canBubbleArg:cancelableArg:)",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/initEvent:::",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/preventDefault()",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent/stopPropagation()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMMutationEvent",
                "doc://com.apple.webkit/documentation/WebKit/DOMOverflowEvent",
                "doc://com.apple.webkit/documentation/WebKit/DOMProgressEvent",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Object-Model-DOM-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
                "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
                "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
                "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
                "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
                "doc://com.apple.webkit/documentation/WebKit/DOMComment",
                "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
              ],
              "title": "Document Object Model (DOM) APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DOMEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)DOMObject",
                    "text": "DOMObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title",
          "value": "DOMCSSImportRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/title",
          "value": "DOMEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title",
          "value": "DOMCSSPageRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1cancelable/title",
          "value": "cancelable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1cancelable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cancelable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title",
          "value": "DOMCSSRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/title",
          "value": "DOMObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title",
          "value": "DOMCSSFontFaceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1srcElement/title",
          "value": "srcElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1srcElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "srcElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title",
          "value": "DOMAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title",
          "value": "DOMComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1timeStamp/title",
          "value": "timeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1timeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1eventPhase/title",
          "value": "eventPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1eventPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eventPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title",
          "value": "DOMCDATASection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title",
          "value": "DOMBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title",
          "value": "DOMCSSPrimitiveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title",
          "value": "DOMCSSCharsetRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMProgressEvent/title",
          "value": "DOMProgressEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMProgressEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMProgressEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMProgressEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMProgressEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMOverflowEvent/title",
          "value": "DOMOverflowEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMOverflowEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMOverflowEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMOverflowEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMOverflowEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title",
          "value": "DOMCSSMediaRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title",
          "value": "DOMCSSRuleList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title",
          "value": "DOMCharacterData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1returnValue/title",
          "value": "returnValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1returnValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title",
          "value": "DOMCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1target/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1target/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMutationEvent/title",
          "value": "DOMMutationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMutationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMutationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMutationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMutationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/title",
          "value": "DOMUIEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1currentTarget/title",
          "value": "currentTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1currentTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1bubbles/title",
          "value": "bubbles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1bubbles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bubbles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1stopPropagation()/title",
          "value": "stopPropagation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1stopPropagation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopPropagation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title",
          "value": "DOMAbstractView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1cancelBubble/title",
          "value": "cancelBubble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1cancelBubble/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cancelBubble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1initEvent(_:canBubbleArg:cancelableArg:)/title",
          "value": "initEvent:canBubbleArg:cancelableArg:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1initEvent(_:canBubbleArg:cancelableArg:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initEvent:canBubbleArg:cancelableArg:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1preventDefault()/title",
          "value": "preventDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent~1preventDefault()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "preventDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/domevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/domevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
