{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLEmbedElement"}],"externalID":"c:objc(cs)DOMHTMLEmbedElement","title":"DOMHTMLEmbedElement","roleHeading":"Class","modules":[{"name":"WebKit"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.4","deprecatedAt":"10.14","beta":false}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLEmbedElement"}]},"topicSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/align","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/height","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/name","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/src","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/type","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/width"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"anchor":"Document-Object-Model-DOM-APIs","title":"Document Object Model (DOM) APIs","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLEmbedElement","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/webkit/domhtmlembedelement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domhtmlembedelement"]}],"relationshipsSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","sections":[],"references":{"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","abstract":[],"role":"symbol","title":"DOMAbstractView","url":"/documentation/webkit/domabstractview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAbstractView"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAbstractView"}]},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.webkit/documentation/WebKit/DOMCounter":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOMCounter"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCounter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCounter"}],"role":"symbol","kind":"symbol","title":"DOMCounter","url":"/documentation/webkit/domcounter","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRule","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRule","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRule","url":"/documentation/webkit/domcssrule","deprecated":true},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","url":"/documentation/Swift/CVarArg","type":"topic","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue":{"navigatorTitle":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domcssprimitivevalue","title":"DOMCSSPrimitiveValue"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","title":"NSCopying"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSCharsetRule"}],"url":"/documentation/webkit/domcsscharsetrule","title":"DOMCSSCharsetRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSCharsetRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/height":{"role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/height","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"height"}],"deprecated":true,"title":"height","url":"/documentation/webkit/domhtmlembedelement/height","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule":{"kind":"symbol","title":"DOMCSSMediaRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"deprecated":true,"url":"/documentation/webkit/domcssmediarule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSMediaRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMEventTarget","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMEventTarget","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMEventTarget","url":"/documentation/webkit/domeventtarget","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCDATASection"}],"url":"/documentation/webkit/domcdatasection","title":"DOMCDATASection","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCDATASection"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSPageRule"}],"url":"/documentation/webkit/domcsspagerule","title":"DOMCSSPageRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSPageRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRuleList","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRuleList","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRuleList","url":"/documentation/webkit/domcssrulelist","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/name":{"role":"symbol","type":"topic","title":"name","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/name","abstract":[],"url":"/documentation/webkit/domhtmlembedelement/name","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"NSObjectProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/width":{"role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/width","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"width"}],"deprecated":true,"title":"width","url":"/documentation/webkit/domhtmlembedelement/width","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCharacterData","kind":"identifier"}],"url":"/documentation/webkit/domcharacterdata","title":"DOMCharacterData","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOMCharacterData","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/src":{"abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/src","type":"topic","url":"/documentation/webkit/domhtmlembedelement/src","navigatorTitle":[{"kind":"identifier","text":"src"}],"title":"src","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"src","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"role":"symbol","deprecated":true},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"kind":"symbol","type":"topic","role":"symbol","title":"CustomDebugStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"title":"Equatable","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/type":{"role":"symbol","type":"topic","title":"type","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/type","abstract":[],"url":"/documentation/webkit/domhtmlembedelement/type","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement","abstract":[],"role":"symbol","title":"DOMHTMLElement","url":"/documentation/webkit/domhtmlelement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLElement"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLElement"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule":{"kind":"symbol","title":"DOMCSSFontFaceRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"deprecated":true,"url":"/documentation/webkit/domcssfontfacerule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSFontFaceRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement":{"role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLEmbedElement"}],"deprecated":true,"title":"DOMHTMLEmbedElement","url":"/documentation/webkit/domhtmlembedelement","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLEmbedElement"}]},"doc://com.apple.webkit/documentation/WebKit/DOMBlob":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMBlob","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMBlob","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMBlob","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMBlob","url":"/documentation/webkit/domblob","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMAttr":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAttr"}],"url":"/documentation/webkit/domattr","title":"DOMAttr","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAttr","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAttr"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/align":{"role":"symbol","title":"align","url":"/documentation/webkit/domhtmlembedelement/align","type":"topic","kind":"symbol","abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/align","navigatorTitle":[{"kind":"identifier","text":"align"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"align"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule":{"url":"/documentation/webkit/domcssimportrule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSImportRule"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSImportRule"}],"deprecated":true,"title":"DOMCSSImportRule","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","abstract":[]},"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"type":"topic","role":"symbol","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","title":"Hashable"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","type":"topic","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMComment":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMComment","abstract":[],"role":"symbol","title":"DOMComment","url":"/documentation/webkit/domcomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMComment"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMComment"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"name":"macOS","introducedAt":"10.4","beta":false,"unavailable":false,"deprecatedAt":"10.14","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Class"},{"path":"/metadata/title","op":"replace","value":"DOMHTMLEmbedElement"},{"path":"/metadata/symbolKind","op":"replace","value":"class"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"DOMHTMLEmbedElement"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOMHTMLEmbedElement"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/align","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/height","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/name","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/src","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/type","doc://com.apple.webkit/documentation/WebKit/DOMHTMLEmbedElement/width"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"],"kind":"relationships"}],"path":"/relationshipsSections","op":"replace"},{"value":[{"title":"Document Object Model (DOM) APIs","anchor":"Document-Object-Model-DOM-APIs","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLEmbedElement","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement","preciseIdentifier":"c:objc(cs)DOMHTMLElement","text":"DOMHTMLElement","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"DOMAbstractView","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title"},{"op":"replace","value":[{"text":"DOMAbstractView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMAbstractView"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle"},{"op":"replace","value":"DOMCounter","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCounter"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCounter"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle"},{"op":"replace","value":"DOMCSSRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title"},{"op":"replace","value":[{"text":"DOMCSSRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle"},{"value":"DOMCSSPrimitiveValue","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle","op":"replace"},{"value":"DOMCSSCharsetRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title","op":"replace"},{"value":[{"text":"DOMCSSCharsetRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSCharsetRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle","op":"replace"},{"value":"height","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1height/title","op":"replace"},{"value":[{"kind":"identifier","text":"height"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1height/fragments","op":"replace"},{"value":"DOMCSSMediaRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments","op":"replace"},{"value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle","op":"replace"},{"value":"DOMEventTarget","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/title","op":"replace"},{"value":[{"text":"DOMEventTarget","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMEventTarget"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/navigatorTitle","op":"replace"},{"value":"DOMCDATASection","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title","op":"replace"},{"value":[{"text":"DOMCDATASection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments","op":"replace"},{"value":[{"text":"DOMCDATASection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle","op":"replace"},{"value":"DOMCSSPageRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title","op":"replace"},{"value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments","op":"replace"},{"value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle","op":"replace"},{"value":"DOMCSSRuleList","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSRuleList"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSRuleList"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle","op":"replace"},{"value":"name","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1name/title","op":"replace"},{"value":[{"kind":"identifier","text":"name"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1name/fragments","op":"replace"},{"value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace"},{"value":"width","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1width/title","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1width/fragments","op":"replace"},{"value":"DOMCharacterData","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title","op":"replace"},{"value":[{"text":"DOMCharacterData","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCharacterData"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle","op":"replace"},{"value":"src","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1src/title","op":"replace"},{"value":[{"kind":"identifier","text":"src"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1src/fragments","op":"replace"},{"value":"type","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1type/title","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1type/fragments","op":"replace"},{"value":"DOMHTMLElement","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMHTMLElement"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMHTMLElement"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/navigatorTitle","op":"replace"},{"value":"DOMCSSFontFaceRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments","op":"replace"},{"value":[{"text":"DOMCSSFontFaceRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle","op":"replace"},{"value":"DOMHTMLEmbedElement","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement/title","op":"replace"},{"value":[{"text":"DOMHTMLEmbedElement","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement/fragments","op":"replace"},{"value":[{"text":"DOMHTMLEmbedElement","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement/navigatorTitle","op":"replace"},{"value":"DOMBlob","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title","op":"replace"},{"value":[{"text":"DOMBlob","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments","op":"replace"},{"value":[{"text":"DOMBlob","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle","op":"replace"},{"value":"DOMAttr","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMAttr"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMAttr"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle","op":"replace"},{"value":"align","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1align/title","op":"replace"},{"value":[{"text":"align","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLEmbedElement~1align/fragments","op":"replace"},{"value":"DOMCSSImportRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSImportRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOMCSSImportRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle","op":"replace"},{"value":"DOMComment","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOMComment"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments","op":"replace"},{"value":[{"text":"DOMComment","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}