{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/webkit/domhtmltablerowelement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domhtmltablerowelement"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"metadata":{"modules":[{"name":"WebKit"}],"externalID":"c:objc(cs)DOMHTMLTableRowElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLTableRowElement"}],"platforms":[{"introducedAt":"10.4","unavailable":false,"name":"macOS","deprecated":false,"deprecatedAt":"10.14","beta":false}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLTableRowElement"}],"symbolKind":"class","title":"DOMHTMLTableRowElement"},"topicSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/align","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/cells","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/ch","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/chOff","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/rowIndex","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/sectionRowIndex","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/vAlign"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/deleteCell(_:)","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/insertCell(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"title":"Document Object Model (DOM) APIs","generated":true,"anchor":"Document-Object-Model-DOM-APIs"}],"kind":"symbol","sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLTableRowElement","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement","interfaceLanguage":"swift"},"references":{"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMEventTarget","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMEventTarget","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMEventTarget","url":"/documentation/webkit/domeventtarget","deprecated":true},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","type":"topic","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"type":"topic","role":"symbol","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","title":"Hashable"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/cells":{"kind":"symbol","title":"cells","role":"symbol","abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/cells","navigatorTitle":[{"kind":"identifier","text":"cells"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cells"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)DOMHTMLCollection","kind":"typeIdentifier","text":"DOMHTMLCollection"},{"kind":"text","text":"!"}],"type":"topic","url":"/documentation/webkit/domhtmltablerowelement/cells","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/rowIndex":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"deprecated":true,"abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/rowIndex","navigatorTitle":[{"kind":"identifier","text":"rowIndex"}],"title":"rowIndex","role":"symbol","url":"/documentation/webkit/domhtmltablerowelement/rowindex"},"doc://com.apple.webkit/documentation/WebKit/DOMBlob":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMBlob","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMBlob","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMBlob","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMBlob","url":"/documentation/webkit/domblob","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRule","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRule","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRule","url":"/documentation/webkit/domcssrule","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/align":{"url":"/documentation/webkit/domhtmltablerowelement/align","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"align"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"align"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/align","type":"topic","title":"align"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor":{"url":"/documentation/webkit/domhtmltablerowelement/bgcolor","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bgColor"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor","type":"topic","title":"bgColor"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement","abstract":[],"role":"symbol","title":"DOMHTMLElement","url":"/documentation/webkit/domhtmlelement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLElement"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLElement"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRuleList","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRuleList","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRuleList","url":"/documentation/webkit/domcssrulelist","deprecated":true},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"kind":"symbol","type":"topic","role":"symbol","title":"CustomDebugStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"title":"Equatable","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement":{"kind":"symbol","title":"DOMHTMLTableRowElement","role":"symbol","abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement","navigatorTitle":[{"text":"DOMHTMLTableRowElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLTableRowElement","kind":"identifier"}],"type":"topic","url":"/documentation/webkit/domhtmltablerowelement","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMAttr":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAttr"}],"url":"/documentation/webkit/domattr","title":"DOMAttr","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAttr","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAttr"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCounter":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOMCounter"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCounter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCounter"}],"role":"symbol","kind":"symbol","title":"DOMCounter","url":"/documentation/webkit/domcounter","deprecated":true},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"NSObjectProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSCharsetRule"}],"url":"/documentation/webkit/domcsscharsetrule","title":"DOMCSSCharsetRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSCharsetRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule":{"url":"/documentation/webkit/domcssimportrule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSImportRule"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSImportRule"}],"deprecated":true,"title":"DOMCSSImportRule","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/vAlign":{"url":"/documentation/webkit/domhtmltablerowelement/valign","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vAlign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"vAlign"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/vAlign","type":"topic","title":"vAlign"},"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCDATASection"}],"url":"/documentation/webkit/domcdatasection","title":"DOMCDATASection","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCDATASection"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/insertCell(_:)":{"role":"symbol","url":"/documentation/webkit/domhtmltablerowelement/insertcell(_:)","deprecated":true,"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"insertCell:"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/insertCell(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertCell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)DOMHTMLElement","kind":"typeIdentifier","text":"DOMHTMLElement"},{"kind":"text","text":"!"}],"title":"insertCell(_:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","url":"/documentation/Swift/CVarArg","type":"topic","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","title":"NSCopying"},"doc://com.apple.webkit/documentation/WebKit/DOMComment":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMComment","abstract":[],"role":"symbol","title":"DOMComment","url":"/documentation/webkit/domcomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMComment"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMComment"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule":{"kind":"symbol","title":"DOMCSSFontFaceRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"deprecated":true,"url":"/documentation/webkit/domcssfontfacerule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSFontFaceRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSPageRule"}],"url":"/documentation/webkit/domcsspagerule","title":"DOMCSSPageRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSPageRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","abstract":[],"role":"symbol","title":"DOMAbstractView","url":"/documentation/webkit/domabstractview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAbstractView"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAbstractView"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue":{"navigatorTitle":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domcssprimitivevalue","title":"DOMCSSPrimitiveValue"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule":{"kind":"symbol","title":"DOMCSSMediaRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"deprecated":true,"url":"/documentation/webkit/domcssmediarule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSMediaRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/sectionRowIndex":{"role":"symbol","url":"/documentation/webkit/domhtmltablerowelement/sectionrowindex","deprecated":true,"abstract":[],"type":"topic","navigatorTitle":[{"text":"sectionRowIndex","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/sectionRowIndex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionRowIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"sectionRowIndex","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/deleteCell(_:)":{"role":"symbol","url":"/documentation/webkit/domhtmltablerowelement/deletecell(_:)","deprecated":true,"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteCell:"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/deleteCell(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteCell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"deleteCell(_:)","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/chOff":{"role":"symbol","url":"/documentation/webkit/domhtmltablerowelement/choff","deprecated":true,"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"chOff"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/chOff","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chOff","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"chOff","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/ch":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/ch","kind":"symbol","type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domhtmltablerowelement/ch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"ch"}],"title":"ch","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCharacterData","kind":"identifier"}],"url":"/documentation/webkit/domcharacterdata","title":"DOMCharacterData","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOMCharacterData","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"10.4","name":"macOS","beta":false,"deprecated":false,"deprecatedAt":"10.14"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Class","op":"replace"},{"path":"/metadata/title","value":"DOMHTMLTableRowElement","op":"replace"},{"path":"/metadata/symbolKind","value":"class","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"DOMHTMLTableRowElement"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"DOMHTMLTableRowElement","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"generated":true,"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/align","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/cells","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/ch","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/chOff","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/rowIndex","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/sectionRowIndex","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/vAlign"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/deleteCell(_:)","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/insertCell(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"],"title":"Inherits From"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"anchor":"Document-Object-Model-DOM-APIs","generated":true,"title":"Document Object Model (DOM) APIs","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLTableRowElement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMHTMLElement","text":"DOMHTMLElement","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"}],"platforms":["macOS"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/title","value":"DOMEventTarget","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOMEventTarget"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/fragments"},{"op":"replace","value":[{"text":"DOMEventTarget","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/navigatorTitle"},{"op":"replace","value":"cells","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1cells/title"},{"op":"replace","value":[{"text":"cells","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1cells/fragments"},{"op":"replace","value":"rowIndex","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1rowIndex/title"},{"op":"replace","value":[{"text":"rowIndex","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1rowIndex/fragments"},{"op":"replace","value":"DOMBlob","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMBlob"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMBlob"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle"},{"op":"replace","value":"DOMCSSRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title"},{"op":"replace","value":[{"text":"DOMCSSRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle"},{"op":"replace","value":"align","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1align/title"},{"op":"replace","value":[{"kind":"identifier","text":"align"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1align/fragments"},{"op":"replace","value":"bgColor","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1bgColor/title"},{"op":"replace","value":[{"text":"bgColor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1bgColor/fragments"},{"op":"replace","value":"DOMHTMLElement","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMHTMLElement"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMHTMLElement"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/navigatorTitle"},{"op":"replace","value":"DOMCSSRuleList","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title"},{"op":"replace","value":[{"text":"DOMCSSRuleList","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments"},{"op":"replace","value":[{"text":"DOMCSSRuleList","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle"},{"op":"replace","value":"DOMHTMLTableRowElement","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMHTMLTableRowElement"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMHTMLTableRowElement"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement/navigatorTitle"},{"op":"replace","value":"DOMAttr","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title"},{"op":"replace","value":[{"text":"DOMAttr","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments"},{"op":"replace","value":[{"text":"DOMAttr","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle"},{"op":"replace","value":"DOMCounter","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title"},{"op":"replace","value":[{"text":"DOMCounter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCounter"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"DOMCSSCharsetRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSCharsetRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSCharsetRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle"},{"op":"replace","value":"DOMCSSImportRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title"},{"op":"replace","value":[{"text":"DOMCSSImportRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSImportRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle"},{"op":"replace","value":"vAlign","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1vAlign/title"},{"op":"replace","value":[{"kind":"identifier","text":"vAlign"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1vAlign/fragments"},{"op":"replace","value":"DOMCDATASection","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCDATASection"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments"},{"op":"replace","value":[{"text":"DOMCDATASection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle"},{"op":"replace","value":"insertCell:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1insertCell(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"insertCell:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1insertCell(_:)/fragments"},{"op":"replace","value":"DOMComment","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title"},{"op":"replace","value":[{"text":"DOMComment","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments"},{"op":"replace","value":[{"text":"DOMComment","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle"},{"op":"replace","value":"DOMCSSFontFaceRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments"},{"op":"replace","value":[{"text":"DOMCSSFontFaceRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle"},{"op":"replace","value":"DOMCSSPageRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title"},{"op":"replace","value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSPageRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle"},{"op":"replace","value":"DOMAbstractView","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMAbstractView"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments"},{"op":"replace","value":[{"text":"DOMAbstractView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle"},{"op":"replace","value":"DOMCSSPrimitiveValue","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle"},{"op":"replace","value":"DOMCSSMediaRule","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title"},{"op":"replace","value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle"},{"op":"replace","value":"sectionRowIndex","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1sectionRowIndex/title"},{"op":"replace","value":[{"text":"sectionRowIndex","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1sectionRowIndex/fragments"},{"op":"replace","value":"deleteCell:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1deleteCell(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deleteCell:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1deleteCell(_:)/fragments"},{"op":"replace","value":"chOff","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1chOff/title"},{"op":"replace","value":[{"text":"chOff","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1chOff/fragments"},{"op":"replace","value":"ch","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1ch/title"},{"op":"replace","value":[{"kind":"identifier","text":"ch"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1ch/fragments"},{"op":"replace","value":"DOMCharacterData","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMCharacterData"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments"},{"op":"replace","value":[{"text":"DOMCharacterData","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}