{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/webkit/domhtmllinkelement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domhtmllinkelement"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLLinkElement"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"seeAlsoSections":[{"generated":true,"title":"Document Object Model (DOM) APIs","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"anchor":"Document-Object-Model-DOM-APIs"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/absoluteLinkURL","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/charset","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/disabled","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/href","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/hreflang","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/media","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rel","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rev","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/sheet","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/target","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/type"],"anchor":"Instance-Properties"}],"kind":"symbol","metadata":{"platforms":[{"deprecatedAt":"10.14","beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.4"}],"roleHeading":"Class","externalID":"c:objc(cs)DOMHTMLLinkElement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLLinkElement","kind":"identifier"}],"modules":[{"name":"WebKit"}],"symbolKind":"class","navigatorTitle":[{"text":"DOMHTMLLinkElement","kind":"identifier"}],"title":"DOMHTMLLinkElement","role":"symbol"},"references":{"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/absoluteLinkURL":{"type":"topic","title":"absoluteLinkURL","url":"/documentation/webkit/domhtmllinkelement/absolutelinkurl","navigatorTitle":[{"text":"absoluteLinkURL","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"absoluteLinkURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"!","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/absoluteLinkURL","abstract":[]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","title":"NSCopying"},"doc://com.apple.webkit/documentation/WebKit/DOMCounter":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOMCounter"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCounter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCounter"}],"role":"symbol","kind":"symbol","title":"DOMCounter","url":"/documentation/webkit/domcounter","deprecated":true},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"NSObjectProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRule","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRule","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRule","url":"/documentation/webkit/domcssrule","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/media":{"kind":"symbol","url":"/documentation/webkit/domhtmllinkelement/media","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"media"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"role":"symbol","title":"media","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/media","abstract":[],"deprecated":true,"navigatorTitle":[{"text":"media","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCDATASection"}],"url":"/documentation/webkit/domcdatasection","title":"DOMCDATASection","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCDATASection"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSCharsetRule"}],"url":"/documentation/webkit/domcsscharsetrule","title":"DOMCSSCharsetRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSCharsetRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule":{"kind":"symbol","title":"DOMCSSFontFaceRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"deprecated":true,"url":"/documentation/webkit/domcssfontfacerule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSFontFaceRule"}]},"doc://com.externally.resolved.symbol/s:SQ":{"title":"Equatable","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","url":"/documentation/Swift/CVarArg","type":"topic","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMEventTarget","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMEventTarget","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMEventTarget","url":"/documentation/webkit/domeventtarget","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule":{"url":"/documentation/webkit/domcssimportrule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSImportRule"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSImportRule"}],"deprecated":true,"title":"DOMCSSImportRule","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/href":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/href","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"href"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","title":"href","deprecated":true,"role":"symbol","url":"/documentation/webkit/domhtmllinkelement/href","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"href"}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"kind":"symbol","type":"topic","role":"symbol","title":"CustomDebugStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/hreflang":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/hreflang","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hreflang","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"deprecated":true,"role":"symbol","abstract":[],"navigatorTitle":[{"text":"hreflang","kind":"identifier"}],"url":"/documentation/webkit/domhtmllinkelement/hreflang","title":"hreflang","type":"topic","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue":{"navigatorTitle":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domcssprimitivevalue","title":"DOMCSSPrimitiveValue"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement":{"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement","abstract":[],"title":"DOMHTMLLinkElement","url":"/documentation/webkit/domhtmllinkelement","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLLinkElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLLinkElement"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/disabled":{"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/disabled","abstract":[],"title":"disabled","url":"/documentation/webkit/domhtmllinkelement/disabled","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"disabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rel":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"deprecated":true,"role":"symbol","abstract":[],"navigatorTitle":[{"text":"rel","kind":"identifier"}],"url":"/documentation/webkit/domhtmllinkelement/rel","title":"rel","type":"topic","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMBlob":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMBlob","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMBlob","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMBlob","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMBlob","url":"/documentation/webkit/domblob","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule":{"kind":"symbol","title":"DOMCSSMediaRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"deprecated":true,"url":"/documentation/webkit/domcssmediarule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSMediaRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rev":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rev","abstract":[],"deprecated":true,"type":"topic","title":"rev","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"rev","kind":"identifier"}],"url":"/documentation/webkit/domhtmllinkelement/rev","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rev","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/type":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/type","deprecated":true,"type":"topic","navigatorTitle":[{"text":"type","kind":"identifier"}],"role":"symbol","url":"/documentation/webkit/domhtmllinkelement/type","abstract":[],"title":"type","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMComment":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMComment","abstract":[],"role":"symbol","title":"DOMComment","url":"/documentation/webkit/domcomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMComment"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMComment"}]},"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","abstract":[],"role":"symbol","title":"DOMAbstractView","url":"/documentation/webkit/domabstractview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAbstractView"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAbstractView"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/charset":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/charset","abstract":[],"deprecated":true,"type":"topic","title":"charset","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"charset","kind":"identifier"}],"url":"/documentation/webkit/domhtmllinkelement/charset","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"charset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/sheet":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/sheet","abstract":[],"deprecated":true,"type":"topic","title":"sheet","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"sheet","kind":"identifier"}],"url":"/documentation/webkit/domhtmllinkelement/sheet","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DOMStyleSheet","preciseIdentifier":"c:objc(cs)DOMStyleSheet","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/target":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/target","abstract":[],"deprecated":true,"type":"topic","title":"target","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"target"}],"url":"/documentation/webkit/domhtmllinkelement/target","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.apple.webkit/documentation/WebKit/DOMAttr":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAttr"}],"url":"/documentation/webkit/domattr","title":"DOMAttr","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAttr","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAttr"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","type":"topic","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRuleList","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRuleList","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRuleList","url":"/documentation/webkit/domcssrulelist","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCharacterData","kind":"identifier"}],"url":"/documentation/webkit/domcharacterdata","title":"DOMCharacterData","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOMCharacterData","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSPageRule"}],"url":"/documentation/webkit/domcsspagerule","title":"DOMCSSPageRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSPageRule"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"type":"topic","role":"symbol","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","title":"Hashable"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement","abstract":[],"role":"symbol","title":"DOMHTMLElement","url":"/documentation/webkit/domhtmlelement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMHTMLElement"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMHTMLElement"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"10.4","beta":false,"name":"macOS","deprecated":false,"deprecatedAt":"10.14","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"value":"DOMHTMLLinkElement","op":"replace","path":"/metadata/title"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"DOMHTMLLinkElement","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"DOMHTMLLinkElement","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/absoluteLinkURL","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/charset","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/disabled","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/href","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/hreflang","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/media","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rel","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/rev","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/sheet","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/target","doc://com.apple.webkit/documentation/WebKit/DOMHTMLLinkElement/type"]}],"op":"replace","path":"/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement"]}],"op":"replace","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"title":"Document Object Model (DOM) APIs","generated":true,"anchor":"Document-Object-Model-DOM-APIs"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLLinkElement","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMHTMLElement","text":"DOMHTMLElement","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLElement","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"absoluteLinkURL","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1absoluteLinkURL/title"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1absoluteLinkURL/fragments","value":[{"text":"absoluteLinkURL","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title","value":"DOMCounter","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments","value":[{"text":"DOMCounter","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle","value":[{"text":"DOMCounter","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title","value":"DOMCSSRule","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments","value":[{"kind":"identifier","text":"DOMCSSRule"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle","value":[{"text":"DOMCSSRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1media/title","value":"media","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1media/fragments","value":[{"text":"media","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title","value":"DOMCDATASection","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments","value":[{"kind":"identifier","text":"DOMCDATASection"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle","value":[{"kind":"identifier","text":"DOMCDATASection"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title","value":"DOMCSSCharsetRule","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments","value":[{"text":"DOMCSSCharsetRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle","value":[{"text":"DOMCSSCharsetRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title","value":"DOMCSSFontFaceRule","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments","value":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle","value":[{"text":"DOMCSSFontFaceRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/title","value":"DOMEventTarget","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/fragments","value":[{"text":"DOMEventTarget","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/navigatorTitle","value":[{"kind":"identifier","text":"DOMEventTarget"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title","value":"DOMCSSImportRule","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments","value":[{"kind":"identifier","text":"DOMCSSImportRule"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle","value":[{"text":"DOMCSSImportRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1href/title","value":"href","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1href/fragments","value":[{"kind":"identifier","text":"href"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1hreflang/title","value":"hreflang","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1hreflang/fragments","value":[{"kind":"identifier","text":"hreflang"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title","value":"DOMCSSPrimitiveValue","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments","value":[{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle","value":[{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement/title","value":"DOMHTMLLinkElement","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement/fragments","value":[{"text":"DOMHTMLLinkElement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement/navigatorTitle","value":[{"kind":"identifier","text":"DOMHTMLLinkElement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1disabled/title","value":"disabled","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1disabled/fragments","value":[{"text":"disabled","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1rel/title","value":"rel","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1rel/fragments","value":[{"kind":"identifier","text":"rel"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title","value":"DOMBlob","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments","value":[{"text":"DOMBlob","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle","value":[{"text":"DOMBlob","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title","value":"DOMCSSMediaRule","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments","value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1rev/title","value":"rev","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1rev/fragments","value":[{"text":"rev","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1type/title","value":"type","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1type/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title","value":"DOMComment","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments","value":[{"kind":"identifier","text":"DOMComment"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle","value":[{"text":"DOMComment","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title","value":"DOMAbstractView","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments","value":[{"kind":"identifier","text":"DOMAbstractView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle","value":[{"kind":"identifier","text":"DOMAbstractView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1charset/title","value":"charset","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1charset/fragments","value":[{"text":"charset","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1sheet/title","value":"sheet","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1sheet/fragments","value":[{"kind":"identifier","text":"sheet"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1target/title","value":"target","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLLinkElement~1target/fragments","value":[{"text":"target","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title","value":"DOMAttr","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments","value":[{"text":"DOMAttr","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle","value":[{"kind":"identifier","text":"DOMAttr"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title","value":"DOMCSSRuleList","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments","value":[{"kind":"identifier","text":"DOMCSSRuleList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle","value":[{"kind":"identifier","text":"DOMCSSRuleList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title","value":"DOMCharacterData","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments","value":[{"text":"DOMCharacterData","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle","value":[{"text":"DOMCharacterData","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title","value":"DOMCSSPageRule","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments","value":[{"kind":"identifier","text":"DOMCSSPageRule"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle","value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/title","value":"DOMHTMLElement","op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/fragments","value":[{"text":"DOMHTMLElement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLElement/navigatorTitle","value":[{"text":"DOMHTMLElement","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}