{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DOMMouseEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOMMouseEvent"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOMMouseEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DOMMouseEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "role": "symbol",
      "title": "DOMAbstractView",
      "type": "topic",
      "url": "/documentation/webkit/domabstractview"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAttr": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "role": "symbol",
      "title": "DOMAttr",
      "type": "topic",
      "url": "/documentation/webkit/domattr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMBlob": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "role": "symbol",
      "title": "DOMBlob",
      "type": "topic",
      "url": "/documentation/webkit/domblob"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "role": "symbol",
      "title": "DOMCDATASection",
      "type": "topic",
      "url": "/documentation/webkit/domcdatasection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSCharsetRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsscharsetrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSFontFaceRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssfontfacerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSImportRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssimportrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSMediaRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssmediarule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPageRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsspagerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPrimitiveValue",
      "type": "topic",
      "url": "/documentation/webkit/domcssprimitivevalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRuleList",
      "type": "topic",
      "url": "/documentation/webkit/domcssrulelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "role": "symbol",
      "title": "DOMCharacterData",
      "type": "topic",
      "url": "/documentation/webkit/domcharacterdata"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMComment": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "role": "symbol",
      "title": "DOMComment",
      "type": "topic",
      "url": "/documentation/webkit/domcomment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCounter": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "role": "symbol",
      "title": "DOMCounter",
      "type": "topic",
      "url": "/documentation/webkit/domcounter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMMouseEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMMouseEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMMouseEvent",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/altKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "altKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/altKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "altKey"
        }
      ],
      "role": "symbol",
      "title": "altKey",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/altkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/button": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "button"
        }
      ],
      "role": "symbol",
      "title": "button",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/button"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientX": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientX"
        }
      ],
      "role": "symbol",
      "title": "clientX",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/clientx"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientY": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientY"
        }
      ],
      "role": "symbol",
      "title": "clientY",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/clienty"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/ctrlKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ctrlKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/ctrlKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ctrlKey"
        }
      ],
      "role": "symbol",
      "title": "ctrlKey",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/ctrlkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/fromElement": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fromElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMNode",
          "text": "DOMNode"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/fromElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fromElement"
        }
      ],
      "role": "symbol",
      "title": "fromElement",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/fromelement"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initMouseEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "canBubble"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cancelable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMAbstractView",
          "text": "DOMAbstractView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "detail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "screenX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "screenY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ctrlKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "altKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shiftKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "metaKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "button"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relatedTarget"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)DOMEventTarget",
          "text": "DOMEventTarget"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initMouseEvent:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:"
        }
      ],
      "role": "symbol",
      "title": "initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/initmouseevent(_:canbubble:cancelable:view:detail:screenx:screeny:clientx:clienty:ctrlkey:altkey:shiftkey:metakey:button:relatedtarget:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent:::::::::::::::": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initMouseEvent:::::::::::::::"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent:::::::::::::::",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initMouseEvent:::::::::::::::"
        }
      ],
      "role": "symbol",
      "title": "initMouseEvent:::::::::::::::",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/initmouseevent:::::::::::::::"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/metaKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metaKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/metaKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metaKey"
        }
      ],
      "role": "symbol",
      "title": "metaKey",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/metakey"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetX": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offsetX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offsetX"
        }
      ],
      "role": "symbol",
      "title": "offsetX",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/offsetx"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetY": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offsetY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offsetY"
        }
      ],
      "role": "symbol",
      "title": "offsetY",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/offsety"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/relatedTarget": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relatedTarget"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)DOMEventTarget",
          "text": "DOMEventTarget"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/relatedTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relatedTarget"
        }
      ],
      "role": "symbol",
      "title": "relatedTarget",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/relatedtarget"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenX": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screenX"
        }
      ],
      "role": "symbol",
      "title": "screenX",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/screenx"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenY": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screenY"
        }
      ],
      "role": "symbol",
      "title": "screenY",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/screeny"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/shiftKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shiftKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/shiftKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shiftKey"
        }
      ],
      "role": "symbol",
      "title": "shiftKey",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/shiftkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/toElement": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMNode",
          "text": "DOMNode"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/toElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toElement"
        }
      ],
      "role": "symbol",
      "title": "toElement",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/toelement"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/x": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "x"
        }
      ],
      "role": "symbol",
      "title": "x",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/x"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/y": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "y"
        }
      ],
      "role": "symbol",
      "title": "y",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent/y"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMUIEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMUIEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMUIEvent",
      "type": "topic",
      "url": "/documentation/webkit/domuievent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMWheelEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMWheelEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMWheelEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMWheelEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMWheelEvent",
      "type": "topic",
      "url": "/documentation/webkit/domwheelevent"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMWheelEvent"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Object-Model-DOM-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
        "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
        "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
        "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
        "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
        "doc://com.apple.webkit/documentation/WebKit/DOMComment",
        "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
      ],
      "title": "Document Object Model (DOM) APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/altKey",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/button",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientX",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientY",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/ctrlKey",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/fromElement",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/metaKey",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetX",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetY",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/relatedTarget",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenX",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenY",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/shiftKey",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/toElement",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/x",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/y"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOMMouseEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/altKey",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/button",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientX",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/clientY",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/ctrlKey",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/fromElement",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/metaKey",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetX",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/offsetY",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/relatedTarget",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenX",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/screenY",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/shiftKey",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/toElement",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/x",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/y"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent/initMouseEvent:::::::::::::::"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMWheelEvent"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Object-Model-DOM-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
                "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
                "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
                "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
                "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
                "doc://com.apple.webkit/documentation/WebKit/DOMComment",
                "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
              ],
              "title": "Document Object Model (DOM) APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DOMMouseEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)DOMUIEvent",
                    "text": "DOMUIEvent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1metaKey/title",
          "value": "metaKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1metaKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metaKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1toElement/title",
          "value": "toElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1toElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1button/title",
          "value": "button"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "button"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title",
          "value": "DOMCSSPrimitiveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title",
          "value": "DOMCharacterData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMWheelEvent/title",
          "value": "DOMWheelEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMWheelEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMWheelEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMWheelEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMWheelEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent/title",
          "value": "DOMMouseEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1x/title",
          "value": "x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1offsetX/title",
          "value": "offsetX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1offsetX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offsetX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title",
          "value": "DOMComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1fromElement/title",
          "value": "fromElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1fromElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fromElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1relatedTarget/title",
          "value": "relatedTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1relatedTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relatedTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title",
          "value": "DOMCSSMediaRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1screenX/title",
          "value": "screenX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1screenX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screenX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title",
          "value": "DOMAbstractView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1altKey/title",
          "value": "altKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1altKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "altKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1clientY/title",
          "value": "clientY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1clientY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)/title",
          "value": "initMouseEvent:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1initMouseEvent(_:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initMouseEvent:canBubble:cancelable:view:detail:screenX:screenY:clientX:clientY:ctrlKey:altKey:shiftKey:metaKey:button:relatedTarget:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title",
          "value": "DOMCSSRuleList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title",
          "value": "DOMBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title",
          "value": "DOMCSSImportRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title",
          "value": "DOMCSSPageRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title",
          "value": "DOMCSSCharsetRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title",
          "value": "DOMCSSRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title",
          "value": "DOMAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title",
          "value": "DOMCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1shiftKey/title",
          "value": "shiftKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1shiftKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shiftKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1ctrlKey/title",
          "value": "ctrlKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1ctrlKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ctrlKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1y/title",
          "value": "y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1offsetY/title",
          "value": "offsetY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1offsetY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offsetY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title",
          "value": "DOMCSSFontFaceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1clientX/title",
          "value": "clientX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1clientX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1screenY/title",
          "value": "screenY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent~1screenY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screenY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/title",
          "value": "DOMUIEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title",
          "value": "DOMCDATASection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/dommouseevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/dommouseevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
