{"seeAlsoSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"generated":true,"anchor":"Document-Object-Model-DOM-APIs","title":"Document Object Model (DOM) APIs"}],"kind":"symbol","metadata":{"platforms":[{"deprecatedAt":"10.14","name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.4"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMNode"}],"title":"DOMNode","externalID":"c:objc(cs)DOMNode","modules":[{"name":"WebKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMNode"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/webkit/domnode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/webkit/domnode"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMNode/attributes","doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI","doc://com.apple.webkit/documentation/WebKit/DOMNode/childNodes","doc://com.apple.webkit/documentation/WebKit/DOMNode/firstChild","doc://com.apple.webkit/documentation/WebKit/DOMNode/isContentEditable","doc://com.apple.webkit/documentation/WebKit/DOMNode/lastChild","doc://com.apple.webkit/documentation/WebKit/DOMNode/localName","doc://com.apple.webkit/documentation/WebKit/DOMNode/namespaceURI","doc://com.apple.webkit/documentation/WebKit/DOMNode/nextSibling","doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeName","doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeType","doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue","doc://com.apple.webkit/documentation/WebKit/DOMNode/ownerDocument","doc://com.apple.webkit/documentation/WebKit/DOMNode/parent","doc://com.apple.webkit/documentation/WebKit/DOMNode/parentElement","doc://com.apple.webkit/documentation/WebKit/DOMNode/prefix","doc://com.apple.webkit/documentation/WebKit/DOMNode/previousSibling","doc://com.apple.webkit/documentation/WebKit/DOMNode/textContent","doc://com.apple.webkit/documentation/WebKit/DOMNode/webArchive"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMNode/appendChild(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/boundingBox()","doc://com.apple.webkit/documentation/WebKit/DOMNode/cloneNode(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/compareDocumentPosition(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/contains(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/hasAttributes()","doc://com.apple.webkit/documentation/WebKit/DOMNode/hasChildNodes()","doc://com.apple.webkit/documentation/WebKit/DOMNode/insert(before:refChild:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isDefaultNamespace(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isEqualNode(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isSameNode(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported(_:version:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/lineBoxRects()","doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupNamespaceURI(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupPrefix(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/normalize()","doc://com.apple.webkit/documentation/WebKit/DOMNode/removeChild(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/DOMNode"},"relationshipsSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMDocument","doc://com.apple.webkit/documentation/WebKit/DOMDocumentFragment","doc://com.apple.webkit/documentation/WebKit/DOMDocumentType","doc://com.apple.webkit/documentation/WebKit/DOMElement","doc://com.apple.webkit/documentation/WebKit/DOMEntity","doc://com.apple.webkit/documentation/WebKit/DOMEntityReference"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}]}]}],"references":{"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule":{"url":"/documentation/webkit/domcssimportrule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSImportRule"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSImportRule"}],"deprecated":true,"title":"DOMCSSImportRule","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/textContent":{"kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"textContent"}],"title":"textContent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/textContent","type":"topic","url":"/documentation/webkit/domnode/textcontent","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMAttr":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAttr"}],"url":"/documentation/webkit/domattr","title":"DOMAttr","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAttr","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAttr"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupPrefix(_:)":{"kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"lookupPrefix:"}],"title":"lookupPrefix(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lookupPrefix"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupPrefix(_:)","type":"topic","url":"/documentation/webkit/domnode/lookupprefix(_:)","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported::":{"url":"/documentation/webkit/domnode/issupported::","title":"isSupported::","fragments":[{"text":"- ","kind":"text"},{"text":"isSupported::","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"isSupported::","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported::","kind":"symbol","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/cloneNode(_:)":{"kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"cloneNode:"}],"title":"cloneNode(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloneNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/cloneNode(_:)","type":"topic","url":"/documentation/webkit/domnode/clonenode(_:)","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/boundingBox()":{"kind":"symbol","abstract":[{"type":"text","text":"Returns a rectangle that bounds the onscreen rendering of the node."}],"navigatorTitle":[{"kind":"identifier","text":"boundingBox"}],"title":"boundingBox()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingBox","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/boundingBox()","type":"topic","url":"/documentation/webkit/domnode/boundingbox()","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/insert(before:refChild:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insert","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"before"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"refChild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!"}],"kind":"symbol","role":"symbol","title":"insert(before:refChild:)","navigatorTitle":[{"kind":"identifier","text":"insertBefore:refChild:"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/insert(before:refChild:)","abstract":[],"deprecated":true,"url":"/documentation/webkit/domnode/insert(before:refchild:)","type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMDocument":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMDocument"}],"url":"/documentation/webkit/domdocument","title":"DOMDocument","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMDocument","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMDocument"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/contains(_:)":{"title":"contains(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"deprecated":true,"url":"/documentation/webkit/domnode/contains(_:)","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/contains(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contains:"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","title":"NSCopying"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSameNode(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSameNode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","title":"isSameNode(_:)","navigatorTitle":[{"kind":"identifier","text":"isSameNode:"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSameNode(_:)","abstract":[],"deprecated":true,"url":"/documentation/webkit/domnode/issamenode(_:)","type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/attributes":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMNamedNodeMap","preciseIdentifier":"c:objc(cs)DOMNamedNodeMap"},{"kind":"text","text":"!"}],"title":"attributes","navigatorTitle":[{"kind":"identifier","text":"attributes"}],"deprecated":true,"abstract":[],"url":"/documentation/webkit/domnode/attributes","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/attributes","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule":{"kind":"symbol","title":"DOMCSSFontFaceRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"deprecated":true,"url":"/documentation/webkit/domcssfontfacerule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSFontFaceRule"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/nextSibling":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nextSibling"}],"deprecated":true,"title":"nextSibling","url":"/documentation/webkit/domnode/nextsibling","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextSibling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/nextSibling","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nodeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt16","preciseIdentifier":"s:s6UInt16V"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeType","title":"nodeType","abstract":[],"kind":"symbol","role":"symbol","url":"/documentation/webkit/domnode/nodetype","navigatorTitle":[{"text":"nodeType","kind":"identifier"}],"deprecated":true,"type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue":{"navigatorTitle":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domcssprimitivevalue","title":"DOMCSSPrimitiveValue"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupNamespaceURI(_:)":{"navigatorTitle":[{"text":"lookupNamespaceURI:","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupNamespaceURI(_:)","url":"/documentation/webkit/domnode/lookupnamespaceuri(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lookupNamespaceURI"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"deprecated":true,"title":"lookupNamespaceURI(_:)","type":"topic","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/insertBefore::":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertBefore::"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/insertBefore::","title":"insertBefore::","abstract":[],"kind":"symbol","role":"symbol","url":"/documentation/webkit/domnode/insertbefore::","navigatorTitle":[{"kind":"identifier","text":"insertBefore::"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/webArchive":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webArchive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebArchive","preciseIdentifier":"c:objc(cs)WebArchive"},{"kind":"text","text":"!"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/webArchive","title":"webArchive","abstract":[{"text":"A web archive of the content of the node and its children.","type":"text"}],"kind":"symbol","role":"symbol","url":"/documentation/webkit/domnode/webarchive","navigatorTitle":[{"kind":"identifier","text":"webArchive"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/appendChild(_:)":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/appendChild(_:)","navigatorTitle":[{"text":"appendChild:","kind":"identifier"}],"role":"symbol","abstract":[],"url":"/documentation/webkit/domnode/appendchild(_:)","type":"topic","title":"appendChild(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendChild","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"deprecated":true},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"kind":"symbol","type":"topic","role":"symbol","title":"CustomDebugStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMEntityReference":{"deprecated":true,"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMEntityReference","kind":"identifier"}],"title":"DOMEntityReference","type":"topic","kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMEntityReference","url":"/documentation/webkit/domentityreference","navigatorTitle":[{"text":"DOMEntityReference","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild::":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild::","abstract":[],"type":"topic","url":"/documentation/webkit/domnode/replacechild::","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceChild::"}],"kind":"symbol","title":"replaceChild::","navigatorTitle":[{"kind":"identifier","text":"replaceChild::"}]},"doc://com.apple.webkit/documentation/WebKit/DOMDocumentFragment":{"kind":"symbol","title":"DOMDocumentFragment","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMDocumentFragment","navigatorTitle":[{"text":"DOMDocumentFragment","kind":"identifier"}],"deprecated":true,"url":"/documentation/webkit/domdocumentfragment","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMDocumentFragment","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/childNodes":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/childNodes","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"childNodes"}],"url":"/documentation/webkit/domnode/childnodes","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNodeList","text":"DOMNodeList"},{"kind":"text","text":"!"}],"title":"childNodes","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMNode/prefix":{"deprecated":true,"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefix","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"prefix","type":"topic","kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/prefix","url":"/documentation/webkit/domnode/prefix","navigatorTitle":[{"text":"prefix","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/hasAttributes()":{"url":"/documentation/webkit/domnode/hasattributes()","type":"topic","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/hasAttributes()","role":"symbol","navigatorTitle":[{"text":"hasAttributes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAttributes"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","title":"hasAttributes()"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/hasChildNodes()":{"url":"/documentation/webkit/domnode/haschildnodes()","type":"topic","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/hasChildNodes()","role":"symbol","navigatorTitle":[{"text":"hasChildNodes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasChildNodes"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","title":"hasChildNodes()"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isEqualNode(_:)":{"url":"/documentation/webkit/domnode/isequalnode(_:)","type":"topic","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isEqualNode(_:)","role":"symbol","navigatorTitle":[{"text":"isEqualNode:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqualNode"},{"text":"(","kind":"text"},{"text":"DOMNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode"},{"text":"!) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","title":"isEqualNode(_:)"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/compareDocumentPosition(_:)":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/compareDocumentPosition(_:)","url":"/documentation/webkit/domnode/comparedocumentposition(_:)","deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"compareDocumentPosition:"}],"type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compareDocumentPosition"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DOMNode","kind":"typeIdentifier","text":"DOMNode"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"s:s6UInt16V","kind":"typeIdentifier","text":"UInt16"}],"title":"compareDocumentPosition(_:)"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeName":{"abstract":[],"role":"symbol","title":"nodeName","url":"/documentation/webkit/domnode/nodename","deprecated":true,"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeName","navigatorTitle":[{"kind":"identifier","text":"nodeName"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nodeName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"NSObjectProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMElement":{"title":"DOMElement","kind":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMElement","kind":"identifier"}],"url":"/documentation/webkit/domelement","abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMElement","navigatorTitle":[{"text":"DOMElement","kind":"identifier"}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)":{"role":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/replacechild(_:oldchild:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceChild"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"oldChild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode"},{"kind":"text","text":"!"}],"type":"topic","title":"replaceChild(_:oldChild:)","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)","navigatorTitle":[{"kind":"identifier","text":"replaceChild:oldChild:"}],"abstract":[],"kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isDefaultNamespace(_:)":{"abstract":[],"role":"symbol","title":"isDefaultNamespace(_:)","url":"/documentation/webkit/domnode/isdefaultnamespace(_:)","deprecated":true,"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isDefaultNamespace(_:)","navigatorTitle":[{"text":"isDefaultNamespace:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDefaultNamespace","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/lastChild":{"abstract":[],"role":"symbol","title":"lastChild","url":"/documentation/webkit/domnode/lastchild","deprecated":true,"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/lastChild","navigatorTitle":[{"text":"lastChild","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastChild","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue","type":"topic","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"nodeValue","kind":"identifier"}],"url":"/documentation/webkit/domnode/nodevalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nodeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"deprecated":true,"title":"nodeValue"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/parent":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/parent","type":"topic","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"parentNode","kind":"identifier"}],"url":"/documentation/webkit/domnode/parent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"deprecated":true,"title":"parent"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/ownerDocument":{"url":"/documentation/webkit/domnode/ownerdocument","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ownerDocument","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DOMDocument","preciseIdentifier":"c:objc(cs)DOMDocument","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"ownerDocument","kind":"identifier"}],"title":"ownerDocument","deprecated":true,"kind":"symbol","role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/ownerDocument","type":"topic","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/namespaceURI":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/namespaceURI","type":"topic","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"namespaceURI","kind":"identifier"}],"url":"/documentation/webkit/domnode/namespaceuri","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"namespaceURI"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"deprecated":true,"title":"namespaceURI"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/removeChild(_:)":{"kind":"symbol","type":"topic","title":"removeChild(_:)","abstract":[],"role":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/removeChild(_:)","url":"/documentation/webkit/domnode/removechild(_:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeChild","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOMNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"c:objc(cs)DOMNode","kind":"typeIdentifier","text":"DOMNode"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"removeChild:"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/firstChild":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/firstChild","type":"topic","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"firstChild"}],"url":"/documentation/webkit/domnode/firstchild","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstChild","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMNode","text":"DOMNode","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"deprecated":true,"title":"firstChild"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/parentElement":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/parentElement","abstract":[],"role":"symbol","kind":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/parentelement","navigatorTitle":[{"text":"parentElement","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentElement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DOMElement","preciseIdentifier":"c:objc(cs)DOMElement","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"parentElement"},"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMEventTarget","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMEventTarget","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMEventTarget","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMEventTarget","url":"/documentation/webkit/domeventtarget","deprecated":true},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","url":"/documentation/Swift/CVarArg","type":"topic","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCounter":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOMCounter"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCounter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCounter"}],"role":"symbol","kind":"symbol","title":"DOMCounter","url":"/documentation/webkit/domcounter","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMComment":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMComment","abstract":[],"role":"symbol","title":"DOMComment","url":"/documentation/webkit/domcomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMComment"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMComment"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/normalize()":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/normalize()","abstract":[],"role":"symbol","kind":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/normalize()","navigatorTitle":[{"text":"normalize","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalize","kind":"identifier"},{"text":"()","kind":"text"}],"title":"normalize()"},"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"type":"topic","role":"symbol","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","title":"Hashable"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/previousSibling":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/previousSibling","abstract":[],"role":"symbol","kind":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/previoussibling","navigatorTitle":[{"text":"previousSibling","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousSibling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"previousSibling"},"doc://com.apple.webkit/documentation/WebKit/DOMEntity":{"role":"symbol","type":"topic","title":"DOMEntity","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMEntity","abstract":[],"url":"/documentation/webkit/domentity","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMEntity"}],"navigatorTitle":[{"kind":"identifier","text":"DOMEntity"}],"kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSCharsetRule"}],"url":"/documentation/webkit/domcsscharsetrule","title":"DOMCSSCharsetRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSCharsetRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode/lineBoxRects()":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/lineBoxRects()","abstract":[{"text":"Returns the rectangles that bound each line of text in the node.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/webkit/domnode/lineboxrects()","navigatorTitle":[{"kind":"identifier","text":"lineBoxRects"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineBoxRects","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"title":"lineBoxRects()"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule":{"kind":"symbol","title":"DOMCSSMediaRule","type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","navigatorTitle":[{"kind":"identifier","text":"DOMCSSMediaRule"}],"deprecated":true,"url":"/documentation/webkit/domcssmediarule","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSMediaRule"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCDATASection"}],"url":"/documentation/webkit/domcdatasection","title":"DOMCDATASection","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCDATASection"}]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMCSSPageRule"}],"url":"/documentation/webkit/domcsspagerule","title":"DOMCSSPageRule","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMCSSPageRule"}]},"doc://com.externally.resolved.symbol/s:SQ":{"title":"Equatable","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"type":"topic"},"doc://com.apple.webkit/documentation/WebKit/DOMBlob":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMBlob","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMBlob","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMBlob","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMBlob","url":"/documentation/webkit/domblob","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported(_:version:)":{"title":"isSupported(_:version:)","abstract":[],"url":"/documentation/webkit/domnode/issupported(_:version:)","type":"topic","navigatorTitle":[{"text":"isSupported:version:","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported(_:version:)","role":"symbol","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSupported","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"version","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMDocumentType":{"title":"DOMDocumentType","navigatorTitle":[{"kind":"identifier","text":"DOMDocumentType"}],"abstract":[],"url":"/documentation/webkit/domdocumenttype","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMDocumentType","deprecated":true,"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMDocumentType"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRule","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRule","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRule","url":"/documentation/webkit/domcssrule","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMObject":{"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMObject","navigatorTitle":[{"text":"DOMObject","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"DOMObject","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMObject","kind":"identifier"}],"url":"/documentation/webkit/domobject","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCharacterData","kind":"identifier"}],"url":"/documentation/webkit/domcharacterdata","title":"DOMCharacterData","abstract":[],"deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOMCharacterData","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","type":"topic","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/localName":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/localName","abstract":[],"role":"symbol","kind":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/localname","navigatorTitle":[{"kind":"identifier","text":"localName"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"title":"localName"},"doc://com.apple.webkit/documentation/WebKit/DOMNode/isContentEditable":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/isContentEditable","abstract":[],"role":"symbol","kind":"symbol","deprecated":true,"url":"/documentation/webkit/domnode/iscontenteditable","navigatorTitle":[{"kind":"identifier","text":"isContentEditable"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isContentEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isContentEditable"},"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"DOMCSSRuleList","kind":"identifier"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMCSSRuleList","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOMCSSRuleList","url":"/documentation/webkit/domcssrulelist","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI":{"url":"/documentation/webkit/domnode/baseuri","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseURI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"baseURI","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI","deprecated":true,"abstract":[],"navigatorTitle":[{"text":"baseURI","kind":"identifier"}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView":{"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","abstract":[],"role":"symbol","title":"DOMAbstractView","url":"/documentation/webkit/domabstractview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMAbstractView"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOMAbstractView"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":false,"deprecatedAt":"10.14","name":"macOS","introducedAt":"10.4"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Class"},{"path":"/metadata/title","op":"replace","value":"DOMNode"},{"path":"/metadata/symbolKind","op":"replace","value":"class"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"DOMNode"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOMNode"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMNode/attributes","doc://com.apple.webkit/documentation/WebKit/DOMNode/baseURI","doc://com.apple.webkit/documentation/WebKit/DOMNode/childNodes","doc://com.apple.webkit/documentation/WebKit/DOMNode/firstChild","doc://com.apple.webkit/documentation/WebKit/DOMNode/isContentEditable","doc://com.apple.webkit/documentation/WebKit/DOMNode/lastChild","doc://com.apple.webkit/documentation/WebKit/DOMNode/localName","doc://com.apple.webkit/documentation/WebKit/DOMNode/namespaceURI","doc://com.apple.webkit/documentation/WebKit/DOMNode/nextSibling","doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeName","doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeType","doc://com.apple.webkit/documentation/WebKit/DOMNode/nodeValue","doc://com.apple.webkit/documentation/WebKit/DOMNode/ownerDocument","doc://com.apple.webkit/documentation/WebKit/DOMNode/parent","doc://com.apple.webkit/documentation/WebKit/DOMNode/parentElement","doc://com.apple.webkit/documentation/WebKit/DOMNode/prefix","doc://com.apple.webkit/documentation/WebKit/DOMNode/previousSibling","doc://com.apple.webkit/documentation/WebKit/DOMNode/textContent","doc://com.apple.webkit/documentation/WebKit/DOMNode/webArchive"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMNode/appendChild(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/boundingBox()","doc://com.apple.webkit/documentation/WebKit/DOMNode/cloneNode(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/compareDocumentPosition(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/contains(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/hasAttributes()","doc://com.apple.webkit/documentation/WebKit/DOMNode/hasChildNodes()","doc://com.apple.webkit/documentation/WebKit/DOMNode/insert(before:refChild:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/insertBefore::","doc://com.apple.webkit/documentation/WebKit/DOMNode/isDefaultNamespace(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isEqualNode(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isSameNode(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported(_:version:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/isSupported::","doc://com.apple.webkit/documentation/WebKit/DOMNode/lineBoxRects()","doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupNamespaceURI(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/lookupPrefix(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/normalize()","doc://com.apple.webkit/documentation/WebKit/DOMNode/removeChild(_:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild(_:oldChild:)","doc://com.apple.webkit/documentation/WebKit/DOMNode/replaceChild::"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"/relationshipsSections","op":"replace","value":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMDocument","doc://com.apple.webkit/documentation/WebKit/DOMDocumentFragment","doc://com.apple.webkit/documentation/WebKit/DOMDocumentType","doc://com.apple.webkit/documentation/WebKit/DOMElement","doc://com.apple.webkit/documentation/WebKit/DOMEntity","doc://com.apple.webkit/documentation/WebKit/DOMEntityReference"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"},{"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMEventTarget"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}]},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Document Object Model (DOM) APIs","generated":true,"identifiers":["doc://com.apple.webkit/documentation/WebKit/DOMAbstractView","doc://com.apple.webkit/documentation/WebKit/DOMAttr","doc://com.apple.webkit/documentation/WebKit/DOMBlob","doc://com.apple.webkit/documentation/WebKit/DOMCDATASection","doc://com.apple.webkit/documentation/WebKit/DOMCharacterData","doc://com.apple.webkit/documentation/WebKit/DOMComment","doc://com.apple.webkit/documentation/WebKit/DOMCounter","doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue","doc://com.apple.webkit/documentation/WebKit/DOMCSSRule","doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"],"anchor":"Document-Object-Model-DOM-APIs"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMNode"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)DOMObject","kind":"typeIdentifier","text":"DOMObject","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMObject"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"value":"DOMCSSImportRule","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title"},{"value":[{"kind":"identifier","text":"DOMCSSImportRule"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments"},{"value":[{"kind":"identifier","text":"DOMCSSImportRule"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle"},{"value":"textContent","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1textContent/title"},{"value":[{"text":"textContent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1textContent/fragments"},{"value":"DOMAttr","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title"},{"value":[{"text":"DOMAttr","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments"},{"value":[{"kind":"identifier","text":"DOMAttr"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle"},{"value":"lookupPrefix:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lookupPrefix(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"lookupPrefix:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lookupPrefix(_:)/fragments"},{"value":"cloneNode:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1cloneNode(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"cloneNode:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1cloneNode(_:)/fragments"},{"value":"boundingBox","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1boundingBox()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"boundingBox"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1boundingBox()/fragments"},{"value":"insertBefore:refChild:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1insert(before:refChild:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertBefore:refChild:"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1insert(before:refChild:)/fragments"},{"value":"DOMDocument","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocument/title"},{"value":[{"text":"DOMDocument","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocument/fragments"},{"value":[{"kind":"identifier","text":"DOMDocument"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocument/navigatorTitle"},{"value":"contains:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1contains(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contains:"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1contains(_:)/fragments"},{"value":"isSameNode:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isSameNode(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isSameNode:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isSameNode(_:)/fragments"},{"value":"attributes","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1attributes/title"},{"value":[{"text":"attributes","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1attributes/fragments"},{"value":"DOMCSSFontFaceRule","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title"},{"value":[{"kind":"identifier","text":"DOMCSSFontFaceRule"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments"},{"value":[{"text":"DOMCSSFontFaceRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle"},{"value":"nextSibling","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nextSibling/title"},{"value":[{"kind":"identifier","text":"nextSibling"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nextSibling/fragments"},{"value":"nodeType","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeType/title"},{"value":[{"text":"nodeType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeType/fragments"},{"value":"DOMCSSPrimitiveValue","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title"},{"value":[{"kind":"identifier","text":"DOMCSSPrimitiveValue"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments"},{"value":[{"text":"DOMCSSPrimitiveValue","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle"},{"value":"lookupNamespaceURI:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lookupNamespaceURI(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lookupNamespaceURI:"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lookupNamespaceURI(_:)/fragments"},{"value":"webArchive","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1webArchive/title"},{"value":[{"kind":"identifier","text":"webArchive"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1webArchive/fragments"},{"value":"appendChild:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1appendChild(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"appendChild:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1appendChild(_:)/fragments"},{"value":"DOMEntityReference","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEntityReference/title"},{"value":[{"kind":"identifier","text":"DOMEntityReference"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEntityReference/fragments"},{"value":[{"kind":"identifier","text":"DOMEntityReference"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEntityReference/navigatorTitle"},{"value":"DOMDocumentFragment","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocumentFragment/title"},{"value":[{"text":"DOMDocumentFragment","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocumentFragment/fragments"},{"value":[{"text":"DOMDocumentFragment","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocumentFragment/navigatorTitle"},{"value":"childNodes","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1childNodes/title"},{"value":[{"kind":"identifier","text":"childNodes"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1childNodes/fragments"},{"value":"prefix","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1prefix/title"},{"value":[{"kind":"identifier","text":"prefix"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1prefix/fragments"},{"value":"hasAttributes","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1hasAttributes()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasAttributes"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1hasAttributes()/fragments"},{"value":"hasChildNodes","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1hasChildNodes()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"hasChildNodes","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1hasChildNodes()/fragments"},{"value":"isEqualNode:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isEqualNode(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqualNode:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isEqualNode(_:)/fragments"},{"value":"compareDocumentPosition:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1compareDocumentPosition(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"compareDocumentPosition:"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1compareDocumentPosition(_:)/fragments"},{"value":"nodeName","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeName/title"},{"value":[{"text":"nodeName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeName/fragments"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"DOMElement","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMElement/title"},{"value":[{"kind":"identifier","text":"DOMElement"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMElement/fragments"},{"value":[{"text":"DOMElement","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMElement/navigatorTitle"},{"value":"replaceChild:oldChild:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1replaceChild(_:oldChild:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"replaceChild:oldChild:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1replaceChild(_:oldChild:)/fragments"},{"value":"isDefaultNamespace:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isDefaultNamespace(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isDefaultNamespace:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isDefaultNamespace(_:)/fragments"},{"value":"lastChild","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lastChild/title"},{"value":[{"kind":"identifier","text":"lastChild"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lastChild/fragments"},{"value":"nodeValue","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeValue/title"},{"value":[{"text":"nodeValue","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1nodeValue/fragments"},{"value":"parentNode","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1parent/title"},{"value":[{"text":"parentNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1parent/fragments"},{"value":"ownerDocument","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1ownerDocument/title"},{"value":[{"kind":"identifier","text":"ownerDocument"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1ownerDocument/fragments"},{"value":"namespaceURI","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1namespaceURI/title"},{"value":[{"text":"namespaceURI","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1namespaceURI/fragments"},{"value":"removeChild:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1removeChild(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeChild:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1removeChild(_:)/fragments"},{"value":"firstChild","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1firstChild/title"},{"value":[{"kind":"identifier","text":"firstChild"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1firstChild/fragments"},{"value":"parentElement","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1parentElement/title"},{"value":[{"text":"parentElement","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1parentElement/fragments"},{"value":"DOMEventTarget","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/title"},{"value":[{"kind":"identifier","text":"DOMEventTarget"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/fragments"},{"value":[{"text":"DOMEventTarget","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventTarget/navigatorTitle"},{"value":"DOMCounter","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title"},{"value":[{"text":"DOMCounter","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments"},{"value":[{"text":"DOMCounter","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle"},{"value":"DOMComment","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title"},{"value":[{"text":"DOMComment","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments"},{"value":[{"kind":"identifier","text":"DOMComment"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle"},{"value":"normalize","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1normalize()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"normalize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1normalize()/fragments"},{"value":"previousSibling","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1previousSibling/title"},{"value":[{"kind":"identifier","text":"previousSibling"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1previousSibling/fragments"},{"value":"DOMEntity","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEntity/title"},{"value":[{"kind":"identifier","text":"DOMEntity"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEntity/fragments"},{"value":[{"text":"DOMEntity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEntity/navigatorTitle"},{"value":"DOMCSSCharsetRule","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title"},{"value":[{"text":"DOMCSSCharsetRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments"},{"value":[{"text":"DOMCSSCharsetRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle"},{"value":"lineBoxRects","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lineBoxRects()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lineBoxRects"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1lineBoxRects()/fragments"},{"value":"DOMCSSMediaRule","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title"},{"value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments"},{"value":[{"text":"DOMCSSMediaRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle"},{"value":"DOMCDATASection","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title"},{"value":[{"kind":"identifier","text":"DOMCDATASection"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments"},{"value":[{"text":"DOMCDATASection","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle"},{"value":"DOMCSSPageRule","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title"},{"value":[{"kind":"identifier","text":"DOMCSSPageRule"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments"},{"value":[{"text":"DOMCSSPageRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle"},{"value":"DOMBlob","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title"},{"value":[{"kind":"identifier","text":"DOMBlob"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments"},{"value":[{"kind":"identifier","text":"DOMBlob"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle"},{"value":"isSupported:version:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isSupported(_:version:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isSupported:version:"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isSupported(_:version:)/fragments"},{"value":"DOMDocumentType","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocumentType/title"},{"value":[{"text":"DOMDocumentType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocumentType/fragments"},{"value":[{"kind":"identifier","text":"DOMDocumentType"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMDocumentType/navigatorTitle"},{"value":"DOMNode","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title"},{"value":[{"text":"DOMNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments"},{"value":[{"text":"DOMNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle"},{"value":"DOMCSSRule","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title"},{"value":[{"text":"DOMCSSRule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments"},{"value":[{"kind":"identifier","text":"DOMCSSRule"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle"},{"value":"DOMObject","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/title"},{"value":[{"kind":"identifier","text":"DOMObject"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/fragments"},{"value":[{"kind":"identifier","text":"DOMObject"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/navigatorTitle"},{"value":"DOMCharacterData","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title"},{"value":[{"kind":"identifier","text":"DOMCharacterData"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments"},{"value":[{"text":"DOMCharacterData","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle"},{"value":"localName","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1localName/title"},{"value":[{"text":"localName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1localName/fragments"},{"value":"isContentEditable","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isContentEditable/title"},{"value":[{"kind":"identifier","text":"isContentEditable"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1isContentEditable/fragments"},{"value":"DOMCSSRuleList","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title"},{"value":[{"kind":"identifier","text":"DOMCSSRuleList"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments"},{"value":[{"kind":"identifier","text":"DOMCSSRuleList"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle"},{"value":"baseURI","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1baseURI/title"},{"value":[{"text":"baseURI","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode~1baseURI/fragments"},{"value":"DOMAbstractView","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title"},{"value":[{"text":"DOMAbstractView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments"},{"value":[{"kind":"identifier","text":"DOMAbstractView"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}