{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOMObject"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DOMObject",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOMObject"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOMObject"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DOMObject"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "role": "symbol",
      "title": "DOMAbstractView",
      "type": "topic",
      "url": "/documentation/webkit/domabstractview"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAttr": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "role": "symbol",
      "title": "DOMAttr",
      "type": "topic",
      "url": "/documentation/webkit/domattr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMBlob": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "role": "symbol",
      "title": "DOMBlob",
      "type": "topic",
      "url": "/documentation/webkit/domblob"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "role": "symbol",
      "title": "DOMCDATASection",
      "type": "topic",
      "url": "/documentation/webkit/domcdatasection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSCharsetRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsscharsetrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSFontFaceRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssfontfacerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSImportRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssimportrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSMediaRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssmediarule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPageRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsspagerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPrimitiveValue",
      "type": "topic",
      "url": "/documentation/webkit/domcssprimitivevalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRuleList",
      "type": "topic",
      "url": "/documentation/webkit/domcssrulelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSStyleDeclaration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSStyleDeclaration"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSStyleDeclaration",
      "type": "topic",
      "url": "/documentation/webkit/domcssstyledeclaration"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSValue"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSValue"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSValue",
      "type": "topic",
      "url": "/documentation/webkit/domcssvalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "role": "symbol",
      "title": "DOMCharacterData",
      "type": "topic",
      "url": "/documentation/webkit/domcharacterdata"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMComment": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "role": "symbol",
      "title": "DOMComment",
      "type": "topic",
      "url": "/documentation/webkit/domcomment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCounter": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "role": "symbol",
      "title": "DOMCounter",
      "type": "topic",
      "url": "/documentation/webkit/domcounter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMEvent",
      "type": "topic",
      "url": "/documentation/webkit/domevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMFileList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMFileList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMFileList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMFileList"
        }
      ],
      "role": "symbol",
      "title": "DOMFileList",
      "type": "topic",
      "url": "/documentation/webkit/domfilelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMHTMLCollection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMHTMLCollection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMHTMLCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMHTMLCollection"
        }
      ],
      "role": "symbol",
      "title": "DOMHTMLCollection",
      "type": "topic",
      "url": "/documentation/webkit/domhtmlcollection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMHTMLOptionsCollection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMHTMLOptionsCollection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMHTMLOptionsCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMHTMLOptionsCollection"
        }
      ],
      "role": "symbol",
      "title": "DOMHTMLOptionsCollection",
      "type": "topic",
      "url": "/documentation/webkit/domhtmloptionscollection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMImplementation": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMImplementation"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMImplementation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMImplementation"
        }
      ],
      "role": "symbol",
      "title": "DOMImplementation",
      "type": "topic",
      "url": "/documentation/webkit/domimplementation"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMediaList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMMediaList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMediaList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMMediaList"
        }
      ],
      "role": "symbol",
      "title": "DOMMediaList",
      "type": "topic",
      "url": "/documentation/webkit/dommedialist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMNamedNodeMap": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMNamedNodeMap"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMNamedNodeMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMNamedNodeMap"
        }
      ],
      "role": "symbol",
      "title": "DOMNamedNodeMap",
      "type": "topic",
      "url": "/documentation/webkit/domnamednodemap"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMNode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMNode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMNode"
        }
      ],
      "role": "symbol",
      "title": "DOMNode",
      "type": "topic",
      "url": "/documentation/webkit/domnode"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMNodeIterator": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMNodeIterator"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMNodeIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMNodeIterator"
        }
      ],
      "role": "symbol",
      "title": "DOMNodeIterator",
      "type": "topic",
      "url": "/documentation/webkit/domnodeiterator"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMNodeList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMNodeList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMNodeList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMNodeList"
        }
      ],
      "role": "symbol",
      "title": "DOMNodeList",
      "type": "topic",
      "url": "/documentation/webkit/domnodelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMObject": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMObject"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMObject"
        }
      ],
      "role": "symbol",
      "title": "DOMObject",
      "type": "topic",
      "url": "/documentation/webkit/domobject"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMObject/sheet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMStyleSheet",
          "text": "DOMStyleSheet"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMObject/sheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sheet"
        }
      ],
      "role": "symbol",
      "title": "sheet",
      "type": "topic",
      "url": "/documentation/webkit/domobject/sheet"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMRGBColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMRGBColor"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMRGBColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMRGBColor"
        }
      ],
      "role": "symbol",
      "title": "DOMRGBColor",
      "type": "topic",
      "url": "/documentation/webkit/domrgbcolor"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMRange": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMRange"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMRange"
        }
      ],
      "role": "symbol",
      "title": "DOMRange",
      "type": "topic",
      "url": "/documentation/webkit/domrange"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMRect": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMRect"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMRect"
        }
      ],
      "role": "symbol",
      "title": "DOMRect",
      "type": "topic",
      "url": "/documentation/webkit/domrect"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheet": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMStyleSheet"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMStyleSheet"
        }
      ],
      "role": "symbol",
      "title": "DOMStyleSheet",
      "type": "topic",
      "url": "/documentation/webkit/domstylesheet"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheetList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMStyleSheetList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheetList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMStyleSheetList"
        }
      ],
      "role": "symbol",
      "title": "DOMStyleSheetList",
      "type": "topic",
      "url": "/documentation/webkit/domstylesheetlist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMTreeWalker": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMTreeWalker"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMTreeWalker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMTreeWalker"
        }
      ],
      "role": "symbol",
      "title": "DOMTreeWalker",
      "type": "topic",
      "url": "/documentation/webkit/domtreewalker"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathExpression": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMXPathExpression"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMXPathExpression"
        }
      ],
      "role": "symbol",
      "title": "DOMXPathExpression",
      "type": "topic",
      "url": "/documentation/webkit/domxpathexpression"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMXPathResult"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMXPathResult"
        }
      ],
      "role": "symbol",
      "title": "DOMXPathResult",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebScriptObject": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebScriptObject",
          "type": "codeVoice"
        },
        {
          "text": " object is an Objective-C wrapper for a scripting object passed to your application from the scripting environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebScriptObject"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebScriptObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebScriptObject"
        }
      ],
      "role": "symbol",
      "title": "WebScriptObject",
      "type": "topic",
      "url": "/documentation/webkit/webscriptobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebScriptObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
        "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent",
        "doc://com.apple.webkit/documentation/WebKit/DOMFileList",
        "doc://com.apple.webkit/documentation/WebKit/DOMHTMLCollection",
        "doc://com.apple.webkit/documentation/WebKit/DOMHTMLOptionsCollection",
        "doc://com.apple.webkit/documentation/WebKit/DOMImplementation",
        "doc://com.apple.webkit/documentation/WebKit/DOMMediaList",
        "doc://com.apple.webkit/documentation/WebKit/DOMNamedNodeMap",
        "doc://com.apple.webkit/documentation/WebKit/DOMNode",
        "doc://com.apple.webkit/documentation/WebKit/DOMNodeIterator",
        "doc://com.apple.webkit/documentation/WebKit/DOMNodeList",
        "doc://com.apple.webkit/documentation/WebKit/DOMRGBColor",
        "doc://com.apple.webkit/documentation/WebKit/DOMRange",
        "doc://com.apple.webkit/documentation/WebKit/DOMRect",
        "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheet",
        "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheetList",
        "doc://com.apple.webkit/documentation/WebKit/DOMTreeWalker",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathExpression",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Object-Model-DOM-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
        "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
        "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
        "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
        "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
        "doc://com.apple.webkit/documentation/WebKit/DOMComment",
        "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
      ],
      "title": "Document Object Model (DOM) APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMObject/sheet"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOMObject"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMObject/sheet"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebScriptObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
                "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSStyleDeclaration",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent",
                "doc://com.apple.webkit/documentation/WebKit/DOMFileList",
                "doc://com.apple.webkit/documentation/WebKit/DOMHTMLCollection",
                "doc://com.apple.webkit/documentation/WebKit/DOMHTMLOptionsCollection",
                "doc://com.apple.webkit/documentation/WebKit/DOMImplementation",
                "doc://com.apple.webkit/documentation/WebKit/DOMMediaList",
                "doc://com.apple.webkit/documentation/WebKit/DOMNamedNodeMap",
                "doc://com.apple.webkit/documentation/WebKit/DOMNode",
                "doc://com.apple.webkit/documentation/WebKit/DOMNodeIterator",
                "doc://com.apple.webkit/documentation/WebKit/DOMNodeList",
                "doc://com.apple.webkit/documentation/WebKit/DOMRGBColor",
                "doc://com.apple.webkit/documentation/WebKit/DOMRange",
                "doc://com.apple.webkit/documentation/WebKit/DOMRect",
                "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheet",
                "doc://com.apple.webkit/documentation/WebKit/DOMStyleSheetList",
                "doc://com.apple.webkit/documentation/WebKit/DOMTreeWalker",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathExpression",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Object-Model-DOM-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
                "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
                "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
                "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
                "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
                "doc://com.apple.webkit/documentation/WebKit/DOMComment",
                "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
              ],
              "title": "Document Object Model (DOM) APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DOMObject"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WebScriptObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WebScriptObject",
                    "text": "WebScriptObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title",
          "value": "DOMAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title",
          "value": "DOMCharacterData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title",
          "value": "DOMCSSImportRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebScriptObject/title",
          "value": "WebScriptObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebScriptObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebScriptObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebScriptObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebScriptObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMediaList/title",
          "value": "DOMMediaList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMediaList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMediaList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMediaList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMediaList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title",
          "value": "DOMBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title",
          "value": "DOMCSSFontFaceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title",
          "value": "DOMCDATASection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title",
          "value": "DOMCSSCharsetRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMImplementation/title",
          "value": "DOMImplementation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMImplementation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMImplementation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMImplementation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMImplementation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title",
          "value": "DOMCSSPrimitiveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathExpression/title",
          "value": "DOMXPathExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathExpression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathExpression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title",
          "value": "DOMNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMFileList/title",
          "value": "DOMFileList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMFileList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMFileList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMFileList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMFileList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNodeList/title",
          "value": "DOMNodeList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNodeList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNodeList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNodeList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNodeList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLCollection/title",
          "value": "DOMHTMLCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMHTMLCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMHTMLCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRGBColor/title",
          "value": "DOMRGBColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRGBColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRGBColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRGBColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRGBColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title",
          "value": "DOMComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMTreeWalker/title",
          "value": "DOMTreeWalker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMTreeWalker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMTreeWalker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMTreeWalker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMTreeWalker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLOptionsCollection/title",
          "value": "DOMHTMLOptionsCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLOptionsCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMHTMLOptionsCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLOptionsCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMHTMLOptionsCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title",
          "value": "DOMCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMStyleSheetList/title",
          "value": "DOMStyleSheetList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMStyleSheetList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMStyleSheetList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMStyleSheetList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMStyleSheetList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/title",
          "value": "DOMRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title",
          "value": "DOMCSSMediaRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title",
          "value": "DOMCSSPageRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title",
          "value": "DOMAbstractView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject~1sheet/title",
          "value": "sheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject~1sheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/title",
          "value": "DOMObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRect/title",
          "value": "DOMRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSValue/title",
          "value": "DOMCSSValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult/title",
          "value": "DOMXPathResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title",
          "value": "DOMCSSRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNamedNodeMap/title",
          "value": "DOMNamedNodeMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNamedNodeMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNamedNodeMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNamedNodeMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNamedNodeMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title",
          "value": "DOMCSSRuleList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/title",
          "value": "DOMEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSStyleDeclaration/title",
          "value": "DOMCSSStyleDeclaration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSStyleDeclaration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSStyleDeclaration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSStyleDeclaration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSStyleDeclaration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNodeIterator/title",
          "value": "DOMNodeIterator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNodeIterator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNodeIterator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNodeIterator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMNodeIterator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMStyleSheet/title",
          "value": "DOMStyleSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMStyleSheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMStyleSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMStyleSheet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMStyleSheet"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/domobject"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/domobject"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
