{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOMRangeException"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@DOMRangeException",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOMRangeException"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOMRangeException"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DOMRangeException"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOMRangeException"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEventException": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMEventException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEventException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMEventException"
        }
      ],
      "role": "symbol",
      "title": "DOMEventException",
      "type": "topic",
      "url": "/documentation/webkit/domeventexception"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMException": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMException"
        }
      ],
      "role": "symbol",
      "title": "DOMException",
      "type": "topic",
      "url": "/documentation/webkit/domexception"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMRangeException": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMRangeException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMRangeException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMRangeException"
        }
      ],
      "role": "symbol",
      "title": "DOMRangeException",
      "type": "topic",
      "url": "/documentation/webkit/domrangeexception"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathException": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMXPathException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMXPathException"
        }
      ],
      "role": "symbol",
      "title": "DOMXPathException",
      "type": "topic",
      "url": "/documentation/webkit/domxpathexception"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_BAD_BOUNDARYPOINTS_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_BAD_BOUNDARYPOINTS_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMRangeExceptionCode",
          "text": "DOMRangeExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_BAD_BOUNDARYPOINTS_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_BAD_BOUNDARYPOINTS_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_BAD_BOUNDARYPOINTS_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_bad_boundarypoints_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_DOMSTRING_SIZE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_DOMSTRING_SIZE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_DOMSTRING_SIZE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_domstring_size_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_HIERARCHY_REQUEST_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_HIERARCHY_REQUEST_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_HIERARCHY_REQUEST_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_hierarchy_request_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INDEX_SIZE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INDEX_SIZE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INDEX_SIZE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_index_size_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INUSE_ATTRIBUTE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INUSE_ATTRIBUTE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INUSE_ATTRIBUTE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_inuse_attribute_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_ACCESS_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_ACCESS_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_ACCESS_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_access_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_CHARACTER_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_CHARACTER_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_CHARACTER_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_character_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_EXPRESSION_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_EXPRESSION_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMXPathExceptionCode",
          "text": "DOMXPathExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_EXPRESSION_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_EXPRESSION_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_EXPRESSION_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_expression_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_MODIFICATION_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_MODIFICATION_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_MODIFICATION_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_modification_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_NODE_TYPE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_NODE_TYPE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMRangeExceptionCode",
          "text": "DOMRangeExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_NODE_TYPE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_NODE_TYPE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_NODE_TYPE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_node_type_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_INVALID_STATE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_INVALID_STATE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_INVALID_STATE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_invalid_state_err"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOM_NAMESPACE_ERR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DOMExceptionCode",
          "text": "DOMExceptionCode"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOM_NAMESPACE_ERR"
        }
      ],
      "role": "symbol",
      "title": "DOM_NAMESPACE_ERR",
      "type": "topic",
      "url": "/documentation/webkit/dom_namespace_err"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "DOM-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMEventException",
        "doc://com.apple.webkit/documentation/WebKit/DOMException",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathException",
        "doc://com.apple.webkit/documentation/WebKit/DOM_BAD_BOUNDARYPOINTS_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_EXPRESSION_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_NODE_TYPE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR",
        "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR"
      ],
      "title": "DOM Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOMRangeException"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRangeException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "DOM-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMEventException",
                "doc://com.apple.webkit/documentation/WebKit/DOMException",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathException",
                "doc://com.apple.webkit/documentation/WebKit/DOM_BAD_BOUNDARYPOINTS_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_DOMSTRING_SIZE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_HIERARCHY_REQUEST_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INDEX_SIZE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INUSE_ATTRIBUTE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_ACCESS_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_CHARACTER_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_EXPRESSION_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_MODIFICATION_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_NODE_TYPE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_INVALID_STATE_ERR",
                "doc://com.apple.webkit/documentation/WebKit/DOM_NAMESPACE_ERR"
              ],
              "title": "DOM Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DOMRangeException"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventException/title",
          "value": "DOMEventException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEventException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEventException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_MODIFICATION_ERR/title",
          "value": "DOM_INVALID_MODIFICATION_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_MODIFICATION_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_MODIFICATION_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_EXPRESSION_ERR/title",
          "value": "DOM_INVALID_EXPRESSION_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_EXPRESSION_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_EXPRESSION_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INUSE_ATTRIBUTE_ERR/title",
          "value": "DOM_INUSE_ATTRIBUTE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INUSE_ATTRIBUTE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INUSE_ATTRIBUTE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_BAD_BOUNDARYPOINTS_ERR/title",
          "value": "DOM_BAD_BOUNDARYPOINTS_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_BAD_BOUNDARYPOINTS_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_BAD_BOUNDARYPOINTS_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NAMESPACE_ERR/title",
          "value": "DOM_NAMESPACE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_NAMESPACE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_NAMESPACE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRangeException/title",
          "value": "DOMRangeException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRangeException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMRangeException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathException/title",
          "value": "DOMXPathException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INDEX_SIZE_ERR/title",
          "value": "DOM_INDEX_SIZE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INDEX_SIZE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INDEX_SIZE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_ACCESS_ERR/title",
          "value": "DOM_INVALID_ACCESS_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_ACCESS_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_ACCESS_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOMSTRING_SIZE_ERR/title",
          "value": "DOM_DOMSTRING_SIZE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_DOMSTRING_SIZE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_DOMSTRING_SIZE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMException/title",
          "value": "DOMException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_NODE_TYPE_ERR/title",
          "value": "DOM_INVALID_NODE_TYPE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_NODE_TYPE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_NODE_TYPE_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_CHARACTER_ERR/title",
          "value": "DOM_INVALID_CHARACTER_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_CHARACTER_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_CHARACTER_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_HIERARCHY_REQUEST_ERR/title",
          "value": "DOM_HIERARCHY_REQUEST_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_HIERARCHY_REQUEST_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_HIERARCHY_REQUEST_ERR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_STATE_ERR/title",
          "value": "DOM_INVALID_STATE_ERR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOM_INVALID_STATE_ERR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOM_INVALID_STATE_ERR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/domrangeexception"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/domrangeexception"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
