{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DOMUIEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOMUIEvent"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOMUIEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DOMUIEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "role": "symbol",
      "title": "DOMAbstractView",
      "type": "topic",
      "url": "/documentation/webkit/domabstractview"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAttr": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "role": "symbol",
      "title": "DOMAttr",
      "type": "topic",
      "url": "/documentation/webkit/domattr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMBlob": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "role": "symbol",
      "title": "DOMBlob",
      "type": "topic",
      "url": "/documentation/webkit/domblob"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "role": "symbol",
      "title": "DOMCDATASection",
      "type": "topic",
      "url": "/documentation/webkit/domcdatasection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSCharsetRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsscharsetrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSFontFaceRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssfontfacerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSImportRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssimportrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSMediaRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssmediarule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPageRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsspagerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPrimitiveValue",
      "type": "topic",
      "url": "/documentation/webkit/domcssprimitivevalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRuleList",
      "type": "topic",
      "url": "/documentation/webkit/domcssrulelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "role": "symbol",
      "title": "DOMCharacterData",
      "type": "topic",
      "url": "/documentation/webkit/domcharacterdata"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMComment": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "role": "symbol",
      "title": "DOMComment",
      "type": "topic",
      "url": "/documentation/webkit/domcomment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCounter": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "role": "symbol",
      "title": "DOMCounter",
      "type": "topic",
      "url": "/documentation/webkit/domcounter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMEvent",
      "type": "topic",
      "url": "/documentation/webkit/domevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMKeyboardEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMKeyboardEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMKeyboardEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMKeyboardEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMKeyboardEvent",
      "type": "topic",
      "url": "/documentation/webkit/domkeyboardevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMMouseEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMMouseEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMMouseEvent",
      "type": "topic",
      "url": "/documentation/webkit/dommouseevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMUIEvent"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMUIEvent"
        }
      ],
      "role": "symbol",
      "title": "DOMUIEvent",
      "type": "topic",
      "url": "/documentation/webkit/domuievent"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/charCode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/charCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "charCode"
        }
      ],
      "role": "symbol",
      "title": "charCode",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/charcode"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/detail": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/detail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detail"
        }
      ],
      "role": "symbol",
      "title": "detail",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/detail"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent(_:canBubble:cancelable:view:detail:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initUIEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "canBubble"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cancelable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMAbstractView",
          "text": "DOMAbstractView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "detail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent(_:canBubble:cancelable:view:detail:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initUIEvent:canBubble:cancelable:view:detail:"
        }
      ],
      "role": "symbol",
      "title": "initUIEvent(_:canBubble:cancelable:view:detail:)",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/inituievent(_:canbubble:cancelable:view:detail:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent:::::": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initUIEvent:::::"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent:::::",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initUIEvent:::::"
        }
      ],
      "role": "symbol",
      "title": "initUIEvent:::::",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/inituievent:::::"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/keyCode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/keyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyCode"
        }
      ],
      "role": "symbol",
      "title": "keyCode",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/keycode"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/layerX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "layerX"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/layerX",
      "kind": "symbol",
      "role": "symbol",
      "title": "layerX",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/layerx"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/layerY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "layerY"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/layerY",
      "kind": "symbol",
      "role": "symbol",
      "title": "layerY",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/layery"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageX": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageX"
        }
      ],
      "role": "symbol",
      "title": "pageX",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/pagex"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageY": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageY"
        }
      ],
      "role": "symbol",
      "title": "pageY",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/pagey"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/view": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMAbstractView",
          "text": "DOMAbstractView"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/view",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "view"
        }
      ],
      "role": "symbol",
      "title": "view",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/view"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/which": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "which"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/which",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "which"
        }
      ],
      "role": "symbol",
      "title": "which",
      "type": "topic",
      "url": "/documentation/webkit/domuievent/which"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMEvent"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMKeyboardEvent",
        "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Object-Model-DOM-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
        "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
        "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
        "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
        "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
        "doc://com.apple.webkit/documentation/WebKit/DOMComment",
        "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
      ],
      "title": "Document Object Model (DOM) APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/charCode",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/detail",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/keyCode",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageX",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageY",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/view",
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/which"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent(_:canBubble:cancelable:view:detail:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOMUIEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/charCode",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/detail",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/keyCode",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/layerX",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/layerY",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageX",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/pageY",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/view",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/which"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent(_:canBubble:cancelable:view:detail:)",
                "doc://com.apple.webkit/documentation/WebKit/DOMUIEvent/initUIEvent:::::"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMEvent"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMKeyboardEvent",
                "doc://com.apple.webkit/documentation/WebKit/DOMMouseEvent"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Object-Model-DOM-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
                "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
                "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
                "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
                "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
                "doc://com.apple.webkit/documentation/WebKit/DOMComment",
                "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
              ],
              "title": "Document Object Model (DOM) APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DOMUIEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)DOMEvent",
                    "text": "DOMEvent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1charCode/title",
          "value": "charCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1charCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "charCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title",
          "value": "DOMCSSCharsetRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1pageX/title",
          "value": "pageX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1pageX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title",
          "value": "DOMCharacterData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1which/title",
          "value": "which"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1which/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "which"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title",
          "value": "DOMCSSMediaRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title",
          "value": "DOMCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title",
          "value": "DOMComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMKeyboardEvent/title",
          "value": "DOMKeyboardEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMKeyboardEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMKeyboardEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMKeyboardEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMKeyboardEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title",
          "value": "DOMAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title",
          "value": "DOMCSSPrimitiveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title",
          "value": "DOMCDATASection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1pageY/title",
          "value": "pageY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1pageY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title",
          "value": "DOMCSSFontFaceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title",
          "value": "DOMCSSImportRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title",
          "value": "DOMCSSRuleList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1keyCode/title",
          "value": "keyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1keyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1view/title",
          "value": "view"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1view/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title",
          "value": "DOMCSSPageRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1initUIEvent(_:canBubble:cancelable:view:detail:)/title",
          "value": "initUIEvent:canBubble:cancelable:view:detail:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1initUIEvent(_:canBubble:cancelable:view:detail:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initUIEvent:canBubble:cancelable:view:detail:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title",
          "value": "DOMAbstractView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/title",
          "value": "DOMEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title",
          "value": "DOMCSSRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent/title",
          "value": "DOMMouseEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMMouseEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/title",
          "value": "DOMUIEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMUIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1detail/title",
          "value": "detail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMUIEvent~1detail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title",
          "value": "DOMBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/domuievent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/domuievent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
