{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DOMXPathResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DOMXPathResult"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DOMXPathResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DOMXPathResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAbstractView"
        }
      ],
      "role": "symbol",
      "title": "DOMAbstractView",
      "type": "topic",
      "url": "/documentation/webkit/domabstractview"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMAttr": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMAttr"
        }
      ],
      "role": "symbol",
      "title": "DOMAttr",
      "type": "topic",
      "url": "/documentation/webkit/domattr"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMBlob": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMBlob"
        }
      ],
      "role": "symbol",
      "title": "DOMBlob",
      "type": "topic",
      "url": "/documentation/webkit/domblob"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCDATASection"
        }
      ],
      "role": "symbol",
      "title": "DOMCDATASection",
      "type": "topic",
      "url": "/documentation/webkit/domcdatasection"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSCharsetRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSCharsetRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsscharsetrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSFontFaceRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSFontFaceRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssfontfacerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSImportRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSImportRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssimportrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSMediaRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSMediaRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssmediarule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPageRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPageRule",
      "type": "topic",
      "url": "/documentation/webkit/domcsspagerule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSPrimitiveValue"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSPrimitiveValue",
      "type": "topic",
      "url": "/documentation/webkit/domcssprimitivevalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRule"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRule",
      "type": "topic",
      "url": "/documentation/webkit/domcssrule"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCSSRuleList"
        }
      ],
      "role": "symbol",
      "title": "DOMCSSRuleList",
      "type": "topic",
      "url": "/documentation/webkit/domcssrulelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCharacterData"
        }
      ],
      "role": "symbol",
      "title": "DOMCharacterData",
      "type": "topic",
      "url": "/documentation/webkit/domcharacterdata"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMComment": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMComment"
        }
      ],
      "role": "symbol",
      "title": "DOMComment",
      "type": "topic",
      "url": "/documentation/webkit/domcomment"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMCounter": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMCounter"
        }
      ],
      "role": "symbol",
      "title": "DOMCounter",
      "type": "topic",
      "url": "/documentation/webkit/domcounter"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMObject": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMObject"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMObject"
        }
      ],
      "role": "symbol",
      "title": "DOMObject",
      "type": "topic",
      "url": "/documentation/webkit/domobject"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOMXPathResult"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOMXPathResult"
        }
      ],
      "role": "symbol",
      "title": "DOMXPathResult",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/booleanValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "booleanValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/booleanValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "booleanValue"
        }
      ],
      "role": "symbol",
      "title": "booleanValue",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/booleanvalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/invalidIteratorState": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidIteratorState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/invalidIteratorState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidIteratorState"
        }
      ],
      "role": "symbol",
      "title": "invalidIteratorState",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/invaliditeratorstate"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/iterateNext()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iterateNext"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMNode",
          "text": "DOMNode"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/iterateNext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iterateNext"
        }
      ],
      "role": "symbol",
      "title": "iterateNext()",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/iteratenext()"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/numberValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/numberValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberValue"
        }
      ],
      "role": "symbol",
      "title": "numberValue",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/numbervalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/resultType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/resultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultType"
        }
      ],
      "role": "symbol",
      "title": "resultType",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/resulttype"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/singleNodeValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "singleNodeValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMNode",
          "text": "DOMNode"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/singleNodeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "singleNodeValue"
        }
      ],
      "role": "symbol",
      "title": "singleNodeValue",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/singlenodevalue"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotItem(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snapshotItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DOMNode",
          "text": "DOMNode"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "snapshotItem:"
        }
      ],
      "role": "symbol",
      "title": "snapshotItem(_:)",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/snapshotitem(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotLength": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snapshotLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "snapshotLength"
        }
      ],
      "role": "symbol",
      "title": "snapshotLength",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/snapshotlength"
    },
    "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/stringValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/stringValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringValue"
        }
      ],
      "role": "symbol",
      "title": "stringValue",
      "type": "topic",
      "url": "/documentation/webkit/domxpathresult/stringvalue"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Object-Model-DOM-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
        "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
        "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
        "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
        "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
        "doc://com.apple.webkit/documentation/WebKit/DOMComment",
        "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
        "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
      ],
      "title": "Document Object Model (DOM) APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/booleanValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/invalidIteratorState",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/numberValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/resultType",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/singleNodeValue",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotLength",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/stringValue"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/iterateNext()",
        "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotItem(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DOMXPathResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/booleanValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/invalidIteratorState",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/numberValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/resultType",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/singleNodeValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotLength",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/stringValue"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/iterateNext()",
                "doc://com.apple.webkit/documentation/WebKit/DOMXPathResult/snapshotItem(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Object-Model-DOM-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/DOMAbstractView",
                "doc://com.apple.webkit/documentation/WebKit/DOMAttr",
                "doc://com.apple.webkit/documentation/WebKit/DOMBlob",
                "doc://com.apple.webkit/documentation/WebKit/DOMCDATASection",
                "doc://com.apple.webkit/documentation/WebKit/DOMCharacterData",
                "doc://com.apple.webkit/documentation/WebKit/DOMComment",
                "doc://com.apple.webkit/documentation/WebKit/DOMCounter",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSCharsetRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSFontFaceRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSImportRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSMediaRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPageRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSPrimitiveValue",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRule",
                "doc://com.apple.webkit/documentation/WebKit/DOMCSSRuleList"
              ],
              "title": "Document Object Model (DOM) APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DOMXPathResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/DOMObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)DOMObject",
                    "text": "DOMObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1snapshotItem(_:)/title",
          "value": "snapshotItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1snapshotItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "snapshotItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/title",
          "value": "DOMAbstractView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAbstractView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAbstractView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/title",
          "value": "DOMObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/title",
          "value": "DOMCSSFontFaceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSFontFaceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSFontFaceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/title",
          "value": "DOMCharacterData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCharacterData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCharacterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1snapshotLength/title",
          "value": "snapshotLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1snapshotLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "snapshotLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/title",
          "value": "DOMCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/title",
          "value": "DOMCSSRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/title",
          "value": "DOMAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1resultType/title",
          "value": "resultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1resultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/title",
          "value": "DOMCDATASection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCDATASection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCDATASection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/title",
          "value": "DOMCSSRuleList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSRuleList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/title",
          "value": "DOMComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMComment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1invalidIteratorState/title",
          "value": "invalidIteratorState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1invalidIteratorState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "invalidIteratorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/title",
          "value": "DOMCSSPageRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPageRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPageRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/title",
          "value": "DOMCSSCharsetRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSCharsetRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSCharsetRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/title",
          "value": "DOMBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMBlob/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/title",
          "value": "DOMCSSMediaRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSMediaRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSMediaRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1singleNodeValue/title",
          "value": "singleNodeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1singleNodeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "singleNodeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult/title",
          "value": "DOMXPathResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMXPathResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1stringValue/title",
          "value": "stringValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1stringValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stringValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/title",
          "value": "DOMCSSImportRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSImportRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSImportRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1booleanValue/title",
          "value": "booleanValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1booleanValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "booleanValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/title",
          "value": "DOMCSSPrimitiveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMCSSPrimitiveValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOMCSSPrimitiveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1iterateNext()/title",
          "value": "iterateNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1iterateNext()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "iterateNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1numberValue/title",
          "value": "numberValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMXPathResult~1numberValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/domxpathresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/domxpathresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
