{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Downloading Information (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/foundation/url_loading_system": {
      "abstract": [
        {
          "text": "Interact with URLs and communicate with servers using standard Internet protocols. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system",
      "kind": "article",
      "role": "article",
      "title": "URL Loading System",
      "type": "topic",
      "url": "/documentation/foundation/url_loading_system"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDownload": {
      "abstract": [
        {
          "code": "WebDownload",
          "type": "codeVoice"
        },
        {
          "text": " objects initiate download client requests on behalf of a delegate. A download request involves loading the data, decoding it (if necessary), and saving it to a file. Instances of this class behave similar to ",
          "type": "text"
        },
        {
          "code": "NSURLDownload",
          "type": "codeVoice"
        },
        {
          "text": " except delegates of ",
          "type": "text"
        },
        {
          "code": "WebDownload",
          "type": "codeVoice"
        },
        {
          "text": " may implement an additional delegate method. The method allows the delegate to specify the window to be used for authentication sheets. If the delegate does not implement this method, the ",
          "type": "text"
        },
        {
          "code": "WebDownload",
          "type": "codeVoice"
        },
        {
          "text": " object will prompt the user for authentication using the standard WebKit authentication panel, as either a sheet or window. There are no additional methods defined in this class. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDownloadDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the delegate method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDownload"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDownload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDownload"
        }
      ],
      "role": "symbol",
      "title": "WebDownload",
      "type": "topic",
      "url": "/documentation/webkit/webdownload"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDownloadDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "WebDownloadDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol declares one additional method for delegates of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDownload",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDownloadDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDownloadDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDownloadDelegate"
        }
      ],
      "role": "symbol",
      "title": "WebDownloadDelegate",
      "type": "topic",
      "url": "/documentation/webkit/webdownloaddelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessing Previous Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/accessing-previous-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Archiving Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/archiving-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Implementing Plugins (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/implementing-plugins-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Incorporating Scripts (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/incorporating-scripts-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Loading Resources (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/loading-resources-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Opening a File (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/opening-a-file-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Policies (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-policies-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Up a Web View (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-up-a-web-view-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working With Document Web Views (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-document-web-views-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working with Frames (legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-frames-legacy"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i",
      "title": "WebKit Objective-C Programming Guide",
      "titleInlineContent": [
        {
          "text": "WebKit Objective-C Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i",
        "doc://com.apple.documentation/documentation/foundation/url_loading_system"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "WebKit-Legacy-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
        "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
        "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
        "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
        "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
      ],
      "title": "WebKit Legacy APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Downloading-Information-Legacy",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebDownload",
        "doc://com.apple.webkit/documentation/WebKit/WebDownloadDelegate"
      ],
      "title": "Downloading Information (Legacy)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Downloading-Information-Legacy",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebDownload",
                "doc://com.apple.webkit/documentation/WebKit/WebDownloadDelegate"
              ],
              "title": "Downloading Information (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i",
                "doc://com.apple.documentation/documentation/foundation/url_loading_system"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "WebKit-Legacy-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
                "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
                "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
                "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
                "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
              ],
              "title": "WebKit Legacy APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDownload/title",
          "value": "WebDownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDownload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDownload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDownloadDelegate/title",
          "value": "WebDownloadDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDownloadDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDownloadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDownloadDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDownloadDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/downloading-information-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/downloading-information-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
