{
  "abstract": [
    {
      "text": "Predefined keys used to access an element dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
        "doc://com.apple.webkit/documentation/WebKit/WebView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/element-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Element Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants represent predefined keys used to access an element dictionary. An element dictionary is an NSDictionary representation of an HTML element, as in a clicked or selected element. Some methods in the WebPolicyDelegate informal protocol have an element dictionary argument. The descriptions below describe the dictionary value for the key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey": {
      "abstract": [
        {
          "text": "The DOMNode for this element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementDOMNodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementDOMNodeKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementDOMNodeKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementdomnodekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey": {
      "abstract": [
        {
          "text": "The WebFrame object associated with this element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementFrameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementFrameKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementFrameKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementframekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey": {
      "abstract": [
        {
          "text": "An NSString of the ALT attribute of an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageAltStringKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageAltStringKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageAltStringKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimagealtstringkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey": {
      "abstract": [
        {
          "text": "An NSImage representing an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimagekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey": {
      "abstract": [
        {
          "text": "An NSValue containing an NSRect, the size of an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageRectKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageRectKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageRectKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimagerectkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey": {
      "abstract": [
        {
          "text": "An NSURL containing the location of an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageURLKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageURLKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimageurlkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey": {
      "abstract": [
        {
          "text": "An NSNumber used as a BOOL value to indicate whether a text element is selected or not. Zero value indicates false, true otherwise.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementIsSelectedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementIsSelectedKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementIsSelectedKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementisselectedkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey": {
      "abstract": [
        {
          "text": "An NSString containing the text within an anchor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementLinkLabelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementLinkLabelKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementLinkLabelKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementlinklabelkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey": {
      "abstract": [
        {
          "text": "The WebFrame object associated with the target of the anchor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementLinkTargetFrameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementLinkTargetFrameKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementLinkTargetFrameKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementlinktargetframekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTitleKey": {
      "abstract": [
        {
          "text": "An NSString containing the title of an anchor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementLinkTitleKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTitleKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementLinkTitleKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementLinkTitleKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementlinktitlekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementLinkURLKey": {
      "abstract": [
        {
          "text": "An NSURL containing the location of a link if the element is within an anchor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementLinkURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementLinkURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementLinkURLKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementLinkURLKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementlinkurlkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s": {
      "abstract": [
        {
          "text": "Connects to a given URL by initiating an asynchronous client request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRequest:"
        }
      ],
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webframe/load(_:)-47p2s"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView": {
      "abstract": [
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " is the core view class in the WebKit framework that manages interactions between the ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " classes. To embed web content in your application, you just create a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " object, attach it to a window, and send a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message to its main frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "role": "symbol",
      "title": "WebView",
      "type": "topic",
      "url": "/documentation/webkit/webview"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Up a Web View (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-up-a-web-view-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementLinkURLKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTitleKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementLinkURLKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTitleKey",
                "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageURLKey/title",
          "value": "WebElementImageURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageRectKey/title",
          "value": "WebElementImageRectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageRectKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageRectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkURLKey/title",
          "value": "WebElementLinkURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementLinkURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkLabelKey/title",
          "value": "WebElementLinkLabelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkLabelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementLinkLabelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkTitleKey/title",
          "value": "WebElementLinkTitleKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkTitleKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementLinkTitleKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementDOMNodeKey/title",
          "value": "WebElementDOMNodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementDOMNodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementDOMNodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementFrameKey/title",
          "value": "WebElementFrameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementFrameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementFrameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementIsSelectedKey/title",
          "value": "WebElementIsSelectedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementIsSelectedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementIsSelectedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/title",
          "value": "WebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title",
          "value": "loadRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageAltStringKey/title",
          "value": "WebElementImageAltStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageAltStringKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageAltStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageKey/title",
          "value": "WebElementImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkTargetFrameKey/title",
          "value": "WebElementLinkTargetFrameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkTargetFrameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementLinkTargetFrameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/element-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/element-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
