{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Opening a File (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebOpenPanelResultListener": {
      "abstract": [
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " user interface delegates that implement the webView:runOpenPanelForFileButtonWithResultListener: method use the methods defined in this protocol to communicate with the listener object. The methods allow the delegate to send a cancel message, or set the selected file name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebOpenPanelResultListener"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebOpenPanelResultListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebOpenPanelResultListener"
        }
      ],
      "role": "symbol",
      "title": "WebOpenPanelResultListener",
      "type": "topic",
      "url": "/documentation/webkit/webopenpanelresultlistener"
    },
    "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessing Previous Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/accessing-previous-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Archiving Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/archiving-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Downloading Information (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/downloading-information-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Implementing Plugins (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/implementing-plugins-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Incorporating Scripts (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/incorporating-scripts-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Loading Resources (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/loading-resources-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Policies (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-policies-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Up a Web View (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-up-a-web-view-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working With Document Web Views (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-document-web-views-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working with Frames (legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-frames-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WebKit-Legacy-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
        "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
        "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
        "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
        "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
      ],
      "title": "WebKit Legacy APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Opening-a-File-Legacy",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebOpenPanelResultListener"
      ],
      "title": "Opening a File (Legacy)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Opening-a-File-Legacy",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebOpenPanelResultListener"
              ],
              "title": "Opening a File (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WebKit-Legacy-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
                "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
                "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
                "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
                "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
              ],
              "title": "WebKit Legacy APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebOpenPanelResultListener/title",
          "value": "WebOpenPanelResultListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebOpenPanelResultListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebOpenPanelResultListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebOpenPanelResultListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebOpenPanelResultListener"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/opening-a-file-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/opening-a-file-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
