{
  "abstract": [
    {
      "text": "Improve your website by optimizing it for Safari.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/optimizing-your-website-for-safari"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Optimizing Your Website for Safari"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari is a full-featured web browser that comes with macOS and iOS. While all W3C-compliant websites work in Safari, there are a few ways that you can optimizing your content for Safari to ensure it works great on Apple devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3030233",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To ensure that your content works great in Safari:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Web Inspector.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use Web Inspector and Safari Developer Tools to inspect details and test the performance of your website in Safari. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://support.apple.com/guide/safari-developer/welcome/mac",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Media Formatting.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Encode media content so that it loads quickly in Safari. For audio and video content, use the HTML5 markup elements ",
                      "type": "text"
                    },
                    {
                      "code": "<audio>",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "<video>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and use ",
                      "type": "text"
                    },
                    {
                      "code": "<canvas>",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for vector graphics and animation. See HLS Authoring Specification for Apple Devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "No Plug-ins.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " To ensure that your website loads fast and efficiently, Safari does not rely on plug-ins to handle audio, video, or animation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Accessibility.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use appropriate markup and tags to ensure the accessibility of your website, including ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://a11yproject.com",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Responsive Design.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use responsive design to accommodate the many different Apple devices for iOS, macOS, and watchOS. A responsive design ensures that users can view your website in Safari everywhere, regardless of the screen or window width. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/videos/play/wwdc2018/239/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/videos/play/wwdc2015/505/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Touch Screen.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Add support for Multi-Touch gestures so these interactions are easier for users on mobile devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Security.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Ensure that your website uses one of Safari’s supported security features, like subresource integrity, TLS, RSA, and HTTPS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Web Standards.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Make use of good web design practices and web standards. Make use of HTML5, CSS3, and the latest web standards supported by the ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://www.w3.org",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use feature detection to make your website browser independent. By detecting the browser, you can not only support multiple browsers but also support multiple WebKit versions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Additionally, you can customize rules for ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/en-us/HT204683",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the web crawler for Apple.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By implementing these best practices and testing your website in Safari, you ensure that visitors to your site have a great experience on all Apple devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/delivering-video-content-for-safari": {
      "abstract": [
        {
          "text": "Improve the performance and appearance of video in your website in Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/delivering-video-content-for-safari",
      "kind": "article",
      "role": "article",
      "title": "Delivering Video Content for Safari",
      "type": "topic",
      "url": "/documentation/webkit/delivering-video-content-for-safari"
    },
    "doc://com.apple.webkit/documentation/WebKit/promoting-apps-with-smart-app-banners": {
      "abstract": [
        {
          "text": "Create a banner to promote your app on the App Store from a website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/promoting-apps-with-smart-app-banners",
      "kind": "article",
      "role": "article",
      "title": "Promoting Apps with Smart App Banners",
      "type": "topic",
      "url": "/documentation/webkit/promoting-apps-with-smart-app-banners"
    },
    "https://a11yproject.com": {
      "identifier": "https://a11yproject.com",
      "title": "A11Y",
      "titleInlineContent": [
        {
          "text": "A11Y",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://a11yproject.com"
    },
    "https://developer.apple.com/videos/play/wwdc2015/505/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2015/505/",
      "title": "Using Safari to Deliver and Debug a Responsive Web Design",
      "titleInlineContent": [
        {
          "text": "Using Safari to Deliver and Debug a Responsive Web Design",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2015/505/"
    },
    "https://developer.apple.com/videos/play/wwdc2018/239/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2018/239/",
      "title": "Designing Web Content for watchOS",
      "titleInlineContent": [
        {
          "text": "Designing Web Content for watchOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2018/239/"
    },
    "https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA": {
      "identifier": "https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA",
      "title": "ARIA",
      "titleInlineContent": [
        {
          "text": "ARIA",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA"
    },
    "https://support.apple.com/en-us/HT204683": {
      "identifier": "https://support.apple.com/en-us/HT204683",
      "title": "Applebot",
      "titleInlineContent": [
        {
          "text": "Applebot",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/HT204683"
    },
    "https://support.apple.com/guide/safari-developer/welcome/mac": {
      "identifier": "https://support.apple.com/guide/safari-developer/welcome/mac",
      "title": "Safari Developer Help",
      "titleInlineContent": [
        {
          "text": "Safari Developer Help",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/safari-developer/welcome/mac"
    },
    "https://www.w3.org": {
      "identifier": "https://www.w3.org",
      "title": "W3C",
      "titleInlineContent": [
        {
          "text": "W3C",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.w3.org"
    },
    "media-3030233": {
      "alt": "Improve your website’s performance in Safari.",
      "identifier": "media-3030233",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4fcae417fa1227eaf78ed2a685a93f6c/media-3030233@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Safari-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/delivering-video-content-for-safari",
        "doc://com.apple.webkit/documentation/WebKit/promoting-apps-with-smart-app-banners"
      ],
      "title": "Safari Support"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Safari-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/delivering-video-content-for-safari",
                "doc://com.apple.webkit/documentation/WebKit/promoting-apps-with-smart-app-banners"
              ],
              "title": "Safari Support"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/optimizing-your-website-for-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/optimizing-your-website-for-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
