{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Setting Up a Web View (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebEditingDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebEditingDelegate"
        }
      ],
      "role": "symbol",
      "title": "WebEditingDelegate",
      "type": "topic",
      "url": "/documentation/webkit/webeditingdelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s": {
      "abstract": [
        {
          "text": "Connects to a given URL by initiating an asynchronous client request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRequest:"
        }
      ],
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webframe/load(_:)-47p2s"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebPreferences": {
      "abstract": [
        {
          "text": "WebPreferences encapsulates the preferences you can change per WebView object. These preferences include font, text encoding, and image settings. Normally a WebView object uses the standard preferences returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebPreferences/standard()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class method. However, you can modify the preferences for individual WebView instances too. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/preferencesIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " WebView method to change a WebView object’s preferences, or to share preferences between WebView objects. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebPreferences/autosaves",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method to specify if the preferences object should be automatically saved to the user defaults database.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebPreferences"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebPreferences"
        }
      ],
      "role": "symbol",
      "title": "WebPreferences",
      "type": "topic",
      "url": "/documentation/webkit/webpreferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebPreferences/autosaves": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether or not the receiver’s attributes are automatically stored in the user defaults database.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autosaves"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebPreferences/autosaves",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autosaves"
        }
      ],
      "role": "symbol",
      "title": "autosaves",
      "type": "topic",
      "url": "/documentation/webkit/webpreferences/autosaves"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebPreferences/standard()": {
      "abstract": [
        {
          "text": "Returns the standard set of preferences that may be used by all WebView objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebPreferences",
          "text": "WebPreferences"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebPreferences/standard()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standardPreferences"
        }
      ],
      "role": "symbol",
      "title": "standard()",
      "type": "topic",
      "url": "/documentation/webkit/webpreferences/standard()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebUIDelegate": {
      "abstract": [
        {
          "text": "Web view user interface delegates implement this protocol to control the opening of new windows, augment the behavior of default menu items displayed when the user clicks elements, and perform other user interface–related tasks. These methods can be invoked as a result of handling JavaScript or other plug-in content. Delegates that display more than one web view per window, for example, need to implement some of these methods to handle that case. The default implementation assumes one window per web view, so non-conventional user interfaces might implement a user interface delegate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebUIDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebUIDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebUIDelegate"
        }
      ],
      "role": "symbol",
      "title": "WebUIDelegate",
      "type": "topic",
      "url": "/documentation/webkit/webuidelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView": {
      "abstract": [
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " is the core view class in the WebKit framework that manages interactions between the ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " classes. To embed web content in your application, you just create a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " object, attach it to a window, and send a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message to its main frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "role": "symbol",
      "title": "WebView",
      "type": "topic",
      "url": "/documentation/webkit/webview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView/preferencesIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the receiver’s preferences.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferencesIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/preferencesIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferencesIdentifier"
        }
      ],
      "role": "symbol",
      "title": "preferencesIdentifier",
      "type": "topic",
      "url": "/documentation/webkit/webview/preferencesidentifier"
    },
    "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessing Previous Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/accessing-previous-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Archiving Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/archiving-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Downloading Information (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/downloading-information-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Implementing Plugins (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/implementing-plugins-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Incorporating Scripts (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/incorporating-scripts-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Loading Resources (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/loading-resources-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Opening a File (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/opening-a-file-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Policies (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-policies-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working With Document Web Views (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-document-web-views-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working with Frames (legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-frames-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WebKit-Legacy-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
        "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
        "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
        "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
        "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
        "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
      ],
      "title": "WebKit Legacy APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-Up-a-Web-View-Legacy",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebView",
        "doc://com.apple.webkit/documentation/WebKit/WebPreferences",
        "doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate",
        "doc://com.apple.webkit/documentation/WebKit/WebUIDelegate"
      ],
      "title": "Setting Up a Web View (Legacy)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-Up-a-Web-View-Legacy",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebView",
                "doc://com.apple.webkit/documentation/WebKit/WebPreferences",
                "doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate",
                "doc://com.apple.webkit/documentation/WebKit/WebUIDelegate"
              ],
              "title": "Setting Up a Web View (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WebKit-Legacy-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
                "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
                "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
                "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
                "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
                "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
              ],
              "title": "WebKit Legacy APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences~1standard()/title",
          "value": "standardPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences~1standard()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "standardPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title",
          "value": "loadRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1preferencesIdentifier/title",
          "value": "preferencesIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1preferencesIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferencesIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/title",
          "value": "WebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences/title",
          "value": "WebPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/title",
          "value": "WebEditingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebEditingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebEditingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebUIDelegate/title",
          "value": "WebUIDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebUIDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebUIDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebUIDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebUIDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences~1autosaves/title",
          "value": "autosaves"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebPreferences~1autosaves/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autosaves"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/setting-up-a-web-view-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/setting-up-a-web-view-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
