{
  "abstract": [
    {
      "text": "Enable WebDriver and run a test.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/testing-with-webdriver-in-safari"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing with WebDriver in Safari"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This article walks you through the process of setting up WebDriver and running a test written in Python. When a test calls a command, the command is executed in the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The client library translates each command into a REST API command.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The REST API command sends the corresponding HTTP request to a local web server hosted by Safari’s driver.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The driver validates the HTTP request’s contents and forwards the command to the appropriate browser instance.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When a command has finished executing, the driver sends an HTTP response for the REST API command. The client library interprets the HTTP response and returns the result to the test code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Make-Sure-You-Have-Safaris-WebDriver",
          "level": 3,
          "text": "Make Sure You Have Safari’s WebDriver",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari and Safari Technology Preview each provide their own ",
              "type": "text"
            },
            {
              "code": "safaridriver",
              "type": "codeVoice"
            },
            {
              "text": " executable. Make sure you already have the executable on your device:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Safari’s executable is located at ",
                      "type": "text"
                    },
                    {
                      "code": "/usr/bin/safaridriver",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Safari Technology Preview’s executable is part of the application bundle’s contents.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Each ",
              "type": "text"
            },
            {
              "code": "safaridriver",
              "type": "codeVoice"
            },
            {
              "text": " is capable of launching only the Safari version it’s associated with, and the two can run simultaneously. Although you can launch ",
              "type": "text"
            },
            {
              "code": "safaridriver",
              "type": "codeVoice"
            },
            {
              "text": " manually by running a ",
              "type": "text"
            },
            {
              "code": "safaridriver",
              "type": "codeVoice"
            },
            {
              "text": " executable, most Selenium libraries launch the driver automatically. See the documentation for your preferred client library to learn how to specify which browser to use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Get-the-Correct-Selenium-Library-Version",
          "level": 3,
          "text": "Get the Correct Selenium Library Version",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Grab a recent release of the ",
              "type": "text"
            },
            {
              "identifier": "https://www.seleniumhq.org/download/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " open source project. Selenium’s Java and Python client libraries offer support for Safari’s native driver implementation starting in the 3.0.0-beta1 release.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t use the old SafariDriver implementation, which is no longer supported by the Selenium project. The Apple-developed driver is a replacement for the legacy SafariDriver formerly maintained by the Selenium project.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Configure-Safari-to-Enable-WebDriver-Support",
          "level": 3,
          "text": "Configure Safari to Enable WebDriver Support",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari’s WebDriver support for developers is turned off by default. How you enable it depends on your operating system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "High Sierra and later:",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Run ",
              "type": "text"
            },
            {
              "code": "safaridriver --enable",
              "type": "codeVoice"
            },
            {
              "text": " once. (If you’re upgrading from a previous macOS release, you may need to use ",
              "type": "text"
            },
            {
              "code": "sudo",
              "type": "codeVoice"
            },
            {
              "text": ".)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Sierra and earlier:",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you haven’t already done so, make the Develop menu available. Choose Safari > Preferences, and on the Advanced tab, select “Show Develop menu in menu bar.” For details, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://support.apple.com/guide/safari/welcome",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose Develop > Allow Remote Automation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Authorize ",
                      "type": "text"
                    },
                    {
                      "code": "safaridriver",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to launch the XPC service that hosts the local web server. To permit this, manually run ",
                      "type": "text"
                    },
                    {
                      "code": "/usr/bin/safaridriver",
                      "type": "codeVoice"
                    },
                    {
                      "text": " once and follow the authentication prompt.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Write-a-WebDriver-Testing-Suite",
          "level": 3,
          "text": "Write a WebDriver Testing Suite",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once you’ve obtained a client library, you can write a WebDriver test and run it against Safari. The example below uses using Python WebDriver to test important functionality of the ",
              "type": "text"
            },
            {
              "identifier": "https://webkit.org/status/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In the Python WebDriver library, each method call synchronously blocks processes until the operation completes. Other WebDriver libraries may provide an asynchronous API.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "code": [
            "#coding: utf-8",
            "from selenium.webdriver.common.by import By",
            "from selenium import webdriver",
            "import unittest",
            "import time",
            "",
            "def setup_module(module):",
            "    WebKitFeatureStatusTest.driver = webdriver.Safari()",
            "",
            "def teardown_module(module):",
            "    WebKitFeatureStatusTest.driver.quit()",
            "",
            "",
            "class WebKitFeatureStatusTest(unittest.TestCase):",
            "    ",
            "    def test_feature_status_page_search(self):",
            "        self.driver.get(\"https://webkit.org/status/\")",
            "            ",
            "        # Enter \"CSS\" into the search box.",
            "        # Ensures that at least one result appears in search",
            "        search_box = self.driver.find_element_by_id(\"search\")",
            "        search_box.send_keys(\"CSS\")",
            "        value = search_box.get_attribute(\"value\")",
            "        self.assertTrue(len(value) > 0)",
            "        search_box.submit()",
            "        time.sleep(1)",
            "        # Count the visible results when filters are applied",
            "        # so one result shows up in at most one filter",
            "        feature_count = self.shown_feature_count()",
            "        self.assertTrue(feature_count > 0)",
            "        ",
            "    def test_feature_status_page_filters(self):",
            "        self.driver.get(\"https://webkit.org/status/\")",
            "            ",
            "        time.sleep(1)",
            "        filters = self.driver.execute_script(\"return document.querySelectorAll('.filter-toggle')\")",
            "        self.assertTrue(len(filters) is 7)",
            "        ",
            "        # Make sure every filter is turned off.",
            "        for checked_filter in filter(lambda f: f.is_selected(), filters):",
            "            checked_filter.click()",
            "        ",
            "        # Make sure you can select every filter.",
            "        for filt in filters:",
            "            filt.click()",
            "            self.assertTrue(filt.is_selected())",
            "            filt.click()",
            "    ",
            "    def shown_feature_count(self):",
            "                return len(self.driver.execute_script(\"return document.querySelectorAll('li.feature:not(.is-hidden)')\"))",
            "",
            "",
            "if __name__ == \"__main__\":",
            "    unittest.main()"
          ],
          "syntax": "python",
          "type": "codeListing"
        },
        {
          "anchor": "Run-Your-Test",
          "level": 3,
          "text": "Run Your Test",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Copy and save the test code above as ",
              "type": "text"
            },
            {
              "code": "test_webkit.py",
              "type": "codeVoice"
            },
            {
              "text": " and run the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "python test_webkit.py"
          ],
          "syntax": "bash",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/about-webdriver-for-safari": {
      "abstract": [
        {
          "text": "Enhance testing of your web content using Safari’s enhancements to WebDriver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/about-webdriver-for-safari",
      "kind": "article",
      "role": "article",
      "title": "About WebDriver for Safari",
      "type": "topic",
      "url": "/documentation/webkit/about-webdriver-for-safari"
    },
    "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-11-1-and-earlier": {
      "abstract": [
        {
          "text": "Test your web content using the WebDriver commands supported by Safari 11.1 and earlier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-11-1-and-earlier",
      "kind": "article",
      "role": "article",
      "title": "macOS WebDriver Commands for Safari 11.1 and earlier",
      "type": "topic",
      "url": "/documentation/webkit/macos-webdriver-commands-for-safari-11-1-and-earlier"
    },
    "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-12-and-later": {
      "abstract": [
        {
          "text": "Test your web content using the WebDriver commands supported by Safari 12 and later.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-12-and-later",
      "kind": "article",
      "role": "article",
      "title": "macOS WebDriver Commands for Safari 12 and later",
      "type": "topic",
      "url": "/documentation/webkit/macos-webdriver-commands-for-safari-12-and-later"
    },
    "https://support.apple.com/guide/safari/welcome": {
      "identifier": "https://support.apple.com/guide/safari/welcome",
      "title": "Safari Help",
      "titleInlineContent": [
        {
          "text": "Safari Help",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/safari/welcome"
    },
    "https://webkit.org/status/": {
      "identifier": "https://webkit.org/status/",
      "title": "WebKit Feature Status",
      "titleInlineContent": [
        {
          "text": "WebKit Feature Status",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://webkit.org/status/"
    },
    "https://www.seleniumhq.org/download/": {
      "identifier": "https://www.seleniumhq.org/download/",
      "title": "Selenium",
      "titleInlineContent": [
        {
          "text": "Selenium",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.seleniumhq.org/download/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WebDriver",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-11-1-and-earlier",
        "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-12-and-later",
        "doc://com.apple.webkit/documentation/WebKit/about-webdriver-for-safari"
      ],
      "title": "WebDriver"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WebDriver",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-11-1-and-earlier",
                "doc://com.apple.webkit/documentation/WebKit/macos-webdriver-commands-for-safari-12-and-later",
                "doc://com.apple.webkit/documentation/WebKit/about-webdriver-for-safari"
              ],
              "title": "WebDriver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/testing-with-webdriver-in-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/testing-with-webdriver-in-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
