{
  "abstract": [
    {
      "text": "The key for accessing the web history items stored in a notification’s user information dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
        "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/web-history-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Web History Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This string is used as the key in the ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary passed as the argument to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory": {
      "abstract": [
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects are used to maintain the pages visited by users. Visited pages are represented by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects. You add and remove history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods. These methods post appropriate notifications when items are added or removed so you can update the display. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " organizes the ",
          "type": "text"
        },
        {
          "code": "WebHistoryItem",
          "type": "codeVoice"
        },
        {
          "text": " objects by the day they were visited, ordered from most recent to oldest. You can request all the days that contain history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method or request the items visited on a particular day using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects can be loaded and saved by specifying a file URL (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "role": "symbol",
      "title": "WebHistory",
      "type": "topic",
      "url": "/documentation/webkit/webhistory"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)": {
      "abstract": [
        {
          "text": "Inserts or updates the specified items in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addItems:"
        }
      ],
      "role": "symbol",
      "title": "addItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/additems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)": {
      "abstract": [
        {
          "text": "Loads the contents of the specified web history file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFromURL:error:"
        }
      ],
      "role": "symbol",
      "title": "load(from:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/load(from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)": {
      "abstract": [
        {
          "text": "Returns web history items that were last visited on the specified date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "onDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendarDate",
          "text": "NSCalendarDate"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisitedOnDay:"
        }
      ],
      "role": "symbol",
      "title": "orderedItemsLastVisited(onDay:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/ordereditemslastvisited(onday:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays": {
      "abstract": [
        {
          "text": "An array of all calendar days represented in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        }
      ],
      "role": "symbol",
      "title": "orderedLastVisitedDays",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/orderedlastvisiteddays"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)": {
      "abstract": [
        {
          "text": "Removes the specified items from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeItems:"
        }
      ],
      "role": "symbol",
      "title": "removeItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/removeitems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification": {
      "abstract": [
        {
          "text": "Posted when all history items have been removed from the web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryAllItemsRemovedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryAllItemsRemovedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryallitemsremovednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem": {
      "abstract": [
        {
          "text": "WebHistoryItem objects encapsulate information about visiting a page so that users can return to that page. WebHistory and WebBackForwardList objects manage lists of WebHistoryItem objects. WebHistoryItem objects are created and added to these lists automatically when loading pages, so you do not need to create WebHistoryItem objects directly.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "role": "symbol",
      "title": "WebHistoryItem",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitem"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification": {
      "abstract": [
        {
          "text": "Posted when history items have been added to a web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsAddedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsAddedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemsaddednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsKey": {
      "abstract": [
        {
          "text": "The key to access an array containing the added or removed web history items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItemsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsKey"
        }
      ],
      "role": "symbol",
      "title": "WebHistoryItemsKey",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemskey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification": {
      "abstract": [
        {
          "text": "Posted when items have been removed from the web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsRemovedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsRemovedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemsremovednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessing Previous Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/accessing-previous-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/title",
          "value": "addItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/title",
          "value": "removeItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/title",
          "value": "orderedLastVisitedDays"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orderedLastVisitedDays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/title",
          "value": "orderedItemsLastVisitedOnDay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "orderedItemsLastVisitedOnDay:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/title",
          "value": "loadFromURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFromURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/title",
          "value": "WebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItemsKey/title",
          "value": "WebHistoryItemsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItemsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItemsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/title",
          "value": "WebHistoryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/web-history-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/web-history-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
