{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "code": "WebBackForwardList",
      "type": "codeVoice"
    },
    {
      "text": " object maintains a list of visited pages used to go back and forward to the most recent page. A ",
      "type": "text"
    },
    {
      "code": "WebBackForwardList",
      "type": "codeVoice"
    },
    {
      "text": " object maintains only the list data—it does not perform actual page loads (in other words, it does not make any client requests). If you need to perform a page load, see the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method in ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " to find out how to do this.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WebBackForwardList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WebBackForwardList"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebBackForwardList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WebBackForwardList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Items are typically inserted in a back-forward list in the order they are visited. A ",
              "type": "text"
            },
            {
              "code": "WebBackForwardList",
              "type": "codeVoice"
            },
            {
              "text": " object also maintains the notion of the current item (which is always at index ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": "), the preceding item (which is at index ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": "), and the following item (which is at index ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": "). The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goBack()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goForward()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods move the current item backward or forward by one. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/go(to:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method sets the current item to the specified item. All other methods that return ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects do not change the value of the current item, they just return the requested item or items. You can also limit the number of history items stored in the back-forward list using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/capacity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "WebBackForwardList",
              "type": "codeVoice"
            },
            {
              "text": " objects also control the number of pages cached. You can turn page caching off by setting the page cache size to ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/pageCacheSize()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, or limit the number of pages cached by passing a value greater than 0.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebBackForwardList",
          "type": "codeVoice"
        },
        {
          "text": " object maintains a list of visited pages used to go back and forward to the most recent page. A ",
          "type": "text"
        },
        {
          "code": "WebBackForwardList",
          "type": "codeVoice"
        },
        {
          "text": " object maintains only the list data—it does not perform actual page loads (in other words, it does not make any client requests). If you need to perform a page load, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to find out how to do this.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebBackForwardList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebBackForwardList"
        }
      ],
      "role": "symbol",
      "title": "WebBackForwardList",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/add(_:)": {
      "abstract": [
        {
          "text": "Inserts an item into the back-forward list, immediately after the current item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/add(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addItem:"
        }
      ],
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/add(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/back(withLimit:)": {
      "abstract": [
        {
          "text": "Returns the items that precede the current item in the back-forward list, up to the specified number of items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "back"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/back(withLimit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backListWithLimit:"
        }
      ],
      "role": "symbol",
      "title": "back(withLimit:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/back(withlimit:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backItem": {
      "abstract": [
        {
          "text": "The item that precedes the current item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backItem"
        }
      ],
      "role": "symbol",
      "title": "backItem",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/backitem"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backListCount": {
      "abstract": [
        {
          "text": "The number of items that precede the current item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backListCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backListCount"
        }
      ],
      "role": "symbol",
      "title": "backListCount",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/backlistcount"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/capacity": {
      "abstract": [
        {
          "text": "The maximum number of items that the back-forward list can contain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/capacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capacity"
        }
      ],
      "role": "symbol",
      "title": "capacity",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/capacity"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/contains(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the back-forward list contains the specified item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/contains(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsItem:"
        }
      ],
      "role": "symbol",
      "title": "contains(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/contains(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/currentItem": {
      "abstract": [
        {
          "text": "The current item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/currentItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentItem"
        }
      ],
      "role": "symbol",
      "title": "currentItem",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/currentitem"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardItem": {
      "abstract": [
        {
          "text": "The item that follows the current item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forwardItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forwardItem"
        }
      ],
      "role": "symbol",
      "title": "forwardItem",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/forwarditem"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardList(withLimit:)": {
      "abstract": [
        {
          "text": "Returns the items that follow the current item in the back-forward list, up to the specified number of items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forwardList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardList(withLimit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forwardListWithLimit:"
        }
      ],
      "role": "symbol",
      "title": "forwardList(withLimit:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/forwardlist(withlimit:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardListCount": {
      "abstract": [
        {
          "text": "The number of items that follow the current item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forwardListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardListCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forwardListCount"
        }
      ],
      "role": "symbol",
      "title": "forwardListCount",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/forwardlistcount"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/go(to:)": {
      "abstract": [
        {
          "text": "Makes the specified item in the back-forward list the current item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/go(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToItem:"
        }
      ],
      "role": "symbol",
      "title": "go(to:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/go(to:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goBack()": {
      "abstract": [
        {
          "text": "Moves backward one item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goBack"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goBack()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goBack"
        }
      ],
      "role": "symbol",
      "title": "goBack()",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/goback()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goForward()": {
      "abstract": [
        {
          "text": "Moves forward one item in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goForward"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goForward()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goForward"
        }
      ],
      "role": "symbol",
      "title": "goForward()",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/goforward()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/item(at:)": {
      "abstract": [
        {
          "text": "Returns the item at the specified index in the back-forward list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/item(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "item(at:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/item(at:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/pageCacheSize()": {
      "abstract": [
        {
          "text": "Returns the maximum number of pages that the receiver can cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageCacheSize"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/pageCacheSize()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageCacheSize"
        }
      ],
      "role": "symbol",
      "title": "pageCacheSize()",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/pagecachesize()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/setPageCacheSize(_:)": {
      "abstract": [
        {
          "text": "Sets the maximum number of pages the receiver can cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPageCacheSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/setPageCacheSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPageCacheSize:"
        }
      ],
      "role": "symbol",
      "title": "setPageCacheSize(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist/setpagecachesize(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object encapsulates the data displayed in a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " object. There is one ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object per frame displayed in a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": ". An entire webpage is represented by a hierarchy of ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " objects in which the root object is called the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "main frame",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "role": "symbol",
      "title": "WebFrame",
      "type": "topic",
      "url": "/documentation/webkit/webframe"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s": {
      "abstract": [
        {
          "text": "Connects to a given URL by initiating an asynchronous client request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRequest:"
        }
      ],
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webframe/load(_:)-47p2s"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory": {
      "abstract": [
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects are used to maintain the pages visited by users. Visited pages are represented by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects. You add and remove history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods. These methods post appropriate notifications when items are added or removed so you can update the display. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " organizes the ",
          "type": "text"
        },
        {
          "code": "WebHistoryItem",
          "type": "codeVoice"
        },
        {
          "text": " objects by the day they were visited, ordered from most recent to oldest. You can request all the days that contain history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method or request the items visited on a particular day using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects can be loaded and saved by specifying a file URL (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "role": "symbol",
      "title": "WebHistory",
      "type": "topic",
      "url": "/documentation/webkit/webhistory"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)": {
      "abstract": [
        {
          "text": "Inserts or updates the specified items in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addItems:"
        }
      ],
      "role": "symbol",
      "title": "addItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/additems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)": {
      "abstract": [
        {
          "text": "Loads the contents of the specified web history file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFromURL:error:"
        }
      ],
      "role": "symbol",
      "title": "load(from:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/load(from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)": {
      "abstract": [
        {
          "text": "Returns web history items that were last visited on the specified date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "onDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendarDate",
          "text": "NSCalendarDate"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisitedOnDay:"
        }
      ],
      "role": "symbol",
      "title": "orderedItemsLastVisited(onDay:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/ordereditemslastvisited(onday:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays": {
      "abstract": [
        {
          "text": "An array of all calendar days represented in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        }
      ],
      "role": "symbol",
      "title": "orderedLastVisitedDays",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/orderedlastvisiteddays"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)": {
      "abstract": [
        {
          "text": "Removes the specified items from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeItems:"
        }
      ],
      "role": "symbol",
      "title": "removeItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/removeitems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem": {
      "abstract": [
        {
          "text": "WebHistoryItem objects encapsulate information about visiting a page so that users can return to that page. WebHistory and WebBackForwardList objects manage lists of WebHistoryItem objects. WebHistoryItem objects are created and added to these lists automatically when loading pages, so you do not need to create WebHistoryItem objects directly.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "role": "symbol",
      "title": "WebHistoryItem",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i",
      "title": "WebKit Objective-C Programming Guide",
      "titleInlineContent": [
        {
          "text": "WebKit Objective-C Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Accessing-Previous-Webpages-Legacy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem"
      ],
      "title": "Accessing Previous Webpages (Legacy)"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adding-and-Removing-Items",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/add(_:)"
      ],
      "title": "Adding and Removing Items"
    },
    {
      "anchor": "Moving-Backward-and-Forward",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goBack()",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goForward()",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/go(to:)"
      ],
      "title": "Moving Backward and Forward"
    },
    {
      "anchor": "Querying-the-Back-Forward-List",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backItem",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backListCount",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/back(withLimit:)",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/contains(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/currentItem",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/item(at:)",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardItem",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardListCount",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardList(withLimit:)"
      ],
      "title": "Querying the Back-Forward List"
    },
    {
      "anchor": "Page-Caching",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/pageCacheSize()",
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/setPageCacheSize(_:)"
      ],
      "title": "Page Caching"
    },
    {
      "anchor": "Setting-Attributes",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/capacity"
      ],
      "title": "Setting Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WebBackForwardList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adding-and-Removing-Items",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/add(_:)"
              ],
              "title": "Adding and Removing Items"
            },
            {
              "anchor": "Moving-Backward-and-Forward",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goBack()",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/goForward()",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/go(to:)"
              ],
              "title": "Moving Backward and Forward"
            },
            {
              "anchor": "Querying-the-Back-Forward-List",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backItem",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/backListCount",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/back(withLimit:)",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/contains(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/currentItem",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/item(at:)",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardItem",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardListCount",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/forwardList(withLimit:)"
              ],
              "title": "Querying the Back-Forward List"
            },
            {
              "anchor": "Page-Caching",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/pageCacheSize()",
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/setPageCacheSize(_:)"
              ],
              "title": "Page Caching"
            },
            {
              "anchor": "Setting-Attributes",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList/capacity"
              ],
              "title": "Setting Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DisplayWebContent/DisplayWebContent.html#//apple_ref/doc/uid/10000164i"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Accessing-Previous-Webpages-Legacy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistory",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem"
              ],
              "title": "Accessing Previous Webpages (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WebBackForwardList"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title",
          "value": "loadRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1setPageCacheSize(_:)/title",
          "value": "setPageCacheSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1setPageCacheSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPageCacheSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1forwardItem/title",
          "value": "forwardItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1forwardItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "forwardItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1currentItem/title",
          "value": "currentItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1currentItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/title",
          "value": "WebFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1go(to:)/title",
          "value": "goToItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1go(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1forwardList(withLimit:)/title",
          "value": "forwardListWithLimit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1forwardList(withLimit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "forwardListWithLimit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/title",
          "value": "addItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1goForward()/title",
          "value": "goForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1goForward()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/title",
          "value": "WebHistoryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/title",
          "value": "removeItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1add(_:)/title",
          "value": "addItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1add(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1back(withLimit:)/title",
          "value": "backListWithLimit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1back(withLimit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backListWithLimit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1goBack()/title",
          "value": "goBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1goBack()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/title",
          "value": "WebBackForwardList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1item(at:)/title",
          "value": "itemAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1item(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1backItem/title",
          "value": "backItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1backItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1contains(_:)/title",
          "value": "containsItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1contains(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "containsItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1backListCount/title",
          "value": "backListCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1backListCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backListCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/title",
          "value": "orderedLastVisitedDays"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orderedLastVisitedDays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1capacity/title",
          "value": "capacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1capacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "capacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1pageCacheSize()/title",
          "value": "pageCacheSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1pageCacheSize()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageCacheSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/title",
          "value": "orderedItemsLastVisitedOnDay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "orderedItemsLastVisitedOnDay:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/title",
          "value": "loadFromURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFromURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/title",
          "value": "WebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1forwardListCount/title",
          "value": "forwardListCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList~1forwardListCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "forwardListCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webbackforwardlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webbackforwardlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
