{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WebFrameLoadDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WebFrameLoadDelegate"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebFrameLoadDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "WebFrameLoadDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDataSource": {
      "abstract": [
        {
          "code": "WebDataSource",
          "type": "codeVoice"
        },
        {
          "text": " encapsulates the web content to be displayed in a web frame view. A ",
          "type": "text"
        },
        {
          "code": "WebDataSource",
          "type": "codeVoice"
        },
        {
          "text": " object has a representation object, conforming to the ",
          "type": "text"
        },
        {
          "code": "WebDocumentRepresentation",
          "type": "codeVoice"
        },
        {
          "text": " protocol, that holds the data in an appropriate format depending on the MIME type. You can extend WebKit to support new MIME types by implementing your own view and representation classes, and specifying the mapping between them using the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " class method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDataSource"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDataSource"
        }
      ],
      "role": "symbol",
      "title": "WebDataSource",
      "type": "topic",
      "url": "/documentation/webkit/webdatasource"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentView": {
      "abstract": [
        {
          "text": "This protocol is adopted by the document view of a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": ". You can extend WebKit to support additional MIME types by implementing your own document view and document representation classes to render data for specific MIME types. You register those classes using the WebFrame ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. Classes that adopt this protocol are expected to be subclasses of ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentView"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentView",
      "type": "topic",
      "url": "/documentation/webkit/webdocumentview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object encapsulates the data displayed in a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " object. There is one ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object per frame displayed in a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": ". An entire webpage is represented by a hierarchy of ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " objects in which the root object is called the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "main frame",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "role": "symbol",
      "title": "WebFrame",
      "type": "topic",
      "url": "/documentation/webkit/webframe"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrameLoadDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrameLoadDelegate"
        }
      ],
      "role": "symbol",
      "title": "WebFrameLoadDelegate",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCancelClientRedirectFor:)": {
      "abstract": [
        {
          "text": "Called when a client redirect is cancelled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didCancelClientRedirectFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCancelClientRedirectFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didCancelClientRedirectForFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didCancelClientRedirectFor:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didcancelclientredirectfor:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didChangeLocationWithinPageFor:)": {
      "abstract": [
        {
          "text": "Called when the scroll position within a frame changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didChangeLocationWithinPageFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didChangeLocationWithinPageFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didChangeLocationWithinPageForFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didChangeLocationWithinPageFor:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didchangelocationwithinpagefor:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)": {
      "abstract": [
        {
          "text": "Called when the JavaScript window object in a frame is ready for loading.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didClearWindowObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebScriptObject",
          "text": "WebScriptObject"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didClearWindowObject:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didClearWindowObject:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didclearwindowobject:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCommitLoadFor:)": {
      "abstract": [
        {
          "text": "Called when content starts arriving for a page load.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didCommitLoadFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCommitLoadFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didCommitLoadForFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didCommitLoadFor:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didcommitloadfor:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCreateJavaScriptContext:for:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that a new JavaScript context has been created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didCreateJavaScriptContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCreateJavaScriptContext:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didCreateJavaScriptContext:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didCreateJavaScriptContext:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didcreatejavascriptcontext:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailLoadWithError:for:)": {
      "abstract": [
        {
          "text": "Called when an error occurs loading a committed data source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didFailLoadWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailLoadWithError:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didFailLoadWithError:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didFailLoadWithError:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didfailloadwitherror:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailProvisionalLoadWithError:for:)": {
      "abstract": [
        {
          "text": "Called if an error occurs when starting to load data for a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didFailProvisionalLoadWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailProvisionalLoadWithError:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didFailProvisionalLoadWithError:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didFailProvisionalLoadWithError:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didfailprovisionalloadwitherror:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFinishLoadFor:)": {
      "abstract": [
        {
          "text": "Called when a page load completes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLoadFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFinishLoadFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didFinishLoadForFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didFinishLoadFor:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didfinishloadfor:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveIcon:for:)": {
      "abstract": [
        {
          "text": "Called when a page icon changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveIcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveIcon:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didReceiveIcon:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didReceiveIcon:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didreceiveicon:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveServerRedirectForProvisionalLoadFor:)": {
      "abstract": [
        {
          "text": "Called when a provisional data source for a frame receives a server redirect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveServerRedirectForProvisionalLoadFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveServerRedirectForProvisionalLoadFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didReceiveServerRedirectForProvisionalLoadForFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didReceiveServerRedirectForProvisionalLoadFor:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didreceiveserverredirectforprovisionalloadfor:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveTitle:for:)": {
      "abstract": [
        {
          "text": "Called when the page title of a frame loads or changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveTitle:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didReceiveTitle:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didReceiveTitle:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didreceivetitle:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didStartProvisionalLoadFor:)": {
      "abstract": [
        {
          "text": "Called when a page load is in progress in a given frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didStartProvisionalLoadFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didStartProvisionalLoadFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didStartProvisionalLoadForFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didStartProvisionalLoadFor:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didstartprovisionalloadfor:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willClose:)": {
      "abstract": [
        {
          "text": "Called when a frame will be closed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "willClose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willClose:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:willCloseFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:willClose:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:willclose:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willPerformClientRedirectTo:delay:fire:for:)": {
      "abstract": [
        {
          "text": "Called when a frame receives a client redirect and before it is fired.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "willPerformClientRedirectTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "delay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willPerformClientRedirectTo:delay:fire:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:willPerformClientRedirectToURL:delay:fireDate:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:willPerformClientRedirectTo:delay:fire:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:willperformclientredirectto:delay:fire:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView:windowScriptObjectAvailable:": {
      "abstract": [
        {
          "text": "Called when a frame’s scripting object for a page is available. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method instead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "webView:windowScriptObjectAvailable:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView:windowScriptObjectAvailable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:windowScriptObjectAvailable:"
        }
      ],
      "role": "symbol",
      "title": "webView:windowScriptObjectAvailable:",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview:windowscriptobjectavailable:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameView": {
      "abstract": [
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " objects and their subviews display the web content contained in a frame. You never create instances of ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " directly—",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " objects create and manage a hierarchy of ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " objects, one for each frame. ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " objects use a scroll view whose document view conforms to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrameView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrameView"
        }
      ],
      "role": "symbol",
      "title": "WebFrameView",
      "type": "topic",
      "url": "/documentation/webkit/webframeview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)": {
      "abstract": [
        {
          "text": "Specifies the view and representation objects to be used for specific MIME types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerClass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "representationClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forMIMEType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerViewClass:representationClass:forMIMEType:"
        }
      ],
      "role": "symbol",
      "title": "registerClass(_:representationClass:forMIMEType:)",
      "type": "topic",
      "url": "/documentation/webkit/webview/registerclass(_:representationclass:formimetype:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Frames-Legacy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebFrame",
        "doc://com.apple.webkit/documentation/WebKit/WebDataSource",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameView"
      ],
      "title": "Working with Frames (Legacy)"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCancelClientRedirectFor:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didChangeLocationWithinPageFor:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCommitLoadFor:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCreateJavaScriptContext:for:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailLoadWithError:for:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailProvisionalLoadWithError:for:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFinishLoadFor:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveIcon:for:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveServerRedirectForProvisionalLoadFor:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveTitle:for:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didStartProvisionalLoadFor:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willClose:)",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willPerformClientRedirectTo:delay:fire:for:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WebFrameLoadDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCancelClientRedirectFor:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didChangeLocationWithinPageFor:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCommitLoadFor:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didCreateJavaScriptContext:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailLoadWithError:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFailProvisionalLoadWithError:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didFinishLoadFor:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveIcon:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveServerRedirectForProvisionalLoadFor:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didReceiveTitle:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didStartProvisionalLoadFor:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willClose:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:willPerformClientRedirectTo:delay:fire:for:)",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView:windowScriptObjectAvailable:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Frames-Legacy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebFrame",
                "doc://com.apple.webkit/documentation/WebKit/WebDataSource",
                "doc://com.apple.webkit/documentation/WebKit/WebFrameView"
              ],
              "title": "Working with Frames (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WebFrameLoadDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDataSource/title",
          "value": "WebDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didFailLoadWithError:for:)/title",
          "value": "webView:didFailLoadWithError:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didFailLoadWithError:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didFailLoadWithError:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:willClose:)/title",
          "value": "webView:willCloseFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:willClose:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:willCloseFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate/title",
          "value": "WebFrameLoadDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/title",
          "value": "WebDocumentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didCancelClientRedirectFor:)/title",
          "value": "webView:didCancelClientRedirectForFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didCancelClientRedirectFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didCancelClientRedirectForFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:willPerformClientRedirectTo:delay:fire:for:)/title",
          "value": "webView:willPerformClientRedirectToURL:delay:fireDate:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:willPerformClientRedirectTo:delay:fire:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:willPerformClientRedirectToURL:delay:fireDate:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didReceiveIcon:for:)/title",
          "value": "webView:didReceiveIcon:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didReceiveIcon:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didReceiveIcon:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didFinishLoadFor:)/title",
          "value": "webView:didFinishLoadForFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didFinishLoadFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didFinishLoadForFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didFailProvisionalLoadWithError:for:)/title",
          "value": "webView:didFailProvisionalLoadWithError:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didFailProvisionalLoadWithError:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didFailProvisionalLoadWithError:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didCreateJavaScriptContext:for:)/title",
          "value": "webView:didCreateJavaScriptContext:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didCreateJavaScriptContext:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didCreateJavaScriptContext:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didChangeLocationWithinPageFor:)/title",
          "value": "webView:didChangeLocationWithinPageForFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didChangeLocationWithinPageFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didChangeLocationWithinPageForFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didReceiveTitle:for:)/title",
          "value": "webView:didReceiveTitle:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didReceiveTitle:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didReceiveTitle:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameView/title",
          "value": "WebFrameView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/title",
          "value": "WebFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didCommitLoadFor:)/title",
          "value": "webView:didCommitLoadForFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didCommitLoadFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didCommitLoadForFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1registerClass(_:representationClass:forMIMEType:)/title",
          "value": "registerViewClass:representationClass:forMIMEType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1registerClass(_:representationClass:forMIMEType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "registerViewClass:representationClass:forMIMEType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didReceiveServerRedirectForProvisionalLoadFor:)/title",
          "value": "webView:didReceiveServerRedirectForProvisionalLoadForFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didReceiveServerRedirectForProvisionalLoadFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didReceiveServerRedirectForProvisionalLoadForFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didClearWindowObject:for:)/title",
          "value": "webView:didClearWindowObject:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didClearWindowObject:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didClearWindowObject:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didStartProvisionalLoadFor:)/title",
          "value": "webView:didStartProvisionalLoadForFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didStartProvisionalLoadFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didStartProvisionalLoadForFrame:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webframeloaddelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webframeloaddelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
