{
  "abstract": [
    {
      "text": "Posted when web history items have been saved to a URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebHistorySavedNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@WebHistorySavedNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "WebHistorySavedNotification"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebHistorySavedNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "WebHistorySavedNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "WebHistorySavedNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The notification object is the web history that saved the history items. This notification does not contain a ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)": {
      "abstract": [
        {
          "text": "Saves the web history to the specified file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToURL:error:"
        }
      ],
      "role": "symbol",
      "title": "save(to:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/save(to:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification": {
      "abstract": [
        {
          "text": "Posted when all history items have been removed from the web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryAllItemsRemovedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryAllItemsRemovedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryallitemsremovednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemChangedNotification": {
      "abstract": [
        {
          "text": "Posted by a WebHistoryItem object when the value of the history item’s title, alternate title, URL strings, or last visited interval changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemChangedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemchangednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification": {
      "abstract": [
        {
          "text": "Posted when history items have been added to a web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsAddedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsAddedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemsaddednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification": {
      "abstract": [
        {
          "text": "Posted when items have been removed from the web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsRemovedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsRemovedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemsremovednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryLoadedNotification": {
      "abstract": [
        {
          "text": "Posted when web history items have been loaded from a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryLoadedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryLoadedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryLoadedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryloadednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistorySavedNotification": {
      "abstract": [
        {
          "text": "Posted when web history items have been saved to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistorySavedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistorySavedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistorySavedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistorysavednotification"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemChangedNotification",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryLoadedNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1save(to:)/title",
          "value": "saveToURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1save(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveToURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webhistorysavednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
