{
  "abstract": [
    {
      "code": "WebHistory",
      "type": "codeVoice"
    },
    {
      "text": " objects are used to maintain the pages visited by users. Visited pages are represented by ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " objects. You add and remove history items using the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " methods. These methods post appropriate notifications when items are added or removed so you can update the display. ",
      "type": "text"
    },
    {
      "code": "WebHistory",
      "type": "codeVoice"
    },
    {
      "text": " organizes the ",
      "type": "text"
    },
    {
      "code": "WebHistoryItem",
      "type": "codeVoice"
    },
    {
      "text": " objects by the day they were visited, ordered from most recent to oldest. You can request all the days that contain history items using the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method or request the items visited on a particular day using the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method. ",
      "type": "text"
    },
    {
      "code": "WebHistory",
      "type": "codeVoice"
    },
    {
      "text": " objects can be loaded and saved by specifying a file URL (see ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ").",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebHistory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WebHistory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WebHistory"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebHistory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WebHistory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521391-webhistoryallitemsremoved": {
      "abstract": [
        {
          "text": "Posted when all history items have been removed from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryAllItemsRemoved"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521391-webhistoryallitemsremoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryAllItemsRemoved",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1521391-webhistoryallitemsremoved"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521392-webhistoryitemsremoved": {
      "abstract": [
        {
          "text": "Posted when items have been removed from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItemsRemoved"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521392-webhistoryitemsremoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsRemoved",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1521392-webhistoryitemsremoved"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521395-webhistoryloaded": {
      "abstract": [
        {
          "text": "Posted when web history items have been loaded from a URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryLoaded"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521395-webhistoryloaded",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryLoaded",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1521395-webhistoryloaded"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521397-webhistorysaved": {
      "abstract": [
        {
          "text": "Posted when web history items have been saved to a URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "WebHistorySaved"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521397-webhistorysaved",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistorySaved",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1521397-webhistorysaved"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521408-webhistoryitemsadded": {
      "abstract": [
        {
          "text": "Posted when history items have been added to a web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItemsAdded"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521408-webhistoryitemsadded",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsAdded",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1521408-webhistoryitemsadded"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1525160-webhistoryitemchanged": {
      "abstract": [
        {
          "text": "Posted by a WebHistoryItem object when the value of the history item’s title, alternate title, URL strings, or last visited interval changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItemChanged"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1525160-webhistoryitemchanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemChanged",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1525160-webhistoryitemchanged"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebBackForwardList",
          "type": "codeVoice"
        },
        {
          "text": " object maintains a list of visited pages used to go back and forward to the most recent page. A ",
          "type": "text"
        },
        {
          "code": "WebBackForwardList",
          "type": "codeVoice"
        },
        {
          "text": " object maintains only the list data—it does not perform actual page loads (in other words, it does not make any client requests). If you need to perform a page load, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to find out how to do this.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebBackForwardList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebBackForwardList"
        }
      ],
      "role": "symbol",
      "title": "WebBackForwardList",
      "type": "topic",
      "url": "/documentation/webkit/webbackforwardlist"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object encapsulates the data displayed in a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " object. There is one ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " object per frame displayed in a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": ". An entire webpage is represented by a hierarchy of ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " objects in which the root object is called the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "main frame",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrame"
        }
      ],
      "role": "symbol",
      "title": "WebFrame",
      "type": "topic",
      "url": "/documentation/webkit/webframe"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s": {
      "abstract": [
        {
          "text": "Connects to a given URL by initiating an asynchronous client request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRequest:"
        }
      ],
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webframe/load(_:)-47p2s"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory": {
      "abstract": [
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects are used to maintain the pages visited by users. Visited pages are represented by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects. You add and remove history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods. These methods post appropriate notifications when items are added or removed so you can update the display. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " organizes the ",
          "type": "text"
        },
        {
          "code": "WebHistoryItem",
          "type": "codeVoice"
        },
        {
          "text": " objects by the day they were visited, ordered from most recent to oldest. You can request all the days that contain history items using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method or request the items visited on a particular day using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. ",
          "type": "text"
        },
        {
          "code": "WebHistory",
          "type": "codeVoice"
        },
        {
          "text": " objects can be loaded and saved by specifying a file URL (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistory"
        }
      ],
      "role": "symbol",
      "title": "WebHistory",
      "type": "topic",
      "url": "/documentation/webkit/webhistory"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)": {
      "abstract": [
        {
          "text": "Inserts or updates the specified items in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addItems:"
        }
      ],
      "role": "symbol",
      "title": "addItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/additems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyAgeInDaysLimit": {
      "abstract": [
        {
          "text": "The maximum age of web history items that can be retrieved.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "historyAgeInDaysLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyAgeInDaysLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "historyAgeInDaysLimit"
        }
      ],
      "role": "symbol",
      "title": "historyAgeInDaysLimit",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/historyageindayslimit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyItemLimit": {
      "abstract": [
        {
          "text": "The maximum number of web history items that can be stored.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "historyItemLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyItemLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "historyItemLimit"
        }
      ],
      "role": "symbol",
      "title": "historyItemLimit",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/historyitemlimit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/item(for:)": {
      "abstract": [
        {
          "text": "Returns the web history item that corresponds to the specified web location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistoryItem",
          "text": "WebHistoryItem"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/item(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemForURL:"
        }
      ],
      "role": "symbol",
      "title": "item(for:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/item(for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)": {
      "abstract": [
        {
          "text": "Loads the contents of the specified web history file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFromURL:error:"
        }
      ],
      "role": "symbol",
      "title": "load(from:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/load(from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/optionalShared()": {
      "abstract": [
        {
          "text": "Returns a shared web history object, if one exists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionalShared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistory",
          "text": "WebHistory"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/optionalShared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalSharedHistory"
        }
      ],
      "role": "symbol",
      "title": "optionalShared()",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/optionalshared()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)": {
      "abstract": [
        {
          "text": "Returns web history items that were last visited on the specified date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "onDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendarDate",
          "text": "NSCalendarDate"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedItemsLastVisitedOnDay:"
        }
      ],
      "role": "symbol",
      "title": "orderedItemsLastVisited(onDay:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/ordereditemslastvisited(onday:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays": {
      "abstract": [
        {
          "text": "An array of all calendar days represented in the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderedLastVisitedDays"
        }
      ],
      "role": "symbol",
      "title": "orderedLastVisitedDays",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/orderedlastvisiteddays"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeAllItems()": {
      "abstract": [
        {
          "text": "Removes all items from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllItems"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeAllItems()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllItems"
        }
      ],
      "role": "symbol",
      "title": "removeAllItems()",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/removeallitems()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)": {
      "abstract": [
        {
          "text": "Removes the specified items from the web history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeItems"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeItems:"
        }
      ],
      "role": "symbol",
      "title": "removeItems(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/removeitems(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)": {
      "abstract": [
        {
          "text": "Saves the web history to the specified file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToURL:error:"
        }
      ],
      "role": "symbol",
      "title": "save(to:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/save(to:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistory/setOptionalShared(_:)": {
      "abstract": [
        {
          "text": "Sets the web history object to share.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOptionalShared"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebHistory",
          "text": "WebHistory"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistory/setOptionalShared(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOptionalSharedHistory:"
        }
      ],
      "role": "symbol",
      "title": "setOptionalShared(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webhistory/setoptionalshared(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification": {
      "abstract": [
        {
          "text": "Posted when all history items have been removed from the web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryAllItemsRemovedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryAllItemsRemovedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryallitemsremovednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem": {
      "abstract": [
        {
          "text": "WebHistoryItem objects encapsulate information about visiting a page so that users can return to that page. WebHistory and WebBackForwardList objects manage lists of WebHistoryItem objects. WebHistoryItem objects are created and added to these lists automatically when loading pages, so you do not need to create WebHistoryItem objects directly.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebHistoryItem"
        }
      ],
      "role": "symbol",
      "title": "WebHistoryItem",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitem"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemChangedNotification": {
      "abstract": [
        {
          "text": "Posted by a WebHistoryItem object when the value of the history item’s title, alternate title, URL strings, or last visited interval changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemChangedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemchangednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification": {
      "abstract": [
        {
          "text": "Posted when history items have been added to a web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsAddedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsAddedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemsaddednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification": {
      "abstract": [
        {
          "text": "Posted when items have been removed from the web history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryItemsRemovedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryItemsRemovedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryitemsremovednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistoryLoadedNotification": {
      "abstract": [
        {
          "text": "Posted when web history items have been loaded from a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistoryLoadedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistoryLoadedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistoryLoadedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistoryloadednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebHistorySavedNotification": {
      "abstract": [
        {
          "text": "Posted when web history items have been saved to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebHistorySavedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebHistorySavedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebHistorySavedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webhistorysavednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/web-history-dictionary-keys": {
      "abstract": [
        {
          "text": "The key for accessing the web history items stored in a notification’s user information dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/web-history-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Web History Dictionary Keys",
      "type": "topic",
      "url": "/documentation/webkit/web-history-dictionary-keys"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Previous-Webpages-Legacy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
        "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem"
      ],
      "title": "Accessing Previous Webpages (Legacy)"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Shared-History-Objects",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/optionalShared()",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/setOptionalShared(_:)"
      ],
      "title": "Accessing Shared History Objects"
    },
    {
      "anchor": "Adding-and-Removing-History-Items",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeAllItems()"
      ],
      "title": "Adding and Removing History Items"
    },
    {
      "anchor": "Getting-Web-History-Items",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/item(for:)"
      ],
      "title": "Getting Web History Items"
    },
    {
      "anchor": "Loading-and-Saving-History-Information",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)"
      ],
      "title": "Loading and Saving History Information"
    },
    {
      "anchor": "Getting-and-Setting-Attributes",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyAgeInDaysLimit",
        "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyItemLimit"
      ],
      "title": "Getting and Setting Attributes"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/web-history-dictionary-keys"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521391-webhistoryallitemsremoved",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1525160-webhistoryitemchanged",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521408-webhistoryitemsadded",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521392-webhistoryitemsremoved",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521395-webhistoryloaded",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1521397-webhistorysaved"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WebHistory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Shared-History-Objects",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/optionalShared()",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/setOptionalShared(_:)"
              ],
              "title": "Accessing Shared History Objects"
            },
            {
              "anchor": "Adding-and-Removing-History-Items",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/addItems(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeItems(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/removeAllItems()"
              ],
              "title": "Adding and Removing History Items"
            },
            {
              "anchor": "Getting-Web-History-Items",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedItemsLastVisited(onDay:)",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/orderedLastVisitedDays",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/item(for:)"
              ],
              "title": "Getting Web History Items"
            },
            {
              "anchor": "Loading-and-Saving-History-Information",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/load(from:)",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/save(to:)"
              ],
              "title": "Loading and Saving History Information"
            },
            {
              "anchor": "Getting-and-Setting-Attributes",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyAgeInDaysLimit",
                "doc://com.apple.webkit/documentation/WebKit/WebHistory/historyItemLimit"
              ],
              "title": "Getting and Setting Attributes"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/web-history-dictionary-keys"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryAllItemsRemovedNotification",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemChangedNotification",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsAddedNotification",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItemsRemovedNotification",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryLoadedNotification",
                "doc://com.apple.webkit/documentation/WebKit/WebHistorySavedNotification"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Previous-Webpages-Legacy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebBackForwardList",
                "doc://com.apple.webkit/documentation/WebKit/WebHistoryItem"
              ],
              "title": "Accessing Previous Webpages (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WebHistory"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1setOptionalShared(_:)/title",
          "value": "setOptionalSharedHistory:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1setOptionalShared(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setOptionalSharedHistory:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/title",
          "value": "addItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1addItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/title",
          "value": "WebFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/title",
          "value": "removeItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeItems(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1historyItemLimit/title",
          "value": "historyItemLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1historyItemLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "historyItemLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1item(for:)/title",
          "value": "itemForURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1item(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemForURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeAllItems()/title",
          "value": "removeAllItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1removeAllItems()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/title",
          "value": "orderedItemsLastVisitedOnDay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedItemsLastVisited(onDay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "orderedItemsLastVisitedOnDay:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/title",
          "value": "WebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/title",
          "value": "WebBackForwardList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebBackForwardList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebBackForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/title",
          "value": "orderedLastVisitedDays"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1orderedLastVisitedDays/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orderedLastVisitedDays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title",
          "value": "loadRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1save(to:)/title",
          "value": "saveToURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1save(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveToURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/title",
          "value": "WebHistoryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistoryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebHistoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/title",
          "value": "loadFromURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1load(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFromURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1historyAgeInDaysLimit/title",
          "value": "historyAgeInDaysLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1historyAgeInDaysLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "historyAgeInDaysLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1optionalShared()/title",
          "value": "optionalSharedHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebHistory~1optionalShared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "optionalSharedHistory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webhistory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webhistory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
