{
  "abstract": [
    {
      "text": "Posted when the web preference settings are changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebPreferencesChangedNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@WebPreferencesChangedNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "WebPreferencesChangedNotification"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebPreferencesChangedNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "WebPreferencesChangedNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "WebPreferencesChangedNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The notification object is the WebPreferences object that changed. This notification does not contain a ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebActionButtonKey": {
      "abstract": [
        {
          "text": "An NSNumber object where ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " indicates the left button, ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " indicates the middle button, and ",
          "type": "text"
        },
        {
          "code": "2",
          "type": "codeVoice"
        },
        {
          "text": " indicates the right button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebActionButtonKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionButtonKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebActionButtonKey"
        }
      ],
      "role": "symbol",
      "title": "WebActionButtonKey",
      "type": "topic",
      "url": "/documentation/webkit/webactionbuttonkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebActionElementKey": {
      "abstract": [
        {
          "text": "A dictionary containing element information. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for a description of the key-value pairs in this dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebActionElementKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionElementKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebActionElementKey"
        }
      ],
      "role": "symbol",
      "title": "WebActionElementKey",
      "type": "topic",
      "url": "/documentation/webkit/webactionelementkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebActionModifierFlagsKey": {
      "abstract": [
        {
          "text": "An unsigned number that indicates the modifier flag.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebActionModifierFlagsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionModifierFlagsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebActionModifierFlagsKey"
        }
      ],
      "role": "symbol",
      "title": "WebActionModifierFlagsKey",
      "type": "topic",
      "url": "/documentation/webkit/webactionmodifierflagskey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey": {
      "abstract": [
        {
          "text": "The navigation type of the action. Can be any of the values defined in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " below.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebActionNavigationTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebActionNavigationTypeKey"
        }
      ],
      "role": "symbol",
      "title": "WebActionNavigationTypeKey",
      "type": "topic",
      "url": "/documentation/webkit/webactionnavigationtypekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebActionOriginalURLKey": {
      "abstract": [
        {
          "text": "The URL that initiated the action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebActionOriginalURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionOriginalURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebActionOriginalURLKey"
        }
      ],
      "role": "symbol",
      "title": "WebActionOriginalURLKey",
      "type": "topic",
      "url": "/documentation/webkit/webactionoriginalurlkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebArchivePboardType": {
      "abstract": [
        {
          "text": "The pasteboard type constant used when adding or accessing a WebArchive on the pasteboard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebArchivePboardType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebArchivePboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebArchivePboardType"
        }
      ],
      "role": "symbol",
      "title": "WebArchivePboardType",
      "type": "topic",
      "url": "/documentation/webkit/webarchivepboardtype"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey": {
      "abstract": [
        {
          "text": "The DOMNode for this element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementDOMNodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementDOMNodeKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementDOMNodeKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementdomnodekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey": {
      "abstract": [
        {
          "text": "The WebFrame object associated with this element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementFrameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementFrameKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementFrameKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementframekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey": {
      "abstract": [
        {
          "text": "An NSString of the ALT attribute of an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageAltStringKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageAltStringKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageAltStringKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimagealtstringkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey": {
      "abstract": [
        {
          "text": "An NSImage representing an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimagekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey": {
      "abstract": [
        {
          "text": "An NSValue containing an NSRect, the size of an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageRectKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageRectKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageRectKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimagerectkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey": {
      "abstract": [
        {
          "text": "An NSURL containing the location of an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementImageURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementImageURLKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementImageURLKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementimageurlkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey": {
      "abstract": [
        {
          "text": "An NSNumber used as a BOOL value to indicate whether a text element is selected or not. Zero value indicates false, true otherwise.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementIsSelectedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementIsSelectedKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementIsSelectedKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementisselectedkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey": {
      "abstract": [
        {
          "text": "An NSString containing the text within an anchor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementLinkLabelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementLinkLabelKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementLinkLabelKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementlinklabelkey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey": {
      "abstract": [
        {
          "text": "The WebFrame object associated with the target of the anchor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebElementLinkTargetFrameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebElementLinkTargetFrameKey"
        }
      ],
      "role": "symbol",
      "title": "WebElementLinkTargetFrameKey",
      "type": "topic",
      "url": "/documentation/webkit/webelementlinktargetframekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType": {
      "abstract": [
        {
          "text": "Possible values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key that appears in an action dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebNavigationType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationType"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebPreferencesChangedNotification": {
      "abstract": [
        {
          "text": "Posted when the web preference settings are changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WebPreferencesChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebPreferencesChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WebPreferencesChangedNotification",
      "type": "topic",
      "url": "/documentation/webkit/webpreferenceschangednotification"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView": {
      "abstract": [
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " is the core view class in the WebKit framework that manages interactions between the ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " classes. To embed web content in your application, you just create a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " object, attach it to a window, and send a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message to its main frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "role": "symbol",
      "title": "WebView",
      "type": "topic",
      "url": "/documentation/webkit/webview"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WebKit-Constants-Legacy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebActionButtonKey",
        "doc://com.apple.webkit/documentation/WebKit/WebActionElementKey",
        "doc://com.apple.webkit/documentation/WebKit/WebActionModifierFlagsKey",
        "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey",
        "doc://com.apple.webkit/documentation/WebKit/WebActionOriginalURLKey",
        "doc://com.apple.webkit/documentation/WebKit/WebArchivePboardType",
        "doc://com.apple.webkit/documentation/WebKit/WebElementDOMNodeKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementFrameKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageAltStringKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageRectKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementImageURLKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementIsSelectedKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementLinkLabelKey",
        "doc://com.apple.webkit/documentation/WebKit/WebElementLinkTargetFrameKey"
      ],
      "title": "WebKit Constants (Legacy)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementIsSelectedKey/title",
          "value": "WebElementIsSelectedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementIsSelectedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementIsSelectedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionModifierFlagsKey/title",
          "value": "WebActionModifierFlagsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionModifierFlagsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebActionModifierFlagsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkLabelKey/title",
          "value": "WebElementLinkLabelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkLabelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementLinkLabelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebArchivePboardType/title",
          "value": "WebArchivePboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebArchivePboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebArchivePboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageURLKey/title",
          "value": "WebElementImageURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkTargetFrameKey/title",
          "value": "WebElementLinkTargetFrameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementLinkTargetFrameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementLinkTargetFrameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionOriginalURLKey/title",
          "value": "WebActionOriginalURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionOriginalURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebActionOriginalURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageAltStringKey/title",
          "value": "WebElementImageAltStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageAltStringKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageAltStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/title",
          "value": "WebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType/title",
          "value": "WebNavigationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionNavigationTypeKey/title",
          "value": "WebActionNavigationTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionNavigationTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebActionNavigationTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementDOMNodeKey/title",
          "value": "WebElementDOMNodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementDOMNodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementDOMNodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageRectKey/title",
          "value": "WebElementImageRectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageRectKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageRectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionButtonKey/title",
          "value": "WebActionButtonKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionButtonKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebActionButtonKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageKey/title",
          "value": "WebElementImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionElementKey/title",
          "value": "WebActionElementKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionElementKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebActionElementKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementFrameKey/title",
          "value": "WebElementFrameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebElementFrameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebElementFrameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webpreferenceschangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
