{
  "abstract": [
    {
      "text": "Web view resource load delegates implement this protocol to be notified on the progress of loading individual resources. Note that there can be hundreds of resources, such as images and other media, per page. So, if you just want to get page loading status see the WebFrameLoadDelegate protocol.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WebResourceLoadDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WebResourceLoadDelegate"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebResourceLoadDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "WebResourceLoadDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WebResourceLoadDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There’s a separate client request and server response made for each resource on a page. By implementing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:identifierForInitialRequest:from:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, resource load delegates provide a tracking object used to identify individual resources in subsequent calls to delegate methods. Delegates are then notified when resource loading starts, when data is incrementally received, when any load errors occur, and when the load is complete. Delegates may also change a request before it is sent. In some cases, depending on the page content and server redirects, methods defined in this protocol may be invoked multiple times (see individual method descriptions for more details). All the methods in this protocol are optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResource": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebResource",
          "type": "codeVoice"
        },
        {
          "text": " object represents a downloaded URL. It encapsulates the data of the download as well as other resource properties such as the URL, MIME type, and frame name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebResource"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebResource"
        }
      ],
      "role": "symbol",
      "title": "WebResource",
      "type": "topic",
      "url": "/documentation/webkit/webresource"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate": {
      "abstract": [
        {
          "text": "Web view resource load delegates implement this protocol to be notified on the progress of loading individual resources. Note that there can be hundreds of resources, such as images and other media, per page. So, if you just want to get page loading status see the WebFrameLoadDelegate protocol.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebResourceLoadDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebResourceLoadDelegate"
        }
      ],
      "role": "symbol",
      "title": "WebResourceLoadDelegate",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:identifierForInitialRequest:from:)": {
      "abstract": [
        {
          "text": "Returns an identifier object used to track the progress of loading a single resource.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "identifierForInitialRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:identifierForInitialRequest:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:identifierForInitialRequest:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:identifierForInitialRequest:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:identifierforinitialrequest:from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:plugInFailedWithError:dataSource:)": {
      "abstract": [
        {
          "text": "Invoked when a plug-in fails to load.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "plugInFailedWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "dataSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:plugInFailedWithError:dataSource:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:plugInFailedWithError:dataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:plugInFailedWithError:dataSource:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:pluginfailedwitherror:datasource:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didCancel:from:)": {
      "abstract": [
        {
          "text": "Invoked when an authentication challenge for a resource was canceled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLAuthenticationChallenge",
          "text": "URLAuthenticationChallenge"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didCancel:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:didCancelAuthenticationChallenge:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:didCancel:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:didcancel:from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFailLoadingWithError:from:)": {
      "abstract": [
        {
          "text": "Invoked when a resource failed to load.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didFailLoadingWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFailLoadingWithError:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:didFailLoadingWithError:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:didFailLoadingWithError:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:didfailloadingwitherror:from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFinishLoadingFrom:)": {
      "abstract": [
        {
          "text": "Invoked when all of the data for a given resource is loaded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLoadingFrom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFinishLoadingFrom:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:didFinishLoadingFromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:didFinishLoadingFrom:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:didfinishloadingfrom:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-22bdg": {
      "abstract": [
        {
          "text": "Invoked after a resource has been loaded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didReceive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-22bdg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:didReceiveResponse:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:didReceive:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:didreceive:from:)-22bdg"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-54xbd": {
      "abstract": [
        {
          "text": "Invoked when an authentication challenge has been received for a resource.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didReceive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLAuthenticationChallenge",
          "text": "URLAuthenticationChallenge"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-54xbd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:didReceiveAuthenticationChallenge:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:didReceive:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:didreceive:from:)-54xbd"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceiveContentLength:from:)": {
      "abstract": [
        {
          "text": "Invoked when some of the data for a given resource has arrived.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveContentLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceiveContentLength:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:didReceiveContentLength:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:didReceiveContentLength:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:didreceivecontentlength:from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:willSend:redirectResponse:from:)": {
      "abstract": [
        {
          "text": "Invoked before a request is initiated for a resource and returns a possibly modified request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "willSend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "redirectResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebDataSource",
          "text": "WebDataSource"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:willSend:redirectResponse:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:resource:willSendRequest:redirectResponse:fromDataSource:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:resource:willSend:redirectResponse:from:)",
      "type": "topic",
      "url": "/documentation/webkit/webresourceloaddelegate/webview(_:resource:willsend:redirectresponse:from:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-Resources-Legacy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebResource"
      ],
      "title": "Loading Resources (Legacy)"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-Identifiers",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:identifierForInitialRequest:from:)"
      ],
      "title": "Setting Identifiers"
    },
    {
      "anchor": "Loading-Content",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:willSend:redirectResponse:from:)",
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFinishLoadingFrom:)",
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-22bdg",
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceiveContentLength:from:)",
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFailLoadingWithError:from:)",
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:plugInFailedWithError:dataSource:)"
      ],
      "title": "Loading Content"
    },
    {
      "anchor": "Authenticating-Resources",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-54xbd",
        "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didCancel:from:)"
      ],
      "title": "Authenticating Resources"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WebResourceLoadDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebResourceLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebResourceLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-Identifiers",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:identifierForInitialRequest:from:)"
              ],
              "title": "Setting Identifiers"
            },
            {
              "anchor": "Loading-Content",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:willSend:redirectResponse:from:)",
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFinishLoadingFrom:)",
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-22bdg",
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceiveContentLength:from:)",
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didFailLoadingWithError:from:)",
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:plugInFailedWithError:dataSource:)"
              ],
              "title": "Loading Content"
            },
            {
              "anchor": "Authenticating-Resources",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didReceive:from:)-54xbd",
                "doc://com.apple.webkit/documentation/WebKit/WebResourceLoadDelegate/webView(_:resource:didCancel:from:)"
              ],
              "title": "Authenticating Resources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-Resources-Legacy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebResource"
              ],
              "title": "Loading Resources (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WebResourceLoadDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didFailLoadingWithError:from:)/title",
          "value": "webView:resource:didFailLoadingWithError:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didFailLoadingWithError:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:didFailLoadingWithError:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didCancel:from:)/title",
          "value": "webView:resource:didCancelAuthenticationChallenge:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didCancel:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:didCancelAuthenticationChallenge:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:willSend:redirectResponse:from:)/title",
          "value": "webView:resource:willSendRequest:redirectResponse:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:willSend:redirectResponse:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:willSendRequest:redirectResponse:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:plugInFailedWithError:dataSource:)/title",
          "value": "webView:plugInFailedWithError:dataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:plugInFailedWithError:dataSource:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:plugInFailedWithError:dataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didReceive:from:)-22bdg/title",
          "value": "webView:resource:didReceiveResponse:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didReceive:from:)-22bdg/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:didReceiveResponse:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:identifierForInitialRequest:from:)/title",
          "value": "webView:identifierForInitialRequest:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:identifierForInitialRequest:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:identifierForInitialRequest:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didReceive:from:)-54xbd/title",
          "value": "webView:resource:didReceiveAuthenticationChallenge:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didReceive:from:)-54xbd/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:didReceiveAuthenticationChallenge:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didReceiveContentLength:from:)/title",
          "value": "webView:resource:didReceiveContentLength:fromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didReceiveContentLength:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:didReceiveContentLength:fromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didFinishLoadingFrom:)/title",
          "value": "webView:resource:didFinishLoadingFromDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate~1webView(_:resource:didFinishLoadingFrom:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:resource:didFinishLoadingFromDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate/title",
          "value": "WebResourceLoadDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebResourceLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResourceLoadDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebResourceLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResource/title",
          "value": "WebResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebResource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webresourceloaddelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webresourceloaddelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
