{
  "abstract": [
    {
      "text": "The data detector types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKDataDetectorTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKDataDetectorTypes"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKDataDetectorTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "WKDataDetectorTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To perform no data detection, create an empty set of data detector types, indicated by the empty array literal, ",
              "type": "text"
            },
            {
              "code": "[]",
              "type": "codeVoice"
            },
            {
              "text": ". For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let myDataDetector: WKDataDetectorTypes = []"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes": {
      "abstract": [
        {
          "text": "The data detector types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "WKDataDetectorTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/WKDataDetectorTypeNone": {
      "abstract": [
        {
          "text": "No data detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeNone"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/WKDataDetectorTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKDataDetectorTypeNone",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/wkdatadetectortypenone"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address": {
      "abstract": [
        {
          "text": "Detect addresses in text and turn them into links to display the location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeAddress"
        }
      ],
      "role": "symbol",
      "title": "address",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/address"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all": {
      "abstract": [
        {
          "text": "Detect all data types and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/all"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent": {
      "abstract": [
        {
          "text": "Turn future dates and times into links to create calendar events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "calendarEvent",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/calendarevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber": {
      "abstract": [
        {
          "text": "Detect flight numbers in text and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flightNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeFlightNumber"
        }
      ],
      "role": "symbol",
      "title": "flightNumber",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/flightnumber"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/init(rawvalue:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link": {
      "abstract": [
        {
          "text": "Detect URLs in text and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeLink"
        }
      ],
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/link"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion": {
      "abstract": [
        {
          "text": "Detect Spotlight suggestions and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookupSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeLookupSuggestion"
        }
      ],
      "role": "symbol",
      "title": "lookupSuggestion",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/lookupsuggestion"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber": {
      "abstract": [
        {
          "text": "Detect phone numbers in text and create a link to call the specified number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypePhoneNumber"
        }
      ],
      "role": "symbol",
      "title": "phoneNumber",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/phonenumber"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/spotlightSuggestion": {
      "abstract": [
        {
          "text": "Spotlight suggestions are detected and turned into links.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spotlightSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/spotlightSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeSpotlightSuggestion"
        }
      ],
      "role": "symbol",
      "title": "spotlightSuggestion",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/spotlightsuggestion"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber": {
      "abstract": [
        {
          "text": "Detect tracking numbers in text and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeTrackingNumber"
        }
      ],
      "role": "symbol",
      "title": "trackingNumber",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/trackingnumber"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes": {
      "abstract": [
        {
          "text": "The types of data detectors to apply to the web view’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataDetectorTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "dataDetectorTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/datadetectortypes"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes"
      ],
      "title": "Identifying data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Detector-Types",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all"
      ],
      "title": "Data Detector Types"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Deprecated-Types",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/spotlightSuggestion"
      ],
      "title": "Deprecated Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKDataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Detector-Types",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/WKDataDetectorTypeNone",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all"
              ],
              "title": "Data Detector Types"
            },
            {
              "anchor": "Deprecated-Types",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/spotlightSuggestion"
              ],
              "title": "Deprecated Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes"
              ],
              "title": "Identifying data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKDataDetectorTypes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1all/title",
          "value": "WKDataDetectorTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1flightNumber/title",
          "value": "WKDataDetectorTypeFlightNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1flightNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeFlightNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1link/title",
          "value": "WKDataDetectorTypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1phoneNumber/title",
          "value": "WKDataDetectorTypePhoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1phoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypePhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1spotlightSuggestion/title",
          "value": "WKDataDetectorTypeSpotlightSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1spotlightSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeSpotlightSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1calendarEvent/title",
          "value": "WKDataDetectorTypeCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1calendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1trackingNumber/title",
          "value": "WKDataDetectorTypeTrackingNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1trackingNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeTrackingNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1address/title",
          "value": "WKDataDetectorTypeAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/title",
          "value": "WKDataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1lookupSuggestion/title",
          "value": "WKDataDetectorTypeLookupSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1lookupSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeLookupSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1dataDetectorTypes/title",
          "value": "dataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1dataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataDetectorTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkdatadetectortypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkdatadetectortypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
