{
  "abstract": [
    {
      "text": "Possible error values that WebKit APIs can return.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11WKErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKError"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "WKError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError": {
      "abstract": [
        {
          "text": "Possible error values that WebKit APIs can return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKError"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKError"
        }
      ],
      "role": "symbol",
      "title": "WKError",
      "type": "topic",
      "url": "/documentation/webkit/wkerror"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code": {
      "abstract": [
        {
          "text": "Possible error values that WebKit APIs can return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/attributedStringContentFailedToLoad": {
      "abstract": [
        {
          "text": "An error that indicates the failure to navigate to web content from an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedStringContentFailedToLoad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/attributedStringContentFailedToLoad",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedStringContentFailedToLoad",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/attributedstringcontentfailedtoload"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/attributedStringContentLoadTimedOut": {
      "abstract": [
        {
          "text": "An error that indicates a timeout occurred while trying to load web content from an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedStringContentLoadTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/attributedStringContentLoadTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedStringContentLoadTimedOut",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/attributedstringcontentloadtimedout"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreCompileFailed": {
      "abstract": [
        {
          "text": "An error that indicates the compilation of a rule list failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreCompileFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreCompileFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentRuleListStoreCompileFailed",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/contentruleliststorecompilefailed"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreLookUpFailed": {
      "abstract": [
        {
          "text": "An error that indicates a content rule list data store didn’t find a rule list with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreLookUpFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreLookUpFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentRuleListStoreLookUpFailed",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/contentruleliststorelookupfailed"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreRemoveFailed": {
      "abstract": [
        {
          "text": "An error that indicates a failure to remove a content rule list from the rule list data store object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreRemoveFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreRemoveFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentRuleListStoreRemoveFailed",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/contentruleliststoreremovefailed"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreVersionMismatch": {
      "abstract": [
        {
          "text": "An error that indicates the rule list version is outdated and cannot be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreVersionMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreVersionMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentRuleListStoreVersionMismatch",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/contentruleliststoreversionmismatch"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/credentialNotFound": {
      "abstract": [
        {
          "text": "An error that indicates the system could not find a passkey during an export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/credentialNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "credentialNotFound",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/credentialnotfound"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/duplicateCredential": {
      "abstract": [
        {
          "text": "An error that indicates the system found a duplicate passkey during an import.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/duplicateCredential",
      "kind": "symbol",
      "role": "symbol",
      "title": "duplicateCredential",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/duplicatecredential"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/errordomain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptAppBoundDomain": {
      "abstract": [
        {
          "text": "An error that indicates JavaScript execution failed due to an app-bound domain restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptAppBoundDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptAppBoundDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "javaScriptAppBoundDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/javascriptappbounddomain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptExceptionOccurred": {
      "abstract": [
        {
          "text": "An error that indicates a JavaScript exception occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptExceptionOccurred"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptExceptionOccurred",
      "kind": "symbol",
      "role": "symbol",
      "title": "javaScriptExceptionOccurred",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/javascriptexceptionoccurred"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptInvalidFrameTarget": {
      "abstract": [
        {
          "text": "An error that indicates your content referenced an invalid web frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptInvalidFrameTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptInvalidFrameTarget",
      "kind": "symbol",
      "role": "symbol",
      "title": "javaScriptInvalidFrameTarget",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/javascriptinvalidframetarget"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptResultTypeIsUnsupported": {
      "abstract": [
        {
          "text": "An error that indicates the result of JavaScript execution could not be returned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptResultTypeIsUnsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptResultTypeIsUnsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "javaScriptResultTypeIsUnsupported",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/javascriptresulttypeisunsupported"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/malformedCredential": {
      "abstract": [
        {
          "text": "An error that indicates the system could not parse passkey data during an import.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malformedCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/malformedCredential",
      "kind": "symbol",
      "role": "symbol",
      "title": "malformedCredential",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/malformedcredential"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/navigationAppBoundDomain": {
      "abstract": [
        {
          "text": "An error that indicates navigation failed due to an app-bound domain restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationAppBoundDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/navigationAppBoundDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "navigationAppBoundDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/navigationappbounddomain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/unknown": {
      "abstract": [
        {
          "text": "An error that indicates an unknown issue occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/unknown"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/webContentProcessTerminated": {
      "abstract": [
        {
          "text": "An error that indicates the web process that contains the content is no longer running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webContentProcessTerminated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/webContentProcessTerminated",
      "kind": "symbol",
      "role": "symbol",
      "title": "webContentProcessTerminated",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/webcontentprocessterminated"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/webViewInvalidated": {
      "abstract": [
        {
          "text": "An error that indicates the web view was invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webViewInvalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WKErrorCodeLeV",
          "text": "WKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/webViewInvalidated",
      "kind": "symbol",
      "role": "symbol",
      "title": "webViewInvalidated",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/webviewinvalidated"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Error-Codes",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKError/unknown",
        "doc://com.apple.webkit/documentation/WebKit/WKError/webContentProcessTerminated",
        "doc://com.apple.webkit/documentation/WebKit/WKError/webViewInvalidated",
        "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptExceptionOccurred",
        "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptResultTypeIsUnsupported",
        "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreCompileFailed",
        "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreLookUpFailed",
        "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreRemoveFailed",
        "doc://com.apple.webkit/documentation/WebKit/WKError/contentRuleListStoreVersionMismatch",
        "doc://com.apple.webkit/documentation/WebKit/WKError/attributedStringContentFailedToLoad",
        "doc://com.apple.webkit/documentation/WebKit/WKError/attributedStringContentLoadTimedOut",
        "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptInvalidFrameTarget",
        "doc://com.apple.webkit/documentation/WebKit/WKError/navigationAppBoundDomain",
        "doc://com.apple.webkit/documentation/WebKit/WKError/javaScriptAppBoundDomain",
        "doc://com.apple.webkit/documentation/WebKit/WKError/credentialNotFound",
        "doc://com.apple.webkit/documentation/WebKit/WKError/duplicateCredential",
        "doc://com.apple.webkit/documentation/WebKit/WKError/malformedCredential"
      ],
      "title": "Getting the Error Codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code/title",
          "value": "WKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
