{
  "abstract": [
    {
      "text": "An enumeration that describes whether an audio or video presentation is playing, paused, or suspended.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKMediaPlaybackState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKMediaPlaybackState"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKMediaPlaybackState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKMediaPlaybackState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState": {
      "abstract": [
        {
          "text": "An enumeration that describes whether an audio or video presentation is playing, paused, or suspended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackState"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/init(rawvalue:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none": {
      "abstract": [
        {
          "text": "There is no media to play back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStateNone"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.none",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/none"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused": {
      "abstract": [
        {
          "text": "The media playback is paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStatePaused"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.paused",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/paused"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing": {
      "abstract": [
        {
          "text": "The media is playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playing"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStatePlaying"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.playing",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/playing"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended": {
      "abstract": [
        {
          "text": "The media is not playing, and cannot be resumed until the user revokes the suspension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStateSuspended"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.suspended",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/suspended"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)": {
      "abstract": [
        {
          "text": "Closes all media the web view is presenting, including picture-in-picture video and fullscreen video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeAllMediaPresentations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "closeAllMediaPresentationsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "closeAllMediaPresentations(completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/closeallmediapresentations(completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)": {
      "abstract": [
        {
          "text": "Pauses playback of all media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlayback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlaybackWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "pauseAllMediaPlayback(completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/pauseallmediaplayback(completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback:": {
      "abstract": [
        {
          "text": "Pauses playback of all media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlayback:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlayback:"
        }
      ],
      "role": "symbol",
      "title": "pauseAllMediaPlayback:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/pauseallmediaplayback:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)": {
      "abstract": [
        {
          "text": "Requests the playback status of media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKMediaPlaybackState",
          "text": "WKMediaPlaybackState"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackStateWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestMediaPlaybackState(completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/requestmediaplaybackstate(completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState:": {
      "abstract": [
        {
          "text": "Requests the playback status of media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackState:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackState:"
        }
      ],
      "role": "symbol",
      "title": "requestMediaPlaybackState:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/requestmediaplaybackstate:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/resumeAllMediaPlayback:": {
      "abstract": [
        {
          "text": "Resumes playback of all media in a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resumeAllMediaPlayback:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/resumeAllMediaPlayback:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeAllMediaPlayback:"
        }
      ],
      "role": "symbol",
      "title": "resumeAllMediaPlayback:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/resumeallmediaplayback:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Changes whether the webpage is suspending playback of all media in the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAllMediaPlaybackSuspended"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAllMediaPlaybackSuspended:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "setAllMediaPlaybackSuspended(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/setallmediaplaybacksuspended(_:completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/suspendAllMediaPlayback:": {
      "abstract": [
        {
          "text": "Changes whether the webpage is suspending playback of all media in the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "suspendAllMediaPlayback:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/suspendAllMediaPlayback:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suspendAllMediaPlayback:"
        }
      ],
      "role": "symbol",
      "title": "suspendAllMediaPlayback:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/suspendallmediaplayback:"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interacting-with-media",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)"
      ],
      "title": "Interacting with media"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKMediaPlaybackState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none",
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused",
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing",
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interacting-with-media",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback:",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState:",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/suspendAllMediaPlayback:",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/resumeAllMediaPlayback:",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)"
              ],
              "title": "Interacting with media"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKMediaPlaybackState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1requestMediaPlaybackState(completionHandler:)/title",
          "value": "requestMediaPlaybackStateWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1requestMediaPlaybackState(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestMediaPlaybackStateWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/title",
          "value": "WKMediaPlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1paused/title",
          "value": "WKMediaPlaybackStatePaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1paused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStatePaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1playing/title",
          "value": "WKMediaPlaybackStatePlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1playing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStatePlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1setAllMediaPlaybackSuspended(_:completionHandler:)/title",
          "value": "setAllMediaPlaybackSuspended:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1setAllMediaPlaybackSuspended(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAllMediaPlaybackSuspended:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1suspended/title",
          "value": "WKMediaPlaybackStateSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1suspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStateSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1pauseAllMediaPlayback(completionHandler:)/title",
          "value": "pauseAllMediaPlaybackWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1pauseAllMediaPlayback(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseAllMediaPlaybackWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1none/title",
          "value": "WKMediaPlaybackStateNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStateNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1closeAllMediaPresentations(completionHandler:)/title",
          "value": "closeAllMediaPresentationsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1closeAllMediaPresentations(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "closeAllMediaPresentationsWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkmediaplaybackstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkmediaplaybackstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
