{
  "abstract": [
    {
      "text": "An object for managing interactions between JavaScript code and your web view, and for filtering content in your web view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKUserContentController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKUserContentController"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKUserContentController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKUserContentController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object provides a bridge between your app and the JavaScript code running in the web view. Use this object to do the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Inject JavaScript code into webpages running in your web view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Install custom JavaScript functions that call through to your app’s native code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify custom filters to prevent the webpage from loading restricted content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Create and configure a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object as part of your overall web view setup. Assign the object to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object before creating your web view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKContentRuleList": {
      "abstract": [
        {
          "text": "A compiled list of rules to apply to web content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKContentRuleList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKContentRuleList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKContentRuleList"
        }
      ],
      "role": "symbol",
      "title": "WKContentRuleList",
      "type": "topic",
      "url": "/documentation/webkit/wkcontentrulelist"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKContentRuleListStore": {
      "abstract": [
        {
          "text": "An object that contains the rules for how to load and filter content in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKContentRuleListStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKContentRuleListStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKContentRuleListStore"
        }
      ],
      "role": "symbol",
      "title": "WKContentRuleListStore",
      "type": "topic",
      "url": "/documentation/webkit/wkcontentruleliststore"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKContentWorld": {
      "abstract": [
        {
          "text": "An object that defines a scope of execution for JavaScript code, and which you use to prevent conflicts between different scripts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKContentWorld"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKContentWorld",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKContentWorld"
        }
      ],
      "role": "symbol",
      "title": "WKContentWorld",
      "type": "topic",
      "url": "/documentation/webkit/wkcontentworld"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo": {
      "abstract": [
        {
          "text": "An object that contains information about a frame on a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKFrameInfo"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKFrameInfo"
        }
      ],
      "role": "symbol",
      "title": "WKFrameInfo",
      "type": "topic",
      "url": "/documentation/webkit/wkframeinfo"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler": {
      "abstract": [
        {
          "text": "An interface for receiving messages from JavaScript code running in a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandler"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandler"
        }
      ],
      "role": "symbol",
      "title": "WKScriptMessageHandler",
      "type": "topic",
      "url": "/documentation/webkit/wkscriptmessagehandler"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply": {
      "abstract": [
        {
          "text": "An interface for responding to messages from JavaScript code running in a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandlerWithReply"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandlerWithReply"
        }
      ],
      "role": "symbol",
      "title": "WKScriptMessageHandlerWithReply",
      "type": "topic",
      "url": "/documentation/webkit/wkscriptmessagehandlerwithreply"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKSecurityOrigin": {
      "abstract": [
        {
          "text": "An object that identifies the origin of a particular resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKSecurityOrigin"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKSecurityOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSecurityOrigin"
        }
      ],
      "role": "symbol",
      "title": "WKSecurityOrigin",
      "type": "topic",
      "url": "/documentation/webkit/wksecurityorigin"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController": {
      "abstract": [
        {
          "text": "An object for managing interactions between JavaScript code and your web view, and for filtering content in your web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserContentController"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKUserContentController"
        }
      ],
      "role": "symbol",
      "title": "WKUserContentController",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:)": {
      "abstract": [
        {
          "text": "Adds the specified content rule list to the content controller object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentRuleList",
          "text": "WKContentRuleList"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addContentRuleList:"
        }
      ],
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/add(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)": {
      "abstract": [
        {
          "text": "Installs a message handler that you can call from the specified content world in your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKScriptMessageHandler",
          "text": "WKScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentWorld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addScriptMessageHandler:contentWorld:name:"
        }
      ],
      "role": "symbol",
      "title": "add(_:contentWorld:name:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/add(_:contentworld:name:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)": {
      "abstract": [
        {
          "text": "Installs a message handler that you can call from your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKScriptMessageHandler",
          "text": "WKScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addScriptMessageHandler:name:"
        }
      ],
      "role": "symbol",
      "title": "add(_:name:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/add(_:name:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)": {
      "abstract": [
        {
          "text": "Installs a message handler that returns a reply to your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKScriptMessageHandlerWithReply",
          "text": "WKScriptMessageHandlerWithReply"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentWorld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addScriptMessageHandlerWithReply:contentWorld:name:"
        }
      ],
      "role": "symbol",
      "title": "addScriptMessageHandler(_:contentWorld:name:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/addscriptmessagehandler(_:contentworld:name:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addUserScript(_:)": {
      "abstract": [
        {
          "text": "Injects the specified script into the webpage’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addUserScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKUserScript",
          "text": "WKUserScript"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addUserScript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addUserScript:"
        }
      ],
      "role": "symbol",
      "title": "addUserScript(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/adduserscript(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/remove(_:)": {
      "abstract": [
        {
          "text": "Removes the specified rule list from the content controller object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentRuleList",
          "text": "WKContentRuleList"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/remove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeContentRuleList:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/remove(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllContentRuleLists()": {
      "abstract": [
        {
          "text": "Removes all rules lists from the content controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllContentRuleLists"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllContentRuleLists()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllContentRuleLists"
        }
      ],
      "role": "symbol",
      "title": "removeAllContentRuleLists()",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removeallcontentrulelists()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()": {
      "abstract": [
        {
          "text": "Uninstalls all custom message handlers associated with the user content controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlers"
        }
      ],
      "role": "symbol",
      "title": "removeAllScriptMessageHandlers()",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removeallscriptmessagehandlers()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)": {
      "abstract": [
        {
          "text": "Uninstalls all custom message handlers from the specified content world in your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlersFromContentWorld:"
        }
      ],
      "role": "symbol",
      "title": "removeAllScriptMessageHandlers(from:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removeallscriptmessagehandlers(from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllUserScripts()": {
      "abstract": [
        {
          "text": "Removes all user scripts from the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllUserScripts"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllUserScripts()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllUserScripts"
        }
      ],
      "role": "symbol",
      "title": "removeAllUserScripts()",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removealluserscripts()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)": {
      "abstract": [
        {
          "text": "Uninstalls the custom message handler with the specified name from your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandlerForName:"
        }
      ],
      "role": "symbol",
      "title": "removeScriptMessageHandler(forName:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removescriptmessagehandler(forname:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)": {
      "abstract": [
        {
          "text": "Uninstalls a custom message handler from the specified content world in your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentWorld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandlerForName:contentWorld:"
        }
      ],
      "role": "symbol",
      "title": "removeScriptMessageHandler(forName:contentWorld:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removescriptmessagehandler(forname:contentworld:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/userScripts": {
      "abstract": [
        {
          "text": "The user scripts associated with the user content controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userScripts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKUserScript",
          "text": "WKUserScript"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/userScripts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userScripts"
        }
      ],
      "role": "symbol",
      "title": "userScripts",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/userscripts"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserScript": {
      "abstract": [
        {
          "text": "A script that the web view injects into a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserScript"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKUserScript"
        }
      ],
      "role": "symbol",
      "title": "WKUserScript",
      "type": "topic",
      "url": "/documentation/webkit/wkuserscript"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration": {
      "abstract": [
        {
          "text": "A collection of properties that you use to initialize a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "WKWebViewConfiguration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController": {
      "abstract": [
        {
          "text": "The object that coordinates interactions between your app’s native code and the webpage’s scripts and other content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userContentController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKUserContentController",
          "text": "WKUserContentController"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userContentController"
        }
      ],
      "role": "symbol",
      "title": "userContentController",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/usercontentcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Page-Content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKContentRuleListStore",
        "doc://com.apple.webkit/documentation/WebKit/WKContentWorld",
        "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo",
        "doc://com.apple.webkit/documentation/WebKit/WKSecurityOrigin",
        "doc://com.apple.webkit/documentation/WebKit/WKUserScript"
      ],
      "title": "Page Content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adding-and-Removing-Custom-Scripts",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addUserScript(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllUserScripts()",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/userScripts"
      ],
      "title": "Adding and Removing Custom Scripts"
    },
    {
      "anchor": "Adding-and-Removing-Message-Handlers",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()",
        "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler",
        "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply"
      ],
      "title": "Adding and Removing Message Handlers"
    },
    {
      "anchor": "Adding-and-Removing-Content-Rules",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/remove(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllContentRuleLists()",
        "doc://com.apple.webkit/documentation/WebKit/WKContentRuleList"
      ],
      "title": "Adding and Removing Content Rules"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKUserContentController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adding-and-Removing-Custom-Scripts",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addUserScript(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllUserScripts()",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/userScripts"
              ],
              "title": "Adding and Removing Custom Scripts"
            },
            {
              "anchor": "Adding-and-Removing-Message-Handlers",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()",
                "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler",
                "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply"
              ],
              "title": "Adding and Removing Message Handlers"
            },
            {
              "anchor": "Adding-and-Removing-Content-Rules",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/remove(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllContentRuleLists()",
                "doc://com.apple.webkit/documentation/WebKit/WKContentRuleList"
              ],
              "title": "Adding and Removing Content Rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Page-Content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKContentRuleListStore",
                "doc://com.apple.webkit/documentation/WebKit/WKContentWorld",
                "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo",
                "doc://com.apple.webkit/documentation/WebKit/WKSecurityOrigin",
                "doc://com.apple.webkit/documentation/WebKit/WKUserScript"
              ],
              "title": "Page Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKUserContentController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController/title",
          "value": "WKUserContentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers(from:)/title",
          "value": "removeAllScriptMessageHandlersFromContentWorld:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllScriptMessageHandlersFromContentWorld:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllContentRuleLists()/title",
          "value": "removeAllContentRuleLists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllContentRuleLists()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllContentRuleLists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1userScripts/title",
          "value": "userScripts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1userScripts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userScripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandlerWithReply/title",
          "value": "WKScriptMessageHandlerWithReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandlerWithReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandlerWithReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandlerWithReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandlerWithReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentRuleList/title",
          "value": "WKContentRuleList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentRuleList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentRuleList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentRuleList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:)/title",
          "value": "removeScriptMessageHandlerForName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeScriptMessageHandlerForName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers()/title",
          "value": "removeAllScriptMessageHandlers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllScriptMessageHandlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/title",
          "value": "WKWebViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1addScriptMessageHandler(_:contentWorld:name:)/title",
          "value": "addScriptMessageHandlerWithReply:contentWorld:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1addScriptMessageHandler(_:contentWorld:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandlerWithReply:contentWorld:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentWorld/title",
          "value": "WKContentWorld"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentWorld/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentWorld/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:contentWorld:name:)/title",
          "value": "addScriptMessageHandler:contentWorld:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:contentWorld:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandler:contentWorld:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandler/title",
          "value": "WKScriptMessageHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1remove(_:)/title",
          "value": "removeContentRuleList:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1remove(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeContentRuleList:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:name:)/title",
          "value": "addScriptMessageHandler:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandler:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userContentController/title",
          "value": "userContentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userContentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentRuleListStore/title",
          "value": "WKContentRuleListStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentRuleListStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentRuleListStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentRuleListStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentRuleListStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:contentWorld:)/title",
          "value": "removeScriptMessageHandlerForName:contentWorld:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:contentWorld:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeScriptMessageHandlerForName:contentWorld:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllUserScripts()/title",
          "value": "removeAllUserScripts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllUserScripts()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllUserScripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKFrameInfo/title",
          "value": "WKFrameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKFrameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFrameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKFrameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFrameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:)/title",
          "value": "addContentRuleList:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addContentRuleList:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1addUserScript(_:)/title",
          "value": "addUserScript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1addUserScript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addUserScript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserScript/title",
          "value": "WKUserScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserScript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKSecurityOrigin/title",
          "value": "WKSecurityOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKSecurityOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSecurityOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKSecurityOrigin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSecurityOrigin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkusercontentcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkusercontentcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
