{
  "abstract": [
    {
      "text": "A collection of properties that you use to initialize a web view.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKWebViewConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKWebViewConfiguration"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKWebViewConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKWebViewConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object provides information about how to configure a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Use your configuration object to specify:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The initial cookies to make available to your web content",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Handlers for any custom URL schemes your web content uses",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Settings for how to handle media content",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Information about how to manage selections within the web view",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Custom scripts to inject into the webpage",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Custom rules that determine how to render content",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object in your code, configure its properties, and pass it to the initializer of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The web view incorporates your configuration settings only at creation time; you cannot change those settings dynamically later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes": {
      "abstract": [
        {
          "text": "The media types that require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "role": "symbol",
      "title": "WKAudiovisualMediaTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkaudiovisualmediatypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes": {
      "abstract": [
        {
          "text": "The data detector types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "WKDataDetectorTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences": {
      "abstract": [
        {
          "text": "An object that encapsulates the standard behaviors to apply to websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKPreferences"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPreferences"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKProcessPool": {
      "abstract": [
        {
          "text": "An opaque token that you use to run multiple web views in a single process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKProcessPool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKProcessPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKProcessPool"
        }
      ],
      "role": "symbol",
      "title": "WKProcessPool",
      "type": "topic",
      "url": "/documentation/webkit/wkprocesspool"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKSelectionGranularity": {
      "abstract": [
        {
          "text": "The granularity with which the user can select and modify web view content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKSelectionGranularity"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKSelectionGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSelectionGranularity"
        }
      ],
      "role": "symbol",
      "title": "WKSelectionGranularity",
      "type": "topic",
      "url": "/documentation/webkit/wkselectiongranularity"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy": {
      "abstract": [
        {
          "text": "The policy that determines the directionality of user interface elements in a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserInterfaceDirectionPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKUserInterfaceDirectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "WKUserInterfaceDirectionPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkuserinterfacedirectionpolicy"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration": {
      "abstract": [
        {
          "text": "A collection of properties that you use to initialize a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "WKWebViewConfiguration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsAirPlayForMediaPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the web view allows media playback over AirPlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsAirPlayForMediaPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsAirPlayForMediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsAirPlayForMediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "allowsAirPlayForMediaPlayback",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/allowsairplayformediaplayback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlineMediaPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether HTML5 videos play inline or use the native full-screen controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsInlineMediaPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlineMediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsInlineMediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "allowsInlineMediaPlayback",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/allowsinlinemediaplayback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlinePredictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsInlinePredictions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlinePredictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsInlinePredictions"
        }
      ],
      "role": "symbol",
      "title": "allowsInlinePredictions",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/allowsinlinepredictions"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsPictureInPictureMediaPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether HTML5 videos can play Picture in Picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsPictureInPictureMediaPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsPictureInPictureMediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsPictureInPictureMediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "allowsPictureInPictureMediaPlayback",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/allowspictureinpicturemediaplayback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/applicationNameForUserAgent": {
      "abstract": [
        {
          "text": "The app name that appears in the user agent string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationNameForUserAgent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/applicationNameForUserAgent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationNameForUserAgent"
        }
      ],
      "role": "symbol",
      "title": "applicationNameForUserAgent",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/applicationnameforuseragent"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes": {
      "abstract": [
        {
          "text": "The types of data detectors to apply to the web view’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataDetectorTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "dataDetectorTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/datadetectortypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/defaultWebpagePreferences": {
      "abstract": [
        {
          "text": "The default preferences to use when loading and rendering content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultWebpagePreferences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebpagePreferences",
          "text": "WKWebpagePreferences"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/defaultWebpagePreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultWebpagePreferences"
        }
      ],
      "role": "symbol",
      "title": "defaultWebpagePreferences",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/defaultwebpagepreferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/ignoresViewportScaleLimits": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether a web view allows scaling of the webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoresViewportScaleLimits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/ignoresViewportScaleLimits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoresViewportScaleLimits"
        }
      ],
      "role": "symbol",
      "title": "ignoresViewportScaleLimits",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/ignoresviewportscalelimits"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/limitsNavigationsToAppBoundDomains": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the web view limits navigation to pages within the app’s domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitsNavigationsToAppBoundDomains"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/limitsNavigationsToAppBoundDomains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "limitsNavigationsToAppBoundDomains"
        }
      ],
      "role": "symbol",
      "title": "limitsNavigationsToAppBoundDomains",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/limitsnavigationstoappbounddomains"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackAllowsAirPlay": {
      "abstract": [
        {
          "text": "Deprecated property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlaybackAllowsAirPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackAllowsAirPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPlaybackAllowsAirPlay"
        }
      ],
      "role": "symbol",
      "title": "mediaPlaybackAllowsAirPlay",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/mediaplaybackallowsairplay"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackRequiresUserAction": {
      "abstract": [
        {
          "text": "Deprecated property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlaybackRequiresUserAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackRequiresUserAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPlaybackRequiresUserAction"
        }
      ],
      "role": "symbol",
      "title": "mediaPlaybackRequiresUserAction",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/mediaplaybackrequiresuseraction"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaTypesRequiringUserActionForPlayback": {
      "abstract": [
        {
          "text": "The media types that require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaTypesRequiringUserActionForPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKAudiovisualMediaTypes",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaTypesRequiringUserActionForPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaTypesRequiringUserActionForPlayback"
        }
      ],
      "role": "symbol",
      "title": "mediaTypesRequiringUserActionForPlayback",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/mediatypesrequiringuseractionforplayback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/preferences": {
      "abstract": [
        {
          "text": "The object that manages the preference-related settings for the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKPreferences",
          "text": "WKPreferences"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/preferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferences"
        }
      ],
      "role": "symbol",
      "title": "preferences",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/preferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/processPool": {
      "abstract": [
        {
          "text": "The object that coordinates the processes the web view uses to render its web content and execute scripts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processPool"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKProcessPool",
          "text": "WKProcessPool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/processPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processPool"
        }
      ],
      "role": "symbol",
      "title": "processPool",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/processpool"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/requiresUserActionForMediaPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether HTML5 videos require the user to start playing them (",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ") or whether the videos play automatically (",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresUserActionForMediaPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/requiresUserActionForMediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresUserActionForMediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "requiresUserActionForMediaPlayback",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/requiresuseractionformediaplayback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/selectionGranularity": {
      "abstract": [
        {
          "text": "The level of granularity with which the user can interactively select web view content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionGranularity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKSelectionGranularity",
          "text": "WKSelectionGranularity"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/selectionGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionGranularity"
        }
      ],
      "role": "symbol",
      "title": "selectionGranularity",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/selectiongranularity"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/setURLSchemeHandler(_:forURLScheme:)": {
      "abstract": [
        {
          "text": "Registers an object to load resources associated with the specified URL scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setURLSchemeHandler"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKURLSchemeHandler",
          "text": "WKURLSchemeHandler"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "forURLScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/setURLSchemeHandler(_:forURLScheme:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setURLSchemeHandler:forURLScheme:"
        }
      ],
      "role": "symbol",
      "title": "setURLSchemeHandler(_:forURLScheme:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/seturlschemehandler(_:forurlscheme:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/supportsAdaptiveImageGlyph": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsAdaptiveImageGlyph"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/supportsAdaptiveImageGlyph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsAdaptiveImageGlyph"
        }
      ],
      "role": "symbol",
      "title": "supportsAdaptiveImageGlyph",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/supportsadaptiveimageglyph"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/suppressesIncrementalRendering": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the web view suppresses content rendering until the content is fully loaded into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suppressesIncrementalRendering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/suppressesIncrementalRendering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suppressesIncrementalRendering"
        }
      ],
      "role": "symbol",
      "title": "suppressesIncrementalRendering",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/suppressesincrementalrendering"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/upgradeKnownHostsToHTTPS": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the web view should automatically upgrade supported HTTP requests to HTTPS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upgradeKnownHostsToHTTPS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/upgradeKnownHostsToHTTPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "upgradeKnownHostsToHTTPS"
        }
      ],
      "role": "symbol",
      "title": "upgradeKnownHostsToHTTPS",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/upgradeknownhoststohttps"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/urlSchemeHandler(forURLScheme:)": {
      "abstract": [
        {
          "text": "Returns the currently registered handler object for the specified URL scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlSchemeHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forURLScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKURLSchemeHandler",
          "text": "WKURLSchemeHandler"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/urlSchemeHandler(forURLScheme:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "urlSchemeHandlerForURLScheme:"
        }
      ],
      "role": "symbol",
      "title": "urlSchemeHandler(forURLScheme:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/urlschemehandler(forurlscheme:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController": {
      "abstract": [
        {
          "text": "The object that coordinates interactions between your app’s native code and the webpage’s scripts and other content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userContentController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKUserContentController",
          "text": "WKUserContentController"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userContentController"
        }
      ],
      "role": "symbol",
      "title": "userContentController",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/usercontentcontroller"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy": {
      "abstract": [
        {
          "text": "The directionality of user interface elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceDirectionPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKUserInterfaceDirectionPolicy",
          "text": "WKUserInterfaceDirectionPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceDirectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceDirectionPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/userinterfacedirectionpolicy"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/webExtensionController": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webExtensionController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtensionController",
          "text": "WKWebExtensionController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/webExtensionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webExtensionController"
        }
      ],
      "role": "symbol",
      "title": "webExtensionController",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/webextensioncontroller"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore": {
      "abstract": [
        {
          "text": "The object you use to get and set the site’s cookies and to track the cached data objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "websiteDataStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebsiteDataStore",
          "text": "WKWebsiteDataStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "websiteDataStore"
        }
      ],
      "role": "symbol",
      "title": "websiteDataStore",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/websitedatastore"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/writingToolsBehavior": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writingToolsBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIWritingToolsBehavior",
          "text": "UIWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/writingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "writingToolsBehavior",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/writingtoolsbehavior"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebpagePreferences": {
      "abstract": [
        {
          "text": "An object that specifies the behaviors to use when loading and rendering page content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebpagePreferences"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebpagePreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebpagePreferences"
        }
      ],
      "role": "symbol",
      "title": "WKWebpagePreferences",
      "type": "topic",
      "url": "/documentation/webkit/wkwebpagepreferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWindowFeatures": {
      "abstract": [
        {
          "text": "Display-related attributes that a webpage requests for its window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWindowFeatures"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWindowFeatures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWindowFeatures"
        }
      ],
      "role": "symbol",
      "title": "WKWindowFeatures",
      "type": "topic",
      "url": "/documentation/webkit/wkwindowfeatures"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Web-View-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWindowFeatures",
        "doc://com.apple.webkit/documentation/WebKit/WKProcessPool",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences",
        "doc://com.apple.webkit/documentation/WebKit/WKWebpagePreferences"
      ],
      "title": "Web View Configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-web-views-behavior",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/processPool",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/applicationNameForUserAgent",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/limitsNavigationsToAppBoundDomains",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/upgradeKnownHostsToHTTPS"
      ],
      "title": "Configuring the web view’s behavior"
    },
    {
      "anchor": "Configuring-the-web-views-preferences",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/preferences",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/defaultWebpagePreferences"
      ],
      "title": "Configuring the web view’s preferences"
    },
    {
      "anchor": "Adding-handlers-for-custom-URL-schemes",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/setURLSchemeHandler(_:forURLScheme:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/urlSchemeHandler(forURLScheme:)"
      ],
      "title": "Adding handlers for custom URL schemes"
    },
    {
      "anchor": "Configuring-the-rendering-behavior",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/ignoresViewportScaleLimits",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/suppressesIncrementalRendering"
      ],
      "title": "Configuring the rendering behavior"
    },
    {
      "anchor": "Setting-media-playback-preferences",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlineMediaPlayback",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsAirPlayForMediaPlayback",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsPictureInPictureMediaPlayback",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaTypesRequiringUserActionForPlayback",
        "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes"
      ],
      "title": "Setting media playback preferences"
    },
    {
      "anchor": "Identifying-data-types",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes"
      ],
      "title": "Identifying data types"
    },
    {
      "anchor": "Setting-selection-granularity",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/selectionGranularity",
        "doc://com.apple.webkit/documentation/WebKit/WKSelectionGranularity"
      ],
      "title": "Setting selection granularity"
    },
    {
      "anchor": "Selecting-user-interface-directionality",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy",
        "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy"
      ],
      "title": "Selecting user interface directionality"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackAllowsAirPlay",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/requiresUserActionForMediaPlayback",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackRequiresUserAction"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlinePredictions",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/supportsAdaptiveImageGlyph",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/webExtensionController",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/writingToolsBehavior"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWebViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-web-views-behavior",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userContentController",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/processPool",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/applicationNameForUserAgent",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/limitsNavigationsToAppBoundDomains",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/upgradeKnownHostsToHTTPS"
              ],
              "title": "Configuring the web view’s behavior"
            },
            {
              "anchor": "Configuring-the-web-views-preferences",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/preferences",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/defaultWebpagePreferences"
              ],
              "title": "Configuring the web view’s preferences"
            },
            {
              "anchor": "Adding-handlers-for-custom-URL-schemes",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/setURLSchemeHandler(_:forURLScheme:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/urlSchemeHandler(forURLScheme:)"
              ],
              "title": "Adding handlers for custom URL schemes"
            },
            {
              "anchor": "Configuring-the-rendering-behavior",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/ignoresViewportScaleLimits",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/suppressesIncrementalRendering"
              ],
              "title": "Configuring the rendering behavior"
            },
            {
              "anchor": "Setting-media-playback-preferences",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlineMediaPlayback",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsAirPlayForMediaPlayback",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsPictureInPictureMediaPlayback",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaTypesRequiringUserActionForPlayback",
                "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes"
              ],
              "title": "Setting media playback preferences"
            },
            {
              "anchor": "Identifying-data-types",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/dataDetectorTypes",
                "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes"
              ],
              "title": "Identifying data types"
            },
            {
              "anchor": "Setting-selection-granularity",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/selectionGranularity",
                "doc://com.apple.webkit/documentation/WebKit/WKSelectionGranularity"
              ],
              "title": "Setting selection granularity"
            },
            {
              "anchor": "Selecting-user-interface-directionality",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy",
                "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy"
              ],
              "title": "Selecting user interface directionality"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackAllowsAirPlay",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/requiresUserActionForMediaPlayback",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/mediaPlaybackRequiresUserAction"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/allowsInlinePredictions",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/supportsAdaptiveImageGlyph",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/webExtensionController",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/writingToolsBehavior"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Web-View-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWindowFeatures",
                "doc://com.apple.webkit/documentation/WebKit/WKProcessPool",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences",
                "doc://com.apple.webkit/documentation/WebKit/WKWebpagePreferences"
              ],
              "title": "Web View Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKWebViewConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userInterfaceDirectionPolicy/title",
          "value": "userInterfaceDirectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userInterfaceDirectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceDirectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/title",
          "value": "WKPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userContentController/title",
          "value": "userContentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userContentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1selectionGranularity/title",
          "value": "selectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1selectionGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKProcessPool/title",
          "value": "WKProcessPool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKProcessPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKProcessPool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKProcessPool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKProcessPool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWindowFeatures/title",
          "value": "WKWindowFeatures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWindowFeatures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWindowFeatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWindowFeatures/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWindowFeatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1mediaPlaybackAllowsAirPlay/title",
          "value": "mediaPlaybackAllowsAirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1mediaPlaybackAllowsAirPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaPlaybackAllowsAirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebpagePreferences/title",
          "value": "WKWebpagePreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebpagePreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebpagePreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebpagePreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebpagePreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsInlineMediaPlayback/title",
          "value": "allowsInlineMediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsInlineMediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsInlineMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1applicationNameForUserAgent/title",
          "value": "applicationNameForUserAgent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1applicationNameForUserAgent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationNameForUserAgent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1mediaPlaybackRequiresUserAction/title",
          "value": "mediaPlaybackRequiresUserAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1mediaPlaybackRequiresUserAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaPlaybackRequiresUserAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1preferences/title",
          "value": "preferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1preferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1processPool/title",
          "value": "processPool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1processPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "processPool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1limitsNavigationsToAppBoundDomains/title",
          "value": "limitsNavigationsToAppBoundDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1limitsNavigationsToAppBoundDomains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "limitsNavigationsToAppBoundDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/title",
          "value": "WKWebViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/title",
          "value": "WKDataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1setURLSchemeHandler(_:forURLScheme:)/title",
          "value": "setURLSchemeHandler:forURLScheme:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1setURLSchemeHandler(_:forURLScheme:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setURLSchemeHandler:forURLScheme:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1requiresUserActionForMediaPlayback/title",
          "value": "requiresUserActionForMediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1requiresUserActionForMediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresUserActionForMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1urlSchemeHandler(forURLScheme:)/title",
          "value": "urlSchemeHandlerForURLScheme:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1urlSchemeHandler(forURLScheme:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "urlSchemeHandlerForURLScheme:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsInlinePredictions/title",
          "value": "allowsInlinePredictions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsInlinePredictions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsInlinePredictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1supportsAdaptiveImageGlyph/title",
          "value": "supportsAdaptiveImageGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1supportsAdaptiveImageGlyph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsAdaptiveImageGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1defaultWebpagePreferences/title",
          "value": "defaultWebpagePreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1defaultWebpagePreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultWebpagePreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy/title",
          "value": "WKUserInterfaceDirectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserInterfaceDirectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserInterfaceDirectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/title",
          "value": "WKWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1upgradeKnownHostsToHTTPS/title",
          "value": "upgradeKnownHostsToHTTPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1upgradeKnownHostsToHTTPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "upgradeKnownHostsToHTTPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKSelectionGranularity/title",
          "value": "WKSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKSelectionGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKSelectionGranularity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1writingToolsBehavior/title",
          "value": "writingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1writingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "writingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1dataDetectorTypes/title",
          "value": "dataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1dataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1mediaTypesRequiringUserActionForPlayback/title",
          "value": "mediaTypesRequiringUserActionForPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1mediaTypesRequiringUserActionForPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaTypesRequiringUserActionForPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsPictureInPictureMediaPlayback/title",
          "value": "allowsPictureInPictureMediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsPictureInPictureMediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsPictureInPictureMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1webExtensionController/title",
          "value": "webExtensionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1webExtensionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "webExtensionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1websiteDataStore/title",
          "value": "websiteDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1websiteDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "websiteDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsAirPlayForMediaPlayback/title",
          "value": "allowsAirPlayForMediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1allowsAirPlayForMediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsAirPlayForMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1ignoresViewportScaleLimits/title",
          "value": "ignoresViewportScaleLimits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1ignoresViewportScaleLimits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoresViewportScaleLimits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes/title",
          "value": "WKAudiovisualMediaTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1suppressesIncrementalRendering/title",
          "value": "suppressesIncrementalRendering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1suppressesIncrementalRendering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "suppressesIncrementalRendering"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebviewconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebviewconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
