{
  "abstract": [
    {
      "text": "An object that manages cookies, disk and memory caches, and other types of data for a web view.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKWebsiteDataStore",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKWebsiteDataStore"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKWebsiteDataStore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKWebsiteDataStore"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKWebsiteDataStore"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to configure and manage web site data. Specifically, use this object to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Manage cookies that your web site uses",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Learn about the types of data that websites store",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Remove unwanted web site data",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Create a data store object and assign it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object before you create your web view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By default, ",
              "type": "text"
            },
            {
              "code": "WKWebViewConfiguration",
              "type": "codeVoice"
            },
            {
              "text": " uses the default data store returned by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/default()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which saves website data persistently to disk.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To implement private browsing, create a nonpersistent data store using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/nonPersistent()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To implement profile browsing, create a persistent data store using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/init(forIdentifier:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, passing an identifier that you use to identify the data store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/documentreadingoptionkey/3182829-readaccessurl": {
      "abstract": [
        {
          "text": "The local files WebKit can access when loading content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "readAccessURL"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.DocumentReadingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/documentreadingoptionkey/3182829-readaccessurl",
      "kind": "symbol",
      "role": "symbol",
      "title": "readAccessURL",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/documentreadingoptionkey/3182829-readaccessurl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/NSReadAccessURLDocumentOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSReadAccessURLDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/NSReadAccessURLDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSReadAccessURLDocumentOption",
      "type": "topic",
      "url": "/documentation/webkit/nsreadaccessurldocumentoption"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKHTTPCookieStore": {
      "abstract": [
        {
          "text": "An object that manages the HTTP cookies associated with a particular web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKHTTPCookieStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKHTTPCookieStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHTTPCookieStore"
        }
      ],
      "role": "symbol",
      "title": "WKHTTPCookieStore",
      "type": "topic",
      "url": "/documentation/webkit/wkhttpcookiestore"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeHandler": {
      "abstract": [
        {
          "text": "A protocol for loading resources with URL schemes that WebKit doesn’t handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKURLSchemeHandler"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKURLSchemeHandler"
        }
      ],
      "role": "symbol",
      "title": "WKURLSchemeHandler",
      "type": "topic",
      "url": "/documentation/webkit/wkurlschemehandler"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeTask": {
      "abstract": [
        {
          "text": "An interface that WebKit uses to request custom resources from your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKURLSchemeTask"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKURLSchemeTask"
        }
      ],
      "role": "symbol",
      "title": "WKURLSchemeTask",
      "type": "topic",
      "url": "/documentation/webkit/wkurlschemetask"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration": {
      "abstract": [
        {
          "text": "A collection of properties that you use to initialize a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "WKWebViewConfiguration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore": {
      "abstract": [
        {
          "text": "The object you use to get and set the site’s cookies and to track the cached data objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "websiteDataStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebsiteDataStore",
          "text": "WKWebsiteDataStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/websiteDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "websiteDataStore"
        }
      ],
      "role": "symbol",
      "title": "websiteDataStore",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/websitedatastore"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord": {
      "abstract": [
        {
          "text": "A record of the data that a particular website stores persistently.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataRecord"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataRecord"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataRecord",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatarecord"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore": {
      "abstract": [
        {
          "text": "An object that manages cookies, disk and memory caches, and other types of data for a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebsiteDataStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebsiteDataStore"
        }
      ],
      "role": "symbol",
      "title": "WKWebsiteDataStore",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/allWebsiteDataTypes()": {
      "abstract": [
        {
          "text": "Returns the set of all the available data types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allWebsiteDataTypes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/allWebsiteDataTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allWebsiteDataTypes"
        }
      ],
      "role": "symbol",
      "title": "allWebsiteDataTypes()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/allwebsitedatatypes()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/default()": {
      "abstract": [
        {
          "text": "Returns the default data store, which stores data persistently to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebsiteDataStore",
          "text": "WKWebsiteDataStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultDataStore"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/default()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchAllDataStoreIdentifiers(_:)": {
      "abstract": [
        {
          "text": "Fetches an array of identifiers from existing data stores that have identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAllDataStoreIdentifiers"
        },
        {
          "kind": "text",
          "text": "((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchAllDataStoreIdentifiers(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAllDataStoreIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "fetchAllDataStoreIdentifiers(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/fetchalldatastoreidentifiers(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchDataRecords(ofTypes:completionHandler:)": {
      "abstract": [
        {
          "text": "Fetches the specified types of records from the data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchDataRecords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebsiteDataRecord",
          "text": "WKWebsiteDataRecord"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchDataRecords(ofTypes:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchDataRecordsOfTypes:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "fetchDataRecords(ofTypes:completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/fetchdatarecords(oftypes:completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/httpCookieStore": {
      "abstract": [
        {
          "text": "The object that manages the HTTP cookies for your website.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "httpCookieStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKHTTPCookieStore",
          "text": "WKHTTPCookieStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/httpCookieStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "httpCookieStore"
        }
      ],
      "role": "symbol",
      "title": "httpCookieStore",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/httpcookiestore"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/identifier": {
      "abstract": [
        {
          "text": "An identifier that uniquely identifies a data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/identifier"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/init(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the persistent data store with the unique identifier you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/init(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataStoreForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/init(foridentifier:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/isPersistent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether this object stores data to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPersistent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/isPersistent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistent"
        }
      ],
      "role": "symbol",
      "title": "isPersistent",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/ispersistent"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/nonPersistent()": {
      "abstract": [
        {
          "text": "Creates a new data store object that stores website data in memory, and doesn’t write that data to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonPersistent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebsiteDataStore",
          "text": "WKWebsiteDataStore"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/nonPersistent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nonPersistentDataStore"
        }
      ],
      "role": "symbol",
      "title": "nonPersistent()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/nonpersistent()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/proxyConfigurations-6g21z": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "proxyConfigurations"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/proxyConfigurations-6g21z",
      "kind": "symbol",
      "role": "symbol",
      "title": "proxyConfigurations",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/proxyconfigurations-6g21z"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/proxyConfigurations-cdc1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proxyConfigurations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Network18ProxyConfigurationV",
          "text": "ProxyConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/proxyConfigurations-cdc1",
      "kind": "symbol",
      "role": "symbol",
      "title": "proxyConfigurations",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/proxyconfigurations-cdc1"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/remove(forIdentifier:completionHandler:)": {
      "abstract": [
        {
          "text": "Removes the data store that matches the identifier you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/remove(forIdentifier:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeDataStoreForIdentifier:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "remove(forIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/remove(foridentifier:completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:for:completionHandler:)": {
      "abstract": [
        {
          "text": "Removes the specified types of website data from one or more data records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebsiteDataRecord",
          "text": "WKWebsiteDataRecord"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeDataOfTypes:forDataRecords:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "removeData(ofTypes:for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/removedata(oftypes:for:completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:modifiedSince:completionHandler:)": {
      "abstract": [
        {
          "text": "Removes website data that changed after the specified date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "modifiedSince"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:modifiedSince:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeDataOfTypes:modifiedSince:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "removeData(ofTypes:modifiedSince:completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebsitedatastore/removedata(oftypes:modifiedsince:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Web-Data-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord",
        "doc://com.apple.webkit/documentation/WebKit/WKHTTPCookieStore",
        "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeHandler",
        "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeTask",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/documentreadingoptionkey/3182829-readaccessurl"
      ],
      "title": "Web Data Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-data-store-object",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/default()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/nonPersistent()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/init(forIdentifier:)"
      ],
      "title": "Creating a data store object"
    },
    {
      "anchor": "Finding-data-stores",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchAllDataStoreIdentifiers(_:)"
      ],
      "title": "Finding data stores"
    },
    {
      "anchor": "Inspecting-data-store-properties",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/identifier",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/isPersistent"
      ],
      "title": "Inspecting data store properties"
    },
    {
      "anchor": "Retrieving-a-cookie-store",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/httpCookieStore"
      ],
      "title": "Retrieving a cookie store"
    },
    {
      "anchor": "Retrieving-specific-types-of-data",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchDataRecords(ofTypes:completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/allWebsiteDataTypes()"
      ],
      "title": "Retrieving specific types of data"
    },
    {
      "anchor": "Removing-specific-types-of-data",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:for:completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:modifiedSince:completionHandler:)"
      ],
      "title": "Removing specific types of data"
    },
    {
      "anchor": "Removing-a-data-store",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/remove(forIdentifier:completionHandler:)"
      ],
      "title": "Removing a data store"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/proxyConfigurations-cdc1"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWebsiteDataStore"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-data-store-object",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/default()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/nonPersistent()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/init(forIdentifier:)"
              ],
              "title": "Creating a data store object"
            },
            {
              "anchor": "Finding-data-stores",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchAllDataStoreIdentifiers(_:)"
              ],
              "title": "Finding data stores"
            },
            {
              "anchor": "Inspecting-data-store-properties",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/identifier",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/isPersistent"
              ],
              "title": "Inspecting data store properties"
            },
            {
              "anchor": "Retrieving-a-cookie-store",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/httpCookieStore"
              ],
              "title": "Retrieving a cookie store"
            },
            {
              "anchor": "Retrieving-specific-types-of-data",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/fetchDataRecords(ofTypes:completionHandler:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/allWebsiteDataTypes()"
              ],
              "title": "Retrieving specific types of data"
            },
            {
              "anchor": "Removing-specific-types-of-data",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:for:completionHandler:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/removeData(ofTypes:modifiedSince:completionHandler:)"
              ],
              "title": "Removing specific types of data"
            },
            {
              "anchor": "Removing-a-data-store",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/remove(forIdentifier:completionHandler:)"
              ],
              "title": "Removing a data store"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataStore/proxyConfigurations-6g21z"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Web-Data-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebsiteDataRecord",
                "doc://com.apple.webkit/documentation/WebKit/WKHTTPCookieStore",
                "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeHandler",
                "doc://com.apple.webkit/documentation/WebKit/WKURLSchemeTask",
                "doc://com.apple.webkit/documentation/WebKit/NSReadAccessURLDocumentOption"
              ],
              "title": "Web Data Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKWebsiteDataStore"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1fetchAllDataStoreIdentifiers(_:)/title",
          "value": "fetchAllDataStoreIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1fetchAllDataStoreIdentifiers(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchAllDataStoreIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1fetchDataRecords(ofTypes:completionHandler:)/title",
          "value": "fetchDataRecordsOfTypes:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1fetchDataRecords(ofTypes:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fetchDataRecordsOfTypes:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1removeData(ofTypes:modifiedSince:completionHandler:)/title",
          "value": "removeDataOfTypes:modifiedSince:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1removeData(ofTypes:modifiedSince:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeDataOfTypes:modifiedSince:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKURLSchemeHandler/title",
          "value": "WKURLSchemeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKURLSchemeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKURLSchemeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKURLSchemeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKURLSchemeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKURLSchemeTask/title",
          "value": "WKURLSchemeTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKURLSchemeTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKURLSchemeTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKURLSchemeTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKURLSchemeTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1default()/title",
          "value": "defaultDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1allWebsiteDataTypes()/title",
          "value": "allWebsiteDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1allWebsiteDataTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allWebsiteDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1isPersistent/title",
          "value": "persistent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1isPersistent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/title",
          "value": "WKWebViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1websiteDataStore/title",
          "value": "websiteDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1websiteDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "websiteDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKHTTPCookieStore/title",
          "value": "WKHTTPCookieStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKHTTPCookieStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHTTPCookieStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKHTTPCookieStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHTTPCookieStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1nonPersistent()/title",
          "value": "nonPersistentDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1nonPersistent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "nonPersistentDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord/title",
          "value": "WKWebsiteDataRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore/title",
          "value": "WKWebsiteDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebsiteDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1removeData(ofTypes:for:completionHandler:)/title",
          "value": "removeDataOfTypes:forDataRecords:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1removeData(ofTypes:for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeDataOfTypes:forDataRecords:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1init(forIdentifier:)/title",
          "value": "dataStoreForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1init(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dataStoreForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1httpCookieStore/title",
          "value": "httpCookieStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1httpCookieStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "httpCookieStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1remove(forIdentifier:completionHandler:)/title",
          "value": "removeDataStoreForIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebsiteDataStore~1remove(forIdentifier:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "removeDataStoreForIdentifier:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebsitedatastore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebsitedatastore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
