{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/wkwebview-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/certificateChain": {
      "abstract": [
        {
          "text": "An array of objects forming the certificate chain for the currently committed navigation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certificateChain"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/certificateChain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "certificateChain"
        }
      ],
      "role": "symbol",
      "title": "certificateChain",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/certificatechain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeAllMediaPresentations"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "closeAllMediaPresentations"
        }
      ],
      "role": "symbol",
      "title": "closeAllMediaPresentations()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/closeallmediapresentations()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:with:responseData:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadSimulatedRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "responseData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigation",
          "text": "WKNavigation"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:with:responseData:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadSimulatedRequest:withResponse:responseData:"
        }
      ],
      "role": "symbol",
      "title": "loadSimulatedRequest(_:with:responseData:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/loadsimulatedrequest(_:with:responsedata:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:withResponseHTML:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadSimulatedRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withResponseHTML"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigation",
          "text": "WKNavigation"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:withResponseHTML:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadSimulatedRequest:withResponseHTMLString:"
        }
      ],
      "role": "symbol",
      "title": "loadSimulatedRequest(_:withResponseHTML:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/loadsimulatedrequest(_:withresponsehtml:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/certificateChain",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:with:responseData:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:withResponseHTML:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/certificateChain",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:with:responseData:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/loadSimulatedRequest(_:withResponseHTML:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1closeAllMediaPresentations()/title",
          "value": "closeAllMediaPresentations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1closeAllMediaPresentations()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "closeAllMediaPresentations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1certificateChain/title",
          "value": "certificateChain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1certificateChain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "certificateChain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1loadSimulatedRequest(_:withResponseHTML:)/title",
          "value": "loadSimulatedRequest:withResponseHTMLString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1loadSimulatedRequest(_:withResponseHTML:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadSimulatedRequest:withResponseHTMLString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1loadSimulatedRequest(_:with:responseData:)/title",
          "value": "loadSimulatedRequest:withResponse:responseData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1loadSimulatedRequest(_:with:responseData:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadSimulatedRequest:withResponse:responseData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/title",
          "value": "WKWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebview-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebview-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
