{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/working-with-document-web-views-legacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Working With Document Web Views (Legacy)"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentRepresentation": {
      "abstract": [
        {
          "text": "This protocol is adopted by document representation classes that handle specific MIME types. You can implement your own document view classes and document representation classes to render data for specific MIME types, and register those classes using the ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentRepresentation"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentRepresentation"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentRepresentation",
      "type": "topic",
      "url": "/documentation/webkit/webdocumentrepresentation"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentSearching": {
      "abstract": [
        {
          "code": "WebDocumentSearching",
          "type": "codeVoice"
        },
        {
          "text": " is an optional protocol for document view objects that support searching. Classes that adopt this protocol should also adopt ",
          "type": "text"
        },
        {
          "code": "WebDocumentView",
          "type": "codeVoice"
        },
        {
          "text": " and inherit from ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentSearching"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentSearching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentSearching"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentSearching",
      "type": "topic",
      "url": "/documentation/webkit/webdocumentsearching"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentText": {
      "abstract": [
        {
          "code": "WebDocumentText",
          "type": "codeVoice"
        },
        {
          "text": " is an optional protocol for document view objects that display text. This protocol defines methods for accessing document content as strings, and methods for text selection. Classes that adopt this protocol should also adopt ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and inherit from ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentText"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentText"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentText",
      "type": "topic",
      "url": "/documentation/webkit/webdocumenttext"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentView": {
      "abstract": [
        {
          "text": "This protocol is adopted by the document view of a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": ". You can extend WebKit to support additional MIME types by implementing your own document view and document representation classes to render data for specific MIME types. You register those classes using the WebFrame ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. Classes that adopt this protocol are expected to be subclasses of ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentView"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentView",
      "type": "topic",
      "url": "/documentation/webkit/webdocumentview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)": {
      "abstract": [
        {
          "text": "Specifies the view and representation objects to be used for specific MIME types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerClass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "representationClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forMIMEType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerViewClass:representationClass:forMIMEType:"
        }
      ],
      "role": "symbol",
      "title": "registerClass(_:representationClass:forMIMEType:)",
      "type": "topic",
      "url": "/documentation/webkit/webview/registerclass(_:representationclass:formimetype:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessing Previous Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/accessing-previous-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Archiving Webpages (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/archiving-webpages-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/webkit/deprecated-symbols"
    },
    "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Object Models API (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/document-object-models-api-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Downloading Information (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/downloading-information-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Implementing Plugins (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/implementing-plugins-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Incorporating Scripts (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/incorporating-scripts-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Loading Resources (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/loading-resources-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Opening a File (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/opening-a-file-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Policies (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-policies-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting Up a Web View (Legacy)",
      "type": "topic",
      "url": "/documentation/webkit/setting-up-a-web-view-legacy"
    },
    "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy": {
      "abstract": [],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Working with Frames (legacy)",
      "type": "topic",
      "url": "/documentation/webkit/working-with-frames-legacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WebKit-Legacy-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
        "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
        "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
        "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
        "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
        "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
        "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
        "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
        "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy"
      ],
      "title": "WebKit Legacy APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Working-With-Document-Web-Views-Legacy",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentRepresentation",
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentSearching",
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentText",
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentView"
      ],
      "title": "Working With Document Web Views (Legacy)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Working-With-Document-Web-Views-Legacy",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentRepresentation",
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentSearching",
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentText",
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentView"
              ],
              "title": "Working With Document Web Views (Legacy)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WebKit-Legacy-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/document-object-models-api-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-up-a-web-view-legacy",
                "doc://com.apple.webkit/documentation/WebKit/accessing-previous-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/archiving-webpages-legacy",
                "doc://com.apple.webkit/documentation/WebKit/loading-resources-legacy",
                "doc://com.apple.webkit/documentation/WebKit/working-with-frames-legacy",
                "doc://com.apple.webkit/documentation/WebKit/downloading-information-legacy",
                "doc://com.apple.webkit/documentation/WebKit/opening-a-file-legacy",
                "doc://com.apple.webkit/documentation/WebKit/setting-policies-legacy",
                "doc://com.apple.webkit/documentation/WebKit/implementing-plugins-legacy",
                "doc://com.apple.webkit/documentation/WebKit/incorporating-scripts-legacy"
              ],
              "title": "WebKit Legacy APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentRepresentation/title",
          "value": "WebDocumentRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentRepresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentRepresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText/title",
          "value": "WebDocumentText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/title",
          "value": "WebDocumentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1registerClass(_:representationClass:forMIMEType:)/title",
          "value": "registerViewClass:representationClass:forMIMEType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1registerClass(_:representationClass:forMIMEType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "registerViewClass:representationClass:forMIMEType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentSearching/title",
          "value": "WebDocumentSearching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentSearching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentSearching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentSearching/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentSearching"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/working-with-document-web-views-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/working-with-document-web-views-legacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
