{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferAttachment-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOSampleBuffer attachment constants"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlockBufferAttachmentKey_CVPixelBufferReference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOBlockBufferAttachmentKey_CVPixelBufferReference"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlockBufferAttachmentKey_CVPixelBufferReference",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOBlockBufferAttachmentKey_CVPixelBufferReference",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioblockbufferattachmentkey_cvpixelbufferreference"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_CAAudioTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_CAAudioTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_CAAudioTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_CAAudioTimeStamp",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_caaudiotimestamp"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_ClientSequenceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_ClientSequenceID"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_ClientSequenceID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_ClientSequenceID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_clientsequenceid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_ClosedCaptionSampleBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_ClosedCaptionSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_ClosedCaptionSampleBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_ClosedCaptionSampleBuffer",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_closedcaptionsamplebuffer"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_DiscontinuityFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_DiscontinuityFlags"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_DiscontinuityFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_DiscontinuityFlags",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_discontinuityflags"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HDV1_PackData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_HDV1_PackData"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HDV1_PackData",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_HDV1_PackData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_hdv1_packdata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HDV2_VAUX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_HDV2_VAUX"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HDV2_VAUX",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_HDV2_VAUX",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_hdv2_vaux"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HostTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_HostTime"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HostTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_HostTime",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_hosttime"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_MouseAndKeyboardModifiers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_MouseAndKeyboardModifiers"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_MouseAndKeyboardModifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_MouseAndKeyboardModifiers",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_mouseandkeyboardmodifiers"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_MuxedSourcePresentationTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_MuxedSourcePresentationTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_MuxedSourcePresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_MuxedSourcePresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_muxedsourcepresentationtimestamp"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NativeSMPTEFrameCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_NativeSMPTEFrameCount"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NativeSMPTEFrameCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_NativeSMPTEFrameCount",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_nativesmpteframecount"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NoDataMarker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_NoDataMarker"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NoDataMarker",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_NoDataMarker",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_nodatamarker"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInBuffer",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_numberofvideoframesinbuffer"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInGOP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInGOP"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInGOP",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInGOP",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_numberofvideoframesingop"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_PixelBufferOverlaidByStaticImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_PixelBufferOverlaidByStaticImage"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_PixelBufferOverlaidByStaticImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_PixelBufferOverlaidByStaticImage",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_pixelbufferoverlaidbystaticimage"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_PulldownCadenceInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_PulldownCadenceInfo"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_PulldownCadenceInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_PulldownCadenceInfo",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_pulldowncadenceinfo"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_RepeatedBufferContents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_RepeatedBufferContents"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_RepeatedBufferContents",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_RepeatedBufferContents",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_repeatedbuffercontents"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SMPTETime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_SMPTETime"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SMPTETime",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_SMPTETime",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_smptetime"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_SequenceNumber"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SequenceNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_SequenceNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_sequencenumber"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SourceAudioFormatDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachmentKey_SourceAudioFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SourceAudioFormatDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachmentKey_SourceAudioFormatDescription",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachmentkey_sourceaudioformatdescription"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorFrameRect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorFrameRect"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorFrameRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorFrameRect",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorframerect"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsDrawnInFramebuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsDrawnInFramebuffer"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsDrawnInFramebuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsDrawnInFramebuffer",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorisdrawninframebuffer"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsVisible": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsVisible"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsVisible",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsVisible",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorisvisible"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionX"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionX",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionX",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorpositionx"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionY"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionY",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionY",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorpositiony"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorReference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorReference"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorReference",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorReference",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorreference"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorScale"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorScale",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorscale"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorSeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorSeed"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorSeed",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorSeed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_cursorseed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiers"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiers",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_keyboardmodifiers"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiersEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiersEvent"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiersEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiersEvent",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_keyboardmodifiersevent"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_MouseButtonState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_MouseButtonState"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_MouseButtonState",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_MouseButtonState",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferattachment_mouseandkeyboardmodifierskey_mousebuttonstate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlockBufferAttachmentKey_CVPixelBufferReference",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorFrameRect",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsDrawnInFramebuffer",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorIsVisible",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionX",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorPositionY",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorReference",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorScale",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_CursorSeed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiers",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_KeyboardModifiersEvent",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachment_MouseAndKeyboardModifiersKey_MouseButtonState",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_CAAudioTimeStamp",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_ClientSequenceID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_ClosedCaptionSampleBuffer",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_DiscontinuityFlags",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HDV1_PackData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HDV2_VAUX",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_HostTime",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_MouseAndKeyboardModifiers",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_MuxedSourcePresentationTimeStamp",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NativeSMPTEFrameCount",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NoDataMarker",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInBuffer",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_NumberOfVideoFramesInGOP",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_PixelBufferOverlaidByStaticImage",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_PulldownCadenceInfo",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_RepeatedBufferContents",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SequenceNumber",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SMPTETime",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferAttachmentKey_SourceAudioFormatDescription"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
              ],
              "title": "Constants"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiosamplebufferattachment-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiosamplebufferattachment-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
