{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOExposureControl properties"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyConvergenceSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyConvergenceSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyConvergenceSpeed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyconvergencespeed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyIntegrationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyIntegrationTime"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyIntegrationTime",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyintegrationtime"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyLockThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyLockThreshold"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyLockThreshold",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertylockthreshold"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyMaximumGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyMaximumGain"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyMaximumGain",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertymaximumgain"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyRegionOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyRegionOfInterest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyregionofinterest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStability"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyStability",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertystability"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStable"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyStable",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertystable"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyTarget"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyTarget",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertytarget"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyUnlockThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyUnlockThreshold"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyUnlockThreshold",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyunlockthreshold"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyMaximumGain/title",
          "value": "kCMIOExposureControlPropertyMaximumGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyMaximumGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyMaximumGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyRegionOfInterest/title",
          "value": "kCMIOExposureControlPropertyRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyRegionOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyIntegrationTime/title",
          "value": "kCMIOExposureControlPropertyIntegrationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyIntegrationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyIntegrationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStable/title",
          "value": "kCMIOExposureControlPropertyStable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyStable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyUnlockThreshold/title",
          "value": "kCMIOExposureControlPropertyUnlockThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyUnlockThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyUnlockThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyTarget/title",
          "value": "kCMIOExposureControlPropertyTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyConvergenceSpeed/title",
          "value": "kCMIOExposureControlPropertyConvergenceSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyConvergenceSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyConvergenceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStability/title",
          "value": "kCMIOExposureControlPropertyStability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyStability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyLockThreshold/title",
          "value": "kCMIOExposureControlPropertyLockThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyLockThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyLockThreshold"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioexposurecontrol-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioexposurecontrol-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
