{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIODeckShuttle speed constants"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePause"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePause"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePause",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlepause"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlay1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlay1x"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlay1x",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplay1x"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFast"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayFast",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayfast"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayFaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayfaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFastest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFastest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayFastest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayfastest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayHighSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayHighSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayHighSpeed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayhighspeed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayNextFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayNextFrame"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayNextFrame",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplaynextframe"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayPreviousFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayPreviousFrame"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayPreviousFrame",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplaypreviousframe"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow1"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlow1",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslow1"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow2"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlow2",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslow2"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow3"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlow3",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslow3"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlowest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlowest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlowest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslowest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverse1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverse1x"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverse1x",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereverse1x"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFast"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseFast",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversefast"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseFaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversefaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFastest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFastest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseFastest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversefastest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseHighSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseHighSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseHighSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseHighSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseHighSpeed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversehighspeed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlow1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlow1"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseSlow1",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereverseslow1"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlow2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlow2"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseSlow2",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereverseslow2"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlow3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlow3"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseSlow3",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereverseslow3"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlowest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlowest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlowest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseSlowest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseSlowest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereverseslowest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseHighSpeed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow1",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow2",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow3",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlowest"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseHighSpeed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow1",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow2",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlow3",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseSlowest"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFastest/title",
          "value": "kCMIODeckShuttleReverseFastest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFastest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseFastest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlowest/title",
          "value": "kCMIODeckShuttlePlaySlowest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlowest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlowest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFaster/title",
          "value": "kCMIODeckShuttlePlayFaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayFaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow1/title",
          "value": "kCMIODeckShuttlePlaySlow1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlow1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFast/title",
          "value": "kCMIODeckShuttleReverseFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFast/title",
          "value": "kCMIODeckShuttlePlayFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayHighSpeed/title",
          "value": "kCMIODeckShuttlePlayHighSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayHighSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayHighSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow2/title",
          "value": "kCMIODeckShuttlePlaySlow2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlow2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFaster/title",
          "value": "kCMIODeckShuttleReverseFaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseFaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlow2/title",
          "value": "kCMIODeckShuttleReverseSlow2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlow2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseSlow2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlowest/title",
          "value": "kCMIODeckShuttleReverseSlowest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlowest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseSlowest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverse1x/title",
          "value": "kCMIODeckShuttleReverse1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverse1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverse1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow3/title",
          "value": "kCMIODeckShuttlePlaySlow3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlow3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseHighSpeed/title",
          "value": "kCMIODeckShuttleReverseHighSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseHighSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseHighSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlow1/title",
          "value": "kCMIODeckShuttleReverseSlow1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlow1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseSlow1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayPreviousFrame/title",
          "value": "kCMIODeckShuttlePlayPreviousFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayPreviousFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayPreviousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayNextFrame/title",
          "value": "kCMIODeckShuttlePlayNextFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayNextFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayNextFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlay1x/title",
          "value": "kCMIODeckShuttlePlay1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlay1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlay1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePause/title",
          "value": "kCMIODeckShuttlePause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlow3/title",
          "value": "kCMIODeckShuttleReverseSlow3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseSlow3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseSlow3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFastest/title",
          "value": "kCMIODeckShuttlePlayFastest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFastest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayFastest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
