{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CMIODeviceRS422Command",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMIODeviceRS422Command"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIODeviceRS422Command"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CMIODeviceRS422Command"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceAVCCommand"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceAVCCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavccommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceRS422Command"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceRS422Command"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceRS422Command",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/init()"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/init(mCommand:mCommandLength:mResponse:mResponseLength:mResponseUsed:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "mCommandLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "mResponseLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mResponseUsed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/init(mCommand:mCommandLength:mResponse:mResponseLength:mResponseUsed:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mCommand:mCommandLength:mResponse:mResponseLength:mResponseUsed:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/init(mcommand:mcommandlength:mresponse:mresponselength:mresponseused:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCommand"
        }
      ],
      "role": "symbol",
      "title": "mCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/mcommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommandLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCommandLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommandLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCommandLength"
        }
      ],
      "role": "symbol",
      "title": "mCommandLength",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/mcommandlength"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mResponse"
        }
      ],
      "role": "symbol",
      "title": "mResponse",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/mresponse"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mResponseLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mResponseLength"
        }
      ],
      "role": "symbol",
      "title": "mResponseLength",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/mresponselength"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseUsed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mResponseUsed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseUsed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mResponseUsed"
        }
      ],
      "role": "symbol",
      "title": "mResponseUsed",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command/mresponseused"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceSMPTETimeCallback",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicesmptetimecallback"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStreamConfiguration",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestreamconfiguration"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOHardwarePlugInInterface"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOHardwarePlugInInterface",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectpropertyaddress"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeck"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeck"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeck",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeck"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamscheduledoutputnotificationprocandrefcon"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/init()",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/init(mCommand:mCommandLength:mResponse:mResponseLength:mResponseUsed:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommandLength",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponse",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseLength",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseUsed"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMIODeviceRS422Command"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mCommandLength",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponse",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseLength",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command/mResponseUsed"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMIODeviceRS422Command"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/title",
          "value": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/title",
          "value": "CMIODeviceAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/title",
          "value": "CMIOObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mResponse/title",
          "value": "mResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mResponseLength/title",
          "value": "mResponseLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mResponseLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mResponseLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/title",
          "value": "CMIODeviceSMPTETimeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mCommandLength/title",
          "value": "mCommandLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mCommandLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCommandLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mResponseUsed/title",
          "value": "mResponseUsed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mResponseUsed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mResponseUsed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/title",
          "value": "CMIODeviceStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/title",
          "value": "CMIOStreamDeck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mCommand/title",
          "value": "mCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command~1mCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/title",
          "value": "CMIODeviceRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiodevicers422command"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiodevicers422command"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
