{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIODevice properties"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceSignalMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceSignalMode"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyAVCDeviceSignalMode",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyavcdevicesignalmode"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceType"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyAVCDeviceType",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyavcdevicetype"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessAVCCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyCanProcessAVCCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertycanprocessavccommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessRS422Command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessRS422Command"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyCanProcessRS422Command",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertycanprocessrs422command"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertycanswitchframerateswithoutframedrops"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyClientSyncDiscontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyClientSyncDiscontinuity"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyClientSyncDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyclientsyncdiscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceCanBeDefaultDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicecanbedefaultdevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceControl"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceControl",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicecontrol"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceHasChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceHasChanged"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceHasChanged",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicehaschanged"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasStreamingError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceHasStreamingError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasStreamingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceHasStreamingError"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceHasStreamingError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicehasstreamingerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsAlive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsAlive"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceIsAlive",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceisalive"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunning"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceIsRunning",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceisrunning"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunningSomewhere"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunningSomewhere"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceIsRunningSomewhere",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceisrunningsomewhere"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceMaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceMaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicemaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceUID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceuid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyExcludeNonDALAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyExcludeNonDALAccess"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyExcludeNonDALAccess",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyexcludenondalaccess"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyHogMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyHogMode"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyHogMode",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyhogmode"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyIIDCCSRData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyIIDCCSRData"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyIIDCCSRData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyiidccsrdata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCInitialUnitSpace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyIIDCInitialUnitSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCInitialUnitSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyIIDCInitialUnitSpace"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyIIDCInitialUnitSpace",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyiidcinitialunitspace"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLatency"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLatency",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylatency"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylinkedandsyncedcoreaudiodeviceuid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedCoreAudioDeviceUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLinkedCoreAudioDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedCoreAudioDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLinkedCoreAudioDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLinkedCoreAudioDeviceUID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylinkedcoreaudiodeviceuid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocation"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLocation",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylocation"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyModelUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyModelUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyModelUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyModelUID"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyModelUID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertymodeluid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyPlugIn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyPlugIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyPlugIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyPlugIn"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyPlugIn",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyplugin"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySMPTETimeCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertySMPTETimeCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySMPTETimeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertySMPTETimeCallback"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertySMPTETimeCallback",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertysmptetimecallback"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreamConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyStreamConfiguration",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertystreamconfiguration"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyStreams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyStreams"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyStreams",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertystreams"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySuspendedByUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertySuspendedByUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySuspendedByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertySuspendedByUser"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertySuspendedByUser",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertysuspendedbyuser"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyTransportType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyTransportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyTransportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyTransportType"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyTransportType",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertytransporttype"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyVideoDigitizerComponents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyVideoDigitizerComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyVideoDigitizerComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyVideoDigitizerComponents"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyVideoDigitizerComponents",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyvideodigitizercomponents"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCInitialUnitSpace",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLatency",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedCoreAudioDeviceUID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyModelUID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyPlugIn",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySMPTETimeCallback",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreamConfiguration",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreams",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySuspendedByUser",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyTransportType",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyVideoDigitizerComponents",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceControl",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasStreamingError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCInitialUnitSpace",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLatency",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLinkedCoreAudioDeviceUID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyModelUID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyPlugIn",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySMPTETimeCallback",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreamConfiguration",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyStreams",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertySuspendedByUser",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyTransportType",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyVideoDigitizerComponents",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceControl",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasStreamingError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceHasChanged/title",
          "value": "kCMIODevicePropertyDeviceHasChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceHasChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceHasChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceMaster/title",
          "value": "kCMIODevicePropertyDeviceMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyExcludeNonDALAccess/title",
          "value": "kCMIODevicePropertyExcludeNonDALAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyExcludeNonDALAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyExcludeNonDALAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertySuspendedByUser/title",
          "value": "kCMIODevicePropertySuspendedByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertySuspendedByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertySuspendedByUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyStreamConfiguration/title",
          "value": "kCMIODevicePropertyStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyClientSyncDiscontinuity/title",
          "value": "kCMIODevicePropertyClientSyncDiscontinuity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyClientSyncDiscontinuity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyClientSyncDiscontinuity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceHasStreamingError/title",
          "value": "kCMIODevicePropertyDeviceHasStreamingError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceHasStreamingError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceHasStreamingError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyIIDCInitialUnitSpace/title",
          "value": "kCMIODevicePropertyIIDCInitialUnitSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyIIDCInitialUnitSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyIIDCInitialUnitSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID/title",
          "value": "kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyPlugIn/title",
          "value": "kCMIODevicePropertyPlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyPlugIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunning/title",
          "value": "kCMIODevicePropertyDeviceIsRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceIsRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessAVCCommand/title",
          "value": "kCMIODevicePropertyCanProcessAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessAVCCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanProcessAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyModelUID/title",
          "value": "kCMIODevicePropertyModelUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyModelUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyModelUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceCanBeDefaultDevice/title",
          "value": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceCanBeDefaultDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertySMPTETimeCallback/title",
          "value": "kCMIODevicePropertySMPTETimeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertySMPTETimeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertySMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessRS422Command/title",
          "value": "kCMIODevicePropertyCanProcessRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessRS422Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanProcessRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyIIDCCSRData/title",
          "value": "kCMIODevicePropertyIIDCCSRData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyIIDCCSRData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyIIDCCSRData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceSignalMode/title",
          "value": "kCMIODevicePropertyAVCDeviceSignalMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceSignalMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyAVCDeviceSignalMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyHogMode/title",
          "value": "kCMIODevicePropertyHogMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyHogMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyHogMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsAlive/title",
          "value": "kCMIODevicePropertyDeviceIsAlive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsAlive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceIsAlive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceType/title",
          "value": "kCMIODevicePropertyAVCDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyAVCDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLinkedCoreAudioDeviceUID/title",
          "value": "kCMIODevicePropertyLinkedCoreAudioDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLinkedCoreAudioDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLinkedCoreAudioDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLatency/title",
          "value": "kCMIODevicePropertyLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops/title",
          "value": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceUID/title",
          "value": "kCMIODevicePropertyDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyStreams/title",
          "value": "kCMIODevicePropertyStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyStreams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunningSomewhere/title",
          "value": "kCMIODevicePropertyDeviceIsRunningSomewhere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunningSomewhere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceIsRunningSomewhere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceControl/title",
          "value": "kCMIODevicePropertyDeviceControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyVideoDigitizerComponents/title",
          "value": "kCMIODevicePropertyVideoDigitizerComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyVideoDigitizerComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyVideoDigitizerComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocation/title",
          "value": "kCMIODevicePropertyLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyTransportType/title",
          "value": "kCMIODevicePropertyTransportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyTransportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyTransportType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiodevice-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiodevice-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
