{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMIOStreamCopyBufferQueue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMIOStreamCopyBufferQueue"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMIOStreamID",
        "text": "CMIOStreamID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMIODeviceStreamQueueAlteredProc",
        "text": "CMIODeviceStreamQueueAlteredProc"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSimpleQueueRef",
        "text": "CMSimpleQueue"
      },
      {
        "kind": "text",
        "text": ">?>!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIOStreamCopyBufferQueue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMIOStreamCopyBufferQueue(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMIOStreamCopyBufferQueue"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "streamID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMIOStreamID",
              "text": "CMIOStreamID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queueAlteredProc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamQueueAlteredProc",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMIODeviceStreamQueueAlteredProc",
              "text": "CMIODeviceStreamQueueAlteredProc"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queueAlteredRefCon"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSimpleQueueRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSimpleQueueRef",
              "text": "CMSimpleQueue"
            },
            {
              "kind": "text",
              "text": ">?>!) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessAVCCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIODeviceAVCCommand",
          "text": "CMIODeviceAVCCommand"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceProcessAVCCommand(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceprocessavccommand(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessRS422Command"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIODeviceRS422Command",
          "text": "CMIODeviceRS422Command"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessRS422Command"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceProcessRS422Command(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceprocessrs422command(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStartStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStartStream"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStartStream(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestartstream(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStopStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStopStream"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStopStream(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestopstream(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamQueueAlteredProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamQueueAlteredProc"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamQueueAlteredProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamQueueAlteredProc"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStreamQueueAlteredProc",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestreamqueuealteredproc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerProc",
          "text": "CMIOObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectAddPropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectaddpropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerBlock",
          "text": "CMIOObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectaddpropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectgetpropertydata(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyDataSize"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectgetpropertydatasize(_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectHasProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectHasProperty"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectHasProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjecthasproperty(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectIsPropertySettable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectIsPropertySettable"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectIsPropertySettable(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectispropertysettable(_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerProc",
          "text": "CMIOObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListener"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectRemovePropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectremovepropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerBlock",
          "text": "CMIOObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectremovepropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectSetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectSetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectsetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectShow"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectShow(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectshow(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCopyNonRequiredAttachments"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCopyNonRequiredAttachments",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercopynonrequiredattachments"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamClockConvertHostTimeToDeviceTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamClockConvertHostTimeToDeviceTime"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamclockconverthosttimetodevicetime(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamCopyBufferQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceStreamQueueAlteredProc",
          "text": "CMIODeviceStreamQueueAlteredProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSimpleQueueRef",
          "text": "CMSimpleQueue"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamCopyBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamCopyBufferQueue(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamcopybufferqueue(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamID"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamID"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamID",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMSimpleQueueRef": {
      "abstract": [
        {
          "text": "A reference to an instance that provides a simple lockless queue of elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSimpleQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSimpleQueueRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSimpleQueue",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSimpleQueue"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMIOStreamCopyBufferQueue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamCopyBufferQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMIOStreamCopyBufferQueue"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMIOStreamID",
                    "text": "CMIOStreamID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "streamID"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamQueueAlteredProc",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMIODeviceStreamQueueAlteredProc",
                    "text": "CMIODeviceStreamQueueAlteredProc"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queueAlteredProc"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queueAlteredRefCon"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSimpleQueueRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSimpleQueueRef",
                    "text": "CMSimpleQueueRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListener(_:_:_:_:)/title",
          "value": "CMIOObjectAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)/title",
          "value": "CMIOStreamClockConvertHostTimeToDeviceTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamClockConvertHostTimeToDeviceTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamID/title",
          "value": "CMIOStreamID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStartStream(_:_:)/title",
          "value": "CMIODeviceStartStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStartStream(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStartStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListener(_:_:_:_:)/title",
          "value": "CMIOObjectRemovePropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectRemovePropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectIsPropertySettable(_:_:_:)/title",
          "value": "CMIOObjectIsPropertySettable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectIsPropertySettable(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectIsPropertySettable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessAVCCommand(_:_:)/title",
          "value": "CMIODeviceProcessAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessAVCCommand(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceProcessAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)/title",
          "value": "CMIOObjectRemovePropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectRemovePropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessRS422Command(_:_:)/title",
          "value": "CMIODeviceProcessRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessRS422Command(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceProcessRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListenerBlock(_:_:_:_:)/title",
          "value": "CMIOObjectAddPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectAddPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamCopyBufferQueue(_:_:_:_:)/title",
          "value": "CMIOStreamCopyBufferQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamCopyBufferQueue(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamCopyBufferQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectHasProperty(_:_:)/title",
          "value": "CMIOObjectHasProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectHasProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectHasProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamQueueAlteredProc/title",
          "value": "CMIODeviceStreamQueueAlteredProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamQueueAlteredProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamQueueAlteredProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamQueueAlteredProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamQueueAlteredProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectShow(_:)/title",
          "value": "CMIOObjectShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectShow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectSetPropertyData(_:_:_:_:_:_:)/title",
          "value": "CMIOObjectSetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectSetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectSetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSimpleQueueRef/title",
          "value": "CMSimpleQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSimpleQueueRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMSimpleQueue",
              "text": "opaqueCMSimpleQueue"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMSimpleQueueRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)/title",
          "value": "CMIOObjectGetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectGetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyDataSize(_:_:_:_:_:)/title",
          "value": "CMIOObjectGetPropertyDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyDataSize(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectGetPropertyDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStopStream(_:_:)/title",
          "value": "CMIODeviceStopStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStopStream(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStopStream"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiostreamcopybufferqueue(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiostreamcopybufferqueue(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
