{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIODeviceAVCSignal mode types"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalMode8mmNTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmode8mmntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalMode8mmPAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmode8mmpal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeAudio"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeAudio",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodeaudio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro100_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro100_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro100_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro100_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro25_525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro25_525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro25_625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro25_625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro50_525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro50_525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro50_625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro50_625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVHS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVHS"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVHS",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvhs"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1125_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1125_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHD1125_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehd1125_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1250_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1250_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHD1250_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehd1250_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV1_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv1_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV1_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv1_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV2_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV2_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV2_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv2_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV2_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV2_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV2_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv2_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHi8NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHi8NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHi8NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehi8ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHi8PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHi8PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHi8PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehi8pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG12Mbps_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG12Mbps_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMPEG12Mbps_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodempeg12mbps_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG12Mbps_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG12Mbps_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMPEG12Mbps_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodempeg12mbps_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG25Mbps_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG25Mbps_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMPEG25Mbps_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodempeg25mbps_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG25Mbps_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG25Mbps_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMPEG25Mbps_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodempeg25mbps_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG6Mbps_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG6Mbps_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMPEG6Mbps_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodempeg6mbps_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG6Mbps_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMPEG6Mbps_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMPEG6Mbps_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodempeg6mbps_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV12Mbps_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV12Mbps_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMicroMV12Mbps_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodemicromv12mbps_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV12Mbps_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV12Mbps_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMicroMV12Mbps_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodemicromv12mbps_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV6Mbps_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV6Mbps_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMicroMV6Mbps_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodemicromv6mbps_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV6Mbps_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeMicroMV6Mbps_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeMicroMV6Mbps_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodemicromv6mbps_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSD525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSD525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSD525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesd525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSD625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSD625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSD625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesd625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSDL525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSDL525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSDL525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesdl525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSDL625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSDL625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSDL625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesdl625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSVHS525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSVHS525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSVHS525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesvhs525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSVHS625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSVHS625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSVHS625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesvhs625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMESECAM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSMESECAM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMESECAM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSMESECAM"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeVHSMESECAM",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodevhsmesecam"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMPAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSMPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSMPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeVHSMPAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodevhsmpal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNPAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSNPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSNPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeVHSNPAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodevhsnpal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeVHSNTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodevhsntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSPAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeVHSPAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodevhspal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSSECAM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSSECAM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSSECAM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeVHSSECAM"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeVHSSECAM",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodevhssecam"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMESECAM",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMPAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNPAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSPAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSSECAM"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHi8PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG12Mbps_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG25Mbps_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMPEG6Mbps_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV12Mbps_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeMicroMV6Mbps_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSDL625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSVHS625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMESECAM",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSMPAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNPAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSNTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSPAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeVHSSECAM"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV2_50/title",
          "value": "kCMIODeviceAVCSignalModeHDV2_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV2_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV2_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_525_60/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHi8NTSC/title",
          "value": "kCMIODeviceAVCSignalModeHi8NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHi8NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHi8NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_60/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro100_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro100_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG6Mbps_60/title",
          "value": "kCMIODeviceAVCSignalModeMPEG6Mbps_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG6Mbps_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMPEG6Mbps_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSDL525_60/title",
          "value": "kCMIODeviceAVCSignalModeSDL525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSDL525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSDL525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSD525_60/title",
          "value": "kCMIODeviceAVCSignalModeSD525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSD525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSD525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeAudio/title",
          "value": "kCMIODeviceAVCSignalModeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG25Mbps_50/title",
          "value": "kCMIODeviceAVCSignalModeMPEG25Mbps_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG25Mbps_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMPEG25Mbps_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHi8PAL/title",
          "value": "kCMIODeviceAVCSignalModeHi8PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHi8PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHi8PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_60/title",
          "value": "kCMIODeviceAVCSignalModeHDV1_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV1_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSPAL/title",
          "value": "kCMIODeviceAVCSignalModeVHSPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeVHSPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSMESECAM/title",
          "value": "kCMIODeviceAVCSignalModeVHSMESECAM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSMESECAM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeVHSMESECAM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG12Mbps_50/title",
          "value": "kCMIODeviceAVCSignalModeMPEG12Mbps_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG12Mbps_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMPEG12Mbps_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG25Mbps_60/title",
          "value": "kCMIODeviceAVCSignalModeMPEG25Mbps_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG25Mbps_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMPEG25Mbps_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_50/title",
          "value": "kCMIODeviceAVCSignalModeHDV1_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV1_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV6Mbps_60/title",
          "value": "kCMIODeviceAVCSignalModeMicroMV6Mbps_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV6Mbps_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMicroMV6Mbps_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVHS/title",
          "value": "kCMIODeviceAVCSignalModeDVHS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVHS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVHS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV12Mbps_60/title",
          "value": "kCMIODeviceAVCSignalModeMicroMV12Mbps_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV12Mbps_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMicroMV12Mbps_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmNTSC/title",
          "value": "kCMIODeviceAVCSignalMode8mmNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalMode8mmNTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSVHS625_50/title",
          "value": "kCMIODeviceAVCSignalModeSVHS625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSVHS625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSVHS625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_625_50/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_525_60/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV12Mbps_50/title",
          "value": "kCMIODeviceAVCSignalModeMicroMV12Mbps_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV12Mbps_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMicroMV12Mbps_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSNPAL/title",
          "value": "kCMIODeviceAVCSignalModeVHSNPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSNPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeVHSNPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSD625_50/title",
          "value": "kCMIODeviceAVCSignalModeSD625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSD625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSD625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_50/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro100_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro100_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSVHS525_60/title",
          "value": "kCMIODeviceAVCSignalModeSVHS525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSVHS525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSVHS525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmPAL/title",
          "value": "kCMIODeviceAVCSignalMode8mmPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalMode8mmPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG12Mbps_60/title",
          "value": "kCMIODeviceAVCSignalModeMPEG12Mbps_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG12Mbps_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMPEG12Mbps_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV6Mbps_50/title",
          "value": "kCMIODeviceAVCSignalModeMicroMV6Mbps_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMicroMV6Mbps_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMicroMV6Mbps_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_625_50/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV2_60/title",
          "value": "kCMIODeviceAVCSignalModeHDV2_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV2_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV2_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSSECAM/title",
          "value": "kCMIODeviceAVCSignalModeVHSSECAM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSSECAM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeVHSSECAM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG6Mbps_50/title",
          "value": "kCMIODeviceAVCSignalModeMPEG6Mbps_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeMPEG6Mbps_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeMPEG6Mbps_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1250_50/title",
          "value": "kCMIODeviceAVCSignalModeHD1250_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1250_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHD1250_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSMPAL/title",
          "value": "kCMIODeviceAVCSignalModeVHSMPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSMPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeVHSMPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSDL625_50/title",
          "value": "kCMIODeviceAVCSignalModeSDL625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSDL625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSDL625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1125_60/title",
          "value": "kCMIODeviceAVCSignalModeHD1125_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1125_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHD1125_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSNTSC/title",
          "value": "kCMIODeviceAVCSignalModeVHSNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeVHSNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeVHSNTSC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
