{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOStream properties"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyCanProcessDeckCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyCanProcessDeckCommand"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyCanProcessDeckCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertycanprocessdeckcommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyClock"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyClock",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyclock"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeck"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeck",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeck"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckCueing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckCueing"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckCueing",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckcueing"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckDropness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckDropness"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckDropness",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckdropness"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckFrameNumber"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckFrameNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckframenumber"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckLocal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckLocal"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckLocal",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydecklocal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckThreaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckThreaded"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckThreaded",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckthreaded"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydevicesynctimeoutinmsec"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDirection"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDirection",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydirection"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyEndOfData"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyEndOfData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyendofdata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyfirstoutputpresentationtimestamp"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFormatDescription",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyformatdescription"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescriptions"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFormatDescriptions",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyformatdescriptions"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRate"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFrameRate",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyframerate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRateRanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRateRanges"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFrameRateRanges",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyframerateranges"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRates"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFrameRates",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyframerates"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyinitialpresentationtimestampforlinkedandsyncedaudio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyLatency"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyLatency",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertylatency"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyMinimumFrameRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyMinimumFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyMinimumFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyMinimumFrameRate"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyMinimumFrameRate",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyminimumframerate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataEventCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyNoDataEventCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataEventCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyNoDataEventCount"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyNoDataEventCount",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertynodataeventcount"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataTimeoutInMSec": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyNoDataTimeoutInMSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataTimeoutInMSec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyNoDataTimeoutInMSec"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyNoDataTimeoutInMSec",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertynodatatimeoutinmsec"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferQueueSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBufferQueueSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferQueueSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBufferQueueSize"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyOutputBufferQueueSize",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyoutputbufferqueuesize"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferRepeatCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBufferRepeatCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferRepeatCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBufferRepeatCount"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyOutputBufferRepeatCount",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyoutputbufferrepeatcount"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBufferUnderrunCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBufferUnderrunCount"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyOutputBufferUnderrunCount",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyoutputbufferunderruncount"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyoutputbuffersneededforthrottledplayback"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersRequiredForStartup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBuffersRequiredForStartup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersRequiredForStartup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyOutputBuffersRequiredForStartup"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyOutputBuffersRequiredForStartup",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyoutputbuffersrequiredforstartup"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFormatDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyPreferredFormatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyPreferredFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyPreferredFormatDescription",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertypreferredformatdescription"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFrameRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyPreferredFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyPreferredFrameRate"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyPreferredFrameRate",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertypreferredframerate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyScheduledOutputNotificationProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyScheduledOutputNotificationProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyScheduledOutputNotificationProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyScheduledOutputNotificationProc"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyScheduledOutputNotificationProc",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyscheduledoutputnotificationproc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStartingChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyStartingChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStartingChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyStartingChannel"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyStartingChannel",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertystartingchannel"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyStillImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyStillImage"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyStillImage",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertystillimage"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImageFormatDescriptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyStillImageFormatDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImageFormatDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyStillImageFormatDescriptions"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyStillImageFormatDescriptions",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertystillimageformatdescriptions"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyTerminalType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyTerminalType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyTerminalType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyTerminalType"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyTerminalType",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyterminaltype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRates",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyLatency",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyMinimumFrameRate",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataEventCount",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataTimeoutInMSec",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferQueueSize",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferRepeatCount",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersRequiredForStartup",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFormatDescription",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFrameRate",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyScheduledOutputNotificationProc",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStartingChannel",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImage",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImageFormatDescriptions",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyTerminalType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRates",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyLatency",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyMinimumFrameRate",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataEventCount",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyNoDataTimeoutInMSec",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferQueueSize",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferRepeatCount",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBufferUnderrunCount",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyOutputBuffersRequiredForStartup",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFormatDescription",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyPreferredFrameRate",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyScheduledOutputNotificationProc",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStartingChannel",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImage",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyStillImageFormatDescriptions",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyTerminalType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDirection/title",
          "value": "kCMIOStreamPropertyDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferQueueSize/title",
          "value": "kCMIOStreamPropertyOutputBufferQueueSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferQueueSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyOutputBufferQueueSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckLocal/title",
          "value": "kCMIOStreamPropertyDeckLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckLocal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBuffersRequiredForStartup/title",
          "value": "kCMIOStreamPropertyOutputBuffersRequiredForStartup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBuffersRequiredForStartup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyOutputBuffersRequiredForStartup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescriptions/title",
          "value": "kCMIOStreamPropertyFormatDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFormatDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyTerminalType/title",
          "value": "kCMIOStreamPropertyTerminalType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyTerminalType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyTerminalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyPreferredFormatDescription/title",
          "value": "kCMIOStreamPropertyPreferredFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyPreferredFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyPreferredFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyClock/title",
          "value": "kCMIOStreamPropertyClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckDropness/title",
          "value": "kCMIOStreamPropertyDeckDropness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckDropness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckDropness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyNoDataTimeoutInMSec/title",
          "value": "kCMIOStreamPropertyNoDataTimeoutInMSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyNoDataTimeoutInMSec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyNoDataTimeoutInMSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFirstOutputPresentationTimeStamp/title",
          "value": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFirstOutputPresentationTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyStartingChannel/title",
          "value": "kCMIOStreamPropertyStartingChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyStartingChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyStartingChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyMinimumFrameRate/title",
          "value": "kCMIOStreamPropertyMinimumFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyMinimumFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyMinimumFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeck/title",
          "value": "kCMIOStreamPropertyDeck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyScheduledOutputNotificationProc/title",
          "value": "kCMIOStreamPropertyScheduledOutputNotificationProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyScheduledOutputNotificationProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyScheduledOutputNotificationProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyLatency/title",
          "value": "kCMIOStreamPropertyLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferRepeatCount/title",
          "value": "kCMIOStreamPropertyOutputBufferRepeatCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferRepeatCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyOutputBufferRepeatCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio/title",
          "value": "kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyInitialPresentationTimeStampForLinkedAndSyncedAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyStillImageFormatDescriptions/title",
          "value": "kCMIOStreamPropertyStillImageFormatDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyStillImageFormatDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyStillImageFormatDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback/title",
          "value": "kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyOutputBuffersNeededForThrottledPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyStillImage/title",
          "value": "kCMIOStreamPropertyStillImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyStillImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyStillImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferUnderrunCount/title",
          "value": "kCMIOStreamPropertyOutputBufferUnderrunCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyOutputBufferUnderrunCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyOutputBufferUnderrunCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescription/title",
          "value": "kCMIOStreamPropertyFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRateRanges/title",
          "value": "kCMIOStreamPropertyFrameRateRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRateRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFrameRateRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyCanProcessDeckCommand/title",
          "value": "kCMIOStreamPropertyCanProcessDeckCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyCanProcessDeckCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyCanProcessDeckCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckThreaded/title",
          "value": "kCMIOStreamPropertyDeckThreaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckThreaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckThreaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyPreferredFrameRate/title",
          "value": "kCMIOStreamPropertyPreferredFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyPreferredFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyPreferredFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRates/title",
          "value": "kCMIOStreamPropertyFrameRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFrameRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeviceSyncTimeoutInMSec/title",
          "value": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeviceSyncTimeoutInMSec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyEndOfData/title",
          "value": "kCMIOStreamPropertyEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyEndOfData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckFrameNumber/title",
          "value": "kCMIOStreamPropertyDeckFrameNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckFrameNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckFrameNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRate/title",
          "value": "kCMIOStreamPropertyFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckCueing/title",
          "value": "kCMIOStreamPropertyDeckCueing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckCueing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckCueing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyNoDataEventCount/title",
          "value": "kCMIOStreamPropertyNoDataEventCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyNoDataEventCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyNoDataEventCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiostream-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiostream-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
