{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMIOSampleBufferCopyNonRequiredAttachments",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMIOSampleBufferCopyNonRequiredAttachments"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIOSampleBufferCopyNonRequiredAttachments"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.7",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMIOSampleBufferCopyNonRequiredAttachments"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMIOSampleBufferCopyNonRequiredAttachments"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sourceSBuf"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "destSBuf"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMAttachmentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMAttachmentMode",
              "text": "CMAttachmentMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attachmentMode"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessAVCCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIODeviceAVCCommand",
          "text": "CMIODeviceAVCCommand"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceProcessAVCCommand(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceprocessavccommand(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessRS422Command"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIODeviceRS422Command",
          "text": "CMIODeviceRS422Command"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessRS422Command"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceProcessRS422Command(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceprocessrs422command(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStartStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStartStream"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStartStream(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestartstream(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStopStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStopStream"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStopStream(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestopstream(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerProc",
          "text": "CMIOObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectAddPropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectaddpropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerBlock",
          "text": "CMIOObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectaddpropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectgetpropertydata(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyDataSize"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectgetpropertydatasize(_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectHasProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectHasProperty"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectHasProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjecthasproperty(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectIsPropertySettable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectIsPropertySettable"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectIsPropertySettable(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectispropertysettable(_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerProc",
          "text": "CMIOObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListener"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectRemovePropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectremovepropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerBlock",
          "text": "CMIOObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectremovepropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectSetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectSetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectsetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectShow"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectShow(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectshow(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCopyNonRequiredAttachments"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCopyNonRequiredAttachments",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercopynonrequiredattachments"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopySampleAttachments": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCopySampleAttachments"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopySampleAttachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCopySampleAttachments",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercopysampleattachments"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMAttachmentMode": {
      "abstract": [
        {
          "text": "The mode to use when propagating attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMAttachmentMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMAttachmentMode",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMAttachmentMode"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBuffer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopySampleAttachments"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)/title",
          "value": "CMIOObjectGetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectGetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectHasProperty(_:_:)/title",
          "value": "CMIOObjectHasProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectHasProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectHasProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListenerBlock(_:_:_:_:)/title",
          "value": "CMIOObjectAddPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectAddPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectIsPropertySettable(_:_:_:)/title",
          "value": "CMIOObjectIsPropertySettable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectIsPropertySettable(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectIsPropertySettable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListener(_:_:_:_:)/title",
          "value": "CMIOObjectAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyDataSize(_:_:_:_:_:)/title",
          "value": "CMIOObjectGetPropertyDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyDataSize(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectGetPropertyDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStopStream(_:_:)/title",
          "value": "CMIODeviceStopStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStopStream(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStopStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessRS422Command(_:_:)/title",
          "value": "CMIODeviceProcessRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessRS422Command(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceProcessRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectSetPropertyData(_:_:_:_:_:_:)/title",
          "value": "CMIOObjectSetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectSetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectSetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectShow(_:)/title",
          "value": "CMIOObjectShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectShow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)/title",
          "value": "CMIOObjectRemovePropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectRemovePropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMAttachmentMode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMAttachmentMode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMSampleBuffer",
              "text": "opaqueCMSampleBuffer"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStartStream(_:_:)/title",
          "value": "CMIODeviceStartStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStartStream(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStartStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListener(_:_:_:_:)/title",
          "value": "CMIOObjectRemovePropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectRemovePropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessAVCCommand(_:_:)/title",
          "value": "CMIODeviceProcessAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessAVCCommand(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceProcessAVCCommand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiosamplebuffercopynonrequiredattachments"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
