{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOAVCDeviceType constants"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_720p"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_720p"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro100_720p",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro100_720p"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro100_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro100_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro100_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro100_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro50_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro50_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro50_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro50_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCProHD_1080i50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcprohd_1080i50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCProHD_1080i60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcprohd_1080i60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DV_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dv_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DV_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dv_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_MPEG2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_MPEG2"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_MPEG2",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_mpeg2"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_Unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_Unknown"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_Unknown",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_PAL/title",
          "value": "kCMIOAVCDeviceType_DV_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DV_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i50/title",
          "value": "kCMIOAVCDeviceType_DVCProHD_1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCProHD_1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_PAL/title",
          "value": "kCMIOAVCDeviceType_DVCPro50_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro50_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i60/title",
          "value": "kCMIOAVCDeviceType_DVCProHD_1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCProHD_1080i60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_NTSC/title",
          "value": "kCMIOAVCDeviceType_DVCPro50_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro50_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_NTSC/title",
          "value": "kCMIOAVCDeviceType_DVCPro_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_PAL/title",
          "value": "kCMIOAVCDeviceType_DVCPro100_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro100_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_MPEG2/title",
          "value": "kCMIOAVCDeviceType_MPEG2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_MPEG2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_MPEG2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_NTSC/title",
          "value": "kCMIOAVCDeviceType_DVCPro100_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro100_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_720p/title",
          "value": "kCMIOAVCDeviceType_DVCPro100_720p"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_720p/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro100_720p"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_Unknown/title",
          "value": "kCMIOAVCDeviceType_Unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_Unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_Unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_PAL/title",
          "value": "kCMIOAVCDeviceType_DVCPro_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_NTSC/title",
          "value": "kCMIOAVCDeviceType_DV_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DV_NTSC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioavcdevicetype-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioavcdevicetype-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
