{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CMIOHardwarePlugInInterface",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMIOHardwarePlugInInterface"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIOHardwarePlugInInterface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.4",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.3",
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CMIOHardwarePlugInInterface"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMIOHardwarePlugInInterface"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceAVCCommand"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceAVCCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavccommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceRS422Command"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceRS422Command"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceRS422Command",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceSMPTETimeCallback",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicesmptetimecallback"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStreamConfiguration",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestreamconfiguration"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOHardwarePlugInInterface"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOHardwarePlugInInterface",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/AddRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AddRef"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/AddRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "AddRef",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/addref"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceProcessAVCCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DeviceProcessAVCCommand"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceProcessAVCCommand",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceProcessAVCCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/deviceprocessavccommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceProcessRS422Command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DeviceProcessRS422Command"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceProcessRS422Command",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceProcessRS422Command",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/deviceprocessrs422command"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceResume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DeviceResume"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceResume",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceResume",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/deviceresume"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceStartStream": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DeviceStartStream"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceStartStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceStartStream",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/devicestartstream"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceStopStream": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DeviceStopStream"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceStopStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceStopStream",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/devicestopstream"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceSuspend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DeviceSuspend"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceSuspend",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceSuspend",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/devicesuspend"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Initialize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "Initialize"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Initialize",
      "kind": "symbol",
      "role": "symbol",
      "title": "Initialize",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/initialize"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/InitializeWithObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "InitializeWithObjectID"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/InitializeWithObjectID",
      "kind": "symbol",
      "role": "symbol",
      "title": "InitializeWithObjectID",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/initializewithobjectid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectGetPropertyData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ObjectGetPropertyData"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectGetPropertyData",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjectGetPropertyData",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/objectgetpropertydata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectGetPropertyDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ObjectGetPropertyDataSize"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectGetPropertyDataSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjectGetPropertyDataSize",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/objectgetpropertydatasize"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectHasProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ObjectHasProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectHasProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjectHasProperty",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/objecthasproperty"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectIsPropertySettable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ObjectIsPropertySettable"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectIsPropertySettable",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjectIsPropertySettable",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/objectispropertysettable"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectSetPropertyData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ObjectSetPropertyData"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectSetPropertyData",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjectSetPropertyData",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/objectsetpropertydata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectShow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ObjectShow"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectShow",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjectShow",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/objectshow"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/QueryInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QueryInterface"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/QueryInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "QueryInterface",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/queryinterface"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Release": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "Release"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Release",
      "kind": "symbol",
      "role": "symbol",
      "title": "Release",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/release"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamCopyBufferQueue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StreamCopyBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamCopyBufferQueue",
      "kind": "symbol",
      "role": "symbol",
      "title": "StreamCopyBufferQueue",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/streamcopybufferqueue"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckCueTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StreamDeckCueTo"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckCueTo",
      "kind": "symbol",
      "role": "symbol",
      "title": "StreamDeckCueTo",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/streamdeckcueto"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckJog": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StreamDeckJog"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckJog",
      "kind": "symbol",
      "role": "symbol",
      "title": "StreamDeckJog",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/streamdeckjog"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckPlay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StreamDeckPlay"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckPlay",
      "kind": "symbol",
      "role": "symbol",
      "title": "StreamDeckPlay",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/streamdeckplay"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckStop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StreamDeckStop"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckStop",
      "kind": "symbol",
      "role": "symbol",
      "title": "StreamDeckStop",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/streamdeckstop"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Teardown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "Teardown"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Teardown",
      "kind": "symbol",
      "role": "symbol",
      "title": "Teardown",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface/teardown"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectpropertyaddress"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeck"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeck"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeck",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeck"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamscheduledoutputnotificationprocandrefcon"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/AddRef",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceProcessAVCCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceProcessRS422Command",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceResume",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceStartStream",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceStopStream",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/DeviceSuspend",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Initialize",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/InitializeWithObjectID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectGetPropertyData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectGetPropertyDataSize",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectHasProperty",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectIsPropertySettable",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectSetPropertyData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/ObjectShow",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/QueryInterface",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Release",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamCopyBufferQueue",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckCueTo",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckJog",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckPlay",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/StreamDeckStop",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface/Teardown"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/title",
          "value": "CMIOObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/title",
          "value": "CMIOStreamDeck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/title",
          "value": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/title",
          "value": "CMIODeviceStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/title",
          "value": "CMIODeviceAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/title",
          "value": "CMIODeviceSMPTETimeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/title",
          "value": "CMIODeviceRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiohardwareplugininterface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
