{
  "abstract": [
    {
      "text": "An object that represents a physical or virtual device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMIOExtensionDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMIOExtensionDevice"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIOExtensionDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMIOExtensionDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A device provides one or more streams of media data to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice": {
      "abstract": [
        {
          "text": "An object that represents a physical or virtual device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDevice"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDevice"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/addStream(_:)": {
      "abstract": [
        {
          "text": "Adds a stream to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
          "text": "CMIOExtensionStream"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/addStream(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addStream:error:"
        }
      ],
      "role": "symbol",
      "title": "addStream(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/addstream(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceID": {
      "abstract": [
        {
          "text": "A universally unique device identifier value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceID"
        }
      ],
      "role": "symbol",
      "title": "deviceID",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/deviceid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceWithLocalizedName:deviceID:legacyDeviceID:source:": {
      "abstract": [
        {
          "text": "Returns a new extension device with an optional legacy device identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "deviceWithLocalizedName:deviceID:legacyDeviceID:source:"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceWithLocalizedName:deviceID:legacyDeviceID:source:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceWithLocalizedName:deviceID:legacyDeviceID:source:"
        }
      ],
      "role": "symbol",
      "title": "deviceWithLocalizedName:deviceID:legacyDeviceID:source:",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/devicewithlocalizedname:deviceid:legacydeviceid:source:"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceWithLocalizedName:deviceID:source:": {
      "abstract": [
        {
          "text": "Returns a new extension device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "deviceWithLocalizedName:deviceID:source:"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceWithLocalizedName:deviceID:source:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceWithLocalizedName:deviceID:source:"
        }
      ],
      "role": "symbol",
      "title": "deviceWithLocalizedName:deviceID:source:",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/devicewithlocalizedname:deviceid:source:"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:legacyDeviceID:source:)": {
      "abstract": [
        {
          "text": "Creates an extension device with an optional legacy device identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "legacyDeviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CMIOExtensionDeviceSource",
          "text": "CMIOExtensionDeviceSource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:legacyDeviceID:source:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedName:deviceID:legacyDeviceID:source:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedName:deviceID:legacyDeviceID:source:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/init(localizedname:deviceid:legacydeviceid:source:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:source:)": {
      "abstract": [
        {
          "text": "Creates an extension device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CMIOExtensionDeviceSource",
          "text": "CMIOExtensionDeviceSource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:source:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedName:deviceID:source:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedName:deviceID:source:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/init(localizedname:deviceid:source:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/legacyDeviceID": {
      "abstract": [
        {
          "text": "A legacy device identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "legacyDeviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/legacyDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "legacyDeviceID"
        }
      ],
      "role": "symbol",
      "title": "legacyDeviceID",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/legacydeviceid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/localizedName": {
      "abstract": [
        {
          "text": "A localized name for a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/localizedname"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/notifyPropertiesChanged(_:)": {
      "abstract": [
        {
          "text": "Notifies clients of property changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notifyPropertiesChanged"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
          "text": "CMIOExtensionPropertyState"
        },
        {
          "kind": "text",
          "text": "<AnyObject>])"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/notifyPropertiesChanged(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notifyPropertiesChanged:"
        }
      ],
      "role": "symbol",
      "title": "notifyPropertiesChanged(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/notifypropertieschanged(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/removeStream(_:)": {
      "abstract": [
        {
          "text": "Removes a stream from the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
          "text": "CMIOExtensionStream"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/removeStream(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeStream:error:"
        }
      ],
      "role": "symbol",
      "title": "removeStream(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/removestream(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/source": {
      "abstract": [
        {
          "text": "A source object for a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CMIOExtensionDeviceSource",
          "text": "CMIOExtensionDeviceSource"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "source"
        }
      ],
      "role": "symbol",
      "title": "source",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/source"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/streams": {
      "abstract": [
        {
          "text": "An array of media streams attached to this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streams"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
          "text": "CMIOExtensionStream"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/streams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "streams"
        }
      ],
      "role": "symbol",
      "title": "streams",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice/streams"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties": {
      "abstract": [
        {
          "text": "An object that defines the properties of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDeviceProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource": {
      "abstract": [
        {
          "text": "A protocol for objects that act as device sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceSource"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceSource"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDeviceSource",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevicesource"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider": {
      "abstract": [
        {
          "text": "An object that manages device connections for a provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProvider"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProvider"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProvider",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovider"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o": {
      "abstract": [
        {
          "text": "Build high-performance camera drivers that are secure and simple to deploy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
      "kind": "article",
      "role": "article",
      "title": "Creating a camera extension with Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio/creating-a-camera-extension-with-core-media-i-o"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Device",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:source:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:legacyDeviceID:source:)"
      ],
      "title": "Creating a Device"
    },
    {
      "anchor": "Identifying-a-Device",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/localizedName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/legacyDeviceID"
      ],
      "title": "Identifying a Device"
    },
    {
      "anchor": "Managing-Streams",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/streams",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/addStream(_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/removeStream(_:)"
      ],
      "title": "Managing Streams"
    },
    {
      "anchor": "Accessing-the-Device-Source",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/source"
      ],
      "title": "Accessing the Device Source"
    },
    {
      "anchor": "Posting-Property-Changes",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/notifyPropertiesChanged(_:)"
      ],
      "title": "Posting Property Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMIOExtensionDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Device",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceWithLocalizedName:deviceID:source:",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceWithLocalizedName:deviceID:legacyDeviceID:source:",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:source:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/init(localizedName:deviceID:legacyDeviceID:source:)"
              ],
              "title": "Creating a Device"
            },
            {
              "anchor": "Identifying-a-Device",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/localizedName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/deviceID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/legacyDeviceID"
              ],
              "title": "Identifying a Device"
            },
            {
              "anchor": "Managing-Streams",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/streams",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/addStream(_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/removeStream(_:)"
              ],
              "title": "Managing Streams"
            },
            {
              "anchor": "Accessing-the-Device-Source",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/source"
              ],
              "title": "Accessing the Device Source"
            },
            {
              "anchor": "Posting-Property-Changes",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice/notifyPropertiesChanged(_:)"
              ],
              "title": "Posting Property Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMIOExtensionDevice"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceSource/title",
          "value": "CMIOExtensionDeviceSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1init(localizedName:deviceID:source:)/title",
          "value": "initWithLocalizedName:deviceID:source:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1init(localizedName:deviceID:source:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedName:deviceID:source:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/title",
          "value": "CMIOExtensionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1source/title",
          "value": "source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1legacyDeviceID/title",
          "value": "legacyDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1legacyDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "legacyDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/title",
          "value": "CMIOExtensionDeviceProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1notifyPropertiesChanged(_:)/title",
          "value": "notifyPropertiesChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1notifyPropertiesChanged(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "notifyPropertiesChanged:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1addStream(_:)/title",
          "value": "addStream:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1addStream(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addStream:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1init(localizedName:deviceID:legacyDeviceID:source:)/title",
          "value": "initWithLocalizedName:deviceID:legacyDeviceID:source:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1init(localizedName:deviceID:legacyDeviceID:source:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedName:deviceID:legacyDeviceID:source:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1streams/title",
          "value": "streams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1streams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "streams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1deviceID/title",
          "value": "deviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1deviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice/title",
          "value": "CMIOExtensionDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1removeStream(_:)/title",
          "value": "removeStream:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice~1removeStream(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeStream:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensiondevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensiondevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
