{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOFeatureControl properties"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteNative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteNative"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteNative",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsolutenative"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteRange"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteRange",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsoluterange"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteUnitName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteUnitName"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteUnitName",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsoluteunitname"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteValue"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteValue",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsolutevalue"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAutomaticManual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAutomaticManual"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAutomaticManual",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyautomaticmanual"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyConvertAbsoluteToNative",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyconvertabsolutetonative"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyConvertNativeToAbsolute",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyconvertnativetoabsolute"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeData"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativedata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeDataRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeDataRange"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeDataRange",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativedatarange"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeRange"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeRange",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativerange"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeValue"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeValue",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativevalue"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyOnOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyOnOff"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyOnOff",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyonoff"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyTune"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyTune"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyTune",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertytune"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeDataRange/title",
          "value": "kCMIOFeatureControlPropertyNativeDataRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeDataRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeDataRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertNativeToAbsolute/title",
          "value": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertNativeToAbsolute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteValue/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteRange/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeRange/title",
          "value": "kCMIOFeatureControlPropertyNativeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteUnitName/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteUnitName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteUnitName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteUnitName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeValue/title",
          "value": "kCMIOFeatureControlPropertyNativeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertAbsoluteToNative/title",
          "value": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertAbsoluteToNative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAutomaticManual/title",
          "value": "kCMIOFeatureControlPropertyAutomaticManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAutomaticManual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAutomaticManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteNative/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteNative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteNative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteNative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyTune/title",
          "value": "kCMIOFeatureControlPropertyTune"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyTune/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyTune"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeData/title",
          "value": "kCMIOFeatureControlPropertyNativeData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyOnOff/title",
          "value": "kCMIOFeatureControlPropertyOnOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyOnOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyOnOff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiofeaturecontrol-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiofeaturecontrol-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
