{
  "abstract": [
    {
      "text": "A protocol for objects that act as provider sources.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CMIOExtensionProviderSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMIOExtensionProviderSource"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIOExtensionProviderSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CMIOExtensionProviderSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a class that adopts this protocol to configure provider properties and manage its client connections.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider": {
      "abstract": [
        {
          "text": "An object that manages device connections for a provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProvider"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProvider"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProvider",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovider"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties": {
      "abstract": [
        {
          "text": "An object that manages the properties of an extension provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProviderProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproviderproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource": {
      "abstract": [
        {
          "text": "A protocol for objects that act as provider sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderSource"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderSource"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProviderSource",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/availableProperties": {
      "abstract": [
        {
          "text": "A set of available properties for a provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/availableProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableProperties"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "availableProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource/availableproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/connect(to:)": {
      "abstract": [
        {
          "text": "Connects a client to a source’s provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
          "text": "CMIOExtensionClient"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/connect(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "connectClient:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "connect(to:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource/connect(to:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/disconnect(from:)": {
      "abstract": [
        {
          "text": "Disconnects a client from a source’s provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
          "text": "CMIOExtensionClient"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/disconnect(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disconnectClient:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "disconnect(from:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource/disconnect(from:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/providerProperties(forProperties:)": {
      "abstract": [
        {
          "text": "Gets the state of provider properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionProviderProperties",
          "text": "CMIOExtensionProviderProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/providerProperties(forProperties:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providerPropertiesForProperties:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "providerProperties(forProperties:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource/providerproperties(forproperties:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/setProviderProperties(_:)": {
      "abstract": [
        {
          "text": "Set the state of provider properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setProviderProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionProviderProperties",
          "text": "CMIOExtensionProviderProperties"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/setProviderProperties(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setProviderProperties:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setProviderProperties(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource/setproviderproperties(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o": {
      "abstract": [
        {
          "text": "Build high-performance camera drivers that are secure and simple to deploy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
      "kind": "article",
      "role": "article",
      "title": "Creating a camera extension with Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio/creating-a-camera-extension-with-core-media-i-o"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension": {
      "abstract": [
        {
          "text": "Create a simple DriverKit extension to override the default driver-matching behavior for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension",
      "kind": "article",
      "role": "article",
      "title": "Overriding the default USB video class extension",
      "type": "topic",
      "url": "/documentation/coremediaio/overriding-the-default-usb-video-class-extension"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties"
      ],
      "title": "Providers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Connections",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/connect(to:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/disconnect(from:)"
      ],
      "title": "Managing Connections"
    },
    {
      "anchor": "Configuring-Properties",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/availableProperties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/providerProperties(forProperties:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/setProviderProperties(_:)"
      ],
      "title": "Configuring Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMIOExtensionProviderSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Connections",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/connect(to:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/disconnect(from:)"
              ],
              "title": "Managing Connections"
            },
            {
              "anchor": "Configuring-Properties",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/availableProperties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/providerProperties(forProperties:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource/setProviderProperties(_:)"
              ],
              "title": "Configuring Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties"
              ],
              "title": "Providers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMIOExtensionProviderSource"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource/title",
          "value": "CMIOExtensionProviderSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1setProviderProperties(_:)/title",
          "value": "setProviderProperties:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1setProviderProperties(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setProviderProperties:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderProperties/title",
          "value": "CMIOExtensionProviderProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1connect(to:)/title",
          "value": "connectClient:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1connect(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "connectClient:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1availableProperties/title",
          "value": "availableProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1availableProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1providerProperties(forProperties:)/title",
          "value": "providerPropertiesForProperties:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1providerProperties(forProperties:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "providerPropertiesForProperties:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/title",
          "value": "CMIOExtensionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1disconnect(from:)/title",
          "value": "disconnectClient:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource~1disconnect(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disconnectClient:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionprovidersource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionprovidersource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
