{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOFeatureControl subclass IDs"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOBacklightCompensationControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOBacklightCompensationControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOBacklightCompensationControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiobacklightcompensationcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOBlackLevelControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOBlackLevelControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOBlackLevelControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioblacklevelcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOBrightnessControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOBrightnessControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOBrightnessControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiobrightnesscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOContrastControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOContrastControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOContrastControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiocontrastcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFocusControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFocusControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFocusControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofocuscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOGainControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOGainControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOGainControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiogaincontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOGammaControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOGammaControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOGammaControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiogammacontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHueControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHueControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHueControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohuecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOIrisControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOIrisControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOIrisControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioiriscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIONoiseReductionControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIONoiseReductionControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIONoiseReductionControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmionoisereductioncontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOOpticalFilterClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOOpticalFilterClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOOpticalFilterClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioopticalfilterclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPanControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPanControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPanControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopancontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltAbsoluteControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPanTiltAbsoluteControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltAbsoluteControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPanTiltAbsoluteControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPanTiltAbsoluteControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopantiltabsolutecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPanTiltRelativeControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPanTiltRelativeControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPanTiltRelativeControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopantiltrelativecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPowerLineFrequencyControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPowerLineFrequencyControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPowerLineFrequencyControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopowerlinefrequencycontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIORollAbsoluteControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIORollAbsoluteControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIORollAbsoluteControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIORollAbsoluteControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIORollAbsoluteControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiorollabsolutecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOSaturationControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOSaturationControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOSaturationControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosaturationcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSharpnessControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOSharpnessControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSharpnessControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOSharpnessControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOSharpnessControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosharpnesscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOShutterControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOShutterControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOShutterControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOShutterControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOShutterControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioshuttercontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTemperatureControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOTemperatureControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTemperatureControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOTemperatureControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOTemperatureControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiotemperaturecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTiltControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOTiltControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTiltControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOTiltControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOTiltControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiotiltcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOWhiteBalanceControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOWhiteBalanceControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOWhiteBalanceControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiowhitebalancecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceUControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOWhiteBalanceUControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceUControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOWhiteBalanceUControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOWhiteBalanceUControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiowhitebalanceucontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceVControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOWhiteBalanceVControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceVControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOWhiteBalanceVControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOWhiteBalanceVControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiowhitebalancevcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteLevelControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOWhiteLevelControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteLevelControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOWhiteLevelControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOWhiteLevelControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiowhitelevelcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOZoomControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOZoomControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOZoomControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiozoomcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomRelativeControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOZoomRelativeControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomRelativeControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOZoomRelativeControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOZoomRelativeControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiozoomrelativecontrolclassid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSharpnessControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOShutterControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTemperatureControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTiltControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceUControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceVControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteLevelControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltAbsoluteControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIORollAbsoluteControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomRelativeControlClassID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSharpnessControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOShutterControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTemperatureControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOTiltControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceUControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteBalanceVControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOWhiteLevelControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltAbsoluteControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIORollAbsoluteControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOZoomRelativeControlClassID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteBalanceUControlClassID/title",
          "value": "kCMIOWhiteBalanceUControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteBalanceUControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOWhiteBalanceUControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIONoiseReductionControlClassID/title",
          "value": "kCMIONoiseReductionControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIONoiseReductionControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIONoiseReductionControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteBalanceControlClassID/title",
          "value": "kCMIOWhiteBalanceControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteBalanceControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOWhiteBalanceControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOContrastControlClassID/title",
          "value": "kCMIOContrastControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOContrastControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOContrastControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteLevelControlClassID/title",
          "value": "kCMIOWhiteLevelControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteLevelControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOWhiteLevelControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOTiltControlClassID/title",
          "value": "kCMIOTiltControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOTiltControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOTiltControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOSaturationControlClassID/title",
          "value": "kCMIOSaturationControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOSaturationControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOSaturationControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOSharpnessControlClassID/title",
          "value": "kCMIOSharpnessControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOSharpnessControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOSharpnessControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPowerLineFrequencyControlClassID/title",
          "value": "kCMIOPowerLineFrequencyControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPowerLineFrequencyControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPowerLineFrequencyControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHueControlClassID/title",
          "value": "kCMIOHueControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHueControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHueControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIORollAbsoluteControlClassID/title",
          "value": "kCMIORollAbsoluteControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIORollAbsoluteControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIORollAbsoluteControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOOpticalFilterClassID/title",
          "value": "kCMIOOpticalFilterClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOOpticalFilterClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOOpticalFilterClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlClassID/title",
          "value": "kCMIOExposureControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOZoomRelativeControlClassID/title",
          "value": "kCMIOZoomRelativeControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOZoomRelativeControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOZoomRelativeControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBacklightCompensationControlClassID/title",
          "value": "kCMIOBacklightCompensationControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBacklightCompensationControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOBacklightCompensationControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBrightnessControlClassID/title",
          "value": "kCMIOBrightnessControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBrightnessControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOBrightnessControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGammaControlClassID/title",
          "value": "kCMIOGammaControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGammaControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOGammaControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOShutterControlClassID/title",
          "value": "kCMIOShutterControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOShutterControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOShutterControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBlackLevelControlClassID/title",
          "value": "kCMIOBlackLevelControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBlackLevelControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOBlackLevelControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteBalanceVControlClassID/title",
          "value": "kCMIOWhiteBalanceVControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOWhiteBalanceVControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOWhiteBalanceVControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOTemperatureControlClassID/title",
          "value": "kCMIOTemperatureControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOTemperatureControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOTemperatureControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanControlClassID/title",
          "value": "kCMIOPanControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPanControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanTiltRelativeControlClassID/title",
          "value": "kCMIOPanTiltRelativeControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanTiltRelativeControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPanTiltRelativeControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFocusControlClassID/title",
          "value": "kCMIOFocusControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFocusControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFocusControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOZoomControlClassID/title",
          "value": "kCMIOZoomControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOZoomControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOZoomControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOIrisControlClassID/title",
          "value": "kCMIOIrisControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOIrisControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOIrisControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanTiltAbsoluteControlClassID/title",
          "value": "kCMIOPanTiltAbsoluteControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanTiltAbsoluteControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPanTiltAbsoluteControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGainControlClassID/title",
          "value": "kCMIOGainControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGainControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOGainControlClassID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
