{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMIOObject constants"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassIDWildcard": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectClassIDWildcard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassIDWildcard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectClassIDWildcard"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectClassIDWildcard",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectclassidwildcard"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementMain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementMain"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyElementMain",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyelementmain"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMaster": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementMaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyElementMaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyelementmaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyScopeGlobal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyScopeGlobal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyScopeGlobal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyScopeGlobal"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyScopeGlobal",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyscopeglobal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectUnknown"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectUnknown",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassIDWildcard",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyScopeGlobal",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectUnknown",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectClassIDWildcard",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyScopeGlobal",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectUnknown",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementMain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementMaster/title",
          "value": "kCMIOObjectPropertyElementMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyElementMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectUnknown/title",
          "value": "kCMIOObjectUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyScopeGlobal/title",
          "value": "kCMIOObjectPropertyScopeGlobal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyScopeGlobal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyScopeGlobal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementMain/title",
          "value": "kCMIOObjectPropertyElementMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementMain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyElementMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectClassID/title",
          "value": "kCMIOObjectClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectClassIDWildcard/title",
          "value": "kCMIOObjectClassIDWildcard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectClassIDWildcard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectClassIDWildcard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioobject-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioobject-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
