{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DAL plug-in enumerations"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOAVCDeviceType constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioavcdevicetype-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOBooleanControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiobooleancontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl base class IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-base-class-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiocontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckShuttle speed constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckshuttle-speed-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckState constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstate-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeckStatus constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeckstatus-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevice properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevice-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODeviceAVCSignal mode types",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavcsignal-mode-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIODevicePropertyLocation constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicepropertylocation-values"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOExposureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioexposurecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOFeatureControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiofeaturecontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Property-Wildcard-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Property-Wildcard-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOObject property wildcard constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobject-property-wildcard-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOPlugIn constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioplugin-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOPlugIn properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioplugin-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-Discontinuity-flag-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-Discontinuity-flag-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSampleBuffer discontinuity flags",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffer-discontinuity-flag-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-No-data-event-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-No-data-event-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSampleBuffer no-data event constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffer-no-data-event-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferAttachment-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferAttachment-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSampleBuffer attachment constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebufferattachment-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSelectorControl properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioselectorcontrol-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Subclass-IDs": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Subclass-IDs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSelectorControl subclass IDs",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioselectorcontrol-subclass-ids"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOStream constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostream-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOStream properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostream-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSystemObject constants",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosystemobject-constants"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Properties": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMIOSystemObject properties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosystemobject-properties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in data types",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-data-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in errors",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-errors"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in functions",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-functions"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in structures",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-structures"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePlugInInterfaceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePlugInInterfaceID"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePlugInInterfaceID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOHardwarePlugInInterfaceID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwareplugininterfaceid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePlugInTypeID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePlugInTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePlugInTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOHardwarePlugInTypeID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwareplugintypeid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOInvalidSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOInvalidSequenceNumber"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOInvalidSequenceNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOInvalidSequenceNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioinvalidsequencenumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Property-Wildcard-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferAttachment-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-No-data-event-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-Discontinuity-flag-constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Subclass-IDs",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Properties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Constants",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Properties"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOAVCDeviceType-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOBooleanControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Base-Class-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckShuttle-Speed-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckState-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeckStatus-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevice-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCSignal-mode-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODevicePropertyLocation-Values",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExposureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOFeatureControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObject-Property-Wildcard-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOPlugIn-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferAttachment-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-No-data-event-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBuffer-Discontinuity-flag-constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSelectorControl-Subclass-IDs",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStream-Properties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Constants",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSystemObject-Properties"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macro-based-constants",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePlugInInterfaceID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePlugInTypeID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOInvalidSequenceNumber"
              ],
              "title": "Macro-based constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/core-media-i-o-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/core-media-i-o-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
