{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DAL plug-in structures"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceAVCCommand"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceAVCCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceavccommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceRS422Command"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceRS422Command"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceRS422Command",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicers422command"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceSMPTETimeCallback",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicesmptetimecallback"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStreamConfiguration",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestreamconfiguration"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOHardwarePlugInInterface"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOHardwarePlugInInterface",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiohardwareplugininterface"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectpropertyaddress"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeck"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeck"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeck",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeck"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamscheduledoutputnotificationprocandrefcon"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in data types",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-data-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in errors",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-errors"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in functions",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-functions"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceAVCCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceRS422Command",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStreamConfiguration",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertyAddress",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeck",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOHardwarePlugInInterface"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/title",
          "value": "CMIOObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/title",
          "value": "CMIODeviceStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/title",
          "value": "CMIODeviceRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceRS422Command/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/title",
          "value": "CMIOStreamDeck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeck/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/title",
          "value": "CMIODeviceSMPTETimeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/title",
          "value": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/title",
          "value": "CMIODeviceAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceAVCCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceAVCCommand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/core-media-i-o-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/core-media-i-o-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
