{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DAL plug-in functions"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessAVCCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIODeviceAVCCommand",
          "text": "CMIODeviceAVCCommand"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceProcessAVCCommand(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceprocessavccommand(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessRS422Command"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIODeviceRS422Command",
          "text": "CMIODeviceRS422Command"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceProcessRS422Command"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceProcessRS422Command(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodeviceprocessrs422command(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStartStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStartStream"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStartStream(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestartstream(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceStopStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceID",
          "text": "CMIODeviceID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceStopStream"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceStopStream(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicestopstream(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODiscontinuityFlagsHaveHardDiscontinuities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIODiscontinuityFlagsHaveHardDiscontinuities"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODiscontinuityFlagsHaveHardDiscontinuities",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIODiscontinuityFlagsHaveHardDiscontinuities",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodiscontinuityflagshaveharddiscontinuities"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOGetNextSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOGetNextSequenceNumber"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOGetNextSequenceNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOGetNextSequenceNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiogetnextsequencenumber"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerProc",
          "text": "CMIOObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectAddPropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectaddpropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerBlock",
          "text": "CMIOObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectAddPropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectaddpropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOObjectCreate"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOObjectCreate",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectcreate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectgetpropertydata(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectGetPropertyDataSize"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectgetpropertydatasize(_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectHasProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectHasProperty"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectHasProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjecthasproperty(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectIsPropertySettable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectIsPropertySettable"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectIsPropertySettable(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectispropertysettable(_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertiesChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOObjectPropertiesChanged"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertiesChanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOObjectPropertiesChanged",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectpropertieschanged"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerProc",
          "text": "CMIOObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListener"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectRemovePropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectremovepropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectPropertyListenerBlock",
          "text": "CMIOObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectRemovePropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectremovepropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectSetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CMIOObjectPropertyAddress",
          "text": "CMIOObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectSetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectsetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOObjectShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOObjectID",
          "text": "CMIOObjectID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOObjectShow"
        }
      ],
      "role": "symbol",
      "title": "CMIOObjectShow(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectshow(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectsPublishedAndDied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOObjectsPublishedAndDied"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectsPublishedAndDied",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOObjectsPublishedAndDied",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioobjectspublishedanddied"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCopyNonRequiredAttachments"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCopyNonRequiredAttachments",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercopynonrequiredattachments"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopySampleAttachments": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCopySampleAttachments"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopySampleAttachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCopySampleAttachments",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercopysampleattachments"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCreate"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCreate",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercreate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreateForImageBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCreateForImageBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreateForImageBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCreateForImageBuffer",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercreateforimagebuffer"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreateNoDataMarker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferCreateNoDataMarker"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreateNoDataMarker",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferCreateNoDataMarker",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffercreatenodatamarker"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferGetDiscontinuityFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferGetDiscontinuityFlags"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferGetDiscontinuityFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferGetDiscontinuityFlags",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffergetdiscontinuityflags"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferGetSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferGetSequenceNumber"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferGetSequenceNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferGetSequenceNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffergetsequencenumber"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferSetDiscontinuityFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferSetDiscontinuityFlags"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferSetDiscontinuityFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferSetDiscontinuityFlags",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffersetdiscontinuityflags"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferSetSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMIOSampleBufferSetSequenceNumber"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferSetSequenceNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMIOSampleBufferSetSequenceNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiosamplebuffersetsequencenumber"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamClockConvertHostTimeToDeviceTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamClockConvertHostTimeToDeviceTime"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamclockconverthosttimetodevicetime(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockCreate(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamClockCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockCreate(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamClockCreate"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamClockCreate(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamclockcreate(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockInvalidate(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamClockInvalidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockInvalidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamClockInvalidate"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamClockInvalidate(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamclockinvalidate(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockPostTimingEvent(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamClockPostTimingEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockPostTimingEvent(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamClockPostTimingEvent"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamClockPostTimingEvent(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamclockposttimingevent(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamCopyBufferQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceStreamQueueAlteredProc",
          "text": "CMIODeviceStreamQueueAlteredProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSimpleQueueRef",
          "text": "CMSimpleQueue"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamCopyBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamCopyBufferQueue(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamcopybufferqueue(_:_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckCueTo(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckCueTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckCueTo(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckCueTo"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeckCueTo(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeckcueto(_:_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckJog(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckJog"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckJog(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckJog"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeckJog(_:_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeckjog(_:_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckPlay(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckPlay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckPlay(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckPlay"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeckPlay(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeckplay(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckStop(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamID",
          "text": "CMIOStreamID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamDeckStop"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamDeckStop(_:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamdeckstop(_:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in data types",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-data-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in errors",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-errors"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in structures",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-structures"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockCreate(_:_:_:_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockInvalidate(_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockPostTimingEvent(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckCueTo(_:_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckJog(_:_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckPlay(_:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckStop(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessAVCCommand(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceProcessRS422Command(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStartStream(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceStopStream(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListener(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectAddPropertyListenerBlock(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectGetPropertyDataSize(_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectHasProperty(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectIsPropertySettable(_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListener(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectSetPropertyData(_:_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectShow(_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopyNonRequiredAttachments",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCopySampleAttachments",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreate",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreateForImageBuffer",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferCreateNoDataMarker",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferGetDiscontinuityFlags",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferGetSequenceNumber",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferSetDiscontinuityFlags",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOSampleBufferSetSequenceNumber",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockCreate(_:_:_:_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockInvalidate(_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamClockPostTimingEvent(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamCopyBufferQueue(_:_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckCueTo(_:_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckJog(_:_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckPlay(_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamDeckStop(_:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectCreate",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectPropertiesChanged",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOObjectsPublishedAndDied"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODiscontinuityFlagsHaveHardDiscontinuities",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOGetNextSequenceNumber"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckStop(_:)/title",
          "value": "CMIOStreamDeckStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckStop(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeckStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockInvalidate(_:)/title",
          "value": "CMIOStreamClockInvalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockInvalidate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamClockInvalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectShow(_:)/title",
          "value": "CMIOObjectShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectShow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListener(_:_:_:_:)/title",
          "value": "CMIOObjectRemovePropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectRemovePropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)/title",
          "value": "CMIOObjectGetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyData(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectGetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStopStream(_:_:)/title",
          "value": "CMIODeviceStopStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStopStream(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStopStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamCopyBufferQueue(_:_:_:_:)/title",
          "value": "CMIOStreamCopyBufferQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamCopyBufferQueue(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamCopyBufferQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectHasProperty(_:_:)/title",
          "value": "CMIOObjectHasProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectHasProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectHasProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStartStream(_:_:)/title",
          "value": "CMIODeviceStartStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceStartStream(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceStartStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListenerBlock(_:_:_:_:)/title",
          "value": "CMIOObjectAddPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectAddPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessAVCCommand(_:_:)/title",
          "value": "CMIODeviceProcessAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessAVCCommand(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceProcessAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckPlay(_:)/title",
          "value": "CMIOStreamDeckPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckPlay(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeckPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckCueTo(_:_:_:)/title",
          "value": "CMIOStreamDeckCueTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckCueTo(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeckCueTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockCreate(_:_:_:_:_:_:_:)/title",
          "value": "CMIOStreamClockCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockCreate(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamClockCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyDataSize(_:_:_:_:_:)/title",
          "value": "CMIOObjectGetPropertyDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectGetPropertyDataSize(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectGetPropertyDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckJog(_:_:)/title",
          "value": "CMIOStreamDeckJog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamDeckJog(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamDeckJog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectIsPropertySettable(_:_:_:)/title",
          "value": "CMIOObjectIsPropertySettable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectIsPropertySettable(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectIsPropertySettable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)/title",
          "value": "CMIOObjectRemovePropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectRemovePropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectRemovePropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectSetPropertyData(_:_:_:_:_:_:)/title",
          "value": "CMIOObjectSetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectSetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectSetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)/title",
          "value": "CMIOStreamClockConvertHostTimeToDeviceTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockConvertHostTimeToDeviceTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamClockConvertHostTimeToDeviceTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessRS422Command(_:_:)/title",
          "value": "CMIODeviceProcessRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceProcessRS422Command(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceProcessRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockPostTimingEvent(_:_:_:_:)/title",
          "value": "CMIOStreamClockPostTimingEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamClockPostTimingEvent(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamClockPostTimingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListener(_:_:_:_:)/title",
          "value": "CMIOObjectAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOObjectAddPropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOObjectAddPropertyListener"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/core-media-i-o-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/core-media-i-o-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
