{
  "abstract": [
    {
      "text": "API reference for legacy DAL plug-ins.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "role": "collectionGroup",
    "title": "Device Abstraction Layer (DAL) Plug-Ins"
  },
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in data types",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-data-types"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in enumerations",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-enumerations"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in errors",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-errors"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in functions",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-functions"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAL plug-in structures",
      "type": "topic",
      "url": "/documentation/coremediaio/core-media-i-o-structures"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-structures",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-functions",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-enumerations",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-data-types",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/core-media-i-o-errors"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
