{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOBlackLevelControlClassID@kCMIOPanTiltRelativeControlClassID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOPanTiltRelativeControlClassID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOPanTiltRelativeControlClassID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOPanTiltRelativeControlClassID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOPanTiltRelativeControlClassID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOBacklightCompensationControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOBacklightCompensationControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOBacklightCompensationControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiobacklightcompensationcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOBlackLevelControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOBlackLevelControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOBlackLevelControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioblacklevelcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOBrightnessControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOBrightnessControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOBrightnessControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiobrightnesscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOContrastControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOContrastControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOContrastControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiocontrastcontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFocusControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFocusControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFocusControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofocuscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOGainControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOGainControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOGainControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiogaincontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOGammaControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOGammaControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOGammaControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiogammacontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHueControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHueControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHueControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohuecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOIrisControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOIrisControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOIrisControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioiriscontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIONoiseReductionControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIONoiseReductionControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIONoiseReductionControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmionoisereductioncontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOOpticalFilterClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOOpticalFilterClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOOpticalFilterClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioopticalfilterclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPanControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPanControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPanControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopancontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPanTiltRelativeControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanTiltRelativeControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPanTiltRelativeControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPanTiltRelativeControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopantiltrelativecontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOPowerLineFrequencyControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOPowerLineFrequencyControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOPowerLineFrequencyControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiopowerlinefrequencycontrolclassid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOSaturationControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOSaturationControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOSaturationControlClassID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosaturationcontrolclassid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOPanTiltRelativeControlClassID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPanTiltRelativeControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBacklightCompensationControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBlackLevelControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOBrightnessControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOContrastControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFocusControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGainControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOGammaControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHueControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOIrisControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIONoiseReductionControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOOpticalFilterClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPanControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOPowerLineFrequencyControlClassID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSaturationControlClassID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOPanTiltRelativeControlClassID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlClassID/title",
          "value": "kCMIOExposureControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOContrastControlClassID/title",
          "value": "kCMIOContrastControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOContrastControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOContrastControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBacklightCompensationControlClassID/title",
          "value": "kCMIOBacklightCompensationControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBacklightCompensationControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOBacklightCompensationControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOSaturationControlClassID/title",
          "value": "kCMIOSaturationControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOSaturationControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOSaturationControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFocusControlClassID/title",
          "value": "kCMIOFocusControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFocusControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFocusControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGammaControlClassID/title",
          "value": "kCMIOGammaControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGammaControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOGammaControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOIrisControlClassID/title",
          "value": "kCMIOIrisControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOIrisControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOIrisControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPowerLineFrequencyControlClassID/title",
          "value": "kCMIOPowerLineFrequencyControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPowerLineFrequencyControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPowerLineFrequencyControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanTiltRelativeControlClassID/title",
          "value": "kCMIOPanTiltRelativeControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanTiltRelativeControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPanTiltRelativeControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanControlClassID/title",
          "value": "kCMIOPanControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOPanControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOPanControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHueControlClassID/title",
          "value": "kCMIOHueControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHueControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHueControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBlackLevelControlClassID/title",
          "value": "kCMIOBlackLevelControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBlackLevelControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOBlackLevelControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGainControlClassID/title",
          "value": "kCMIOGainControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOGainControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOGainControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIONoiseReductionControlClassID/title",
          "value": "kCMIONoiseReductionControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIONoiseReductionControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIONoiseReductionControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBrightnessControlClassID/title",
          "value": "kCMIOBrightnessControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOBrightnessControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOBrightnessControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOOpticalFilterClassID/title",
          "value": "kCMIOOpticalFilterClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOOpticalFilterClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOOpticalFilterClassID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiopantiltrelativecontrolclassid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiopantiltrelativecontrolclassid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
