{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOStreamPropertyDirection@kCMIOStreamPropertyFormatDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOStreamPropertyFormatDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOStreamPropertyFormatDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOStreamPropertyFormatDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFormatDescription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyCanProcessDeckCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyCanProcessDeckCommand"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyCanProcessDeckCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertycanprocessdeckcommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyClock"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyClock",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyclock"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeck"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeck",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeck"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckCueing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckCueing"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckCueing",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckcueing"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckDropness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckDropness"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckDropness",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckdropness"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckFrameNumber"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckFrameNumber",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckframenumber"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckLocal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckLocal"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckLocal",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydecklocal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckThreaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeckThreaded"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeckThreaded",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydeckthreaded"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydevicesynctimeoutinmsec"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyDirection"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyDirection",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertydirection"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyEndOfData"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyEndOfData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyendofdata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyfirstoutputpresentationtimestamp"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFormatDescription",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyformatdescription"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFormatDescriptions"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFormatDescriptions",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyformatdescriptions"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRate"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFrameRate",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyframerate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRateRanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyFrameRateRanges"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyFrameRateRanges",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyframerateranges"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOStreamPropertyFormatDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyCanProcessDeckCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyClock",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeck",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckCueing",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckDropness",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckFrameNumber",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckLocal",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeckThreaded",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDeviceSyncTimeoutInMSec",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyDirection",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFirstOutputPresentationTimeStamp",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFormatDescriptions",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRate",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyFrameRateRanges"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOStreamPropertyFormatDescription"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescription/title",
          "value": "kCMIOStreamPropertyFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyClock/title",
          "value": "kCMIOStreamPropertyClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckFrameNumber/title",
          "value": "kCMIOStreamPropertyDeckFrameNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckFrameNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckFrameNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeck/title",
          "value": "kCMIOStreamPropertyDeck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckLocal/title",
          "value": "kCMIOStreamPropertyDeckLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckLocal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckThreaded/title",
          "value": "kCMIOStreamPropertyDeckThreaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckThreaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckThreaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyEndOfData/title",
          "value": "kCMIOStreamPropertyEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyEndOfData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRate/title",
          "value": "kCMIOStreamPropertyFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyCanProcessDeckCommand/title",
          "value": "kCMIOStreamPropertyCanProcessDeckCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyCanProcessDeckCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyCanProcessDeckCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckDropness/title",
          "value": "kCMIOStreamPropertyDeckDropness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckDropness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckDropness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescriptions/title",
          "value": "kCMIOStreamPropertyFormatDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFormatDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFormatDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFirstOutputPresentationTimeStamp/title",
          "value": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFirstOutputPresentationTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFirstOutputPresentationTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeviceSyncTimeoutInMSec/title",
          "value": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeviceSyncTimeoutInMSec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeviceSyncTimeoutInMSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckCueing/title",
          "value": "kCMIOStreamPropertyDeckCueing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDeckCueing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDeckCueing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRateRanges/title",
          "value": "kCMIOStreamPropertyFrameRateRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyFrameRateRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyFrameRateRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDirection/title",
          "value": "kCMIOStreamPropertyDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiostreampropertyformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiostreampropertyformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
