{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowScreenCaptureDevices"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOHardwarePropertyProcessIsMain@kCMIOHardwarePropertyAllowScreenCaptureDevices",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.10",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowScreenCaptureDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowScreenCaptureDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyAllowScreenCaptureDevices",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyallowscreencapturedevices"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyallowwirelessscreencapturedevices"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultInputDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDefaultInputDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultInputDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDefaultInputDevice"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyDefaultInputDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertydefaultinputdevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultOutputDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDefaultOutputDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultOutputDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDefaultOutputDevice"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyDefaultOutputDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertydefaultoutputdevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDeviceForUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDeviceForUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDeviceForUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDeviceForUID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyDeviceForUID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertydeviceforuid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyDevices"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyDevices",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertydevices"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyIsInitingOrExiting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyIsInitingOrExiting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyIsInitingOrExiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyIsInitingOrExiting"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyIsInitingOrExiting",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyisinitingorexiting"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyPlugInForBundleID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyPlugInForBundleID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyPlugInForBundleID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyPlugInForBundleID"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyPlugInForBundleID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertypluginforbundleid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyProcessIsMain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyProcessIsMain"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyProcessIsMain",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyprocessismain"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMaster": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyProcessIsMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyProcessIsMaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyProcessIsMaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyprocessismaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySleepingIsAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertySleepingIsAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySleepingIsAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertySleepingIsAllowed"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertySleepingIsAllowed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertysleepingisallowed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySuspendedBySystem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertySuspendedBySystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySuspendedBySystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertySuspendedBySystem"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertySuspendedBySystem",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertysuspendedbysystem"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUnloadingIsAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyUnloadingIsAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUnloadingIsAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyUnloadingIsAllowed"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyUnloadingIsAllowed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyunloadingisallowed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUserSessionIsActiveOrHeadless": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyUserSessionIsActiveOrHeadless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUserSessionIsActiveOrHeadless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwarePropertyUserSessionIsActiveOrHeadless"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwarePropertyUserSessionIsActiveOrHeadless",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarepropertyusersessionisactiveorheadless"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultInputDevice",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultOutputDevice",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDeviceForUID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDevices",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyIsInitingOrExiting",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyPlugInForBundleID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMain",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySleepingIsAllowed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySuspendedBySystem",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUnloadingIsAllowed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUserSessionIsActiveOrHeadless"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultInputDevice",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDefaultOutputDevice",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDeviceForUID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyDevices",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyIsInitingOrExiting",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyPlugInForBundleID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMain",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyProcessIsMaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySleepingIsAllowed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertySuspendedBySystem",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUnloadingIsAllowed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwarePropertyUserSessionIsActiveOrHeadless"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDefaultOutputDevice/title",
          "value": "kCMIOHardwarePropertyDefaultOutputDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDefaultOutputDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyDefaultOutputDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertySuspendedBySystem/title",
          "value": "kCMIOHardwarePropertySuspendedBySystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertySuspendedBySystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertySuspendedBySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyPlugInForBundleID/title",
          "value": "kCMIOHardwarePropertyPlugInForBundleID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyPlugInForBundleID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyPlugInForBundleID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDefaultInputDevice/title",
          "value": "kCMIOHardwarePropertyDefaultInputDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDefaultInputDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyDefaultInputDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertySleepingIsAllowed/title",
          "value": "kCMIOHardwarePropertySleepingIsAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertySleepingIsAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertySleepingIsAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyUnloadingIsAllowed/title",
          "value": "kCMIOHardwarePropertyUnloadingIsAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyUnloadingIsAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyUnloadingIsAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDeviceForUID/title",
          "value": "kCMIOHardwarePropertyDeviceForUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDeviceForUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyDeviceForUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyProcessIsMaster/title",
          "value": "kCMIOHardwarePropertyProcessIsMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyProcessIsMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyProcessIsMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyIsInitingOrExiting/title",
          "value": "kCMIOHardwarePropertyIsInitingOrExiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyIsInitingOrExiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyIsInitingOrExiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyUserSessionIsActiveOrHeadless/title",
          "value": "kCMIOHardwarePropertyUserSessionIsActiveOrHeadless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyUserSessionIsActiveOrHeadless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyUserSessionIsActiveOrHeadless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDevices/title",
          "value": "kCMIOHardwarePropertyDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyProcessIsMain/title",
          "value": "kCMIOHardwarePropertyProcessIsMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyProcessIsMain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyProcessIsMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyAllowScreenCaptureDevices/title",
          "value": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyAllowScreenCaptureDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyAllowScreenCaptureDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices/title",
          "value": "kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwarePropertyAllowWirelessScreenCaptureDevices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiohardwarepropertyallowscreencapturedevices"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiohardwarepropertyallowscreencapturedevices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
