{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOExposureControlPropertyRegionOfInterest@kCMIOExposureControlPropertyRegionOfInterest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOExposureControlPropertyRegionOfInterest"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOExposureControlPropertyRegionOfInterest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOExposureControlPropertyRegionOfInterest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyRegionOfInterest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyConvergenceSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyConvergenceSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyConvergenceSpeed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyconvergencespeed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyIntegrationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyIntegrationTime"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyIntegrationTime",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyintegrationtime"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyLockThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyLockThreshold"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyLockThreshold",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertylockthreshold"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyMaximumGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyMaximumGain"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyMaximumGain",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertymaximumgain"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyRegionOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyRegionOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyRegionOfInterest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyregionofinterest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStability"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyStability",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertystability"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyStable"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyStable",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertystable"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyTarget"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyTarget",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertytarget"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyUnlockThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOExposureControlPropertyUnlockThreshold"
        }
      ],
      "role": "symbol",
      "title": "kCMIOExposureControlPropertyUnlockThreshold",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioexposurecontrolpropertyunlockthreshold"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOExposureControlPropertyRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyConvergenceSpeed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyIntegrationTime",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyLockThreshold",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyMaximumGain",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStability",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyStable",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyTarget",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOExposureControlPropertyUnlockThreshold"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOExposureControlPropertyRegionOfInterest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStable/title",
          "value": "kCMIOExposureControlPropertyStable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyStable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyConvergenceSpeed/title",
          "value": "kCMIOExposureControlPropertyConvergenceSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyConvergenceSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyConvergenceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyMaximumGain/title",
          "value": "kCMIOExposureControlPropertyMaximumGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyMaximumGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyMaximumGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyIntegrationTime/title",
          "value": "kCMIOExposureControlPropertyIntegrationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyIntegrationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyIntegrationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyLockThreshold/title",
          "value": "kCMIOExposureControlPropertyLockThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyLockThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyLockThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyRegionOfInterest/title",
          "value": "kCMIOExposureControlPropertyRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyRegionOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyUnlockThreshold/title",
          "value": "kCMIOExposureControlPropertyUnlockThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyUnlockThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyUnlockThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStability/title",
          "value": "kCMIOExposureControlPropertyStability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyStability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyStability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyTarget/title",
          "value": "kCMIOExposureControlPropertyTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOExposureControlPropertyTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOExposureControlPropertyTarget"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmioexposurecontrolpropertyregionofinterest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmioexposurecontrolpropertyregionofinterest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
