{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOFeatureControlPropertyOnOff@kCMIOFeatureControlPropertyConvertAbsoluteToNative",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteNative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteNative"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteNative",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsolutenative"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteRange"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteRange",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsoluterange"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteUnitName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteUnitName"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteUnitName",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsoluteunitname"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAbsoluteValue"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAbsoluteValue",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyabsolutevalue"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAutomaticManual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyAutomaticManual"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyAutomaticManual",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyautomaticmanual"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertAbsoluteToNative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyConvertAbsoluteToNative",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyconvertabsolutetonative"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyConvertNativeToAbsolute",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyconvertnativetoabsolute"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeData"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativedata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeDataRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeDataRange"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeDataRange",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativedatarange"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeRange"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeRange",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativerange"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyNativeValue"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyNativeValue",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertynativevalue"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyOnOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyOnOff"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyOnOff",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertyonoff"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyTune"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOFeatureControlPropertyTune"
        }
      ],
      "role": "symbol",
      "title": "kCMIOFeatureControlPropertyTune",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiofeaturecontrolpropertytune"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteNative",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteRange",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteUnitName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAbsoluteValue",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyAutomaticManual",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyConvertNativeToAbsolute",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeRange",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeValue",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyOnOff",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyTune",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOFeatureControlPropertyNativeDataRange"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteValue/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAutomaticManual/title",
          "value": "kCMIOFeatureControlPropertyAutomaticManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAutomaticManual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAutomaticManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteUnitName/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteUnitName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteUnitName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteUnitName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeData/title",
          "value": "kCMIOFeatureControlPropertyNativeData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeValue/title",
          "value": "kCMIOFeatureControlPropertyNativeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeDataRange/title",
          "value": "kCMIOFeatureControlPropertyNativeDataRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeDataRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeDataRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertNativeToAbsolute/title",
          "value": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertNativeToAbsolute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyConvertNativeToAbsolute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertAbsoluteToNative/title",
          "value": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyConvertAbsoluteToNative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyConvertAbsoluteToNative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteNative/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteNative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteNative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteNative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteRange/title",
          "value": "kCMIOFeatureControlPropertyAbsoluteRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyAbsoluteRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyAbsoluteRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyTune/title",
          "value": "kCMIOFeatureControlPropertyTune"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyTune/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyTune"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeRange/title",
          "value": "kCMIOFeatureControlPropertyNativeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyNativeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyNativeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyOnOff/title",
          "value": "kCMIOFeatureControlPropertyOnOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOFeatureControlPropertyOnOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOFeatureControlPropertyOnOff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiofeaturecontrolpropertyconvertabsolutetonative"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiofeaturecontrolpropertyconvertabsolutetonative"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
