{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotRunningError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOHardwareNoError@kCMIOHardwareNotRunningError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOHardwareNotRunningError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOHardwareNotRunningError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOHardwareNotRunningError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOHardwareNotRunningError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePermissionsError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePermissionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePermissionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePermissionsError"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePermissionsError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepermissionserror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceUnsupportedFormatError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceUnsupportedFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceUnsupportedFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceUnsupportedFormatError"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceUnsupportedFormatError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceunsupportedformaterror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadDeviceError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadDeviceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadDeviceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadDeviceError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareBadDeviceError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarebaddeviceerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadObjectError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadObjectError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadObjectError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadObjectError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareBadObjectError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarebadobjecterror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadPropertySizeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarebadpropertysizeerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadStreamError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadStreamError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareBadStreamError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareBadStreamError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarebadstreamerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareIllegalOperationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareIllegalOperationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareIllegalOperationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareIllegalOperationError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareIllegalOperationError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwareillegaloperationerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNoError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareNoError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareNoError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarenoerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotRunningError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareNotRunningError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotRunningError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareNotRunningError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareNotRunningError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarenotrunningerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotStoppedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareNotStoppedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotStoppedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareNotStoppedError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareNotStoppedError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwarenotstoppederror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareSuspendedBySystemError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareSuspendedBySystemError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareSuspendedBySystemError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareSuspendedBySystemError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareSuspendedBySystemError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwaresuspendedbysystemerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnknownPropertyError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareUnknownPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnknownPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareUnknownPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareUnknownPropertyError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwareunknownpropertyerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnspecifiedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareUnspecifiedError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwareunspecifiederror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnsupportedOperationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOHardwareUnsupportedOperationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnsupportedOperationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOHardwareUnsupportedOperationError"
        }
      ],
      "role": "symbol",
      "title": "kCMIOHardwareUnsupportedOperationError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiohardwareunsupportedoperationerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePermissionsError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceUnsupportedFormatError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadDeviceError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadObjectError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadPropertySizeError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadStreamError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareIllegalOperationError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNoError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotStoppedError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareSuspendedBySystemError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnknownPropertyError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnspecifiedError",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnsupportedOperationError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOHardwareNotRunningError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareNotRunningError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePermissionsError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceUnsupportedFormatError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadDeviceError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadObjectError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadPropertySizeError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareBadStreamError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareIllegalOperationError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNoError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareNotStoppedError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareSuspendedBySystemError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnknownPropertyError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnspecifiedError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOHardwareUnsupportedOperationError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOHardwareNotRunningError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadObjectError/title",
          "value": "kCMIOHardwareBadObjectError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadObjectError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareBadObjectError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareNotStoppedError/title",
          "value": "kCMIOHardwareNotStoppedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareNotStoppedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareNotStoppedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceUnsupportedFormatError/title",
          "value": "kCMIODeviceUnsupportedFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceUnsupportedFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceUnsupportedFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareUnspecifiedError/title",
          "value": "kCMIOHardwareUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareUnsupportedOperationError/title",
          "value": "kCMIOHardwareUnsupportedOperationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareUnsupportedOperationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareUnsupportedOperationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareSuspendedBySystemError/title",
          "value": "kCMIOHardwareSuspendedBySystemError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareSuspendedBySystemError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareSuspendedBySystemError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareNoError/title",
          "value": "kCMIOHardwareNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadStreamError/title",
          "value": "kCMIOHardwareBadStreamError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadStreamError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareBadStreamError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareNotRunningError/title",
          "value": "kCMIOHardwareNotRunningError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareNotRunningError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareNotRunningError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadDeviceError/title",
          "value": "kCMIOHardwareBadDeviceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadDeviceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareBadDeviceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareIllegalOperationError/title",
          "value": "kCMIOHardwareIllegalOperationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareIllegalOperationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareIllegalOperationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadPropertySizeError/title",
          "value": "kCMIOHardwareBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareBadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareUnknownPropertyError/title",
          "value": "kCMIOHardwareUnknownPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOHardwareUnknownPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOHardwareUnknownPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePermissionsError/title",
          "value": "kCMIODevicePermissionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePermissionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePermissionsError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiohardwarenotrunningerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiohardwarenotrunningerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
