{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIODeviceAVCSignalModeSD525_60@kCMIODeviceAVCSignalModeSD525_60",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIODeviceAVCSignalModeSD525_60"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIODeviceAVCSignalModeSD525_60"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIODeviceAVCSignalModeSD525_60"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSD525_60"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalMode8mmNTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmode8mmntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalMode8mmPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalMode8mmPAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmode8mmpal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeAudio"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeAudio",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodeaudio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro100_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro100_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro100_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro100_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro100_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro25_525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro25_525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro25_625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro25_625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro50_525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro50_525_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVCPro50_625_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvcpro50_625_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVHS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeDVHS"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeDVHS",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodedvhs"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1125_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1125_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHD1125_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehd1125_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1250_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHD1250_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHD1250_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehd1250_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV1_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv1_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV1_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV1_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv1_60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV2_50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeHDV2_50"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeHDV2_50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodehdv2_50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSD525_60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeSD525_60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeviceAVCSignalModeSD525_60"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeviceAVCSignalModeSD525_60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeviceavcsignalmodesd525_60"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIODeviceAVCSignalModeSD525_60"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSD525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmNTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalMode8mmPAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeAudio",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro100_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro25_625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_525_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVCPro50_625_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeDVHS",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1125_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHD1250_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV1_60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeviceAVCSignalModeHDV2_50"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIODeviceAVCSignalModeSD525_60"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1250_50/title",
          "value": "kCMIODeviceAVCSignalModeHD1250_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1250_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHD1250_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSD525_60/title",
          "value": "kCMIODeviceAVCSignalModeSD525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeSD525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeSD525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1125_60/title",
          "value": "kCMIODeviceAVCSignalModeHD1125_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHD1125_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHD1125_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVHS/title",
          "value": "kCMIODeviceAVCSignalModeDVHS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVHS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVHS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_525_60/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro50_525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_60/title",
          "value": "kCMIODeviceAVCSignalModeHDV1_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV1_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeAudio/title",
          "value": "kCMIODeviceAVCSignalModeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_50/title",
          "value": "kCMIODeviceAVCSignalModeHDV1_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV1_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV1_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV2_50/title",
          "value": "kCMIODeviceAVCSignalModeHDV2_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeHDV2_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeHDV2_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_60/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro100_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro100_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmPAL/title",
          "value": "kCMIODeviceAVCSignalMode8mmPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalMode8mmPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_625_50/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro25_625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_525_60/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro25_525_60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro25_525_60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_50/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro100_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro100_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro100_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_625_50/title",
          "value": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalModeDVCPro50_625_50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalModeDVCPro50_625_50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmNTSC/title",
          "value": "kCMIODeviceAVCSignalMode8mmNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeviceAVCSignalMode8mmNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeviceAVCSignalMode8mmNTSC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiodeviceavcsignalmodesd525_60"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiodeviceavcsignalmodesd525_60"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
