{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyCreator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOObjectPropertyClass@kCMIOObjectPropertyCreator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOObjectPropertyCreator"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOObjectPropertyCreator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOObjectPropertyCreator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyCreator"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyClass"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyClass",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyclass"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyCreator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyCreator"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyCreator",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertycreator"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementCategoryName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementCategoryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementCategoryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementCategoryName"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyElementCategoryName",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyelementcategoryname"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementName"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyElementName",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyelementname"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementNumberName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementNumberName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementNumberName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyElementNumberName"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyElementNumberName",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyelementnumbername"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerAdded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyListenerAdded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyListenerAdded"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyListenerAdded",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertylisteneradded"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerRemoved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyListenerRemoved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyListenerRemoved"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyListenerRemoved",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertylistenerremoved"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyManufacturer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyManufacturer"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyManufacturer",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertymanufacturer"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyName"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyName",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyname"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwnedObjects": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyOwnedObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwnedObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyOwnedObjects"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyOwnedObjects",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyownedobjects"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyOwner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOObjectPropertyOwner"
        }
      ],
      "role": "symbol",
      "title": "kCMIOObjectPropertyOwner",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioobjectpropertyowner"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyClass",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementCategoryName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementNumberName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerAdded",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerRemoved",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyManufacturer",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyName",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwnedObjects",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwner"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOObjectPropertyCreator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyClass",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementCategoryName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyElementNumberName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerAdded",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyListenerRemoved",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyManufacturer",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyName",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwnedObjects",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOObjectPropertyOwner"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOObjectPropertyCreator"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyListenerAdded/title",
          "value": "kCMIOObjectPropertyListenerAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyListenerAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyListenerAdded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementNumberName/title",
          "value": "kCMIOObjectPropertyElementNumberName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementNumberName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyElementNumberName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyListenerRemoved/title",
          "value": "kCMIOObjectPropertyListenerRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyListenerRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyListenerRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyManufacturer/title",
          "value": "kCMIOObjectPropertyManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyClass/title",
          "value": "kCMIOObjectPropertyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementCategoryName/title",
          "value": "kCMIOObjectPropertyElementCategoryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementCategoryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyElementCategoryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyCreator/title",
          "value": "kCMIOObjectPropertyCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyName/title",
          "value": "kCMIOObjectPropertyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyOwner/title",
          "value": "kCMIOObjectPropertyOwner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyOwner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyOwner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementName/title",
          "value": "kCMIOObjectPropertyElementName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyElementName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyElementName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyOwnedObjects/title",
          "value": "kCMIOObjectPropertyOwnedObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOObjectPropertyOwnedObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOObjectPropertyOwnedObjects"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmioobjectpropertycreator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmioobjectpropertycreator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
