{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIOAVCDeviceType_Unknown@kCMIOAVCDeviceType_DVCPro_PAL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIOAVCDeviceType_DVCPro_PAL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIOAVCDeviceType_DVCPro_PAL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIOAVCDeviceType_DVCPro_PAL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro_PAL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_720p"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_720p"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro100_720p",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro100_720p"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro100_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro100_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro100_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro100_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro100_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro50_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro50_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro50_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro50_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro50_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCProHD_1080i50",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcprohd_1080i50"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCProHD_1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCProHD_1080i60",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcprohd_1080i60"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DVCPro_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DVCPro_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dvcpro_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DV_NTSC",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dv_ntsc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_DV_PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_DV_PAL",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_dv_pal"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_MPEG2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_MPEG2"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_MPEG2",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_mpeg2"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_Unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOAVCDeviceType_Unknown"
        }
      ],
      "role": "symbol",
      "title": "kCMIOAVCDeviceType_Unknown",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmioavcdevicetype_unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIOAVCDeviceType_DVCPro_PAL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_720p",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro100_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro50_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i50",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCProHD_1080i60",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DVCPro_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_NTSC",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_DV_PAL",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_MPEG2",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOAVCDeviceType_Unknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIOAVCDeviceType_DVCPro_PAL"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_Unknown/title",
          "value": "kCMIOAVCDeviceType_Unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_Unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_Unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_PAL/title",
          "value": "kCMIOAVCDeviceType_DVCPro_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i50/title",
          "value": "kCMIOAVCDeviceType_DVCProHD_1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCProHD_1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_NTSC/title",
          "value": "kCMIOAVCDeviceType_DVCPro_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_NTSC/title",
          "value": "kCMIOAVCDeviceType_DVCPro50_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro50_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_720p/title",
          "value": "kCMIOAVCDeviceType_DVCPro100_720p"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_720p/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro100_720p"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_NTSC/title",
          "value": "kCMIOAVCDeviceType_DVCPro100_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro100_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_MPEG2/title",
          "value": "kCMIOAVCDeviceType_MPEG2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_MPEG2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_MPEG2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_NTSC/title",
          "value": "kCMIOAVCDeviceType_DV_NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DV_NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_PAL/title",
          "value": "kCMIOAVCDeviceType_DV_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DV_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DV_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_PAL/title",
          "value": "kCMIOAVCDeviceType_DVCPro50_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro50_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro50_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_PAL/title",
          "value": "kCMIOAVCDeviceType_DVCPro100_PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCPro100_PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCPro100_PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i60/title",
          "value": "kCMIOAVCDeviceType_DVCProHD_1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOAVCDeviceType_DVCProHD_1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOAVCDeviceType_DVCProHD_1080i60"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmioavcdevicetype_dvcpro_pal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmioavcdevicetype_dvcpro_pal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
