{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIODeckShuttleReverseHighSpeed@kCMIODeckShuttlePause",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIODeckShuttlePause"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIODeckShuttlePause"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIODeckShuttlePause"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePause"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePause"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePause"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePause",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlepause"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlay1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlay1x"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlay1x",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplay1x"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFast"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayFast",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayfast"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayFaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayfaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFastest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayFastest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayFastest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayfastest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayHighSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayHighSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayHighSpeed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayhighspeed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayNextFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayNextFrame"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayNextFrame",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplaynextframe"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayPreviousFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlayPreviousFrame"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlayPreviousFrame",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplaypreviousframe"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow1"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlow1",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslow1"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow2"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlow2",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslow2"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlow3"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlow3",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslow3"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlowest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttlePlaySlowest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttlePlaySlowest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttleplayslowest"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverse1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverse1x"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverse1x",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereverse1x"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFast"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseFast",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversefast"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseFaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversefaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFastest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODeckShuttleReverseFastest"
        }
      ],
      "role": "symbol",
      "title": "kCMIODeckShuttleReverseFastest",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodeckshuttlereversefastest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIODeckShuttlePause"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlay1x",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFast",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayFastest",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayHighSpeed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayNextFrame",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlayPreviousFrame",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow1",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow2",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlow3",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttlePlaySlowest",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverse1x",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFast",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODeckShuttleReverseFastest"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIODeckShuttlePause"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePause/title",
          "value": "kCMIODeckShuttlePause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow2/title",
          "value": "kCMIODeckShuttlePlaySlow2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlow2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayNextFrame/title",
          "value": "kCMIODeckShuttlePlayNextFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayNextFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayNextFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow1/title",
          "value": "kCMIODeckShuttlePlaySlow1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlow1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlay1x/title",
          "value": "kCMIODeckShuttlePlay1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlay1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlay1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFaster/title",
          "value": "kCMIODeckShuttleReverseFaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseFaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFastest/title",
          "value": "kCMIODeckShuttlePlayFastest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFastest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayFastest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFaster/title",
          "value": "kCMIODeckShuttlePlayFaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayFaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFastest/title",
          "value": "kCMIODeckShuttleReverseFastest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFastest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseFastest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow3/title",
          "value": "kCMIODeckShuttlePlaySlow3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlow3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlow3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayHighSpeed/title",
          "value": "kCMIODeckShuttlePlayHighSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayHighSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayHighSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayPreviousFrame/title",
          "value": "kCMIODeckShuttlePlayPreviousFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayPreviousFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayPreviousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFast/title",
          "value": "kCMIODeckShuttlePlayFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlayFast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlayFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFast/title",
          "value": "kCMIODeckShuttleReverseFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverseFast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverseFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlowest/title",
          "value": "kCMIODeckShuttlePlaySlowest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttlePlaySlowest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttlePlaySlowest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverse1x/title",
          "value": "kCMIODeckShuttleReverse1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODeckShuttleReverse1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODeckShuttleReverse1x"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiodeckshuttlepause"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiodeckshuttlepause"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
