{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIODevicePropertyLocationUnknown@kCMIODevicePropertyLocationExternalDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIODevicePropertyLocationExternalDevice"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIODevicePropertyLocationExternalDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.13",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIODevicePropertyLocationExternalDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationExternalDevice"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationBuiltInDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationBuiltInDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationBuiltInDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationBuiltInDisplay"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLocationBuiltInDisplay",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylocationbuiltindisplay"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationExternalDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationExternalDevice"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLocationExternalDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylocationexternaldevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationExternalDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationExternalDisplay"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLocationExternalDisplay",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylocationexternaldisplay"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalWirelessDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationExternalWirelessDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalWirelessDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationExternalWirelessDevice"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLocationExternalWirelessDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylocationexternalwirelessdevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyLocationUnknown"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyLocationUnknown",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertylocationunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationBuiltInDisplay",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDisplay",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalWirelessDevice",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationUnknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIODevicePropertyLocationExternalDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationExternalDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationBuiltInDisplay",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalDisplay",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationExternalWirelessDevice",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyLocationUnknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIODevicePropertyLocationExternalDevice"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationUnknown/title",
          "value": "kCMIODevicePropertyLocationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationBuiltInDisplay/title",
          "value": "kCMIODevicePropertyLocationBuiltInDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationBuiltInDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationBuiltInDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationExternalDisplay/title",
          "value": "kCMIODevicePropertyLocationExternalDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationExternalDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationExternalDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationExternalWirelessDevice/title",
          "value": "kCMIODevicePropertyLocationExternalWirelessDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationExternalWirelessDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationExternalWirelessDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationExternalDevice/title",
          "value": "kCMIODevicePropertyLocationExternalDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyLocationExternalDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyLocationExternalDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiodevicepropertylocationexternaldevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiodevicepropertylocationexternaldevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
