{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMIODevicePropertyPlugIn@kCMIODevicePropertyCanProcessRS422Command",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMIODevicePropertyCanProcessRS422Command"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMIODevicePropertyCanProcessRS422Command"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMIODevicePropertyCanProcessRS422Command"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanProcessRS422Command"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceSignalMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceSignalMode"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyAVCDeviceSignalMode",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyavcdevicesignalmode"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyAVCDeviceType"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyAVCDeviceType",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyavcdevicetype"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessAVCCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessAVCCommand"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyCanProcessAVCCommand",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertycanprocessavccommand"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessRS422Command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessRS422Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanProcessRS422Command"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyCanProcessRS422Command",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertycanprocessrs422command"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertycanswitchframerateswithoutframedrops"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyClientSyncDiscontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyClientSyncDiscontinuity"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyClientSyncDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyclientsyncdiscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceCanBeDefaultDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicecanbedefaultdevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceHasChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceHasChanged"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceHasChanged",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicehaschanged"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsAlive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsAlive"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceIsAlive",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceisalive"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunning"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceIsRunning",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceisrunning"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunningSomewhere"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceIsRunningSomewhere"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceIsRunningSomewhere",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceisrunningsomewhere"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceMaster"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceMaster",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydevicemaster"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyDeviceUID",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertydeviceuid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyExcludeNonDALAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyExcludeNonDALAccess"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyExcludeNonDALAccess",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyexcludenondalaccess"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyHogMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyHogMode"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyHogMode",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyhogmode"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyIIDCCSRData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIODevicePropertyIIDCCSRData"
        }
      ],
      "role": "symbol",
      "title": "kCMIODevicePropertyIIDCCSRData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiodevicepropertyiidccsrdata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMIODevicePropertyCanProcessRS422Command"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanProcessRS422Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceSignalMode",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyAVCDeviceType",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanProcessAVCCommand",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyClientSyncDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceCanBeDefaultDevice",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceHasChanged",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsAlive",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunning",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceIsRunningSomewhere",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceMaster",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyDeviceUID",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyExcludeNonDALAccess",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyHogMode",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIODevicePropertyIIDCCSRData"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMIODevicePropertyCanProcessRS422Command"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceSignalMode/title",
          "value": "kCMIODevicePropertyAVCDeviceSignalMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceSignalMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyAVCDeviceSignalMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsAlive/title",
          "value": "kCMIODevicePropertyDeviceIsAlive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsAlive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceIsAlive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceType/title",
          "value": "kCMIODevicePropertyAVCDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyAVCDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyAVCDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops/title",
          "value": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanSwitchFrameRatesWithoutFrameDrops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyIIDCCSRData/title",
          "value": "kCMIODevicePropertyIIDCCSRData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyIIDCCSRData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyIIDCCSRData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceHasChanged/title",
          "value": "kCMIODevicePropertyDeviceHasChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceHasChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceHasChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyClientSyncDiscontinuity/title",
          "value": "kCMIODevicePropertyClientSyncDiscontinuity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyClientSyncDiscontinuity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyClientSyncDiscontinuity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessAVCCommand/title",
          "value": "kCMIODevicePropertyCanProcessAVCCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessAVCCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanProcessAVCCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunningSomewhere/title",
          "value": "kCMIODevicePropertyDeviceIsRunningSomewhere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunningSomewhere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceIsRunningSomewhere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyExcludeNonDALAccess/title",
          "value": "kCMIODevicePropertyExcludeNonDALAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyExcludeNonDALAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyExcludeNonDALAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunning/title",
          "value": "kCMIODevicePropertyDeviceIsRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceIsRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceIsRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyHogMode/title",
          "value": "kCMIODevicePropertyHogMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyHogMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyHogMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceMaster/title",
          "value": "kCMIODevicePropertyDeviceMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceCanBeDefaultDevice/title",
          "value": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceCanBeDefaultDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceCanBeDefaultDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceUID/title",
          "value": "kCMIODevicePropertyDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessRS422Command/title",
          "value": "kCMIODevicePropertyCanProcessRS422Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIODevicePropertyCanProcessRS422Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIODevicePropertyCanProcessRS422Command"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/kcmiodevicepropertycanprocessrs422command"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/kcmiodevicepropertycanprocessrs422command"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
