{
  "abstract": [
    {
      "text": "Mask for the font class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontSymbolicTraits@kCTFontTraitClassMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "traitClassMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
        "text": "CTFontSymbolicTraits"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontTraitClassMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "traitClassMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "traitClassMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
              "text": "CTFontSymbolicTraits"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits": {
      "abstract": [
        {
          "text": "The symbolic representation of stylistic font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "CTFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold": {
      "abstract": [
        {
          "text": "The font typestyle is boldface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitBold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitBold"
        }
      ],
      "role": "symbol",
      "title": "traitBold",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitbold"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask": {
      "abstract": [
        {
          "text": "Mask for the font class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitClassMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitClassMask"
        }
      ],
      "role": "symbol",
      "title": "traitClassMask",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitclassmask"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs": {
      "abstract": [
        {
          "text": "The font contains color glyphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitColorGlyphs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitColorGlyphs"
        }
      ],
      "role": "symbol",
      "title": "traitColorGlyphs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitcolorglyphs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite": {
      "abstract": [
        {
          "text": "The font is in Composite Font Reference format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitComposite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitComposite"
        }
      ],
      "role": "symbol",
      "title": "traitComposite",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitcomposite"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed": {
      "abstract": [
        {
          "text": "The font typestyle is condensed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitCondensed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitCondensed"
        }
      ],
      "role": "symbol",
      "title": "traitCondensed",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitcondensed"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded": {
      "abstract": [
        {
          "text": "The font typestyle is expanded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitExpanded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitExpanded"
        }
      ],
      "role": "symbol",
      "title": "traitExpanded",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitexpanded"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic": {
      "abstract": [
        {
          "text": "The font typestyle is italic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitItalic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitItalic"
        }
      ],
      "role": "symbol",
      "title": "traitItalic",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traititalic"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace": {
      "abstract": [
        {
          "text": "The font uses fixed-pitch glyphs if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitMonoSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitMonoSpace"
        }
      ],
      "role": "symbol",
      "title": "traitMonoSpace",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitmonospace"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized": {
      "abstract": [
        {
          "text": "The font synthesizes appropriate attributes for user interface rendering, such as control titles, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitUIOptimized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitUIOptimized"
        }
      ],
      "role": "symbol",
      "title": "traitUIOptimized",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traituioptimized"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitVertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitVertical"
        }
      ],
      "role": "symbol",
      "title": "traitVertical",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitvertical"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Symbolic-Traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite"
      ],
      "title": "Symbolic Traits"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontTraitClassMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitClassMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Symbolic-Traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite"
              ],
              "title": "Symbolic Traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontTraitClassMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitUIOptimized/title",
          "value": "kCTFontTraitUIOptimized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitUIOptimized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitUIOptimized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitColorGlyphs/title",
          "value": "kCTFontTraitColorGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitColorGlyphs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitColorGlyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitExpanded/title",
          "value": "kCTFontTraitExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitExpanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitComposite/title",
          "value": "kCTFontTraitComposite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitComposite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitComposite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/title",
          "value": "CTFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitItalic/title",
          "value": "kCTFontTraitItalic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitItalic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitItalic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitMonoSpace/title",
          "value": "kCTFontTraitMonoSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitMonoSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitMonoSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitBold/title",
          "value": "kCTFontTraitBold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitBold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitBold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitVertical/title",
          "value": "kCTFontTraitVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitVertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitClassMask/title",
          "value": "kCTFontTraitClassMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitClassMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitClassMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitCondensed/title",
          "value": "kCTFontTraitCondensed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitCondensed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitCondensed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontsymbolictraits/traitclassmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontsymbolictraits/traitclassmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
