{
  "abstract": [
    {
      "text": "The font uses vertical glyph variants and metrics.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontSymbolicTraits@kCTFontVerticalTrait",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "verticalTrait"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
        "text": "CTFontSymbolicTraits"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontVerticalTrait"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "verticalTrait"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "verticalTrait"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
              "text": "CTFontSymbolicTraits"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits": {
      "abstract": [
        {
          "text": "The symbolic representation of stylistic font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "CTFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait": {
      "abstract": [
        {
          "text": "The font typestyle is boldface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boldTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontBoldTrait"
        }
      ],
      "role": "symbol",
      "title": "boldTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/boldtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait": {
      "abstract": [
        {
          "text": "Mask for the font class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classMaskTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassMaskTrait"
        }
      ],
      "role": "symbol",
      "title": "classMaskTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/classmasktrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait": {
      "abstract": [
        {
          "text": "The font contains color glyphs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorGlyphsTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontColorGlyphsTrait"
        }
      ],
      "role": "symbol",
      "title": "colorGlyphsTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/colorglyphstrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait": {
      "abstract": [
        {
          "text": "The font is in Composite Font Reference format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositeTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCompositeTrait"
        }
      ],
      "role": "symbol",
      "title": "compositeTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/compositetrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait": {
      "abstract": [
        {
          "text": "The font typestyle is condensed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condensedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCondensedTrait"
        }
      ],
      "role": "symbol",
      "title": "condensedTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/condensedtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait": {
      "abstract": [
        {
          "text": "The font typestyle is expanded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expandedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontExpandedTrait"
        }
      ],
      "role": "symbol",
      "title": "expandedTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/expandedtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait": {
      "abstract": [
        {
          "text": "The font typestyle is italic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italicTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontItalicTrait"
        }
      ],
      "role": "symbol",
      "title": "italicTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/italictrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait": {
      "abstract": [
        {
          "text": "The font uses fixed-pitch glyphs if available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoSpaceTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMonoSpaceTrait"
        }
      ],
      "role": "symbol",
      "title": "monoSpaceTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/monospacetrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitVertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitVertical"
        }
      ],
      "role": "symbol",
      "title": "traitVertical",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitvertical"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait": {
      "abstract": [
        {
          "text": "The font synthesizes appropriate attributes for user interface rendering, such as control titles, if necessary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uiOptimizedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIOptimizedTrait"
        }
      ],
      "role": "symbol",
      "title": "uiOptimizedTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/uioptimizedtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVerticalTrait"
        }
      ],
      "role": "symbol",
      "title": "verticalTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/verticaltrait"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontVerticalTrait"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVerticalTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontVerticalTrait"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/title",
          "value": "CTFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitVertical/title",
          "value": "kCTFontTraitVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitVertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1italicTrait/title",
          "value": "kCTFontItalicTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1italicTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontItalicTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1boldTrait/title",
          "value": "kCTFontBoldTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1boldTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontBoldTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1verticalTrait/title",
          "value": "kCTFontVerticalTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1verticalTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVerticalTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1expandedTrait/title",
          "value": "kCTFontExpandedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1expandedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontExpandedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1compositeTrait/title",
          "value": "kCTFontCompositeTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1compositeTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCompositeTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1uiOptimizedTrait/title",
          "value": "kCTFontUIOptimizedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1uiOptimizedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIOptimizedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1colorGlyphsTrait/title",
          "value": "kCTFontColorGlyphsTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1colorGlyphsTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontColorGlyphsTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1monoSpaceTrait/title",
          "value": "kCTFontMonoSpaceTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1monoSpaceTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMonoSpaceTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1condensedTrait/title",
          "value": "kCTFontCondensedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1condensedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCondensedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1classMaskTrait/title",
          "value": "kCTFontClassMaskTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1classMaskTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassMaskTrait"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontsymbolictraits/verticaltrait"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontsymbolictraits/verticaltrait"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
