{
  "abstract": [
    {
      "text": "An error code that indicates the relay manager isn’t loaded.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationStale"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NERelayManagerError@NERelayManagerErrorConfigurationStale",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "configurationStale"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NERelayManagerErrorConfigurationStale"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NERelayManagerError.configurationStale"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationStale"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError": {
      "abstract": [
        {
          "text": "Error codes specific to relay managers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NERelayManagerError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NERelayManagerError"
        }
      ],
      "role": "symbol",
      "title": "NERelayManagerError",
      "type": "topic",
      "url": "/documentation/networkextension/nerelaymanagererror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationCannotBeRemoved": {
      "abstract": [
        {
          "text": "An error code that indicates removing the relay manager failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationCannotBeRemoved"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationCannotBeRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NERelayManagerErrorConfigurationCannotBeRemoved"
        }
      ],
      "role": "symbol",
      "title": "NERelayManagerError.configurationCannotBeRemoved",
      "type": "topic",
      "url": "/documentation/networkextension/nerelaymanagererror/configurationcannotberemoved"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationDisabled": {
      "abstract": [
        {
          "text": "An error code that indicates the relay manager isn’t enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDisabled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NERelayManagerErrorConfigurationDisabled"
        }
      ],
      "role": "symbol",
      "title": "NERelayManagerError.configurationDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/nerelaymanagererror/configurationdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the relay manager is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NERelayManagerErrorConfigurationInvalid"
        }
      ],
      "role": "symbol",
      "title": "NERelayManagerError.configurationInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nerelaymanagererror/configurationinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationStale": {
      "abstract": [
        {
          "text": "An error code that indicates the relay manager isn’t loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationStale"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationStale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NERelayManagerErrorConfigurationStale"
        }
      ],
      "role": "symbol",
      "title": "NERelayManagerError.configurationStale",
      "type": "topic",
      "url": "/documentation/networkextension/nerelaymanagererror/configurationstale"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationCannotBeRemoved"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NERelayManagerErrorConfigurationStale"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerErrorConfigurationStale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationInvalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationDisabled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NERelayManagerError/configurationCannotBeRemoved"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NERelayManagerErrorConfigurationStale"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationCannotBeRemoved/title",
          "value": "NERelayManagerErrorConfigurationCannotBeRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationCannotBeRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerErrorConfigurationCannotBeRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError/title",
          "value": "NERelayManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationInvalid/title",
          "value": "NERelayManagerErrorConfigurationInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerErrorConfigurationInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationDisabled/title",
          "value": "NERelayManagerErrorConfigurationDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerErrorConfigurationDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationStale/title",
          "value": "NERelayManagerErrorConfigurationStale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NERelayManagerError~1configurationStale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NERelayManagerErrorConfigurationStale"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nerelaymanagererror/configurationstale"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nerelaymanagererror/configurationstale"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
