{
  "abstract": [
    {
      "text": "Device-dependent color space with red, green, blue, and alpha components.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceRGB"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSDeviceRGBColorSpace",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deviceRGB"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSColorSpaceName",
        "text": "NSColorSpaceName"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDeviceRGBColorSpace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "deviceRGB"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceRGB"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSColorSpaceName",
              "text": "NSColorSpaceName"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can also create a color with HSB (hue, saturation, brightness) and alpha components and can extract these components.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName": {
      "abstract": [
        {
          "text": "Constants that specify color space names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceName"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpaceName",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB": {
      "abstract": [
        {
          "text": "Calibrated color space with red, green, blue, and alpha components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibratedRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCalibratedRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "calibratedRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/calibratedrgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite": {
      "abstract": [
        {
          "text": "Calibrated color space with white and alpha components (pure white is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibratedWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCalibratedWhiteColorSpace"
        }
      ],
      "role": "symbol",
      "title": "calibratedWhite",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/calibratedwhite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom": {
      "abstract": [
        {
          "text": "Custom ",
          "type": "text"
        },
        {
          "code": "NSColorSpace",
          "type": "codeVoice"
        },
        {
          "text": " object and floating-point components describing a color in that space",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCustomColorSpace"
        }
      ],
      "role": "symbol",
      "title": "custom",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/custom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK": {
      "abstract": [
        {
          "text": "Device-dependent color space with cyan, magenta, yellow, black, and alpha components",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceCMYKColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceCMYK",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicecmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceRGB": {
      "abstract": [
        {
          "text": "Device-dependent color space with red, green, blue, and alpha components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicergb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite": {
      "abstract": [
        {
          "text": "Device-dependent color space with white and alpha components (pure white is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceWhiteColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceWhite",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicewhite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/named": {
      "abstract": [
        {
          "text": "Catalog name and color name components",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/named",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNamedColorSpace"
        }
      ],
      "role": "symbol",
      "title": "named",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/named"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/pattern": {
      "abstract": [
        {
          "text": "Pattern image (tiled)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/pattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPatternColorSpace"
        }
      ],
      "role": "symbol",
      "title": "pattern",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/pattern"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-Space-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/named",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/pattern"
      ],
      "title": "Color Space Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDeviceRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-Space-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/named",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/pattern"
              ],
              "title": "Color Space Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSColorSpaceName",
                    "text": "NSColorSpaceName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDeviceRGBColorSpace"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1pattern/title",
          "value": "NSPatternColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1pattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPatternColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceRGB/title",
          "value": "NSDeviceRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1named/title",
          "value": "NSNamedColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1named/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNamedColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceCMYK/title",
          "value": "NSDeviceCMYKColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCMYKColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceWhite/title",
          "value": "NSDeviceWhiteColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceWhiteColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedRGB/title",
          "value": "NSCalibratedRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCalibratedRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName/title",
          "value": "NSColorSpaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedWhite/title",
          "value": "NSCalibratedWhiteColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCalibratedWhiteColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1custom/title",
          "value": "NSCustomColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomColorSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorspacename/devicergb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorspacename/devicergb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
