{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/managedObjectIDFromUTF8String:length:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPersistentStoreCoordinator(im)managedObjectIDFromUTF8String:length:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "managedObjectIDFromUTF8String:length:"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "managedObjectIDFromUTF8String:length:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "managedObjectIDFromUTF8String:length:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
              "text": "NSManagedObjectID"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "managedObjectIDFromUTF8String:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "utf8string"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "length:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "len"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectID": {
      "abstract": [
        {
          "text": "A compact, universal identifier for a managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectID"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectID"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectID",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectid"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/managedObjectIDFromUTF8String:length:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "managedObjectIDFromUTF8String:length:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/managedObjectIDFromUTF8String:length:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedObjectIDFromUTF8String:length:"
        }
      ],
      "role": "symbol",
      "title": "managedObjectIDFromUTF8String:length:",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/managedobjectidfromutf8string:length:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectID/title",
          "value": "NSManagedObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentstorecoordinator/managedobjectidfromutf8string:length:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
