{"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream/availableVirtualFormats","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/coreaudio/audiohardwarestream/availablevirtualformats"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableVirtualFormats","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@AudioStreamRangedDescription","text":"AudioStreamRangedDescription"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","modules":[{"name":"Core Audio"}],"externalID":"s:9CoreAudio0B14HardwareStreamC23availableVirtualFormatsSaySo0bD17RangedDescriptionVGvp","platforms":[{"beta":false,"name":"macOS","introducedAt":"15.0","unavailable":false,"deprecated":false}],"symbolKind":"property","title":"availableVirtualFormats"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableVirtualFormats","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@AudioStreamRangedDescription","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription","text":"AudioStreamRangedDescription","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioStreamRangedDescription"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioStreamRangedDescription"}],"title":"AudioStreamRangedDescription","type":"topic","url":"/documentation/coreaudio/audiostreamrangeddescription","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream/availableVirtualFormats":{"title":"availableVirtualFormats","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream/availableVirtualFormats","abstract":[],"url":"/documentation/coreaudio/audiohardwarestream/availablevirtualformats","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableVirtualFormats","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@AudioStreamRangedDescription","text":"AudioStreamRangedDescription"},{"kind":"text","text":"]"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioHardwareStream","kind":"identifier"}],"url":"/documentation/coreaudio/audiohardwarestream","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream","role":"symbol","title":"AudioHardwareStream","navigatorTitle":[{"text":"AudioHardwareStream","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"AudioStreamRangedDescription","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title"},{"value":[{"kind":"identifier","text":"AudioStreamRangedDescription"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments"},{"value":[{"kind":"identifier","text":"AudioStreamRangedDescription"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}