{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream"]]},"metadata":{"role":"symbol","title":"availablePhysicalFormats","externalID":"s:9CoreAudio0B14HardwareStreamC24availablePhysicalFormatsSaySo0bD17RangedDescriptionVGvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availablePhysicalFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@AudioStreamRangedDescription","text":"AudioStreamRangedDescription"},{"kind":"text","text":"]"}],"symbolKind":"property","roleHeading":"Instance Property","platforms":[{"introducedAt":"15.0","name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"modules":[{"name":"Core Audio"}]},"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream/availablePhysicalFormats","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/audiohardwarestream/availablephysicalformats"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availablePhysicalFormats","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@AudioStreamRangedDescription","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription","text":"AudioStreamRangedDescription","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioHardwareStream","kind":"identifier"}],"url":"/documentation/coreaudio/audiohardwarestream","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream","role":"symbol","title":"AudioHardwareStream","navigatorTitle":[{"text":"AudioHardwareStream","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioStreamRangedDescription"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioStreamRangedDescription"}],"title":"AudioStreamRangedDescription","type":"topic","url":"/documentation/coreaudio/audiostreamrangeddescription","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream/availablePhysicalFormats":{"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream/availablePhysicalFormats","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availablePhysicalFormats","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AudioStreamRangedDescription","preciseIdentifier":"c:@S@AudioStreamRangedDescription","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"kind":"symbol","title":"availablePhysicalFormats","url":"/documentation/coreaudio/audiohardwarestream/availablephysicalformats","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AudioStreamRangedDescription","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title"},{"value":[{"text":"AudioStreamRangedDescription","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments"},{"value":[{"text":"AudioStreamRangedDescription","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}