{
  "abstract": [
    {
      "text": "For every separate set of three vertices, rasterize a triangle. If the number of vertices is not a multiple of three, either one or two vertices is ignored.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPrimitiveType@MTLPrimitiveTypeTriangle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "triangle"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPrimitiveTypeTriangle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPrimitiveType.triangle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "triangle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType": {
      "abstract": [
        {
          "text": "The geometric primitive type for drawing commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPrimitiveType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveType"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveType",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitivetype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/line": {
      "abstract": [
        {
          "text": "Rasterize a line between each separate pair of vertices, resulting in a series of unconnected lines. If there are an odd number of vertices, the last vertex is ignored.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveTypeLine"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveType.line",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitivetype/line"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/lineStrip": {
      "abstract": [
        {
          "text": "Rasterize a line between each pair of adjacent vertices, resulting in a series of connected lines (also called a polyline).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineStrip"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/lineStrip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveTypeLineStrip"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveType.lineStrip",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitivetype/linestrip"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/point": {
      "abstract": [
        {
          "text": "Rasterize a point at each vertex. The vertex shader must provide ",
          "type": "text"
        },
        {
          "code": "[[point_size]]",
          "type": "codeVoice"
        },
        {
          "text": ", or the point size is undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "point"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/point",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveTypePoint"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveType.point",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitivetype/point"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangle": {
      "abstract": [
        {
          "text": "For every separate set of three vertices, rasterize a triangle. If the number of vertices is not a multiple of three, either one or two vertices is ignored.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangle"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveTypeTriangle"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveType.triangle",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitivetype/triangle"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangleStrip": {
      "abstract": [
        {
          "text": "For every three adjacent vertices, rasterize a triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleStrip"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangleStrip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveTypeTriangleStrip"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveType.triangleStrip",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitivetype/trianglestrip"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/point",
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/line",
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/lineStrip",
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangleStrip"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPrimitiveTypeTriangle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveTypeTriangle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/point",
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/line",
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/lineStrip",
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveType/triangleStrip"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPrimitiveTypeTriangle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1triangleStrip/title",
          "value": "MTLPrimitiveTypeTriangleStrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1triangleStrip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveTypeTriangleStrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1triangle/title",
          "value": "MTLPrimitiveTypeTriangle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1triangle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveTypeTriangle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType/title",
          "value": "MTLPrimitiveType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1line/title",
          "value": "MTLPrimitiveTypeLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveTypeLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1point/title",
          "value": "MTLPrimitiveTypePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1point/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveTypePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1lineStrip/title",
          "value": "MTLPrimitiveTypeLineStrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveType~1lineStrip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveTypeLineStrip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlprimitivetype/triangle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlprimitivetype/triangle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
