{
  "abstract": [
    {
      "text": "A type that represents trade items in varying quantity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeC"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNBarcodeCompositeType@VNBarcodeCompositeTypeGS1TypeC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gs1TypeC"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNBarcodeCompositeTypeGS1TypeC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VNBarcodeCompositeType.gs1TypeC"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gs1TypeC"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType": {
      "abstract": [
        {
          "text": "Composite types for barcode requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeType"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeType"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeCompositeType",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodecompositetype"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeA": {
      "abstract": [
        {
          "text": "A type that represents trade items in bulk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1TypeA"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeTypeGS1TypeA"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeCompositeType.gs1TypeA",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodecompositetype/gs1typea"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeB": {
      "abstract": [
        {
          "text": "A type that represents trade items by piece.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1TypeB"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeTypeGS1TypeB"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeCompositeType.gs1TypeB",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodecompositetype/gs1typeb"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeC": {
      "abstract": [
        {
          "text": "A type that represents trade items in varying quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1TypeC"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeTypeGS1TypeC"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeCompositeType.gs1TypeC",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodecompositetype/gs1typec"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/linked": {
      "abstract": [
        {
          "text": "A type that represents a linked composite type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linked"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/linked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeTypeLinked"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeCompositeType.linked",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodecompositetype/linked"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/none": {
      "abstract": [
        {
          "text": "A type that represents no composite type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeCompositeTypeNone"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeCompositeType.none",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodecompositetype/none"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Composite-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeA",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeB",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/linked",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/none"
      ],
      "title": "Composite Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNBarcodeCompositeTypeGS1TypeC"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeTypeGS1TypeC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Composite-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeA",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/gs1TypeB",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/linked",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeCompositeType/none"
              ],
              "title": "Composite Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VNBarcodeCompositeTypeGS1TypeC"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType/title",
          "value": "VNBarcodeCompositeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1gs1TypeC/title",
          "value": "VNBarcodeCompositeTypeGS1TypeC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1gs1TypeC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeTypeGS1TypeC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1linked/title",
          "value": "VNBarcodeCompositeTypeLinked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1linked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeTypeLinked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1gs1TypeA/title",
          "value": "VNBarcodeCompositeTypeGS1TypeA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1gs1TypeA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeTypeGS1TypeA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1none/title",
          "value": "VNBarcodeCompositeTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1gs1TypeB/title",
          "value": "VNBarcodeCompositeTypeGS1TypeB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeCompositeType~1gs1TypeB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeCompositeTypeGS1TypeB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnbarcodecompositetype/gs1typec"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnbarcodecompositetype/gs1typec"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
