{
  "abstract": [
    {
      "text": "The type of session used to record the sample.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/sessionGuidance-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRElectrocardiogramSession(py)sessionGuidance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sessionGuidance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRElectrocardiogramSession",
        "text": "SRElectrocardiogramSession"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SRElectrocardiogramSessionGuidance",
        "text": "SessionGuidance"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sessionGuidance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sessionGuidance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sessionGuidance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRElectrocardiogramSession",
              "text": "SRElectrocardiogramSession"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/SessionGuidance-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SRElectrocardiogramSessionGuidance",
              "text": "SessionGuidance"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession": {
      "abstract": [
        {
          "text": "An object that represents ECG data that a device records during a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRElectrocardiogramSession"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRElectrocardiogramSession"
        }
      ],
      "role": "symbol",
      "title": "SRElectrocardiogramSession",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsession"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/SessionGuidance-swift.enum": {
      "abstract": [
        {
          "text": "The type of session guidance used to record a ECG sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SessionGuidance"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/SessionGuidance-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SessionGuidance"
        }
      ],
      "role": "symbol",
      "title": "SRElectrocardiogramSession.SessionGuidance",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsession/sessionguidance-swift.enum"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/State-swift.enum": {
      "abstract": [
        {
          "text": "The state of a session used to record a ECG sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "SRElectrocardiogramSession.State",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsession/state-swift.enum"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/identifier": {
      "abstract": [
        {
          "text": "A unique identifier for the ECG session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsession/identifier"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/sessionGuidance-swift.property": {
      "abstract": [
        {
          "text": "The type of session used to record the sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionGuidance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRElectrocardiogramSession",
          "text": "SRElectrocardiogramSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRElectrocardiogramSessionGuidance",
          "text": "SessionGuidance"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/sessionGuidance-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sessionGuidance"
        }
      ],
      "role": "symbol",
      "title": "sessionGuidance",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsession/sessionguidance-swift.property"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/state-swift.property": {
      "abstract": [
        {
          "text": "The state of the session used to record the sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRElectrocardiogramSession",
          "text": "SRElectrocardiogramSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRElectrocardiogramSessionState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsession/state-swift.property"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-session-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/identifier",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/SessionGuidance-swift.enum",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/state-swift.property",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/State-swift.enum"
      ],
      "title": "Getting session information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sessionGuidance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sessionGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-session-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/identifier",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/SessionGuidance-swift.enum",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/state-swift.property",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/State-swift.enum"
              ],
              "title": "Getting session information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSession/SessionGuidance-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SRElectrocardiogramSessionGuidance",
                    "text": "SRElectrocardiogramSessionGuidance"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sessionGuidance"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1State-swift.enum/title",
          "value": "SRElectrocardiogramSessionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1SessionGuidance-swift.enum/title",
          "value": "SRElectrocardiogramSessionGuidance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1SessionGuidance-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSessionGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1SessionGuidance-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSessionGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession/title",
          "value": "SRElectrocardiogramSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1sessionGuidance-swift.property/title",
          "value": "sessionGuidance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSession~1sessionGuidance-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sessionGuidance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srelectrocardiogramsession/sessionguidance-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srelectrocardiogramsession/sessionguidance-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
