{
  "abstract": [
    {
      "text": "A behavior that shows an interface for performing an action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/genericAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INUIInteractiveBehavior@INUIInteractiveBehaviorGenericAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "genericAction"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INUIInteractiveBehaviorGenericAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INUIInteractiveBehavior.genericAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "genericAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior": {
      "abstract": [
        {
          "text": "Constants indicating how users are able to interact with your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehavior"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehavior"
        }
      ],
      "role": "symbol",
      "title": "INUIInteractiveBehavior",
      "type": "topic",
      "url": "/documentation/intentsui/inuiinteractivebehavior"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/genericAction": {
      "abstract": [
        {
          "text": "A behavior that shows an interface for performing an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericAction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/genericAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehaviorGenericAction"
        }
      ],
      "role": "symbol",
      "title": "INUIInteractiveBehavior.genericAction",
      "type": "topic",
      "url": "/documentation/intentsui/inuiinteractivebehavior/genericaction"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/launch": {
      "abstract": [
        {
          "text": "A behavior that displays an interface to launch the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/launch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehaviorLaunch"
        }
      ],
      "role": "symbol",
      "title": "INUIInteractiveBehavior.launch",
      "type": "topic",
      "url": "/documentation/intentsui/inuiinteractivebehavior/launch"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/nextView": {
      "abstract": [
        {
          "text": "A behavior that displays controls for navigating to a new view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextView"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/nextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehaviorNextView"
        }
      ],
      "role": "symbol",
      "title": "INUIInteractiveBehavior.nextView",
      "type": "topic",
      "url": "/documentation/intentsui/inuiinteractivebehavior/nextview"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/none": {
      "abstract": [
        {
          "text": "No interactions",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "INUIInteractiveBehavior.none",
      "type": "topic",
      "url": "/documentation/intentsui/inuiinteractivebehavior/none"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/none",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/nextView",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/launch"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INUIInteractiveBehaviorGenericAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehaviorGenericAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/none",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/nextView",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior/launch"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INUIInteractiveBehaviorGenericAction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior/title",
          "value": "INUIInteractiveBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1genericAction/title",
          "value": "INUIInteractiveBehaviorGenericAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1genericAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehaviorGenericAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1nextView/title",
          "value": "INUIInteractiveBehaviorNextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1nextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehaviorNextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1launch/title",
          "value": "INUIInteractiveBehaviorLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1launch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehaviorLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1none/title",
          "value": "INUIInteractiveBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehaviorNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuiinteractivebehavior/genericaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuiinteractivebehavior/genericaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
