{
  "abstract": [
    {
      "text": "Don’t draw a line.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/NSUnderlineStyleNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSUnderlineStyle@NSUnderlineStyleNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSUnderlineStyleNone"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnderlineStyleNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSUnderlineStyleNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/NSUnderlineStyleNone": {
      "abstract": [
        {
          "text": "Don’t draw a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/NSUnderlineStyleNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStyleNone",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/nsunderlinestylenone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/NSUnderlineStylePatternSolid": {
      "abstract": [
        {
          "text": "Draw a solid line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternSolid"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/NSUnderlineStylePatternSolid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStylePatternSolid",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/nsunderlinestylepatternsolid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/byWord": {
      "abstract": [
        {
          "text": "Draw the line only beneath or through words, not whitespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byWord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/byWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleByWord"
        }
      ],
      "role": "symbol",
      "title": "byWord",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/byword"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/double": {
      "abstract": [
        {
          "text": "Draw a double line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleDouble"
        }
      ],
      "role": "symbol",
      "title": "double",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/double"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDash": {
      "abstract": [
        {
          "text": "Draw a line of dashes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDash"
        }
      ],
      "role": "symbol",
      "title": "patternDash",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/patterndash"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDashDot": {
      "abstract": [
        {
          "text": "Draw a line of alternating dashes and dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDashDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDashDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDashDot"
        }
      ],
      "role": "symbol",
      "title": "patternDashDot",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/patterndashdot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDashDotDot": {
      "abstract": [
        {
          "text": "Draw a line of alternating dashes and two dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDashDotDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDashDotDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDashDotDot"
        }
      ],
      "role": "symbol",
      "title": "patternDashDotDot",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/patterndashdotdot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDot": {
      "abstract": [
        {
          "text": "Draw a line of dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDot"
        }
      ],
      "role": "symbol",
      "title": "patternDot",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/patterndot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/single": {
      "abstract": [
        {
          "text": "Draw a single line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "single"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/single",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleSingle"
        }
      ],
      "role": "symbol",
      "title": "single",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/single"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/thick": {
      "abstract": [
        {
          "text": "Draw a thick line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/thick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleThick"
        }
      ],
      "role": "symbol",
      "title": "thick",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle/thick"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-line-style",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/single",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/thick",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/double",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/NSUnderlineStylePatternSolid",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDot",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDash",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDashDot",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/patternDashDotDot",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle/byWord"
      ],
      "title": "Getting the line style"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDot/title",
          "value": "NSUnderlineStylePatternDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDashDot/title",
          "value": "NSUnderlineStylePatternDashDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDashDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDashDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1byWord/title",
          "value": "NSUnderlineStyleByWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1byWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleByWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1double/title",
          "value": "NSUnderlineStyleDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1single/title",
          "value": "NSUnderlineStyleSingle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1single/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleSingle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1thick/title",
          "value": "NSUnderlineStyleThick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1thick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleThick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDash/title",
          "value": "NSUnderlineStylePatternDash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDashDotDot/title",
          "value": "NSUnderlineStylePatternDashDotDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle~1patternDashDotDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDashDotDot"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsunderlinestyle/nsunderlinestylenone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
