{
  "abstract": [
    {
      "text": "Constants that defines metadata keys for a sequencer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@T@AVAudioSequencerInfoDictionaryKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "InfoDictionaryKey"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "InfoDictionaryKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVAudioSequencer.InfoDictionaryKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "InfoDictionaryKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer": {
      "abstract": [
        {
          "text": "An object that plays audio from a collection of MIDI events the system organizes into music tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSequencer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSequencer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey": {
      "abstract": [
        {
          "text": "Constants that defines metadata keys for a sequencer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InfoDictionaryKey"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSequencer.InfoDictionaryKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/ISRC": {
      "abstract": [
        {
          "text": "A key that represents the international standard recording code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ISRC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/ISRC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyISRC"
        }
      ],
      "role": "symbol",
      "title": "ISRC",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/isrc"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album": {
      "abstract": [
        {
          "text": "A key that represents the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyAlbum"
        }
      ],
      "role": "symbol",
      "title": "album",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/album"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/approximateDurationInSeconds": {
      "abstract": [
        {
          "text": "A key that represents the approximate duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "approximateDurationInSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/approximateDurationInSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyApproximateDurationInSeconds"
        }
      ],
      "role": "symbol",
      "title": "approximateDurationInSeconds",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/approximatedurationinseconds"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist": {
      "abstract": [
        {
          "text": "A key that represents the artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyArtist"
        }
      ],
      "role": "symbol",
      "title": "artist",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/artist"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/channelLayout": {
      "abstract": [
        {
          "text": "A key that represents the channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/channelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "channelLayout",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/channellayout"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments": {
      "abstract": [
        {
          "text": "A key that represents the comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyComments"
        }
      ],
      "role": "symbol",
      "title": "comments",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/comments"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer": {
      "abstract": [
        {
          "text": "A key that represents the composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyComposer"
        }
      ],
      "role": "symbol",
      "title": "composer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/composer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyCopyright"
        }
      ],
      "role": "symbol",
      "title": "copyright",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/copyright"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/encodingApplication": {
      "abstract": [
        {
          "text": "A key that represents the encoding application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodingApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/encodingApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyEncodingApplication"
        }
      ],
      "role": "symbol",
      "title": "encodingApplication",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/encodingapplication"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre": {
      "abstract": [
        {
          "text": "A key that represents the genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyGenre"
        }
      ],
      "role": "symbol",
      "title": "genre",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/genre"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the raw value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/keySignature": {
      "abstract": [
        {
          "text": "A key that represents the key signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keySignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/keySignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyKeySignature"
        }
      ],
      "role": "symbol",
      "title": "keySignature",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/keysignature"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist": {
      "abstract": [
        {
          "text": "A key that represents the lyricist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lyricist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyLyricist"
        }
      ],
      "role": "symbol",
      "title": "lyricist",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/lyricist"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/nominalBitRate": {
      "abstract": [
        {
          "text": "A key that represents the nominal bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalBitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/nominalBitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyNominalBitRate"
        }
      ],
      "role": "symbol",
      "title": "nominalBitRate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/nominalbitrate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/recordedDate": {
      "abstract": [
        {
          "text": "A key that represents the date of the recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/recordedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyRecordedDate"
        }
      ],
      "role": "symbol",
      "title": "recordedDate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/recordeddate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceBitDepth": {
      "abstract": [
        {
          "text": "A key that represents the bit depth of the source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceBitDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceBitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeySourceBitDepth"
        }
      ],
      "role": "symbol",
      "title": "sourceBitDepth",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/sourcebitdepth"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceEncoder": {
      "abstract": [
        {
          "text": "A key that represents the encoder the source uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceEncoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeySourceEncoder"
        }
      ],
      "role": "symbol",
      "title": "sourceEncoder",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/sourceencoder"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle": {
      "abstract": [
        {
          "text": "A key that represents the subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeySubTitle"
        }
      ],
      "role": "symbol",
      "title": "subTitle",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/subtitle"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/tempo": {
      "abstract": [
        {
          "text": "A key that represents the tempo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tempo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/tempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyTempo"
        }
      ],
      "role": "symbol",
      "title": "tempo",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/tempo"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/timeSignature": {
      "abstract": [
        {
          "text": "A key that represents the time signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/timeSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyTimeSignature"
        }
      ],
      "role": "symbol",
      "title": "timeSignature",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/timesignature"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title": {
      "abstract": [
        {
          "text": "A key that represents the title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyTitle"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/title"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber": {
      "abstract": [
        {
          "text": "A key that represents the track number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyTrackNumber"
        }
      ],
      "role": "symbol",
      "title": "trackNumber",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/tracknumber"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year": {
      "abstract": [
        {
          "text": "A key that represents the year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "year"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyYear"
        }
      ],
      "role": "symbol",
      "title": "year",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/year"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInBeats": {
      "abstract": [
        {
          "text": "The current playback position, in beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPositionInBeats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInBeats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPositionInBeats"
        }
      ],
      "role": "symbol",
      "title": "currentPositionInBeats",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/currentpositioninbeats"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInSeconds": {
      "abstract": [
        {
          "text": "The current playback position, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPositionInSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPositionInSeconds"
        }
      ],
      "role": "symbol",
      "title": "currentPositionInSeconds",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/currentpositioninseconds"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/data(withSMPTEResolution:error:)": {
      "abstract": [
        {
          "text": "Gets a data object that contains the events from the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withSMPTEResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/data(withSMPTEResolution:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataWithSMPTEResolution:error:"
        }
      ],
      "role": "symbol",
      "title": "data(withSMPTEResolution:error:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/data(withsmpteresolution:error:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/isPlaying": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the sequencer’s player is in a playing state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPlaying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/isPlaying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playing"
        }
      ],
      "role": "symbol",
      "title": "isPlaying",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/isplaying"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/rate": {
      "abstract": [
        {
          "text": "The playback rate of the sequencer’s player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rate"
        }
      ],
      "role": "symbol",
      "title": "rate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/rate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tempoTrack": {
      "abstract": [
        {
          "text": "The track that contains tempo information about the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tempoTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMusicTrack",
          "text": "AVMusicTrack"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tempoTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tempoTrack"
        }
      ],
      "role": "symbol",
      "title": "tempoTrack",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/tempotrack"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tracks": {
      "abstract": [
        {
          "text": "An array that contains all the tracks in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tracks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMusicTrack",
          "text": "AVMusicTrack"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tracks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tracks"
        }
      ],
      "role": "symbol",
      "title": "tracks",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/tracks"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/userInfo": {
      "abstract": [
        {
          "text": "A dictionary that contains metadata from a sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/userinfo"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMusicTimeStampEndOfTrack": {
      "abstract": [
        {
          "text": "A timestamp you use to access all events in a music track through a beat range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMusicTimeStampEndOfTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMusicTimeStampEndOfTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMusicTimeStampEndOfTrack"
        }
      ],
      "role": "symbol",
      "title": "AVMusicTimeStampEndOfTrack",
      "type": "topic",
      "url": "/documentation/avfaudio/avmusictimestampendoftrack"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Sequence-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/isPlaying",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/rate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tracks",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInBeats",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInSeconds",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tempoTrack",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/userInfo",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/data(withSMPTEResolution:error:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMusicTimeStampEndOfTrack"
      ],
      "title": "Getting Sequence Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Album-Details",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year"
      ],
      "title": "Getting Album Details"
    },
    {
      "anchor": "Getting-the-Duration-and-Time",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/approximateDurationInSeconds",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/timeSignature",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/tempo"
      ],
      "title": "Getting the Duration and Time"
    },
    {
      "anchor": "Getting-the-Recording-Date",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/recordedDate"
      ],
      "title": "Getting the Recording Date"
    },
    {
      "anchor": "Getting-Encoding-Information",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/encodingApplication",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceEncoder",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/nominalBitRate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceBitDepth",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/keySignature"
      ],
      "title": "Getting Encoding Information"
    },
    {
      "anchor": "Getting-the-Channel-Layout",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/channelLayout"
      ],
      "title": "Getting the Channel Layout"
    },
    {
      "anchor": "Getting-the-Recording-Code",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/ISRC"
      ],
      "title": "Getting the Recording Code"
    },
    {
      "anchor": "Creating-a-Dictionary-Key",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/init(rawValue:)"
      ],
      "title": "Creating a Dictionary Key"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSequencerInfoDictionaryKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Album-Details",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year"
              ],
              "title": "Getting Album Details"
            },
            {
              "anchor": "Getting-the-Duration-and-Time",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/approximateDurationInSeconds",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/timeSignature",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/tempo"
              ],
              "title": "Getting the Duration and Time"
            },
            {
              "anchor": "Getting-the-Recording-Date",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/recordedDate"
              ],
              "title": "Getting the Recording Date"
            },
            {
              "anchor": "Getting-Encoding-Information",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/encodingApplication",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceEncoder",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/nominalBitRate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/sourceBitDepth",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/keySignature"
              ],
              "title": "Getting Encoding Information"
            },
            {
              "anchor": "Getting-the-Channel-Layout",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/channelLayout"
              ],
              "title": "Getting the Channel Layout"
            },
            {
              "anchor": "Getting-the-Recording-Code",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/ISRC"
              ],
              "title": "Getting the Recording Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Sequence-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/isPlaying",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/rate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tracks",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInBeats",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/currentPositionInSeconds",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/tempoTrack",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/userInfo",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/data(withSMPTEResolution:error:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMusicTimeStampEndOfTrack"
              ],
              "title": "Getting Sequence Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioSequencerInfoDictionaryKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1tempoTrack/title",
          "value": "tempoTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1tempoTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tempoTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMusicTimeStampEndOfTrack/title",
          "value": "AVMusicTimeStampEndOfTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMusicTimeStampEndOfTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMusicTimeStampEndOfTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1sourceEncoder/title",
          "value": "AVAudioSequencerInfoDictionaryKeySourceEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1sourceEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeySourceEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1tracks/title",
          "value": "tracks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1tracks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tracks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1rate/title",
          "value": "rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1timeSignature/title",
          "value": "AVAudioSequencerInfoDictionaryKeyTimeSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1timeSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyTimeSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1title/title",
          "value": "AVAudioSequencerInfoDictionaryKeyTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1comments/title",
          "value": "AVAudioSequencerInfoDictionaryKeyComments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1comments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1sourceBitDepth/title",
          "value": "AVAudioSequencerInfoDictionaryKeySourceBitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1sourceBitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeySourceBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1ISRC/title",
          "value": "AVAudioSequencerInfoDictionaryKeyISRC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1ISRC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyISRC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1album/title",
          "value": "AVAudioSequencerInfoDictionaryKeyAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1recordedDate/title",
          "value": "AVAudioSequencerInfoDictionaryKeyRecordedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1recordedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyRecordedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1channelLayout/title",
          "value": "AVAudioSequencerInfoDictionaryKeyChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1channelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1data(withSMPTEResolution:error:)/title",
          "value": "dataWithSMPTEResolution:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1data(withSMPTEResolution:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dataWithSMPTEResolution:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer/title",
          "value": "AVAudioSequencer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1currentPositionInSeconds/title",
          "value": "currentPositionInSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1currentPositionInSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPositionInSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1copyright/title",
          "value": "AVAudioSequencerInfoDictionaryKeyCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1copyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1subTitle/title",
          "value": "AVAudioSequencerInfoDictionaryKeySubTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1subTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeySubTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1composer/title",
          "value": "AVAudioSequencerInfoDictionaryKeyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1nominalBitRate/title",
          "value": "AVAudioSequencerInfoDictionaryKeyNominalBitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1nominalBitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyNominalBitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey/title",
          "value": "AVAudioSequencerInfoDictionaryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1currentPositionInBeats/title",
          "value": "currentPositionInBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1currentPositionInBeats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPositionInBeats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1keySignature/title",
          "value": "AVAudioSequencerInfoDictionaryKeyKeySignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1keySignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyKeySignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1genre/title",
          "value": "AVAudioSequencerInfoDictionaryKeyGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1artist/title",
          "value": "AVAudioSequencerInfoDictionaryKeyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1trackNumber/title",
          "value": "AVAudioSequencerInfoDictionaryKeyTrackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1trackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyTrackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1approximateDurationInSeconds/title",
          "value": "AVAudioSequencerInfoDictionaryKeyApproximateDurationInSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1approximateDurationInSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyApproximateDurationInSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1tempo/title",
          "value": "AVAudioSequencerInfoDictionaryKeyTempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1tempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1isPlaying/title",
          "value": "playing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1isPlaying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1encodingApplication/title",
          "value": "AVAudioSequencerInfoDictionaryKeyEncodingApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1encodingApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyEncodingApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1lyricist/title",
          "value": "AVAudioSequencerInfoDictionaryKeyLyricist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1lyricist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyLyricist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1year/title",
          "value": "AVAudioSequencerInfoDictionaryKeyYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1year/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyYear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosequencer/infodictionarykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosequencer/infodictionarykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
