{
  "abstract": [
    {
      "text": "The format uses imperial units that include measurements in yards.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MKDistanceFormatterUnits@MKDistanceFormatterUnitsImperialWithYards",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imperialWithYards"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKDistanceFormatterUnitsImperialWithYards"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MKDistanceFormatter.Units.imperialWithYards"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imperialWithYards"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter": {
      "abstract": [
        {
          "text": "A utility object that converts between a geographic distance and a string-based expression of that distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKDistanceFormatter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatter"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum": {
      "abstract": [
        {
          "text": "Constants that reflect the type of units to use in the string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Units"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Units"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default": {
      "abstract": [
        {
          "text": "The format uses the locale information to determine which units to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsDefault"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.default",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/default"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial": {
      "abstract": [
        {
          "text": "The format uses imperial units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imperial"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsImperial"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.imperial",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/imperial"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards": {
      "abstract": [
        {
          "text": "The format uses imperial units that include measurements in yards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imperialWithYards"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsImperialWithYards"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.imperialWithYards",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/imperialwithyards"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric": {
      "abstract": [
        {
          "text": "The format uses metric units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metric"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsMetric"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.metric",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/metric"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKDistanceFormatterUnitsImperialWithYards"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsImperialWithYards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MKDistanceFormatterUnitsImperialWithYards"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/title",
          "value": "MKDistanceFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1metric/title",
          "value": "MKDistanceFormatterUnitsMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1metric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperialWithYards/title",
          "value": "MKDistanceFormatterUnitsImperialWithYards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperialWithYards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsImperialWithYards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperial/title",
          "value": "MKDistanceFormatterUnitsImperial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsImperial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum/title",
          "value": "MKDistanceFormatterUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1default/title",
          "value": "MKDistanceFormatterUnitsDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkdistanceformatter/units-swift.enum/imperialwithyards"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkdistanceformatter/units-swift.enum/imperialwithyards"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
