{
  "abstract": [
    {
      "text": "Perform your app’s actions from Control Center, the Lock Screen, and the Action button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.WidgetKit/documentation/WidgetKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-controls-to-perform-actions-across-the-system"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "creating-controls-to-perform-actions-PageImage-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "WidgetKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating controls to perform actions across the system"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A control allows your app to execute an action, launch your app to a specific view, or launch a locked camera capture extension from Control Center, the Lock Screen, or by using the Action button. Customers configure these system spaces with your app’s controls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Controls can be buttons or toggles: buttons perform an action, and toggles perform an action and switch between two states. Configure a control using SwiftUI views and modifiers that define strings and icons that the system uses to display the control. Anticipate people using controls from different places throughout the system, and provide appropriate configuration details for the best experience. For added privacy, require device authentication before a control performs its action, as well as redact the text in a control when the device is locked.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create your control’s icon using a symbol image, such as one from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/design/Human-Interface-Guidelines/sf-symbols",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Using symbols allows the system to dynamically apply tint color, weight, scale, and other stylistic traits. While Apple platforms include thousands of symbols, you can also build custom symbols. To learn more, read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/creating-custom-symbol-images-for-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Make controls configurable to allow someone to choose what it does. This ability is helpful in cases where a control can be configured with a list of options, such as which light to turn on or off.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-the-control-lifecycle",
          "level": 3,
          "text": "Understand the control lifecycle",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system loads a control when someone adds it to a system space from the controls gallery. A control updates when someone interacts with it, when the app asks to reload it using the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or when the system receives a remote push notification from the Apple Push Notification service (APNs). When the system loads or reloads a control, it runs the body of the control from the widget extension and asks for the control’s current value and content for the current state. The system updates the displayed control with these values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Controls provide their values to the system using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/AppIntentControlValueProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Providers require two functions: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider/previewValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider/currentValue()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". ",
              "type": "text"
            },
            {
              "code": "previewValue",
              "type": "codeVoice"
            },
            {
              "text": " prepares a canned synchronous value to show people when the control displays in the controls gallery. The controls gallery displays controls using their preview value and in their inactive state. The system fetches the ",
              "type": "text"
            },
            {
              "code": "currentValue()",
              "type": "codeVoice"
            },
            {
              "text": " when the control renders. The system fetches this value asynchronously, and gives you the opportunity to fetch the value from a shared data source or a server. Use a custom intent with ",
              "type": "text"
            },
            {
              "code": "AppIntentControlValueProvider",
              "type": "codeVoice"
            },
            {
              "text": " to provide options for a configurable control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When someone interacts with a control, it performs its action using an app intent you specify. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/OpenIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for control buttons and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/SetValueIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for control toggles. The app intent requires a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent/perform()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function  in which you carry out actions. The system queries for the state of a control when ",
              "type": "text"
            },
            {
              "code": "perform()",
              "type": "codeVoice"
            },
            {
              "text": " returns; finish all actions and save all state data before it returns.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may pass additional data into the app intent to ensure it successfully performs its action. The system preserves the data and makes it available in the ",
              "type": "text"
            },
            {
              "code": "perform()",
              "type": "codeVoice"
            },
            {
              "text": " function inside the app intent. Annotate additional data you pass in with ",
              "type": "text"
            },
            {
              "code": "@Parameter",
              "type": "codeVoice"
            },
            {
              "text": ". For more information on ",
              "type": "text"
            },
            {
              "code": "AppIntent",
              "type": "codeVoice"
            },
            {
              "text": ", refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system populates the value parameter of a ",
              "type": "text"
            },
            {
              "code": "SetValueIntent",
              "type": "codeVoice"
            },
            {
              "text": " with the value that reflects the new state of the control toggle. Don’t set or manage the value parameter. Update the internal state or model data to this value to remain consistent with the appearance of the control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-control-toggle-to-your-app",
          "level": 3,
          "text": "Add a control toggle to your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Widget Extension template provides all you need to start building your control. The template creates a widget extension target that contains a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetToggle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open your app project in Xcode and choose File > New > Target.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From the Application Extension group, select Widget Extension, and click Next.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter the name of your extension.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the Include Control checkbox.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Finish.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Live Activities use WidgetKit and share many aspects of their design and implementation with the widgets in your app. If your app would benefit from Live Activities, consider implementing them at the same time you add controls or widgets. For more information about Live Activities, read ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ActivityKit/displaying-live-data-with-live-activities",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The widget extension template provides an initial implementation of a ",
              "type": "text"
            },
            {
              "code": "ControlWidgetToggle",
              "type": "codeVoice"
            },
            {
              "text": ", a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ControlWidgetTemplate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type that starts and stops a timer. The body property determines if a control is static or configurable. Controls use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/StaticControlConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the body property by default. Provide people with the ability to configure a control by using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/AppIntentControlConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code creates a nonconfigurable control toggle that starts and stops a timer. The ",
              "type": "text"
            },
            {
              "code": "kind",
              "type": "codeVoice"
            },
            {
              "text": " is the control’s unique identifier and the action of the ",
              "type": "text"
            },
            {
              "code": "ControlWidgetToggle",
              "type": "codeVoice"
            },
            {
              "text": " executes the app intent specified:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct TimerToggle: ControlWidget {",
            "\tstatic let kind: String = \"com.example.MyApp.TimerToggle\"",
            "",
            "\tvar body: some ControlWidgetConfiguration {",
            "\t\tStaticControlConfiguration(",
            "\t\t\tkind: Self.kind,",
            "\t\t\tprovider: Provider()",
            "\t\t) { value in",
            "\t\t\tControlWidgetToggle(",
            "\t\t\t\t\"Productivity Timer\",",
            "\t\t\t\tisOn: value,",
            "\t\t\t\taction: ToggleTimerIntent(),",
            "\t\t\t\tvalueLabel: { isOn in",
            "\t\t\t\t\tLabel(isOn ? \"Running\" : \"Stopped\", systemImage: \"timer\")",
            "\t\t\t\t}",
            "\t\t\t)",
            "\t\t}",
            "\t\t.displayName(\"Productivity Timer\")",
            "\t\t.description(\"Start and stop a productivity timer.\")",
            "\t}",
            "}",
            "",
            "extension TimerToggle {",
            "\tstruct Provider: ControlValueProvider {",
            "\t\tvar previewValue: Bool {",
            "\t\t\tfalse",
            "\t\t}",
            "",
            "\t\tfunc currentValue() async throws -> Bool {",
            "\t\t\tlet isRunning = true // Check if the timer is running",
            "\t\t\treturn isRunning",
            "\t\t}",
            "\t}",
            "}",
            "",
            "struct ToggleTimerIntent: SetValueIntent {",
            "\tstatic var title: LocalizedStringResource = \"Productivity Timer\"",
            "",
            "\t@Parameter(title: \"Timer is running\")",
            "\tvar value: Bool",
            "",
            "\tfunc perform() async throws -> some IntentResult {",
            "\t\t// Start / stop the timer based on `value`.",
            "\t\treturn .result()",
            "\t}",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Create-a-button-control",
          "level": 3,
          "text": "Create a button control",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A control button performs an action from your app. For example, the button can launch a locked camera capture extension, start a live activity, or take someone to a specific area of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code creates a nonconfigurable ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that uses an app intent to perform an action:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct PerformActionButton: ControlWidget {",
            "\tvar body: some ControlWidgetConfiguration {",
            "\t\tStaticControlConfiguration(",
            "\t\t\tkind: \"com.example.myApp.performActionButton\"",
            "\t\t) {",
            "\t\t\tControlWidgetButton(action: PerformAction()) {",
            "                Label(\"Perform Action\", systemImage: \"checkmark.circle\")",
            "\t\t\t}",
            "\t\t}",
            "\t\t.displayName(\"Perform Action\")",
            "\t\t.description(\"An example control that performs an action.\")",
            "\t}",
            "}",
            "",
            "struct PerformAction: AppIntent {",
            "\tstatic let title: LocalizedStringResource = \"Perform action\"",
            "",
            "\tfunc perform() async throws -> some IntentResult {",
            "\t\t// Code that performs the action...",
            "\t\treturn .result()",
            "\t}",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Open-your-app-with-a-control",
          "level": 3,
          "text": "Open your app with a control",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set your control’s action to an app intent that conforms to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/OpenIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to open your app when someone uses a control. Using ",
              "type": "text"
            },
            {
              "code": "OpenIntent",
              "type": "codeVoice"
            },
            {
              "text": " allows you to take someone to a specific area of your app when a control performs its action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system requires the Target Membership of the app intent to be set to both the app and the widget extension to open the app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code uses an app intent to launch the app to a specific screen when a ",
              "type": "text"
            },
            {
              "code": "ControlWidgetButton",
              "type": "codeVoice"
            },
            {
              "text": " performs its action:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import AppIntents",
            "",
            "struct LaunchAppIntent: OpenIntent {",
            "    static var title: LocalizedStringResource = \"Launch App\"",
            "    @Parameter(title: \"Target\")",
            "    var target: LaunchAppEnum",
            "}",
            "",
            "enum LaunchAppEnum: String, AppEnum {",
            "    case timer",
            "    case history",
            "",
            "    static var typeDisplayRepresentation = TypeDisplayRepresentation(\"Productivity Timer's app screens\")",
            "    static var caseDisplayRepresentations = [",
            "        LaunchAppEnum.timer : DisplayRepresentation(\"Timer\"),",
            "        LaunchAppEnum.history : DisplayRepresentation(\"History\")",
            "    ]",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Use a control button to launch a locked camera capture extension. For more information about creating a locked camera capture extension, refer to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Add-controls-to-your-widget-bundle",
          "level": 3,
          "text": "Add controls to your widget bundle",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WidgetBundle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the Widget extension provides controls and widgets to the system from your app. List all controls and widgets inside the ",
              "type": "text"
            },
            {
              "code": "WidgetBundle",
              "type": "codeVoice"
            },
            {
              "text": ". The order of controls and widgets in the ",
              "type": "text"
            },
            {
              "code": "WidgetBundle",
              "type": "codeVoice"
            },
            {
              "text": " defines the order that the controls gallery and widgets gallery will display them in.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@main",
            "struct MyControlsAndWidgetsBundle: WidgetBundle {",
            "\tvar body: some Widget {",
            "\t\tPerformActionButton()",
            "\t\tMyAppWidget()",
            "\t\tMyAppControlToggle()",
            "\t}",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Locked-Camera-Capture-PageImage-card.png": {
      "alt": null,
      "identifier": "Locked-Camera-Capture-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3c2a77a54fb9667d1e58e1995951eb99/Locked-Camera-Capture-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/554cb5f26e2e6a1f759be4a76fdd33fd/Locked-Camera-Capture-PageImage-card@2x.png"
        }
      ]
    },
    "creating-controls-to-perform-actions-PageImage-card.png": {
      "alt": null,
      "identifier": "creating-controls-to-perform-actions-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/89b3200777246c98d3bbd28ebaaafe5b/creating-controls-to-perform-actions-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c63a545b551c9c7a56541562a57c11ab/creating-controls-to-perform-actions-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-refinements-and-configuration-to-controls": {
      "abstract": [
        {
          "text": "Customize the way controls display across the system and offer people the ability to configure them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-refinements-and-configuration-to-controls",
      "kind": "article",
      "role": "article",
      "title": "Adding refinements and configuration to controls",
      "type": "topic",
      "url": "/documentation/widgetkit/adding-refinements-and-configuration-to-controls"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/AppIntentControlConfiguration": {
      "abstract": [
        {
          "text": "The description of a control widget that uses a custom intent to provide",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "user-configurable options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppIntentControlConfiguration"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/AppIntentControlConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppIntentControlConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AppIntentControlConfiguration",
      "type": "topic",
      "url": "/documentation/widgetkit/appintentcontrolconfiguration"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/AppIntentControlValueProvider": {
      "abstract": [
        {
          "text": "A type that uses a custom intent to provide a value to a control template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppIntentControlValueProvider"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/AppIntentControlValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppIntentControlValueProvider"
        }
      ],
      "role": "symbol",
      "title": "AppIntentControlValueProvider",
      "type": "topic",
      "url": "/documentation/widgetkit/appintentcontrolvalueprovider"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter": {
      "abstract": [
        {
          "text": "An object that contains a list of user-configured controls and is used for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "reloading controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlCenter"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlCenter"
        }
      ],
      "role": "symbol",
      "title": "ControlCenter",
      "type": "topic",
      "url": "/documentation/widgetkit/controlcenter"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider": {
      "abstract": [
        {
          "text": "A type that provides a value to a control widget template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlValueProvider"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlValueProvider"
        }
      ],
      "role": "symbol",
      "title": "ControlValueProvider",
      "type": "topic",
      "url": "/documentation/widgetkit/controlvalueprovider"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider/currentValue()": {
      "abstract": [
        {
          "text": "The current value of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentValue"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit20ControlValueProviderP0D0Qa",
          "text": "Value"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider/currentValue()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "currentValue()",
      "type": "topic",
      "url": "/documentation/widgetkit/controlvalueprovider/currentvalue()"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider/previewValue": {
      "abstract": [
        {
          "text": "A value to be shown while previewing the control in the add sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit20ControlValueProviderP0D0Qa",
          "text": "Value"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlValueProvider/previewValue",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "previewValue",
      "type": "topic",
      "url": "/documentation/widgetkit/controlvalueprovider/previewvalue"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetButton": {
      "abstract": [
        {
          "text": "A control template representing a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlWidgetButton"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlWidgetButton"
        }
      ],
      "role": "symbol",
      "title": "ControlWidgetButton",
      "type": "topic",
      "url": "/documentation/widgetkit/controlwidgetbutton"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetToggle": {
      "abstract": [
        {
          "text": "A control template representing a toggle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlWidgetToggle"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetToggle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlWidgetToggle"
        }
      ],
      "role": "symbol",
      "title": "ControlWidgetToggle",
      "type": "topic",
      "url": "/documentation/widgetkit/controlwidgettoggle"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/StaticControlConfiguration": {
      "abstract": [
        {
          "text": "The description of a control widget that has no user-configurable options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StaticControlConfiguration"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/StaticControlConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StaticControlConfiguration"
        }
      ],
      "role": "symbol",
      "title": "StaticControlConfiguration",
      "type": "topic",
      "url": "/documentation/widgetkit/staticcontrolconfiguration"
    },
    "doc://com.apple.documentation/design/Human-Interface-Guidelines/sf-symbols": {
      "abstract": [
        {
          "text": "SF Symbols provides thousands of consistent, highly configurable symbols that integrate seamlessly with the San Francisco system font, automatically aligning with text in all weights and sizes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/design/Human-Interface-Guidelines/sf-symbols",
      "images": [
        {
          "identifier": "sf-symbols.svg",
          "type": "icon"
        },
        {
          "identifier": "foundations-sf-symbols-thumbnail.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "SF Symbols",
      "type": "topic",
      "url": "/design/Human-Interface-Guidelines/sf-symbols"
    },
    "doc://com.apple.documentation/documentation/ActivityKit/displaying-live-data-with-live-activities": {
      "abstract": [
        {
          "text": "Display your app’s data in the Dynamic Island and on the Lock Screen and offer quick interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ActivityKit/displaying-live-data-with-live-activities",
      "kind": "article",
      "role": "article",
      "title": "Displaying live data with Live Activities",
      "type": "topic",
      "url": "/documentation/ActivityKit/displaying-live-data-with-live-activities"
    },
    "doc://com.apple.documentation/documentation/AppIntents/AppIntent": {
      "abstract": [
        {
          "text": "An interface for providing an app-specific capability that people invoke from system experiences like Siri and the Shortcuts app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppIntent"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents24PersistentlyIdentifiableP",
          "text": "PersistentlyIdentifiable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "_SupportsAppDependencies"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppIntent",
      "type": "topic",
      "url": "/documentation/AppIntents/AppIntent"
    },
    "doc://com.apple.documentation/documentation/AppIntents/AppIntent/perform()": {
      "abstract": [
        {
          "text": "Performs the intent after resolving the provided parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents0A6IntentP13PerformResultQa",
          "text": "PerformResult"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent/perform()",
      "kind": "symbol",
      "role": "symbol",
      "title": "perform()",
      "type": "topic",
      "url": "/documentation/AppIntents/AppIntent/perform()"
    },
    "doc://com.apple.documentation/documentation/AppIntents/OpenIntent": {
      "abstract": [
        {
          "text": "Open the associated item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenIntent"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents12SystemIntentP",
          "text": "SystemIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppIntents/OpenIntent",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpenIntent",
      "type": "topic",
      "url": "/documentation/AppIntents/OpenIntent"
    },
    "doc://com.apple.documentation/documentation/AppIntents/SetValueIntent": {
      "abstract": [
        {
          "text": "An intent that contains a value which can be set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetValueIntent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents14SetValueIntentP0D4TypeQa",
          "text": "ValueType"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents0A6IntentP",
          "text": "AppIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppIntents/SetValueIntent",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetValueIntent",
      "type": "topic",
      "url": "/documentation/AppIntents/SetValueIntent"
    },
    "doc://com.apple.documentation/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen": {
      "abstract": [
        {
          "text": "Offer your app’s camera experience on locked devices from Control Center, the Lock Screen, and the Action button.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen",
      "images": [
        {
          "identifier": "Locked-Camera-Capture-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Creating a camera experience for the Lock Screen",
      "type": "topic",
      "url": "/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ControlWidgetTemplate": {
      "abstract": [
        {
          "text": "A type that describes a control widget’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlWidgetTemplate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ControlWidgetTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "ControlWidgetTemplate",
      "type": "topic",
      "url": "/documentation/SwiftUI/ControlWidgetTemplate"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/WidgetBundle": {
      "abstract": [
        {
          "text": "A container used to expose multiple widgets from a single widget extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetBundle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WidgetBundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "WidgetBundle",
      "type": "topic",
      "url": "/documentation/SwiftUI/WidgetBundle"
    },
    "doc://com.apple.documentation/documentation/UIKit/creating-custom-symbol-images-for-your-app": {
      "abstract": [
        {
          "text": "Create, organize, and annotate symbol images using SF Symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/creating-custom-symbol-images-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Creating custom symbol images for your app",
      "type": "topic",
      "url": "/documentation/UIKit/creating-custom-symbol-images-for-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "foundations-sf-symbols-thumbnail.png": {
      "alt": null,
      "identifier": "foundations-sf-symbols-thumbnail.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5cbaab2340c91ec558c8f0dc15966a82/foundations-sf-symbols-thumbnail@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e41d1c836c410f756940ced72ff5ec3/foundations-sf-symbols-thumbnail~dark@2x.png"
        }
      ]
    },
    "sf-symbols.svg": {
      "alt": null,
      "identifier": "sf-symbols.svg",
      "type": "image",
      "variants": [
        {
          "svgID": "sf-symbols",
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/889c48d0b4f0916dabff9890e12cff79/sf-symbols.svg"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-refinements-and-configuration-to-controls",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetToggle",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlWidgetButton",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter"
      ],
      "title": "Controls"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-refinements-and-configuration-to-controls"
              ],
              "title": "Controls"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/widgetkit/creating-controls-to-perform-actions-across-the-system"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/widgetkit/creating-controls-to-perform-actions-across-the-system"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
