{
  "abstract": [
    {
      "text": "Show up-to-date, time-based information in your widget even when it",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "isn’t running.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.WidgetKit/documentation/WidgetKit",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/SwiftUI-Views"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.WidgetKit/documentation/WidgetKit/Displaying-Dynamic-Dates"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WidgetKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Displaying dynamic dates in widgets"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because your widget extension isn’t always running, you can’t directly update",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your widget’s content. Instead, WidgetKit renders your widget’s view on your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "behalf and displays the result. However, some SwiftUI views let you display",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "content that continues updating while your widget is visible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view in your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "widget, you can display dates and times that stay up to date onscreen. The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "following examples show the combinations available.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display a relative time that updates automatically:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let components = DateComponents(minute: 11, second: 14)",
            "let futureDate = Calendar.current.date(byAdding: components, to: Date())!",
            "",
            "Text(futureDate, style: .relative)",
            "// Displays:",
            "// 11 min, 14 sec",
            "",
            "Text(futureDate, style: .offset)",
            "// Displays:",
            "// -11 minutes"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Using the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/relative",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "style shows the absolute difference between the current date and time and the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "date specified, regardless of whether the date is in the future or the past.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/offset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "style shows the difference between the current date and time and the date",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specified, indicating dates in the future with a minus sign (",
              "type": "text"
            },
            {
              "code": "-",
              "type": "codeVoice"
            },
            {
              "text": ") prefix and dates in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "past with a plus sign (",
              "type": "text"
            },
            {
              "code": "+",
              "type": "codeVoice"
            },
            {
              "text": ") prefix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display a timer that continues updating automatically:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let components = DateComponents(minute: 15)",
            "let futureDate = Calendar.current.date(byAdding: components, to: Date())!",
            "",
            "Text(futureDate, style: .timer)",
            "// Displays:",
            "// 15:00"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For dates in the future, the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/timer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "style counts down until the current time reaches the specified date and time,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and counts up when the date passes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display an absolute date or time:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Absolute Date or Time",
            "let components = DateComponents(year: 2020, month: 4, day: 1, hour: 9, minute: 41)",
            "let aprilFirstDate = Calendar.current(components)!",
            "",
            "Text(aprilFirstDate, style: .date)",
            "Text(\"Date: \\(aprilFirstDate, style: .date)\")",
            "Text(\"Time: \\(aprilFirstDate, style: .time)\")",
            "",
            "// Displays:",
            "// April 1, 2020",
            "// Date: April 1, 2020",
            "// Time: 9:41AM"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "And finally, to display a time interval between two dates:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let startComponents = DateComponents(hour: 9, minute: 30)",
            "let startDate = Calendar.current.date(from: startComponents)!",
            "",
            "let endComponents = DateComponents(hour: 14, minute: 45)",
            "let endDate = Calendar.current.date(from: endComponents)!",
            "",
            "Text(startDate ... endDate)",
            "Text(\"The meeting will take place: \\(startDate ... endDate)\")",
            "",
            "// Displays:",
            "// 9:30AM-2:45PM",
            "// The meeting will take place: 9:30AM-2:45PM"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.WidgetKit/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/SwiftUI-Views": {
      "abstract": [
        {
          "text": "Present your app’s content in widgets with SwiftUI views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/SwiftUI-Views",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SwiftUI views for widgets",
      "type": "topic",
      "url": "/documentation/widgetkit/swiftui-views"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
      "kind": "symbol",
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/offset": {
      "abstract": [
        {
          "text": "A style displaying a date as offset from now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/offset",
      "kind": "symbol",
      "role": "symbol",
      "title": "offset",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle/offset"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/relative": {
      "abstract": [
        {
          "text": "A style displaying a date as relative to now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/relative",
      "kind": "symbol",
      "role": "symbol",
      "title": "relative",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle/relative"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/timer": {
      "abstract": [
        {
          "text": "A style displaying a date as timer counting from now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/timer",
      "kind": "symbol",
      "role": "symbol",
      "title": "timer",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle/timer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Text"
      ],
      "title": "Displaying text"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displaying-text",
              "generated": true,
              "identifiers": [],
              "title": "Displaying text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/widgetkit/displaying-dynamic-dates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/widgetkit/displaying-dynamic-dates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
