{
  "abstract": [
    {
      "text": "Use Swift macros to create widget previews in Xcode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.WidgetKit/documentation/WidgetKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WidgetKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Preview macros"
  },
  "references": {
    "doc://com.apple.WidgetKit/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Debugging-Widgets": {
      "abstract": [
        {
          "text": "Set environment variables in Xcode to control your widget’s configuration in",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the debugger.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Debugging-Widgets",
      "kind": "article",
      "role": "article",
      "title": "Debugging Widgets",
      "type": "topic",
      "url": "/documentation/widgetkit/debugging-widgets"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:contentStates:)": {
      "abstract": [
        {
          "text": "Preview a widget with an activity configuration, using the specified attributes and content states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit23ActivityPreviewViewKindO",
          "text": "ActivityPreviewViewKind"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "widget"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentStates"
        },
        {
          "kind": "text",
          "text": ": () "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:11ActivityKit0A10AttributesP12ContentStateQa",
          "text": "ContentState"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:contentStates:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:as:using:widget:contentStates:)",
      "type": "topic",
      "url": "/documentation/widgetkit/preview(_:as:using:widget:contentstates:)"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:timelineProvider:)-3df1l": {
      "abstract": [
        {
          "text": "Preview a widget with an intent configuration, using the specified timeline provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A6FamilyO",
          "text": "WidgetFamily"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit22IntentTimelineProviderP0C0Qa",
          "text": "Intent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "widget"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timelineProvider"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:timelineProvider:)-3df1l",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:as:using:widget:timelineProvider:)",
      "type": "topic",
      "url": "/documentation/widgetkit/preview(_:as:using:widget:timelineprovider:)-3df1l"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:timelineProvider:)-4ljg1": {
      "abstract": [
        {
          "text": "Preview a widget with an app intent configuration, using the specified timeline provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A6FamilyO",
          "text": "WidgetFamily"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit25AppIntentTimelineProviderP0D0Qa",
          "text": "Intent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "widget"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timelineProvider"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:timelineProvider:)-4ljg1",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:as:using:widget:timelineProvider:)",
      "type": "topic",
      "url": "/documentation/widgetkit/preview(_:as:using:widget:timelineprovider:)-4ljg1"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:widget:timeline:)": {
      "abstract": [
        {
          "text": "Preview a timeline-style widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A6FamilyO",
          "text": "WidgetFamily"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "widget"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeline"
        },
        {
          "kind": "text",
          "text": ": () "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit13TimelineEntryP",
          "text": "TimelineEntry"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:widget:timeline:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:as:widget:timeline:)",
      "type": "topic",
      "url": "/documentation/widgetkit/preview(_:as:widget:timeline:)"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:widget:timelineProvider:)": {
      "abstract": [
        {
          "text": "Preview a widget with a static configuration, using the specified timeline provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A6FamilyO",
          "text": "WidgetFamily"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "widget"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Widget"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timelineProvider"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Provider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:widget:timelineProvider:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:as:widget:timelineProvider:)",
      "type": "topic",
      "url": "/documentation/widgetkit/preview(_:as:widget:timelineprovider:)"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/PreviewActivityBuilder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PreviewActivityBuilder"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/PreviewActivityBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PreviewActivityBuilder"
        }
      ],
      "role": "symbol",
      "title": "PreviewActivityBuilder",
      "type": "topic",
      "url": "/documentation/widgetkit/previewactivitybuilder"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/PreviewTimelineBuilder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PreviewTimelineBuilder"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/PreviewTimelineBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PreviewTimelineBuilder"
        }
      ],
      "role": "symbol",
      "title": "PreviewTimelineBuilder",
      "type": "topic",
      "url": "/documentation/widgetkit/previewtimelinebuilder"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Previewing-widgets-and-live-activities-in-xcode": {
      "abstract": [
        {
          "text": "Use Xcode previews to iteratively develop, fine-tune, and troubleshoot widgets and Live Activities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Previewing-widgets-and-live-activities-in-xcode",
      "kind": "article",
      "role": "article",
      "title": "Previewing widgets and Live Activities in Xcode",
      "type": "topic",
      "url": "/documentation/widgetkit/previewing-widgets-and-live-activities-in-xcode"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetPreviewContext": {
      "abstract": [
        {
          "text": "A specification for the context of a widget preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetPreviewContext"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetPreviewContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WidgetPreviewContext"
        }
      ],
      "role": "symbol",
      "title": "WidgetPreviewContext",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetpreviewcontext"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Widget-preview-and-debugging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Previewing-widgets-and-live-activities-in-xcode",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Debugging-Widgets",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetPreviewContext"
      ],
      "title": "Widget preview and debugging"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-a-widget-preview",
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:widget:timelineProvider:)",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:timelineProvider:)-4ljg1",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:timelineProvider:)-3df1l",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:widget:timeline:)"
      ],
      "title": "Providing a widget preview"
    },
    {
      "anchor": "Generating-a-Live-Activity-preview",
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Preview(_:as:using:widget:contentStates:)"
      ],
      "title": "Generating a Live Activity preview"
    },
    {
      "anchor": "Generated-structures",
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/PreviewActivityBuilder",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/PreviewTimelineBuilder"
      ],
      "title": "Generated structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Widget-preview-and-debugging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Previewing-widgets-and-live-activities-in-xcode",
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Debugging-Widgets"
              ],
              "title": "Widget preview and debugging"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/widgetkit/preview-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/widgetkit/preview-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
