{
  "abstract": [
    {
      "text": "Offer widgets in additional contexts by adding support for various widget sizes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.WidgetKit/documentation/WidgetKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.WidgetKit/documentation/WidgetKit/Supporting-additional-widget-sizes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WidgetKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Supporting additional widget sizes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you add a widget extension to your app and create your first widget, add code to declare additional widgets your app supports using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WidgetConfiguration/supportedFamilies(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property modifier. The sizes you use depend on the devices your app supports. If your app supports more than one platform, make sure to conditionally declare supported widget families.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/emoji-rangers-supporting-live-activities-interactivity-and-animations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample code project shows how you declare several widgets sizes in your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Widget",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " implementation. The app supports accessory widgets in both watchOS and iOS and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily/systemSmall",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily/systemMedium",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " widgets in iOS. Note the usage of the ",
              "type": "text"
            },
            {
              "code": "#if os(watchOS)",
              "type": "codeVoice"
            },
            {
              "text": " macro to make sure you declare the correct supported widget families for each platform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "public var body: some WidgetConfiguration {",
            "    makeWidgetConfiguration()",
            "        .configurationDisplayName(\"Ranger Detail\")",
            "        .description(\"See your favorite ranger.\")",
            "#if os(watchOS)",
            "        .supportedFamilies([.accessoryCircular,",
            "                            .accessoryRectangular, .accessoryInline])",
            "#else",
            "        .supportedFamilies([.accessoryCircular,",
            "                            .accessoryRectangular, .accessoryInline,",
            "                            .systemSmall, .systemMedium, .systemLarge])",
            "#endif",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Update-SwiftUI-views-to-support-additional-sizes",
          "level": 3,
          "text": "Update SwiftUI views to support additional sizes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you’ve declared support for additional widget sizes in your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Widget",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", update the views of your widget to support the additional family sizes. In your view code:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/widgetFamily",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " environment variable to detect different widget families.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Construct the view for each size and include code to handle appearances like vibrant and Dark Mode, as applicable. To learn more, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows an abbreviated code snippet from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/emoji-rangers-supporting-live-activities-interactivity-and-animations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample code project. It conditionally returns the right SwiftUI view for each widget family.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct EmojiRangerWidgetEntryView: View {",
            "    var entry: Provider.Entry",
            "    ",
            "    @Environment(\\.widgetFamily) var family",
            "",
            "    @ViewBuilder",
            "    var body: some View {",
            "        switch family {",
            "        case .accessoryCircular:",
            "            // Code to construct the view for the circular accessory widget or watch complication.",
            "        case .accessoryRectangular:",
            "            // Code to construct the view for the rectangular accessory widget or watch complication.",
            "        case .accessoryInline:",
            "            // Code to construct the view for the inline accessory widget or watch complication.",
            "        case .systemSmall:",
            "            // Code to construct the view for the small widget.",
            "        case .systemLarge:",
            "            // Code to construct the view for the large widget.",
            "        case .systemMedium",
            "            // Code to construct the view for the medium widget.",
            "        default:",
            "            // Code to construct the view for other widgets, for example, the extra large widget.",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Use Xcode previews to view your widget designs without running your app in Simulator or on a device. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension#Preview-widgets-in-Xcode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Backyard-Birds-intro.png": {
      "alt": null,
      "identifier": "Backyard-Birds-intro.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/308516255a4b167225a334a5a55a1ff3/Backyard-Birds-intro@2x.png"
        }
      ]
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Converting-A-ClockKit-App": {
      "abstract": [
        {
          "text": "Leverage WidgetKit’s API to create watchOS complications using SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Converting-A-ClockKit-App",
      "kind": "article",
      "role": "article",
      "title": "Migrating ClockKit complications to WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit/converting-a-clockkit-app"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension": {
      "abstract": [
        {
          "text": "Display your app’s content in a convenient, informative widget on various devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a widget extension",
      "type": "topic",
      "url": "/documentation/widgetkit/creating-a-widget-extension"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension#Preview-widgets-in-Xcode": {
      "abstract": [],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension#Preview-widgets-in-Xcode",
      "kind": "section",
      "title": "Preview widgets in Xcode",
      "type": "topic",
      "url": "/documentation/widgetkit/creating-a-widget-extension#Preview-widgets-in-Xcode"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-accessory-widgets-and-watch-complications": {
      "abstract": [
        {
          "text": "Support accessory widgets that appear on the Lock Screen and as complications on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-accessory-widgets-and-watch-complications",
      "kind": "article",
      "role": "article",
      "title": "Creating accessory widgets and watch complications",
      "type": "topic",
      "url": "/documentation/widgetkit/creating-accessory-widgets-and-watch-complications"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances": {
      "abstract": [
        {
          "text": "Create widgets that support additional platforms and adapt to their context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances",
      "kind": "article",
      "role": "article",
      "title": "Preparing widgets for additional platforms, contexts, and appearances",
      "type": "topic",
      "url": "/documentation/widgetkit/preparing-widgets-for-additional-contexts-and-appearances"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/StaticConfiguration": {
      "abstract": [
        {
          "text": "An object describing the content of a widget that has no user-configurable",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StaticConfiguration"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/StaticConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StaticConfiguration"
        }
      ],
      "role": "symbol",
      "title": "StaticConfiguration",
      "type": "topic",
      "url": "/documentation/widgetkit/staticconfiguration"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetAccentedRenderingMode": {
      "abstract": [
        {
          "text": "Constants that indicate the rendering mode for an ",
          "type": "text"
        },
        {
          "code": "Image",
          "type": "codeVoice"
        },
        {
          "text": " in when displayed in a widget",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetRenderingMode/accented",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetAccentedRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetAccentedRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WidgetAccentedRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "WidgetAccentedRenderingMode",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetaccentedrenderingmode"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily": {
      "abstract": [
        {
          "text": "Values that define the widget’s size and shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetFamily"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WidgetFamily"
        }
      ],
      "role": "symbol",
      "title": "WidgetFamily",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetfamily"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily/systemMedium": {
      "abstract": [
        {
          "text": "A medium-sized widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemMedium"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily/systemMedium",
      "kind": "symbol",
      "role": "symbol",
      "title": "WidgetFamily.systemMedium",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetfamily/systemmedium"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily/systemSmall": {
      "abstract": [
        {
          "text": "A small widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemSmall"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily/systemSmall",
      "kind": "symbol",
      "role": "symbol",
      "title": "WidgetFamily.systemSmall",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetfamily/systemsmall"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetRenderingMode": {
      "abstract": [
        {
          "text": "Constants that indicate the rendering mode for a widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WidgetRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "WidgetRenderingMode",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetrenderingmode"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetRenderingMode/accented": {
      "abstract": [
        {
          "text": "The system divides the widget’s view hierarchy into an accent group and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a default group, applying a different color to each group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accented"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A13RenderingModeV",
          "text": "WidgetRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetRenderingMode/accented",
      "kind": "symbol",
      "role": "symbol",
      "title": "accented",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetrenderingmode/accented"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/emoji-rangers-supporting-live-activities-interactivity-and-animations": {
      "abstract": [
        {
          "text": "Offer Live Activities, controls, animate data updates, and add interactivity to widgets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/emoji-rangers-supporting-live-activities-interactivity-and-animations",
      "kind": "article",
      "role": "sampleCode",
      "title": "Emoji Rangers: Supporting Live Activities, interactivity, and animations",
      "type": "topic",
      "url": "/documentation/widgetkit/emoji-rangers-supporting-live-activities-interactivity-and-animations"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample": {
      "abstract": [
        {
          "text": "Create an app with persistent data, interactive widgets, and an all new in-app purchase experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample",
      "images": [
        {
          "identifier": "Backyard-Birds-intro.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Backyard Birds: Building an app with SwiftData and widgets",
      "type": "topic",
      "url": "/documentation/SwiftUI/Backyard-birds-sample"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/widgetFamily": {
      "abstract": [
        {
          "text": "The template of the widget — small, medium, or large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetFamily"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A6FamilyO",
          "text": "WidgetFamily"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/widgetFamily",
      "kind": "symbol",
      "role": "symbol",
      "title": "widgetFamily",
      "type": "topic",
      "url": "/documentation/SwiftUI/EnvironmentValues/widgetFamily"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Widget": {
      "abstract": [
        {
          "text": "The configuration and content of a widget to display on the Home screen or in Notification Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Widget"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Widget",
      "kind": "symbol",
      "role": "symbol",
      "title": "Widget",
      "type": "topic",
      "url": "/documentation/SwiftUI/Widget"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/WidgetBundle": {
      "abstract": [
        {
          "text": "A container used to expose multiple widgets from a single widget extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetBundle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WidgetBundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "WidgetBundle",
      "type": "topic",
      "url": "/documentation/SwiftUI/WidgetBundle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/WidgetConfiguration/supportedFamilies(_:)": {
      "abstract": [
        {
          "text": "Sets the sizes that a widget supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedFamilies"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "families"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit0A6FamilyO",
          "text": "WidgetFamily"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19WidgetConfigurationP",
          "text": "WidgetConfiguration"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WidgetConfiguration/supportedFamilies(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedFamilies(_:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/WidgetConfiguration/supportedFamilies(_:)"
    },
    "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui": {
      "abstract": [
        {
          "text": "Create a shared codebase to build a multiplatform app that offers widgets and an App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Fruta: Building a Feature-Rich App with SwiftUI",
      "type": "topic",
      "url": "/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/widgetkit/building_widgets_using_widgetkit_and_swiftui": {
      "abstract": [
        {
          "text": "Create widgets to show your app’s content on the Home screen, with custom intents for user-customizable settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/widgetkit/building_widgets_using_widgetkit_and_swiftui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building Widgets Using WidgetKit and SwiftUI",
      "type": "topic",
      "url": "/documentation/widgetkit/building_widgets_using_widgetkit_and_swiftui"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Widget-creation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-accessory-widgets-and-watch-complications",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Converting-A-ClockKit-App",
        "doc://com.apple.documentation/documentation/widgetkit/building_widgets_using_widgetkit_and_swiftui",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/emoji-rangers-supporting-live-activities-interactivity-and-animations",
        "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample",
        "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui",
        "doc://com.apple.documentation/documentation/SwiftUI/Widget",
        "doc://com.apple.documentation/documentation/SwiftUI/WidgetBundle",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/StaticConfiguration",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetFamily",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetRenderingMode",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetAccentedRenderingMode"
      ],
      "title": "Widget creation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Widget-creation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-a-Widget-Extension",
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-accessory-widgets-and-watch-complications",
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Converting-A-ClockKit-App",
                "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample"
              ],
              "title": "Widget creation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/widgetkit/supporting-additional-widget-sizes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/widgetkit/supporting-additional-widget-sizes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
