{
  "abstract": [
    {
      "text": "Present your app’s content in widgets with SwiftUI views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.WidgetKit/documentation/WidgetKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.WidgetKit/documentation/WidgetKit/SwiftUI-Views"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WidgetKit"
      }
    ],
    "role": "collectionGroup",
    "title": "SwiftUI views for widgets"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Widgets can use many, but not all, SwiftUI views to present content. Use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "views listed below to implement your widget’s view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Widgets can’t use UIKit or AppKit views wrapped with ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/SwiftUI/UIViewRepresentable",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NSViewRepresentable",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.WidgetKit/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/AccessoryWidgetBackground": {
      "abstract": [
        {
          "text": "An adaptive background view that provides a standard appearance based on the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the widget’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessoryWidgetBackground"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/AccessoryWidgetBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessoryWidgetBackground"
        }
      ],
      "role": "symbol",
      "title": "AccessoryWidgetBackground",
      "type": "topic",
      "url": "/documentation/widgetkit/accessorywidgetbackground"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-interactivity-to-widgets-and-Live-Activities": {
      "abstract": [
        {
          "text": "Include buttons or toggles in a widget or Live Activity to offer app functionality without launching the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-interactivity-to-widgets-and-Live-Activities",
      "kind": "article",
      "role": "article",
      "title": "Adding interactivity to widgets and Live Activities",
      "type": "topic",
      "url": "/documentation/widgetkit/adding-interactivity-to-widgets-and-live-activities"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-views-for-widgets-Live-Activities-and-watch-complications": {
      "abstract": [
        {
          "text": "Implement glanceable views with WidgetKit and SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-views-for-widgets-Live-Activities-and-watch-complications",
      "kind": "article",
      "role": "article",
      "title": "Creating views for widgets, Live Activities, and watch complications",
      "type": "topic",
      "url": "/documentation/widgetkit/creating-views-for-widgets-live-activities-and-watch-complications"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Displaying-Dynamic-Dates": {
      "abstract": [
        {
          "text": "Show up-to-date, time-based information in your widget even when it",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "isn’t running.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Displaying-Dynamic-Dates",
      "kind": "article",
      "role": "article",
      "title": "Displaying dynamic dates in widgets",
      "type": "topic",
      "url": "/documentation/widgetkit/displaying-dynamic-dates"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances": {
      "abstract": [
        {
          "text": "Create widgets that support additional platforms and adapt to their context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances",
      "kind": "article",
      "role": "article",
      "title": "Preparing widgets for additional platforms, contexts, and appearances",
      "type": "topic",
      "url": "/documentation/widgetkit/preparing-widgets-for-additional-contexts-and-appearances"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetLocation": {
      "abstract": [
        {
          "text": "Values that indicate different widget locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WidgetLocation"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WidgetLocation"
        }
      ],
      "role": "symbol",
      "title": "WidgetLocation",
      "type": "topic",
      "url": "/documentation/widgetkit/widgetlocation"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/AngularGradient": {
      "abstract": [
        {
          "text": "An angular gradient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AngularGradient"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/AngularGradient",
      "kind": "symbol",
      "role": "symbol",
      "title": "AngularGradient",
      "type": "topic",
      "url": "/documentation/SwiftUI/AngularGradient"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/AnyView": {
      "abstract": [
        {
          "text": "A type-erased view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/AnyView",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyView",
      "type": "topic",
      "url": "/documentation/SwiftUI/AnyView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/BackgroundStyle": {
      "abstract": [
        {
          "text": "The background style in the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/BackgroundStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "BackgroundStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/BackgroundStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Button": {
      "abstract": [
        {
          "text": "A control that initiates an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Button"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Button",
      "kind": "symbol",
      "role": "symbol",
      "title": "Button",
      "type": "topic",
      "url": "/documentation/SwiftUI/Button"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Canvas": {
      "abstract": [
        {
          "text": "A view type that supports immediate mode drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Canvas"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Symbols"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Symbols"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Canvas",
      "kind": "symbol",
      "role": "symbol",
      "title": "Canvas",
      "type": "topic",
      "url": "/documentation/SwiftUI/Canvas"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Capsule": {
      "abstract": [
        {
          "text": "A capsule shape aligned inside the frame of the view containing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Capsule"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Capsule",
      "kind": "symbol",
      "role": "symbol",
      "title": "Capsule",
      "type": "topic",
      "url": "/documentation/SwiftUI/Capsule"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Circle": {
      "abstract": [
        {
          "text": "A circle centered on the frame of the view containing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Circle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Circle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Circle",
      "type": "topic",
      "url": "/documentation/SwiftUI/Circle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Color": {
      "abstract": [
        {
          "text": "A representation of a color that adapts to a given context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Color"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Color",
      "kind": "symbol",
      "role": "symbol",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/SwiftUI/Color"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ContainerRelativeShape": {
      "abstract": [
        {
          "text": "A shape that is replaced by an inset version of the current container shape. If no container shape was defined, is replaced by a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContainerRelativeShape"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ContainerRelativeShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "ContainerRelativeShape",
      "type": "topic",
      "url": "/documentation/SwiftUI/ContainerRelativeShape"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Divider": {
      "abstract": [
        {
          "text": "A visual element that can be used to separate other content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Divider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Divider",
      "kind": "symbol",
      "role": "symbol",
      "title": "Divider",
      "type": "topic",
      "url": "/documentation/SwiftUI/Divider"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Ellipse": {
      "abstract": [
        {
          "text": "An ellipse aligned inside the frame of the view containing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Ellipse"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Ellipse",
      "kind": "symbol",
      "role": "symbol",
      "title": "Ellipse",
      "type": "topic",
      "url": "/documentation/SwiftUI/Ellipse"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EmptyView": {
      "abstract": [
        {
          "text": "A view that doesn’t contain any content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EmptyView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EmptyView",
      "kind": "symbol",
      "role": "symbol",
      "title": "EmptyView",
      "type": "topic",
      "url": "/documentation/SwiftUI/EmptyView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EquatableView": {
      "abstract": [
        {
          "text": "A view type that compares itself against its previous value and prevents its child updating if its new value is the same as its old value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EquatableView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EquatableView",
      "kind": "symbol",
      "role": "symbol",
      "title": "EquatableView",
      "type": "topic",
      "url": "/documentation/SwiftUI/EquatableView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/FillStyle": {
      "abstract": [
        {
          "text": "A style for rasterizing vector shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FillStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/FillStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "FillStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/FillStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ForEach": {
      "abstract": [
        {
          "text": "A structure that computes views on demand from an underlying collection of identified data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ForEach"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk",
          "text": "RandomAccessCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ForEach",
      "kind": "symbol",
      "role": "symbol",
      "title": "ForEach",
      "type": "topic",
      "url": "/documentation/SwiftUI/ForEach"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ForegroundStyle": {
      "abstract": [
        {
          "text": "The foreground style in the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ForegroundStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ForegroundStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "ForegroundStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/ForegroundStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/GeometryProxy": {
      "abstract": [
        {
          "text": "A proxy for access to the size and coordinate space (for anchor resolution) of the container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometryProxy"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/GeometryProxy",
      "kind": "symbol",
      "role": "symbol",
      "title": "GeometryProxy",
      "type": "topic",
      "url": "/documentation/SwiftUI/GeometryProxy"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/GeometryReader": {
      "abstract": [
        {
          "text": "A container view that defines its content as a function of its own size and coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometryReader"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/GeometryReader",
      "kind": "symbol",
      "role": "symbol",
      "title": "GeometryReader",
      "type": "topic",
      "url": "/documentation/SwiftUI/GeometryReader"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Gradient": {
      "abstract": [
        {
          "text": "A color gradient represented as an array of color stops, each having a parametric location value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Gradient"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Gradient",
      "kind": "symbol",
      "role": "symbol",
      "title": "Gradient",
      "type": "topic",
      "url": "/documentation/SwiftUI/Gradient"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/GridItem": {
      "abstract": [
        {
          "text": "A description of a row or a column in a lazy grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GridItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/GridItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "GridItem",
      "type": "topic",
      "url": "/documentation/SwiftUI/GridItem"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Group": {
      "abstract": [
        {
          "text": "A type that collects multiple instances of a content type — like views, scenes, or commands — into a single unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Group"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Group",
      "kind": "symbol",
      "role": "symbol",
      "title": "Group",
      "type": "topic",
      "url": "/documentation/SwiftUI/Group"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/GroupBox": {
      "abstract": [
        {
          "text": "A stylized view, with an optional label, that visually collects a logical grouping of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GroupBox"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/GroupBox",
      "kind": "symbol",
      "role": "symbol",
      "title": "GroupBox",
      "type": "topic",
      "url": "/documentation/SwiftUI/GroupBox"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/HStack": {
      "abstract": [
        {
          "text": "A view that arranges its subviews in a horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HStack"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HStack",
      "kind": "symbol",
      "role": "symbol",
      "title": "HStack",
      "type": "topic",
      "url": "/documentation/SwiftUI/HStack"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Image": {
      "abstract": [
        {
          "text": "A view that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Image",
      "kind": "symbol",
      "role": "symbol",
      "title": "Image",
      "type": "topic",
      "url": "/documentation/SwiftUI/Image"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ImagePaint": {
      "abstract": [
        {
          "text": "A shape style that fills a shape by repeating a region of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImagePaint"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ImagePaint",
      "kind": "symbol",
      "role": "symbol",
      "title": "ImagePaint",
      "type": "topic",
      "url": "/documentation/SwiftUI/ImagePaint"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Label": {
      "abstract": [
        {
          "text": "A standard label for user interface items, consisting of an icon with a title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Title"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Title"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Label",
      "kind": "symbol",
      "role": "symbol",
      "title": "Label",
      "type": "topic",
      "url": "/documentation/SwiftUI/Label"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/LazyHGrid": {
      "abstract": [
        {
          "text": "A container view that arranges its child views in a grid that grows horizontally, creating items only as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LazyHGrid"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/LazyHGrid",
      "kind": "symbol",
      "role": "symbol",
      "title": "LazyHGrid",
      "type": "topic",
      "url": "/documentation/SwiftUI/LazyHGrid"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/LazyHStack": {
      "abstract": [
        {
          "text": "A view that arranges its children in a line that grows horizontally, creating items only as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LazyHStack"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/LazyHStack",
      "kind": "symbol",
      "role": "symbol",
      "title": "LazyHStack",
      "type": "topic",
      "url": "/documentation/SwiftUI/LazyHStack"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/LazyVGrid": {
      "abstract": [
        {
          "text": "A container view that arranges its child views in a grid that grows vertically, creating items only as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LazyVGrid"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/LazyVGrid",
      "kind": "symbol",
      "role": "symbol",
      "title": "LazyVGrid",
      "type": "topic",
      "url": "/documentation/SwiftUI/LazyVGrid"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/LazyVStack": {
      "abstract": [
        {
          "text": "A view that arranges its children in a line that grows vertically, creating items only as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LazyVStack"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/LazyVStack",
      "kind": "symbol",
      "role": "symbol",
      "title": "LazyVStack",
      "type": "topic",
      "url": "/documentation/SwiftUI/LazyVStack"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/LinearGradient": {
      "abstract": [
        {
          "text": "A linear gradient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LinearGradient"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/LinearGradient",
      "kind": "symbol",
      "role": "symbol",
      "title": "LinearGradient",
      "type": "topic",
      "url": "/documentation/SwiftUI/LinearGradient"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Link": {
      "abstract": [
        {
          "text": "A control for navigating to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Link"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Link",
      "kind": "symbol",
      "role": "symbol",
      "title": "Link",
      "type": "topic",
      "url": "/documentation/SwiftUI/Link"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/NSViewRepresentable": {
      "abstract": [
        {
          "text": "A wrapper that you use to integrate an AppKit view into your SwiftUI view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewRepresentable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP4BodyQa",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NSViewRepresentable",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewRepresentable",
      "type": "topic",
      "url": "/documentation/SwiftUI/NSViewRepresentable"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/OffsetShape": {
      "abstract": [
        {
          "text": "A shape with a translation offset transform applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OffsetShape"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ShapeP",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/OffsetShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "OffsetShape",
      "type": "topic",
      "url": "/documentation/SwiftUI/OffsetShape"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/OutlineGroup": {
      "abstract": [
        {
          "text": "A structure that computes views and disclosure groups on demand from an underlying collection of tree-structured, identified data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OutlineGroup"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Parent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Leaf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Subgroup"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk",
          "text": "RandomAccessCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/OutlineGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "OutlineGroup",
      "type": "topic",
      "url": "/documentation/SwiftUI/OutlineGroup"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Path": {
      "abstract": [
        {
          "text": "The outline of a 2D shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Path"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Path",
      "kind": "symbol",
      "role": "symbol",
      "title": "Path",
      "type": "topic",
      "url": "/documentation/SwiftUI/Path"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProjectionTransform": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProjectionTransform"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProjectionTransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProjectionTransform",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProjectionTransform"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/RadialGradient": {
      "abstract": [
        {
          "text": "A radial gradient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RadialGradient"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/RadialGradient",
      "kind": "symbol",
      "role": "symbol",
      "title": "RadialGradient",
      "type": "topic",
      "url": "/documentation/SwiftUI/RadialGradient"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Rectangle": {
      "abstract": [
        {
          "text": "A rectangular shape aligned inside the frame of the view containing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Rectangle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Rectangle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Rectangle",
      "type": "topic",
      "url": "/documentation/SwiftUI/Rectangle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/RotatedShape": {
      "abstract": [
        {
          "text": "A shape with a rotation transform applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RotatedShape"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ShapeP",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/RotatedShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "RotatedShape",
      "type": "topic",
      "url": "/documentation/SwiftUI/RotatedShape"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/RoundedRectangle": {
      "abstract": [
        {
          "text": "A rectangular shape with rounded corners, aligned inside the frame of the view containing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoundedRectangle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/RoundedRectangle",
      "kind": "symbol",
      "role": "symbol",
      "title": "RoundedRectangle",
      "type": "topic",
      "url": "/documentation/SwiftUI/RoundedRectangle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ScaledShape": {
      "abstract": [
        {
          "text": "A shape with a scale transform applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScaledShape"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ShapeP",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScaledShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "ScaledShape",
      "type": "topic",
      "url": "/documentation/SwiftUI/ScaledShape"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Section": {
      "abstract": [
        {
          "text": "A container view that you can use to add hierarchy within certain views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Section"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Parent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Footer"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Section",
      "kind": "symbol",
      "role": "symbol",
      "title": "Section",
      "type": "topic",
      "url": "/documentation/SwiftUI/Section"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/SelectionShapeStyle": {
      "abstract": [
        {
          "text": "A style used to visually indicate selection following platform conventional colors and behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionShapeStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SelectionShapeStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "SelectionShapeStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/SelectionShapeStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/SeparatorShapeStyle": {
      "abstract": [
        {
          "text": "A style appropriate for foreground separator or border lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SeparatorShapeStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SeparatorShapeStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "SeparatorShapeStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/SeparatorShapeStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Spacer": {
      "abstract": [
        {
          "text": "A flexible space that expands along the major axis of its containing stack layout, or on both axes if not contained in a stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Spacer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Spacer",
      "kind": "symbol",
      "role": "symbol",
      "title": "Spacer",
      "type": "topic",
      "url": "/documentation/SwiftUI/Spacer"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/StrokeStyle": {
      "abstract": [
        {
          "text": "The characteristics of a stroke that traces a path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StrokeStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/StrokeStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "StrokeStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/StrokeStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
      "kind": "symbol",
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Toggle": {
      "abstract": [
        {
          "text": "A control that toggles between on and off states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Toggle"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Toggle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Toggle",
      "type": "topic",
      "url": "/documentation/SwiftUI/Toggle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/TransformedShape": {
      "abstract": [
        {
          "text": "A shape with an affine transform applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransformedShape"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ShapeP",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TransformedShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "TransformedShape",
      "type": "topic",
      "url": "/documentation/SwiftUI/TransformedShape"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/TupleView": {
      "abstract": [
        {
          "text": "A View created from a swift tuple of View values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TupleView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TupleView",
      "kind": "symbol",
      "role": "symbol",
      "title": "TupleView",
      "type": "topic",
      "url": "/documentation/SwiftUI/TupleView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/UIViewRepresentable": {
      "abstract": [
        {
          "text": "A wrapper for a UIKit view that you use to integrate that view into your SwiftUI view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewRepresentable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP4BodyQa",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/UIViewRepresentable",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewRepresentable",
      "type": "topic",
      "url": "/documentation/SwiftUI/UIViewRepresentable"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/VStack": {
      "abstract": [
        {
          "text": "A view that arranges its subviews in a vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VStack"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/VStack",
      "kind": "symbol",
      "role": "symbol",
      "title": "VStack",
      "type": "topic",
      "url": "/documentation/SwiftUI/VStack"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ZStack": {
      "abstract": [
        {
          "text": "A view that overlays its subviews, aligning them in both axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ZStack"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ZStack",
      "kind": "symbol",
      "role": "symbol",
      "title": "ZStack",
      "type": "topic",
      "url": "/documentation/SwiftUI/ZStack"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/tutorials/SwiftUI": {
      "abstract": [
        {
          "text": "SwiftUI is a modern way to declare user interfaces for any Apple platform. Create beautiful, dynamic apps faster than ever before.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/tutorials/SwiftUI",
      "kind": "overview",
      "role": "overview",
      "title": "Introducing SwiftUI",
      "type": "topic",
      "url": "/tutorials/SwiftUI"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presentation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-views-for-widgets-Live-Activities-and-watch-complications",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances",
        "doc://com.apple.documentation/tutorials/SwiftUI",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/AccessoryWidgetBackground",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/WidgetLocation"
      ],
      "title": "Presentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Displaying-text",
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Displaying-Dynamic-Dates",
        "doc://com.apple.documentation/documentation/SwiftUI/Text"
      ],
      "title": "Displaying text"
    },
    {
      "anchor": "Showing-images",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Image"
      ],
      "title": "Showing images"
    },
    {
      "anchor": "Adding-interaction",
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-interactivity-to-widgets-and-Live-Activities",
        "doc://com.apple.documentation/documentation/SwiftUI/Button",
        "doc://com.apple.documentation/documentation/SwiftUI/Toggle"
      ],
      "title": "Adding interaction"
    },
    {
      "anchor": "Adding-labels-and-links",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Label",
        "doc://com.apple.documentation/documentation/SwiftUI/Link"
      ],
      "title": "Adding labels and links"
    },
    {
      "anchor": "Stacking-views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/HStack",
        "doc://com.apple.documentation/documentation/SwiftUI/VStack",
        "doc://com.apple.documentation/documentation/SwiftUI/ZStack",
        "doc://com.apple.documentation/documentation/SwiftUI/LazyHStack",
        "doc://com.apple.documentation/documentation/SwiftUI/LazyVStack"
      ],
      "title": "Stacking views"
    },
    {
      "anchor": "Arranging-views-in-grids",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/LazyHGrid",
        "doc://com.apple.documentation/documentation/SwiftUI/LazyVGrid",
        "doc://com.apple.documentation/documentation/SwiftUI/GridItem"
      ],
      "title": "Arranging views in grids"
    },
    {
      "anchor": "Enumerating-lists",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/ForEach"
      ],
      "title": "Enumerating lists"
    },
    {
      "anchor": "Grouping-views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Group",
        "doc://com.apple.documentation/documentation/SwiftUI/GroupBox",
        "doc://com.apple.documentation/documentation/SwiftUI/Section"
      ],
      "title": "Grouping views"
    },
    {
      "anchor": "Representing-hierarchies",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/OutlineGroup"
      ],
      "title": "Representing hierarchies"
    },
    {
      "anchor": "Adding-spacers-and-dividers",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Spacer",
        "doc://com.apple.documentation/documentation/SwiftUI/Divider"
      ],
      "title": "Adding spacers and dividers"
    },
    {
      "anchor": "Handling-conditional-views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/EmptyView",
        "doc://com.apple.documentation/documentation/SwiftUI/EquatableView"
      ],
      "title": "Handling conditional views"
    },
    {
      "anchor": "Displaying-shapes",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Rectangle",
        "doc://com.apple.documentation/documentation/SwiftUI/RoundedRectangle",
        "doc://com.apple.documentation/documentation/SwiftUI/Circle",
        "doc://com.apple.documentation/documentation/SwiftUI/Ellipse",
        "doc://com.apple.documentation/documentation/SwiftUI/Capsule",
        "doc://com.apple.documentation/documentation/SwiftUI/Path"
      ],
      "title": "Displaying shapes"
    },
    {
      "anchor": "Transforming-views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/ScaledShape",
        "doc://com.apple.documentation/documentation/SwiftUI/RotatedShape",
        "doc://com.apple.documentation/documentation/SwiftUI/OffsetShape",
        "doc://com.apple.documentation/documentation/SwiftUI/TransformedShape",
        "doc://com.apple.documentation/documentation/SwiftUI/ContainerRelativeShape"
      ],
      "title": "Transforming views"
    },
    {
      "anchor": "Styling-views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Color",
        "doc://com.apple.documentation/documentation/SwiftUI/ImagePaint",
        "doc://com.apple.documentation/documentation/SwiftUI/Gradient",
        "doc://com.apple.documentation/documentation/SwiftUI/LinearGradient",
        "doc://com.apple.documentation/documentation/SwiftUI/AngularGradient",
        "doc://com.apple.documentation/documentation/SwiftUI/RadialGradient",
        "doc://com.apple.documentation/documentation/SwiftUI/ForegroundStyle",
        "doc://com.apple.documentation/documentation/SwiftUI/FillStyle",
        "doc://com.apple.documentation/documentation/SwiftUI/BackgroundStyle",
        "doc://com.apple.documentation/documentation/SwiftUI/SelectionShapeStyle",
        "doc://com.apple.documentation/documentation/SwiftUI/SeparatorShapeStyle",
        "doc://com.apple.documentation/documentation/SwiftUI/StrokeStyle"
      ],
      "title": "Styling views"
    },
    {
      "anchor": "Creating-2D-graphics",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Canvas"
      ],
      "title": "Creating 2D graphics"
    },
    {
      "anchor": "Managing-view-geometry",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/GeometryProxy",
        "doc://com.apple.documentation/documentation/SwiftUI/GeometryReader",
        "doc://com.apple.documentation/documentation/SwiftUI/ProjectionTransform"
      ],
      "title": "Managing view geometry"
    },
    {
      "anchor": "Substituting-views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/AnyView",
        "doc://com.apple.documentation/documentation/SwiftUI/TupleView"
      ],
      "title": "Substituting views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Displaying-text",
              "identifiers": [
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Displaying-Dynamic-Dates"
              ],
              "title": "Displaying text"
            },
            {
              "anchor": "Adding-interaction",
              "identifiers": [
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Adding-interactivity-to-widgets-and-Live-Activities"
              ],
              "title": "Adding interaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presentation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Creating-views-for-widgets-Live-Activities-and-watch-complications",
                "doc://com.apple.WidgetKit/documentation/WidgetKit/Preparing-widgets-for-additional-contexts-and-appearances"
              ],
              "title": "Presentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/widgetkit/swiftui-views"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/widgetkit/swiftui-views"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
