{
  "abstract": [
    {
      "text": "Update and reload controls from your app or using push notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.WidgetKit/documentation/WidgetKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.WidgetKit/documentation/WidgetKit/Updating-controls-locally-and-remotely"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WidgetKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Updating controls locally and remotely"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A control reloads and updates when someone interacts with it, when the app asks to reload it using the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or when the system receives a specific remote push notification from Apple Push Notification service (APNs). When someone interacts with a control, it’s reloaded once the assigned app intent finishes its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent/perform()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. Plan for when someone interacts with your app or website and the state of a control needs to update to reflect the changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Request-reloading-controls-from-an-app",
          "level": 3,
          "text": "Request reloading controls from an app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Reload controls when their state changes after someone interacts with them, such as turning a light on or off from within your app. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/reloadControls(ofKind:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the shared ",
              "type": "text"
            },
            {
              "code": "ControlCenter",
              "type": "codeVoice"
            },
            {
              "text": " to ask the system to reload a control from your app that matches a specific ",
              "type": "text"
            },
            {
              "code": "kind",
              "type": "codeVoice"
            },
            {
              "text": " unique identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows reloading a garage door control toggle from within the app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func toggleGarageDoor {",
            "\t//Open or close a garage door.",
            "\t",
            "\tControlCenter.shared.reloadControls(ofKind: \"com.example.myApp.garageDoorToggle\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/reloadAllControls()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to ask the system to reload all controls your app provides.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-push-notifications-to-reload-controls",
          "level": 3,
          "text": "Use push notifications to reload controls",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You may need the system to reload controls when someone interacts with a web server connected to your app that affects their state. Enable a control to update its state from a push notification event by registering a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ControlWidgetConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The system reloads any controls with a registered push handler in response to a push notification event. You don’t need to reload the controls manually.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "ControlPushHandler",
              "type": "codeVoice"
            },
            {
              "text": " requires a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler/pushTokensDidChange(controls:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function that is called when push tokens change. The system calls this function when you add or remove controls, and may call it at other times if any push tokens change or if someone reconfigures a control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "controls",
              "type": "codeVoice"
            },
            {
              "text": " parameter describes all controls from your app registered with this handler type, which allows you to batch all push tokens together and send them to your server at the same time. Each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object represents a control and includes the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/kind",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " you set when creating the control.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/configurationIntent(of:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function. If your control is configurable, this function provides the custom intent containing the user-configured value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/pushInfo",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " containing the unique push token that’s used to deliver updates for this control, if a push handler is registered.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code registers a push handler on a control that opens and closes a garage door:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct GarageDoorOpener: ControlWidget {",
            "\tvar body: some ControlWidgetConfiguration {",
            "\t\tStaticControlConfiguration(",
            "\t\t\tkind: \"com.apple.GarageDoorOpener\"",
            "\t\t) {",
            "\t\t\tControlWidgetToggle(...)",
            "\t\t}",
            "\t\t.pushHandler(MyPushHandler.self)",
            "\t}",
            "}",
            "",
            "struct MyPushHandler: ControlPushHandler {",
            "\tfunc pushTokensDidChange(controls: [ControlInfo]) {",
            "\t\t// TODO: Send push tokens and subscription info to server",
            "\t\t// ...",
            "\t}",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Query for the current set of your controls someone placed across their system in your app by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/currentControls()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the shared ",
              "type": "text"
            },
            {
              "code": "ControlCenter",
              "type": "codeVoice"
            },
            {
              "text": ". Introspect the push tokens, if any, from the set of controls to sync state with your app and server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code queries for the current set of controls and gets any push tokens associated with them:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let controls = await ControlCenter.shared.currentControls()",
            "let pushTokens = controls.compactMap { $0.pushInfo?.token }",
            "",
            "// Sync push tokens with server."
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use APNs when your server has a state change to communicate to controls on someone’s devices. The POST request indicates that state changed for the single control representing that given push token, and the system reloads the control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code snippet below shows a sample POST request created with an authentication token:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "HEADERS",
            "  - END_STREAM",
            "  + END_HEADERS",
            "  :method = POST",
            "  :scheme = https",
            "  :path = /3/device/00fc13adff785122b4ad28809a3420982341241421348097878e577c991de8f0",
            "  host = api.sandbox.push.apple.com",
            "  authorization = bearer eyAia2lkIjogIjhZTDNHM1JSWDciIH0.eyAiaXNzIjogIkM4Nk5WOUpYM0QiLCAiaWF0I",
            "\t\t jogIjE0NTkxNDM1ODA2NTAiIH0.MEYCIQDzqyahmH1rz1s-LFNkylXEa2lZ_aOCX4daxxTZkVEGzwIhALvkClnx5m5eAT6",
            "\t\t Lxw7LZtEQcH6JENhJTMArwLf3sXwi",
            "  apns-id = eabeae54-14a8-11e5-b60b-1697f925ec7b",
            "  apns-push-type = controls",
            "  apns-expiration = 0",
            "  apns-priority = 10",
            "  apns-topic = com.example.MyApp.push-type.controls",
            "DATA",
            "  + END_STREAM",
            "  { \"aps\" : { \"content-changed\" : true } }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.WidgetKit/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/widgetkit"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter": {
      "abstract": [
        {
          "text": "An object that contains a list of user-configured controls and is used for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "reloading controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlCenter"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlCenter"
        }
      ],
      "role": "symbol",
      "title": "ControlCenter",
      "type": "topic",
      "url": "/documentation/widgetkit/controlcenter"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/currentControls()": {
      "abstract": [
        {
          "text": "Retrieves information about user-configured controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentControls"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit11ControlInfoV",
          "text": "ControlInfo"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/currentControls()",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentControls()",
      "type": "topic",
      "url": "/documentation/widgetkit/controlcenter/currentcontrols()"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/reloadAllControls()": {
      "abstract": [
        {
          "text": "Reloads the templates for all configured controls belonging to the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "containing app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadAllControls"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/reloadAllControls()",
      "kind": "symbol",
      "role": "symbol",
      "title": "reloadAllControls()",
      "type": "topic",
      "url": "/documentation/widgetkit/controlcenter/reloadallcontrols()"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/reloadControls(ofKind:)": {
      "abstract": [
        {
          "text": "Reloads the templates for all controls of a particular kind.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadControls"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlCenter/reloadControls(ofKind:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "reloadControls(ofKind:)",
      "type": "topic",
      "url": "/documentation/widgetkit/controlcenter/reloadcontrols(ofkind:)"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo": {
      "abstract": [
        {
          "text": "A structure that contains information about user-configured controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlInfo"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlInfo"
        }
      ],
      "role": "symbol",
      "title": "ControlInfo",
      "type": "topic",
      "url": "/documentation/widgetkit/controlinfo"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/configurationIntent(of:)": {
      "abstract": [
        {
          "text": "Gets the associated App Intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationIntent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Intent"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Intent"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Intent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/configurationIntent(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationIntent(of:)",
      "type": "topic",
      "url": "/documentation/widgetkit/controlinfo/configurationintent(of:)"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/kind": {
      "abstract": [
        {
          "text": "The string specified during creation of the control’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/kind",
      "kind": "symbol",
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/widgetkit/controlinfo/kind"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/pushInfo": {
      "abstract": [
        {
          "text": "Push information about a control, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit15ControlPushInfoV",
          "text": "ControlPushInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlInfo/pushInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "pushInfo",
      "type": "topic",
      "url": "/documentation/widgetkit/controlinfo/pushinfo"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler": {
      "abstract": [
        {
          "text": "A type that can receive push information about user-configured controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlPushHandler"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlPushHandler"
        }
      ],
      "role": "symbol",
      "title": "ControlPushHandler",
      "type": "topic",
      "url": "/documentation/widgetkit/controlpushhandler"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler/pushTokensDidChange(controls:)": {
      "abstract": [
        {
          "text": "Handle push tokens changing for configured controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushTokensDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "controls"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9WidgetKit11ControlInfoV",
          "text": "ControlInfo"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler/pushTokensDidChange(controls:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "pushTokensDidChange(controls:)",
      "type": "topic",
      "url": "/documentation/widgetkit/controlpushhandler/pushtokensdidchange(controls:)"
    },
    "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushInfo": {
      "abstract": [
        {
          "text": "A structure that contains information about the push token of a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "user-configured control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlPushInfo"
        }
      ],
      "identifier": "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlPushInfo"
        }
      ],
      "role": "symbol",
      "title": "ControlPushInfo",
      "type": "topic",
      "url": "/documentation/widgetkit/controlpushinfo"
    },
    "doc://com.apple.documentation/documentation/AppIntents/AppIntent/perform()": {
      "abstract": [
        {
          "text": "Performs the intent after resolving the provided parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents0A6IntentP13PerformResultQa",
          "text": "PerformResult"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppIntents/AppIntent/perform()",
      "kind": "symbol",
      "role": "symbol",
      "title": "perform()",
      "type": "topic",
      "url": "/documentation/AppIntents/AppIntent/perform()"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ControlWidgetConfiguration": {
      "abstract": [
        {
          "text": "A type that describes a control widget’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlWidgetConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ControlWidgetConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "ControlWidgetConfiguration",
      "type": "topic",
      "url": "/documentation/SwiftUI/ControlWidgetConfiguration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Control-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushHandler",
        "doc://com.apple.WidgetKit/documentation/WidgetKit/ControlPushInfo"
      ],
      "title": "Control updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Control-updates",
              "generated": true,
              "identifiers": [],
              "title": "Control updates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/widgetkit/updating-controls-locally-and-remotely"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/widgetkit/updating-controls-locally-and-remotely"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
