{
  "abstract": [
    {
      "text": "A tab’s placement when displayed in contexts that allow different placement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITab"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UITabPlacement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Placement"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Placement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITab.Placement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Placement"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab": {
      "abstract": [
        {
          "text": "An object that manages a tab in a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITab"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITab"
        }
      ],
      "role": "symbol",
      "title": "UITab",
      "type": "topic",
      "url": "/documentation/uikit/uitab"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement": {
      "abstract": [
        {
          "text": "A tab’s placement when displayed in contexts that allow different placement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic": {
      "abstract": [
        {
          "text": "The system adds only top-level items to the tab bar, but people can add, remove, or move this item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default": {
      "abstract": [
        {
          "text": "The item appears in the tab bar, but people can move or remove it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementDefault"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.default",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed": {
      "abstract": [
        {
          "text": "The item appears in the tab bar’s leading edge, and people can’t move or remove it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementFixed"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.fixed",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/fixed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable": {
      "abstract": [
        {
          "text": "The item appears in the tab bar, people can move it but can’t remove it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementMovable"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.movable",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/movable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional": {
      "abstract": [
        {
          "text": "The item doesn’t appear in the tab bar, but people can add it and move it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optional"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementOptional"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.optional",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/optional"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned": {
      "abstract": [
        {
          "text": "The item appears as a pinned tab, on the trailing edge of the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinned"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementPinned"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.pinned",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/pinned"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly": {
      "abstract": [
        {
          "text": "The item only appears in the sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebarOnly"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementSidebarOnly"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.sidebarOnly",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/sidebaronly"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/allowsHiding": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether people can hide a tab in a sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsHiding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/allowsHiding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsHiding"
        }
      ],
      "role": "symbol",
      "title": "allowsHiding",
      "type": "topic",
      "url": "/documentation/uikit/uitab/allowshiding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an item is hidden in a sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/uikit/uitab/ishidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/isHiddenByDefault": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an item is hidden by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHiddenByDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/isHiddenByDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hiddenByDefault"
        }
      ],
      "role": "symbol",
      "title": "isHiddenByDefault",
      "type": "topic",
      "url": "/documentation/uikit/uitab/ishiddenbydefault"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/preferredPlacement": {
      "abstract": [
        {
          "text": "The preferred placement for a tab when displayed in contexts that allow different placement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITabPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/preferredPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredPlacement"
        }
      ],
      "role": "symbol",
      "title": "preferredPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uitab/preferredplacement"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-customization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITab/isHidden",
        "doc://com.apple.uikit/documentation/UIKit/UITab/isHiddenByDefault",
        "doc://com.apple.uikit/documentation/UIKit/UITab/allowsHiding",
        "doc://com.apple.uikit/documentation/UIKit/UITab/preferredPlacement"
      ],
      "title": "Managing customization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Placement-values",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly"
      ],
      "title": "Placement values"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITabPlacement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Placement-values",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly"
              ],
              "title": "Placement values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-customization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITab/isHidden",
                "doc://com.apple.uikit/documentation/UIKit/UITab/isHiddenByDefault",
                "doc://com.apple.uikit/documentation/UIKit/UITab/allowsHiding",
                "doc://com.apple.uikit/documentation/UIKit/UITab/preferredPlacement"
              ],
              "title": "Managing customization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITabPlacement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1optional/title",
          "value": "UITabPlacementOptional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1optional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementOptional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1isHiddenByDefault/title",
          "value": "hiddenByDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1isHiddenByDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hiddenByDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1default/title",
          "value": "UITabPlacementDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1sidebarOnly/title",
          "value": "UITabPlacementSidebarOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1sidebarOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementSidebarOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1movable/title",
          "value": "UITabPlacementMovable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1movable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementMovable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/title",
          "value": "UITab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1automatic/title",
          "value": "UITabPlacementAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1preferredPlacement/title",
          "value": "preferredPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1preferredPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1fixed/title",
          "value": "UITabPlacementFixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1fixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementFixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1allowsHiding/title",
          "value": "allowsHiding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1allowsHiding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsHiding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement/title",
          "value": "UITabPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1pinned/title",
          "value": "UITabPlacementPinned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1pinned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementPinned"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitab/placement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitab/placement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
