{
  "abstract": [
    {
      "text": "An array of application-specific providers to add to the list of account providers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VSAccountMetadataRequest(py)applicationAccountProviders",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "applicationAccountProviders"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VSAccountApplicationProvider",
        "text": "VSAccountApplicationProvider"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applicationAccountProviders"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "applicationAccountProviders"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "applicationAccountProviders"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VSAccountApplicationProvider",
              "text": "VSAccountApplicationProvider"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider": {
      "abstract": [
        {
          "text": "An object to display app-specific providers in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountApplicationProvider"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountApplicationProvider"
        }
      ],
      "role": "symbol",
      "title": "VSAccountApplicationProvider",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountapplicationprovider"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest": {
      "abstract": [
        {
          "text": "An object that specifies what subscriber account information your app retrieves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountMetadataRequest"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountMetadataRequest"
        }
      ],
      "role": "symbol",
      "title": "VSAccountMetadataRequest",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders": {
      "abstract": [
        {
          "text": "An array of application-specific providers to add to the list of account providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationAccountProviders"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSAccountApplicationProvider",
          "text": "VSAccountApplicationProvider"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationAccountProviders"
        }
      ],
      "role": "symbol",
      "title": "applicationAccountProviders",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/applicationaccountproviders"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers": {
      "abstract": [
        {
          "text": "The providers your app lists prominently during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featuredAccountProviderIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featuredAccountProviderIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "featuredAccountProviderIdentifiers",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/featuredaccountprovideridentifiers"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app ignores cached credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceAuthentication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forceAuthentication"
        }
      ],
      "role": "symbol",
      "title": "forceAuthentication",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/forceauthentication"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can prompt the user to authenticate to complete the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInterruptionAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interruptionAllowed"
        }
      ],
      "role": "symbol",
      "title": "isInterruptionAllowed",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/isinterruptionallowed"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle": {
      "abstract": [
        {
          "text": "A short, user-presentable name for the video that the user wants to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedVideoTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedVideoTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedVideoTitle",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/localizedvideotitle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Additional-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle"
      ],
      "title": "Specifying Additional Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applicationAccountProviders"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationAccountProviders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Additional-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle"
              ],
              "title": "Specifying Additional Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<VSAccountApplicationProvider *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "applicationAccountProviders"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1forceAuthentication/title",
          "value": "forceAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1forceAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "forceAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountApplicationProvider/title",
          "value": "VSAccountApplicationProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountApplicationProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountApplicationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountApplicationProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountApplicationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1applicationAccountProviders/title",
          "value": "applicationAccountProviders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1applicationAccountProviders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationAccountProviders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1featuredAccountProviderIdentifiers/title",
          "value": "featuredAccountProviderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1featuredAccountProviderIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featuredAccountProviderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1localizedVideoTitle/title",
          "value": "localizedVideoTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1localizedVideoTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedVideoTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1isInterruptionAllowed/title",
          "value": "interruptionAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1isInterruptionAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interruptionAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest/title",
          "value": "VSAccountMetadataRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vsaccountmetadatarequest/applicationaccountproviders"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videosubscriberaccount/vsaccountmetadatarequest/applicationaccountproviders"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
