{
  "abstract": [
    {
      "text": "A quantity sample type that measures the amount of vitamin C consumed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminC"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKQuantityTypeIdentifierDietaryVitaminC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dietaryVitaminC"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
        "text": "HKQuantityTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKQuantityTypeIdentifierDietaryVitaminC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "dietaryVitaminC"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dietaryVitaminC"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These samples use mass units (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") and measure cumulative values (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity": {
      "abstract": [
        {
          "text": "An object that stores a value for a given unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle": {
      "abstract": [
        {
          "text": "Constant values that describe how quantities can be aggregated over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityAggregationStyle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityAggregationStyle"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityAggregationStyle",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityaggregationstyle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample": {
      "abstract": [
        {
          "text": "A sample that represents a quantity, including the value and the units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySample"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySample",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitysample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier": {
      "abstract": [
        {
          "text": "The identifiers that create quantity type objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryBiotin": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of biotin (vitamin B7) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryBiotin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryBiotin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryBiotin"
        }
      ],
      "role": "symbol",
      "title": "dietaryBiotin",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietarybiotin"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryFolate": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of folate (folic acid) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryFolate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryFolate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryFolate"
        }
      ],
      "role": "symbol",
      "title": "dietaryFolate",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryfolate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryNiacin": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of niacin (vitamin B3) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryNiacin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryNiacin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryNiacin"
        }
      ],
      "role": "symbol",
      "title": "dietaryNiacin",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryniacin"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryPantothenicAcid": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of pantothenic acid (vitamin B5) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryPantothenicAcid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryPantothenicAcid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryPantothenicAcid"
        }
      ],
      "role": "symbol",
      "title": "dietaryPantothenicAcid",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietarypantothenicacid"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryRiboflavin": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of riboflavin (vitamin B2) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryRiboflavin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryRiboflavin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryRiboflavin"
        }
      ],
      "role": "symbol",
      "title": "dietaryRiboflavin",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryriboflavin"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryThiamin": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of thiamin (vitamin B1) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryThiamin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryThiamin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryThiamin"
        }
      ],
      "role": "symbol",
      "title": "dietaryThiamin",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietarythiamin"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminA": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of vitamin A consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminA"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminA",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitamina"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB12": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of cyanocobalamin (vitamin B12) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminB12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminB12"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminB12",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitaminb12"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB6": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of pyridoxine (vitamin B6) consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminB6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminB6"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminB6",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitaminb6"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminC": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of vitamin C consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminC"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminC",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitaminc"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminD": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of vitamin D consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminD"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminD",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitamind"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminE": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of vitamin E consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminE"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminE",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitamine"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminK": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of vitamin K consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dietaryVitaminK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDietaryVitaminK"
        }
      ],
      "role": "symbol",
      "title": "dietaryVitaminK",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitamink"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUnit": {
      "abstract": [
        {
          "text": "A class for managing the units of measure within HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKUnit"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUnit"
        }
      ],
      "role": "symbol",
      "title": "HKUnit",
      "type": "topic",
      "url": "/documentation/healthkit/hkunit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Vitamins",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminA",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryThiamin",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryRiboflavin",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryNiacin",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryPantothenicAcid",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB6",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryBiotin",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB12",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminD",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminE",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminK",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryFolate"
      ],
      "title": "Vitamins"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminC"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Vitamins",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminA",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryThiamin",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryRiboflavin",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryNiacin",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryPantothenicAcid",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB6",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryBiotin",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminB12",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminD",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminE",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryVitaminK",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/dietaryFolate"
              ],
              "title": "Vitamins"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
                    "text": "HKQuantityTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKQuantityTypeIdentifierDietaryVitaminC"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/title",
          "value": "HKQuantityTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryRiboflavin/title",
          "value": "HKQuantityTypeIdentifierDietaryRiboflavin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryRiboflavin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryRiboflavin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminD/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminA/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryThiamin/title",
          "value": "HKQuantityTypeIdentifierDietaryThiamin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryThiamin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryThiamin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminC/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/title",
          "value": "HKUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/title",
          "value": "HKQuantitySample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/title",
          "value": "HKQuantityAggregationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityAggregationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityAggregationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminE/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title",
          "value": "HKQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminB12/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminB12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminB12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminB12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryNiacin/title",
          "value": "HKQuantityTypeIdentifierDietaryNiacin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryNiacin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryNiacin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminK/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminB6/title",
          "value": "HKQuantityTypeIdentifierDietaryVitaminB6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryVitaminB6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryVitaminB6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryBiotin/title",
          "value": "HKQuantityTypeIdentifierDietaryBiotin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryBiotin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryBiotin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryFolate/title",
          "value": "HKQuantityTypeIdentifierDietaryFolate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryFolate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryFolate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryPantothenicAcid/title",
          "value": "HKQuantityTypeIdentifierDietaryPantothenicAcid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1dietaryPantothenicAcid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDietaryPantothenicAcid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitaminc"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkquantitytypeidentifier/dietaryvitaminc"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
