{
  "abstract": [
    {
      "text": "A quantity sample type that measures the user’s heart rate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKQuantityTypeIdentifierHeartRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "heartRate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
        "text": "HKQuantityTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKQuantityTypeIdentifierHeartRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "heartRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "heartRate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions",
        "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These samples use count/time units (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") and measure discrete values (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Heart rate samples may include motion context information, which is stored as metadata using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key. The value of this key is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that contains a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The motion context gives additional information about the user’s activity level when the heart rate sample was taken. Apple Watch uses the following guidelines when setting the motion context:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the user has been still for at least 5 minutes prior to the sample, the context is set to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/sedentary",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the user is in motion, the context is set to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/active",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can add motion context to the metadata of any heart rate samples that you create. This means other apps may also save heart rate samples with (or without) the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " metadata key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that not all heart rate samples have a motion context. For example, if Apple Watch cannot determine the motion context, it creates samples without a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " metadata key. In addition, heart rate samples recorded by an Apple Watch (1st generation) or by a device running watchOS 3 or earlier do not have the motion context metadata key. Treat these samples as if they used the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/notSet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " motion context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent": {
      "abstract": [
        {
          "text": "A category sample type for high heart rate events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highHeartRateEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierHighHeartRateEvent"
        }
      ],
      "role": "symbol",
      "title": "highHeartRateEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/highheartrateevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent": {
      "abstract": [
        {
          "text": "A category sample type for irregular heart rhythm events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "irregularHeartRhythmEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
        }
      ],
      "role": "symbol",
      "title": "irregularHeartRhythmEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/irregularheartrhythmevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent": {
      "abstract": [
        {
          "text": "A category sample type for low heart rate events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowHeartRateEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierLowHeartRateEvent"
        }
      ],
      "role": "symbol",
      "title": "lowHeartRateEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/lowheartrateevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationTypeIdentifier/bloodPressure": {
      "abstract": [
        {
          "text": "A correlation sample that combines a systolic sample and a diastolic sample into a single blood pressure reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bloodPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCorrelationTypeIdentifier",
          "text": "HKCorrelationTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationTypeIdentifier/bloodPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCorrelationTypeIdentifierBloodPressure"
        }
      ],
      "role": "symbol",
      "title": "bloodPressure",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationtypeidentifier/bloodpressure"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierHeartbeatSeries": {
      "abstract": [
        {
          "text": "A series sample containing heartbeat data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDataTypeIdentifierHeartbeatSeries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierHeartbeatSeries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDataTypeIdentifierHeartbeatSeries"
        }
      ],
      "role": "symbol",
      "title": "HKDataTypeIdentifierHeartbeatSeries",
      "type": "topic",
      "url": "/documentation/healthkit/hkdatatypeidentifierheartbeatseries"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType": {
      "abstract": [
        {
          "text": "A type that identifies samples containing electrocardiogram data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramType"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogramType",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogramtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext": {
      "abstract": [
        {
          "text": "Values that indicate the user’s level of activity when the heart rate sample was measured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHeartRateMotionContext"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateMotionContext"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateMotionContext",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratemotioncontext"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/active": {
      "abstract": [
        {
          "text": "A value indicating that the user was in motion during the heart rate sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/active",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateMotionContextActive"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateMotionContext.active",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratemotioncontext/active"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/notSet": {
      "abstract": [
        {
          "text": "A value indicating that the user’s activity level could not be determined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/notSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateMotionContextNotSet"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateMotionContext.notSet",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratemotioncontext/notset"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/sedentary": {
      "abstract": [
        {
          "text": "A value indicating that the user has been still for at least 5 minutes prior to the heart rate sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sedentary"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartRateMotionContext/sedentary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartRateMotionContextSedentary"
        }
      ],
      "role": "symbol",
      "title": "HKHeartRateMotionContext.sedentary",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartratemotioncontext/sedentary"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext": {
      "abstract": [
        {
          "text": "The user’s activity level when the heart rate sample was measured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateMotionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateMotionContext"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateMotionContext",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartratemotioncontext"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation": {
      "abstract": [
        {
          "text": "The location where a specific heart rate reading was taken.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateSensorLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateSensorLocation"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateSensorLocation",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartratesensorlocation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity": {
      "abstract": [
        {
          "text": "An object that stores a value for a given unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle": {
      "abstract": [
        {
          "text": "Constant values that describe how quantities can be aggregated over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityAggregationStyle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityAggregationStyle"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityAggregationStyle",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityaggregationstyle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample": {
      "abstract": [
        {
          "text": "A sample that represents a quantity, including the value and the units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySample"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySample",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitysample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier": {
      "abstract": [
        {
          "text": "The identifiers that create quantity type objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/atrialFibrillationBurden": {
      "abstract": [
        {
          "text": "A quantity type that measures an estimate of the percentage of time a person’s heart shows signs of atrial fibrillation (AFib) while wearing Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atrialFibrillationBurden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/atrialFibrillationBurden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierAtrialFibrillationBurden"
        }
      ],
      "role": "symbol",
      "title": "atrialFibrillationBurden",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/atrialfibrillationburden"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureDiastolic": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s diastolic blood pressure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bloodPressureDiastolic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureDiastolic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierBloodPressureDiastolic"
        }
      ],
      "role": "symbol",
      "title": "bloodPressureDiastolic",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/bloodpressurediastolic"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureSystolic": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s systolic blood pressure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bloodPressureSystolic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureSystolic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierBloodPressureSystolic"
        }
      ],
      "role": "symbol",
      "title": "bloodPressureSystolic",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/bloodpressuresystolic"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bodyTemperature": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s body temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyTemperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bodyTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierBodyTemperature"
        }
      ],
      "role": "symbol",
      "title": "bodyTemperature",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/bodytemperature"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRate": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s heart rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierHeartRate"
        }
      ],
      "role": "symbol",
      "title": "heartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/heartrate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateRecoveryOneMinute": {
      "abstract": [
        {
          "text": "A quantity sample that records the reduction in heart rate from the peak exercise rate to the rate one minute after exercising ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartRateRecoveryOneMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateRecoveryOneMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute"
        }
      ],
      "role": "symbol",
      "title": "heartRateRecoveryOneMinute",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/heartraterecoveryoneminute"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateVariabilitySDNN": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the standard deviation of heartbeat intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartRateVariabilitySDNN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateVariabilitySDNN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
        }
      ],
      "role": "symbol",
      "title": "heartRateVariabilitySDNN",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/heartratevariabilitysdnn"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/oxygenSaturation": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s oxygen saturation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oxygenSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/oxygenSaturation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierOxygenSaturation"
        }
      ],
      "role": "symbol",
      "title": "oxygenSaturation",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/oxygensaturation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/restingHeartRate": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s resting heart rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restingHeartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/restingHeartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierRestingHeartRate"
        }
      ],
      "role": "symbol",
      "title": "restingHeartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/restingheartrate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/walkingHeartRateAverage": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s heart rate while walking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "walkingHeartRateAverage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/walkingHeartRateAverage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierWalkingHeartRateAverage"
        }
      ],
      "role": "symbol",
      "title": "walkingHeartRateAverage",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/walkingheartrateaverage"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUnit": {
      "abstract": [
        {
          "text": "A class for managing the units of measure within HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKUnit"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUnit"
        }
      ],
      "role": "symbol",
      "title": "HKUnit",
      "type": "topic",
      "url": "/documentation/healthkit/hkunit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples": {
      "abstract": [
        {
          "text": "Read series data from condensed workouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
      "kind": "article",
      "role": "article",
      "title": "Accessing condensed workout samples",
      "type": "topic",
      "url": "/documentation/healthkit/accessing-condensed-workout-samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions": {
      "abstract": [
        {
          "text": "Track a workout on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions",
      "kind": "article",
      "role": "article",
      "title": "Running workout sessions",
      "type": "topic",
      "url": "/documentation/healthkit/running-workout-sessions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Vital-signs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/restingHeartRate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateVariabilitySDNN",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateRecoveryOneMinute",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/atrialFibrillationBurden",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/walkingHeartRateAverage",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierHeartbeatSeries",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/oxygenSaturation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bodyTemperature",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationTypeIdentifier/bloodPressure",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureSystolic",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureDiastolic"
      ],
      "title": "Vital signs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Metadata-Keys",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext"
      ],
      "title": "Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKQuantityTypeIdentifierHeartRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Metadata-Keys",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext"
              ],
              "title": "Metadata Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Vital-signs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/restingHeartRate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateVariabilitySDNN",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRateRecoveryOneMinute",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/atrialFibrillationBurden",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/walkingHeartRateAverage",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierHeartbeatSeries",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/oxygenSaturation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bodyTemperature",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationTypeIdentifier/bloodPressure",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureSystolic",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodPressureDiastolic"
              ],
              "title": "Vital signs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
                    "text": "HKQuantityTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKQuantityTypeIdentifierHeartRate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bodyTemperature/title",
          "value": "HKQuantityTypeIdentifierBodyTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bodyTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierBodyTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bloodPressureSystolic/title",
          "value": "HKQuantityTypeIdentifierBloodPressureSystolic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bloodPressureSystolic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierBloodPressureSystolic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/title",
          "value": "HKQuantityTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1irregularHeartRhythmEvent/title",
          "value": "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1irregularHeartRhythmEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRate/title",
          "value": "HKQuantityTypeIdentifierHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/title",
          "value": "HKQuantitySample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext/title",
          "value": "HKHeartRateMotionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateMotionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateMotionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDataTypeIdentifierHeartbeatSeries/title",
          "value": "HKDataTypeIdentifierHeartbeatSeries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDataTypeIdentifierHeartbeatSeries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDataTypeIdentifierHeartbeatSeries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title",
          "value": "HKQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRateRecoveryOneMinute/title",
          "value": "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRateRecoveryOneMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationTypeIdentifier~1bloodPressure/title",
          "value": "HKCorrelationTypeIdentifierBloodPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationTypeIdentifier~1bloodPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationTypeIdentifierBloodPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramType/title",
          "value": "HKElectrocardiogramType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateMotionContext/title",
          "value": "HKMetadataKeyHeartRateMotionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateMotionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateMotionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext~1sedentary/title",
          "value": "HKHeartRateMotionContextSedentary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext~1sedentary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateMotionContextSedentary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1atrialFibrillationBurden/title",
          "value": "HKQuantityTypeIdentifierAtrialFibrillationBurden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1atrialFibrillationBurden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierAtrialFibrillationBurden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1walkingHeartRateAverage/title",
          "value": "HKQuantityTypeIdentifierWalkingHeartRateAverage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1walkingHeartRateAverage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierWalkingHeartRateAverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1restingHeartRate/title",
          "value": "HKQuantityTypeIdentifierRestingHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1restingHeartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierRestingHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1highHeartRateEvent/title",
          "value": "HKCategoryTypeIdentifierHighHeartRateEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1highHeartRateEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierHighHeartRateEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bloodPressureDiastolic/title",
          "value": "HKQuantityTypeIdentifierBloodPressureDiastolic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bloodPressureDiastolic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierBloodPressureDiastolic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/title",
          "value": "HKUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateSensorLocation/title",
          "value": "HKMetadataKeyHeartRateSensorLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateSensorLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext~1notSet/title",
          "value": "HKHeartRateMotionContextNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext~1notSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateMotionContextNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1oxygenSaturation/title",
          "value": "HKQuantityTypeIdentifierOxygenSaturation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1oxygenSaturation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierOxygenSaturation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRateVariabilitySDNN/title",
          "value": "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRateVariabilitySDNN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext~1active/title",
          "value": "HKHeartRateMotionContextActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartRateMotionContext~1active/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartRateMotionContextActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/title",
          "value": "HKQuantityAggregationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityAggregationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityAggregationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lowHeartRateEvent/title",
          "value": "HKCategoryTypeIdentifierLowHeartRateEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lowHeartRateEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierLowHeartRateEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkquantitytypeidentifier/heartrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkquantitytypeidentifier/heartrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
