{
  "abstract": [
    {
      "text": "A quantity sample type that measures the number of standard alcoholic drinks that the user has consumed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/numberOfAlcoholicBeverages"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKQuantityTypeIdentifierNumberOfAlcoholicBeverages",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "numberOfAlcoholicBeverages"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
        "text": "HKQuantityTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "numberOfAlcoholicBeverages"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfAlcoholicBeverages"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Samples matching the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/numberOfAlcoholicBeverages",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " identifier measure the number of standard alcoholic drinks consumed by the user. A standard drink is one beer, glass of wine, or mixed drink made with spirits. The samples use count units (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") to measure cumulative values (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code listing saves a single standard drink to the HealthKit store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the alcoholic beverage sample type.",
            "let alcoholConsumptionType = HKQuantityType(.numberOfAlcoholicBeverages)",
            "",
            "// Create a quantity for the number of standard beverages consumed.",
            "let beverageCount = HKQuantity(unit:HKUnit.count(), doubleValue:1.0)",
            "",
            "// Get the current date.",
            "let date = Date()",
            "",
            "// Create the alcoholic beverage consumption sample.",
            "let beverageSample = HKQuantitySample(type: alcoholConsumptionType,",
            "                                      quantity: beverageCount,",
            "                                      start: date,",
            "                                      end: date)",
            "",
            "// Save the sample to the HealthKit store.",
            "store.save(beverageSample) { (success, error) in",
            "    ",
            "    if success {",
            "        // The system successfully saved the sample.",
            "        ",
            "    } else {",
            "        if let error = error {",
            "            // Handle the error here.",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle": {
      "abstract": [
        {
          "text": "Constant values that describe how quantities can be aggregated over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityAggregationStyle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityAggregationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityAggregationStyle"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityAggregationStyle",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityaggregationstyle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier": {
      "abstract": [
        {
          "text": "The identifiers that create quantity type objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodAlcoholContent": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s blood alcohol content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bloodAlcoholContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodAlcoholContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierBloodAlcoholContent"
        }
      ],
      "role": "symbol",
      "title": "bloodAlcoholContent",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/bloodalcoholcontent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/numberOfAlcoholicBeverages": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the number of standard alcoholic drinks that the user has consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfAlcoholicBeverages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/numberOfAlcoholicBeverages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
        }
      ],
      "role": "symbol",
      "title": "numberOfAlcoholicBeverages",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/numberofalcoholicbeverages"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUnit": {
      "abstract": [
        {
          "text": "A class for managing the units of measure within HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKUnit"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUnit"
        }
      ],
      "role": "symbol",
      "title": "HKUnit",
      "type": "topic",
      "url": "/documentation/healthkit/hkunit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Alcohol-consumption",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodAlcoholContent"
      ],
      "title": "Alcohol consumption"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Alcohol-consumption",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/bloodAlcoholContent"
              ],
              "title": "Alcohol consumption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
                    "text": "HKQuantityTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1numberOfAlcoholicBeverages/title",
          "value": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1numberOfAlcoholicBeverages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/title",
          "value": "HKQuantityAggregationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityAggregationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityAggregationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityAggregationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/title",
          "value": "HKQuantityTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/title",
          "value": "HKUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bloodAlcoholContent/title",
          "value": "HKQuantityTypeIdentifierBloodAlcoholContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1bloodAlcoholContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierBloodAlcoholContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkquantitytypeidentifier/numberofalcoholicbeverages"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkquantitytypeidentifier/numberofalcoholicbeverages"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
