{"abstract":[{"text":"The Auto Layout priority that results in detachment of a view when there is insufficient space in the stack view to display it fully.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachOnlyIfNecessary"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier","text":"NSStackView"},{"text":".","kind":"text"},{"text":"VisibilityPriority","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/visibilitypriority/detachonlyifnecessary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/visibilitypriority/detachonlyifnecessary"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary"},"metadata":{"role":"symbol","title":"detachOnlyIfNecessary","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachOnlyIfNecessary"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"}],"modules":[{"name":"AppKit"}],"roleHeading":"Type Property","symbolKind":"property","extendedModule":"AppKit","externalID":"c:@NSStackViewVisibilityPriorityDetachOnlyIfNecessary","platforms":[{"name":"macOS","introducedAt":"10.9","beta":false,"unavailable":false,"deprecated":false}]},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary":{"kind":"symbol","type":"topic","title":"detachOnlyIfNecessary","role":"symbol","abstract":[{"text":"The Auto Layout priority that results in detachment of a view when there is insufficient space in the stack view to display it fully.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detachOnlyIfNecessary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","url":"/documentation/appkit/nsstackview/visibilitypriority/detachonlyifnecessary"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold":{"kind":"symbol","type":"topic","title":"mustHold","role":"symbol","abstract":[{"type":"text","text":"The default value, and maximum Auto Layout priority, that results in a view never detaching from the stack view."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mustHold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold","url":"/documentation/appkit/nsstackview/visibilitypriority/musthold"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible":{"kind":"symbol","type":"topic","title":"notVisible","role":"symbol","abstract":[{"text":"The minimum Auto Layout priority that forces a view to detach from the stack view.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityNotVisible"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible","url":"/documentation/appkit/nsstackview/visibilitypriority/notvisible"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority":{"kind":"symbol","type":"topic","title":"NSStackView.VisibilityPriority","role":"symbol","abstract":[{"text":"The various Auto Layout priorities for a view in the stack view to remain attached.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisibilityPriority","kind":"identifier"}],"navigatorTitle":[{"text":"VisibilityPriority","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","url":"/documentation/appkit/nsstackview/visibilitypriority"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","introducedAt":"10.9","deprecated":false,"unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","value":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"value":[{"text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","text":"NSStackViewVisibilityPriority","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1detachOnlyIfNecessary/title","op":"replace"},{"value":[{"text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1detachOnlyIfNecessary/fragments","op":"replace"},{"value":"NSStackViewVisibilityPriorityMustHold","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/fragments","op":"replace"},{"value":"NSStackViewVisibilityPriorityNotVisible","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1notVisible/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityNotVisible"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1notVisible/fragments","op":"replace"},{"value":"NSStackView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","op":"replace"},{"value":[{"text":"NSStackView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","op":"replace"},{"value":[{"text":"NSStackView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","op":"replace"},{"value":"NSStackViewVisibilityPriority","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSStackViewVisibilityPriority"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/fragments"},{"value":[{"kind":"identifier","text":"NSStackViewVisibilityPriority"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}