{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/visibilitypriority/musthold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/visibilitypriority/musthold"]}],"metadata":{"role":"symbol","extendedModule":"AppKit","symbolKind":"property","roleHeading":"Type Property","platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"10.9","beta":false,"name":"macOS"}],"externalID":"c:@NSStackViewVisibilityPriorityMustHold","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mustHold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VisibilityPriority","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority"}],"title":"mustHold","navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"modules":[{"name":"AppKit"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mustHold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"abstract":[{"type":"text","text":"The default value, and maximum Auto Layout priority, that results in a view never detaching from the stack view."}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold":{"kind":"symbol","type":"topic","title":"mustHold","role":"symbol","abstract":[{"type":"text","text":"The default value, and maximum Auto Layout priority, that results in a view never detaching from the stack view."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mustHold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold","url":"/documentation/appkit/nsstackview/visibilitypriority/musthold"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority":{"kind":"symbol","type":"topic","title":"NSStackView.VisibilityPriority","role":"symbol","abstract":[{"text":"The various Auto Layout priorities for a view in the stack view to remain attached.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisibilityPriority","kind":"identifier"}],"navigatorTitle":[{"text":"VisibilityPriority","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","url":"/documentation/appkit/nsstackview/visibilitypriority"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible":{"kind":"symbol","type":"topic","title":"notVisible","role":"symbol","abstract":[{"text":"The minimum Auto Layout priority that forces a view to detach from the stack view.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityNotVisible"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible","url":"/documentation/appkit/nsstackview/visibilitypriority/notvisible"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary":{"kind":"symbol","type":"topic","title":"detachOnlyIfNecessary","role":"symbol","abstract":[{"text":"The Auto Layout priority that results in detachment of a view when there is insufficient space in the stack view to display it fully.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detachOnlyIfNecessary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","url":"/documentation/appkit/nsstackview/visibilitypriority/detachonlyifnecessary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"deprecated":false,"introducedAt":"10.9","beta":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Global Variable"},{"value":"NSStackViewVisibilityPriorityMustHold","path":"/metadata/title","op":"replace"},{"value":"var","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","text":"NSStackViewVisibilityPriority"},{"text":" ","kind":"text"},{"text":"NSStackViewVisibilityPriorityMustHold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"NSStackViewVisibilityPriorityMustHold","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/fragments"},{"op":"replace","value":"NSStackViewVisibilityPriority","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackViewVisibilityPriority"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/navigatorTitle","op":"replace","value":[{"text":"NSStackViewVisibilityPriority","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1notVisible/title","op":"replace","value":"NSStackViewVisibilityPriorityNotVisible"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1notVisible/fragments","op":"replace","value":[{"text":"NSStackViewVisibilityPriorityNotVisible","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","op":"replace","value":"NSStackView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSStackView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1detachOnlyIfNecessary/title","op":"replace","value":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1detachOnlyIfNecessary/fragments","op":"replace","value":[{"text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}