{"kind":"symbol","metadata":{"platforms":[{"introducedAt":"10.9","beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"AppKit"}],"externalID":"c:@NSStackViewVisibilityPriorityNotVisible","navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityNotVisible"}],"title":"notVisible","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier","text":"NSStackView"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","kind":"typeIdentifier","text":"VisibilityPriority"}],"role":"symbol","extendedModule":"AppKit"},"seeAlsoSections":[{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/visibilitypriority/notvisible"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/visibilitypriority/notvisible"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The minimum Auto Layout priority that forces a view to detach from the stack view."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notVisible"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","kind":"typeIdentifier","text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","kind":"typeIdentifier","text":"VisibilityPriority","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority"}],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority":{"kind":"symbol","type":"topic","title":"NSStackView.VisibilityPriority","role":"symbol","abstract":[{"text":"The various Auto Layout priorities for a view in the stack view to remain attached.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisibilityPriority","kind":"identifier"}],"navigatorTitle":[{"text":"VisibilityPriority","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","url":"/documentation/appkit/nsstackview/visibilitypriority"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary":{"kind":"symbol","type":"topic","title":"detachOnlyIfNecessary","role":"symbol","abstract":[{"text":"The Auto Layout priority that results in detachment of a view when there is insufficient space in the stack view to display it fully.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detachOnlyIfNecessary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","url":"/documentation/appkit/nsstackview/visibilitypriority/detachonlyifnecessary"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible":{"kind":"symbol","type":"topic","title":"notVisible","role":"symbol","abstract":[{"text":"The minimum Auto Layout priority that forces a view to detach from the stack view.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityNotVisible"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/notVisible","url":"/documentation/appkit/nsstackview/visibilitypriority/notvisible"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold":{"kind":"symbol","type":"topic","title":"mustHold","role":"symbol","abstract":[{"type":"text","text":"The default value, and maximum Auto Layout priority, that results in a view never detaching from the stack view."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mustHold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority"}],"navigatorTitle":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold","url":"/documentation/appkit/nsstackview/visibilitypriority/musthold"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","value":[{"introducedAt":"10.9","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"NSStackViewVisibilityPriorityNotVisible","op":"replace"},{"value":"var","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"NSStackViewVisibilityPriorityNotVisible","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/detachOnlyIfNecessary","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold"],"anchor":"Type-Properties","title":"Type Properties"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackViewVisibilityPriority","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSStackViewVisibilityPriority"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSStackViewVisibilityPriorityNotVisible"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/title","value":"NSStackViewVisibilityPriority"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/fragments","value":[{"text":"NSStackViewVisibilityPriority","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/navigatorTitle","value":[{"kind":"identifier","text":"NSStackViewVisibilityPriority"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","value":"NSStackView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","value":[{"kind":"identifier","text":"NSStackView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","value":[{"text":"NSStackView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1detachOnlyIfNecessary/title","value":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1detachOnlyIfNecessary/fragments","value":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityDetachOnlyIfNecessary"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1notVisible/title","value":"NSStackViewVisibilityPriorityNotVisible"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1notVisible/fragments","value":[{"text":"NSStackViewVisibilityPriorityNotVisible","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/title","value":"NSStackViewVisibilityPriorityMustHold"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/fragments","value":[{"kind":"identifier","text":"NSStackViewVisibilityPriorityMustHold"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}