{
  "abstract": [
    {
      "text": "A class that defines a set of methods for saving and restoring user defaults for screen savers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screensaver/documentation/ScreenSaver"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ScreenSaverDefaults",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ScreenSaverDefaults"
      }
    ],
    "modules": [
      {
        "name": "Screen Saver"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ScreenSaverDefaults"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ScreenSaverDefaults"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ScreenSaverDefaults"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " gives you access to preference values you need to configure your screen saver. Because multiple apps can load a screen saver, you can’t use the standard ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to store preferences. Instead, instantiate this class using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults/init(forModuleWithName:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which takes your screen saver’s bundle identifier as a parameter. The resulting object gives you a way to store your preference values and associate them only with your screen saver. Use the inherited ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods to load, store, or modify values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/userdefaults": {
      "abstract": [
        {
          "text": "An interface to the user’s defaults database, where you store key-value pairs persistently across launches of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "UserDefaults"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "UserDefaults",
      "type": "topic",
      "url": "/documentation/foundation/userdefaults"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver": {
      "abstract": [
        {
          "text": "Animate screen savers, and interact with the screen saver infrastructure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver",
      "kind": "symbol",
      "role": "collection",
      "title": "Screen Saver",
      "type": "topic",
      "url": "/documentation/screensaver"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults": {
      "abstract": [
        {
          "text": "A class that defines a set of methods for saving and restoring user defaults for screen savers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScreenSaverDefaults"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScreenSaverDefaults"
        }
      ],
      "role": "symbol",
      "title": "ScreenSaverDefaults",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverdefaults"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults/init(forModuleWithName:)": {
      "abstract": [
        {
          "text": "Returns a screen saver defaults instance that reads and writes defaults for the specified module.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "forModuleWithName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults/init(forModuleWithName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultsForModuleWithName:"
        }
      ],
      "role": "symbol",
      "title": "init(forModuleWithName:)",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverdefaults/init(formodulewithname:)"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for subclassers to interact with the screen saver infrastructure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScreenSaverView"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScreenSaverView"
        }
      ],
      "role": "symbol",
      "title": "ScreenSaverView",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSUserDefaults": {
      "abstract": [
        {
          "text": "An interface to the user’s defaults database, where you store key-value pairs persistently across launches of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "UserDefaults"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUserDefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "UserDefaults",
      "type": "topic",
      "url": "/documentation/foundation/userdefaults"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSUserDefaults"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView"
      ],
      "title": "Interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-screen-saver-defaults",
      "identifiers": [
        "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults/init(forModuleWithName:)"
      ],
      "title": "Creating the screen saver defaults"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ScreenSaverDefaults"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screensaver/documentation/ScreenSaver"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-screen-saver-defaults",
              "identifiers": [
                "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverDefaults/init(forModuleWithName:)"
              ],
              "title": "Creating the screen saver defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSUserDefaults"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView"
              ],
              "title": "Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ScreenSaverDefaults"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUserDefaults",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUserDefaults",
                    "text": "NSUserDefaults"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverDefaults~1init(forModuleWithName:)/title",
          "value": "defaultsForModuleWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverDefaults~1init(forModuleWithName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultsForModuleWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1userdefaults/title",
          "value": "NSUserDefaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView/title",
          "value": "ScreenSaverView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverDefaults/title",
          "value": "ScreenSaverDefaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverDefaults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverDefaults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSUserDefaults/title",
          "value": "NSUserDefaults"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screensaver/screensaverdefaults"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screensaver/screensaverdefaults"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
