{
  "abstract": [
    {
      "text": "The function for reporting parameter errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/reportError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SparseSymbolicFactorOptions@FI@reportError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reportError"
      },
      {
        "kind": "text",
        "text": ": (("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reportError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "reportError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reportError"
            },
            {
              "kind": "text",
              "text": ": (("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If this value is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the system reports errors using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/os_log_error",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and then ",
              "type": "text"
            },
            {
              "code": "__builtin_trap()",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t": {
      "abstract": [
        {
          "text": "Options that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "role": "symbol",
      "title": "SparseControl_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecontrol_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOrder_t": {
      "abstract": [
        {
          "text": "Options that define which ordering algorithm to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOrder_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOrder_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOrder_t"
        }
      ],
      "role": "symbol",
      "title": "SparseOrder_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparseorder_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions": {
      "abstract": [
        {
          "text": "A structure that contains options that affect the symbolic stage of a sparse factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSymbolicFactorOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSymbolicFactorOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseSymbolicFactorOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/control": {
      "abstract": [
        {
          "text": "The flags that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "control"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseControl_t",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/control",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "control"
        }
      ],
      "role": "symbol",
      "title": "control",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/control"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/free": {
      "abstract": [
        {
          "text": "The function for freeing allocated storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "free"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/free",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "free"
        }
      ],
      "role": "symbol",
      "title": "free",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/free"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/ignoreRowsAndColumns": {
      "abstract": [
        {
          "text": "An array that contains row and column indices to ignore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoreRowsAndColumns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/ignoreRowsAndColumns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoreRowsAndColumns"
        }
      ],
      "role": "symbol",
      "title": "ignoreRowsAndColumns",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/ignorerowsandcolumns"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/malloc": {
      "abstract": [
        {
          "text": "The function for allocating any necessary storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malloc"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/malloc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "malloc"
        }
      ],
      "role": "symbol",
      "title": "malloc",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/malloc"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/order": {
      "abstract": [
        {
          "text": "The user-supplied array for ordering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "order"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/order",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "order"
        }
      ],
      "role": "symbol",
      "title": "order",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/order"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/orderMethod": {
      "abstract": [
        {
          "text": "The ordering algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orderMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseOrder_t",
          "text": "SparseOrder_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/orderMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orderMethod"
        }
      ],
      "role": "symbol",
      "title": "orderMethod",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/ordermethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/reportError": {
      "abstract": [
        {
          "text": "The function for reporting parameter errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportError"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/reportError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportError"
        }
      ],
      "role": "symbol",
      "title": "reportError",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions/reporterror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods": {
      "abstract": [
        {
          "text": "Use direct methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using direct methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-direct-methods"
    },
    "doc://com.apple.documentation/documentation/os/os_log_error": {
      "abstract": [
        {
          "text": "Sends an error-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "#define"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log_error"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "internalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "internalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ", ...)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/os_log_error",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_error",
      "type": "topic",
      "url": "/documentation/os/os_log_error"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Symbolic-Factor-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/control",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/orderMethod",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/order",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOrder_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/ignoreRowsAndColumns",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/malloc",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/free"
      ],
      "title": "Inspecting Symbolic Factor Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "reportError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Symbolic-Factor-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/control",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/orderMethod",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/order",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOrder_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/ignoreRowsAndColumns",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/malloc",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions/free"
              ],
              "title": "Inspecting Symbolic Factor Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*1C)",
                    "text": "void (*)(const char *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "reportError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1ignoreRowsAndColumns/title",
          "value": "ignoreRowsAndColumns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1ignoreRowsAndColumns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoreRowsAndColumns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1orderMethod/title",
          "value": "orderMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1orderMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orderMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1reportError/title",
          "value": "reportError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1reportError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1malloc/title",
          "value": "malloc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1malloc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "malloc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1free/title",
          "value": "free"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1free/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "free"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/title",
          "value": "SparseSymbolicFactorOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSymbolicFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSymbolicFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1control/title",
          "value": "control"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1control/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/title",
          "value": "SparseControl_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOrder_t/title",
          "value": "SparseOrder_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOrder_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOrder_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOrder_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOrder_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1order/title",
          "value": "order"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions~1order/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "order"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsesymbolicfactoroptions/reporterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparsesymbolicfactoroptions/reporterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
