{
  "abstract": [
    {
      "text": "The context describing where your iMessage app is presented.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSMessagesAppViewController(py)presentationContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "presentationContext"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MSMessagesAppPresentationContext",
        "text": "MSMessagesAppPresentationContext"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "presentationContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "presentationContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "presentationContext"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MSMessagesAppPresentationContext",
              "text": "MSMessagesAppPresentationContext"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the system only displays iMessage apps in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/messages",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " context (the iMessage app only appears inside the Messages app). iMessage apps in the media context have additional limitations and design considerations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can control the supported contexts by adding the ",
              "type": "text"
            },
            {
              "code": "MSSupportedPresentationContexts",
              "type": "codeVoice"
            },
            {
              "text": " key to the iMessage app extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. For example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enables the iMessage app in effects in Messages and FaceTime.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>MSSupportedPresentationContexts</key>",
            "<array>",
            "  <string>MSMessagesAppPresentationContextMessages</string>",
            "  <string>MSMessagesAppPresentationContextMedia</string>",
            "</array>"
          ],
          "syntax": "plist",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext": {
      "abstract": [
        {
          "text": "Presentation contexts describing where your iMessage app appears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContext"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationContext",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationcontext"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/messages": {
      "abstract": [
        {
          "text": "A constant that indicates the iMessage app appears in Messages in the list of iMessage apps that appears when you press the plus button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messages"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/messages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContextMessages"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationContext.messages",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationcontext/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle": {
      "abstract": [
        {
          "text": "Presentation styles that describe your iMessage app’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationStyle",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationstyle"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController": {
      "abstract": [
        {
          "text": "The principal view controller for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppViewController",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/didTransition(to:)": {
      "abstract": [
        {
          "text": "Tells the view controller that the extension has transitioned to a new presentation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didTransition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MSMessagesAppPresentationStyle",
          "text": "MSMessagesAppPresentationStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/didTransition(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didTransitionToPresentationStyle:"
        }
      ],
      "role": "symbol",
      "title": "didTransition(to:)",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller/didtransition(to:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationContext": {
      "abstract": [
        {
          "text": "The context describing where your iMessage app is presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MSMessagesAppPresentationContext",
          "text": "MSMessagesAppPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationContext"
        }
      ],
      "role": "symbol",
      "title": "presentationContext",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller/presentationcontext"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle": {
      "abstract": [
        {
          "text": "The extension’s current presentation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MSMessagesAppPresentationStyle",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationStyle"
        }
      ],
      "role": "symbol",
      "title": "presentationStyle",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller/presentationstyle"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/requestPresentationStyle(_:)": {
      "abstract": [
        {
          "text": "Asks the extension’s user interface to transition to the provided style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestPresentationStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MSMessagesAppPresentationStyle",
          "text": "MSMessagesAppPresentationStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/requestPresentationStyle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestPresentationStyle:"
        }
      ],
      "role": "symbol",
      "title": "requestPresentationStyle(_:)",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller/requestpresentationstyle(_:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/willTransition(to:)": {
      "abstract": [
        {
          "text": "Tells the view controller that the extension is about to transition to a new presentation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willTransition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MSMessagesAppPresentationStyle",
          "text": "MSMessagesAppPresentationStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/willTransition(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willTransitionToPresentationStyle:"
        }
      ],
      "role": "symbol",
      "title": "willTransition(to:)",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller/willtransition(to:)"
    },
    "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime": {
      "abstract": [
        {
          "text": "Enable your Sticker pack or iMessage app in the media context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime",
      "kind": "article",
      "role": "article",
      "title": "Adding Sticker packs and iMessage apps to the system Stickers app, Messages camera, and FaceTime",
      "type": "topic",
      "url": "/documentation/messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Presentation-Styles-and-Contexts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/requestPresentationStyle(_:)",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/willTransition(to:)",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/didTransition(to:)",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext"
      ],
      "title": "Working with Presentation Styles and Contexts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "presentationContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Presentation-Styles-and-Contexts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/requestPresentationStyle(_:)",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/willTransition(to:)",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/didTransition(to:)",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext"
              ],
              "title": "Working with Presentation Styles and Contexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MSMessagesAppPresentationContext",
                    "text": "MSMessagesAppPresentationContext"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "presentationContext"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext~1messages/title",
          "value": "MSMessagesAppPresentationContextMessages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext~1messages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContextMessages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1didTransition(to:)/title",
          "value": "didTransitionToPresentationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1didTransition(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didTransitionToPresentationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/title",
          "value": "MSMessagesAppViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1presentationStyle/title",
          "value": "presentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1presentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1willTransition(to:)/title",
          "value": "willTransitionToPresentationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1willTransition(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willTransitionToPresentationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/title",
          "value": "MSMessagesAppPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1requestPresentationStyle(_:)/title",
          "value": "requestPresentationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1requestPresentationStyle(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestPresentationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1presentationContext/title",
          "value": "presentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1presentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext/title",
          "value": "MSMessagesAppPresentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msmessagesappviewcontroller/presentationcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msmessagesappviewcontroller/presentationcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
