{
  "abstract": [
    {
      "text": "Do not add the app or documents to the Recents menu.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use -[NSWorkspaceOpenConfiguration setAddsToRecentItems:YES] instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutAddingToRecents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWorkspaceLaunchOptions@NSWorkspaceLaunchWithoutAddingToRecents",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "withoutAddingToRecents"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWorkspace",
        "text": "NSWorkspace"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
        "text": "LaunchOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWorkspaceLaunchWithoutAddingToRecents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.3",
        "message": "Use -[NSWorkspaceOpenConfiguration setAddsToRecentItems:YES] instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "withoutAddingToRecents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withoutAddingToRecents"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWorkspace",
              "text": "NSWorkspace"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
              "text": "LaunchOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions": {
      "abstract": [
        {
          "text": "Constants specifying how you want to launch an app",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LaunchOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace.LaunchOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/allowingClassicStartup": {
      "abstract": [
        {
          "text": "Start up the Classic compatibility environment, if it is required by the app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowingClassicStartup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/allowingClassicStartup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchAllowingClassicStartup"
        }
      ],
      "role": "symbol",
      "title": "allowingClassicStartup",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/allowingclassicstartup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHide": {
      "abstract": [
        {
          "text": "Tell the app to hide itself as soon as it finishes launching.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "andHide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchAndHide"
        }
      ],
      "role": "symbol",
      "title": "andHide",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/andhide"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHideOthers": {
      "abstract": [
        {
          "text": "Hide all apps except the newly launched one.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "andHideOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHideOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchAndHideOthers"
        }
      ],
      "role": "symbol",
      "title": "andHideOthers",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/andhideothers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andPrint": {
      "abstract": [
        {
          "text": "Print items instead of opening them.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "andPrint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andPrint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchAndPrint"
        }
      ],
      "role": "symbol",
      "title": "andPrint",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/andprint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/async": {
      "abstract": [
        {
          "text": "Launch the app and return the results asynchronously.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "async"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/async",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchAsync"
        }
      ],
      "role": "symbol",
      "title": "async",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/async"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/default": {
      "abstract": [
        {
          "text": "Launch the app asynchronously and launch it in the Classic environment, if required.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/inhibitingBackgroundOnly": {
      "abstract": [
        {
          "text": "Causes launch to fail if the target is background-only.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inhibitingBackgroundOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/inhibitingBackgroundOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchInhibitingBackgroundOnly"
        }
      ],
      "role": "symbol",
      "title": "inhibitingBackgroundOnly",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/inhibitingbackgroundonly"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/newInstance": {
      "abstract": [
        {
          "text": "Create a new instance of the app, even if one is already running.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newInstance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/newInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchNewInstance"
        }
      ],
      "role": "symbol",
      "title": "newInstance",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/newinstance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/preferringClassic": {
      "abstract": [
        {
          "text": "Force the app to launch in the Classic compatibility environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferringClassic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/preferringClassic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchPreferringClassic"
        }
      ],
      "role": "symbol",
      "title": "preferringClassic",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/preferringclassic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withErrorPresentation": {
      "abstract": [
        {
          "text": "Display an error panel to the user if a failure occurs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withErrorPresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withErrorPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchWithErrorPresentation"
        }
      ],
      "role": "symbol",
      "title": "withErrorPresentation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/witherrorpresentation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutActivation": {
      "abstract": [
        {
          "text": "Launch the app but do not bring it into the foreground.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withoutActivation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchWithoutActivation"
        }
      ],
      "role": "symbol",
      "title": "withoutActivation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/withoutactivation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutAddingToRecents": {
      "abstract": [
        {
          "text": "Do not add the app or documents to the Recents menu.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withoutAddingToRecents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceLaunchOptions",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutAddingToRecents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLaunchWithoutAddingToRecents"
        }
      ],
      "role": "symbol",
      "title": "withoutAddingToRecents",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/launchoptions/withoutaddingtorecents"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andPrint",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withErrorPresentation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/inhibitingBackgroundOnly",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutActivation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/async",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/allowingClassicStartup",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/preferringClassic",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/newInstance",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHide",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHideOthers",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/default"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWorkspaceLaunchWithoutAddingToRecents"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchWithoutAddingToRecents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andPrint",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withErrorPresentation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/inhibitingBackgroundOnly",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/withoutActivation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/async",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/allowingClassicStartup",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/preferringClassic",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/newInstance",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHide",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/andHideOthers",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/LaunchOptions/default"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWorkspaceLaunchWithoutAddingToRecents"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use -[NSWorkspaceOpenConfiguration setAddsToRecentItems:YES] instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title",
          "value": "NSWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1allowingClassicStartup/title",
          "value": "NSWorkspaceLaunchAllowingClassicStartup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1allowingClassicStartup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchAllowingClassicStartup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1default/title",
          "value": "NSWorkspaceLaunchDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1inhibitingBackgroundOnly/title",
          "value": "NSWorkspaceLaunchInhibitingBackgroundOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1inhibitingBackgroundOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchInhibitingBackgroundOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1withErrorPresentation/title",
          "value": "NSWorkspaceLaunchWithErrorPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1withErrorPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchWithErrorPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1withoutActivation/title",
          "value": "NSWorkspaceLaunchWithoutActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1withoutActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchWithoutActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1newInstance/title",
          "value": "NSWorkspaceLaunchNewInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1newInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchNewInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1preferringClassic/title",
          "value": "NSWorkspaceLaunchPreferringClassic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1preferringClassic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchPreferringClassic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1andHide/title",
          "value": "NSWorkspaceLaunchAndHide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1andHide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchAndHide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1withoutAddingToRecents/title",
          "value": "NSWorkspaceLaunchWithoutAddingToRecents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1withoutAddingToRecents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchWithoutAddingToRecents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1andHideOthers/title",
          "value": "NSWorkspaceLaunchAndHideOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1andHideOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchAndHideOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1async/title",
          "value": "NSWorkspaceLaunchAsync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1async/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions/title",
          "value": "NSWorkspaceLaunchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1andPrint/title",
          "value": "NSWorkspaceLaunchAndPrint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1LaunchOptions~1andPrint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLaunchAndPrint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsworkspace/launchoptions/withoutaddingtorecents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsworkspace/launchoptions/withoutaddingtorecents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
