{
  "abstract": [
    {
      "text": "The media type of the port.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/mediaType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureInputPort(py)mediaType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMediaType",
        "text": "AVMediaType"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mediaType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mediaType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMediaType",
              "text": "AVMediaType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput": {
      "abstract": [
        {
          "text": "An abstract superclass for objects that provide input data to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port": {
      "abstract": [
        {
          "text": "An object that represents a stream of data that a capture input provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Port"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Port"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureInput.Port",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/clock": {
      "abstract": [
        {
          "text": "An object that represents the capture device’s clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/clock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clock"
        }
      ],
      "role": "symbol",
      "title": "clock",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port/clock"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/formatDescription": {
      "abstract": [
        {
          "text": "A description of the port format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/formatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "formatDescription"
        }
      ],
      "role": "symbol",
      "title": "formatDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port/formatdescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the port is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port/isenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/mediaType": {
      "abstract": [
        {
          "text": "The media type of the port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaType",
          "text": "AVMediaType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/mediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaType"
        }
      ],
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port/mediatype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDevicePosition": {
      "abstract": [
        {
          "text": "The position of the source device providing input through this port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDevicePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureDevicePosition",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDevicePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceDevicePosition"
        }
      ],
      "role": "symbol",
      "title": "sourceDevicePosition",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port/sourcedeviceposition"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDeviceType": {
      "abstract": [
        {
          "text": "The device type of the source camera that provides data to the port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureDeviceType",
          "text": "DeviceType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceDeviceType"
        }
      ],
      "role": "symbol",
      "title": "sourceDeviceType",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput/port/sourcedevicetype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType": {
      "abstract": [
        {
          "text": "An identifier for various media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaType"
        }
      ],
      "role": "symbol",
      "title": "AVMediaType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediatype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-Input-Port",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/isEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/formatDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDeviceType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDevicePosition",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/clock"
      ],
      "title": "Inspecting an Input Port"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-Input-Port",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/isEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/formatDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDeviceType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/sourceDevicePosition",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput/Port/clock"
              ],
              "title": "Inspecting an Input Port"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMediaType",
                    "text": "AVMediaType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mediaType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1clock/title",
          "value": "clock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1clock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1sourceDeviceType/title",
          "value": "sourceDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1sourceDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1mediaType/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1mediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port/title",
          "value": "AVCaptureInputPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureInputPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureInputPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput/title",
          "value": "AVCaptureInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/title",
          "value": "AVMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1sourceDevicePosition/title",
          "value": "sourceDevicePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1sourceDevicePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceDevicePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1formatDescription/title",
          "value": "formatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput~1Port~1formatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "formatDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureinput/port/mediatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptureinput/port/mediatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
