{
  "abstract": [
    {
      "text": "The transformation matrix that determines the extent of a scene visible to the camera’s left viewpoint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftProjectionMatrix"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLStereoscopicCamera(py)leftProjectionMatrix",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "leftProjectionMatrix"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@matrix_float4x4",
        "text": "matrix_float4x4"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "leftProjectionMatrix"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "leftProjectionMatrix"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "leftProjectionMatrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@matrix_float4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@matrix_float4x4",
              "text": "matrix_float4x4"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Model I/O  automatically generates this matrix from the same properties that produce the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a monocular camera, additionally using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/interPupillaryDistance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftVergence",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to account for the offset and angle of a stereoscopic camera’s left viewpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A renderer uses this matrix, along with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftViewMatrix",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property and model matrices derived from the camera’s position and orientation (the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject/transform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property) and the content to be rendered, to transform vertex data to the renderer’s 2D screen space at render time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix": {
      "abstract": [
        {
          "text": "A transformation matrix that determines the extent of a scene visible to the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        }
      ],
      "role": "symbol",
      "title": "projectionMatrix",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/projectionmatrix"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLObject/transform": {
      "abstract": [
        {
          "text": "A component that manages this object’s spatial transform and its changes over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLTransformComponent",
          "text": "MDLTransformComponent"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject/transform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transform"
        }
      ],
      "role": "symbol",
      "title": "transform",
      "type": "topic",
      "url": "/documentation/modelio/mdlobject/transform"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera": {
      "abstract": [
        {
          "text": "A point of view for rendering a stereoscopic display of a 3D scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLStereoscopicCamera"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLStereoscopicCamera"
        }
      ],
      "role": "symbol",
      "title": "MDLStereoscopicCamera",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/interPupillaryDistance": {
      "abstract": [
        {
          "text": "The distance, in millimeters, between the stereoscopic camera’s two viewpoints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interPupillaryDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/interPupillaryDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interPupillaryDistance"
        }
      ],
      "role": "symbol",
      "title": "interPupillaryDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera/interpupillarydistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftProjectionMatrix": {
      "abstract": [
        {
          "text": "The transformation matrix that determines the extent of a scene visible to the camera’s left viewpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftProjectionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftProjectionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftProjectionMatrix"
        }
      ],
      "role": "symbol",
      "title": "leftProjectionMatrix",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera/leftprojectionmatrix"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftVergence": {
      "abstract": [
        {
          "text": "The angle, in degrees, at which the camera’s left viewpoint faces toward a central focal point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftVergence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftVergence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftVergence"
        }
      ],
      "role": "symbol",
      "title": "leftVergence",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera/leftvergence"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftViewMatrix": {
      "abstract": [
        {
          "text": "The transformation matrix that determines the position and orientation of the camera’s left viewpoint relative to a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftViewMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftViewMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftViewMatrix"
        }
      ],
      "role": "symbol",
      "title": "leftViewMatrix",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera/leftviewmatrix"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightProjectionMatrix": {
      "abstract": [
        {
          "text": "The transformation matrix that determines the extent of a scene visible to the camera’s right viewpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightProjectionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightProjectionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightProjectionMatrix"
        }
      ],
      "role": "symbol",
      "title": "rightProjectionMatrix",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera/rightprojectionmatrix"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightViewMatrix": {
      "abstract": [
        {
          "text": "The transformation matrix that determines the position and orientation of the camera’s right viewpoint relative to a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightViewMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightViewMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightViewMatrix"
        }
      ],
      "role": "symbol",
      "title": "rightViewMatrix",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera/rightviewmatrix"
    },
    "doc://com.externally.resolved.symbol/c:@T@matrix_float4x4": {
      "abstract": [
        {
          "text": "A type alias for a single-precision 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_float4x4"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@matrix_float4x4",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_float4x4",
      "type": "topic",
      "url": "/documentation/simd/matrix_float4x4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Generating-View-and-Projection-Matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftViewMatrix",
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightViewMatrix",
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightProjectionMatrix"
      ],
      "title": "Generating View and Projection Matrices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "leftProjectionMatrix"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftProjectionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Generating-View-and-Projection-Matrices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/leftViewMatrix",
                "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightViewMatrix",
                "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera/rightProjectionMatrix"
              ],
              "title": "Generating View and Projection Matrices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@matrix_float4x4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@matrix_float4x4",
                    "text": "matrix_float4x4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "leftProjectionMatrix"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1rightViewMatrix/title",
          "value": "rightViewMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1rightViewMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightViewMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1rightProjectionMatrix/title",
          "value": "rightProjectionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1rightProjectionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightProjectionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/title",
          "value": "MDLStereoscopicCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLStereoscopicCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLStereoscopicCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1leftViewMatrix/title",
          "value": "leftViewMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1leftViewMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftViewMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1interPupillaryDistance/title",
          "value": "interPupillaryDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1interPupillaryDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interPupillaryDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1leftProjectionMatrix/title",
          "value": "leftProjectionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1leftProjectionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftProjectionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@matrix_float4x4/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_float4x4",
              "text": "simd_float4x4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matrix_float4x4"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1transform/title",
          "value": "transform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1transform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projectionMatrix/title",
          "value": "projectionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projectionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "projectionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1leftVergence/title",
          "value": "leftVergence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera~1leftVergence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftVergence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlstereoscopiccamera/leftprojectionmatrix"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlstereoscopiccamera/leftprojectionmatrix"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
