{
  "abstract": [
    {
      "text": "A value that represents the home key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/home"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValueRemoteKey@HMCharacteristicValueRemoteKeyHome",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "home"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValueRemoteKeyHome"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCharacteristicValueRemoteKey.home"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "home"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey": {
      "abstract": [
        {
          "text": "Values for the state of the remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKey"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKey"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowDown": {
      "abstract": [
        {
          "text": "A value that represents the down-arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowDown"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyArrowDown"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.arrowDown",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/arrowdown"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowLeft": {
      "abstract": [
        {
          "text": "A value that represents the left arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowLeft"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyArrowLeft"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.arrowLeft",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/arrowleft"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowRight": {
      "abstract": [
        {
          "text": "A value that represents the right arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowRight"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyArrowRight"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.arrowRight",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/arrowright"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowUp": {
      "abstract": [
        {
          "text": "A value that represents the up-arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowUp"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyArrowUp"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.arrowUp",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/arrowup"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/back": {
      "abstract": [
        {
          "text": "A value that represents the back key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "back"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/back",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyBack"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.back",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/back"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/exit": {
      "abstract": [
        {
          "text": "A value that represents the exit key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exit"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/exit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyExit"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.exit",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/exit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/fastForward": {
      "abstract": [
        {
          "text": "A value that represents the fast forward key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fastForward"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/fastForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyFastForward"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.fastForward",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/fastforward"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/home": {
      "abstract": [
        {
          "text": "A value that represents the home key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyHome"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.home",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/home"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/info": {
      "abstract": [
        {
          "text": "A value that represents the info key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyInfo"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.info",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/info"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/menu": {
      "abstract": [
        {
          "text": "A value that represents the menu key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyMenu"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.menu",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/menu"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/nextTrack": {
      "abstract": [
        {
          "text": "A value that represents the next track key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextTrack"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/nextTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyNextTrack"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.nextTrack",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/nexttrack"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/pause": {
      "abstract": [
        {
          "text": "A value that represents the pause key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyPause"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.pause",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/pause"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/play": {
      "abstract": [
        {
          "text": "A value that represents the play key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyPlay"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.play",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/play"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/playPause": {
      "abstract": [
        {
          "text": "A value that represents the play pause key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playPause"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/playPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyPlayPause"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.playPause",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/playpause"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/previousTrack": {
      "abstract": [
        {
          "text": "A value that represents the previous track key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousTrack"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/previousTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyPreviousTrack"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.previousTrack",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/previoustrack"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/rewind": {
      "abstract": [
        {
          "text": "A value that represents the rewind key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rewind"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/rewind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueRemoteKeyRewind"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueRemoteKey.rewind",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueremotekey/rewind"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Remote-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowDown",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowLeft",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowRight",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowUp",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/back",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/exit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/fastForward",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/info",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/menu",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/nextTrack",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/pause",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/play",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/playPause",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/previousTrack",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/rewind"
      ],
      "title": "Remote states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValueRemoteKeyHome"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Remote-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowDown",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowLeft",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowRight",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/arrowUp",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/back",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/exit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/fastForward",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/info",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/menu",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/nextTrack",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/pause",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/play",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/playPause",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/previousTrack",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueRemoteKey/rewind"
              ],
              "title": "Remote states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValueRemoteKeyHome"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1exit/title",
          "value": "HMCharacteristicValueRemoteKeyExit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1exit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyExit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1back/title",
          "value": "HMCharacteristicValueRemoteKeyBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1back/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowLeft/title",
          "value": "HMCharacteristicValueRemoteKeyArrowLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyArrowLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowRight/title",
          "value": "HMCharacteristicValueRemoteKeyArrowRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyArrowRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1previousTrack/title",
          "value": "HMCharacteristicValueRemoteKeyPreviousTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1previousTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyPreviousTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1home/title",
          "value": "HMCharacteristicValueRemoteKeyHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1play/title",
          "value": "HMCharacteristicValueRemoteKeyPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowDown/title",
          "value": "HMCharacteristicValueRemoteKeyArrowDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyArrowDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1fastForward/title",
          "value": "HMCharacteristicValueRemoteKeyFastForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1fastForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyFastForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowUp/title",
          "value": "HMCharacteristicValueRemoteKeyArrowUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1arrowUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyArrowUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1rewind/title",
          "value": "HMCharacteristicValueRemoteKeyRewind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1rewind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyRewind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1playPause/title",
          "value": "HMCharacteristicValueRemoteKeyPlayPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1playPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyPlayPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1info/title",
          "value": "HMCharacteristicValueRemoteKeyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1menu/title",
          "value": "HMCharacteristicValueRemoteKeyMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1nextTrack/title",
          "value": "HMCharacteristicValueRemoteKeyNextTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1nextTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyNextTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1pause/title",
          "value": "HMCharacteristicValueRemoteKeyPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKeyPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey/title",
          "value": "HMCharacteristicValueRemoteKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueRemoteKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueRemoteKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvalueremotekey/home"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvalueremotekey/home"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
