{
  "abstract": [
    {
      "text": "The set of Unicode characters covered by the font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/characterSet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSFontCharacterSetAttribute",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "characterSet"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
        "text": "NSFontDescriptor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
        "text": "AttributeName"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontCharacterSetAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "characterSet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "characterSet"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
              "text": "NSFontDescriptor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
              "text": "AttributeName"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this attribute is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nscharacterset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The default value is supplied by the font.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor": {
      "abstract": [
        {
          "text": "A dictionary of attributes that describe a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName": {
      "abstract": [
        {
          "text": "Constants for the names of font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeName"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.AttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/cascadeList": {
      "abstract": [
        {
          "text": "An array, each member of which is a sub-descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cascadeList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/cascadeList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCascadeListAttribute"
        }
      ],
      "role": "symbol",
      "title": "cascadeList",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/cascadelist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/characterSet": {
      "abstract": [
        {
          "text": "The set of Unicode characters covered by the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "characterSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/characterSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCharacterSetAttribute"
        }
      ],
      "role": "symbol",
      "title": "characterSet",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/characterset"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/face": {
      "abstract": [
        {
          "text": "An optional string object that specifies the font face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "face"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/face",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFaceAttribute"
        }
      ],
      "role": "symbol",
      "title": "face",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/face"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/family": {
      "abstract": [
        {
          "text": "An optional string object that specifies the font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "family"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/family",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyAttribute"
        }
      ],
      "role": "symbol",
      "title": "family",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/family"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/featureSettings": {
      "abstract": [
        {
          "text": "An array of dictionaries representing non-default font feature settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/featureSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFeatureSettingsAttribute"
        }
      ],
      "role": "symbol",
      "title": "featureSettings",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/featuresettings"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/fixedAdvance": {
      "abstract": [
        {
          "text": "A floating-point value that overrides the glyph advancement specified by the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedAdvance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/fixedAdvance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFixedAdvanceAttribute"
        }
      ],
      "role": "symbol",
      "title": "fixedAdvance",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/fixedadvance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/matrix": {
      "abstract": [
        {
          "text": "An affine transform that specifies the font’s transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/matrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontMatrixAttribute"
        }
      ],
      "role": "symbol",
      "title": "matrix",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/matrix"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/name": {
      "abstract": [
        {
          "text": "An optional string object that specifies the font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/size": {
      "abstract": [
        {
          "text": "An optional floating-point number that specifies the font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSizeAttribute"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/size"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/traits": {
      "abstract": [
        {
          "text": "A dictionary that fully describes the font traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/traits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTraitsAttribute"
        }
      ],
      "role": "symbol",
      "title": "traits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/traits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/variation": {
      "abstract": [
        {
          "text": "A dictionary that describes the font’s variation axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "variation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/variation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontVariationAttribute"
        }
      ],
      "role": "symbol",
      "title": "variation",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/variation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/visibleName": {
      "abstract": [
        {
          "text": "An optional string object that specifies the font’s visible name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/visibleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontVisibleNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "visibleName",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename/visiblename"
    },
    "doc://com.apple.documentation/documentation/foundation/nscharacterset": {
      "abstract": [
        {
          "text": "An object representing a fixed set of Unicode character values that bridges to a ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSCharacterSet"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscharacterset",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCharacterSet",
      "type": "topic",
      "url": "/documentation/foundation/nscharacterset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/family",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/name",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/face",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/size",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/visibleName",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/matrix",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/variation",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/cascadeList",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/traits",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/fixedAdvance",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/featureSettings"
      ],
      "title": "Font Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontCharacterSetAttribute"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCharacterSetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/family",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/name",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/face",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/size",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/visibleName",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/matrix",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/variation",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/cascadeList",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/traits",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/fixedAdvance",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName/featureSettings"
              ],
              "title": "Font Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
                    "text": "NSFontDescriptorAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontCharacterSetAttribute"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1size/title",
          "value": "NSFontSizeAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSizeAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1matrix/title",
          "value": "NSFontMatrixAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1matrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontMatrixAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1variation/title",
          "value": "NSFontVariationAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1variation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontVariationAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1featureSettings/title",
          "value": "NSFontFeatureSettingsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1featureSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFeatureSettingsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1characterSet/title",
          "value": "NSFontCharacterSetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1characterSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCharacterSetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName/title",
          "value": "NSFontDescriptorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1traits/title",
          "value": "NSFontTraitsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1traits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1family/title",
          "value": "NSFontFamilyAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1family/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1face/title",
          "value": "NSFontFaceAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1face/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFaceAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1cascadeList/title",
          "value": "NSFontCascadeListAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1cascadeList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCascadeListAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1visibleName/title",
          "value": "NSFontVisibleNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1visibleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontVisibleNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1fixedAdvance/title",
          "value": "NSFontFixedAdvanceAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1fixedAdvance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFixedAdvanceAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nscharacterset/abstract",
          "value": [
            {
              "text": "An object representing a fixed set of Unicode character values for use in search operations. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1name/title",
          "value": "NSFontNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontNameAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor/attributename/characterset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor/attributename/characterset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
