{
  "abstract": [
    {
      "text": "Error codes that the app proxy flow API declares.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEAppProxyFlowError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEAppProxyFlowError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain": {
      "abstract": [
        {
          "text": "The domain used for app proxy errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyErrorDomain",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyerrordomain"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct": {
      "abstract": [
        {
          "text": "An error that the app proxy flow encounters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowError"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that the app proxy flow API declares.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/aborted": {
      "abstract": [
        {
          "text": "The flow was aborted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aborted"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/aborted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorAborted"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.aborted",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/aborted"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/datagramTooLarge": {
      "abstract": [
        {
          "text": "A caller attempted to write a datagram that was larger than the socket’s receive window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datagramTooLarge"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/datagramTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorDatagramTooLarge"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.datagramTooLarge",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/datagramtoolarge"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/hostUnreachable": {
      "abstract": [
        {
          "text": "An attempt to reach the remote endpoint of the flow failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostUnreachable"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/hostUnreachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorHostUnreachable"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.hostUnreachable",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/hostunreachable"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/internal": {
      "abstract": [
        {
          "text": "An internal error occurred while handling the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.internal",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/internal"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/invalidArgument": {
      "abstract": [
        {
          "text": "A proxy flow method received an invalid argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/invalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.invalidArgument",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/invalidargument"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/notConnected": {
      "abstract": [
        {
          "text": "The flow is not fully opened.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/notConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorNotConnected"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.notConnected",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/notconnected"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/peerReset": {
      "abstract": [
        {
          "text": "The remote peer closed the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerReset"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/peerReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorPeerReset"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.peerReset",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/peerreset"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/readAlreadyPending": {
      "abstract": [
        {
          "text": "A read operation on the flow is already pending.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAlreadyPending"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/readAlreadyPending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorReadAlreadyPending"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.readAlreadyPending",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/readalreadypending"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/refused": {
      "abstract": [
        {
          "text": "Connecting the flow to its remote endpoint failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refused"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/refused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorRefused"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.refused",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/refused"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/timedOut": {
      "abstract": [
        {
          "text": "The flow timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/timedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowErrorTimedOut"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code.timedOut",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code/timedout"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/notConnected",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/peerReset",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/hostUnreachable",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/invalidArgument",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/aborted",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/refused",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/timedOut",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/internal",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/datagramTooLarge",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/readAlreadyPending"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEAppProxyFlowError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/notConnected",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/peerReset",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/hostUnreachable",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/invalidArgument",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/aborted",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/refused",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/timedOut",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/internal",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/datagramTooLarge",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code/readAlreadyPending"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEAppProxyFlowError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1datagramTooLarge/title",
          "value": "NEAppProxyFlowErrorDatagramTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1datagramTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorDatagramTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyErrorDomain/title",
          "value": "NEAppProxyErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1hostUnreachable/title",
          "value": "NEAppProxyFlowErrorHostUnreachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1hostUnreachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorHostUnreachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1peerReset/title",
          "value": "NEAppProxyFlowErrorPeerReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1peerReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorPeerReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1internal/title",
          "value": "NEAppProxyFlowErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1invalidArgument/title",
          "value": "NEAppProxyFlowErrorInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1invalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1aborted/title",
          "value": "NEAppProxyFlowErrorAborted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1aborted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorAborted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1notConnected/title",
          "value": "NEAppProxyFlowErrorNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1notConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1timedOut/title",
          "value": "NEAppProxyFlowErrorTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1timedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1readAlreadyPending/title",
          "value": "NEAppProxyFlowErrorReadAlreadyPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1readAlreadyPending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorReadAlreadyPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code/title",
          "value": "NEAppProxyFlowError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1refused/title",
          "value": "NEAppProxyFlowErrorRefused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code~1refused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowErrorRefused"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neappproxyflowerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neappproxyflowerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
